var searchData=
[
  ['variable_20actions_0',['Variable actions',['../group__var__action.html',1,'Variable actions'],['../group__var__GetAndSet.html',1,'Variable actions']]],
  ['variable_20types_1',['Variable types',['../group__var__type.html',1,'']]],
  ['variables_2',['Variables',['../group__variables.html',1,'']]],
  ['variables_3',['Input variables',['../group__inputvariable.html',1,'']]],
  ['video_20controls_4',['LibVLC video controls',['../group__libvlc__video.html',1,'']]],
  ['video_20on_20demand_20vod_5',['Video on Demand (VoD)',['../group__vod.html',1,'']]],
  ['video_20output_6',['Video output',['../group__video__output.html',1,'']]],
  ['video_20output_20display_7',['Video output display',['../group__video__display.html',1,'']]],
  ['video_20sub_20pictures_8',['Video sub-pictures',['../group__subpicture.html',1,'']]],
  ['video_20window_9',['Video window',['../group__video__window.html',1,'']]],
  ['vlc_20dialog_10',['VLC dialog',['../group__vlc__dialog.html',1,'']]],
  ['vlc_20dialog_20callbacks_11',['VLC dialog callbacks',['../group__vlc__dialog__impl.html',1,'']]],
  ['vlc_20dialog_20functions_12',['VLC dialog functions',['../group__vlc__dialog__api.html',1,'']]],
  ['vlc_20extension_20dialog_20functions_13',['VLC extension dialog functions',['../group__vlc__dialog__ext.html',1,'']]],
  ['vlc_20objects_14',['VLC objects',['../group__vlc__object.html',1,'']]],
  ['vlc_20playlist_15',['VLC playlist',['../group__playlist.html',1,'']]],
  ['vlc_20playlist_20internals_16',['VLC playlist internals',['../group__playlist__internals.html',1,'']]],
  ['vlc_20renderer_20discovery_17',['VLC renderer discovery',['../group__vlc__renderer.html',1,'']]],
  ['vlc_20renderer_20discovery_20interface_18',['VLC renderer discovery interface',['../group__vlc__renderer__discovery.html',1,'']]],
  ['vlc_20renderer_20items_20returned_20by_20the_20discovery_19',['VLC renderer items returned by the discovery',['../group__vlc__renderer__item.html',1,'']]],
  ['vlc_20renderer_20module_20',['VLC renderer module',['../group__vlc__renderer__discovery__module.html',1,'']]],
  ['vlm_21',['VLM',['../group__libvlc__vlm.html',1,'LibVLC VLM'],['../group__server.html',1,'VLM']]],
  ['vod_22',['Video on Demand (VoD)',['../group__vod.html',1,'']]],
  ['volume_23',['Audio output volume',['../group__audio__volume.html',1,'']]]
];
