var searchData=
[
  ['layer_20security_0',['Transport Layer Security',['../group__tls.html',1,'']]],
  ['layer_20sockets_1',['Transport layer sockets',['../group__transport.html',1,'']]],
  ['legacy_2',['legacy',['../group__libvlc__log__deprecated.html',1,'LibVLC logging (legacy)'],['../group__libvlc__playlist.html',1,'LibVLC playlist (legacy)']]],
  ['library_3',['LibVLC media library',['../group__libvlc__media__library.html',1,'']]],
  ['libvlc_4',['LibVLC',['../group__libvlc.html',1,'']]],
  ['libvlc_20asynchronous_20events_5',['LibVLC asynchronous events',['../group__libvlc__event.html',1,'']]],
  ['libvlc_20audio_20controls_6',['LibVLC audio controls',['../group__libvlc__audio.html',1,'']]],
  ['libvlc_20core_7',['LibVLC core',['../group__libvlc__core.html',1,'']]],
  ['libvlc_20dialog_8',['LibVLC dialog',['../group__libvlc__dialog.html',1,'']]],
  ['libvlc_20error_20handling_9',['LibVLC error handling',['../group__libvlc__error.html',1,'']]],
  ['libvlc_20logging_10',['LibVLC logging',['../group__libvlc__log.html',1,'']]],
  ['libvlc_20logging_20legacy_11',['LibVLC logging (legacy)',['../group__libvlc__log__deprecated.html',1,'']]],
  ['libvlc_20media_12',['LibVLC media',['../group__libvlc__media.html',1,'']]],
  ['libvlc_20media_20discovery_13',['LibVLC media discovery',['../group__libvlc__media__discoverer.html',1,'']]],
  ['libvlc_20media_20library_14',['LibVLC media library',['../group__libvlc__media__library.html',1,'']]],
  ['libvlc_20media_20list_15',['LibVLC media list',['../group__libvlc__media__list.html',1,'']]],
  ['libvlc_20media_20list_20player_16',['LibVLC media list player',['../group__libvlc__media__list__player.html',1,'']]],
  ['libvlc_20media_20player_17',['LibVLC media player',['../group__libvlc__media__player.html',1,'']]],
  ['libvlc_20playlist_20legacy_18',['LibVLC playlist (legacy)',['../group__libvlc__playlist.html',1,'']]],
  ['libvlc_20renderer_20discoverer_19',['LibVLC renderer discoverer',['../group__libvlc__renderer__discoverer.html',1,'']]],
  ['libvlc_20time_20',['LibVLC time',['../group__libvlc__clock.html',1,'']]],
  ['libvlc_20video_20controls_21',['LibVLC video controls',['../group__libvlc__video.html',1,'']]],
  ['libvlc_20vlm_22',['LibVLC VLM',['../group__libvlc__vlm.html',1,'']]],
  ['list_23',['LibVLC media list',['../group__libvlc__media__list.html',1,'']]],
  ['list_20player_24',['LibVLC media list player',['../group__libvlc__media__list__player.html',1,'']]],
  ['live_20streams_25',['Live streams',['../group__http__live.html',1,'']]],
  ['locator_20mrl_26',['Media Resource Locator (MRL)',['../group__mrl.html',1,'']]],
  ['logging_27',['Logging',['../group__messages.html',1,'']]],
  ['logging_28',['LibVLC logging',['../group__libvlc__log.html',1,'']]],
  ['logging_20legacy_29',['LibVLC logging (legacy)',['../group__libvlc__log__deprecated.html',1,'']]]
];
