VLC: src/android/thread.c File Reference
thread.c File Reference
Data Structures
struct vlc_thread
Macros
#define VLC_THREAD_ASSERT(action)
Functions
static void vlc_thread_fatal_print (const char *action, int error, const char *function, const char *file, unsigned line)
void vlc_mutex_init (vlc_mutex_t *p_mutex)
Initializes a fast mutex.
void vlc_mutex_init_recursive (vlc_mutex_t *p_mutex)
Initializes a recursive mutex.
void vlc_mutex_destroy (vlc_mutex_t *p_mutex)
Deinitializes a mutex.
void vlc_assert_locked (vlc_mutex_t *p_mutex)
void vlc_mutex_lock (vlc_mutex_t *p_mutex)
Acquires a mutex.
int vlc_mutex_trylock (vlc_mutex_t *p_mutex)
Tries to acquire a mutex.
void vlc_mutex_unlock (vlc_mutex_t *p_mutex)
Releases a mutex.
vlc_thread_t vlc_thread_self (void)
Thread handle.
void vlc_threads_setup (libvlc_int_t *p_libvlc)
static void clean_detached_thread (void *data)
static void * detached_thread (void *data)
static void finish_joinable_thread (void *data)
static void * joinable_thread (void *data)
static int vlc_clone_attr (vlc_thread_t *th, void *(*entry)(void *), void *data, bool detach)
int vlc_clone (vlc_thread_t *th, void *(*entry)(void *), void *data, int priority)
Creates and starts a new thread.
void vlc_join (vlc_thread_t handle, void **result)
Waits for a thread to complete (if needed), then destroys it.
int vlc_clone_detach (vlc_thread_t *th, void *(*entry)(void *), void *data, int priority)
int vlc_set_priority (vlc_thread_t th, int priority)
void vlc_cancel (vlc_thread_t thread_id)
Marks a thread as cancelled.
int vlc_savecancel (void)
Disables thread cancellation.
void vlc_restorecancel (int state)
Restores the cancellation state.
void vlc_testcancel (void)
Issues an explicit deferred cancellation point.
void vlc_control_cancel (int cmd,...)
Internal handler for thread cancellation.
int vlc_threadvar_create (vlc_threadvar_t *key, void(*destr)(void *))
Allocates a thread-specific variable.
void vlc_threadvar_delete (vlc_threadvar_t *p_tls)
Deallocates a thread-specific variable.
int vlc_threadvar_set (vlc_threadvar_t key, void *value)
Sets a thread-specific variable.
void * vlc_threadvar_get (vlc_threadvar_t key)
Gets the value of a thread-local variable for the calling thread.
mtime_t mdate (void)
Precision monotonic clock.
unsigned vlc_GetCPUCount (void)
Count CPUs.
Variables
static thread_local struct vlc_thread * thread = NULL
Macro Definition Documentation
VLC_THREAD_ASSERT
#define VLC_THREAD_ASSERT (action)
Value:
    do { \
    if (unlikely(val)) { \
        vlc_thread_fatal_print (action, val, __func__, __FILE__, __LINE__); \
        assert (!action); \
    } \
} while(0)
Referenced by vlc_cond_destroy(), vlc_cond_signal(), vlc_cond_timedwait(), vlc_cond_timedwait_daytime(), vlc_cond_wait(), vlc_join(), vlc_join(), vlc_mutex_destroy(), vlc_mutex_lock(), vlc_mutex_trylock(), vlc_mutex_unlock(), vlc_restorecancel(), vlc_rwlock_destroy(), vlc_rwlock_rdlock(), vlc_rwlock_unlock(), vlc_rwlock_wrlock(), vlc_savecancel(), vlc_sem_destroy(), vlc_sem_post(), and vlc_sem_wait().
Function Documentation
clean_detached_thread()
static void clean_detached_thread (void * data) static
References vlc_thread::data, vlc_thread::lock, vlc_mutex_destroy(), and vlc_thread::wait.
Referenced by detached_thread(), and vlc_join().
detached_thread()
static void * detached_thread (void * data) static
References clean_detached_thread(), vlc_thread::data, thread, vlc_cleanup_pop, and vlc_cleanup_push.
Referenced by vlc_clone_attr().
finish_joinable_thread()
static void finish_joinable_thread (void * data) static
References vlc_thread::data, and vlc_sem_post().
Referenced by joinable_thread().
joinable_thread()
static void * joinable_thread (void * data) static
References vlc_thread::data, finish_joinable_thread(), thread, vlc_cleanup_pop, vlc_cleanup_push, and vlc_sem_post().
Referenced by vlc_clone_attr().
vlc_assert_locked()
void vlc_assert_locked (vlc_mutex_t * p_mutex)
Referenced by aout_OutputAssertLocked(), aout_OutputUnlock(), DecoderFixTs(), DecoderUpdateFormatLocked(), DecoderWaitUnblock(), InputItemFindCat(), InputItemVaAddInfo(), playlist_AssertLocked(), RequestVout(), TsPopCmdLocked(), vlc_fifo_DequeueAllUnlocked(), vlc_fifo_DequeueUnlocked(), vlc_fifo_QueueUnlocked(), and VoutVideoFilterStaticNewPicture().
vlc_clone_attr()
static int vlc_clone_attr (vlc_thread_t * th, void *(* entry)(void *), void * data, bool detach) static
References vlc_thread::addr, vlc_thread::data, detached_thread(), vlc_thread::entry, vlc_thread::finished, joinable_thread(), vlc_thread::killable, vlc_thread::killed, vlc_thread::lock, thread, vlc_thread::thread, unlikely, vlc_mutex_init(), vlc_sem_init(), and vlc_thread::wait.
Referenced by vlc_clone(), vlc_clone(), vlc_clone_detach(), and vlc_clone_detach().
vlc_clone_detach()
int vlc_clone_detach (vlc_thread_t * th, void *(* entry)(void *), void * data, int priority)
References vlc_thread::data, and vlc_clone_attr().
Referenced by background_worker_Push().
vlc_set_priority()
int vlc_set_priority (vlc_thread_t th, int priority)
< No error
References VLC_SUCCESS.
Referenced by Run().
vlc_thread_fatal_print()
static void vlc_thread_fatal_print (const char * action, int error, const char * function, const char * file, unsigned line) static
References vlc_thread_id().
vlc_threads_setup()
void vlc_threads_setup (libvlc_int_t * p_libvlc)
Referenced by libvlc_InternalInit(), and mdate_default().
Variable Documentation
thread
thread_local struct vlc_thread* thread = NULL static
Referenced by detached_thread(), input_Close(), joinable_thread(), vlc_clone_attr(), vlc_restorecancel(), vlc_savecancel(), vlc_testcancel(), and vlc_thread_self().