VLC: src/android/specific.c File Reference
specific.c File Reference
Macros
#define GENERIC_DIR_COUNT (VLC_VIDEOS_DIR - VLC_DESKTOP_DIR + 1)
Functions
static char * get_java_string (JNIEnv *env, jclass clazz, const char *psz_name)
void JNI_OnUnload (JavaVM *vm, void *reserved)
jint JNI_OnLoad (JavaVM *vm, void *reserved)
void system_Init (void)
void system_Configure (libvlc_int_t *p_libvlc, int i_argc, const char *const pp_argv[])
static char * config_GetHomeDir (const char *psz_dir, const char *psz_default_dir)
static JNIEnv * get_env (bool *p_detach)
static void release_env (bool b_detach)
static char * config_GetGenericDir (const char *psz_name)
char * config_GetUserDir (vlc_userdir_t type)
char * vlc_getProxyUrl (const char *url)
Determines the network proxy server to use (if any).
Variables
static JavaVM * s_jvm = NULL
static char * ppsz_generic_names [(VLC_VIDEOS_DIR - VLC_DESKTOP_DIR+1)] = {}
struct {
struct {
jclass clazz
jmethodID getExternalStoragePublicDirectory
} Environment
struct {
jmethodID getAbsolutePath
} File
struct {
jclass clazz
jmethodID getProperty
} System
} fields = { .Environment.clazz = NULL }
Macro Definition Documentation
GENERIC_DIR_COUNT
#define GENERIC_DIR_COUNT (VLC_VIDEOS_DIR - VLC_DESKTOP_DIR + 1)
Referenced by JNI_OnLoad(), and JNI_OnUnload().
Function Documentation
config_GetGenericDir()
static char * config_GetGenericDir (const char * psz_name) static
References fields, get_env(), psz_name, release_env(), and strdup().
Referenced by config_GetUserDir().
config_GetHomeDir()
static char * config_GetHomeDir (const char * psz_dir, const char * psz_default_dir) static
References asprintf(), getenv(), strdup(), and vlc_mkdir().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References config_GetGenericDir(), config_GetHomeDir(), ppsz_generic_names, psz_name, VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.
Referenced by ArtCacheGetDirPath(), config_GetConfigFile(), config_OpenConfigFile(), config_PrepareDir(), EsOutSetRecord(), GetDirByItemUIDs(), playlist_MLDump(), playlist_MLLoad(), and vout_snapshot_GetDirectory().
get_env()
static JNIEnv * get_env (bool * p_detach) static
References s_jvm.
Referenced by config_GetGenericDir(), and vlc_getProxyUrl().
get_java_string()
static char * get_java_string (JNIEnv * env, jclass clazz, const char * psz_name) static
References clazz, psz_name, and strdup().
Referenced by JNI_OnLoad().
JNI_OnLoad()
jint JNI_OnLoad (JavaVM * vm, void * reserved)
References clazz, fields, GENERIC_DIR_COUNT, get_java_string(), JNI_OnUnload(), ppsz_generic_names, and s_jvm.
JNI_OnUnload()
void JNI_OnUnload (JavaVM * vm, void * reserved)
References fields, GENERIC_DIR_COUNT, and ppsz_generic_names.
Referenced by JNI_OnLoad().
release_env()
static void release_env (bool b_detach) static
References s_jvm.
Referenced by config_GetGenericDir(), and vlc_getProxyUrl().
system_Configure()
void system_Configure (libvlc_int_t * p_libvlc, int i_argc, const char *const pp_argv[])
References s_jvm, var_Create, var_SetAddress, and VLC_VAR_ADDRESS.
Referenced by libvlc_InternalInit().
system_Init()
void system_Init (void)
Referenced by config_GetLibDir(), and libvlc_InternalInit().
Variable Documentation
clazz
jclass clazz
Referenced by get_java_string(), and JNI_OnLoad().
[struct]
struct { ... } Environment
[struct]
struct { ... } fields
Referenced by config_GetGenericDir(), JNI_OnLoad(), JNI_OnUnload(), and vlc_getProxyUrl().
[struct]
struct { ... } File
getAbsolutePath
jmethodID getAbsolutePath
getExternalStoragePublicDirectory
jmethodID getExternalStoragePublicDirectory
getProperty
jmethodID getProperty
ppsz_generic_names
char* ppsz_generic_names[(VLC_VIDEOS_DIR - VLC_DESKTOP_DIR+1)] = {} static
Referenced by config_GetUserDir(), JNI_OnLoad(), and JNI_OnUnload().
s_jvm
JavaVM* s_jvm = NULL static
Referenced by get_env(), JNI_OnLoad(), release_env(), and system_Configure().
[struct]
struct { ... } System