VLC: src/playlist/art.c File Reference
art.c File Reference
Functions
static void ArtCacheCreateDir (const char *psz_dir)
static char * ArtCacheGetDirPath (const char *psz_arturl, const char *psz_artist, const char *psz_album, const char *psz_title)
static char * ArtCachePath (input_item_t *p_item)
static char * ArtCacheName (input_item_t *p_item, const char *psz_type)
int playlist_FindArtInCache (input_item_t *p_item)
static char * GetDirByItemUIDs (char *psz_uid)
static char * GetFileByItemUID (char *psz_dir, const char *psz_type)
int playlist_FindArtInCacheUsingItemUID (input_item_t *p_item)
int playlist_SaveArt (vlc_object_t *obj, input_item_t *p_item, const void *data, size_t length, const char *psz_type)
Function Documentation
ArtCacheCreateDir()
static void ArtCacheCreateDir (const char * psz_dir) static
References DIR_SEP_CHAR, EMPTY_STR, and vlc_mkdir().
Referenced by ArtCacheName(), and playlist_SaveArt().
ArtCacheGetDirPath()
static char * ArtCacheGetDirPath (const char * psz_arturl, const char * psz_artist, const char * psz_album, const char * psz_title) static
References AddMD5(), asprintf(), config_GetUserDir(), DIR_SEP, EMPTY_STR, EndMD5(), filename_sanitize(), InitMD5(), psz_md5_hash(), strdup(), and VLC_CACHE_DIR.
Referenced by ArtCachePath().
ArtCacheName()
static char * ArtCacheName (input_item_t * p_item, const char * psz_type) static
References ArtCacheCreateDir(), ArtCachePath(), asprintf(), DIR_SEP, filename_sanitize(), psz_ext, strdup(), and unlikely.
Referenced by playlist_SaveArt().
ArtCachePath()
static char * ArtCachePath (input_item_t * p_item) static
References ArtCacheGetDirPath(), EMPTY_STR, input_item_t::lock, input_item_t::p_meta, input_item_t::psz_name, vlc_meta_Album, vlc_meta_Artist, vlc_meta_ArtworkURL, vlc_meta_Get(), vlc_meta_New(), vlc_meta_Title, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ArtCacheName(), and playlist_FindArtInCache().
GetDirByItemUIDs()
static char * GetDirByItemUIDs (char * psz_uid) static
References asprintf(), config_GetUserDir(), DIR_SEP, and VLC_CACHE_DIR.
Referenced by playlist_FindArtInCacheUsingItemUID(), and playlist_SaveArt().
GetFileByItemUID()
static char * GetFileByItemUID (char * psz_dir, const char * psz_type) static
References asprintf(), and DIR_SEP.
Referenced by playlist_FindArtInCacheUsingItemUID(), and playlist_SaveArt().
playlist_FindArtInCache()
int playlist_FindArtInCache (input_item_t * p_item)
< Unspecified error
< Unspecified error
< No error
< Unspecified error
References ArtCachePath(), asprintf(), DIR_SEP, input_item_SetArtURL, VLC_EGENERIC, vlc_opendir(), vlc_path2uri(), vlc_readdir(), and VLC_SUCCESS.
Referenced by input_ExtractAttachmentAndCacheArt(), and SearchByScope().
playlist_FindArtInCacheUsingItemUID()
int playlist_FindArtInCacheUsingItemUID (input_item_t * p_item)
< Unspecified error
< No error
< Unspecified error
References GetDirByItemUIDs(), GetFileByItemUID(), input_item_GetInfo(), input_item_SetArtURL, VLC_EGENERIC, vlc_fopen(), and VLC_SUCCESS.
Referenced by SearchByScope().
playlist_SaveArt()
int playlist_SaveArt (vlc_object_t * obj, input_item_t * p_item, const void * data, size_t length, const char * psz_type)
< Unspecified error
< Unspecified error
< No error
< No error
References ArtCacheCreateDir(), ArtCacheName(), GetDirByItemUIDs(), GetFileByItemUID(), input_item_GetInfo(), input_item_SetArtURL, msg_Dbg, msg_Err, VLC_EGENERIC, vlc_fopen(), vlc_path2uri(), vlc_stat(), vlc_strerror_c(), and VLC_SUCCESS.
Referenced by Downloader(), and input_ExtractAttachmentAndCacheArt().