VLC: src/playlist/art.h File Reference
art.h File Reference
Functions
int playlist_FindArtInCache (input_item_t *)
int playlist_FindArtInCacheUsingItemUID (input_item_t *)
int playlist_SaveArt (vlc_object_t *, input_item_t *, const void *, size_t, const char *psz_type)
Function Documentation
playlist_FindArtInCache()
int playlist_FindArtInCache (input_item_t * p_item)
< Unspecified error
< Unspecified error
< No error
< Unspecified error
References ArtCachePath(), asprintf(), DIR_SEP, input_item_SetArtURL, VLC_EGENERIC, vlc_opendir(), vlc_path2uri(), vlc_readdir(), and VLC_SUCCESS.
Referenced by input_ExtractAttachmentAndCacheArt(), and SearchByScope().
playlist_FindArtInCacheUsingItemUID()
int playlist_FindArtInCacheUsingItemUID (input_item_t * p_item)
< Unspecified error
< No error
< Unspecified error
References GetDirByItemUIDs(), GetFileByItemUID(), input_item_GetInfo(), input_item_SetArtURL, VLC_EGENERIC, vlc_fopen(), and VLC_SUCCESS.
Referenced by SearchByScope().
playlist_SaveArt()
int playlist_SaveArt (vlc_object_t * obj, input_item_t * p_item, const void * data, size_t length, const char * psz_type)
< Unspecified error
< Unspecified error
< No error
< No error
References ArtCacheCreateDir(), ArtCacheName(), GetDirByItemUIDs(), GetFileByItemUID(), input_item_GetInfo(), input_item_SetArtURL, msg_Dbg, msg_Err, VLC_EGENERIC, vlc_fopen(), vlc_path2uri(), vlc_stat(), vlc_strerror_c(), and VLC_SUCCESS.
Referenced by Downloader(), and input_ExtractAttachmentAndCacheArt().