VLC: src/misc/block.c File Reference
block.c File Reference
Macros
#define BLOCK_ALIGN 32
Initial memory alignment of data block.
#define BLOCK_PADDING 32
Initial reserved header and footer size.
#define S_TYPEISSHM(buf) (0)
Functions
static void BlockNoRelease (block_t *b)
static void block_Check (block_t *block)
static void block_Invalidate (block_t *block)
void block_Init (block_t *restrict b, void *buf, size_t size)
static void block_generic_Release (block_t *block)
static void BlockMetaCopy (block_t *restrict out, const block_t *in)
block_t * block_Alloc (size_t size)
Allocates a block.
block_t * block_TryRealloc (block_t *p_block, ssize_t i_prebody, size_t i_body)
block_t * block_Realloc (block_t *block, ssize_t prebody, size_t body)
Reallocates a block.
static void block_heap_Release (block_t *block)
block_t * block_heap_Alloc (void *addr, size_t length)
Wraps heap in a block.
block_t * block_mmap_Alloc (void *addr, size_t length)
Wraps a memory mapping in a block.
block_t * block_shm_Alloc (void *addr, size_t length)
Wraps a System V memory segment in a block.
block_t * block_File (int fd, bool write)
Maps a file handle in memory.
block_t * block_FilePath (const char *path, bool write)
Maps a file in memory.
Macro Definition Documentation
BLOCK_ALIGN
#define BLOCK_ALIGN 32
Initial memory alignment of data block.
Note
This must be a multiple of sizeof(void*) and a power of two. libavcodec AVX optimizations require at least 32-bytes.
Referenced by block_Alloc().
BLOCK_PADDING
#define BLOCK_PADDING 32
Initial reserved header and footer size.
Referenced by block_Alloc().
S_TYPEISSHM
#define S_TYPEISSHM (buf) (0)
Referenced by block_File().
Function Documentation
block_Check()
static void block_Check (block_t * block) static
References BlockNoRelease(), block_t::i_buffer, block_t::i_size, block_t::p_buffer, block_t::p_next, block_t::p_start, and block_t::pf_release.
Referenced by block_Invalidate(), and block_TryRealloc().
block_generic_Release()
static void block_generic_Release (block_t * block) static
References block_Invalidate(), and block_t::p_start.
Referenced by block_Alloc().
block_heap_Release()
static void block_heap_Release (block_t * block) static
References block_Invalidate(), and block_t::p_start.
Referenced by block_heap_Alloc().
block_Init()
void block_Init (block_t *restrict b, void * buf, size_t size)
References BlockNoRelease(), and VLC_TS_INVALID.
Referenced by block_Alloc(), and block_heap_Alloc().
block_Invalidate()
static void block_Invalidate (block_t * block) static
References block_Check(), BlockNoRelease(), block_t::p_next, and block_t::pf_release.
Referenced by block_generic_Release(), and block_heap_Release().
BlockMetaCopy()
static void BlockMetaCopy (block_t *restrict out, const block_t * in) static
References block_t::i_dts, block_t::i_flags, block_t::i_length, block_t::i_nb_samples, block_t::i_pts, and block_t::p_next.
Referenced by block_TryRealloc().
BlockNoRelease()
static void BlockNoRelease (block_t * b) static
Referenced by block_Check(), block_Init(), and block_Invalidate().