VLC: src/text/charset.c File Reference
charset.c File Reference
Functions
double us_strtod (const char *str, char **end)
us_strtod() has the same prototype as ANSI C strtod() but it uses the POSIX/C decimal format, regardless of the current numeric locale.
float us_strtof (const char *str, char **end)
us_strtof() has the same prototype as ANSI C strtof() but it uses the POSIX/C decimal format, regardless of the current numeric locale.
double us_atof (const char *str)
us_atof() has the same prototype as ANSI C atof() but it expects a dot as decimal separator, regardless of the system locale.
int us_vasprintf (char **ret, const char *format, va_list ap)
us_vasprintf() has the same prototype as vasprintf(), but doesn't use the system locale.
int us_asprintf (char **ret, const char *format,...)
us_asprintf() has the same prototype as asprintf(), but doesn't use the system locale.
Function Documentation
us_asprintf()
int us_asprintf (char ** ret, const char * format, ...)
us_asprintf() has the same prototype as asprintf(), but doesn't use the system locale.
References us_vasprintf().
us_atof()
double us_atof (const char * str)
us_atof() has the same prototype as ANSI C atof() but it expects a dot as decimal separator, regardless of the system locale.
References us_strtod().
Referenced by config_ChainParse(), config_LoadCmdLine(), var_OptionParse(), and vlc_audio_replay_gain_MergeFromMeta().
us_strtod()
double us_strtod (const char * str, char ** end)
us_strtod() has the same prototype as ANSI C strtod() but it uses the POSIX/C decimal format, regardless of the current numeric locale.
References freelocale(), LC_NUMERIC_MASK, newlocale(), and uselocale().
Referenced by us_atof().
us_strtof()
float us_strtof (const char * str, char ** end)
us_strtof() has the same prototype as ANSI C strtof() but it uses the POSIX/C decimal format, regardless of the current numeric locale.
References freelocale(), LC_NUMERIC_MASK, newlocale(), strtof(), and uselocale().
us_vasprintf()
int us_vasprintf (char ** ret, const char * format, va_list ap)
us_vasprintf() has the same prototype as vasprintf(), but doesn't use the system locale.
References freelocale(), LC_NUMERIC_MASK, newlocale(), uselocale(), and vasprintf().
Referenced by httpd_MsgAdd(), and us_asprintf().