VLC: src/video_output/chrono.h File Reference
chrono.h File Reference
Data Structures
struct vout_chrono_t
Functions
static void vout_chrono_Init (vout_chrono_t *chrono, int shift, mtime_t avg_initial)
static void vout_chrono_Clean (vout_chrono_t *chrono)
static void vout_chrono_Start (vout_chrono_t *chrono)
static mtime_t vout_chrono_GetHigh (vout_chrono_t *chrono)
static mtime_t vout_chrono_GetLow (vout_chrono_t *chrono)
static void vout_chrono_Stop (vout_chrono_t *chrono)
static void vout_chrono_Reset (vout_chrono_t *chrono)
Function Documentation
vout_chrono_Clean()
static void vout_chrono_Clean (vout_chrono_t * chrono) inline static
References VLC_UNUSED.
Referenced by ThreadClean(), and vout_chrono_Reset().
vout_chrono_GetHigh()
static mtime_t vout_chrono_GetHigh (vout_chrono_t * chrono) inline static
References vout_chrono_t::avg, and vout_chrono_t::var.
Referenced by ThreadDisplayPicture(), and vout_chrono_Stop().
vout_chrono_GetLow()
static mtime_t vout_chrono_GetLow (vout_chrono_t * chrono) inline static
References vout_chrono_t::avg, and vout_chrono_t::var.
vout_chrono_Init()
static void vout_chrono_Init (vout_chrono_t * chrono, int shift, mtime_t avg_initial) inline static
References vout_chrono_t::avg, vout_chrono_t::avg_initial, vout_chrono_t::shift, vout_chrono_t::shift_var, vout_chrono_t::start, vout_chrono_t::var, and VLC_TS_INVALID.
Referenced by ThreadInit(), and vout_chrono_Reset().
vout_chrono_Reset()
static void vout_chrono_Reset (vout_chrono_t * chrono) inline static
References vout_chrono_t::avg_initial, vout_chrono_t::shift, vout_chrono_Clean(), and vout_chrono_Init().
vout_chrono_Start()
static void vout_chrono_Start (vout_chrono_t * chrono) inline static
References mdate(), and vout_chrono_t::start.
Referenced by ThreadDisplayRenderPicture().
vout_chrono_Stop()
static void vout_chrono_Stop (vout_chrono_t * chrono) inline static
References vout_chrono_t::avg, mdate(), vout_chrono_t::shift, vout_chrono_t::shift_var, vout_chrono_t::start, vout_chrono_t::var, VLC_TS_INVALID, and vout_chrono_GetHigh().
Referenced by ThreadDisplayRenderPicture().