VLC: modules/access/http/chunked.c File Reference
chunked.c File Reference
Data Structures
struct vlc_chunked_stream
Functions
static void * vlc_chunked_fatal (struct vlc_chunked_stream *s)
static struct vlc_http_msg * vlc_chunked_wait (struct vlc_http_stream *stream)
static block_t * vlc_chunked_read (struct vlc_http_stream *stream)
static void vlc_chunked_close (struct vlc_http_stream *stream, bool abort)
struct vlc_http_stream * vlc_chunked_open (struct vlc_http_stream *parent, struct vlc_tls *tls)
Variables
static struct vlc_http_stream_cbs vlc_chunked_callbacks
Function Documentation
vlc_chunked_close()
static void vlc_chunked_close (struct vlc_http_stream * stream, bool abort) static
References container_of, vlc_chunked_stream::eof, vlc_chunked_stream::error, vlc_chunked_stream::parent, vlc_chunked_stream::stream, vlc_chunked_fatal(), and vlc_http_stream_close().
vlc_chunked_fatal()
static void * vlc_chunked_fatal (struct vlc_chunked_stream * s) static
References vlc_chunked_stream::error, and vlc_http_error.
Referenced by vlc_chunked_close(), and vlc_chunked_read().
vlc_chunked_read()
static block_t * vlc_chunked_read (struct vlc_http_stream * stream) static
References block_Alloc(), block_Release(), vlc_chunked_stream::chunk_length, container_of, vlc_chunked_stream::eof, vlc_chunked_stream::error, block_t::i_buffer, block_t::p_buffer, vlc_chunked_stream::stream, vlc_chunked_stream::tls, unlikely, vlc_chunked_fatal(), vlc_http_error, vlc_tls_GetLine(), and vlc_tls_Read().
vlc_chunked_wait()
static struct vlc_http_msg * vlc_chunked_wait (struct vlc_http_stream * stream) static
Variable Documentation
vlc_chunked_callbacks
struct vlc_http_stream_cbs vlc_chunked_callbacks static
Initial value:
=
{
    vlc_chunked_wait,
    vlc_chunked_read,
    vlc_chunked_close,
}
Referenced by vlc_chunked_open().