VLC: src/config/cmdline.c File Reference
cmdline.c File Reference
Macros
#define b_ignore_errors (pindex == NULL)
Functions
int config_LoadCmdLine (vlc_object_t *p_this, int i_argc, const char *ppsz_argv[], int *pindex)
Parse command line for configuration options.
Macro Definition Documentation
b_ignore_errors
#define b_ignore_errors (pindex == NULL)
Referenced by config_LoadCmdLine().
Function Documentation
config_LoadCmdLine()
int config_LoadCmdLine (vlc_object_t * p_this, int i_argc, const char * ppsz_argv[], int * pindex)
Parse command line for configuration options.
Now that the module_bank has been initialized, we can dynamically generate the longopts structure used by getops. We have to do it this way because we don't know (and don't want to know) in advance the configuration options used (ie. exported) by each module.
Parameters
p_this object to write command line options as variables to
i_argc number of command line arguments
ppsz_args commandl ine arguments [IN/OUT]
pindex NULL to ignore unknown options, otherwise index of the first non-option argument [OUT]
Returns
0 on success, -1 on error.
References vlc_getopt_s::arg, asprintf(), b_ignore_errors, module_config_t::b_removed, CONFIG_CLASS, config_FindConfig(), CONFIG_ITEM, CONFIG_ITEM_BOOL, CONFIG_ITEM_FLOAT, CONFIG_ITEM_INTEGER, CONFIG_ITEM_STRING, module_value_t::f, vlc_option::flag, vlc_option::has_arg, module_value_t::i, i_type, module_config_t::i_type, vlc_getopt_s::ind, module_config_t::max, module_config_t::min, name, vlc_option::name, vlc_plugin_t::next, vlc_getopt_s::opt, p, module_config_t::psz_name, psz_name, strdup(), strtoll(), us_atof(), vlc_option::val, var_Change, var_Create, var_SetBool, var_SetFloat, var_SetInteger, var_SetString, vlc_alloc(), vlc_getopt_long(), vlc_plugins, VLC_VAR_BOOL, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_SETMINMAX, and VLC_VAR_STRING.