VLC: modules/access/http/connmgr.c File Reference
connmgr.c File Reference
Data Structures
struct vlc_http_mgr
Functions
void vlc_http_err (void *ctx, const char *fmt,...)
void vlc_http_dbg (void *ctx, const char *fmt,...)
vlc_tls_t * vlc_https_connect (vlc_tls_creds_t *creds, const char *name, unsigned port, bool *restrict two)
static char * vlc_http_proxy_find (const char *hostname, unsigned port, bool secure)
static struct vlc_http_conn * vlc_http_mgr_find (struct vlc_http_mgr *mgr, const char *host, unsigned port)
static void vlc_http_mgr_release (struct vlc_http_mgr *mgr, struct vlc_http_conn *conn)
static struct vlc_http_msg * vlc_http_mgr_reuse (struct vlc_http_mgr *mgr, const char *host, unsigned port, const struct vlc_http_msg *req)
static struct vlc_http_msg * vlc_https_request (struct vlc_http_mgr *mgr, const char *host, unsigned port, const struct vlc_http_msg *req)
static struct vlc_http_msg * vlc_http_request (struct vlc_http_mgr *mgr, const char *host, unsigned port, const struct vlc_http_msg *req)
struct vlc_http_msg * vlc_http_mgr_request (struct vlc_http_mgr *mgr, bool https, const char *host, unsigned port, const struct vlc_http_msg *m)
Sends an HTTP request.
struct vlc_http_cookie_jar_t * vlc_http_mgr_get_jar (struct vlc_http_mgr *mgr)
struct vlc_http_mgr * vlc_http_mgr_create (vlc_object_t *obj, struct vlc_http_cookie_jar_t *jar)
Creates an HTTP connection manager.
void vlc_http_mgr_destroy (struct vlc_http_mgr *mgr)
Destroys an HTTP connection manager.
Function Documentation
vlc_http_dbg()
void vlc_http_dbg (void * ctx, const char * fmt, ...)
References VLC_MSG_DBG, and vlc_vaLog().
vlc_http_err()
void vlc_http_err (void * ctx, const char * fmt, ...)
References VLC_MSG_ERR, and vlc_vaLog().
vlc_http_mgr_find()
static struct vlc_http_conn * vlc_http_mgr_find (struct vlc_http_mgr * mgr, const char * host, unsigned port) static
References vlc_http_mgr::conn.
Referenced by vlc_http_mgr_reuse().
vlc_http_mgr_release()
static void vlc_http_mgr_release (struct vlc_http_mgr * mgr, struct vlc_http_conn * conn) static
References vlc_http_mgr::conn, and vlc_http_conn_release().
Referenced by vlc_http_mgr_destroy(), and vlc_http_mgr_reuse().
vlc_http_mgr_reuse()
static struct vlc_http_msg * vlc_http_mgr_reuse (struct vlc_http_mgr * mgr, const char * host, unsigned port, const struct vlc_http_msg * req) static
References vlc_http_mgr_find(), vlc_http_mgr_release(), vlc_http_msg_get_initial(), and vlc_http_stream_open().
Referenced by vlc_http_request(), and vlc_https_request().
vlc_http_proxy_find()
static char * vlc_http_proxy_find (const char * hostname, unsigned port, bool secure) static
References asprintf(), likely, and vlc_getProxyUrl().
Referenced by vlc_http_request(), and vlc_https_request().
vlc_http_request()
static struct vlc_http_msg * vlc_http_request (struct vlc_http_mgr * mgr, const char * host, unsigned port, const struct vlc_http_msg * req) static
References vlc_http_mgr::conn, vlc_http_mgr::creds, vlc_url_t::i_port, vlc_http_mgr::obj, vlc_url_t::psz_host, vlc_h1_request(), vlc_http_conn_release(), vlc_http_mgr_reuse(), vlc_http_msg_get_initial(), vlc_http_proxy_find(), vlc_UrlClean(), and vlc_UrlParse().
Referenced by vlc_http_mgr_request().
vlc_https_connect()
vlc_tls_t * vlc_https_connect (vlc_tls_creds_t * creds, const char * name, unsigned port, bool *restrict two)
References name, and vlc_tls_SocketOpenTLS().
Referenced by vlc_https_connect_proxy(), and vlc_https_request().
vlc_https_request()
static struct vlc_http_msg * vlc_https_request (struct vlc_http_mgr * mgr, const char * host, unsigned port, const struct vlc_http_msg * req) static
References vlc_http_mgr::conn, vlc_http_mgr::creds, vlc_http_mgr::obj, vlc_http_conn::tls, unlikely, vlc_h1_conn_create(), vlc_h2_conn_create(), vlc_http_mgr_reuse(), vlc_http_proxy_find(), vlc_https_connect(), vlc_https_connect_proxy(), vlc_tls_ClientCreate(), and vlc_tls_Close().
Referenced by vlc_http_mgr_request().