VLC: src/video_output/control.h File Reference
control.h File Reference
Data Structures
struct vout_control_cmd_t
struct vout_control_t
Enumerations
enum {
VOUT_CONTROL_INIT , VOUT_CONTROL_CLEAN , VOUT_CONTROL_REINIT , VOUT_CONTROL_CANCEL ,
VOUT_CONTROL_SUBPICTURE , VOUT_CONTROL_FLUSH_SUBPICTURE , VOUT_CONTROL_OSD_TITLE , VOUT_CONTROL_CHANGE_FILTERS ,
VOUT_CONTROL_CHANGE_INTERLACE , VOUT_CONTROL_CHANGE_SUB_SOURCES , VOUT_CONTROL_CHANGE_SUB_FILTERS , VOUT_CONTROL_CHANGE_SUB_MARGIN ,
VOUT_CONTROL_PAUSE , VOUT_CONTROL_FLUSH , VOUT_CONTROL_STEP , VOUT_CONTROL_FULLSCREEN ,
VOUT_CONTROL_WINDOW_STATE , VOUT_CONTROL_WINDOW_MOUSE , VOUT_CONTROL_DISPLAY_FILLED , VOUT_CONTROL_ZOOM ,
VOUT_CONTROL_ASPECT_RATIO , VOUT_CONTROL_CROP_BORDER , VOUT_CONTROL_CROP_RATIO , VOUT_CONTROL_CROP_WINDOW ,
VOUT_CONTROL_VIEWPOINT
}
Functions
void vout_control_cmd_Init (vout_control_cmd_t *, int type)
void vout_control_cmd_Clean (vout_control_cmd_t *)
void vout_control_Init (vout_control_t *)
void vout_control_Clean (vout_control_t *)
void vout_control_WaitEmpty (vout_control_t *)
void vout_control_Push (vout_control_t *, vout_control_cmd_t *)
void vout_control_PushVoid (vout_control_t *, int type)
void vout_control_PushBool (vout_control_t *, int type, bool boolean)
void vout_control_PushInteger (vout_control_t *, int type, int integer)
void vout_control_PushTime (vout_control_t *, int type, mtime_t time)
void vout_control_PushMessage (vout_control_t *, int type, int channel, const char *string)
void vout_control_PushPair (vout_control_t *, int type, int a, int b)
void vout_control_PushString (vout_control_t *, int type, const char *string)
void vout_control_Wake (vout_control_t *)
int vout_control_Pop (vout_control_t *, vout_control_cmd_t *, mtime_t deadline)
void vout_control_Dead (vout_control_t *)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VOUT_CONTROL_INIT
VOUT_CONTROL_CLEAN
VOUT_CONTROL_REINIT
VOUT_CONTROL_CANCEL
VOUT_CONTROL_SUBPICTURE
VOUT_CONTROL_FLUSH_SUBPICTURE
VOUT_CONTROL_OSD_TITLE
VOUT_CONTROL_CHANGE_FILTERS
VOUT_CONTROL_CHANGE_INTERLACE
VOUT_CONTROL_CHANGE_SUB_SOURCES
VOUT_CONTROL_CHANGE_SUB_FILTERS
VOUT_CONTROL_CHANGE_SUB_MARGIN
VOUT_CONTROL_PAUSE
VOUT_CONTROL_FLUSH
VOUT_CONTROL_STEP
VOUT_CONTROL_FULLSCREEN
VOUT_CONTROL_WINDOW_STATE
VOUT_CONTROL_WINDOW_MOUSE
VOUT_CONTROL_DISPLAY_FILLED
VOUT_CONTROL_ZOOM
VOUT_CONTROL_ASPECT_RATIO
VOUT_CONTROL_CROP_BORDER
VOUT_CONTROL_CROP_RATIO
VOUT_CONTROL_CROP_WINDOW
VOUT_CONTROL_VIEWPOINT
Function Documentation
vout_control_Clean()
void vout_control_Clean (vout_control_t * ctrl)
References ARRAY_RESET, ARRAY_VAL, vout_control_t::cmd, vout_control_t::i_size, vout_control_t::lock, vlc_cond_destroy(), vlc_mutex_destroy(), vout_control_cmd_Clean(), vout_control_t::wait_acknowledge, and vout_control_t::wait_request.
Referenced by VoutDestructor().
vout_control_cmd_Clean()
void vout_control_cmd_Clean (vout_control_cmd_t * cmd)
References vout_control_cmd_t::string, vout_control_cmd_t::subpicture, subpicture_Delete(), vout_control_cmd_t::type, vout_control_cmd_t::u, VOUT_CONTROL_CHANGE_FILTERS, VOUT_CONTROL_CHANGE_SUB_FILTERS, VOUT_CONTROL_CHANGE_SUB_SOURCES, VOUT_CONTROL_OSD_TITLE, and VOUT_CONTROL_SUBPICTURE.
Referenced by ThreadControl(), vout_control_Clean(), and vout_control_Push().
vout_control_cmd_Init()
void vout_control_cmd_Init (vout_control_cmd_t * cmd, int type)
References vout_control_cmd_t::type.
Referenced by vout_ChangePause(), vout_control_PushBool(), vout_control_PushInteger(), vout_control_PushMessage(), vout_control_PushPair(), vout_control_PushString(), vout_control_PushTime(), vout_control_PushVoid(), vout_ControlChangeCropBorder(), vout_ControlChangeCropWindow(), vout_ControlChangeViewpoint(), vout_NextPicture(), vout_PutSubpicture(), vout_Request(), and vout_WindowMouseEvent().
vout_control_Dead()
void vout_control_Dead (vout_control_t * ctrl)
References vout_control_t::is_dead, vout_control_t::lock, vlc_cond_broadcast(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_control_t::wait_acknowledge.
Referenced by ThreadClean().
vout_control_Init()
void vout_control_Init (vout_control_t * ctrl)
References ARRAY_INIT, vout_control_t::can_sleep, vout_control_t::cmd, vout_control_t::is_dead, vout_control_t::is_processing, vout_control_t::lock, vlc_cond_init(), vlc_mutex_init(), vout_control_t::wait_acknowledge, and vout_control_t::wait_request.
Referenced by VoutCreate().
vout_control_Pop()
int vout_control_Pop (vout_control_t * ctrl, vout_control_cmd_t * cmd, mtime_t deadline)
< No error
< Unspecified error
References ARRAY_REMOVE, ARRAY_VAL, vout_control_t::can_sleep, vout_control_t::cmd, vout_control_t::i_size, vout_control_t::is_processing, vout_control_t::lock, vlc_cond_broadcast(), vlc_cond_timedwait(), VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, VLC_TS_INVALID, vout_control_t::wait_acknowledge, and vout_control_t::wait_request.
Referenced by Thread().
vout_control_Push()
void vout_control_Push (vout_control_t * ctrl, vout_control_cmd_t * cmd)
References ARRAY_APPEND, vout_control_t::cmd, vout_control_t::is_dead, vout_control_t::lock, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), vout_control_cmd_Clean(), and vout_control_t::wait_request.
Referenced by vout_ChangePause(), vout_control_PushBool(), vout_control_PushInteger(), vout_control_PushMessage(), vout_control_PushPair(), vout_control_PushString(), vout_control_PushTime(), vout_control_PushVoid(), vout_ControlChangeCropBorder(), vout_ControlChangeCropWindow(), vout_ControlChangeViewpoint(), vout_NextPicture(), vout_PutSubpicture(), vout_Request(), and vout_WindowMouseEvent().
vout_control_PushBool()
void vout_control_PushBool (vout_control_t * ctrl, int type, bool boolean)
References vout_control_cmd_t::boolean, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
Referenced by DeinterlaceCallback(), vout_Cancel(), vout_ControlChangeDisplayFilled(), and vout_ControlChangeFullscreen().
vout_control_PushInteger()
void vout_control_PushInteger (vout_control_t * ctrl, int type, int integer)
References vout_control_cmd_t::integer, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
Referenced by vout_ControlChangeSubMargin(), vout_ControlChangeWindowState(), and vout_FlushSubpictureChannel().
vout_control_PushMessage()
void vout_control_PushMessage (vout_control_t * ctrl, int type, int channel, const char * string)
References vout_control_cmd_t::channel, vout_control_cmd_t::message, strdup(), vout_control_cmd_t::string, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
vout_control_PushPair()
void vout_control_PushPair (vout_control_t * ctrl, int type, int a, int b)
References vout_control_cmd_t::a, vout_control_cmd_t::b, vout_control_cmd_t::pair, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
Referenced by vout_ControlChangeCropRatio(), vout_ControlChangeSampleAspectRatio(), and vout_ControlChangeZoom().
vout_control_PushString()
void vout_control_PushString (vout_control_t * ctrl, int type, const char * string)
References strdup(), vout_control_cmd_t::string, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
Referenced by vout_ControlChangeFilters(), vout_ControlChangeSubFilters(), vout_ControlChangeSubSources(), and vout_DisplayTitle().
vout_control_PushTime()
void vout_control_PushTime (vout_control_t * ctrl, int type, mtime_t time)
References vout_control_cmd_t::time, vout_control_cmd_t::u, vout_control_cmd_Init(), and vout_control_Push().
Referenced by vout_Flush().
vout_control_PushVoid()
void vout_control_PushVoid (vout_control_t * ctrl, int type)
References vout_control_cmd_Init(), and vout_control_Push().
Referenced by vout_Close(), and VoutCreate().
vout_control_WaitEmpty()
void vout_control_WaitEmpty (vout_control_t * ctrl)
References vout_control_t::cmd, vout_control_t::i_size, vout_control_t::is_dead, vout_control_t::is_processing, vout_control_t::lock, vlc_cond_wait(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_control_t::wait_acknowledge.
Referenced by vout_Cancel(), vout_ChangePause(), vout_Flush(), vout_NextPicture(), vout_Request(), and VoutCreate().
vout_control_Wake()
void vout_control_Wake (vout_control_t * ctrl)
References vout_control_t::can_sleep, vout_control_t::lock, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_control_t::wait_request.
Referenced by vout_PutPicture().