VLC: src/config/core.c File Reference
core.c File Reference
Functions
static char * strdupnull (const char *src)
int config_GetType (const char *psz_name)
bool config_IsSafe (const char *name)
int64_t config_GetInt (vlc_object_t *p_this, const char *psz_name)
float config_GetFloat (vlc_object_t *p_this, const char *psz_name)
char * config_GetPsz (vlc_object_t *p_this, const char *psz_name)
void config_PutPsz (vlc_object_t *p_this, const char *psz_name, const char *psz_value)
void config_PutInt (vlc_object_t *p_this, const char *psz_name, int64_t i_value)
void config_PutFloat (vlc_object_t *p_this, const char *psz_name, float f_value)
ssize_t config_GetIntChoices (vlc_object_t *obj, const char *name, int64_t **restrict values, char ***restrict texts)
Determines a list of suggested values for an integer configuration item.
static ssize_t config_ListModules (const char *cap, char ***restrict values, char ***restrict texts)
ssize_t config_GetPszChoices (vlc_object_t *obj, const char *name, char ***restrict values, char ***restrict texts)
Determines a list of suggested values for a string configuration item.
static int confcmp (const void *a, const void *b)
static int confnamecmp (const void *key, const void *elem)
int config_SortConfig (void)
Index the configuration items by name for faster lookups.
void config_UnsortConfig (void)
module_config_t * config_FindConfig (const char *name)
void config_Free (module_config_t *tab, size_t confsize)
Destroys an array of configuration items.
void config_ResetAll (vlc_object_t *p_this)
Variables
vlc_rwlock_t config_lock = PTHREAD_RWLOCK_INITIALIZER
bool config_dirty = false
struct {
module_config_t ** list
size_t count
} config = { NULL, 0 }
Function Documentation
confcmp()
static int confcmp (const void * a, const void * b) static
Referenced by config_SortConfig().
config_FindConfig()
module_config_t * config_FindConfig (const char * name)
References config, confnamecmp(), name, p, and unlikely.
Referenced by aout_New(), config_ChainParse(), config_GetFloat(), config_GetInt(), config_GetIntChoices(), config_GetPsz(), config_GetPszChoices(), config_GetType(), config_IsSafe(), config_LoadCmdLine(), config_LoadConfigFile(), config_PutFloat(), config_PutInt(), config_PutPsz(), and vout_InitInterlacingSupport().
config_Free()
void config_Free (module_config_t * tab, size_t confsize)
Destroys an array of configuration items.
Parameters
config start of array of items
confsize number of items in the array
References module_config_t::i_type, IsConfigStringType, module_config_t::list, module_config_t::list_count, module_config_t::list_text, module_config_t::psz, module_value_t::psz, and module_config_t::value.
Referenced by vlc_plugin_destroy().
config_GetFloat()
float config_GetFloat (vlc_object_t * p_this, const char * psz_name)
References config_FindConfig(), config_lock, module_value_t::f, module_config_t::i_type, IsConfigFloatType, msg_Err, psz_name, module_config_t::value, vlc_rwlock_rdlock(), and vlc_rwlock_unlock().
config_GetInt()
int64_t config_GetInt (vlc_object_t * p_this, const char * psz_name)
References config_FindConfig(), config_lock, module_value_t::i, module_config_t::i_type, IsConfigIntegerType, msg_Err, psz_name, module_config_t::value, vlc_rwlock_rdlock(), and vlc_rwlock_unlock().
config_GetIntChoices()
ssize_t config_GetIntChoices (vlc_object_t * obj, const char * name, int64_t **restrict values, char ***restrict texts)
Determines a list of suggested values for an integer configuration item.
Parameters
values pointer to a table of integer values [OUT]
texts pointer to a table of descriptions strings [OUT]
Returns
number of choices, or -1 on error
Note
the caller is responsible for calling free() on all descriptions and on both tables. In case of error, both pointers are set to NULL.
References config_FindConfig(), count, module_config_t::i, module_config_t::i_cb, module_config_t::list, module_config_t::list_count, module_config_t::list_text, module_Map(), msg_Warn, name, module_config_t::owner, strdup(), unlikely, vlc_alloc(), and vlc_gettext().
Referenced by print_item().
config_GetPsz()
char * config_GetPsz (vlc_object_t * p_this, const char * psz_name)
References config_FindConfig(), config_lock, module_config_t::i_type, IsConfigStringType, msg_Err, module_value_t::psz, psz_name, psz_value, strdupnull(), module_config_t::value, vlc_rwlock_rdlock(), and vlc_rwlock_unlock().
config_GetPszChoices()
ssize_t config_GetPszChoices (vlc_object_t * obj, const char * name, char ***restrict values, char ***restrict texts)
Determines a list of suggested values for a string configuration item.
Parameters
values pointer to a table of value strings [OUT]
texts pointer to a table of descriptions strings [OUT]
Returns
number of choices, or -1 on error
Note
the caller is responsible for calling free() on all values, on all descriptions and on both tables. In case of error, both pointers are set to NULL.
References config_FindConfig(), CONFIG_ITEM_MODULE, config_ListModules(), count, module_config_t::i_type, IsConfigStringType, module_config_t::list, module_config_t::list_count, module_config_t::list_text, module_Map(), name, module_config_t::owner, module_config_t::psz, module_config_t::psz_cb, module_config_t::psz_type, vlc_gettext(), xmalloc(), and xstrdup().
Referenced by print_item().
config_GetType()
int config_GetType (const char * psz_name)
References CONFIG_CLASS, config_FindConfig(), CONFIG_ITEM_BOOL, CONFIG_ITEM_FLOAT, CONFIG_ITEM_INTEGER, CONFIG_ITEM_STRING, module_config_t::i_type, psz_name, VLC_VAR_BOOL, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_STRING.
Referenced by config_ChainParse(), and var_OptionParse().
config_IsSafe()
bool config_IsSafe (const char * name)
References module_config_t::b_safe, config_FindConfig(), and name.
Referenced by var_OptionParse().
config_ListModules()
static ssize_t config_ListModules (const char * cap, char ***restrict values, char ***restrict texts) static
References _, list, module_get_name(), module_get_object(), module_gettext(), module_list_cap(), module_list_free(), unlikely, xmalloc(), and xstrdup().
Referenced by config_GetPszChoices().
config_PutFloat()
void config_PutFloat (vlc_object_t * p_this, const char * psz_name, float f_value)
References config_dirty, config_FindConfig(), config_lock, module_value_t::f, f_value, module_config_t::i_type, IsConfigFloatType, module_config_t::max, module_config_t::min, msg_Warn, psz_name, module_config_t::value, vlc_rwlock_unlock(), and vlc_rwlock_wrlock().
config_PutInt()
void config_PutInt (vlc_object_t * p_this, const char * psz_name, int64_t i_value)
References config_dirty, config_FindConfig(), config_lock, module_value_t::i, module_config_t::i_type, i_value, IsConfigIntegerType, module_config_t::max, module_config_t::min, msg_Warn, psz_name, module_config_t::value, vlc_rwlock_unlock(), and vlc_rwlock_wrlock().
config_PutPsz()
void config_PutPsz (vlc_object_t * p_this, const char * psz_name, const char * psz_value)
References config_dirty, config_FindConfig(), config_lock, module_config_t::i_type, IsConfigStringType, msg_Warn, module_value_t::psz, psz_name, psz_value, strdup(), module_config_t::value, vlc_rwlock_unlock(), and vlc_rwlock_wrlock().
config_ResetAll()
void config_ResetAll (vlc_object_t * p_this)
References config_lock, module_value_t::f, module_value_t::i, module_config_t::i_type, IsConfigFloatType, IsConfigIntegerType, IsConfigStringType, vlc_plugin_t::next, module_config_t::orig, p, module_value_t::psz, strdupnull(), module_config_t::value, vlc_plugins, vlc_rwlock_unlock(), vlc_rwlock_wrlock(), and VLC_UNUSED.
config_SortConfig()
int config_SortConfig (void)
Index the configuration items by name for faster lookups.
< Not enough memory
< No error
References vlc_plugin_t::conf, confcmp(), config, CONFIG_ITEM, module_config_t::i_type, vlc_plugin_t::next, p, vlc_plugin_t::size, unlikely, vlc_alloc(), VLC_ENOMEM, vlc_plugins, and VLC_SUCCESS.
Referenced by module_InitBank(), and module_LoadPlugins().
config_UnsortConfig()
void config_UnsortConfig (void)
References config, and module_config_t::list.
Referenced by module_EndBank(), and module_LoadPlugins().
confnamecmp()
static int confnamecmp (const void * key, const void * elem) static
Referenced by config_FindConfig().
strdupnull()
static char * strdupnull (const char * src) inline static
References strdup().
Referenced by config_GetPsz(), and config_ResetAll().
Variable Documentation
[struct]
struct { ... } config
Referenced by config_FindConfig(), config_SortConfig(), config_UnsortConfig(), module_config_free(), and module_config_get().
config_dirty
bool config_dirty = false
Referenced by config_AutoSaveConfigFile(), config_PutFloat(), config_PutInt(), and config_PutPsz().
config_lock
vlc_rwlock_t config_lock = PTHREAD_RWLOCK_INITIALIZER
Referenced by _DLL_InitTerm(), config_AutoSaveConfigFile(), config_GetFloat(), config_GetInt(), config_GetPsz(), config_LoadConfigFile(), config_PutFloat(), config_PutInt(), config_PutPsz(), config_ResetAll(), config_SaveConfigFile(), and DllMain().
count
size_t count
Referenced by aout_FiltersPipelineChangeViewpoint(), aout_FiltersPipelineCreate(), aout_FiltersPipelineDrain(), aout_FiltersPipelineFlush(), aout_FiltersPipelinePlay(), config_GetIntChoices(), config_GetPszChoices(), EsOutControlLocked(), hpack_decode(), hpack_encode(), input_EsOutTimeshiftNew(), input_SlaveSourceAdd(), input_vaControl(), InputSourceNew(), ListModules(), module_find(), module_LoadPlugins(), picture_pool_New(), picture_pool_NewFromFormat(), picture_pool_Reserve(), popcount(), popcountll(), SeekpointCallback(), SplitterPool(), SpuRenderSubpictures(), stream_extractor_AttachParsed(), TitleCallback(), TriggerCallback(), TriggerListCallback(), var_CountChoices(), vlc_alloc(), vlc_dictionary_all_keys(), vlc_dictionary_insert_impl_(), vlc_dictionary_keys_count(), vlc_GetCPUCount(), vlc_h2_frame_headers(), vlc_h2_stream_headers(), vlc_https_recv(), vlc_https_send(), vlc_list_children(), vlc_rand_bytes(), vlc_read_i11e(), vlc_readv_i11e(), vlc_sd_GetNames(), vlc_timer_do(), vlc_tls_ConnectWrite(), vlc_tls_ProxyRead(), vlc_tls_ProxyWrite(), vlc_tls_SocketRead(), vlc_tls_SocketWrite(), vlc_write_i11e(), vlc_writev(), vlc_writev_i11e(), and vout_display_Pool().
list
module_config_t** list
Referenced by config_ListModules(), InitPrograms(), input_SlaveSourceAdd(), InputSourceNew(), ListModules(), module_find(), module_list_cap(), module_list_free(), module_LoadPlugins(), and process_list().