VLC: src/darwin/thread.c File Reference
thread.c File Reference
Macros
#define vlc_clock_setup() pthread_once(&vlc_clock_once, vlc_clock_setup_once)
#define VLC_THREAD_ASSERT(action)
#define RUNNING_ON_VALGRIND (0)
#define VLC_STACKSIZE (128 * sizeof (void *) * 1024)
Functions
static void vlc_clock_setup_once (void)
static struct timespec mtime_to_ts (mtime_t date)
void vlc_trace (const char *fn, const char *file, unsigned line)
static void vlc_thread_fatal (const char *action, int error, const char *function, const char *file, unsigned line)
void vlc_mutex_init (vlc_mutex_t *p_mutex)
Initializes a fast mutex.
void vlc_mutex_init_recursive (vlc_mutex_t *p_mutex)
Initializes a recursive mutex.
void vlc_mutex_destroy (vlc_mutex_t *p_mutex)
Deinitializes a mutex.
void vlc_assert_locked (vlc_mutex_t *p_mutex)
void vlc_mutex_lock (vlc_mutex_t *p_mutex)
Acquires a mutex.
int vlc_mutex_trylock (vlc_mutex_t *p_mutex)
Tries to acquire a mutex.
void vlc_mutex_unlock (vlc_mutex_t *p_mutex)
Releases a mutex.
void vlc_cond_init (vlc_cond_t *p_condvar)
Initializes a condition variable.
void vlc_cond_init_daytime (vlc_cond_t *p_condvar)
Initializes a condition variable (wall clock).
void vlc_cond_destroy (vlc_cond_t *p_condvar)
Deinitializes a condition variable.
void vlc_cond_signal (vlc_cond_t *p_condvar)
Wakes up one thread waiting on a condition variable.
void vlc_cond_broadcast (vlc_cond_t *p_condvar)
Wakes up all threads waiting on a condition variable.
void vlc_cond_wait (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex)
Waits on a condition variable.
int vlc_cond_timedwait (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex, mtime_t deadline)
Waits on a condition variable up to a certain date.
int vlc_cond_timedwait_daytime (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex, time_t deadline)
void vlc_sem_init (vlc_sem_t *sem, unsigned value)
Initializes a semaphore.
void vlc_sem_destroy (vlc_sem_t *sem)
Deinitializes a semaphore.
int vlc_sem_post (vlc_sem_t *sem)
Increments the value of a semaphore.
void vlc_sem_wait (vlc_sem_t *sem)
Waits on a semaphore.
void vlc_rwlock_init (vlc_rwlock_t *lock)
Initializes a read/write lock.
void vlc_rwlock_destroy (vlc_rwlock_t *lock)
Destroys an initialized unused read/write lock.
void vlc_rwlock_rdlock (vlc_rwlock_t *lock)
Acquires a read/write lock for reading.
void vlc_rwlock_wrlock (vlc_rwlock_t *lock)
Acquires a read/write lock for writing.
void vlc_rwlock_unlock (vlc_rwlock_t *lock)
Releases a read/write lock.
int vlc_threadvar_create (vlc_threadvar_t *key, void(*destr)(void *))
Allocates a thread-specific variable.
void vlc_threadvar_delete (vlc_threadvar_t *p_tls)
Deallocates a thread-specific variable.
int vlc_threadvar_set (vlc_threadvar_t key, void *value)
Sets a thread-specific variable.
void * vlc_threadvar_get (vlc_threadvar_t key)
Gets the value of a thread-local variable for the calling thread.
void vlc_threads_setup (libvlc_int_t *p_libvlc)
static int vlc_clone_attr (vlc_thread_t *th, pthread_attr_t *attr, void *(*entry)(void *), void *data, int priority)
int vlc_clone (vlc_thread_t *th, void *(*entry)(void *), void *data, int priority)
Creates and starts a new thread.
void vlc_join (vlc_thread_t handle, void **result)
Waits for a thread to complete (if needed), then destroys it.
int vlc_clone_detach (vlc_thread_t *th, void *(*entry)(void *), void *data, int priority)
vlc_thread_t vlc_thread_self (void)
Thread handle.
unsigned long vlc_thread_id (void)
Thread identifier.
int vlc_set_priority (vlc_thread_t th, int priority)
void vlc_cancel (vlc_thread_t thread_id)
Marks a thread as cancelled.
int vlc_savecancel (void)
Disables thread cancellation.
void vlc_restorecancel (int state)
Restores the cancellation state.
void vlc_testcancel (void)
Issues an explicit deferred cancellation point.
void vlc_control_cancel (int cmd,...)
Internal handler for thread cancellation.
mtime_t mdate (void)
Precision monotonic clock.
void mwait (mtime_t deadline)
void msleep (mtime_t delay)
unsigned vlc_GetCPUCount (void)
Count CPUs.
Variables
static mach_timebase_info_data_t vlc_clock_conversion_factor
static pthread_once_t vlc_clock_once = PTHREAD_ONCE_INIT
Macro Definition Documentation
RUNNING_ON_VALGRIND
#define RUNNING_ON_VALGRIND (0)
Referenced by module_Unload(), and vlc_assert_locked().
vlc_clock_setup
#define vlc_clock_setup () pthread_once(&vlc_clock_once, vlc_clock_setup_once)
Referenced by mdate(), msleep(), mwait(), and vlc_cond_init().
VLC_STACKSIZE
#define VLC_STACKSIZE (128 * sizeof (void *) * 1024)
Referenced by vlc_clone_attr().
VLC_THREAD_ASSERT
#define VLC_THREAD_ASSERT (action)
Value:
    if (unlikely(val)) \
        vlc_thread_fatal (action, val, __func__, __FILE__, __LINE__)
Function Documentation
msleep()
void msleep (mtime_t delay)
References mtime_to_ts().
mtime_to_ts()
static struct timespec mtime_to_ts (mtime_t date) static
References CLOCK_FREQ, and lldiv().
Referenced by msleep(), mwait(), vlc_cond_timedwait(), and vlc_cond_timedwait_daytime().
mwait()
void mwait (mtime_t deadline)
References mdate(), and msleep.
vlc_assert_locked()
void vlc_assert_locked (vlc_mutex_t * p_mutex)
References RUNNING_ON_VALGRIND.
vlc_clock_setup_once()
static void vlc_clock_setup_once (void) static
References unlikely, and vlc_clock_conversion_factor.
vlc_clone_attr()
static int vlc_clone_attr (vlc_thread_t * th, pthread_attr_t * attr, void *(* entry)(void *), void * data, int priority) static
References VLC_STACKSIZE.
vlc_clone_detach()
int vlc_clone_detach (vlc_thread_t * th, void *(* entry)(void *), void * data, int priority)
References vlc_clone_attr().
vlc_set_priority()
int vlc_set_priority (vlc_thread_t th, int priority)
< No error
References VLC_SUCCESS.
vlc_thread_fatal()
static void vlc_thread_fatal (const char * action, int error, const char * function, const char * file, unsigned line) static
References vlc_restorecancel(), vlc_savecancel(), vlc_thread_id(), and vlc_trace().
Referenced by vlc_restorecancel().
vlc_threads_setup()
void vlc_threads_setup (libvlc_int_t * p_libvlc)
vlc_trace()
void vlc_trace (const char * fn, const char * file, unsigned line)
References fsync().
Referenced by vlc_thread_fatal().
Variable Documentation
vlc_clock_conversion_factor
mach_timebase_info_data_t vlc_clock_conversion_factor static
Referenced by mdate(), and vlc_clock_setup_once().
vlc_clock_once
pthread_once_t vlc_clock_once = PTHREAD_ONCE_INIT static