VLC: src/darwin/dirs.c File Reference
dirs.c File Reference
Functions
char * config_GetLibDir (void)
char * config_GetDataDir (void)
static char * config_GetHomeDir (void)
static char * getAppDependentDir (vlc_userdir_t type)
char * config_GetUserDir (vlc_userdir_t type)
Function Documentation
config_GetDataDir()
char * config_GetDataDir (void)
References asprintf(), config_GetLibDir(), getenv(), and strdup().
Referenced by GetDefaultArtUri(), and vlc_bindtextdomain().
config_GetHomeDir()
static char * config_GetHomeDir (void) static
References getenv(), and strdup().
Referenced by config_GetAppDir(), config_GetUserDir(), and getAppDependentDir().
config_GetLibDir()
char * config_GetLibDir (void)
References asprintf(), p, strdup(), and system_Init().
Referenced by config_GetDataDir(), config_GetHomeDir(), and config_GetLibDir().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References asprintf(), config_GetHomeDir(), getAppDependentDir(), VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.
Referenced by config_GetUserDir().
getAppDependentDir()
static char * getAppDependentDir (vlc_userdir_t type) static
References asprintf(), config_GetHomeDir(), name, vlc_assert_unreachable, VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, and VLC_TEMPLATES_DIR.
Referenced by config_GetUserDir().