VLC: src/input/decoder.c File Reference
decoder.c File Reference
Data Structures
struct decoder_owner_sys_t
Macros
#define MAX_CC_DECODERS 64 /* The es_out only creates one type of es */
#define DECODER_BOGUS_VIDEO_DELAY ((mtime_t)(DEFAULT_PTS_DELAY * 30))
#define DECODER_SPU_VOUT_WAIT_DURATION ((int)(0.200*CLOCK_FREQ))
#define BLOCK_FLAG_CORE_PRIVATE_RELOADED (1 << BLOCK_FLAG_CORE_PRIVATE_SHIFT)
Enumerations
enum reload { RELOAD_NO_REQUEST , RELOAD_DECODER , RELOAD_DECODER_AOUT }
Functions
static int LoadDecoder (decoder_t *p_dec, bool b_packetizer, const es_format_t *restrict p_fmt)
Load a decoder module.
static void UnloadDecoder (decoder_t *p_dec)
Unload a decoder module.
static int ReloadDecoder (decoder_t *p_dec, bool b_packetizer, const es_format_t *restrict p_fmt, enum reload reload)
static void DecoderUpdateFormatLocked (decoder_t *p_dec)
static vout_thread_t * aout_request_vout (void *p_private, vout_thread_t *p_vout, const video_format_t *p_fmt, bool b_recyle)
static bool aout_replaygain_changed (const audio_replay_gain_t *a, const audio_replay_gain_t *b)
static int aout_update_format (decoder_t *p_dec)
static int vout_update_format (decoder_t *p_dec)
static picture_t * vout_new_buffer (decoder_t *p_dec)
static subpicture_t * spu_new_buffer (decoder_t *p_dec, const subpicture_updater_t *p_updater)
static int DecoderGetInputAttachments (decoder_t *p_dec, input_attachment_t ***ppp_attachment, int *pi_attachment)
static mtime_t DecoderGetDisplayDate (decoder_t *p_dec, mtime_t i_ts)
static int DecoderGetDisplayRate (decoder_t *p_dec)
block_t * decoder_NewAudioBuffer (decoder_t *dec, int samples)
This function will return a new audio buffer usable by a decoder as an output buffer.
subpicture_t * decoder_NewSubpicture (decoder_t *p_decoder, const subpicture_updater_t *p_dyn)
This function will return a new subpicture usable by a decoder as an output buffer.
static void RequestReload (decoder_t *p_dec)
int decoder_GetInputAttachments (decoder_t *p_dec, input_attachment_t ***ppp_attachment, int *pi_attachment)
This function gives all input attachments at once.
mtime_t decoder_GetDisplayDate (decoder_t *p_dec, mtime_t i_ts)
This function converts a decoder timestamp into a display date comparable to mdate().
int decoder_GetDisplayRate (decoder_t *p_dec)
This function returns the current input rate.
void decoder_AbortPictures (decoder_t *p_dec, bool b_abort)
Abort any calls of decoder_NewPicture.
static void DecoderWaitUnblock (decoder_t *p_dec)
static int DecoderTimedWait (decoder_t *p_dec, mtime_t deadline)
static void DecoderUpdatePreroll (int64_t *pi_preroll, const block_t *p)
static void DecoderFixTs (decoder_t *p_dec, mtime_t *pi_ts0, mtime_t *pi_ts1, mtime_t *pi_duration, int *pi_rate, mtime_t i_ts_bound)
static void DecoderPlayCc (decoder_t *p_dec, block_t *p_cc, const decoder_cc_desc_t *p_desc)
static void PacketizerGetCc (decoder_t *p_dec, decoder_t *p_dec_cc)
static int DecoderQueueCc (decoder_t *p_videodec, block_t *p_cc, const decoder_cc_desc_t *p_desc)
static int DecoderPlayVideo (decoder_t *p_dec, picture_t *p_picture, unsigned *restrict pi_lost_sum)
static void DecoderUpdateStatVideo (decoder_owner_sys_t *p_owner, unsigned decoded, unsigned lost)
static int DecoderQueueVideo (decoder_t *p_dec, picture_t *p_pic)
static int DecoderPlayAudio (decoder_t *p_dec, block_t *p_audio, unsigned *restrict pi_lost_sum)
static void DecoderUpdateStatAudio (decoder_owner_sys_t *p_owner, unsigned decoded, unsigned lost)
static int DecoderQueueAudio (decoder_t *p_dec, block_t *p_aout_buf)
static void DecoderPlaySpu (decoder_t *p_dec, subpicture_t *p_subpic)
static void DecoderUpdateStatSpu (decoder_owner_sys_t *p_owner, unsigned decoded, unsigned lost)
static int DecoderQueueSpu (decoder_t *p_dec, subpicture_t *p_spu)
static void DecoderProcess (decoder_t *p_dec, block_t *p_block)
Decode a block.
static void DecoderDecode (decoder_t *p_dec, block_t *p_block)
static void DecoderProcessFlush (decoder_t *p_dec)
static void * DecoderThread (void *p_data)
The decoding main loop.
static decoder_t * CreateDecoder (vlc_object_t *p_parent, input_thread_t *p_input, const es_format_t *fmt, input_resource_t *p_resource, sout_instance_t *p_sout)
Create a decoder object.
static void DeleteDecoder (decoder_t *p_dec)
Destroys a decoder object.
static void DecoderUnsupportedCodec (decoder_t *p_dec, const es_format_t *fmt, bool b_decoding)
static decoder_t * decoder_New (vlc_object_t *p_parent, input_thread_t *p_input, const es_format_t *fmt, input_clock_t *p_clock, input_resource_t *p_resource, sout_instance_t *p_sout)
decoder_t * input_DecoderNew (input_thread_t *p_input, es_format_t *fmt, input_clock_t *p_clock, sout_instance_t *p_sout)
Spawns a new decoder thread from the input thread.
decoder_t * input_DecoderCreate (vlc_object_t *p_parent, const es_format_t *fmt, input_resource_t *p_resource)
Spawn a decoder thread outside of the input thread.
void input_DecoderDelete (decoder_t *p_dec)
Kills a decoder thread and waits until it's finished.
void input_DecoderDecode (decoder_t *p_dec, block_t *p_block, bool b_do_pace)
Put a block_t in the decoder's fifo.
bool input_DecoderIsEmpty (decoder_t *p_dec)
This function returns true if the decoder fifo is empty and false otherwise.
void input_DecoderDrain (decoder_t *p_dec)
Signals that there are no further blocks to decode, and requests that the decoder drain all pending buffers.
void input_DecoderFlush (decoder_t *p_dec)
Requests that the decoder immediately discard all pending buffers.
void input_DecoderGetCcDesc (decoder_t *p_dec, decoder_cc_desc_t *p_desc)
This function get cc channels descriptions.
static bool input_DecoderHasCCChanFlag (decoder_t *p_dec, vlc_fourcc_t codec, int i_channel)
int input_DecoderSetCcState (decoder_t *p_dec, vlc_fourcc_t codec, int i_channel, bool b_decode)
This function activates the request closed caption channel.
int input_DecoderGetCcState (decoder_t *p_dec, vlc_fourcc_t codec, int i_channel, bool *pb_decode)
This function returns an error if the requested channel does not exist and set pb_decode to the channel status(active or not) otherwise.
void input_DecoderChangePause (decoder_t *p_dec, bool b_paused, mtime_t i_date)
This function changes the pause state.
void input_DecoderChangeDelay (decoder_t *p_dec, mtime_t i_delay)
This function changes the delay.
void input_DecoderStartWait (decoder_t *p_dec)
This function makes the decoder start waiting for a valid data block from its fifo.
void input_DecoderStopWait (decoder_t *p_dec)
This function exits the waiting mode of the decoder.
void input_DecoderWait (decoder_t *p_dec)
This function waits for the decoder to actually receive data.
void input_DecoderFrameNext (decoder_t *p_dec, mtime_t *pi_duration)
This function force the display of the next picture and fills the stream time consumed.
bool input_DecoderHasFormatChanged (decoder_t *p_dec, es_format_t *p_fmt, vlc_meta_t **pp_meta)
This function will return true if the ES format or meta data have changed since the last call.
size_t input_DecoderGetFifoSize (decoder_t *p_dec)
This function returns the current size in bytes of the decoder fifo.
void input_DecoderGetObjects (decoder_t *p_dec, vout_thread_t **pp_vout, audio_output_t **pp_aout)
This function returns the objects associated to a decoder.
Macro Definition Documentation
BLOCK_FLAG_CORE_PRIVATE_RELOADED
#define BLOCK_FLAG_CORE_PRIVATE_RELOADED (1 << BLOCK_FLAG_CORE_PRIVATE_SHIFT)
Referenced by DecoderDecode(), and DecoderProcess().
DECODER_BOGUS_VIDEO_DELAY
#define DECODER_BOGUS_VIDEO_DELAY ((mtime_t)(DEFAULT_PTS_DELAY * 30))
Referenced by DecoderPlayVideo().
DECODER_SPU_VOUT_WAIT_DURATION
#define DECODER_SPU_VOUT_WAIT_DURATION ((int)(0.200*CLOCK_FREQ))
Referenced by spu_new_buffer().
MAX_CC_DECODERS
#define MAX_CC_DECODERS 64 /* The es_out only creates one type of es */
Referenced by CreateDecoder(), DecoderProcessFlush(), and input_DecoderDelete().
Enumeration Type Documentation
reload
enum reload
Enumerator
RELOAD_NO_REQUEST
RELOAD_DECODER
RELOAD_DECODER_AOUT
Function Documentation
aout_replaygain_changed()
static bool aout_replaygain_changed (const audio_replay_gain_t * a, const audio_replay_gain_t * b) static
References AUDIO_REPLAY_GAIN_MAX, audio_replay_gain_t::pb_gain, and audio_replay_gain_t::pb_peak.
Referenced by aout_update_format().
aout_request_vout()
static vout_thread_t * aout_request_vout (void * p_private, vout_thread_t * p_vout, const video_format_t * p_fmt, bool b_recyle) static
References input_resource_RequestVout(), input_SendEventVout(), decoder_owner_sys_t::p_input, decoder_t::p_owner, and decoder_owner_sys_t::p_resource.
Referenced by aout_update_format().
aout_update_format()
static int aout_update_format (decoder_t * p_dec) static
References AOUT_CHAN_LEFT, AOUT_CHAN_RIGHT, AOUT_CHANMODE_DOLBYSTEREO, aout_DecDelete(), aout_DecNew(), AOUT_FMTS_IDENTICAL, aout_FormatPrepare(), aout_replaygain_changed(), aout_request_vout(), es_format_t::audio, es_format_t::audio_replay_gain, DecoderUpdateFormatLocked(), decoder_owner_sys_t::fmt, decoder_t::fmt_in, decoder_t::fmt_out, audio_format_t::i_bytes_per_frame, audio_format_t::i_chan_mode, es_format_t::i_codec, audio_format_t::i_format, audio_format_t::i_frame_length, audio_format_t::i_physical_channels, es_format_t::i_profile, input_resource_GetAout(), input_resource_PutAout(), input_SendEventAout(), decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_aout, decoder_owner_sys_t::p_input, decoder_t::p_owner, decoder_owner_sys_t::p_resource, aout_request_vout::pf_request_vout, var_InheritInteger, var_SetBool, var_TriggerCallback, VLC_CODEC_DTS, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by CreateDecoder().
CreateDecoder()
static decoder_t * CreateDecoder (vlc_object_t * p_parent, input_thread_t * p_input, const es_format_t * fmt, input_resource_t * p_resource, sout_instance_t * p_sout) static
Create a decoder object.
Parameters
p_input the input thread
p_es the es descriptor
b_packetizer instead of a decoder
Returns
the decoder object
References aout_update_format(), AUDIO_ES, es_format_t::audio_replay_gain, AUDIO_REPLAY_GAIN_MAX, decoder_owner_sys_t::b_draining, decoder_owner_sys_t::b_first, decoder_owner_sys_t::b_fmt_description, decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_idle, es_format_t::b_packetized, decoder_owner_sys_t::b_supported, decoder_owner_sys_t::b_waiting, block_FifoNew(), decoder_owner_sys_t::cc, DecoderGetDisplayDate(), DecoderGetDisplayRate(), DecoderGetInputAttachments(), DecoderQueueAudio(), DecoderQueueCc(), DecoderQueueSpu(), DecoderQueueVideo(), DecoderUpdateStatAudio(), DecoderUpdateStatSpu(), DecoderUpdateStatVideo(), decoder_owner_sys_t::desc, decoder_owner_sys_t::drained, decoder_owner_sys_t::error, es_format_Init(), decoder_owner_sys_t::flushing, decoder_owner_sys_t::fmt, decoder_t::fmt_out, decoder_owner_sys_t::frames_countdown, decoder_cc_desc_t::i_608_channels, decoder_cc_desc_t::i_708_channels, es_format_t::i_cat, decoder_owner_sys_t::i_last_rate, decoder_owner_sys_t::i_preroll_end, decoder_owner_sys_t::i_spu_channel, decoder_owner_sys_t::i_spu_order, decoder_owner_sys_t::i_ts_delay, INPUT_RATE_DEFAULT, LoadDecoder(), decoder_owner_sys_t::lock, MAX_CC_DECODERS, msg_Err, decoder_owner_sys_t::p_aout, decoder_owner_sys_t::p_description, decoder_owner_sys_t::p_fifo, decoder_owner_sys_t::p_input, decoder_t::p_owner, decoder_owner_sys_t::p_packetizer, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_sout, decoder_owner_sys_t::p_sout_input, decoder_owner_sys_t::p_spu_vout, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::pause_date, decoder_owner_sys_t::paused, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pb_peak, decoder_t::pf_aout_format_update, audio_replay_gain_t::pf_gain, decoder_t::pf_get_attachments, decoder_t::pf_get_display_date, decoder_t::pf_get_display_rate, audio_replay_gain_t::pf_peak, decoder_t::pf_queue_audio, decoder_t::pf_queue_cc, decoder_t::pf_queue_sub, decoder_t::pf_queue_video, decoder_t::pf_spu_buffer_new, decoder_owner_sys_t::pf_update_stat, decoder_t::pf_vout_buffer_new, decoder_t::pf_vout_format_update, decoder_owner_sys_t::pp_decoder, decoder_owner_sys_t::reload, RELOAD_NO_REQUEST, SPU_ES, spu_new_buffer(), unlikely, UnloadDecoder(), VIDEO_ES, vlc_cond_init(), vlc_custom_create, vlc_mutex_init(), vlc_object_release, VLC_TS_INVALID, vout_new_buffer(), vout_update_format(), decoder_owner_sys_t::wait_acknowledge, decoder_owner_sys_t::wait_fifo, decoder_owner_sys_t::wait_request, and decoder_owner_sys_t::wait_timed.
Referenced by decoder_New().
decoder_New()
static decoder_t * decoder_New (vlc_object_t * p_parent, input_thread_t * p_input, const es_format_t * fmt, input_clock_t * p_clock, input_resource_t * p_resource, sout_instance_t * p_sout) static
References _, AUDIO_ES, CreateDecoder(), DecoderThread(), DecoderUnsupportedCodec(), DeleteDecoder(), decoder_t::fmt_out, es_format_t::i_cat, msg_Err, N_, decoder_owner_sys_t::p_clock, decoder_t::p_module, decoder_t::p_owner, decoder_owner_sys_t::thread, UNKNOWN_ES, vlc_clone(), vlc_dialog_display_error, vlc_gettext(), VLC_THREAD_PRIORITY_AUDIO, and VLC_THREAD_PRIORITY_VIDEO.
Referenced by input_DecoderCreate(), and input_DecoderNew().
DecoderDecode()
static void DecoderDecode (decoder_t * p_dec, block_t * p_block) static
< No error
< Unspecified error
References BLOCK_FLAG_CORE_PRIVATE_RELOADED, block_Release(), DecoderProcess(), decoder_owner_sys_t::error, block_t::i_flags, decoder_t::p_owner, decoder_t::pf_decode, decoder_owner_sys_t::pf_update_stat, RequestReload(), unlikely, vlc_assert_unreachable, VLCDEC_ECRITICAL, VLCDEC_RELOAD, and VLCDEC_SUCCESS.
Referenced by DecoderProcess().
DecoderFixTs()
static void DecoderFixTs (decoder_t * p_dec, mtime_t * pi_ts0, mtime_t * pi_ts1, mtime_t * pi_duration, int * pi_rate, mtime_t i_ts_bound) static
References decoder_owner_sys_t::i_ts_delay, input_clock_ConvertTS(), input_clock_GetRate(), INPUT_RATE_DEFAULT, decoder_owner_sys_t::lock, module_get_name(), msg_Err, decoder_owner_sys_t::p_clock, decoder_t::p_module, decoder_t::p_owner, psz_name, vlc_assert_locked(), VLC_OBJECT, and VLC_TS_INVALID.
Referenced by DecoderPlayAudio(), DecoderPlaySpu(), and DecoderPlayVideo().
DecoderGetDisplayDate()
static mtime_t DecoderGetDisplayDate (decoder_t * p_dec, mtime_t i_ts) static
References decoder_owner_sys_t::b_waiting, input_clock_ConvertTS(), decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_clock, decoder_t::p_owner, decoder_owner_sys_t::paused, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, and VLC_TS_INVALID.
Referenced by CreateDecoder().
DecoderGetDisplayRate()
static int DecoderGetDisplayRate (decoder_t * p_dec) static
References input_clock_GetRate(), INPUT_RATE_DEFAULT, decoder_owner_sys_t::p_clock, and decoder_t::p_owner.
Referenced by CreateDecoder().
DecoderGetInputAttachments()
static int DecoderGetInputAttachments (decoder_t * p_dec, input_attachment_t *** ppp_attachment, int * pi_attachment) static
< Object not found
References input_Control(), INPUT_GET_ATTACHMENTS, decoder_owner_sys_t::p_input, decoder_t::p_owner, unlikely, and VLC_ENOOBJ.
Referenced by CreateDecoder().
DecoderPlayAudio()
static int DecoderPlayAudio (decoder_t * p_dec, block_t * p_audio, unsigned *restrict pi_lost_sum) static
References AOUT_DEC_CHANGED, AOUT_DEC_FAILED, aout_DecFlush(), aout_DecPlay(), AOUT_MAX_ADVANCE_TIME, AOUT_MAX_INPUT_RATE, AOUT_MAX_PREPARE_TIME, decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, block_Release(), DecoderFixTs(), DecoderTimedWait(), DecoderWaitUnblock(), block_t::i_length, decoder_owner_sys_t::i_preroll_end, block_t::i_pts, INPUT_RATE_DEFAULT, decoder_owner_sys_t::lock, msg_Dbg, msg_Warn, decoder_owner_sys_t::p_aout, decoder_t::p_owner, decoder_owner_sys_t::reload, RELOAD_DECODER_AOUT, RequestReload(), unlikely, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_TS_INVALID, and decoder_owner_sys_t::wait_acknowledge.
Referenced by DecoderQueueAudio().
DecoderPlayCc()
static void DecoderPlayCc (decoder_t * p_dec, block_t * p_cc, const decoder_cc_desc_t * p_desc) static
References block_Duplicate(), block_FifoPut(), block_Release(), decoder_owner_sys_t::cc, decoder_owner_sys_t::desc, decoder_cc_desc_t::i_608_channels, decoder_cc_desc_t::i_708_channels, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::pp_decoder, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by DecoderQueueCc(), and PacketizerGetCc().
DecoderPlaySpu()
static void DecoderPlaySpu (decoder_t * p_dec, subpicture_t * p_subpic) static
References decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, DecoderFixTs(), DecoderTimedWait(), DecoderWaitUnblock(), subpicture_t::i_start, subpicture_t::i_stop, decoder_owner_sys_t::lock, msg_Warn, decoder_t::p_owner, decoder_owner_sys_t::p_spu_vout, SPU_MAX_PREPARE_TIME, subpicture_Delete(), vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_TS_INVALID, vout_PutSubpicture(), and decoder_owner_sys_t::wait_acknowledge.
Referenced by DecoderQueueSpu().
DecoderPlayVideo()
static int DecoderPlayVideo (decoder_t * p_dec, picture_t * p_picture, unsigned *restrict pi_lost_sum) static
References decoder_owner_sys_t::b_first, picture_t::b_force, decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, picture_t::date, DECODER_BOGUS_VIDEO_DELAY, DecoderFixTs(), DecoderWaitUnblock(), decoder_owner_sys_t::frames_countdown, decoder_owner_sys_t::i_last_rate, decoder_owner_sys_t::i_preroll_end, INPUT_RATE_DEFAULT, likely, decoder_owner_sys_t::lock, msg_Dbg, msg_Warn, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::paused, picture_Release(), unlikely, vlc_cond_signal(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_TS_INVALID, vout_Flush(), vout_PutPicture(), and decoder_owner_sys_t::wait_acknowledge.
Referenced by DecoderQueueVideo().
DecoderProcess()
static void DecoderProcess (decoder_t * p_dec, block_t * p_block) static
Decode a block.
Parameters
p_dec the decoder object
p_block the block to decode
< No error
< No error
References block_ChainRelease(), BLOCK_FLAG_CORE_PRIVATE_RELOADED, block_Release(), DecoderDecode(), DecoderUpdatePreroll(), decoder_owner_sys_t::error, es_format_IsSimilar(), decoder_t::fmt_in, decoder_t::fmt_out, block_t::i_buffer, block_t::i_flags, decoder_owner_sys_t::i_preroll_end, decoder_owner_sys_t::lock, msg_Dbg, msg_Warn, block_t::p_next, decoder_t::p_owner, decoder_owner_sys_t::p_packetizer, decoder_owner_sys_t::p_sout, PacketizerGetCc(), decoder_t::pf_get_cc, decoder_t::pf_packetize, decoder_owner_sys_t::reload, RELOAD_DECODER, RELOAD_DECODER_AOUT, RELOAD_NO_REQUEST, ReloadDecoder(), unlikely, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by DecoderDecode(), and DecoderThread().
DecoderProcessFlush()
static void DecoderProcessFlush (decoder_t * p_dec) static
References aout_DecFlush(), AUDIO_ES, decoder_owner_sys_t::b_supported, decoder_owner_sys_t::cc, decoder_owner_sys_t::error, decoder_t::fmt_out, es_format_t::i_cat, decoder_owner_sys_t::i_preroll_end, decoder_owner_sys_t::i_spu_channel, input_resource_HoldVout(), decoder_owner_sys_t::lock, MAX_CC_DECODERS, decoder_owner_sys_t::p_aout, decoder_t::p_owner, decoder_owner_sys_t::p_packetizer, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_sout_input, decoder_owner_sys_t::p_spu_vout, decoder_owner_sys_t::p_vout, decoder_t::pf_flush, decoder_owner_sys_t::pp_decoder, sout_InputFlush(), SPU_ES, VIDEO_ES, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, VLC_TS_INVALID, vout_Flush(), and vout_FlushSubpictureChannel().
Referenced by DecoderThread().
DecoderQueueAudio()
static int DecoderQueueAudio (decoder_t * p_dec, block_t * p_aout_buf) static
References DecoderPlayAudio(), decoder_t::p_owner, and decoder_owner_sys_t::pf_update_stat.
Referenced by CreateDecoder().
DecoderQueueCc()
static int DecoderQueueCc (decoder_t * p_videodec, block_t * p_cc, const decoder_cc_desc_t * p_desc) static
References decoder_owner_sys_t::b_supported, block_Release(), decoder_owner_sys_t::cc, DecoderPlayCc(), decoder_t::p_owner, decoder_owner_sys_t::p_packetizer, decoder_t::pf_get_cc, and unlikely.
Referenced by CreateDecoder().
DecoderQueueSpu()
static int DecoderQueueSpu (decoder_t * p_dec, subpicture_t * p_spu) static
References input_thread_private_t::counters_lock, DecoderPlaySpu(), decoder_owner_sys_t::i_preroll_end, subpicture_t::i_start, subpicture_t::i_stop, input_priv(), input_resource_HoldVout(), decoder_owner_sys_t::lock, input_thread_private_t::p_decoded_sub, decoder_owner_sys_t::p_input, decoder_t::p_owner, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_spu_vout, stats_Update(), subpicture_Delete(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, and VLC_TS_INVALID.
Referenced by CreateDecoder().
DecoderQueueVideo()
static int DecoderQueueVideo (decoder_t * p_dec, picture_t * p_pic) static
References DecoderPlayVideo(), decoder_t::p_owner, and decoder_owner_sys_t::pf_update_stat.
Referenced by CreateDecoder().
DecoderThread()
static void * DecoderThread (void * p_data) static
The decoding main loop.
Parameters
p_dec the decoder
References aout_DecChangePause(), aout_DecFlush(), decoder_owner_sys_t::b_draining, decoder_owner_sys_t::b_idle, DecoderProcess(), DecoderProcessFlush(), decoder_owner_sys_t::drained, decoder_owner_sys_t::flushing, decoder_owner_sys_t::frames_countdown, likely, decoder_owner_sys_t::lock, msg_Dbg, decoder_owner_sys_t::p_aout, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::pause_date, decoder_owner_sys_t::paused, vlc_assert_unreachable, vlc_cleanup_pop, vlc_cond_signal(), vlc_fifo_CleanupPush, vlc_fifo_DequeueUnlocked(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_fifo_Wait(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), vlc_savecancel(), vlc_testcancel(), vout_ChangePause(), decoder_owner_sys_t::wait_acknowledge, and decoder_owner_sys_t::wait_fifo.
Referenced by decoder_New().
DecoderTimedWait()
static int DecoderTimedWait (decoder_t * p_dec, mtime_t deadline) static
< No error
< Unspecified error
< No error
References decoder_owner_sys_t::flushing, mdate(), decoder_owner_sys_t::p_fifo, decoder_t::p_owner, VLC_EGENERIC, vlc_fifo_Lock(), vlc_fifo_TimedWaitCond(), vlc_fifo_Unlock(), VLC_SUCCESS, and decoder_owner_sys_t::wait_timed.
Referenced by DecoderPlayAudio(), and DecoderPlaySpu().
DecoderUnsupportedCodec()
static void DecoderUnsupportedCodec (decoder_t * p_dec, const es_format_t * fmt, bool b_decoding) static
References _, es_format_t::i_cat, es_format_t::i_codec, msg_Err, N_, VLC_CODEC_UNKNOWN, vlc_dialog_display_error, and vlc_fourcc_GetDescription().
Referenced by decoder_New(), and input_DecoderSetCcState().
DecoderUpdateFormatLocked()
static void DecoderUpdateFormatLocked (decoder_t * p_dec) static
References decoder_owner_sys_t::b_fmt_description, es_format_Clean(), es_format_Copy(), decoder_owner_sys_t::fmt, decoder_t::fmt_out, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_description, decoder_t::p_description, decoder_t::p_owner, vlc_assert_locked(), and vlc_meta_Delete().
Referenced by aout_update_format(), and vout_update_format().
DecoderUpdatePreroll()
static void DecoderUpdatePreroll (int64_t * pi_preroll, const block_t * p) inline static
References BLOCK_FLAG_CORRUPTED, BLOCK_FLAG_DISCONTINUITY, BLOCK_FLAG_PREROLL, p, and VLC_TS_INVALID.
Referenced by DecoderProcess().
DecoderUpdateStatAudio()
static void DecoderUpdateStatAudio (decoder_owner_sys_t * p_owner, unsigned decoded, unsigned lost) static
References aout_DecGetResetStats(), input_thread_private_t::counters_lock, input_priv(), decoder_owner_sys_t::p_aout, input_thread_private_t::p_decoded_audio, decoder_owner_sys_t::p_input, input_thread_private_t::p_lost_abuffers, input_thread_private_t::p_played_abuffers, stats_Update(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by CreateDecoder().
DecoderUpdateStatSpu()
static void DecoderUpdateStatSpu (decoder_owner_sys_t * p_owner, unsigned decoded, unsigned lost) static
Referenced by CreateDecoder().
DecoderUpdateStatVideo()
static void DecoderUpdateStatVideo (decoder_owner_sys_t * p_owner, unsigned decoded, unsigned lost) static
References input_thread_private_t::counters_lock, input_priv(), input_thread_private_t::p_decoded_video, input_thread_private_t::p_displayed_pictures, decoder_owner_sys_t::p_input, input_thread_private_t::p_lost_pictures, decoder_owner_sys_t::p_vout, stats_Update(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_GetResetStatistic().
Referenced by CreateDecoder().
DecoderWaitUnblock()
static void DecoderWaitUnblock (decoder_t * p_dec) static
References decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_assert_locked(), vlc_cond_wait(), and decoder_owner_sys_t::wait_request.
Referenced by DecoderPlayAudio(), DecoderPlaySpu(), and DecoderPlayVideo().
DeleteDecoder()
static void DeleteDecoder (decoder_t * p_dec) static
Destroys a decoder object.
Parameters
p_dec the decoder object
Returns
nothing
References aout_DecDelete(), aout_DecFlush(), block_FifoRelease(), es_format_Clean(), decoder_owner_sys_t::fmt, decoder_t::fmt_in, decoder_t::fmt_out, es_format_t::i_cat, es_format_t::i_codec, decoder_owner_sys_t::i_spu_channel, input_resource_HoldVout(), input_resource_PutAout(), input_resource_RequestVout(), input_SendEventAout(), input_SendEventVout(), decoder_owner_sys_t::lock, msg_Dbg, decoder_owner_sys_t::p_aout, decoder_owner_sys_t::p_description, decoder_owner_sys_t::p_fifo, decoder_owner_sys_t::p_input, decoder_t::p_owner, decoder_owner_sys_t::p_packetizer, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_sout_input, decoder_owner_sys_t::p_spu_vout, decoder_owner_sys_t::p_vout, sout_InputDelete(), SPU_ES, UnloadDecoder(), vlc_cond_destroy(), vlc_meta_Delete(), vlc_mutex_destroy(), vlc_object_release, vout_Cancel(), vout_FlushSubpictureChannel(), decoder_owner_sys_t::wait_acknowledge, decoder_owner_sys_t::wait_fifo, decoder_owner_sys_t::wait_request, and decoder_owner_sys_t::wait_timed.
Referenced by decoder_New(), and input_DecoderDelete().
input_DecoderChangeDelay()
void input_DecoderChangeDelay (decoder_t * p_dec, mtime_t i_delay)
This function changes the delay.
References decoder_owner_sys_t::i_ts_delay, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutDecoderChangeDelay().
input_DecoderChangePause()
void input_DecoderChangePause (decoder_t * p_dec, bool b_paused, mtime_t i_date)
This function changes the pause state.
The date parameter MUST hold the exact date at which the change has been done for proper vout/aout pausing.
References decoder_owner_sys_t::frames_countdown, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::pause_date, decoder_owner_sys_t::paused, vlc_fifo_Lock(), vlc_fifo_Signal(), and vlc_fifo_Unlock().
Referenced by EsOutDecodersChangePause().
input_DecoderCreate()
decoder_t * input_DecoderCreate (vlc_object_t * p_parent, const es_format_t * fmt, input_resource_t * p_resource)
Spawn a decoder thread outside of the input thread.
References decoder_New().
input_DecoderDecode()
void input_DecoderDecode (decoder_t * p_dec, block_t * p_block, bool b_do_pace)
Put a block_t in the decoder's fifo.
Thread-safe w.r.t. the decoder. May be a cancellation point.
Parameters
p_dec the decoder object
p_block the data block
References decoder_owner_sys_t::b_waiting, block_ChainRelease(), BLOCK_FLAG_DISCONTINUITY, block_t::i_flags, msg_Warn, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, vlc_fifo_DequeueAllUnlocked(), vlc_fifo_GetBytes(), vlc_fifo_GetCount(), vlc_fifo_Lock(), vlc_fifo_QueueUnlocked(), vlc_fifo_Unlock(), vlc_fifo_WaitCond(), and decoder_owner_sys_t::wait_fifo.
Referenced by EsOutSend().
input_DecoderDelete()
void input_DecoderDelete (decoder_t * p_dec)
Kills a decoder thread and waits until it's finished.
Parameters
p_input the input thread
p_es the es descriptor
Returns
nothing
References decoder_owner_sys_t::b_supported, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::cc, DeleteDecoder(), decoder_owner_sys_t::flushing, input_DecoderSetCcState(), decoder_owner_sys_t::lock, MAX_CC_DECODERS, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::thread, vlc_cancel(), VLC_CODEC_CEA608, vlc_cond_signal(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_join(), vlc_mutex_lock(), vlc_mutex_unlock(), vout_Cancel(), decoder_owner_sys_t::wait_request, and decoder_owner_sys_t::wait_timed.
Referenced by EsDestroyDecoder(), EsOutSetRecord(), EsOutTerminate(), and input_DecoderSetCcState().
input_DecoderDrain()
void input_DecoderDrain (decoder_t * p_dec)
Signals that there are no further blocks to decode, and requests that the decoder drain all pending buffers.
This is used to ensure that all intermediate buffers empty and no samples get lost at the end of the stream.
Note
The function does not actually wait for draining. It just signals that draining should be performed once the decoder has emptied FIFO.
References decoder_owner_sys_t::b_draining, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, vlc_fifo_Lock(), vlc_fifo_Signal(), and vlc_fifo_Unlock().
Referenced by EsOutControlLocked(), and EsOutDel().
input_DecoderFlush()
void input_DecoderFlush (decoder_t * p_dec)
Requests that the decoder immediately discard all pending buffers.
This is useful when seeking or when deselecting a stream.
References block_ChainRelease(), decoder_owner_sys_t::flushing, decoder_owner_sys_t::fmt, decoder_owner_sys_t::frames_countdown, es_format_t::i_cat, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::paused, SPU_ES, VIDEO_ES, vlc_cond_signal(), vlc_fifo_DequeueAllUnlocked(), vlc_fifo_Lock(), vlc_fifo_Signal(), vlc_fifo_Unlock(), and decoder_owner_sys_t::wait_timed.
Referenced by EsOutChangePosition().
input_DecoderFrameNext()
void input_DecoderFrameNext (decoder_t * p_dec, mtime_t * pi_duration)
This function force the display of the next picture and fills the stream time consumed.
References decoder_owner_sys_t::fmt, decoder_owner_sys_t::frames_countdown, es_format_t::i_cat, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::paused, VIDEO_ES, vlc_fifo_Lock(), vlc_fifo_Signal(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_NextPicture().
Referenced by EsOutFrameNext().
input_DecoderGetCcDesc()
void input_DecoderGetCcDesc (decoder_t * p_dec, decoder_cc_desc_t * p_desc)
This function get cc channels descriptions.
References decoder_owner_sys_t::cc, decoder_owner_sys_t::desc, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutSend().
input_DecoderGetCcState()
int input_DecoderGetCcState (decoder_t * p_dec, vlc_fourcc_t codec, int i_channel, bool * pb_decode)
This function returns an error if the requested channel does not exist and set pb_decode to the channel status(active or not) otherwise.
< Unspecified error
< No error
References decoder_owner_sys_t::cc, input_DecoderHasCCChanFlag(), decoder_owner_sys_t::lock, decoder_t::p_owner, decoder_owner_sys_t::pp_decoder, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by EsIsSelected().
input_DecoderGetFifoSize()
size_t input_DecoderGetFifoSize (decoder_t * p_dec)
This function returns the current size in bytes of the decoder fifo.
References block_FifoSize(), decoder_owner_sys_t::p_fifo, and decoder_t::p_owner.
Referenced by EsOutIsExtraBufferingAllowed().
input_DecoderGetObjects()
void input_DecoderGetObjects (decoder_t * p_dec, vout_thread_t ** pp_vout, audio_output_t ** pp_aout)
This function returns the objects associated to a decoder.
They must be released using vlc_object_release().
References decoder_owner_sys_t::lock, decoder_owner_sys_t::p_aout, decoder_t::p_owner, decoder_owner_sys_t::p_vout, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_hold.
Referenced by EsOutControlLocked().
input_DecoderHasCCChanFlag()
static bool input_DecoderHasCCChanFlag (decoder_t * p_dec, vlc_fourcc_t codec, int i_channel) static
References decoder_owner_sys_t::cc, decoder_owner_sys_t::desc, decoder_cc_desc_t::i_608_channels, decoder_cc_desc_t::i_708_channels, decoder_t::p_owner, VLC_CODEC_CEA608, and VLC_CODEC_CEA708.
Referenced by input_DecoderGetCcState(), and input_DecoderSetCcState().
input_DecoderHasFormatChanged()
bool input_DecoderHasFormatChanged (decoder_t * p_dec, es_format_t * p_fmt, vlc_meta_t ** pp_meta)
This function will return true if the ES format or meta data have changed since the last call.
In which case, it will do a copy of the current es_format_t if p_fmt is not NULL and will do a copy of the current description if pp_meta is non NULL. The es_format_t MUST be freed by es_format_Clean and *pp_meta MUST be freed by vlc_meta_Delete. Otherwise it will return false and will not initialize p_fmt and *pp_meta.
References decoder_owner_sys_t::b_fmt_description, es_format_Copy(), decoder_owner_sys_t::fmt, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_description, decoder_t::p_owner, vlc_meta_Merge(), vlc_meta_New(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutSend().
input_DecoderIsEmpty()
bool input_DecoderIsEmpty (decoder_t * p_dec)
This function returns true if the decoder fifo is empty and false otherwise.
References AUDIO_ES, decoder_owner_sys_t::b_draining, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::drained, decoder_owner_sys_t::fmt, es_format_t::i_cat, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_sout_input, decoder_owner_sys_t::p_vout, sout_InputIsEmpty(), VIDEO_ES, vlc_fifo_IsEmpty(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_IsEmpty().
Referenced by EsOutDecodersIsEmpty(), and EsOutDel().
input_DecoderNew()
decoder_t * input_DecoderNew (input_thread_t * p_input, es_format_t * fmt, input_clock_t * p_clock, sout_instance_t * p_sout)
Spawns a new decoder thread from the input thread.
Parameters
p_input the input thread
p_es the es descriptor
Returns
the spawned decoder object
References decoder_New(), input_priv(), and VLC_OBJECT.
Referenced by EsCreateDecoder(), EsOutSetRecord(), and input_DecoderSetCcState().
input_DecoderSetCcState()
int input_DecoderSetCcState (decoder_t * p_dec, vlc_fourcc_t codec, int i_channel, bool b_decode)
This function activates the request closed caption channel.
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References _, decoder_owner_sys_t::cc, subs_format_t::cc, DecoderUnsupportedCodec(), decoder_owner_sys_t::desc, es_format_Init(), subs_format_t::i_channel, decoder_cc_desc_t::i_reorder_depth, subs_format_t::i_reorder_depth, input_DecoderDelete(), input_DecoderHasCCChanFlag(), input_DecoderNew(), decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_clock, decoder_owner_sys_t::p_input, decoder_t::p_module, decoder_t::p_owner, decoder_owner_sys_t::p_sout, decoder_owner_sys_t::pp_decoder, SPU_ES, es_format_t::subs, vlc_dialog_display_error, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by EsSelect(), EsUnselect(), and input_DecoderDelete().
input_DecoderStartWait()
void input_DecoderStartWait (decoder_t * p_dec)
This function makes the decoder start waiting for a valid data block from its fifo.
References decoder_owner_sys_t::b_first, decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_request.
Referenced by EsCreateDecoder(), EsOutChangePosition(), and EsOutSetRecord().
input_DecoderStopWait()
void input_DecoderStopWait (decoder_t * p_dec)
This function exits the waiting mode of the decoder.
References decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_request.
Referenced by EsOutDecodersStopBuffering().
input_DecoderWait()
void input_DecoderWait (decoder_t * p_dec)
This function waits for the decoder to actually receive data.
References decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_idle, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::paused, vlc_cond_wait(), vlc_fifo_IsEmpty(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_acknowledge.
Referenced by EsOutDecodersStopBuffering().
LoadDecoder()
static int LoadDecoder (decoder_t * p_dec, bool b_packetizer, const es_format_t *restrict p_fmt) static
Load a decoder module.
References AUDIO_ES, decoder_t::b_frame_drop_allowed, ES_CATEGORY_COUNT, es_format_Clean(), es_format_Copy(), es_format_Init(), decoder_t::fmt_in, decoder_t::fmt_out, es_format_t::i_cat, decoder_t::i_extra_picture_buffers, module_need, decoder_t::p_module, decoder_t::pf_decode, decoder_t::pf_flush, decoder_t::pf_get_cc, decoder_t::pf_packetize, SPU_ES, and VIDEO_ES.
Referenced by CreateDecoder(), and ReloadDecoder().
PacketizerGetCc()
static void PacketizerGetCc (decoder_t * p_dec, decoder_t * p_dec_cc) static
References decoder_owner_sys_t::b_supported, decoder_owner_sys_t::cc, DecoderPlayCc(), decoder_t::p_owner, and decoder_t::pf_get_cc.
Referenced by DecoderProcess().
ReloadDecoder()
static int ReloadDecoder (decoder_t * p_dec, bool b_packetizer, const es_format_t *restrict p_fmt, enum reload reload) static
< No error
< Unspecified error
< Unspecified error
< No error
References aout_DecDelete(), AUDIO_ES, decoder_owner_sys_t::error, es_format_Clean(), es_format_Copy(), decoder_owner_sys_t::fmt, es_format_t::i_cat, input_resource_PutAout(), LoadDecoder(), decoder_owner_sys_t::lock, decoder_owner_sys_t::p_aout, decoder_t::p_owner, decoder_owner_sys_t::p_resource, RELOAD_DECODER_AOUT, UnloadDecoder(), VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by DecoderProcess().
RequestReload()
static void RequestReload (decoder_t * p_dec) static
References decoder_t::p_owner, decoder_owner_sys_t::reload, RELOAD_DECODER, and RELOAD_NO_REQUEST.
Referenced by DecoderDecode(), and DecoderPlayAudio().
spu_new_buffer()
static subpicture_t * spu_new_buffer (decoder_t * p_dec, const subpicture_updater_t * p_updater) static
References subpicture_t::b_subtitle, DECODER_SPU_VOUT_WAIT_DURATION, decoder_owner_sys_t::error, subpicture_t::i_channel, subpicture_t::i_order, decoder_owner_sys_t::i_spu_channel, decoder_owner_sys_t::i_spu_order, input_resource_HoldVout(), msg_Warn, msleep, decoder_t::p_owner, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_spu_vout, subpicture_New(), vlc_object_release, and vout_RegisterSubpictureChannel().
Referenced by CreateDecoder().
UnloadDecoder()
static void UnloadDecoder (decoder_t * p_dec) static
Unload a decoder module.
References es_format_Clean(), decoder_t::fmt_in, decoder_t::fmt_out, module_unneed, decoder_t::p_description, decoder_t::p_module, and vlc_meta_Delete().
Referenced by CreateDecoder(), DeleteDecoder(), and ReloadDecoder().
vout_new_buffer()
static picture_t * vout_new_buffer (decoder_t * p_dec) static
References decoder_t::p_owner, decoder_owner_sys_t::p_vout, and vout_GetPicture().
Referenced by CreateDecoder().
vout_update_format()
static int vout_update_format (decoder_t * p_dec) static
References DecoderUpdateFormatLocked(), vlc_rational_t::den, decoder_owner_sys_t::fmt, decoder_t::fmt_in, decoder_t::fmt_out, vlc_chroma_description_t::h, video_format_t::i_chroma, es_format_t::i_codec, decoder_t::i_extra_picture_buffers, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, input_resource_RequestVout(), input_SendEventVout(), video_format_t::lighting, decoder_owner_sys_t::lock, video_format_t::mastering, video_format_t::MaxCLL, video_format_t::MaxFALL, msg_Err, msg_Warn, video_format_t::multiview_mode, video_format_t::orientation, vlc_chroma_description_t::p, decoder_owner_sys_t::p_input, decoder_t::p_owner, decoder_owner_sys_t::p_resource, decoder_owner_sys_t::p_vout, vlc_chroma_description_t::plane_count, var_CreateGetBool, es_format_t::video, video_format_AdjustColorSpace(), VLC_CODEC_DIRAC, VLC_CODEC_H264, VLC_CODEC_HEVC, VLC_CODEC_VP5, VLC_CODEC_VP6, VLC_CODEC_VP6F, VLC_CODEC_VP8, vlc_fourcc_GetChromaDescription(), vlc_fourcc_IsYUV(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_ureduce(), and vlc_chroma_description_t::w.
Referenced by CreateDecoder().