VLC: src/input/decoder.h File Reference
decoder.h File Reference
Functions
decoder_t * input_DecoderNew (input_thread_t *, es_format_t *, input_clock_t *, sout_instance_t *)
Spawns a new decoder thread from the input thread.
void input_DecoderChangePause (decoder_t *, bool b_paused, mtime_t i_date)
This function changes the pause state.
void input_DecoderChangeDelay (decoder_t *, mtime_t i_delay)
This function changes the delay.
void input_DecoderStartWait (decoder_t *)
This function makes the decoder start waiting for a valid data block from its fifo.
void input_DecoderWait (decoder_t *)
This function waits for the decoder to actually receive data.
void input_DecoderStopWait (decoder_t *)
This function exits the waiting mode of the decoder.
bool input_DecoderIsEmpty (decoder_t *)
This function returns true if the decoder fifo is empty and false otherwise.
int input_DecoderSetCcState (decoder_t *, vlc_fourcc_t, int i_channel, bool b_decode)
This function activates the request closed caption channel.
int input_DecoderGetCcState (decoder_t *, vlc_fourcc_t, int i_channel, bool *pb_decode)
This function returns an error if the requested channel does not exist and set pb_decode to the channel status(active or not) otherwise.
void input_DecoderGetCcDesc (decoder_t *, decoder_cc_desc_t *)
This function get cc channels descriptions.
void input_DecoderFrameNext (decoder_t *p_dec, mtime_t *pi_duration)
This function force the display of the next picture and fills the stream time consumed.
bool input_DecoderHasFormatChanged (decoder_t *p_dec, es_format_t *p_fmt, vlc_meta_t **pp_meta)
This function will return true if the ES format or meta data have changed since the last call.
size_t input_DecoderGetFifoSize (decoder_t *p_dec)
This function returns the current size in bytes of the decoder fifo.
void input_DecoderGetObjects (decoder_t *, vout_thread_t **, audio_output_t **)
This function returns the objects associated to a decoder.
Function Documentation
input_DecoderChangeDelay()
void input_DecoderChangeDelay (decoder_t * p_dec, mtime_t i_delay)
This function changes the delay.
References decoder_owner_sys_t::i_ts_delay, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutDecoderChangeDelay().
input_DecoderChangePause()
void input_DecoderChangePause (decoder_t * p_dec, bool b_paused, mtime_t i_date)
This function changes the pause state.
The date parameter MUST hold the exact date at which the change has been done for proper vout/aout pausing.
References decoder_owner_sys_t::frames_countdown, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::pause_date, decoder_owner_sys_t::paused, vlc_fifo_Lock(), vlc_fifo_Signal(), and vlc_fifo_Unlock().
Referenced by EsOutDecodersChangePause().
input_DecoderFrameNext()
void input_DecoderFrameNext (decoder_t * p_dec, mtime_t * pi_duration)
This function force the display of the next picture and fills the stream time consumed.
References decoder_owner_sys_t::fmt, decoder_owner_sys_t::frames_countdown, es_format_t::i_cat, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_vout, decoder_owner_sys_t::paused, VIDEO_ES, vlc_fifo_Lock(), vlc_fifo_Signal(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_NextPicture().
Referenced by EsOutFrameNext().
input_DecoderGetCcDesc()
void input_DecoderGetCcDesc (decoder_t * p_dec, decoder_cc_desc_t * p_desc)
This function get cc channels descriptions.
References decoder_owner_sys_t::cc, decoder_owner_sys_t::desc, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutSend().
input_DecoderGetCcState()
int input_DecoderGetCcState (decoder_t * p_dec, vlc_fourcc_t codec, int i_channel, bool * pb_decode)
This function returns an error if the requested channel does not exist and set pb_decode to the channel status(active or not) otherwise.
< Unspecified error
< No error
References decoder_owner_sys_t::cc, input_DecoderHasCCChanFlag(), decoder_owner_sys_t::lock, decoder_t::p_owner, decoder_owner_sys_t::pp_decoder, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by EsIsSelected().
input_DecoderGetFifoSize()
size_t input_DecoderGetFifoSize (decoder_t * p_dec)
This function returns the current size in bytes of the decoder fifo.
References block_FifoSize(), decoder_owner_sys_t::p_fifo, and decoder_t::p_owner.
Referenced by EsOutIsExtraBufferingAllowed().
input_DecoderGetObjects()
void input_DecoderGetObjects (decoder_t * p_dec, vout_thread_t ** pp_vout, audio_output_t ** pp_aout)
This function returns the objects associated to a decoder.
They must be released using vlc_object_release().
References decoder_owner_sys_t::lock, decoder_owner_sys_t::p_aout, decoder_t::p_owner, decoder_owner_sys_t::p_vout, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_hold.
Referenced by EsOutControlLocked().
input_DecoderHasFormatChanged()
bool input_DecoderHasFormatChanged (decoder_t * p_dec, es_format_t * p_fmt, vlc_meta_t ** pp_meta)
This function will return true if the ES format or meta data have changed since the last call.
In which case, it will do a copy of the current es_format_t if p_fmt is not NULL and will do a copy of the current description if pp_meta is non NULL. The es_format_t MUST be freed by es_format_Clean and *pp_meta MUST be freed by vlc_meta_Delete. Otherwise it will return false and will not initialize p_fmt and *pp_meta.
References decoder_owner_sys_t::b_fmt_description, es_format_Copy(), decoder_owner_sys_t::fmt, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_description, decoder_t::p_owner, vlc_meta_Merge(), vlc_meta_New(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutSend().
input_DecoderIsEmpty()
bool input_DecoderIsEmpty (decoder_t * p_dec)
This function returns true if the decoder fifo is empty and false otherwise.
References AUDIO_ES, decoder_owner_sys_t::b_draining, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::drained, decoder_owner_sys_t::fmt, es_format_t::i_cat, decoder_owner_sys_t::lock, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::p_sout_input, decoder_owner_sys_t::p_vout, sout_InputIsEmpty(), VIDEO_ES, vlc_fifo_IsEmpty(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_IsEmpty().
Referenced by EsOutDecodersIsEmpty(), and EsOutDel().
input_DecoderNew()
decoder_t * input_DecoderNew (input_thread_t * p_input, es_format_t * fmt, input_clock_t * p_clock, sout_instance_t * p_sout)
Spawns a new decoder thread from the input thread.
Parameters
p_input the input thread
p_es the es descriptor
Returns
the spawned decoder object
References decoder_New(), input_priv(), and VLC_OBJECT.
Referenced by EsCreateDecoder(), EsOutSetRecord(), and input_DecoderSetCcState().
input_DecoderSetCcState()
int input_DecoderSetCcState (decoder_t * p_dec, vlc_fourcc_t codec, int i_channel, bool b_decode)
This function activates the request closed caption channel.
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References _, decoder_owner_sys_t::cc, subs_format_t::cc, DecoderUnsupportedCodec(), decoder_owner_sys_t::desc, es_format_Init(), subs_format_t::i_channel, decoder_cc_desc_t::i_reorder_depth, subs_format_t::i_reorder_depth, input_DecoderDelete(), input_DecoderHasCCChanFlag(), input_DecoderNew(), decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_clock, decoder_owner_sys_t::p_input, decoder_t::p_module, decoder_t::p_owner, decoder_owner_sys_t::p_sout, decoder_owner_sys_t::pp_decoder, SPU_ES, es_format_t::subs, vlc_dialog_display_error, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by EsSelect(), EsUnselect(), and input_DecoderDelete().
input_DecoderStartWait()
void input_DecoderStartWait (decoder_t * p_dec)
This function makes the decoder start waiting for a valid data block from its fifo.
References decoder_owner_sys_t::b_first, decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_request.
Referenced by EsCreateDecoder(), EsOutChangePosition(), and EsOutSetRecord().
input_DecoderStopWait()
void input_DecoderStopWait (decoder_t * p_dec)
This function exits the waiting mode of the decoder.
References decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, decoder_t::p_owner, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_request.
Referenced by EsOutDecodersStopBuffering().
input_DecoderWait()
void input_DecoderWait (decoder_t * p_dec)
This function waits for the decoder to actually receive data.
References decoder_owner_sys_t::b_has_data, decoder_owner_sys_t::b_idle, decoder_owner_sys_t::b_waiting, decoder_owner_sys_t::lock, msg_Err, decoder_owner_sys_t::p_fifo, decoder_t::p_owner, decoder_owner_sys_t::paused, vlc_cond_wait(), vlc_fifo_IsEmpty(), vlc_fifo_Lock(), vlc_fifo_Unlock(), vlc_mutex_lock(), vlc_mutex_unlock(), and decoder_owner_sys_t::wait_acknowledge.
Referenced by EsOutDecodersStopBuffering().