VLC: src/input/demux_chained.c File Reference
demux_chained.c File Reference
Data Structures
struct vlc_demux_chained_t
Functions
static void * vlc_demux_chained_Thread (void *data)
vlc_demux_chained_t * vlc_demux_chained_New (vlc_object_t *parent, const char *name, es_out_t *out)
Creates a chained demuxer.
void vlc_demux_chained_Send (vlc_demux_chained_t *dc, block_t *block)
Sends data to a chained demuxer.
int vlc_demux_chained_ControlVa (vlc_demux_chained_t *dc, int query, va_list ap)
Controls a chained demuxer.
void vlc_demux_chained_Delete (vlc_demux_chained_t *dc)
Destroys a chained demuxer.
Function Documentation
vlc_demux_chained_Thread()
static void * vlc_demux_chained_Thread (void * data) static
References CLOCK_FREQ, demux_Control(), demux_Delete(), demux_Demux(), DEMUX_GET_LENGTH, DEMUX_GET_POSITION, DEMUX_GET_TIME, demux_NewAdvanced, DEMUX_SET_GROUP, demux_TestAndClearFlags(), vlc_demux_chained_t::fifo, vlc_demux_chained_t::length, vlc_demux_chained_t::lock, mdate(), vlc_demux_chained_t::name, vlc_demux_chained_t::out, vlc_demux_chained_t::position, vlc_demux_chained_t::stats, vlc_demux_chained_t::time, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_stream_Delete().
Referenced by vlc_demux_chained_New().