VLC: src/input/demux.h File Reference
demux.h File Reference
Macros
#define demux_NewAdvanced(a, b, c, d, e, f, g, h) demux_NewAdvanced(VLC_OBJECT(a),b,c,d,e,f,g,h)
Functions
demux_t * demux_NewAdvanced (vlc_object_t *p_obj, input_thread_t *p_parent_input, const char *psz_access, const char *psz_demux, const char *psz_path, stream_t *s, es_out_t *out, bool)
unsigned demux_TestAndClearFlags (demux_t *, unsigned)
int demux_GetTitle (demux_t *)
int demux_GetSeekpoint (demux_t *)
demux_t * demux_FilterChainNew (demux_t *source, const char *list)
Builds an explicit chain of demux filters.
bool demux_FilterEnable (demux_t *p_demux_chain, const char *psz_demux)
bool demux_FilterDisable (demux_t *p_demux_chain, const char *psz_demux)
Macro Definition Documentation
demux_NewAdvanced
#define demux_NewAdvanced (a, b, c, d, e, f, g, h) demux_NewAdvanced(VLC_OBJECT(a),b,c,d,e,f,g,h)
Referenced by demux_New(), InputDemuxNew(), and vlc_demux_chained_Thread().
Function Documentation
demux_FilterChainNew()
demux_t * demux_FilterChainNew (demux_t * source, const char * list)
Builds an explicit chain of demux filters.
This function creates a chain of filters according to a supplied list.
See also stream_FilterChainNew(). Those two functions have identical semantics and ownership rules, except for the use of demux vs stream.
Parameters
source input stream around which to build a filter chain
list colon-separated list of stream filters (upstream first)
Returns
The last demux (filter) in the chain. The return value is always a valid (non-NULL) demux pointer.
References config_ChainCreate(), config_ChainDestroy(), demux_FilterNew(), psz_name, and strdup().
Referenced by ControlInsertDemuxFilter(), and InputSourceNew().
demux_FilterDisable()
bool demux_FilterDisable (demux_t * p_demux_chain, const char * psz_demux)
References demux_filter_enable_disable().
Referenced by Control().
demux_FilterEnable()
bool demux_FilterEnable (demux_t * p_demux_chain, const char * psz_demux)
References demux_filter_enable_disable().
Referenced by Control().
demux_GetSeekpoint()
int demux_GetSeekpoint (demux_t * p_demux)
< No error
References demux_Control(), DEMUX_GET_SEEKPOINT, demux_t::i_seekpoint, demux_t::info, and VLC_SUCCESS.
Referenced by Control(), and UpdateTitleSeekpointFromDemux().
demux_GetTitle()
int demux_GetTitle (demux_t * p_demux)
< No error
References demux_Control(), DEMUX_GET_TITLE, demux_t::i_title, demux_t::info, and VLC_SUCCESS.
Referenced by Control(), and UpdateTitleSeekpointFromDemux().
demux_NewAdvanced()
demux_t * demux_NewAdvanced (vlc_object_t * p_obj, input_thread_t * p_parent_input, const char * psz_access, const char * psz_demux, const char * psz_path, stream_t * s, es_out_t * out, bool b_preparsing)
References demux_t::b_preparsing, demux_priv_t::demux, demux_DestroyAccessDemux(), demux_DestroyDemux(), demux_NameFromMimeType(), demux_Probe(), DemuxNameFromExtension(), demux_priv_t::destroy, get_path(), demux_t::i_seekpoint, demux_t::i_title, demux_t::i_update, demux_t::info, module_need, msg_Dbg, demux_t::out, demux_t::p_input, demux_t::p_module, demux_t::p_sys, demux_t::pf_control, demux_t::pf_demux, demux_t::psz_access, demux_t::psz_demux, psz_ext, demux_t::psz_file, demux_t::psz_location, demux_t::s, strcasecmp(), strdup(), stream_MimeType(), unlikely, vlc_custom_create, vlc_module_load, and vlc_object_release.
demux_TestAndClearFlags()
unsigned demux_TestAndClearFlags (demux_t * p_demux, unsigned flags)
< No error
References demux_Control(), DEMUX_TEST_AND_CLEAR_FLAGS, demux_t::i_update, demux_t::info, and VLC_SUCCESS.
Referenced by MainLoopDemux(), UpdateGenericFromDemux(), UpdateTitleSeekpointFromDemux(), and vlc_demux_chained_Thread().