VLC: src/input/demux.c File Reference
demux.c File Reference
Data Structures
struct demux_mapping
struct demux_priv_t
Macros
#define static_control_match(foo) static_assert((unsigned) DEMUX_##foo == STREAM_##foo, "Mismatch")
Typedefs
typedef struct demux_priv_t demux_priv_t
Functions
static int demux_mapping_cmp (const void *k, const void *v)
static demux_mapping * demux_lookup (char const *key, demux_mapping *data, size_t size)
static const char * demux_NameFromMimeType (const char *mime)
static const char * DemuxNameFromExtension (char const *ext, bool b_preparsing)
demux_t * demux_New (vlc_object_t *p_obj, const char *psz_name, const char *psz_location, stream_t *s, es_out_t *out)
static void demux_DestroyDemux (demux_t *demux)
static void demux_DestroyAccessDemux (demux_t *demux)
static void demux_DestroyDemuxFilter (demux_t *demux)
static int demux_Probe (void *func, va_list ap)
demux_t * demux_NewAdvanced (vlc_object_t *p_obj, input_thread_t *p_parent_input, const char *psz_access, const char *psz_demux, const char *psz_location, stream_t *s, es_out_t *out, bool b_preparsing)
void demux_Delete (demux_t *p_demux)
static int demux_ControlInternal (demux_t *demux, int query,...)
int demux_vaControl (demux_t *demux, int query, va_list args)
int demux_vaControlHelper (stream_t *s, int64_t i_start, int64_t i_end, int64_t i_bitrate, int i_align, int i_query, va_list args)
decoder_t * demux_PacketizerNew (demux_t *p_demux, es_format_t *p_fmt, const char *psz_msg)
This function will create a packetizer suitable for a demuxer that parses elementary stream.
void demux_PacketizerDestroy (decoder_t *p_packetizer)
This function will destroy a packetizer create by demux_PacketizerNew.
unsigned demux_TestAndClearFlags (demux_t *p_demux, unsigned flags)
int demux_GetTitle (demux_t *p_demux)
int demux_GetSeekpoint (demux_t *p_demux)
static demux_t * demux_FilterNew (demux_t *p_next, const char *p_name)
demux_t * demux_FilterChainNew (demux_t *p_demux, const char *psz_chain)
Builds an explicit chain of demux filters.
static bool demux_filter_enable_disable (demux_t *p_demux_chain, const char *psz_demux, bool b_enable)
bool demux_FilterEnable (demux_t *p_demux_chain, const char *psz_demux)
bool demux_FilterDisable (demux_t *p_demux_chain, const char *psz_demux)
Macro Definition Documentation
static_control_match
#define static_control_match (foo) static_assert((unsigned) DEMUX_##foo == STREAM_##foo, "Mismatch")
Referenced by demux_vaControlHelper().
Typedef Documentation
demux_priv_t
typedef struct demux_priv_t demux_priv_t
Function Documentation
demux_ControlInternal()
static int demux_ControlInternal (demux_t * demux, int query, ...) static
References demux_t::pf_control.
Referenced by demux_vaControl().
demux_DestroyAccessDemux()
static void demux_DestroyAccessDemux (demux_t * demux) static
References demux_t::s.
Referenced by demux_NewAdvanced().
demux_DestroyDemux()
static void demux_DestroyDemux (demux_t * demux) static
References demux_t::s, and vlc_stream_Delete().
Referenced by demux_NewAdvanced().
demux_DestroyDemuxFilter()
static void demux_DestroyDemuxFilter (demux_t * demux) static
References demux_Delete(), and demux_t::p_next.
Referenced by demux_FilterNew().
demux_filter_enable_disable()
static bool demux_filter_enable_disable (demux_t * p_demux_chain, const char * psz_demux, bool b_enable) static
References demux_Control(), DEMUX_FILTER_DISABLE, DEMUX_FILTER_ENABLE, module_get_name(), and demux_t::p_module.
Referenced by demux_FilterDisable(), and demux_FilterEnable().
demux_FilterChainNew()
demux_t * demux_FilterChainNew (demux_t * source, const char * list)
Builds an explicit chain of demux filters.
This function creates a chain of filters according to a supplied list.
See also stream_FilterChainNew(). Those two functions have identical semantics and ownership rules, except for the use of demux vs stream.
Parameters
source input stream around which to build a filter chain
list colon-separated list of stream filters (upstream first)
Returns
The last demux (filter) in the chain. The return value is always a valid (non-NULL) demux pointer.
References config_ChainCreate(), config_ChainDestroy(), demux_FilterNew(), psz_name, and strdup().
Referenced by ControlInsertDemuxFilter(), and InputSourceNew().
demux_FilterDisable()
bool demux_FilterDisable (demux_t * p_demux_chain, const char * psz_demux)
References demux_filter_enable_disable().
Referenced by Control().
demux_FilterEnable()
bool demux_FilterEnable (demux_t * p_demux_chain, const char * psz_demux)
References demux_filter_enable_disable().
Referenced by Control().
demux_FilterNew()
static demux_t * demux_FilterNew (demux_t * p_next, const char * p_name) static
References demux_priv_t::demux, demux_DestroyDemuxFilter(), demux_priv_t::destroy, module_need, demux_t::out, demux_t::p_input, demux_t::p_module, demux_t::p_next, demux_t::p_sys, demux_t::psz_access, demux_t::psz_demux, demux_t::psz_file, demux_t::psz_location, unlikely, vlc_custom_create, and vlc_object_release.
Referenced by demux_FilterChainNew().
demux_GetSeekpoint()
int demux_GetSeekpoint (demux_t * p_demux)
< No error
References demux_Control(), DEMUX_GET_SEEKPOINT, demux_t::i_seekpoint, demux_t::info, and VLC_SUCCESS.
Referenced by Control(), and UpdateTitleSeekpointFromDemux().
demux_GetTitle()
int demux_GetTitle (demux_t * p_demux)
< No error
References demux_Control(), DEMUX_GET_TITLE, demux_t::i_title, demux_t::info, and VLC_SUCCESS.
Referenced by Control(), and UpdateTitleSeekpointFromDemux().
demux_lookup()
static demux_mapping * demux_lookup (char const * key, demux_mapping * data, size_t size) static
References demux_mapping_cmp().
Referenced by demux_NameFromMimeType(), and DemuxNameFromExtension().
demux_mapping_cmp()
static int demux_mapping_cmp (const void * k, const void * v) static
References entry::key, and vlc_ascii_strcasecmp().
Referenced by demux_lookup().
demux_NameFromMimeType()
static const char * demux_NameFromMimeType (const char * mime) static
References ARRAY_SIZE, demux_lookup(), and demux_mapping::name.
Referenced by demux_NewAdvanced().
demux_NewAdvanced()
demux_t * demux_NewAdvanced (vlc_object_t * p_obj, input_thread_t * p_parent_input, const char * psz_access, const char * psz_demux, const char * psz_location, stream_t * s, es_out_t * out, bool b_preparsing)
References demux_t::b_preparsing, demux_priv_t::demux, demux_DestroyAccessDemux(), demux_DestroyDemux(), demux_NameFromMimeType(), demux_Probe(), DemuxNameFromExtension(), demux_priv_t::destroy, get_path(), demux_t::i_seekpoint, demux_t::i_title, demux_t::i_update, demux_t::info, module_need, msg_Dbg, demux_t::out, demux_t::p_input, demux_t::p_module, demux_t::p_sys, demux_t::pf_control, demux_t::pf_demux, demux_t::psz_access, demux_t::psz_demux, psz_ext, demux_t::psz_file, demux_t::psz_location, demux_t::s, strcasecmp(), strdup(), stream_MimeType(), unlikely, vlc_custom_create, vlc_module_load, and vlc_object_release.
demux_Probe()
static int demux_Probe (void * func, va_list ap) static
< Unspecified error
References msg_Err, demux_t::s, VLC_EGENERIC, VLC_OBJECT, vlc_stream_Seek(), and vlc_stream_Tell().
Referenced by demux_NewAdvanced().
demux_TestAndClearFlags()
unsigned demux_TestAndClearFlags (demux_t * p_demux, unsigned flags)
< No error
References demux_Control(), DEMUX_TEST_AND_CLEAR_FLAGS, demux_t::i_update, demux_t::info, and VLC_SUCCESS.
Referenced by MainLoopDemux(), UpdateGenericFromDemux(), UpdateTitleSeekpointFromDemux(), and vlc_demux_chained_Thread().
DemuxNameFromExtension()
static const char * DemuxNameFromExtension (char const * ext, bool b_preparsing) static
References ARRAY_SIZE, demux_lookup(), and demux_mapping::name.
Referenced by demux_NewAdvanced().