VLC: src/interface/dialog.c File Reference
dialog.c File Reference
Data Structures
struct vlc_dialog_provider
struct dialog_answer
struct dialog
struct vlc_dialog_id
struct dialog_i11e_context
Enumerations
enum dialog_type { VLC_DIALOG_ERROR , VLC_DIALOG_LOGIN , VLC_DIALOG_QUESTION , VLC_DIALOG_PROGRESS }
Functions
static vlc_dialog_provider * get_dialog_provider (vlc_object_t *p_obj, bool b_check_interact)
static void dialog_id_release (vlc_dialog_id *p_id)
int libvlc_InternalDialogInit (libvlc_int_t *p_libvlc)
static void dialog_cancel_locked (vlc_dialog_provider *p_provider, vlc_dialog_id *p_id)
static vlc_dialog_id * dialog_add_locked (vlc_dialog_provider *p_provider, enum dialog_type i_type)
static void dialog_remove_locked (vlc_dialog_provider *p_provider, vlc_dialog_id *p_id)
static void dialog_clear_all_locked (vlc_dialog_provider *p_provider)
void libvlc_InternalDialogClean (libvlc_int_t *p_libvlc)
void vlc_dialog_provider_set_callbacks (vlc_object_t *p_obj, const vlc_dialog_cbs *p_cbs, void *p_data)
Register callbacks to handle VLC dialogs.
static void dialog_wait_interrupted (void *p_data)
static int dialog_wait (vlc_dialog_provider *p_provider, vlc_dialog_id *p_id, enum dialog_type i_type, struct dialog_answer *p_answer)
static int dialog_display_error_va (vlc_dialog_provider *p_provider, const char *psz_title, const char *psz_fmt, va_list ap)
int vlc_dialog_display_error_va (vlc_object_t *p_obj, const char *psz_title, const char *psz_fmt, va_list ap)
Sends an error message.
int vlc_dialog_display_error (vlc_object_t *p_obj, const char *psz_title, const char *psz_fmt,...)
Sends an error message.
static int dialog_display_login_va (vlc_dialog_provider *p_provider, vlc_dialog_id **pp_id, const char *psz_default_username, bool b_ask_store, const char *psz_title, const char *psz_fmt, va_list ap)
int vlc_dialog_wait_login_va (vlc_object_t *p_obj, char **ppsz_username, char **ppsz_password, bool *p_store, const char *psz_default_username, const char *psz_title, const char *psz_fmt, va_list ap)
Requests an user name and a password.
int vlc_dialog_wait_login (vlc_object_t *p_obj, char **ppsz_username, char **ppsz_password, bool *p_store, const char *psz_default_username, const char *psz_title, const char *psz_fmt,...)
Requests an user name and a password.
static int dialog_display_question_va (vlc_dialog_provider *p_provider, vlc_dialog_id **pp_id, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2, const char *psz_title, const char *psz_fmt, va_list ap)
int vlc_dialog_wait_question_va (vlc_object_t *p_obj, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2, const char *psz_title, const char *psz_fmt, va_list ap)
Asks a total (Yes/No/Cancel) question.
int vlc_dialog_wait_question (vlc_object_t *p_obj, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2, const char *psz_title, const char *psz_fmt,...)
Asks a total (Yes/No/Cancel) question.
static int display_progress_va (vlc_dialog_provider *p_provider, vlc_dialog_id **pp_id, bool b_indeterminate, float f_position, const char *psz_cancel, const char *psz_title, const char *psz_fmt, va_list ap)
vlc_dialog_id * vlc_dialog_display_progress_va (vlc_object_t *p_obj, bool b_indeterminate, float f_position, const char *psz_cancel, const char *psz_title, const char *psz_fmt, va_list ap)
Display a progress dialog.
vlc_dialog_id * vlc_dialog_display_progress (vlc_object_t *p_obj, bool b_indeterminate, float f_position, const char *psz_cancel, const char *psz_title, const char *psz_fmt,...)
Display a progress dialog.
static int dialog_update_progress (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_value, char *psz_text)
int vlc_dialog_update_progress (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_value)
Update the position of the progress dialog.
int vlc_dialog_update_progress_text_va (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_value, const char *psz_fmt, va_list ap)
Update the position and the message of the progress dialog.
int vlc_dialog_update_progress_text (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_value, const char *psz_fmt,...)
Update the position and the message of the progress dialog.
void vlc_dialog_release (vlc_object_t *p_obj, vlc_dialog_id *p_id)
Release the dialog id returned by vlc_dialog_display_progress()
bool vlc_dialog_is_cancelled (vlc_object_t *p_obj, vlc_dialog_id *p_id)
Return true if the dialog id is cancelled.
void vlc_dialog_id_set_context (vlc_dialog_id *p_id, void *p_context)
Associate an opaque pointer with the dialog id.
void * vlc_dialog_id_get_context (vlc_dialog_id *p_id)
Return the opaque pointer associated with the dialog id.
static int dialog_id_post (vlc_dialog_id *p_id, struct dialog_answer *p_answer)
int vlc_dialog_id_post_login (vlc_dialog_id *p_id, const char *psz_username, const char *psz_password, bool b_store)
Post a login answer.
int vlc_dialog_id_post_action (vlc_dialog_id *p_id, int i_action)
Post a question answer.
int vlc_dialog_id_dismiss (vlc_dialog_id *p_id)
Dismiss a dialog.
void vlc_dialog_provider_set_ext_callback (vlc_object_t *p_obj, vlc_dialog_ext_update_cb pf_update, void *p_data)
Register a callback for VLC extension dialog.
int vlc_ext_dialog_update (vlc_object_t *p_obj, extension_dialog_t *p_ext_dialog)
Enumeration Type Documentation
dialog_type
enum dialog_type
Enumerator
VLC_DIALOG_ERROR
VLC_DIALOG_LOGIN
VLC_DIALOG_QUESTION
VLC_DIALOG_PROGRESS
Function Documentation
dialog_add_locked()
static vlc_dialog_id * dialog_add_locked (vlc_dialog_provider * p_provider, enum dialog_type i_type) static
References vlc_dialog_provider::dialog_array, vlc_dialog_id::i_refcount, i_type, vlc_dialog_id::i_type, vlc_dialog_id::lock, vlc_array_append(), vlc_cond_init(), vlc_mutex_init(), and vlc_dialog_id::wait.
Referenced by dialog_display_login_va(), dialog_display_question_va(), and display_progress_va().
dialog_cancel_locked()
static void dialog_cancel_locked (vlc_dialog_provider * p_provider, vlc_dialog_id * p_id) static
References vlc_dialog_id::b_answered, vlc_dialog_id::b_cancelled, vlc_dialog_provider::cbs, vlc_dialog_id::lock, vlc_dialog_provider::p_cbs_data, vlc_dialog_cbs::pf_cancel, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by dialog_clear_all_locked(), dialog_wait_interrupted(), and vlc_dialog_release().
dialog_clear_all_locked()
static void dialog_clear_all_locked (vlc_dialog_provider * p_provider) static
References vlc_dialog_provider::dialog_array, dialog_cancel_locked(), vlc_array_count(), and vlc_array_item_at_index.
Referenced by libvlc_InternalDialogClean(), and vlc_dialog_provider_set_callbacks().
dialog_display_error_va()
static int dialog_display_error_va (vlc_dialog_provider * p_provider, const char * psz_title, const char * psz_fmt, va_list ap) static
< Unspecified error
< Not enough memory
< No error
References vlc_dialog_provider::cbs, vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, dialog_i11e_context::p_provider, vlc_dialog_cbs::pf_display_error, vasprintf(), VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vlc_dialog_display_error_va().
dialog_display_login_va()
static int dialog_display_login_va (vlc_dialog_provider * p_provider, vlc_dialog_id ** pp_id, const char * psz_default_username, bool b_ask_store, const char * psz_title, const char * psz_fmt, va_list ap) static
< Unspecified error
< Not enough memory
< Not enough memory
< No error
References vlc_dialog_provider::cbs, dialog_add_locked(), vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, dialog_i11e_context::p_id, dialog_i11e_context::p_provider, vlc_dialog_cbs::pf_cancel, vlc_dialog_cbs::pf_display_login, vasprintf(), VLC_DIALOG_LOGIN, VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vlc_dialog_wait_login_va().
dialog_display_question_va()
static int dialog_display_question_va (vlc_dialog_provider * p_provider, vlc_dialog_id ** pp_id, vlc_dialog_question_type i_type, const char * psz_cancel, const char * psz_action1, const char * psz_action2, const char * psz_title, const char * psz_fmt, va_list ap) static
< Unspecified error
< Not enough memory
< Not enough memory
< No error
References vlc_dialog_provider::cbs, dialog_add_locked(), i_type, vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, vlc_dialog_cbs::pf_cancel, vlc_dialog_cbs::pf_display_question, vasprintf(), VLC_DIALOG_QUESTION, VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vlc_dialog_wait_question_va().
dialog_id_post()
static int dialog_id_post (vlc_dialog_id * p_id, struct dialog_answer * p_answer) static
< No error
References vlc_dialog_id::answer, vlc_dialog_id::b_answered, vlc_dialog_id::b_cancelled, dialog_id_release(), vlc_dialog_id::i_refcount, vlc_dialog_id::lock, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and vlc_dialog_id::wait.
Referenced by vlc_dialog_id_dismiss(), vlc_dialog_id_post_action(), and vlc_dialog_id_post_login().
dialog_id_release()
static void dialog_id_release (vlc_dialog_id * p_id) static
References vlc_dialog_id::answer, dialog_answer::i_type, vlc_dialog_id::lock, dialog_answer::login, dialog_answer::psz_password, vlc_dialog_id::psz_progress_text, dialog_answer::psz_username, dialog_answer::u, vlc_cond_destroy(), VLC_DIALOG_LOGIN, vlc_mutex_destroy(), and vlc_dialog_id::wait.
Referenced by dialog_id_post(), and dialog_remove_locked().
dialog_remove_locked()
static void dialog_remove_locked (vlc_dialog_provider * p_provider, vlc_dialog_id * p_id) static
References vlc_dialog_provider::dialog_array, dialog_id_release(), vlc_dialog_id::i_refcount, vlc_dialog_id::lock, vlc_array_index_of_item(), vlc_array_remove(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by dialog_wait(), and vlc_dialog_release().
dialog_update_progress()
static int dialog_update_progress (vlc_object_t * p_obj, vlc_dialog_id * p_id, float f_value, char * psz_text) static
< Unspecified error
< No error
References vlc_dialog_id::b_progress_indeterminate, vlc_dialog_provider::cbs, f_value, get_dialog_provider(), vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, vlc_dialog_cbs::pf_update_progress, vlc_dialog_id::psz_progress_text, vlc_dialog_is_cancelled, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vlc_dialog_update_progress(), and vlc_dialog_update_progress_text_va().
dialog_wait()
static int dialog_wait (vlc_dialog_provider * p_provider, vlc_dialog_id * p_id, enum dialog_type i_type, struct dialog_answer * p_answer) static
< Unspecified error
References vlc_dialog_id::answer, vlc_dialog_id::b_answered, vlc_dialog_id::b_cancelled, dialog_remove_locked(), dialog_wait_interrupted(), dialog_answer::i_type, i_type, vlc_dialog_id::lock, vlc_dialog_provider::lock, dialog_i11e_context::p_id, dialog_i11e_context::p_provider, vlc_cond_wait(), VLC_EGENERIC, vlc_interrupt_register(), vlc_interrupt_unregister(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_dialog_id::wait.
Referenced by vlc_dialog_wait_login_va(), and vlc_dialog_wait_question_va().
dialog_wait_interrupted()
static void dialog_wait_interrupted (void * p_data) static
References dialog_cancel_locked(), vlc_dialog_id::lock, vlc_dialog_provider::lock, dialog_i11e_context::p_id, dialog_i11e_context::p_provider, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_dialog_id::wait.
Referenced by dialog_wait().
display_progress_va()
static int display_progress_va (vlc_dialog_provider * p_provider, vlc_dialog_id ** pp_id, bool b_indeterminate, float f_position, const char * psz_cancel, const char * psz_title, const char * psz_fmt, va_list ap) static
< Unspecified error
< Not enough memory
< Not enough memory
< No error
References vlc_dialog_id::b_progress_indeterminate, vlc_dialog_provider::cbs, dialog_add_locked(), vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, vlc_dialog_cbs::pf_cancel, vlc_dialog_cbs::pf_display_progress, vlc_dialog_cbs::pf_update_progress, vlc_dialog_id::psz_progress_text, vasprintf(), VLC_DIALOG_PROGRESS, VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vlc_dialog_display_progress_va().
get_dialog_provider()
static vlc_dialog_provider * get_dialog_provider (vlc_object_t * p_obj, bool b_check_interact) inline static
References vlc_common_members::flags, vlc_common_members::libvlc, libvlc_priv(), vlc_object_t::obj, OBJECT_FLAGS_NOINTERACT, and libvlc_priv_t::p_dialog_provider.
Referenced by dialog_update_progress(), vlc_dialog_display_error_va(), vlc_dialog_display_progress_va(), vlc_dialog_provider_set_callbacks(), vlc_dialog_provider_set_ext_callback(), vlc_dialog_release(), vlc_dialog_wait_login_va(), vlc_dialog_wait_question_va(), and vlc_ext_dialog_update().
libvlc_InternalDialogClean()
void libvlc_InternalDialogClean (libvlc_int_t * p_libvlc)
References dialog_clear_all_locked(), libvlc_priv(), vlc_dialog_provider::lock, libvlc_priv_t::p_dialog_provider, vlc_mutex_destroy(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by libvlc_InternalCleanup().
libvlc_InternalDialogInit()
int libvlc_InternalDialogInit (libvlc_int_t * p_libvlc)
< Unspecified error
< No error
References vlc_dialog_provider::cbs, vlc_dialog_provider::dialog_array, libvlc_priv(), vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, libvlc_priv_t::p_dialog_provider, vlc_dialog_provider::p_ext_data, vlc_dialog_provider::pf_ext_update, vlc_array_init(), VLC_EGENERIC, vlc_mutex_init(), and VLC_SUCCESS.
Referenced by libvlc_InternalInit().