VLC: src/video_output/display.h File Reference
display.h File Reference
Functions
vout_display_t * vout_NewSplitter (vout_thread_t *vout, const video_format_t *source, const vout_display_state_t *state, const char *module, const char *splitter_module, mtime_t double_click_timeout, mtime_t hide_timeout)
void vout_SendDisplayEventMouse (vout_thread_t *, const vlc_mouse_t *)
vout_window_t * vout_NewDisplayWindow (vout_thread_t *, unsigned type)
void vout_DeleteDisplayWindow (vout_thread_t *, vout_window_t *)
void vout_SetDisplayWindowSize (vout_thread_t *, unsigned, unsigned)
int vout_HideWindowMouse (vout_thread_t *, bool)
void vout_UpdateDisplaySourceProperties (vout_display_t *vd, const video_format_t *)
Function Documentation
vout_DeleteDisplayWindow()
void vout_DeleteDisplayWindow (vout_thread_t * vout, vout_window_t * window)
References vout_thread_t::p, vout_display_window_Delete(), and vout_thread_sys_t::window.
Referenced by VoutDisplayDelWindow().
vout_HideWindowMouse()
int vout_HideWindowMouse (vout_thread_t * vout, bool hide)
< Unspecified error
References vout_thread_t::p, VLC_EGENERIC, vout_window_HideMouse(), and vout_thread_sys_t::window.
Referenced by vout_ManageDisplay().
vout_NewDisplayWindow()
vout_window_t * vout_NewDisplayWindow (vout_thread_t * vout, unsigned type)
References vout_thread_t::p, vout_thread_sys_t::splitter_name, vout_window_t::type, VOUT_WINDOW_TYPE_INVALID, and vout_thread_sys_t::window.
Referenced by VoutDisplayNewWindow().
vout_NewSplitter()
vout_display_t * vout_NewSplitter (vout_thread_t * vout, const video_format_t * source, const vout_display_state_t * state, const char * module, const char * splitter_module, mtime_t double_click_timeout, mtime_t hide_timeout)
References vout_display_cfg_t::align, vout_display_state_t::cfg, vout_display_t::control, vout_display_sys_t::count, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_display_sys_t::display, vout_display_t::display, DisplayNew(), vout_display_owner_t::event, video_splitter_output_t::fmt, vout_display_cfg_t::horizontal, video_splitter_t::i_output, vout_display_cfg_t::is_display_filled, vout_display_t::manage, vout_display_cfg_t::num, video_splitter_t::p_output, video_splitter_t::p_owner, video_splitter_t::pf_picture_del, video_splitter_t::pf_picture_new, vout_display_sys_t::picture, vout_display_sys_t::pool, vout_display_t::pool, vout_display_t::prepare, video_splitter_output_t::psz_module, vout_display_sys_t::splitter, SplitterControl(), SplitterDelWindow(), SplitterDisplay(), SplitterEvent(), SplitterManage(), SplitterNewWindow(), SplitterPictureDel(), SplitterPictureNew(), SplitterPool(), SplitterPrepare(), vout_display_t::sys, TAB_APPEND, TAB_INIT, vout_display_cfg_t::vertical, video_splitter_Delete(), video_splitter_New(), VLC_OBJECT, vout_DeleteDisplay(), video_splitter_owner_t::wrapper, xmalloc(), and vout_display_cfg_t::zoom.
Referenced by vout_OpenWrapper().
vout_SendDisplayEventMouse()
void vout_SendDisplayEventMouse (vout_thread_t * vout, const vlc_mouse_t * m)
References vlc_mouse_t::b_double_click, vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, vout_thread_sys_t::display, vout_thread_sys_t::filter, filter_chain_MouseFilter(), vlc_mouse_t::i_x, vlc_mouse_t::i_y, vout_thread_sys_t::lock, vout_thread_sys_t::mouse, MOUSE_BUTTON_MAX, vout_thread_t::p, vout_display_t::source, vout_thread_sys_t::spu, spu_ProcessMouse(), vout_thread_sys_t::vd, vlc_mouse_HasButton(), vlc_mouse_HasMoved(), vlc_mouse_HasPressed(), vlc_mouse_HasReleased(), vlc_mutex_lock(), vlc_mutex_unlock(), vout_SendEventMouseDoubleClick(), vout_SendEventMouseMoved(), vout_SendEventMousePressed(), and vout_SendEventMouseReleased().
Referenced by VoutDisplayEventMouse().
vout_SetDisplayWindowSize()
void vout_SetDisplayWindowSize (vout_thread_t * vout, unsigned width, unsigned height)
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, vout_display_SendEventDisplaySize(), vout_window_SetSize(), and vout_thread_sys_t::window.
Referenced by vout_ManageDisplay(), and VoutDisplayFitWindow().
vout_UpdateDisplaySourceProperties()
void vout_UpdateDisplaySourceProperties (vout_display_t * vd, const video_format_t * source)
References vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::ch_sar, vlc_rational_t::den, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_owner_t::sys, video_format_CopyCrop(), and vlc_ureduce().
Referenced by ThreadDisplayRenderPicture().