VLC: src/video_output/display.c File Reference
display.c File Reference
Data Structures
struct vout_display_owner_sys_t
struct vout_display_sys_t
struct video_splitter_owner_t
Functions
static void SplitterClose (vout_display_t *vd)
static picture_t * VideoBufferNew (filter_t *filter)
static vout_display_t * vout_display_New (vlc_object_t *obj, const char *module, bool load_module, const video_format_t *fmt, const vout_display_cfg_t *cfg, vout_display_owner_t *owner)
It creates a new vout_display_t using the given configuration.
static void vout_display_Delete (vout_display_t *vd)
It deletes a vout_display_t.
static int vout_display_Control (vout_display_t *vd, int query,...)
It controls a vout_display_t.
static void vout_display_Manage (vout_display_t *vd)
void vout_display_GetDefaultDisplaySize (unsigned *width, unsigned *height, const video_format_t *source, const vout_display_cfg_t *cfg)
Computes the default display size given the source and the display configuration.
void vout_display_PlacePicture (vout_display_place_t *place, const video_format_t *source, const vout_display_cfg_t *cfg, bool do_clipping)
Computes how to place a picture inside the display to respect the given parameters.
void vout_display_SendMouseMovedDisplayCoordinates (vout_display_t *vd, video_orientation_t orient_display, int m_x, int m_y, vout_display_place_t *place)
Helper function that applies the necessary transforms to the mouse position and then calls vout_display_SendEventMouseMoved.
static int VoutDisplayCreateRender (vout_display_t *vd)
static void VoutDisplayDestroyRender (vout_display_t *vd)
static int VoutDisplayResetRender (vout_display_t *vd)
static void VoutDisplayEventMouse (vout_display_t *vd, int event, va_list args)
static void VoutDisplayEvent (vout_display_t *vd, int event, va_list args)
static vout_window_t * VoutDisplayNewWindow (vout_display_t *vd, unsigned type)
static void VoutDisplayDelWindow (vout_display_t *vd, vout_window_t *window)
static void VoutDisplayFitWindow (vout_display_t *vd, bool default_size)
static void VoutDisplayCropRatio (int *left, int *top, int *right, int *bottom, const video_format_t *source, unsigned num, unsigned den)
bool vout_ManageDisplay (vout_display_t *vd, bool allow_reset_pictures)
bool vout_AreDisplayPicturesInvalid (vout_display_t *vd)
bool vout_IsDisplayFiltered (vout_display_t *vd)
picture_t * vout_FilterDisplay (vout_display_t *vd, picture_t *picture)
void vout_FilterFlush (vout_display_t *vd)
void vout_UpdateDisplaySourceProperties (vout_display_t *vd, const video_format_t *source)
void vout_SetDisplayFilled (vout_display_t *vd, bool is_filled)
void vout_SetDisplayZoom (vout_display_t *vd, unsigned num, unsigned den)
void vout_SetDisplayAspect (vout_display_t *vd, unsigned dar_num, unsigned dar_den)
void vout_SetDisplayCrop (vout_display_t *vd, unsigned crop_num, unsigned crop_den, unsigned left, unsigned top, int right, int bottom)
void vout_SetDisplayViewpoint (vout_display_t *vd, const vlc_viewpoint_t *p_viewpoint)
static vout_display_t * DisplayNew (vout_thread_t *vout, const video_format_t *source, const vout_display_state_t *state, const char *module, bool is_splitter, mtime_t double_click_timeout, mtime_t hide_timeout, const vout_display_owner_t *owner_ptr)
void vout_DeleteDisplay (vout_display_t *vd, vout_display_state_t *state)
It destroy a vout managed display.
vout_display_t * vout_NewDisplay (vout_thread_t *vout, const video_format_t *source, const vout_display_state_t *state, const char *module, mtime_t double_click_timeout, mtime_t hide_timeout)
It creates a vout managed display.
static vout_window_t * SplitterNewWindow (vout_display_t *vd, unsigned type)
static void SplitterDelWindow (vout_display_t *vd, vout_window_t *window)
static void SplitterEvent (vout_display_t *vd, int event, va_list args)
static picture_pool_t * SplitterPool (vout_display_t *vd, unsigned count)
static void SplitterPrepare (vout_display_t *vd, picture_t *picture, subpicture_t *subpicture)
static void SplitterDisplay (vout_display_t *vd, picture_t *picture, subpicture_t *subpicture)
static int SplitterControl (vout_display_t *vd, int query, va_list args)
static void SplitterManage (vout_display_t *vd)
static int SplitterPictureNew (video_splitter_t *splitter, picture_t *picture[])
static void SplitterPictureDel (video_splitter_t *splitter, picture_t *picture[])
vout_display_t * vout_NewSplitter (vout_thread_t *vout, const video_format_t *source, const vout_display_state_t *state, const char *module, const char *splitter_module, mtime_t double_click_timeout, mtime_t hide_timeout)
void vout_SendDisplayEventMouse (vout_thread_t *vout, const vlc_mouse_t *m)
Function Documentation
DisplayNew()
static vout_display_t * DisplayNew (vout_thread_t * vout, const video_format_t * source, const vout_display_state_t * state, const char * module, bool is_splitter, mtime_t double_click_timeout, mtime_t hide_timeout, const vout_display_owner_t * owner_ptr) static
References vout_display_owner_sys_t::bottom, vout_display_owner_sys_t::cfg, vout_display_state_t::cfg, vout_display_owner_sys_t::ch_sar, vout_display_owner_sys_t::crop, vlc_rational_t::den, vout_display_cfg_t::den, vout_display_owner_sys_t::den, vout_display_cfg_t::display, vout_display_owner_sys_t::display_height, vout_display_owner_sys_t::display_width, vout_display_owner_sys_t::double_click_timeout, vout_display_owner_t::event, vout_display_owner_sys_t::fit_window, vout_display_t::fmt, vout_display_cfg_t::height, vout_display_owner_sys_t::hide_timeout, video_format_t::i_sar_den, video_format_t::i_sar_num, vout_display_cfg_t::is_display_filled, vout_display_owner_sys_t::is_display_filled, vout_display_owner_sys_t::is_splitter, vout_display_owner_sys_t::last_moved, vout_display_owner_sys_t::left, vout_display_owner_sys_t::lock, mdate(), vout_display_owner_sys_t::mouse, vlc_rational_t::num, vout_display_cfg_t::num, vout_display_owner_sys_t::num, video_format_t::projection_mode, PROJECTION_MODE_RECTANGULAR, vout_display_owner_sys_t::right, vout_display_owner_sys_t::sar, vout_display_state_t::sar, vout_display_owner_sys_t::sar_initial, vout_display_owner_sys_t::source, vout_display_owner_sys_t::state, vout_display_owner_t::sys, vout_display_owner_sys_t::top, vout_display_cfg_t::viewpoint, vout_display_owner_sys_t::viewpoint, vlc_mouse_Init(), vlc_mutex_destroy(), vlc_mutex_init(), VLC_OBJECT, vout_display_owner_sys_t::vout, vout_display_Delete(), vout_display_GetDefaultDisplaySize(), vout_display_New(), vout_SendEventViewpointChangeable(), VOUT_WINDOW_STATE_NORMAL, VoutDisplayCreateRender(), VoutDisplayDelWindow(), VoutDisplayEvent(), VoutDisplayNewWindow(), vout_display_cfg_t::width, vout_display_owner_t::window_del, vout_display_owner_t::window_new, vout_display_cfg_t::zoom, and vout_display_owner_sys_t::zoom.
Referenced by vout_NewDisplay(), and vout_NewSplitter().
SplitterClose()
static void SplitterClose (vout_display_t * vd) static
References vout_display_sys_t::count, vout_display_sys_t::display, video_splitter_t::p_owner, vout_display_sys_t::picture, picture_pool_Release(), vout_display_sys_t::pool, vout_display_sys_t::splitter, vout_display_t::sys, TAB_CLEAN, video_splitter_Delete(), and vout_DeleteDisplay().
Referenced by vout_DeleteDisplay().
SplitterControl()
static int SplitterControl (vout_display_t * vd, int query, va_list args) static
< Unspecified error
References VLC_EGENERIC.
Referenced by vout_NewSplitter().
SplitterDelWindow()
static void SplitterDelWindow (vout_display_t * vd, vout_window_t * window) static
References vout_display_window_Delete(), and vout_display_window_Detach().
Referenced by vout_NewSplitter().
SplitterDisplay()
static void SplitterDisplay (vout_display_t * vd, picture_t * picture, subpicture_t * subpicture) static
References vout_display_sys_t::count, vout_display_sys_t::display, vout_display_sys_t::picture, picture_Release(), vout_display_t::sys, and vout_display_Display().
Referenced by vout_NewSplitter().
SplitterEvent()
static void SplitterEvent (vout_display_t * vd, int event, va_list args) static
References msg_Err, VOUT_DISPLAY_EVENT_CLOSE, VOUT_DISPLAY_EVENT_DISPLAY_SIZE, VOUT_DISPLAY_EVENT_KEY, VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK, VOUT_DISPLAY_EVENT_MOUSE_MOVED, VOUT_DISPLAY_EVENT_MOUSE_PRESSED, VOUT_DISPLAY_EVENT_MOUSE_RELEASED, VOUT_DISPLAY_EVENT_MOUSE_STATE, VOUT_DISPLAY_EVENT_PICTURES_INVALID, and VoutDisplayEvent().
Referenced by vout_NewSplitter().
SplitterManage()
static void SplitterManage (vout_display_t * vd) static
References vout_display_sys_t::count, vout_display_sys_t::display, vout_display_t::sys, and vout_ManageDisplay().
Referenced by vout_NewSplitter().
SplitterNewWindow()
static vout_window_t * SplitterNewWindow (vout_display_t * vd, unsigned type) static
References vout_display_t::cfg, vout_display_cfg_t::display, vout_display_cfg_t::height, vout_display_t::owner, vout_display_owner_t::sys, vout_window_cfg_t::type, vout_display_owner_sys_t::vout, vout_display_window_Attach(), vout_display_window_New(), and vout_display_cfg_t::width.
Referenced by vout_NewSplitter().
SplitterPictureDel()
static void SplitterPictureDel (video_splitter_t * splitter, picture_t * picture[]) static
References vout_display_sys_t::count, video_splitter_t::p_owner, picture_Release(), vout_display_t::sys, and video_splitter_owner_t::wrapper.
Referenced by vout_NewSplitter().
SplitterPictureNew()
static int SplitterPictureNew (video_splitter_t * splitter, picture_t * picture[]) static
< Unspecified error
< No error
References vout_display_sys_t::count, vout_display_sys_t::display, video_splitter_t::p_owner, picture_NewFromFormat(), picture_pool_Get(), picture_Release(), vout_display_t::source, vout_display_t::sys, VLC_EGENERIC, VLC_SUCCESS, vout_display_Pool(), vout_IsDisplayFiltered(), and video_splitter_owner_t::wrapper.
Referenced by vout_NewSplitter().
SplitterPool()
static picture_pool_t * SplitterPool (vout_display_t * vd, unsigned count) static
References count, vout_display_t::fmt, picture_pool_NewFromFormat(), vout_display_sys_t::pool, and vout_display_t::sys.
Referenced by vout_NewSplitter().
SplitterPrepare()
static void SplitterPrepare (vout_display_t * vd, picture_t * picture, subpicture_t * subpicture) static
References vout_display_sys_t::count, vout_display_sys_t::display, vout_display_sys_t::picture, picture_Hold(), vout_display_sys_t::splitter, vout_display_t::sys, video_splitter_Filter(), vout_display_Prepare(), and vout_FilterDisplay().
Referenced by vout_NewSplitter().
VideoBufferNew()
static picture_t * VideoBufferNew (filter_t * filter) static
References vout_display_t::fmt, filter_t::fmt_out, video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_width, filter_t::owner, picture_pool_Get(), filter_owner_t::sys, es_format_t::video, and vout_display_Pool().
Referenced by VoutDisplayCreateRender().
vout_AreDisplayPicturesInvalid()
bool vout_AreDisplayPicturesInvalid (vout_display_t * vd)
References vout_display_owner_sys_t::lock, vout_display_t::owner, vout_display_owner_sys_t::reset_pictures, vout_display_owner_t::sys, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vout_ManageWrapper().
vout_DeleteDisplay()
void vout_DeleteDisplay (vout_display_t * vd, vout_display_state_t * state)
It destroy a vout managed display.
References vout_display_owner_sys_t::cfg, vout_display_state_t::cfg, vout_display_owner_sys_t::is_splitter, vout_display_owner_sys_t::lock, vout_display_t::owner, vout_display_state_t::sar, vout_display_owner_sys_t::sar_initial, SplitterClose(), vout_display_owner_t::sys, vlc_mutex_destroy(), vout_display_Delete(), and VoutDisplayDestroyRender().
Referenced by SplitterClose(), vout_CloseWrapper(), and vout_NewSplitter().
vout_display_Control()
static int vout_display_Control (vout_display_t * vd, int query, ...) static
It controls a vout_display_t.
References vout_display_t::control.
Referenced by vout_ManageDisplay().
vout_display_Delete()
static void vout_display_Delete (vout_display_t * vd) static
It deletes a vout_display_t.
References vout_display_t::fmt, vout_display_t::module, module_unneed, vout_display_t::source, video_format_Clean(), and vlc_object_release.
Referenced by DisplayNew(), and vout_DeleteDisplay().
vout_display_Manage()
static void vout_display_Manage (vout_display_t * vd) static
References vout_display_t::manage.
Referenced by vout_ManageDisplay().
vout_display_New()
static vout_display_t * vout_display_New (vlc_object_t * obj, const char * module, bool load_module, const video_format_t * fmt, const vout_display_cfg_t * cfg, vout_display_owner_t * owner) static
It creates a new vout_display_t using the given configuration.
References vout_display_t::cfg, vout_display_t::control, vout_display_t::display, vout_display_t::fmt, vout_display_info_t::has_double_click, vout_display_info_t::has_pictures_invalid, video_format_t::i_sar_den, video_format_t::i_sar_num, vout_display_t::info, vout_display_info_t::is_slow, vout_display_t::manage, vout_display_t::module, module_need, vout_display_info_t::needs_hide_mouse, vout_display_t::owner, vout_display_t::pool, vout_display_t::prepare, vout_display_t::source, vout_display_info_t::subpicture_chromas, vout_display_t::sys, video_format_Copy(), vlc_custom_create, and vlc_object_release.
Referenced by DisplayNew().
vout_FilterDisplay()
picture_t * vout_FilterDisplay (vout_display_t * vd, picture_t * picture)
References filter_chain_VideoFilter(), vout_display_owner_sys_t::filters, vout_display_t::owner, picture_Release(), and vout_display_owner_t::sys.
Referenced by SplitterPrepare(), and ThreadDisplayRenderPicture().
vout_FilterFlush()
void vout_FilterFlush (vout_display_t * vd)
References filter_chain_VideoFlush(), vout_display_owner_sys_t::filters, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by ThreadFlush().
vout_IsDisplayFiltered()
bool vout_IsDisplayFiltered (vout_display_t * vd)
References filter_chain_IsEmpty(), vout_display_owner_sys_t::filters, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by SplitterPictureNew(), ThreadDisplayRenderPicture(), vout_InitWrapper(), and vout_ManageWrapper().
vout_ManageDisplay()
bool vout_ManageDisplay (vout_display_t * vd, bool allow_reset_pictures)
< No error
References vout_display_owner_sys_t::bottom, vout_display_owner_sys_t::cfg, vout_display_owner_sys_t::ch_activity, vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::ch_display_size, vout_display_owner_sys_t::ch_sar, vout_display_owner_sys_t::ch_viewpoint, vout_display_owner_sys_t::ch_zoom, vout_display_owner_sys_t::crop, vlc_rational_t::den, vout_display_cfg_t::den, vout_display_owner_sys_t::den, vout_display_cfg_t::display, vout_display_owner_sys_t::display_height, vout_display_owner_sys_t::display_width, vout_display_owner_sys_t::fit_window, vout_display_cfg_t::height, vout_display_owner_sys_t::hide_timeout, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, vout_display_t::info, vout_display_cfg_t::is_display_filled, vout_display_owner_sys_t::is_display_filled, vout_display_owner_sys_t::is_hidden, vout_display_owner_sys_t::last_moved, vout_display_owner_sys_t::left, vout_display_owner_sys_t::lock, mdate(), vout_display_owner_sys_t::mouse, msg_Dbg, msg_Err, vout_display_info_t::needs_hide_mouse, vlc_rational_t::num, vout_display_cfg_t::num, vout_display_owner_sys_t::num, vout_display_t::owner, vout_display_owner_sys_t::reset_pictures, vout_display_owner_sys_t::right, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_t::source, vout_display_owner_t::sys, vout_display_owner_sys_t::top, video_format_Print(), vout_display_cfg_t::viewpoint, vout_display_owner_sys_t::viewpoint, VLC_CLIP, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, VLC_SUCCESS, vout_display_owner_sys_t::vout, VOUT_DISPLAY_CHANGE_DISPLAY_FILLED, VOUT_DISPLAY_CHANGE_DISPLAY_SIZE, VOUT_DISPLAY_CHANGE_SOURCE_ASPECT, VOUT_DISPLAY_CHANGE_SOURCE_CROP, VOUT_DISPLAY_CHANGE_VIEWPOINT, VOUT_DISPLAY_CHANGE_ZOOM, vout_display_Control(), VOUT_DISPLAY_HIDE_MOUSE, vout_display_Manage(), VOUT_DISPLAY_RESET_PICTURES, vout_HideWindowMouse(), vout_SetDisplayWindowSize(), VoutDisplayCropRatio(), VoutDisplayFitWindow(), VoutDisplayResetRender(), vout_display_cfg_t::width, vout_display_cfg_t::zoom, and vout_display_owner_sys_t::zoom.
Referenced by SplitterManage(), and vout_ManageWrapper().
vout_NewDisplay()
vout_display_t * vout_NewDisplay (vout_thread_t * vout, const video_format_t * source, const vout_display_state_t * state, const char * module, mtime_t double_click_timeout, mtime_t hide_timeout)
It creates a vout managed display.
References DisplayNew().
Referenced by vout_OpenWrapper().
vout_NewSplitter()
vout_display_t * vout_NewSplitter (vout_thread_t * vout, const video_format_t * source, const vout_display_state_t * state, const char * module, const char * splitter_module, mtime_t double_click_timeout, mtime_t hide_timeout)
References vout_display_cfg_t::align, vout_display_state_t::cfg, vout_display_t::control, vout_display_sys_t::count, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_display_sys_t::display, vout_display_t::display, DisplayNew(), vout_display_owner_t::event, video_splitter_output_t::fmt, vout_display_cfg_t::horizontal, video_splitter_t::i_output, vout_display_cfg_t::is_display_filled, vout_display_t::manage, vout_display_cfg_t::num, video_splitter_t::p_output, video_splitter_t::p_owner, video_splitter_t::pf_picture_del, video_splitter_t::pf_picture_new, vout_display_sys_t::picture, vout_display_sys_t::pool, vout_display_t::pool, vout_display_t::prepare, video_splitter_output_t::psz_module, vout_display_sys_t::splitter, SplitterControl(), SplitterDelWindow(), SplitterDisplay(), SplitterEvent(), SplitterManage(), SplitterNewWindow(), SplitterPictureDel(), SplitterPictureNew(), SplitterPool(), SplitterPrepare(), vout_display_t::sys, TAB_APPEND, TAB_INIT, vout_display_cfg_t::vertical, video_splitter_Delete(), video_splitter_New(), VLC_OBJECT, vout_DeleteDisplay(), video_splitter_owner_t::wrapper, xmalloc(), and vout_display_cfg_t::zoom.
Referenced by vout_OpenWrapper().
vout_SendDisplayEventMouse()
void vout_SendDisplayEventMouse (vout_thread_t * vout, const vlc_mouse_t * m)
References vlc_mouse_t::b_double_click, vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, vout_thread_sys_t::display, vout_thread_sys_t::filter, filter_chain_MouseFilter(), vlc_mouse_t::i_x, vlc_mouse_t::i_y, vout_thread_sys_t::lock, vout_thread_sys_t::mouse, MOUSE_BUTTON_MAX, vout_thread_t::p, vout_display_t::source, vout_thread_sys_t::spu, spu_ProcessMouse(), vout_thread_sys_t::vd, vlc_mouse_HasButton(), vlc_mouse_HasMoved(), vlc_mouse_HasPressed(), vlc_mouse_HasReleased(), vlc_mutex_lock(), vlc_mutex_unlock(), vout_SendEventMouseDoubleClick(), vout_SendEventMouseMoved(), vout_SendEventMousePressed(), and vout_SendEventMouseReleased().
Referenced by VoutDisplayEventMouse().
vout_SetDisplayAspect()
void vout_SetDisplayAspect (vout_display_t * vd, unsigned dar_num, unsigned dar_den)
References vout_display_owner_sys_t::ch_sar, vlc_rational_t::den, video_format_t::i_visible_height, video_format_t::i_visible_width, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_owner_t::sys, and vlc_ureduce().
Referenced by ThreadChangeAspectRatio().
vout_SetDisplayCrop()
void vout_SetDisplayCrop (vout_display_t * vd, unsigned crop_num, unsigned crop_den, unsigned left, unsigned top, int right, int bottom)
References vout_display_owner_sys_t::bottom, vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::crop, vout_display_owner_sys_t::den, vout_display_owner_sys_t::left, vout_display_owner_sys_t::num, vout_display_t::owner, vout_display_owner_sys_t::right, vout_display_owner_t::sys, and vout_display_owner_sys_t::top.
Referenced by ThreadExecuteCropBorder(), ThreadExecuteCropRatio(), and ThreadExecuteCropWindow().
vout_SetDisplayFilled()
void vout_SetDisplayFilled (vout_display_t * vd, bool is_filled)
References vout_display_owner_sys_t::is_display_filled, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by ThreadChangeDisplayFilled().
vout_SetDisplayViewpoint()
void vout_SetDisplayViewpoint (vout_display_t * vd, const vlc_viewpoint_t * p_viewpoint)
References vout_display_owner_sys_t::ch_viewpoint, vlc_viewpoint_t::fov, vout_display_t::owner, vlc_viewpoint_t::pitch, vlc_viewpoint_t::roll, vout_display_owner_t::sys, vout_display_owner_sys_t::viewpoint, and vlc_viewpoint_t::yaw.
Referenced by ThreadExecuteViewpoint().
vout_SetDisplayZoom()
void vout_SetDisplayZoom (vout_display_t * vd, unsigned num, unsigned den)
References vout_display_owner_sys_t::ch_zoom, vlc_rational_t::den, vout_display_owner_sys_t::is_display_filled, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_t::sys, vlc_ureduce(), and vout_display_owner_sys_t::zoom.
Referenced by ThreadChangeZoom().
vout_UpdateDisplaySourceProperties()
void vout_UpdateDisplaySourceProperties (vout_display_t * vd, const video_format_t * source)
References vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::ch_sar, vlc_rational_t::den, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_owner_t::sys, video_format_CopyCrop(), and vlc_ureduce().
Referenced by ThreadDisplayRenderPicture().
VoutDisplayCreateRender()
static int VoutDisplayCreateRender (vout_display_t * vd) static
References es_format_Clean(), es_format_InitFromVideo(), filter_chain_AppendConverter(), filter_chain_Delete(), filter_chain_NewVideo, filter_chain_Reset(), vout_display_owner_sys_t::filters, vout_display_t::fmt, video_format_t::i_chroma, video_format_t::i_sar_den, video_format_t::i_sar_num, msg_Dbg, msg_Err, vout_display_t::owner, vout_display_t::source, filter_owner_t::sys, vout_display_owner_t::sys, unlikely, VideoBufferNew(), VLC_CODEC_I420, VLC_CODEC_I422, VLC_CODEC_I440, VLC_CODEC_I444, VLC_CODEC_J420, VLC_CODEC_J422, VLC_CODEC_J440, and VLC_CODEC_J444.
Referenced by DisplayNew(), and VoutDisplayResetRender().
VoutDisplayCropRatio()
static void VoutDisplayCropRatio (int * left, int * top, int * right, int * bottom, const video_format_t * source, unsigned num, unsigned den) static
References video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, and video_format_t::i_visible_width.
Referenced by vout_ManageDisplay().
VoutDisplayDelWindow()
static void VoutDisplayDelWindow (vout_display_t * vd, vout_window_t * window) static
References vout_display_t::owner, vout_display_owner_t::sys, vout_display_owner_sys_t::vout, vout_DeleteDisplayWindow(), and vout_display_window_Detach().
Referenced by DisplayNew().
VoutDisplayDestroyRender()
static void VoutDisplayDestroyRender (vout_display_t * vd) static
References filter_chain_Delete(), vout_display_owner_sys_t::filters, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by vout_DeleteDisplay(), and VoutDisplayResetRender().
VoutDisplayEvent()
static void VoutDisplayEvent (vout_display_t * vd, int event, va_list args) static
References vout_display_owner_sys_t::ch_display_size, vout_display_owner_sys_t::display_height, vout_display_owner_sys_t::display_width, vout_display_info_t::has_pictures_invalid, vout_display_t::info, vout_display_owner_sys_t::lock, msg_Dbg, msg_Err, msg_Warn, vout_display_t::owner, vout_display_owner_sys_t::reset_pictures, vout_display_owner_t::sys, vlc_mutex_lock(), vlc_mutex_unlock(), vout_display_owner_sys_t::vout, VOUT_DISPLAY_EVENT_CLOSE, VOUT_DISPLAY_EVENT_DISPLAY_SIZE, VOUT_DISPLAY_EVENT_KEY, VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK, VOUT_DISPLAY_EVENT_MOUSE_MOVED, VOUT_DISPLAY_EVENT_MOUSE_PRESSED, VOUT_DISPLAY_EVENT_MOUSE_RELEASED, VOUT_DISPLAY_EVENT_MOUSE_STATE, VOUT_DISPLAY_EVENT_PICTURES_INVALID, VOUT_DISPLAY_EVENT_VIEWPOINT_MOVED, vout_SendEventClose(), vout_SendEventKey(), vout_SendEventViewpointMoved(), and VoutDisplayEventMouse().
Referenced by DisplayNew(), and SplitterEvent().
VoutDisplayEventMouse()
static void VoutDisplayEventMouse (vout_display_t * vd, int event, va_list args) static
References vlc_mouse_t::b_double_click, vout_display_owner_sys_t::ch_activity, vout_display_owner_sys_t::double_click_timeout, vout_display_info_t::has_double_click, vlc_mouse_t::i_pressed, vlc_mouse_t::i_x, vlc_mouse_t::i_y, vout_display_t::info, vout_display_owner_sys_t::last_moved, vout_display_owner_sys_t::last_pressed, vout_display_owner_sys_t::lock, mdate(), vout_display_owner_sys_t::mouse, MOUSE_BUTTON_LEFT, msg_Dbg, vout_display_t::owner, vout_display_owner_sys_t::state, vout_display_owner_t::sys, vlc_assert_unreachable, vlc_mouse_HasPressed(), vlc_mouse_Init(), vlc_mutex_lock(), vlc_mutex_unlock(), vout_display_owner_sys_t::vout, VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK, VOUT_DISPLAY_EVENT_MOUSE_MOVED, VOUT_DISPLAY_EVENT_MOUSE_PRESSED, VOUT_DISPLAY_EVENT_MOUSE_RELEASED, VOUT_DISPLAY_EVENT_MOUSE_STATE, and vout_SendDisplayEventMouse().
Referenced by VoutDisplayEvent().
VoutDisplayFitWindow()
static void VoutDisplayFitWindow (vout_display_t * vd, bool default_size) static
References vout_display_owner_sys_t::cfg, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_display_cfg_t::height, vout_display_cfg_t::is_display_filled, vout_display_cfg_t::num, vout_display_t::owner, vout_display_t::source, vout_display_owner_t::sys, vout_display_owner_sys_t::vout, vout_display_GetDefaultDisplaySize(), vout_SetDisplayWindowSize(), vout_display_cfg_t::width, and vout_display_cfg_t::zoom.
Referenced by vout_ManageDisplay().
VoutDisplayNewWindow()
static vout_window_t * VoutDisplayNewWindow (vout_display_t * vd, unsigned type) static
References vout_display_t::owner, vout_display_owner_t::sys, vout_display_owner_sys_t::vout, vout_display_window_Attach(), and vout_NewDisplayWindow().
Referenced by DisplayNew().
VoutDisplayResetRender()
static int VoutDisplayResetRender (vout_display_t * vd) static
References VoutDisplayCreateRender(), and VoutDisplayDestroyRender().
Referenced by vout_ManageDisplay().