VLC: src/playlist/engine.c File Reference
engine.c File Reference
Functions
static void VariablesInit (playlist_t *p_playlist)
static int RandomCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *a)
static int CorksCallback (vlc_object_t *obj, char const *var, vlc_value_t old, vlc_value_t cur, void *dummy)
When there are one or more pending corks, playback should be paused.
static int RateCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p)
static int RateOffsetCallback (vlc_object_t *obj, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
static int VideoSplitterCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
playlist_t * playlist_Create (vlc_object_t *p_parent)
Create playlist.
void playlist_Destroy (playlist_t *p_playlist)
Destroy playlist.
input_thread_t * playlist_CurrentInputLocked (playlist_t *p_playlist)
Get current playing input.
input_thread_t * playlist_CurrentInput (playlist_t *p_playlist)
Get current playing input.
playlist_item_t * get_current_status_item (playlist_t *p_playlist)
Accessor for status item and status nodes.
playlist_item_t * get_current_status_node (playlist_t *p_playlist)
void set_current_status_item (playlist_t *p_playlist, playlist_item_t *p_item)
void set_current_status_node (playlist_t *p_playlist, playlist_item_t *p_node)
playlist_item_t * playlist_CurrentPlayingItem (playlist_t *p_playlist)
int playlist_Status (playlist_t *p_playlist)
Function Documentation
CorksCallback()
static int CorksCallback (vlc_object_t * obj, char const * var, vlc_value_t old, vlc_value_t cur, void * dummy) static
When there are one or more pending corks, playback should be paused.
This is used for audio policy.
Warning
Always add and remove a cork with var_IncInteger() and var_DecInteger(). var_Get() and var_Set() are prone to race conditions.
< No error
< No error
< No error
References vlc_value_t::i_int, msg_Dbg, playlist_Pause, playlist_Resume, var_InheritBool, and VLC_SUCCESS.
Referenced by VariablesInit().
RandomCallback()
static int RandomCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * a) static
< No error
References vlc_value_t::b_bool, playlist_private_t::p_item, PL_LOCK, pl_priv, PL_UNLOCK, ResetCurrentlyPlaying(), ResyncCurrentIndex(), playlist_private_t::status, vlc_cond_signal(), and VLC_SUCCESS.
Referenced by VariablesInit().
RateCallback()
static int RateCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p) static
< No error
References vlc_value_t::f_float, p, PL_LOCK, pl_priv, PL_UNLOCK, var_SetFloat, and VLC_SUCCESS.
Referenced by VariablesInit().
RateOffsetCallback()
static int RateOffsetCallback (vlc_object_t * obj, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
References ARRAY_SIZE, msg_Dbg, PL_LOCK, pl_priv, PL_UNLOCK, var_GetFloat, var_SetFloat, VLC_OBJECT, and VLC_UNUSED.
Referenced by VariablesInit().
VariablesInit()
static void VariablesInit (playlist_t * p_playlist) static
References CorksCallback(), RandomCallback(), RateCallback(), RateOffsetCallback(), var_AddCallback, var_Create, var_SetFloat, VideoSplitterCallback(), VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_STRING, and VLC_VAR_VOID.
Referenced by playlist_Create().
VideoSplitterCallback()
static int VideoSplitterCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References input_Control(), INPUT_RESTART_ES, PL_LOCK, pl_priv, PL_UNLOCK, var_GetFloat, var_SetFloat, VIDEO_ES, VLC_SUCCESS, and VLC_UNUSED.
Referenced by VariablesInit().