VLC: src/input/es_out.c File Reference
es_out.c File Reference
Data Structures
struct es_out_pgrm_t
struct es_out_id_t
struct es_out_es_props_t
struct es_out_sys_t
Macros
#define IGNORE_ES DATA_ES
Functions
static es_out_id_t * EsOutAdd (es_out_t *, const es_format_t *)
static int EsOutSend (es_out_t *out, es_out_id_t *es, block_t *p_block)
Send a block for the given es_out.
static void EsOutDel (es_out_t *, es_out_id_t *)
static int EsOutControl (es_out_t *, int i_query, va_list)
static void EsOutDelete (es_out_t *)
static void EsOutTerminate (es_out_t *)
static void EsOutSelect (es_out_t *out, es_out_id_t *es, bool b_force)
Select an ES given the current mode XXX: you need to take a the lock before (stream.stream_lock)
static void EsOutUpdateInfo (es_out_t *, es_out_id_t *es, const es_format_t *, const vlc_meta_t *)
static int EsOutSetRecord (es_out_t *, bool b_record)
static bool EsIsSelected (es_out_id_t *es)
static void EsSelect (es_out_t *out, es_out_id_t *es)
static void EsDeleteInfo (es_out_t *, es_out_id_t *es)
static void EsUnselect (es_out_t *out, es_out_id_t *es, bool b_update)
static void EsOutDecoderChangeDelay (es_out_t *out, es_out_id_t *p_es)
static void EsOutDecodersChangePause (es_out_t *out, bool b_paused, mtime_t i_date)
static void EsOutProgramChangePause (es_out_t *out, bool b_paused, mtime_t i_date)
static void EsOutProgramsChangeRate (es_out_t *out)
static void EsOutDecodersStopBuffering (es_out_t *out, bool b_forced)
static void EsOutGlobalMeta (es_out_t *p_out, const vlc_meta_t *p_meta)
static void EsOutMeta (es_out_t *p_out, const vlc_meta_t *p_meta, const vlc_meta_t *p_progmeta)
static char * LanguageGetName (const char *psz_code)
static char * LanguageGetCode (const char *psz_lang)
static char ** LanguageSplit (const char *psz_langs)
static int LanguageArrayIndex (char **ppsz_langs, const char *psz_lang)
static char * EsOutProgramGetMetaName (es_out_pgrm_t *p_pgrm)
static char * EsInfoCategoryName (es_out_id_t *es)
static int EsOutGetClosedCaptionsChannel (const es_format_t *p_fmt)
static bool EsFmtIsTeletext (const es_format_t *p_fmt)
static es_out_es_props_t * GetPropsByCat (es_out_sys_t *p_sys, int i_cat)
static void EsOutPropsCleanup (es_out_es_props_t *p_props)
static void EsOutPropsInit (es_out_es_props_t *p_props, bool autoselect, input_thread_t *p_input, enum es_out_policy_e e_default_policy, const char *psz_trackidvar, const char *psz_trackvar, const char *psz_langvar, const char *psz_debug)
es_out_t * input_EsOutNew (input_thread_t *p_input, int i_rate)
static mtime_t EsOutGetWakeup (es_out_t *out)
static es_out_id_t * EsOutGetFromID (es_out_t *out, int i_id)
static bool EsOutDecodersIsEmpty (es_out_t *out)
static void EsOutSetDelay (es_out_t *out, int i_cat, int64_t i_delay)
static void EsOutChangePause (es_out_t *out, bool b_paused, mtime_t i_date)
static void EsOutChangeRate (es_out_t *out, int i_rate)
static void EsOutChangePosition (es_out_t *out)
static bool EsOutIsExtraBufferingAllowed (es_out_t *out)
static void EsOutFrameNext (es_out_t *out)
static mtime_t EsOutGetBuffering (es_out_t *out)
static void EsOutESVarUpdateGeneric (es_out_t *out, int i_id, const es_format_t *fmt, const char *psz_language, bool b_delete)
static void EsOutESVarUpdate (es_out_t *out, es_out_id_t *es, bool b_delete)
static bool EsOutIsProgramVisible (es_out_t *out, int i_group)
static void EsOutProgramSelect (es_out_t *out, es_out_pgrm_t *p_pgrm)
static es_out_pgrm_t * EsOutProgramAdd (es_out_t *out, int i_group)
static int EsOutProgramDel (es_out_t *out, int i_group)
static es_out_pgrm_t * EsOutProgramFind (es_out_t *p_out, int i_group)
static char * EsOutProgramGetProgramName (es_out_pgrm_t *p_pgrm)
static void EsOutProgramMeta (es_out_t *out, int i_group, const vlc_meta_t *p_meta)
static void EsOutProgramEpgEvent (es_out_t *out, int i_group, const vlc_epg_event_t *p_event)
static void EsOutProgramEpg (es_out_t *out, int i_group, const vlc_epg_t *p_epg)
static void EsOutEpgTime (es_out_t *out, int64_t time)
static void EsOutProgramUpdateScrambled (es_out_t *p_out, es_out_pgrm_t *p_pgrm)
static es_out_id_t * EsOutAddSlave (es_out_t *out, const es_format_t *fmt, es_out_id_t *p_master)
static void EsCreateDecoder (es_out_t *out, es_out_id_t *p_es)
static void EsDestroyDecoder (es_out_t *out, es_out_id_t *p_es)
static void EsDeleteCCChannels (es_out_t *out, es_out_id_t *parent)
static void EsOutCreateCCChannels (es_out_t *out, vlc_fourcc_t codec, uint64_t i_bitmap, const char *psz_descfmt, es_out_id_t *parent)
static int EsOutControlLocked (es_out_t *out, int i_query, va_list args)
Control query handler.
Variables
static es_out_id_t es_cat [DATA_ES]
Macro Definition Documentation
IGNORE_ES
#define IGNORE_ES DATA_ES
Referenced by EsOutControlLocked().
Function Documentation
EsCreateDecoder()
static void EsCreateDecoder (es_out_t * out, es_out_id_t * p_es) static
References es_out_sys_t::b_buffering, EsOutDecoderChangeDelay(), es_out_id_t::fmt, input_DecoderNew(), input_DecoderStartWait(), input_priv(), es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_id_t::p_master, es_out_id_t::p_pgrm, es_out_sys_t::p_sout_record, and es_out_t::p_sys.
Referenced by EsOutControlLocked(), and EsSelect().
EsDeleteCCChannels()
static void EsDeleteCCChannels (es_out_t * out, es_out_id_t * parent) static
References es_out_id_t::cc, EsOutDel(), es_out_id_t::i_bitmap, es_out_id_t::i_id, input_SendEventEsSelect(), es_out_sys_t::p_input, es_out_t::p_sys, es_out_id_t::pp_es, SPU_ES, es_out_id_t::type, and var_GetInteger.
Referenced by EsUnselect().
EsDeleteInfo()
static void EsDeleteInfo (es_out_t * out, es_out_id_t * es) static
References EsInfoCategoryName(), input_Control(), INPUT_DEL_INFO, likely, es_out_sys_t::p_input, and es_out_t::p_sys.
Referenced by EsOutDel().
EsDestroyDecoder()
static void EsDestroyDecoder (es_out_t * out, es_out_id_t * p_es) static
References input_DecoderDelete(), es_out_id_t::p_dec, es_out_id_t::p_dec_record, and VLC_UNUSED.
Referenced by EsOutControlLocked(), and EsUnselect().
EsFmtIsTeletext()
static bool EsFmtIsTeletext (const es_format_t * p_fmt) inline static
References es_format_t::i_cat, es_format_t::i_codec, SPU_ES, and VLC_CODEC_TELETEXT.
Referenced by EsOutESVarUpdateGeneric(), EsSelect(), and EsUnselect().
EsInfoCategoryName()
static char * EsInfoCategoryName (es_out_id_t * es) static
References _, asprintf(), and es_out_id_t::i_meta_id.
Referenced by EsDeleteInfo(), and EsOutUpdateInfo().
EsIsSelected()
static bool EsIsSelected (es_out_id_t * es) static
References EsOutGetClosedCaptionsChannel(), es_out_id_t::fmt, es_format_t::i_codec, input_DecoderGetCcState(), es_out_id_t::p_dec, and es_out_id_t::p_master.
Referenced by EsOutControlLocked(), EsOutDel(), EsOutProgramSelect(), EsOutSelect(), EsSelect(), and EsUnselect().
EsOutAdd()
static es_out_id_t * EsOutAdd (es_out_t * out, const es_format_t * fmt) static
References EsOutAddSlave().
Referenced by input_EsOutNew().
EsOutAddSlave()
static es_out_id_t * EsOutAddSlave (es_out_t * out, const es_format_t * fmt, es_out_id_t * p_master) static
References es_format_t::audio, es_out_sys_t::audio, AUDIO_ES, es_format_t::audio_replay_gain, AUDIO_REPLAY_GAIN_MAX, es_out_id_t::b_scrambled, es_out_id_t::cc, es_out_sys_t::es, es_format_Copy(), EsOutESVarUpdate(), EsOutProgramFind(), EsOutProgramUpdateScrambled(), EsOutSelect(), EsOutUpdateInfo(), es_out_id_t::fmt, es_out_id_t::i_bitmap, audio_format_t::i_bitspersample, es_format_t::i_cat, es_out_id_t::i_channel, es_format_t::i_codec, es_out_es_props_t::i_count, es_out_pgrm_t::i_es, es_out_sys_t::i_es, video_format_t::i_frame_rate, video_format_t::i_frame_rate_base, es_format_t::i_group, video_format_t::i_height, es_format_t::i_id, es_out_id_t::i_id, es_out_sys_t::i_id, es_out_id_t::i_meta_id, es_format_t::i_original_fourcc, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, input_priv(), LanguageGetCode(), LanguageGetName(), es_out_sys_t::lock, msg_Err, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_id_t::p_master, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, es_out_t::p_sys, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pb_peak, audio_replay_gain_t::pf_gain, audio_replay_gain_t::pf_peak, es_format_t::psz_language, es_out_id_t::psz_language, es_out_id_t::psz_language_code, SPU_ES, es_out_sys_t::sub, TAB_APPEND, es_out_id_t::type, es_format_t::video, es_out_sys_t::video, VIDEO_ES, vlc_audio_replay_gain_MergeFromMeta(), vlc_fourcc_GetCodec(), vlc_fourcc_GetCodecAudio(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_ureduce().
Referenced by EsOutAdd(), and EsOutCreateCCChannels().
EsOutChangePause()
static void EsOutChangePause (es_out_t * out, bool b_paused, mtime_t i_date) static
References es_out_sys_t::b_paused, EsOutDecodersChangePause(), EsOutProgramChangePause(), EsOutProgramsChangeRate(), es_out_sys_t::i_buffering_extra_initial, es_out_sys_t::i_buffering_extra_stream, es_out_sys_t::i_buffering_extra_system, es_out_sys_t::i_pause_date, input_clock_GetState(), es_out_pgrm_t::p_clock, es_out_sys_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutChangePosition()
static void EsOutChangePosition (es_out_t * out) static
References es_out_sys_t::b_buffering, es_out_sys_t::es, es_out_sys_t::i_buffering_extra_initial, es_out_sys_t::i_buffering_extra_stream, es_out_sys_t::i_buffering_extra_system, es_out_sys_t::i_es, es_out_sys_t::i_pgrm, es_out_sys_t::i_preroll_end, es_out_sys_t::i_prev_stream_level, input_clock_Reset(), input_DecoderFlush(), input_DecoderStartWait(), input_SendEventCache(), es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_t::p_sys, and es_out_sys_t::pgrm.
Referenced by EsOutControlLocked().
EsOutChangeRate()
static void EsOutChangeRate (es_out_t * out, int i_rate) static
References EsOutProgramsChangeRate(), es_out_sys_t::i_rate, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutControl()
static int EsOutControl (es_out_t * out, int i_query, va_list args) static
References EsOutControlLocked(), es_out_sys_t::lock, es_out_t::p_sys, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_EsOutNew().
EsOutControlLocked()
static int EsOutControlLocked (es_out_t * out, int i_query, va_list args) static
Control query handler.
Parameters
out the es_out to control
i_query A es_out query as defined in include/ninput.h
args a variable list of arguments for the query
Returns
VLC_SUCCESS or an error code
< No error
< Unspecified error
< No error
< No error
< No error
< Unspecified error
< No error
< No error
< No error
< No error
< Not enough memory
< No error
< No error
< No error
< Unspecified error
< Unspecified error
< No error
< No error
< No error
< No error
< Unspecified error
< Unspecified error
< No error
< No error
< Unspecified error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< Unspecified error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< Unspecified error
< Unspecified error
< No error
< Unspecified error
< Unspecified error
< No error
< No error
< No error
< Unspecified error
References AUDIO_ES, es_out_sys_t::b_active, es_out_sys_t::b_buffering, input_thread_private_t::b_can_pace_control, input_thread_private_t::b_out_pace_control, es_out_id_t::b_scrambled, count, es_out_es_props_t::e_policy, es_out_sys_t::es, es_cat, es_format_Clean(), es_format_Copy(), es_out_Control(), ES_OUT_DEL_GROUP, ES_OUT_GET_BUFFERING, ES_OUT_GET_EMPTY, ES_OUT_GET_ES_OBJECTS_BY_ID, ES_OUT_GET_ES_STATE, ES_OUT_GET_GROUP_FORCED, ES_OUT_GET_PCR_SYSTEM, ES_OUT_GET_WAKE_UP, ES_OUT_MODE_ALL, ES_OUT_MODE_AUTO, ES_OUT_MODE_END, ES_OUT_MODE_NONE, ES_OUT_MODE_PARTIAL, ES_OUT_MODIFY_PCR_SYSTEM, ES_OUT_POST_SUBNODE, ES_OUT_RESET_PCR, ES_OUT_RESTART_ES, ES_OUT_RESTART_ES_BY_ID, ES_OUT_SET_DELAY, ES_OUT_SET_EOS, ES_OUT_SET_EPG_TIME, ES_OUT_SET_ES, ES_OUT_SET_ES_BY_ID, ES_OUT_SET_ES_CAT_POLICY, ES_OUT_SET_ES_DEFAULT, ES_OUT_SET_ES_DEFAULT_BY_ID, ES_OUT_SET_ES_FMT, ES_OUT_SET_ES_SCRAMBLED_STATE, ES_OUT_SET_ES_STATE, ES_OUT_SET_FRAME_NEXT, ES_OUT_SET_GROUP, ES_OUT_SET_GROUP_EPG, ES_OUT_SET_GROUP_EPG_EVENT, ES_OUT_SET_GROUP_META, ES_OUT_SET_GROUP_PCR, ES_OUT_SET_JITTER, ES_OUT_SET_META, ES_OUT_SET_MODE, ES_OUT_SET_NEXT_DISPLAY_TIME, ES_OUT_SET_PAUSE_STATE, ES_OUT_SET_PCR, ES_OUT_SET_RATE, ES_OUT_SET_RECORD_STATE, ES_OUT_SET_TIME, ES_OUT_SET_TIMES, es_out_SetJitter(), ES_OUT_START_ALL_ES, ES_OUT_STOP_ALL_ES, EsCreateDecoder(), EsDestroyDecoder(), EsIsSelected(), EsOutChangePause(), EsOutChangePosition(), EsOutChangeRate(), EsOutDecodersIsEmpty(), EsOutDecodersStopBuffering(), EsOutEpgTime(), EsOutFrameNext(), EsOutGetBuffering(), EsOutGetFromID(), EsOutGetWakeup(), EsOutGlobalMeta(), EsOutIsExtraBufferingAllowed(), EsOutProgramAdd(), EsOutProgramDel(), EsOutProgramEpg(), EsOutProgramEpgEvent(), EsOutProgramFind(), EsOutProgramMeta(), EsOutProgramSelect(), EsOutProgramUpdateScrambled(), EsOutSelect(), EsOutSetDelay(), EsOutSetRecord(), EsOutTerminate(), EsSelect(), EsUnselect(), es_out_id_t::fmt, GetPropsByCat(), es_format_t::i_cat, es_out_sys_t::i_cr_average, es_out_es_props_t::i_demux_id, es_out_sys_t::i_es, es_out_sys_t::i_group_id, es_out_id_t::i_id, es_out_pgrm_t::i_id, es_out_sys_t::i_mode, es_out_sys_t::i_pgrm, es_out_sys_t::i_preroll_end, es_out_sys_t::i_pts_delay, es_out_sys_t::i_pts_jitter, IGNORE_ES, input_clock_ChangeSystemOrigin(), input_clock_GetJitter(), input_clock_GetSystemOrigin(), input_clock_Reset(), input_clock_SetJitter(), input_clock_Update(), input_DecoderDrain(), input_DecoderGetObjects(), input_item_node_PostAndDelete(), input_priv(), INPUT_PTS_DELAY_MAX, input_resource_TerminateVout(), input_SendEventLength(), input_SendEventPosition(), mdate(), msg_Dbg, msg_Err, es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_sys_t::p_input, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, input_thread_private_t::p_resource, input_thread_private_t::p_sout, es_out_t::p_sys, es_out_sys_t::pgrm, SPU_ES, es_out_sys_t::sub, UNKNOWN_ES, var_InheritInteger, VIDEO_ES, vlc_alloc(), vlc_assert_unreachable, VLC_EGENERIC, VLC_ENOMEM, VLC_OBJECT, vlc_object_hold, VLC_SUCCESS, and VLC_TS_INVALID.
Referenced by EsOutControl().
EsOutCreateCCChannels()
static void EsOutCreateCCChannels (es_out_t * out, vlc_fourcc_t codec, uint64_t i_bitmap, const char * psz_descfmt, es_out_id_t * parent) static
References asprintf(), es_out_id_t::cc, subs_format_t::cc, es_format_Clean(), es_format_Init(), EsOutAddSlave(), EsOutSelect(), es_out_id_t::fmt, es_out_id_t::i_bitmap, es_out_es_props_t::i_channel, subs_format_t::i_channel, es_format_t::i_group, es_out_id_t::i_id, msg_Dbg, es_out_sys_t::p_input, es_out_t::p_sys, es_out_id_t::pp_es, es_format_t::psz_description, SPU_ES, es_out_sys_t::sub, es_format_t::subs, and es_out_id_t::type.
Referenced by EsOutSend().
EsOutDecoderChangeDelay()
static void EsOutDecoderChangeDelay (es_out_t * out, es_out_id_t * p_es) static
References AUDIO_ES, es_out_id_t::fmt, es_out_sys_t::i_audio_delay, es_format_t::i_cat, es_out_sys_t::i_spu_delay, input_DecoderChangeDelay(), es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_t::p_sys, and SPU_ES.
Referenced by EsCreateDecoder(), and EsOutSetDelay().
EsOutDecodersChangePause()
static void EsOutDecodersChangePause (es_out_t * out, bool b_paused, mtime_t i_date) static
References es_out_sys_t::es, es_out_sys_t::i_es, input_DecoderChangePause(), es_out_id_t::p_dec, es_out_id_t::p_dec_record, and es_out_t::p_sys.
Referenced by EsOutChangePause().
EsOutDecodersIsEmpty()
static bool EsOutDecodersIsEmpty (es_out_t * out) static
References es_out_sys_t::b_buffering, es_out_sys_t::es, EsOutDecodersStopBuffering(), es_out_sys_t::i_es, input_DecoderIsEmpty(), es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutDecodersStopBuffering()
static void EsOutDecodersStopBuffering (es_out_t * out, bool b_forced) static
References es_out_sys_t::b_buffering, es_out_sys_t::b_paused, es_out_sys_t::es, es_out_id_t::fmt, es_out_sys_t::i_buffering_extra_initial, es_out_sys_t::i_buffering_extra_stream, es_format_t::i_cat, es_out_sys_t::i_es, es_out_sys_t::i_pause_date, es_out_sys_t::i_preroll_end, es_out_sys_t::i_prev_stream_level, es_out_sys_t::i_pts_delay, input_clock_ChangeSystemOrigin(), input_clock_GetState(), input_DecoderStopWait(), input_DecoderWait(), input_priv(), input_resource_TerminateVout(), input_SendEventCache(), mdate(), msg_Dbg, es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_sys_t::p_pgrm, input_thread_private_t::p_resource, es_out_t::p_sys, and SPU_ES.
Referenced by EsOutControlLocked(), and EsOutDecodersIsEmpty().
EsOutDel()
static void EsOutDel (es_out_t * out, es_out_id_t * es) static
References es_out_sys_t::b_buffering, es_out_id_t::b_scrambled, es_out_sys_t::es, es_format_Clean(), EsDeleteInfo(), EsIsSelected(), EsOutESVarUpdate(), EsOutProgramUpdateScrambled(), EsOutSelect(), EsUnselect(), es_out_id_t::fmt, GetPropsByCat(), es_format_t::i_cat, es_out_es_props_t::i_count, es_out_pgrm_t::i_es, es_out_sys_t::i_es, es_out_id_t::i_id, input_DecoderDrain(), input_DecoderIsEmpty(), input_SendEventEsSelect(), input_Stopped(), es_out_sys_t::lock, msg_Dbg, msleep, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_es_props_t::p_main_es, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, es_out_t::p_sys, es_out_id_t::psz_language, es_out_id_t::psz_language_code, TAB_REMOVE, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsDeleteCCChannels(), and input_EsOutNew().
EsOutDelete()
static void EsOutDelete (es_out_t * out) static
References es_out_sys_t::audio, EsOutPropsCleanup(), es_out_sys_t::i_es, es_out_sys_t::i_pgrm, es_out_sys_t::lock, es_out_sys_t::p_pgrm, es_out_t::p_sys, es_out_sys_t::sub, and vlc_mutex_destroy().
Referenced by input_EsOutNew().
EsOutEpgTime()
static void EsOutEpgTime (es_out_t * out, int64_t time) static
References input_item_SetEpgTime(), input_priv(), es_out_sys_t::p_input, input_thread_private_t::p_item, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutESVarUpdate()
static void EsOutESVarUpdate (es_out_t * out, es_out_id_t * es, bool b_delete) static
References EsOutESVarUpdateGeneric(), es_out_id_t::fmt, es_out_id_t::i_id, and es_out_id_t::psz_language.
Referenced by EsOutAddSlave(), EsOutDel(), and EsOutProgramSelect().
EsOutESVarUpdateGeneric()
static void EsOutESVarUpdateGeneric (es_out_t * out, int i_id, const es_format_t * fmt, const char * psz_language, bool b_delete) static
References _, asprintf(), AUDIO_ES, EsFmtIsTeletext(), es_format_t::i_cat, vlc_value_t::i_int, subs_format_t::i_magazine, subs_format_t::i_page, input_SendEventEsAdd(), input_SendEventEsDel(), input_SendEventTeletextAdd(), input_SendEventTeletextDel(), es_out_sys_t::p_input, es_out_t::p_sys, es_format_t::psz_description, vlc_value_t::psz_string, strdup(), es_format_t::subs, subs_format_t::teletext, var_Change, VIDEO_ES, VLC_VAR_ADDCHOICE, and VLC_VAR_CHOICESCOUNT.
Referenced by EsOutESVarUpdate().
EsOutFrameNext()
static void EsOutFrameNext (es_out_t * out) static
References es_out_sys_t::b_buffering, es_out_sys_t::b_paused, es_out_sys_t::es, es_out_id_t::fmt, es_out_sys_t::i_buffering_extra_initial, es_out_sys_t::i_buffering_extra_stream, es_out_sys_t::i_buffering_extra_system, es_format_t::i_cat, es_out_sys_t::i_es, es_out_sys_t::i_preroll_end, es_out_sys_t::i_prev_stream_level, es_out_sys_t::i_pts_delay, input_clock_GetRate(), input_clock_GetState(), input_DecoderFrameNext(), INPUT_RATE_DEFAULT, msg_Dbg, msg_Warn, es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_sys_t::p_input, es_out_sys_t::p_pgrm, es_out_t::p_sys, and VIDEO_ES.
Referenced by EsOutControlLocked().
EsOutGetBuffering()
static mtime_t EsOutGetBuffering (es_out_t * out) static
References es_out_sys_t::b_buffering, es_out_sys_t::b_paused, es_out_sys_t::i_buffering_extra_initial, es_out_sys_t::i_buffering_extra_system, es_out_sys_t::i_pause_date, es_out_sys_t::i_pts_delay, es_out_sys_t::i_rate, input_clock_GetState(), INPUT_RATE_DEFAULT, mdate(), es_out_pgrm_t::p_clock, es_out_sys_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutGetClosedCaptionsChannel()
static int EsOutGetClosedCaptionsChannel (const es_format_t * p_fmt) inline static
References subs_format_t::cc, subs_format_t::i_channel, es_format_t::i_codec, es_format_t::subs, VLC_CODEC_CEA608, and VLC_CODEC_CEA708.
Referenced by EsIsSelected(), EsSelect(), and EsUnselect().
EsOutGetFromID()
static es_out_id_t * EsOutGetFromID (es_out_t * out, int i_id) static
References es_out_sys_t::es, es_cat, es_out_sys_t::i_es, es_out_id_t::i_id, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutGetWakeup()
static mtime_t EsOutGetWakeup (es_out_t * out) static
References es_out_sys_t::b_buffering, input_clock_GetWakeup(), input_priv(), es_out_pgrm_t::p_clock, es_out_sys_t::p_input, es_out_sys_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutGlobalMeta()
static void EsOutGlobalMeta (es_out_t * p_out, const vlc_meta_t * p_meta) static
References EsOutMeta(), es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutControlLocked(), and EsOutProgramMeta().
EsOutIsExtraBufferingAllowed()
static bool EsOutIsExtraBufferingAllowed (es_out_t * out) static
References es_out_sys_t::es, es_out_sys_t::i_es, input_DecoderGetFifoSize(), es_out_id_t::p_dec, es_out_id_t::p_dec_record, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutIsProgramVisible()
static bool EsOutIsProgramVisible (es_out_t * out, int i_group) static
References es_out_sys_t::i_group_id, and es_out_t::p_sys.
Referenced by EsOutProgramAdd(), EsOutProgramEpg(), EsOutProgramEpgEvent(), and EsOutProgramMeta().
EsOutMeta()
static void EsOutMeta (es_out_t * p_out, const vlc_meta_t * p_meta, const vlc_meta_t * p_progmeta) static
References input_ExtractAttachmentAndCacheArt(), input_GetItem(), input_item_GetArtURL, input_item_SetArtURL, input_item_SetName(), input_item_SetPreparsed(), input_priv(), input_SendEventMeta(), input_item_t::lock, es_out_sys_t::p_input, input_item_t::p_meta, es_out_t::p_sys, vlc_meta_ArtworkURL, vlc_meta_Get(), vlc_meta_Merge(), vlc_meta_Title, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutGlobalMeta(), and EsOutProgramMeta().
EsOutProgramAdd()
static es_out_pgrm_t * EsOutProgramAdd (es_out_t * out, int i_group) static
References es_out_sys_t::b_paused, es_out_pgrm_t::b_scrambled, es_out_pgrm_t::b_selected, EsOutIsProgramVisible(), EsOutProgramSelect(), es_out_sys_t::i_cr_average, es_out_pgrm_t::i_es, es_out_sys_t::i_group_id, es_out_pgrm_t::i_id, es_out_sys_t::i_pause_date, es_out_sys_t::i_pgrm, es_out_sys_t::i_pts_delay, es_out_sys_t::i_rate, input_clock_ChangePause(), input_clock_New(), input_clock_SetJitter(), input_SendEventProgramAdd(), es_out_pgrm_t::p_clock, es_out_sys_t::p_input, es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, es_out_t::p_sys, es_out_sys_t::pgrm, and TAB_APPEND.
Referenced by EsOutControlLocked(), and EsOutProgramFind().
EsOutProgramChangePause()
static void EsOutProgramChangePause (es_out_t * out, bool b_paused, mtime_t i_date) static
References es_out_sys_t::i_pgrm, input_clock_ChangePause(), es_out_pgrm_t::p_clock, es_out_t::p_sys, and es_out_sys_t::pgrm.
Referenced by EsOutChangePause().
EsOutProgramDel()
static int EsOutProgramDel (es_out_t * out, int i_group) static
< Unspecified error
< Unspecified error
< No error
References es_out_pgrm_t::i_es, es_out_pgrm_t::i_id, es_out_sys_t::i_pgrm, input_clock_Delete(), input_SendEventProgramDel(), msg_Dbg, es_out_pgrm_t::p_clock, es_out_sys_t::p_input, es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, es_out_t::p_sys, es_out_sys_t::pgrm, TAB_REMOVE, VLC_EGENERIC, vlc_meta_Delete(), and VLC_SUCCESS.
Referenced by EsOutControlLocked().
EsOutProgramEpg()
static void EsOutProgramEpg (es_out_t * out, int i_group, const vlc_epg_t * p_epg) static
References vlc_epg_t::b_present, EsOutIsProgramVisible(), EsOutProgramFind(), EsOutProgramGetMetaName(), EsOutProgramGetProgramName(), input_item_t::i_epg, vlc_epg_t::i_event, es_out_pgrm_t::i_id, vlc_epg_t::i_source_id, INPUT_ADD_INFO, input_Control(), INPUT_DEL_INFO, input_item_SetEpg(), input_item_SetESNowPlaying(), input_priv(), input_SendEventMeta(), input_SendEventMetaEpg(), input_item_t::lock, msg_Dbg, vlc_epg_t::p_current, es_out_sys_t::p_input, input_thread_private_t::p_item, es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, es_out_t::p_sys, input_item_t::pp_epg, psz_name, vlc_epg_event_t::psz_name, vlc_epg_t::psz_name, vlc_meta_ESNowPlaying, vlc_meta_Get(), vlc_meta_New(), vlc_meta_Set(), vlc_meta_SetNowPlaying, vlc_meta_TypeToLocalizedString(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutControlLocked().
EsOutProgramEpgEvent()
static void EsOutProgramEpgEvent (es_out_t * out, int i_group, const vlc_epg_event_t * p_event) static
References EsOutIsProgramVisible(), EsOutProgramFind(), input_item_SetEpgEvent(), input_priv(), es_out_sys_t::p_input, input_thread_private_t::p_item, and es_out_t::p_sys.
Referenced by EsOutControlLocked().
EsOutProgramFind()
static es_out_pgrm_t * EsOutProgramFind (es_out_t * p_out, int i_group) static
References EsOutProgramAdd(), es_out_pgrm_t::i_id, es_out_sys_t::i_pgrm, es_out_t::p_sys, and es_out_sys_t::pgrm.
Referenced by EsOutAddSlave(), EsOutControlLocked(), EsOutProgramEpg(), EsOutProgramEpgEvent(), and EsOutProgramMeta().
EsOutProgramGetMetaName()
static char * EsOutProgramGetMetaName (es_out_pgrm_t * p_pgrm) static
References _, asprintf(), es_out_pgrm_t::i_id, es_out_pgrm_t::p_meta, vlc_meta_Get(), and vlc_meta_Title.
Referenced by EsOutProgramEpg(), EsOutProgramMeta(), and EsOutProgramUpdateScrambled().
EsOutProgramGetProgramName()
static char * EsOutProgramGetProgramName (es_out_pgrm_t * p_pgrm) static
References _, asprintf(), es_out_pgrm_t::i_id, es_out_pgrm_t::p_meta, strdup(), vlc_meta_Get(), and vlc_meta_Title.
Referenced by EsOutProgramEpg().
EsOutProgramMeta()
static void EsOutProgramMeta (es_out_t * out, int i_group, const vlc_meta_t * p_meta) static
References asprintf(), EsOutGlobalMeta(), EsOutIsProgramVisible(), EsOutMeta(), EsOutProgramFind(), EsOutProgramGetMetaName(), info_category_AddInfo(), info_category_New(), input_Control(), INPUT_DEL_INFO, input_item_SetPublisher(), INPUT_MERGE_INFOS, input_priv(), input_SendEventMeta(), input_SendEventProgramAdd(), input_SendEventProgramDel(), input_SendEventProgramSelect(), msg_Dbg, es_out_sys_t::p_input, es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, es_out_t::p_sys, strdup(), vlc_gettext(), vlc_meta_CopyExtraNames(), vlc_meta_Delete(), vlc_meta_ESNowPlaying, vlc_meta_Get(), vlc_meta_GetExtra(), vlc_meta_Merge(), vlc_meta_New(), vlc_meta_Publisher, vlc_meta_Title, and vlc_meta_TypeToLocalizedString().
Referenced by EsOutControlLocked().
EsOutProgramsChangeRate()
static void EsOutProgramsChangeRate (es_out_t * out) static
References es_out_sys_t::i_pgrm, es_out_sys_t::i_rate, input_clock_ChangeRate(), es_out_pgrm_t::p_clock, es_out_t::p_sys, and es_out_sys_t::pgrm.
Referenced by EsOutChangePause(), and EsOutChangeRate().
EsOutProgramSelect()
static void EsOutProgramSelect (es_out_t * out, es_out_pgrm_t * p_pgrm) static
References es_out_sys_t::audio, AUDIO_ES, es_out_pgrm_t::b_scrambled, es_out_pgrm_t::b_selected, es_out_sys_t::es, ES_OUT_MODE_ALL, EsIsSelected(), EsOutESVarUpdate(), EsOutSelect(), EsOutUpdateInfo(), EsUnselect(), es_out_id_t::fmt, es_out_sys_t::i_es, es_out_pgrm_t::i_id, es_out_sys_t::i_mode, input_item_ChangeEPGSource(), input_item_SetESNowPlaying(), input_item_SetPublisher(), input_item_SetTitle(), input_priv(), input_SendEventEsDel(), input_SendEventMeta(), input_SendEventProgramScrambled(), input_SendEventProgramSelect(), input_SendEventTeletextDel(), msg_Dbg, es_out_sys_t::p_input, es_out_es_props_t::p_main_es, es_out_pgrm_t::p_meta, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, es_out_t::p_sys, SPU_ES, es_out_sys_t::sub, var_SetInteger, es_out_sys_t::video, VIDEO_ES, vlc_meta_ESNowPlaying, vlc_meta_Get(), vlc_meta_Publisher, and vlc_meta_Title.
Referenced by EsOutControlLocked(), and EsOutProgramAdd().
EsOutProgramUpdateScrambled()
static void EsOutProgramUpdateScrambled (es_out_t * p_out, es_out_pgrm_t * p_pgrm) static
References _, es_out_id_t::b_scrambled, es_out_pgrm_t::b_scrambled, es_out_sys_t::es, EsOutProgramGetMetaName(), es_out_sys_t::i_es, es_out_pgrm_t::i_id, INPUT_ADD_INFO, input_Control(), INPUT_DEL_INFO, input_SendEventProgramScrambled(), es_out_sys_t::p_input, es_out_id_t::p_pgrm, and es_out_t::p_sys.
Referenced by EsOutAddSlave(), EsOutControlLocked(), and EsOutDel().
EsOutPropsCleanup()
static void EsOutPropsCleanup (es_out_es_props_t * p_props) static
References es_out_es_props_t::ppsz_language.
Referenced by EsOutDelete().
EsOutPropsInit()
static void EsOutPropsInit (es_out_es_props_t * p_props, bool autoselect, input_thread_t * p_input, enum es_out_policy_e e_default_policy, const char * psz_trackidvar, const char * psz_trackvar, const char * psz_langvar, const char * psz_debug) static
References es_out_es_props_t::b_autoselect, input_thread_private_t::b_preparsing, es_out_es_props_t::e_policy, es_out_es_props_t::i_channel, es_out_es_props_t::i_count, es_out_es_props_t::i_demux_id, es_out_es_props_t::i_id, input_priv(), LanguageSplit(), msg_Dbg, es_out_es_props_t::p_main_es, es_out_es_props_t::ppsz_language, var_GetInteger, and var_GetString.
Referenced by input_EsOutNew().
EsOutSelect()
static void EsOutSelect (es_out_t * out, es_out_id_t * es, bool b_force) static
Select an ES given the current mode XXX: you need to take a the lock before (stream.stream_lock)
Parameters
out The es_out structure
es es_out_id structure
b_force ...
Returns
nothing
References es_out_sys_t::b_active, es_out_es_props_t::b_autoselect, es_out_es_props_t::e_policy, ES_OUT_ES_POLICY_EXCLUSIVE, ES_OUT_MODE_ALL, ES_OUT_MODE_AUTO, ES_OUT_MODE_PARTIAL, ES_PRIORITY_SELECTABLE_MIN, EsIsSelected(), EsSelect(), EsUnselect(), es_out_id_t::fmt, GetPropsByCat(), es_format_t::i_cat, es_out_es_props_t::i_channel, es_out_id_t::i_channel, es_out_es_props_t::i_demux_id, es_out_es_props_t::i_id, es_out_id_t::i_id, es_out_pgrm_t::i_id, es_out_sys_t::i_mode, es_format_t::i_priority, LanguageArrayIndex(), es_out_sys_t::p_input, es_out_es_props_t::p_main_es, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, es_out_t::p_sys, es_out_es_props_t::ppsz_language, es_out_id_t::psz_language_code, strtok_r(), and var_GetNonEmptyString.
Referenced by EsOutAddSlave(), EsOutControlLocked(), EsOutCreateCCChannels(), EsOutDel(), and EsOutProgramSelect().
EsOutSend()
static int EsOutSend (es_out_t * out, es_out_id_t * es, block_t * p_block) static
Send a block for the given es_out.
Parameters
out the es_out to send from
es the es_out_id
p_block the data block to send
< No error
< No error
References _, input_thread_private_t::b_out_pace_control, block_Duplicate(), BLOCK_FLAG_CORRUPTED, BLOCK_FLAG_DISCONTINUITY, BLOCK_FLAG_PREROLL, block_Release(), input_thread_private_t::counters_lock, es_format_Clean(), EsOutCreateCCChannels(), EsOutUpdateInfo(), decoder_cc_desc_t::i_608_channels, decoder_cc_desc_t::i_708_channels, block_t::i_buffer, block_t::i_dts, block_t::i_flags, block_t::i_length, es_out_sys_t::i_preroll_end, block_t::i_pts, input_DecoderDecode(), input_DecoderGetCcDesc(), input_DecoderHasFormatChanged(), input_priv(), libvlc_stats, es_out_sys_t::lock, msg_Dbg, es_out_id_t::p_dec, es_out_id_t::p_dec_record, input_thread_private_t::p_demux_bitrate, input_thread_private_t::p_demux_corrupted, input_thread_private_t::p_demux_discontinuity, input_thread_private_t::p_demux_read, es_out_sys_t::p_input, block_t::p_next, es_out_t::p_sys, stats_Update(), var_InheritInteger, VLC_CODEC_CEA608, VLC_CODEC_CEA708, vlc_meta_Delete(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and VLC_TS_INVALID.
Referenced by input_EsOutNew().
EsOutSetDelay()
static void EsOutSetDelay (es_out_t * out, int i_cat, int64_t i_delay) static
References AUDIO_ES, es_out_sys_t::es, EsOutDecoderChangeDelay(), es_out_sys_t::i_audio_delay, es_out_sys_t::i_es, es_out_sys_t::i_spu_delay, es_out_t::p_sys, and SPU_ES.
Referenced by EsOutControlLocked().
EsOutSetRecord()
static int EsOutSetRecord (es_out_t * out, bool b_record) static
< Unspecified error
< Unspecified error
< No error
References asprintf(), es_out_sys_t::b_buffering, config_GetUserDir(), config_StringEscape(), es_out_sys_t::es, es_out_id_t::fmt, es_out_sys_t::i_es, input_CreateFilename(), input_DecoderDelete(), input_DecoderNew(), input_DecoderStartWait(), INPUT_RECORD_PREFIX, es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_id_t::p_dec_record, es_out_sys_t::p_input, es_out_id_t::p_master, es_out_id_t::p_pgrm, es_out_sys_t::p_sout_record, es_out_t::p_sys, sout_DeleteInstance(), sout_NewInstance, var_CountChoices, var_CreateGetNonEmptyString, VLC_DOWNLOAD_DIR, VLC_EGENERIC, VLC_MUSIC_DIR, VLC_SUCCESS, and VLC_VIDEOS_DIR.
Referenced by EsOutControlLocked(), and EsOutTerminate().
EsOutTerminate()
static void EsOutTerminate (es_out_t * out) static
References es_out_sys_t::es, es_format_Clean(), EsOutSetRecord(), es_out_id_t::fmt, es_out_sys_t::i_es, es_out_sys_t::i_pgrm, input_clock_Delete(), input_DecoderDelete(), input_item_SetEpgOffline(), input_priv(), input_SendEventMetaEpg(), es_out_pgrm_t::p_clock, es_out_id_t::p_dec, es_out_sys_t::p_input, input_thread_private_t::p_item, es_out_pgrm_t::p_meta, es_out_sys_t::p_pgrm, es_out_sys_t::p_sout_record, es_out_t::p_sys, es_out_sys_t::pgrm, es_out_id_t::psz_language, es_out_id_t::psz_language_code, TAB_CLEAN, and vlc_meta_Delete().
Referenced by EsOutControlLocked().
EsOutUpdateInfo()
static void EsOutUpdateInfo (es_out_t * out, es_out_id_t * es, const es_format_t * fmt, const vlc_meta_t * p_meta) static
References _, aout_BitsPerSample(), aout_FormatPrintChannels(), ARRAY_SIZE, es_format_t::audio, AUDIO_ES, es_format_t::audio_replay_gain, AUDIO_REPLAY_GAIN_MAX, AUDIO_REPLAY_GAIN_TRACK, video_format_t::b_color_range_full, video_format_t::chroma_location, CHROMA_LOCATION_BOTTOM_CENTER, CHROMA_LOCATION_BOTTOM_LEFT, CHROMA_LOCATION_CENTER, CHROMA_LOCATION_LEFT, CHROMA_LOCATION_MAX, CHROMA_LOCATION_TOP_CENTER, CHROMA_LOCATION_TOP_LEFT, CHROMA_LOCATION_UNDEF, COLOR_PRIMARIES_BT2020, COLOR_PRIMARIES_BT470_M, COLOR_PRIMARIES_BT601_525, COLOR_PRIMARIES_BT601_625, COLOR_PRIMARIES_BT709, COLOR_PRIMARIES_DCI_P3, COLOR_PRIMARIES_MAX, COLOR_PRIMARIES_UNDEF, COLOR_SPACE_BT2020, COLOR_SPACE_BT601, COLOR_SPACE_BT709, COLOR_SPACE_MAX, COLOR_SPACE_UNDEF, EsInfoCategoryName(), es_out_id_t::fmt, vlc_viewpoint_t::fov, es_format_t::i_bitrate, audio_format_t::i_bitspersample, es_format_t::i_cat, es_format_t::i_codec, es_format_t::i_extra, es_format_t::i_extra_languages, video_format_t::i_frame_rate, video_format_t::i_frame_rate_base, video_format_t::i_height, es_format_t::i_id, es_out_id_t::i_id, es_out_id_t::i_meta_id, es_format_t::i_original_fourcc, audio_format_t::i_physical_channels, audio_format_t::i_rate, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, info_category_AddInfo(), info_category_New(), input_Control(), input_GetItem(), input_item_UpdateTracksInfo(), INPUT_REPLACE_INFOS, video_format_t::lighting, lldiv(), video_format_t::mastering, video_format_t::max_luminance, video_format_t::MaxCLL, video_format_t::MaxFALL, video_format_t::min_luminance, N_, video_format_t::orientation, es_format_t::p_extra, es_format_t::p_extra_languages, es_out_sys_t::p_input, subs_format_t::p_style, es_out_t::p_sys, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pf_gain, vlc_viewpoint_t::pitch, video_format_t::pose, video_format_t::primaries, video_format_t::projection_mode, PROJECTION_MODE_CUBEMAP_LAYOUT_STANDARD, PROJECTION_MODE_EQUIRECTANGULAR, PROJECTION_MODE_RECTANGULAR, es_format_t::psz_description, subs_format_t::psz_encoding, es_format_t::psz_language, es_out_id_t::psz_language, psz_name, psz_value, lldiv_t::quot, lldiv_t::rem, vlc_viewpoint_t::roll, video_format_t::space, SPU_ES, es_format_t::subs, video_format_t::transfer, TRANSFER_FUNC_BT470_BG, TRANSFER_FUNC_BT470_M, TRANSFER_FUNC_BT709, TRANSFER_FUNC_HLG, TRANSFER_FUNC_LINEAR, TRANSFER_FUNC_MAX, TRANSFER_FUNC_SMPTE_240, TRANSFER_FUNC_SMPTE_ST2084, TRANSFER_FUNC_SRGB, TRANSFER_FUNC_UNDEF, unlikely, var_SetInteger, es_format_t::video, VIDEO_ES, vlc_assert_unreachable, VLC_FOURCC, vlc_fourcc_GetDescription(), vlc_gettext(), vlc_meta_CopyExtraNames(), vlc_meta_GetExtra(), vlc_pgettext, video_format_t::white_point, and vlc_viewpoint_t::yaw.
Referenced by EsOutAddSlave(), EsOutProgramSelect(), and EsOutSend().
EsSelect()
static void EsSelect (es_out_t * out, es_out_id_t * es) static
References AUDIO_ES, EsCreateDecoder(), EsFmtIsTeletext(), EsIsSelected(), EsOutGetClosedCaptionsChannel(), es_out_id_t::fmt, es_format_t::i_cat, es_format_t::i_codec, es_out_id_t::i_id, input_DecoderSetCcState(), input_priv(), input_SendEventEsSelect(), input_SendEventTeletextSelect(), msg_Dbg, msg_Warn, es_out_id_t::p_dec, es_out_sys_t::p_input, es_out_id_t::p_master, es_out_id_t::p_pgrm, es_out_sys_t::p_pgrm, input_thread_private_t::p_sout, es_out_t::p_sys, SPU_ES, var_GetBool, and VIDEO_ES.
Referenced by EsOutControlLocked(), and EsOutSelect().
EsUnselect()
static void EsUnselect (es_out_t * out, es_out_id_t * es, bool b_update) static
References EsDeleteCCChannels(), EsDestroyDecoder(), EsFmtIsTeletext(), EsIsSelected(), EsOutGetClosedCaptionsChannel(), es_out_id_t::fmt, es_format_t::i_cat, es_format_t::i_codec, es_out_id_t::i_id, input_DecoderSetCcState(), input_SendEventEsSelect(), input_SendEventTeletextSelect(), msg_Warn, es_out_id_t::p_dec, es_out_sys_t::p_input, es_out_id_t::p_master, and es_out_t::p_sys.
Referenced by EsOutControlLocked(), EsOutDel(), EsOutProgramSelect(), and EsOutSelect().
GetPropsByCat()
static es_out_es_props_t * GetPropsByCat (es_out_sys_t * p_sys, int i_cat) static
References es_out_sys_t::audio, AUDIO_ES, SPU_ES, es_out_sys_t::sub, es_out_sys_t::video, and VIDEO_ES.
Referenced by EsOutControlLocked(), EsOutDel(), and EsOutSelect().
input_EsOutNew()
es_out_t * input_EsOutNew (input_thread_t * p_input, int i_rate)
References es_out_sys_t::audio, es_out_sys_t::b_active, es_out_sys_t::b_buffering, es_out_sys_t::es, ES_OUT_ES_POLICY_EXCLUSIVE, ES_OUT_ES_POLICY_SIMULTANEOUS, ES_OUT_MODE_NONE, EsOutAdd(), EsOutControl(), EsOutDel(), EsOutDelete(), EsOutPropsInit(), EsOutSend(), es_out_sys_t::i_es, es_out_sys_t::i_group_id, es_out_sys_t::i_mode, es_out_sys_t::i_pause_date, es_out_sys_t::i_pgrm, es_out_sys_t::i_preroll_end, es_out_sys_t::i_prev_stream_level, es_out_sys_t::i_rate, es_out_sys_t::lock, es_out_sys_t::p_input, es_out_t::p_sys, es_out_t::pf_add, es_out_t::pf_control, es_out_t::pf_del, es_out_t::pf_destroy, es_out_t::pf_send, es_out_sys_t::pgrm, es_out_sys_t::sub, TAB_INIT, var_GetInteger, es_out_sys_t::video, and vlc_mutex_init_recursive().
Referenced by Create().
LanguageArrayIndex()
static int LanguageArrayIndex (char ** ppsz_langs, const char * psz_lang) static
References strcasecmp().
Referenced by EsOutSelect().
LanguageGetCode()
static char * LanguageGetCode (const char * psz_lang) static
References p_languages, iso639_lang_t::psz_eng_name, iso639_lang_t::psz_iso639_1, iso639_lang_t::psz_iso639_2B, iso639_lang_t::psz_iso639_2T, strcasecmp(), and strdup().
Referenced by EsOutAddSlave(), LanguageGetName(), and LanguageSplit().
LanguageGetName()
static char * LanguageGetName (const char * psz_code) static
References GetLang_1(), GetLang_2B(), GetLang_2T(), LanguageGetCode(), iso639_lang_t::psz_eng_name, iso639_lang_t::psz_iso639_1, strdup(), and vlc_gettext().
Referenced by EsOutAddSlave().
LanguageSplit()
static char ** LanguageSplit (const char * psz_langs) static
References LanguageGetCode(), strdup(), and TAB_APPEND.
Referenced by EsOutPropsInit().
Variable Documentation
es_cat
es_out_id_t es_cat[DATA_ES] static
Referenced by EsOutControlLocked(), and EsOutGetFromID().