VLC: src/input/es_out_timeshift.h File Reference
es_out_timeshift.h File Reference
Functions
es_out_t * input_EsOutTimeshiftNew (input_thread_t *, es_out_t *, int i_rate)
Function Documentation
input_EsOutTimeshiftNew()
es_out_t * input_EsOutTimeshiftNew (input_thread_t * p_input, es_out_t * p_next_out, int i_rate)
References Add(), es_out_sys_t::b_delayed, es_out_sys_t::b_input_paused, es_out_sys_t::b_input_paused_source, Control(), count, Del(), Destroy(), DIR_SEP_CHAR, es_out_sys_t::i_es, es_out_sys_t::i_input_rate, es_out_sys_t::i_input_rate_source, es_out_sys_t::i_tmp_size_max, es_out_sys_t::lock, msg_Dbg, es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_t::pf_add, es_out_t::pf_control, es_out_t::pf_del, es_out_t::pf_destroy, es_out_t::pf_send, es_out_sys_t::pp_es, es_out_sys_t::psz_tmp_path, Send(), strdup(), TAB_INIT, var_CreateGetInteger, var_InheritString, vlc_alloc(), and vlc_mutex_init_recursive().
Referenced by Init().