VLC: src/input/es_out.h File Reference
es_out.h File Reference
Enumerations
enum es_out_mode_e {
ES_OUT_MODE_NONE , ES_OUT_MODE_ALL , ES_OUT_MODE_AUTO , ES_OUT_MODE_PARTIAL ,
ES_OUT_MODE_END
}
enum es_out_query_private_e {
ES_OUT_SET_MODE = ES_OUT_PRIVATE_START , ES_OUT_GET_WAKE_UP , ES_OUT_SET_ES_BY_ID , ES_OUT_RESTART_ES_BY_ID ,
ES_OUT_SET_ES_DEFAULT_BY_ID , ES_OUT_GET_ES_OBJECTS_BY_ID , ES_OUT_STOP_ALL_ES , ES_OUT_START_ALL_ES ,
ES_OUT_GET_BUFFERING , ES_OUT_SET_DELAY , ES_OUT_SET_RECORD_STATE , ES_OUT_SET_PAUSE_STATE ,
ES_OUT_SET_RATE , ES_OUT_SET_TIME , ES_OUT_SET_FRAME_NEXT , ES_OUT_SET_TIMES ,
ES_OUT_SET_JITTER , ES_OUT_GET_GROUP_FORCED , ES_OUT_SET_EOS
}
Functions
static void es_out_SetMode (es_out_t *p_out, int i_mode)
static mtime_t es_out_GetWakeup (es_out_t *p_out)
static bool es_out_GetBuffering (es_out_t *p_out)
static bool es_out_GetEmpty (es_out_t *p_out)
static void es_out_SetDelay (es_out_t *p_out, int i_cat, mtime_t i_delay)
static int es_out_SetRecordState (es_out_t *p_out, bool b_record)
static int es_out_SetPauseState (es_out_t *p_out, bool b_source_paused, bool b_paused, mtime_t i_date)
static int es_out_SetRate (es_out_t *p_out, int i_source_rate, int i_rate)
static int es_out_SetTime (es_out_t *p_out, mtime_t i_date)
static int es_out_SetFrameNext (es_out_t *p_out)
static void es_out_SetTimes (es_out_t *p_out, double f_position, mtime_t i_time, mtime_t i_length)
static void es_out_SetJitter (es_out_t *p_out, mtime_t i_pts_delay, mtime_t i_pts_jitter, int i_cr_average)
static int es_out_GetEsObjects (es_out_t *p_out, int i_id, vlc_object_t **pp_decoder, vout_thread_t **pp_vout, audio_output_t **pp_aout)
static int es_out_GetGroupForced (es_out_t *p_out)
static void es_out_Eos (es_out_t *p_out)
es_out_t * input_EsOutNew (input_thread_t *, int i_rate)
Enumeration Type Documentation
es_out_mode_e
enum es_out_mode_e
Enumerator
ES_OUT_MODE_NONE
ES_OUT_MODE_ALL
ES_OUT_MODE_AUTO
ES_OUT_MODE_PARTIAL
ES_OUT_MODE_END
es_out_query_private_e
enum es_out_query_private_e
Enumerator
ES_OUT_SET_MODE
ES_OUT_GET_WAKE_UP
ES_OUT_SET_ES_BY_ID
ES_OUT_RESTART_ES_BY_ID
ES_OUT_SET_ES_DEFAULT_BY_ID
ES_OUT_GET_ES_OBJECTS_BY_ID
ES_OUT_STOP_ALL_ES
ES_OUT_START_ALL_ES
ES_OUT_GET_BUFFERING
ES_OUT_SET_DELAY
ES_OUT_SET_RECORD_STATE
ES_OUT_SET_PAUSE_STATE
ES_OUT_SET_RATE
ES_OUT_SET_TIME
ES_OUT_SET_FRAME_NEXT
ES_OUT_SET_TIMES
ES_OUT_SET_JITTER
ES_OUT_GET_GROUP_FORCED
ES_OUT_SET_EOS
Function Documentation
es_out_Eos()
static void es_out_Eos (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_SET_EOS.
Referenced by MainLoopDemux().
es_out_GetBuffering()
static bool es_out_GetBuffering (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_GET_BUFFERING.
Referenced by ControlLockedGetBuffering(), MainLoop(), and TsRun().
es_out_GetEmpty()
static bool es_out_GetEmpty (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_GET_EMPTY.
Referenced by ControlLockedGetEmpty(), and MainLoop().
es_out_GetEsObjects()
static int es_out_GetEsObjects (es_out_t * p_out, int i_id, vlc_object_t ** pp_decoder, vout_thread_t ** pp_vout, audio_output_t ** pp_aout) inline static
References es_out_Control(), and ES_OUT_GET_ES_OBJECTS_BY_ID.
es_out_GetGroupForced()
static int es_out_GetGroupForced (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_GET_GROUP_FORCED.
Referenced by InitPrograms().
es_out_GetWakeup()
static mtime_t es_out_GetWakeup (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_GET_WAKE_UP.
Referenced by ControlLockedGetWakeup(), and MainLoop().
es_out_SetDelay()
static void es_out_SetDelay (es_out_t * p_out, int i_cat, mtime_t i_delay) inline static
References es_out_Control(), and ES_OUT_SET_DELAY.
Referenced by UpdatePtsDelay().
es_out_SetFrameNext()
static int es_out_SetFrameNext (es_out_t * p_out) inline static
References es_out_Control(), and ES_OUT_SET_FRAME_NEXT.
Referenced by Control(), and ControlLockedSetFrameNext().
es_out_SetJitter()
static void es_out_SetJitter (es_out_t * p_out, mtime_t i_pts_delay, mtime_t i_pts_jitter, int i_cr_average) inline static
References es_out_Control(), and ES_OUT_SET_JITTER.
Referenced by EsOutControlLocked(), and UpdatePtsDelay().
es_out_SetMode()
static void es_out_SetMode (es_out_t * p_out, int i_mode) inline static
References es_out_Control(), and ES_OUT_SET_MODE.
Referenced by End(), Init(), and InitPrograms().
es_out_SetPauseState()
static int es_out_SetPauseState (es_out_t * p_out, bool b_source_paused, bool b_paused, mtime_t i_date) inline static
References es_out_Control(), and ES_OUT_SET_PAUSE_STATE.
Referenced by ControlLockedSetPauseState(), ControlPause(), ControlUnpause(), and TsChangePause().
es_out_SetRate()
static int es_out_SetRate (es_out_t * p_out, int i_source_rate, int i_rate) inline static
References es_out_Control(), and ES_OUT_SET_RATE.
Referenced by Control(), ControlLockedSetRate(), TsChangeRate(), and TsRun().
es_out_SetRecordState()
static int es_out_SetRecordState (es_out_t * p_out, bool b_record) inline static
References es_out_Control(), and ES_OUT_SET_RECORD_STATE.
Referenced by Control().
es_out_SetTime()
static int es_out_SetTime (es_out_t * p_out, mtime_t i_date) inline static
References es_out_Control(), and ES_OUT_SET_TIME.
Referenced by Control(), and ControlLockedSetTime().
es_out_SetTimes()
static void es_out_SetTimes (es_out_t * p_out, double f_position, mtime_t i_time, mtime_t i_length) inline static
References es_out_Control(), and ES_OUT_SET_TIMES.
Referenced by MainLoopStatistics().
input_EsOutNew()
es_out_t * input_EsOutNew (input_thread_t * p_input, int i_rate)
References es_out_sys_t::audio, es_out_sys_t::b_active, es_out_sys_t::b_buffering, es_out_sys_t::es, ES_OUT_ES_POLICY_EXCLUSIVE, ES_OUT_ES_POLICY_SIMULTANEOUS, ES_OUT_MODE_NONE, EsOutAdd(), EsOutControl(), EsOutDel(), EsOutDelete(), EsOutPropsInit(), EsOutSend(), es_out_sys_t::i_es, es_out_sys_t::i_group_id, es_out_sys_t::i_mode, es_out_sys_t::i_pause_date, es_out_sys_t::i_pgrm, es_out_sys_t::i_preroll_end, es_out_sys_t::i_prev_stream_level, es_out_sys_t::i_rate, es_out_sys_t::lock, es_out_sys_t::p_input, es_out_t::p_sys, es_out_t::pf_add, es_out_t::pf_control, es_out_t::pf_del, es_out_t::pf_destroy, es_out_t::pf_send, es_out_sys_t::pgrm, es_out_sys_t::sub, TAB_INIT, var_GetInteger, es_out_sys_t::video, and vlc_mutex_init_recursive().
Referenced by Create().