VLC: src/input/es_out_timeshift.c File Reference
es_out_timeshift.c File Reference
Data Structures
struct ts_cmd_add_t
struct ts_cmd_del_t
struct ts_cmd_send_t
struct ts_cmd_control_t
struct ts_cmd_t
struct ts_storage_t
struct ts_thread_t
struct es_out_id_t
struct es_out_sys_t
Macros
#define attribute_packed
Typedefs
typedef struct ts_storage_t ts_storage_t
Enumerations
enum { C_ADD , C_SEND , C_DEL , C_CONTROL }
Functions
static es_out_id_t * Add (es_out_t *, const es_format_t *)
static int Send (es_out_t *, es_out_id_t *, block_t *)
static void Del (es_out_t *, es_out_id_t *)
static int Control (es_out_t *, int i_query, va_list)
static void Destroy (es_out_t *)
static int TsStart (es_out_t *)
static void TsAutoStop (es_out_t *)
static void TsStop (ts_thread_t *)
static void TsPushCmd (ts_thread_t *, ts_cmd_t *)
static int TsPopCmdLocked (ts_thread_t *, ts_cmd_t *, bool b_flush)
static bool TsHasCmd (ts_thread_t *)
static bool TsIsUnused (ts_thread_t *)
static int TsChangePause (ts_thread_t *, bool b_source_paused, bool b_paused, mtime_t i_date)
static int TsChangeRate (ts_thread_t *, int i_src_rate, int i_rate)
static void * TsRun (void *)
static ts_storage_t * TsStorageNew (const char *psz_path, int64_t i_tmp_size_max)
static void TsStorageDelete (ts_storage_t *)
static void TsStoragePack (ts_storage_t *p_storage)
static bool TsStorageIsFull (ts_storage_t *, const ts_cmd_t *p_cmd)
static bool TsStorageIsEmpty (ts_storage_t *)
static void TsStoragePushCmd (ts_storage_t *, const ts_cmd_t *p_cmd, bool b_flush)
static void TsStoragePopCmd (ts_storage_t *p_storage, ts_cmd_t *p_cmd, bool b_flush)
static void CmdClean (ts_cmd_t *)
static void cmd_cleanup_routine (void *p)
static int CmdInitAdd (ts_cmd_t *, es_out_id_t *, const es_format_t *, bool b_copy)
static void CmdInitSend (ts_cmd_t *, es_out_id_t *, block_t *)
static int CmdInitDel (ts_cmd_t *, es_out_id_t *)
static int CmdInitControl (ts_cmd_t *, int i_query, va_list, bool b_copy)
static void CmdCleanAdd (ts_cmd_t *)
static void CmdCleanSend (ts_cmd_t *)
static void CmdCleanControl (ts_cmd_t *p_cmd)
static void CmdExecuteAdd (es_out_t *, ts_cmd_t *)
static int CmdExecuteSend (es_out_t *, ts_cmd_t *)
static void CmdExecuteDel (es_out_t *, ts_cmd_t *)
static int CmdExecuteControl (es_out_t *, ts_cmd_t *)
static int GetTmpFile (char **ppsz_file, const char *psz_path)
es_out_t * input_EsOutTimeshiftNew (input_thread_t *p_input, es_out_t *p_next_out, int i_rate)
static int ControlLockedGetEmpty (es_out_t *p_out, bool *pb_empty)
static int ControlLockedGetWakeup (es_out_t *p_out, mtime_t *pi_wakeup)
static int ControlLockedGetBuffering (es_out_t *p_out, bool *pb_buffering)
static int ControlLockedSetPauseState (es_out_t *p_out, bool b_source_paused, bool b_paused, mtime_t i_date)
static int ControlLockedSetRate (es_out_t *p_out, int i_src_rate, int i_rate)
static int ControlLockedSetTime (es_out_t *p_out, mtime_t i_date)
static int ControlLockedSetFrameNext (es_out_t *p_out)
static int ControlLocked (es_out_t *p_out, int i_query, va_list args)
static void TsDestroy (ts_thread_t *p_ts)
Macro Definition Documentation
attribute_packed
#define attribute_packed
Typedef Documentation
ts_storage_t
typedef struct ts_storage_t ts_storage_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
C_ADD
C_SEND
C_DEL
C_CONTROL
Function Documentation
Add()
static es_out_id_t * Add (es_out_t * p_out, const es_format_t * p_fmt) static
References es_out_sys_t::b_delayed, CmdExecuteAdd(), CmdInitAdd(), es_out_sys_t::i_es, es_out_sys_t::lock, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_sys_t::pp_es, TAB_APPEND, TsAutoStop(), TsPushCmd(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_EsOutTimeshiftNew().
cmd_cleanup_routine()
static void cmd_cleanup_routine (void * p) static
References CmdClean(), and p.
Referenced by TsRun().
CmdClean()
static void CmdClean (ts_cmd_t * p_cmd) static
References C_ADD, C_CONTROL, C_DEL, C_SEND, CmdCleanAdd(), CmdCleanControl(), CmdCleanSend(), ts_cmd_t::i_type, and vlc_assert_unreachable.
Referenced by cmd_cleanup_routine(), TsPushCmd(), TsStop(), and TsStorageDelete().
CmdCleanAdd()
static void CmdCleanAdd (ts_cmd_t * p_cmd) static
References ts_cmd_t::add, es_format_Clean(), ts_cmd_add_t::p_fmt, and ts_cmd_t::u.
Referenced by CmdClean(), and TsRun().
CmdCleanControl()
static void CmdCleanControl (ts_cmd_t * p_cmd) static
References ts_cmd_t::control, ts_cmd_control_t::es_fmt, es_format_Clean(), ES_OUT_SET_ES_FMT, ES_OUT_SET_GROUP_EPG, ES_OUT_SET_GROUP_EPG_EVENT, ES_OUT_SET_GROUP_META, ES_OUT_SET_META, ts_cmd_control_t::i_query, ts_cmd_control_t::int_epg, ts_cmd_control_t::int_epg_evt, ts_cmd_control_t::int_meta, ts_cmd_control_t::p_epg, ts_cmd_control_t::p_evt, ts_cmd_control_t::p_fmt, ts_cmd_control_t::p_meta, ts_cmd_control_t::u, ts_cmd_t::u, vlc_epg_Delete(), vlc_epg_event_Delete(), and vlc_meta_Delete().
Referenced by CmdClean(), and TsRun().
CmdCleanSend()
static void CmdCleanSend (ts_cmd_t * p_cmd) static
References block_Release(), ts_cmd_send_t::p_block, ts_cmd_t::send, and ts_cmd_t::u.
Referenced by CmdClean(), and TsRun().
CmdExecuteAdd()
static void CmdExecuteAdd (es_out_t * p_out, ts_cmd_t * p_cmd) static
References ts_cmd_t::add, es_out_Add(), es_out_id_t::p_es, ts_cmd_add_t::p_es, ts_cmd_add_t::p_fmt, and ts_cmd_t::u.
Referenced by Add(), and TsRun().
CmdExecuteControl()
static int CmdExecuteControl (es_out_t * p_out, ts_cmd_t * p_cmd) static
< Unspecified error
References ts_cmd_control_t::b_bool, ts_cmd_t::control, ts_cmd_control_t::es_bool, ts_cmd_control_t::es_fmt, es_out_Control(), ES_OUT_DEL_GROUP, ES_OUT_RESET_PCR, ES_OUT_RESTART_ALL_ES, ES_OUT_RESTART_ES, ES_OUT_SET_EOS, ES_OUT_SET_EPG_TIME, ES_OUT_SET_ES, ES_OUT_SET_ES_CAT_POLICY, ES_OUT_SET_ES_DEFAULT, ES_OUT_SET_ES_FMT, ES_OUT_SET_ES_SCRAMBLED_STATE, ES_OUT_SET_ES_STATE, ES_OUT_SET_GROUP, ES_OUT_SET_GROUP_EPG, ES_OUT_SET_GROUP_EPG_EVENT, ES_OUT_SET_GROUP_META, ES_OUT_SET_GROUP_PCR, ES_OUT_SET_JITTER, ES_OUT_SET_META, ES_OUT_SET_MODE, ES_OUT_SET_NEXT_DISPLAY_TIME, ES_OUT_SET_PCR, ES_OUT_SET_TIMES, ts_cmd_control_t::es_policy, ts_cmd_control_t::f_position, ts_cmd_control_t::i_cat, ts_cmd_control_t::i_cr_average, ts_cmd_control_t::i_i64, ts_cmd_control_t::i_int, ts_cmd_control_t::i_length, ts_cmd_control_t::i_policy, ts_cmd_control_t::i_pts_delay, ts_cmd_control_t::i_pts_jitter, ts_cmd_control_t::i_query, ts_cmd_control_t::i_time, ts_cmd_control_t::int_epg, ts_cmd_control_t::int_epg_evt, ts_cmd_control_t::int_i64, ts_cmd_control_t::int_meta, ts_cmd_control_t::jitter, ts_cmd_control_t::p_epg, es_out_id_t::p_es, ts_cmd_control_t::p_es, ts_cmd_control_t::p_evt, ts_cmd_control_t::p_fmt, ts_cmd_control_t::p_meta, ts_cmd_control_t::times, ts_cmd_control_t::u, ts_cmd_t::u, vlc_assert_unreachable, and VLC_EGENERIC.
Referenced by ControlLocked(), and TsRun().
CmdExecuteDel()
static void CmdExecuteDel (es_out_t * p_out, ts_cmd_t * p_cmd) static
References ts_cmd_t::del, es_out_Del(), es_out_id_t::p_es, ts_cmd_del_t::p_es, and ts_cmd_t::u.
Referenced by Del(), and TsRun().
CmdExecuteSend()
static int CmdExecuteSend (es_out_t * p_out, ts_cmd_t * p_cmd) static
< Unspecified error
References block_Release(), es_out_Send(), ts_cmd_send_t::p_block, es_out_id_t::p_es, ts_cmd_send_t::p_es, ts_cmd_t::send, ts_cmd_t::u, and VLC_EGENERIC.
Referenced by Send(), and TsRun().
CmdInitAdd()
static int CmdInitAdd (ts_cmd_t * p_cmd, es_out_id_t * p_es, const es_format_t * p_fmt, bool b_copy) static
< Unspecified error
< No error
References ts_cmd_t::add, C_ADD, es_format_Copy(), ts_cmd_t::i_date, ts_cmd_t::i_type, mdate(), ts_cmd_add_t::p_es, ts_cmd_add_t::p_fmt, ts_cmd_t::u, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by Add().
CmdInitControl()
static int CmdInitControl (ts_cmd_t * p_cmd, int i_query, va_list args, bool b_copy) static
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References ts_cmd_control_t::b_bool, C_CONTROL, ts_cmd_t::control, ts_cmd_control_t::es_bool, ts_cmd_control_t::es_fmt, es_format_Copy(), ES_OUT_DEL_GROUP, ES_OUT_RESET_PCR, ES_OUT_RESTART_ALL_ES, ES_OUT_RESTART_ES, ES_OUT_SET_EOS, ES_OUT_SET_EPG_TIME, ES_OUT_SET_ES, ES_OUT_SET_ES_CAT_POLICY, ES_OUT_SET_ES_DEFAULT, ES_OUT_SET_ES_FMT, ES_OUT_SET_ES_SCRAMBLED_STATE, ES_OUT_SET_ES_STATE, ES_OUT_SET_GROUP, ES_OUT_SET_GROUP_EPG, ES_OUT_SET_GROUP_EPG_EVENT, ES_OUT_SET_GROUP_META, ES_OUT_SET_GROUP_PCR, ES_OUT_SET_JITTER, ES_OUT_SET_META, ES_OUT_SET_MODE, ES_OUT_SET_NEXT_DISPLAY_TIME, ES_OUT_SET_PCR, ES_OUT_SET_TIMES, ts_cmd_control_t::es_policy, ts_cmd_control_t::f_position, ts_cmd_control_t::i_cat, ts_cmd_control_t::i_cr_average, ts_cmd_t::i_date, ts_cmd_control_t::i_i64, ts_cmd_control_t::i_int, ts_cmd_control_t::i_length, ts_cmd_control_t::i_policy, ts_cmd_control_t::i_pts_delay, ts_cmd_control_t::i_pts_jitter, ts_cmd_control_t::i_query, ts_cmd_control_t::i_time, ts_cmd_t::i_type, ts_cmd_control_t::int_epg, ts_cmd_control_t::int_epg_evt, ts_cmd_control_t::int_i64, ts_cmd_control_t::int_meta, ts_cmd_control_t::jitter, mdate(), ts_cmd_control_t::p_epg, ts_cmd_control_t::p_es, ts_cmd_control_t::p_evt, ts_cmd_control_t::p_fmt, ts_cmd_control_t::p_meta, ts_cmd_control_t::times, ts_cmd_control_t::u, ts_cmd_t::u, vlc_assert_unreachable, VLC_EGENERIC, vlc_epg_Duplicate(), vlc_epg_event_Duplicate(), vlc_meta_Merge(), vlc_meta_New(), and VLC_SUCCESS.
Referenced by ControlLocked().
CmdInitDel()
static int CmdInitDel (ts_cmd_t * p_cmd, es_out_id_t * p_es) static
< No error
References C_DEL, ts_cmd_t::del, ts_cmd_t::i_date, ts_cmd_t::i_type, mdate(), ts_cmd_del_t::p_es, ts_cmd_t::u, and VLC_SUCCESS.
Referenced by Del().
CmdInitSend()
static void CmdInitSend (ts_cmd_t * p_cmd, es_out_id_t * p_es, block_t * p_block) static
References C_SEND, ts_cmd_t::i_date, ts_cmd_t::i_type, mdate(), ts_cmd_send_t::p_block, ts_cmd_send_t::p_es, ts_cmd_t::send, and ts_cmd_t::u.
Referenced by Send().
Control()
static int Control (es_out_t * p_out, int i_query, va_list args) static
References ControlLocked(), es_out_sys_t::lock, es_out_t::p_sys, TsAutoStop(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_EsOutTimeshiftNew().
ControlLocked()
static int ControlLocked (es_out_t * p_out, int i_query, va_list args) static
< Unspecified error
< No error
< No error
< Unspecified error
< Unspecified error
< Unspecified error
References es_out_sys_t::b_delayed, CmdExecuteControl(), CmdInitControl(), ControlLockedGetBuffering(), ControlLockedGetEmpty(), ControlLockedGetWakeup(), ControlLockedSetFrameNext(), ControlLockedSetPauseState(), ControlLockedSetRate(), ControlLockedSetTime(), es_out_Control(), es_out_ControlModifyPcrSystem(), ES_OUT_DEL_GROUP, ES_OUT_GET_BUFFERING, ES_OUT_GET_EMPTY, ES_OUT_GET_ES_OBJECTS_BY_ID, ES_OUT_GET_ES_STATE, ES_OUT_GET_GROUP_FORCED, ES_OUT_GET_PCR_SYSTEM, ES_OUT_GET_WAKE_UP, ES_OUT_MODIFY_PCR_SYSTEM, ES_OUT_POST_SUBNODE, ES_OUT_RESET_PCR, ES_OUT_RESTART_ALL_ES, ES_OUT_RESTART_ES, ES_OUT_RESTART_ES_BY_ID, ES_OUT_SET_DELAY, ES_OUT_SET_EOS, ES_OUT_SET_EPG_TIME, ES_OUT_SET_ES, ES_OUT_SET_ES_BY_ID, ES_OUT_SET_ES_CAT_POLICY, ES_OUT_SET_ES_DEFAULT, ES_OUT_SET_ES_DEFAULT_BY_ID, ES_OUT_SET_ES_FMT, ES_OUT_SET_ES_SCRAMBLED_STATE, ES_OUT_SET_ES_STATE, ES_OUT_SET_FRAME_NEXT, ES_OUT_SET_GROUP, ES_OUT_SET_GROUP_EPG, ES_OUT_SET_GROUP_EPG_EVENT, ES_OUT_SET_GROUP_META, ES_OUT_SET_GROUP_PCR, ES_OUT_SET_JITTER, ES_OUT_SET_META, ES_OUT_SET_MODE, ES_OUT_SET_NEXT_DISPLAY_TIME, ES_OUT_SET_PAUSE_STATE, ES_OUT_SET_PCR, ES_OUT_SET_RATE, ES_OUT_SET_RECORD_STATE, ES_OUT_SET_TIME, ES_OUT_SET_TIMES, ES_OUT_START_ALL_ES, ES_OUT_STOP_ALL_ES, es_out_vaControl(), es_out_id_t::p_es, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, TsPushCmd(), vlc_assert_unreachable, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by Control().
ControlLockedGetBuffering()
static int ControlLockedGetBuffering (es_out_t * p_out, bool * pb_buffering) static
< No error
References es_out_sys_t::b_delayed, es_out_GetBuffering(), es_out_sys_t::p_out, es_out_t::p_sys, and VLC_SUCCESS.
Referenced by ControlLocked().
ControlLockedGetEmpty()
static int ControlLockedGetEmpty (es_out_t * p_out, bool * pb_empty) static
< No error
References es_out_sys_t::b_delayed, es_out_GetEmpty(), es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, TsHasCmd(), and VLC_SUCCESS.
Referenced by ControlLocked().
ControlLockedGetWakeup()
static int ControlLockedGetWakeup (es_out_t * p_out, mtime_t * pi_wakeup) static
< No error
References input_thread_private_t::b_can_pace_control, es_out_sys_t::b_delayed, es_out_GetWakeup(), input_priv(), es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, and VLC_SUCCESS.
Referenced by ControlLocked().
ControlLockedSetFrameNext()
static int ControlLockedSetFrameNext (es_out_t * p_out) static
References es_out_SetFrameNext(), es_out_sys_t::p_out, and es_out_t::p_sys.
Referenced by ControlLocked().
ControlLockedSetPauseState()
static int ControlLockedSetPauseState (es_out_t * p_out, bool b_source_paused, bool b_paused, mtime_t i_date) static
< Unspecified error
References input_thread_private_t::b_can_pace_control, es_out_sys_t::b_delayed, es_out_sys_t::b_input_paused, es_out_sys_t::b_input_paused_source, es_out_SetPauseState(), input_priv(), msg_Err, es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, TsChangePause(), TsStart(), and VLC_EGENERIC.
Referenced by ControlLocked().
ControlLockedSetRate()
static int ControlLockedSetRate (es_out_t * p_out, int i_src_rate, int i_rate) static
< Unspecified error
References input_thread_private_t::b_can_pace_control, es_out_sys_t::b_delayed, es_out_SetRate(), es_out_sys_t::i_input_rate, es_out_sys_t::i_input_rate_source, input_priv(), msg_Err, es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, TsChangeRate(), TsStart(), and VLC_EGENERIC.
Referenced by ControlLocked().
ControlLockedSetTime()
static int ControlLockedSetTime (es_out_t * p_out, mtime_t i_date) static
< Unspecified error
References es_out_sys_t::b_delayed, es_out_SetTime(), msg_Err, es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, and VLC_EGENERIC.
Referenced by ControlLocked().
Del()
static void Del (es_out_t * p_out, es_out_id_t * p_es) static
References es_out_sys_t::b_delayed, CmdExecuteDel(), CmdInitDel(), es_out_sys_t::i_es, es_out_sys_t::lock, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_sys_t::pp_es, TAB_REMOVE, TsAutoStop(), TsPushCmd(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Destroy(), and input_EsOutTimeshiftNew().
Destroy()
static void Destroy (es_out_t * p_out) static
References es_out_sys_t::b_delayed, Del(), es_out_sys_t::i_es, es_out_sys_t::lock, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_sys_t::pp_es, es_out_sys_t::psz_tmp_path, TAB_CLEAN, TsStop(), and vlc_mutex_destroy().
Referenced by input_EsOutTimeshiftNew().
GetTmpFile()
static int GetTmpFile (char ** ppsz_file, const char * psz_path) static
References asprintf(), DIR_SEP, strdup(), unlikely, vlc_mkdir(), and vlc_mkstemp().
Referenced by TsStorageNew().
input_EsOutTimeshiftNew()
es_out_t * input_EsOutTimeshiftNew (input_thread_t * p_input, es_out_t * p_next_out, int i_rate)
References Add(), es_out_sys_t::b_delayed, es_out_sys_t::b_input_paused, es_out_sys_t::b_input_paused_source, Control(), count, Del(), Destroy(), DIR_SEP_CHAR, es_out_sys_t::i_es, es_out_sys_t::i_input_rate, es_out_sys_t::i_input_rate_source, es_out_sys_t::i_tmp_size_max, es_out_sys_t::lock, msg_Dbg, es_out_sys_t::p_input, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_t::pf_add, es_out_t::pf_control, es_out_t::pf_del, es_out_t::pf_destroy, es_out_t::pf_send, es_out_sys_t::pp_es, es_out_sys_t::psz_tmp_path, Send(), strdup(), TAB_INIT, var_CreateGetInteger, var_InheritString, vlc_alloc(), and vlc_mutex_init_recursive().
Referenced by Init().
Send()
static int Send (es_out_t * p_out, es_out_id_t * p_es, block_t * p_block) static
< No error
References es_out_sys_t::b_delayed, CmdExecuteSend(), CmdInitSend(), es_out_sys_t::lock, es_out_sys_t::p_out, es_out_t::p_sys, es_out_sys_t::p_ts, TsAutoStop(), TsPushCmd(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by input_EsOutTimeshiftNew().
TsAutoStop()
static void TsAutoStop (es_out_t * p_out) static
References es_out_sys_t::b_delayed, msg_Warn, es_out_sys_t::p_input, es_out_t::p_sys, es_out_sys_t::p_ts, TsIsUnused(), and TsStop().
Referenced by Add(), Control(), Del(), and Send().
TsChangePause()
static int TsChangePause (ts_thread_t * p_ts, bool b_source_paused, bool b_paused, mtime_t i_date) static
References ts_thread_t::b_paused, es_out_SetPauseState(), ts_thread_t::i_cmd_delay, ts_thread_t::i_pause_date, ts_thread_t::lock, ts_thread_t::p_out, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and ts_thread_t::wait.
Referenced by ControlLockedSetPauseState().
TsChangeRate()
static int TsChangeRate (ts_thread_t * p_ts, int i_src_rate, int i_rate) static
References es_out_SetRate(), ts_thread_t::i_cmd_delay, ts_thread_t::i_rate, ts_thread_t::i_rate_date, ts_thread_t::i_rate_delay, ts_thread_t::i_rate_source, ts_thread_t::lock, ts_thread_t::p_out, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ControlLockedSetRate().
TsDestroy()
static void TsDestroy (ts_thread_t * p_ts) static
References ts_thread_t::lock, vlc_cond_destroy(), vlc_mutex_destroy(), and ts_thread_t::wait.
Referenced by TsStart(), and TsStop().
TsHasCmd()
static bool TsHasCmd (ts_thread_t * p_ts) static
References ts_thread_t::lock, ts_thread_t::p_storage_r, TsStorageIsEmpty(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ControlLockedGetEmpty().
TsIsUnused()
static bool TsIsUnused (ts_thread_t * p_ts) static
References ts_thread_t::b_paused, ts_thread_t::i_rate, ts_thread_t::i_rate_source, ts_thread_t::lock, ts_thread_t::p_storage_r, TsStorageIsEmpty(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by TsAutoStop().
TsPopCmdLocked()
static int TsPopCmdLocked (ts_thread_t * p_ts, ts_cmd_t * p_cmd, bool b_flush) static
< Unspecified error
< No error
References ts_thread_t::lock, ts_storage_t::p_next, ts_thread_t::p_storage_r, TsStorageDelete(), TsStorageIsEmpty(), TsStoragePopCmd(), vlc_assert_locked(), VLC_EGENERIC, and VLC_SUCCESS.
Referenced by TsRun(), and TsStop().
TsPushCmd()
static void TsPushCmd (ts_thread_t * p_ts, ts_cmd_t * p_cmd) static
References CmdClean(), ts_thread_t::i_tmp_size_max, ts_thread_t::lock, ts_storage_t::p_next, ts_thread_t::p_storage_r, ts_thread_t::p_storage_w, ts_thread_t::psz_tmp_path, TsStorageIsFull(), TsStorageNew(), TsStoragePack(), TsStoragePushCmd(), vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and ts_thread_t::wait.
Referenced by Add(), ControlLocked(), Del(), and Send().
TsRun()
static void * TsRun (void * p_data) static
References ts_thread_t::b_paused, C_ADD, C_CONTROL, C_DEL, C_SEND, cmd_cleanup_routine(), CmdCleanAdd(), CmdCleanControl(), CmdCleanSend(), CmdExecuteAdd(), CmdExecuteControl(), CmdExecuteDel(), CmdExecuteSend(), es_out_GetBuffering(), es_out_SetRate(), ts_thread_t::i_buffering_delay, ts_thread_t::i_cmd_delay, ts_cmd_t::i_date, vlc_value_t::i_int, ts_thread_t::i_rate, ts_thread_t::i_rate_date, ts_thread_t::i_rate_delay, ts_thread_t::i_rate_source, ts_cmd_t::i_type, INPUT_CONTROL_SET_RATE, input_ControlPush(), ts_thread_t::lock, msg_Warn, mutex_cleanup_push, mwait, ts_thread_t::p_input, ts_thread_t::p_out, TsPopCmdLocked(), vlc_assert_unreachable, vlc_cleanup_pop, vlc_cleanup_push, vlc_cond_wait(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), vlc_savecancel(), and ts_thread_t::wait.
Referenced by TsStart().
TsStart()
static int TsStart (es_out_t * p_out) static
< Unspecified error
< Unspecified error
< No error
References es_out_sys_t::b_delayed, es_out_sys_t::b_input_paused, es_out_sys_t::b_input_paused_source, ts_thread_t::b_paused, ts_thread_t::i_buffering_delay, ts_thread_t::i_cmd_delay, es_out_sys_t::i_input_rate, es_out_sys_t::i_input_rate_source, ts_thread_t::i_pause_date, ts_thread_t::i_rate, ts_thread_t::i_rate_date, ts_thread_t::i_rate_delay, ts_thread_t::i_rate_source, es_out_sys_t::i_tmp_size_max, ts_thread_t::i_tmp_size_max, ts_thread_t::lock, mdate(), msg_Err, es_out_sys_t::p_input, ts_thread_t::p_input, es_out_sys_t::p_out, ts_thread_t::p_out, ts_thread_t::p_storage_r, ts_thread_t::p_storage_w, es_out_t::p_sys, es_out_sys_t::p_ts, es_out_sys_t::psz_tmp_path, ts_thread_t::psz_tmp_path, ts_thread_t::thread, TsDestroy(), TsRun(), vlc_clone(), vlc_cond_init(), VLC_EGENERIC, vlc_mutex_init(), VLC_SUCCESS, VLC_THREAD_PRIORITY_INPUT, and ts_thread_t::wait.
Referenced by ControlLockedSetPauseState(), and ControlLockedSetRate().
TsStop()
static void TsStop (ts_thread_t * p_ts) static
References CmdClean(), ts_thread_t::lock, ts_storage_t::p_next, ts_thread_t::p_storage_r, ts_thread_t::thread, TsDestroy(), TsPopCmdLocked(), TsStorageDelete(), vlc_cancel(), vlc_join(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Destroy(), and TsAutoStop().
TsStorageDelete()
static void TsStorageDelete (ts_storage_t * p_storage) static
References CmdClean(), ts_storage_t::i_cmd_r, ts_storage_t::i_cmd_w, ts_storage_t::p_cmd, ts_storage_t::p_filer, ts_storage_t::p_filew, TsStoragePopCmd(), and vlc_unlink().
Referenced by TsPopCmdLocked(), TsStop(), and TsStorageNew().
TsStorageIsEmpty()
static bool TsStorageIsEmpty (ts_storage_t * p_storage) static
References ts_storage_t::i_cmd_r, and ts_storage_t::i_cmd_w.
Referenced by TsHasCmd(), TsIsUnused(), TsPopCmdLocked(), and TsStoragePopCmd().
TsStorageIsFull()
static bool TsStorageIsFull (ts_storage_t * p_storage, const ts_cmd_t * p_cmd) static
References C_SEND, block_t::i_buffer, ts_storage_t::i_cmd_max, ts_storage_t::i_cmd_w, ts_storage_t::i_file_max, ts_storage_t::i_file_size, ts_cmd_t::i_type, ts_cmd_send_t::p_block, ts_cmd_t::send, and ts_cmd_t::u.
Referenced by TsPushCmd(), and TsStoragePushCmd().
TsStorageNew()
static ts_storage_t * TsStorageNew (const char * psz_path, int64_t i_tmp_size_max) static
References GetTmpFile(), ts_storage_t::i_cmd_max, ts_storage_t::i_cmd_r, ts_storage_t::i_cmd_w, ts_storage_t::i_file_max, ts_storage_t::i_file_size, ts_storage_t::p_cmd, ts_storage_t::p_filer, ts_storage_t::p_filew, ts_storage_t::p_next, TsStorageDelete(), unlikely, vlc_alloc(), vlc_close(), vlc_fopen(), and vlc_unlink().
Referenced by TsPushCmd().
TsStoragePack()
static void TsStoragePack (ts_storage_t * p_storage) static
References ts_storage_t::i_cmd_max, ts_storage_t::i_cmd_w, and ts_storage_t::p_cmd.
Referenced by TsPushCmd().
TsStoragePopCmd()
static void TsStoragePopCmd (ts_storage_t * p_storage, ts_cmd_t * p_cmd, bool b_flush) static
References block_Alloc(), C_SEND, block_t::i_buffer, ts_storage_t::i_cmd_r, block_t::i_dts, block_t::i_flags, block_t::i_length, block_t::i_nb_samples, ts_cmd_send_t::i_offset, block_t::i_pts, ts_cmd_t::i_type, ts_cmd_send_t::p_block, block_t::p_buffer, ts_storage_t::p_cmd, ts_storage_t::p_filer, ts_cmd_t::send, TsStorageIsEmpty(), and ts_cmd_t::u.
Referenced by TsPopCmdLocked(), and TsStorageDelete().
TsStoragePushCmd()
static void TsStoragePushCmd (ts_storage_t * p_storage, const ts_cmd_t * p_cmd, bool b_flush) static
References block_Release(), C_SEND, block_t::i_buffer, ts_storage_t::i_cmd_w, ts_storage_t::i_file_size, ts_cmd_send_t::i_offset, ts_cmd_t::i_type, ts_cmd_send_t::p_block, block_t::p_buffer, ts_storage_t::p_cmd, ts_storage_t::p_filew, ts_cmd_t::send, TsStorageIsFull(), and ts_cmd_t::u.
Referenced by TsPushCmd().