VLC: src/misc/es_format.c File Reference
es_format.c File Reference
Functions
static int BinaryLog (uint32_t i)
static void MaskToShift (int *pi_left, int *pi_right, uint32_t i_mask)
It transforms a color mask into right and left shifts FIXME copied from video_output.c.
void video_format_FixRgb (video_format_t *p_fmt)
This function will fill all RGB shift from RGB masks.
void video_format_Setup (video_format_t *p_fmt, vlc_fourcc_t i_chroma, int i_width, int i_height, int i_visible_width, int i_visible_height, int i_sar_num, int i_sar_den)
It will fill up a video_format_t using the given arguments.
void video_format_CopyCrop (video_format_t *p_dst, const video_format_t *p_src)
It will copy the crop properties from a video_format_t to another.
void video_format_ScaleCropAr (video_format_t *p_dst, const video_format_t *p_src)
It will compute the crop/ar properties when scaling.
static void transform_GetBasicOps (video_transform_t transform, unsigned *restrict angle, bool *restrict hflip)
static video_transform_t transform_FromBasicOps (unsigned angle, bool hflip)
video_transform_t video_format_GetTransform (video_orientation_t src, video_orientation_t dst)
Returns the operation required to transform src into dst.
void video_format_TransformBy (video_format_t *fmt, video_transform_t transform)
This function applies the transform operation to fmt.
void video_format_TransformTo (video_format_t *restrict fmt, video_orientation_t dst_orientation)
void video_format_ApplyRotation (video_format_t *restrict out, const video_format_t *restrict in)
bool video_format_IsSimilar (const video_format_t *f1, const video_format_t *f2)
This function will check if the first video format is similar to the second one.
void video_format_Print (vlc_object_t *p_this, const char *psz_text, const video_format_t *fmt)
It prints details about the given video_format_t.
void es_format_Init (es_format_t *fmt, int i_cat, vlc_fourcc_t i_codec)
This function will initialize a es_format_t structure.
void es_format_InitFromVideo (es_format_t *p_es, const video_format_t *p_fmt)
This function will initialize a es_format_t structure from a video_format_t.
int es_format_Copy (es_format_t *restrict dst, const es_format_t *src)
void es_format_Clean (es_format_t *fmt)
This function will clean up a es_format_t and release all associated resources.
bool es_format_IsSimilar (const es_format_t *p_fmt1, const es_format_t *p_fmt2)
This function will check if the first ES format is similar to the second one.
Function Documentation
BinaryLog()
static int BinaryLog (uint32_t i) static
Referenced by MaskToShift().
es_format_Clean()
void es_format_Clean (es_format_t * fmt)
This function will clean up a es_format_t and release all associated resources.
You can call it multiple times on the same structure.
References es_format_Init(), es_format_t::i_cat, es_format_t::i_extra, es_format_t::i_extra_languages, es_format_t::p_extra, es_format_t::p_extra_languages, subs_format_t::p_style, es_format_t::psz_description, extra_languages_t::psz_description, subs_format_t::psz_encoding, es_format_t::psz_language, extra_languages_t::psz_language, SPU_ES, es_format_t::subs, text_style_Delete(), UNKNOWN_ES, es_format_t::video, VIDEO_ES, and video_format_Clean().
Referenced by CmdCleanAdd(), CmdCleanControl(), DecoderUpdateFormatLocked(), DeleteDecoder(), DeleteDecoder(), DeleteEncoder(), DeleteFilter(), demux_PacketizerDestroy(), demux_PacketizerNew(), es_format_Change(), EsOutControlLocked(), EsOutCreateCCChannels(), EsOutDel(), EsOutSend(), EsOutTerminate(), filter_chain_AppendInner(), filter_chain_Delete(), filter_chain_DeleteFilter(), filter_chain_Reset(), input_item_Release(), input_item_UpdateTracksInfo(), LoadDecoder(), ReloadDecoder(), sout_MuxAddStream(), sout_MuxDeleteStream(), ThreadChangeFilters(), UnloadDecoder(), and VoutDisplayCreateRender().
es_format_Copy()
int es_format_Copy (es_format_t *restrict dst, const es_format_t * src)
< No error
< Not enough memory
< Not enough memory
< Not enough memory
< Not enough memory
< Not enough memory
< Not enough memory
References es_format_t::i_cat, es_format_t::i_extra, es_format_t::i_extra_languages, likely, es_format_t::p_extra, es_format_t::p_extra_languages, subs_format_t::p_style, es_format_t::psz_description, extra_languages_t::psz_description, subs_format_t::psz_encoding, es_format_t::psz_language, extra_languages_t::psz_language, SPU_ES, strdup(), es_format_t::subs, text_style_Duplicate(), unlikely, es_format_t::video, VIDEO_ES, video_format_Copy(), VLC_ENOMEM, and VLC_SUCCESS.
Referenced by CmdInitAdd(), CmdInitControl(), CreateFilter(), DecoderUpdateFormatLocked(), EsOutAddSlave(), EsOutControlLocked(), filter_chain_AppendInner(), filter_chain_Reset(), input_DecoderHasFormatChanged(), input_item_UpdateTracksInfo(), LoadDecoder(), ReloadDecoder(), and sout_MuxAddStream().
es_format_Init()
void es_format_Init (es_format_t * fmt, int i_cat, vlc_fourcc_t i_codec)
This function will initialize a es_format_t structure.
References es_format_t::b_packetized, ES_PRIORITY_SELECTABLE_MIN, es_format_t::i_cat, es_format_t::i_codec, i_codec, es_format_t::i_id, es_format_t::i_level, es_format_t::i_priority, es_format_t::i_profile, es_format_t::p_extra, es_format_t::p_extra_languages, es_format_t::psz_description, es_format_t::psz_language, es_format_t::video, VIDEO_ES, and video_format_Init().
Referenced by CreateDecoder(), CreateDecoder(), demux_PacketizerNew(), es_format_Change(), es_format_Clean(), es_format_InitFromVideo(), EsOutCreateCCChannels(), filter_chain_NewInner(), filter_NewBlend(), ImageConvert(), ImageWrite(), input_DecoderSetCcState(), LoadDecoder(), SpuRenderCreateAndLoadScale(), SpuRenderCreateAndLoadText(), and vlm_OnMediaUpdate().
es_format_InitFromVideo()
void es_format_InitFromVideo (es_format_t * p_es, const video_format_t * p_fmt)
This function will initialize a es_format_t structure from a video_format_t.
References es_format_Init(), video_format_t::i_chroma, es_format_t::video, VIDEO_ES, and video_format_Copy().
Referenced by CreateDecoder(), CreateEncoder(), ThreadChangeFilters(), and VoutDisplayCreateRender().
es_format_IsSimilar()
bool es_format_IsSimilar (const es_format_t * p_fmt1, const es_format_t * p_fmt2)
This function will check if the first ES format is similar to the second one.
All descriptive fields are ignored.
References es_format_t::audio, AUDIO_ES, audio_format_t::channel_type, es_format_t::i_cat, audio_format_t::i_chan_mode, audio_format_t::i_channels, video_format_t::i_chroma, es_format_t::i_codec, audio_format_t::i_format, audio_format_t::i_physical_channels, es_format_t::i_profile, audio_format_t::i_rate, SPU_ES, es_format_t::video, VIDEO_ES, video_format_IsSimilar(), and vlc_fourcc_GetCodec().
Referenced by DecoderProcess(), and ThreadChangeFilters().
MaskToShift()
static void MaskToShift (int * pi_left, int * pi_right, uint32_t i_mask) static
It transforms a color mask into right and left shifts FIXME copied from video_output.c.
References BinaryLog().
Referenced by video_format_FixRgb().
transform_FromBasicOps()
static video_transform_t transform_FromBasicOps (unsigned angle, bool hflip) static
References TRANSFORM_ANTI_TRANSPOSE, TRANSFORM_HFLIP, TRANSFORM_IDENTITY, TRANSFORM_R180, TRANSFORM_R270, TRANSFORM_R90, TRANSFORM_TRANSPOSE, and TRANSFORM_VFLIP.
Referenced by video_format_GetTransform().
transform_GetBasicOps()
static void transform_GetBasicOps (video_transform_t transform, unsigned *restrict angle, bool *restrict hflip) static
References ORIENT_IS_MIRROR, transform(), TRANSFORM_ANTI_TRANSPOSE, TRANSFORM_HFLIP, TRANSFORM_IDENTITY, TRANSFORM_R180, TRANSFORM_R270, TRANSFORM_R90, TRANSFORM_TRANSPOSE, TRANSFORM_VFLIP, and vlc_assert_unreachable.
Referenced by video_format_GetTransform(), and video_format_TransformBy().
video_format_ApplyRotation()
void video_format_ApplyRotation (video_format_t *restrict out, const video_format_t *restrict in)
References ORIENT_NORMAL, and video_format_TransformTo().
Referenced by ThreadDisplayRenderPicture(), and vout_display_PlacePicture().
video_format_CopyCrop()
void video_format_CopyCrop (video_format_t * p_dst, const video_format_t * p_src)
It will copy the crop properties from a video_format_t to another.
References video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, and video_format_t::i_y_offset.
Referenced by picture_NewFromResource(), VideoFormatCopyCropAr(), vout_snapshot_Set(), and vout_UpdateDisplaySourceProperties().
video_format_FixRgb()
void video_format_FixRgb (video_format_t * p_fmt)
This function will fill all RGB shift from RGB masks.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_lbshift, video_format_t::i_lgshift, video_format_t::i_lrshift, video_format_t::i_rbshift, video_format_t::i_rgshift, video_format_t::i_rmask, video_format_t::i_rrshift, MaskToShift(), VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, and VLC_CODEC_RGB32.
Referenced by BitMapFormatIsSimilar(), ConvertRGB32AndBlend(), video_format_IsSimilar(), and VoutValidateFormat().
video_format_GetTransform()
video_transform_t video_format_GetTransform (video_orientation_t src, video_orientation_t dst)
Returns the operation required to transform src into dst.
References transform_FromBasicOps(), transform_GetBasicOps(), and transform_Inverse().
Referenced by video_format_TransformTo(), and vout_display_SendMouseMovedDisplayCoordinates().
video_format_IsSimilar()
bool video_format_IsSimilar (const video_format_t * f1, const video_format_t * f2)
This function will check if the first video format is similar to the second one.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_height, video_format_t::i_rmask, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, video_format_t::multiview_mode, video_format_t::orientation, video_format_FixRgb(), VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, and VLC_CODEC_RGB32.
Referenced by es_format_IsSimilar(), subpicture_Update(), and ThreadReinit().
video_format_Print()
void video_format_Print (vlc_object_t * p_this, const char * psz_text, const video_format_t * fmt)
It prints details about the given video_format_t.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_height, video_format_t::i_rmask, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, and msg_Dbg.
Referenced by ThreadStart(), and vout_ManageDisplay().
video_format_ScaleCropAr()
void video_format_ScaleCropAr (video_format_t * p_dst, const video_format_t * p_src)
It will compute the crop/ar properties when scaling.
References video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, and vlc_ureduce().
video_format_Setup()
void video_format_Setup (video_format_t * p_fmt, vlc_fourcc_t i_chroma, int i_width, int i_height, int i_visible_width, int i_visible_height, int i_sar_num, int i_sar_den)
It will fill up a video_format_t using the given arguments.
Note that the video_format_t must already be initialized.
References video_format_t::i_bits_per_pixel, video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, VIDEO_ES, VLC_CODEC_ARGB, VLC_CODEC_BGRA, VLC_CODEC_GREY, VLC_CODEC_I410, VLC_CODEC_I411, VLC_CODEC_I420, VLC_CODEC_I422, VLC_CODEC_I440, VLC_CODEC_I444, VLC_CODEC_J420, VLC_CODEC_J422, VLC_CODEC_J440, VLC_CODEC_J444, VLC_CODEC_NV12, VLC_CODEC_P010, VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, VLC_CODEC_RGB32, VLC_CODEC_RGB8, VLC_CODEC_RGBA, VLC_CODEC_RGBP, VLC_CODEC_UYVY, VLC_CODEC_VYUY, VLC_CODEC_XYZ12, VLC_CODEC_Y211, VLC_CODEC_YUV420A, VLC_CODEC_YUV422A, VLC_CODEC_YUVA, VLC_CODEC_YUVP, VLC_CODEC_YUYV, VLC_CODEC_YV12, VLC_CODEC_YV9, VLC_CODEC_YVYU, vlc_fourcc_GetCodec(), and vlc_ureduce().
Referenced by picture_New(), picture_NewFromResource(), and picture_Setup().
video_format_TransformBy()
void video_format_TransformBy (video_format_t * fmt, video_transform_t transform)
This function applies the transform operation to fmt.
References video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, ORIENT_ANTI_TRANSPOSED, ORIENT_HFLIPPED, ORIENT_IS_SWAP, ORIENT_NORMAL, ORIENT_ROTATED_180, ORIENT_ROTATED_270, ORIENT_ROTATED_90, ORIENT_TRANSPOSED, ORIENT_VFLIPPED, video_format_t::orientation, transform(), and transform_GetBasicOps().
Referenced by video_format_TransformTo().
video_format_TransformTo()
void video_format_TransformTo (video_format_t *restrict fmt, video_orientation_t dst_orientation)
References transform(), video_format_GetTransform(), and video_format_TransformBy().
Referenced by video_format_ApplyRotation(), and vout_display_SendMouseMovedDisplayCoordinates().