VLC: src/input/event.c File Reference
event.c File Reference
Functions
static void Trigger (input_thread_t *, int i_type)
static void VarListAdd (input_thread_t *, const char *psz_variable, int i_event, int i_value, const char *psz_text)
static void VarListDel (input_thread_t *, const char *psz_variable, int i_event, int i_value)
static void VarListSelect (input_thread_t *, const char *psz_variable, int i_event, int i_value)
void input_SendEventDead (input_thread_t *p_input)
void input_SendEventPosition (input_thread_t *p_input, double f_position, mtime_t i_time)
void input_SendEventLength (input_thread_t *p_input, mtime_t i_length)
void input_SendEventStatistics (input_thread_t *p_input)
void input_SendEventRate (input_thread_t *p_input, int i_rate)
void input_SendEventAudioDelay (input_thread_t *p_input, mtime_t i_delay)
void input_SendEventSubtitleDelay (input_thread_t *p_input, mtime_t i_delay)
void input_SendEventRecord (input_thread_t *p_input, bool b_recording)
void input_SendEventTitle (input_thread_t *p_input, int i_title)
void input_SendEventSeekpoint (input_thread_t *p_input, int i_title, int i_seekpoint)
void input_SendEventSignal (input_thread_t *p_input, double f_quality, double f_strength)
void input_SendEventState (input_thread_t *p_input, int i_state)
void input_SendEventCache (input_thread_t *p_input, double f_level)
void input_SendEventMeta (input_thread_t *p_input)
void input_SendEventMetaInfo (input_thread_t *p_input)
void input_SendEventMetaEpg (input_thread_t *p_input)
void input_SendEventProgramAdd (input_thread_t *p_input, int i_program, const char *psz_text)
void input_SendEventProgramDel (input_thread_t *p_input, int i_program)
void input_SendEventProgramSelect (input_thread_t *p_input, int i_program)
void input_SendEventProgramScrambled (input_thread_t *p_input, int i_group, bool b_scrambled)
static const char * GetEsVarName (enum es_format_category_e i_cat)
void input_SendEventEsAdd (input_thread_t *p_input, enum es_format_category_e i_cat, int i_id, const char *psz_text)
void input_SendEventEsDel (input_thread_t *p_input, enum es_format_category_e i_cat, int i_id)
void input_SendEventEsSelect (input_thread_t *p_input, enum es_format_category_e i_cat, int i_id)
void input_SendEventTeletextAdd (input_thread_t *p_input, int i_teletext, const char *psz_text)
void input_SendEventTeletextDel (input_thread_t *p_input, int i_teletext)
void input_SendEventTeletextSelect (input_thread_t *p_input, int i_teletext)
void input_SendEventVout (input_thread_t *p_input)
void input_SendEventAout (input_thread_t *p_input)
void input_SendEventBookmark (input_thread_t *p_input)
Function Documentation
GetEsVarName()
static const char * GetEsVarName (enum es_format_category_e i_cat) static
References AUDIO_ES, SPU_ES, and VIDEO_ES.
Referenced by input_SendEventEsAdd(), input_SendEventEsDel(), and input_SendEventEsSelect().
input_SendEventAout()
void input_SendEventAout (input_thread_t * p_input)
References INPUT_EVENT_AOUT, and Trigger().
Referenced by aout_update_format(), and DeleteDecoder().
input_SendEventAudioDelay()
void input_SendEventAudioDelay (input_thread_t * p_input, mtime_t i_delay)
References vlc_value_t::i_int, INPUT_EVENT_AUDIO_DELAY, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control().
input_SendEventBookmark()
void input_SendEventBookmark (input_thread_t * p_input)
References INPUT_EVENT_BOOKMARK, and Trigger().
Referenced by UpdateBookmarksOption().
input_SendEventCache()
void input_SendEventCache (input_thread_t * p_input, double f_level)
References vlc_value_t::f_float, INPUT_EVENT_CACHE, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by EsOutChangePosition(), EsOutDecodersStopBuffering(), and Init().
input_SendEventDead()
void input_SendEventDead (input_thread_t * p_input)
References INPUT_EVENT_DEAD, and Trigger().
Referenced by Preparse(), and Run().
input_SendEventEsAdd()
void input_SendEventEsAdd (input_thread_t * p_input, enum es_format_category_e i_cat, int i_id, const char * psz_text)
References GetEsVarName(), INPUT_EVENT_ES, and VarListAdd().
Referenced by EsOutESVarUpdateGeneric().
input_SendEventEsDel()
void input_SendEventEsDel (input_thread_t * p_input, enum es_format_category_e i_cat, int i_id)
References GetEsVarName(), INPUT_EVENT_ES, and VarListDel().
Referenced by EsOutESVarUpdateGeneric(), and EsOutProgramSelect().
input_SendEventEsSelect()
void input_SendEventEsSelect (input_thread_t * p_input, enum es_format_category_e i_cat, int i_id)
References GetEsVarName(), INPUT_EVENT_ES, and VarListSelect().
Referenced by EsDeleteCCChannels(), EsOutDel(), EsSelect(), and EsUnselect().
input_SendEventLength()
void input_SendEventLength (input_thread_t * p_input, mtime_t i_length)
References vlc_value_t::i_int, INPUT_EVENT_LENGTH, input_item_SetDuration(), input_priv(), Trigger(), var_Change, var_GetInteger, and VLC_VAR_SETVALUE.
Referenced by EsOutControlLocked(), and Init().
input_SendEventMeta()
void input_SendEventMeta (input_thread_t * p_input)
References INPUT_EVENT_ITEM_META, and Trigger().
Referenced by Create(), EsOutMeta(), EsOutProgramEpg(), EsOutProgramMeta(), and EsOutProgramSelect().
input_SendEventMetaEpg()
void input_SendEventMetaEpg (input_thread_t * p_input)
References INPUT_EVENT_ITEM_EPG, and Trigger().
Referenced by EsOutProgramEpg(), and EsOutTerminate().
input_SendEventMetaInfo()
void input_SendEventMetaInfo (input_thread_t * p_input)
References INPUT_EVENT_ITEM_INFO, and Trigger().
Referenced by input_vaControl().
input_SendEventPosition()
void input_SendEventPosition (input_thread_t * p_input, double f_position, mtime_t i_time)
References vlc_value_t::f_float, vlc_value_t::i_int, INPUT_EVENT_POSITION, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by EsOutControlLocked(), and Init().
input_SendEventProgramAdd()
void input_SendEventProgramAdd (input_thread_t * p_input, int i_program, const char * psz_text)
References INPUT_EVENT_PROGRAM, and VarListAdd().
Referenced by EsOutProgramAdd(), and EsOutProgramMeta().
input_SendEventProgramDel()
void input_SendEventProgramDel (input_thread_t * p_input, int i_program)
References INPUT_EVENT_PROGRAM, and VarListDel().
Referenced by EsOutProgramDel(), and EsOutProgramMeta().
input_SendEventProgramScrambled()
void input_SendEventProgramScrambled (input_thread_t * p_input, int i_group, bool b_scrambled)
References INPUT_EVENT_PROGRAM, Trigger(), var_GetInteger, and var_SetBool.
Referenced by EsOutProgramSelect(), and EsOutProgramUpdateScrambled().
input_SendEventProgramSelect()
void input_SendEventProgramSelect (input_thread_t * p_input, int i_program)
References INPUT_EVENT_PROGRAM, and VarListSelect().
Referenced by EsOutProgramMeta(), and EsOutProgramSelect().
input_SendEventRate()
void input_SendEventRate (input_thread_t * p_input, int i_rate)
References vlc_value_t::f_float, INPUT_EVENT_RATE, INPUT_RATE_DEFAULT, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control().
input_SendEventRecord()
void input_SendEventRecord (input_thread_t * p_input, bool b_recording)
References vlc_value_t::b_bool, INPUT_EVENT_RECORD, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control().
input_SendEventSeekpoint()
void input_SendEventSeekpoint (input_thread_t * p_input, int i_title, int i_seekpoint)
References vlc_value_t::i_int, INPUT_EVENT_CHAPTER, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control(), and UpdateTitleSeekpointFromDemux().
input_SendEventSignal()
void input_SendEventSignal (input_thread_t * p_input, double f_quality, double f_strength)
References vlc_value_t::f_float, INPUT_EVENT_SIGNAL, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by UpdateGenericFromDemux().
input_SendEventState()
void input_SendEventState (input_thread_t * p_input, int i_state)
References vlc_value_t::i_int, INPUT_EVENT_STATE, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by input_ChangeState().
input_SendEventStatistics()
void input_SendEventStatistics (input_thread_t * p_input)
References INPUT_EVENT_STATISTICS, and Trigger().
Referenced by MainLoopStatistics().
input_SendEventSubtitleDelay()
void input_SendEventSubtitleDelay (input_thread_t * p_input, mtime_t i_delay)
References vlc_value_t::i_int, INPUT_EVENT_SUBTITLE_DELAY, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control().
input_SendEventTeletextAdd()
void input_SendEventTeletextAdd (input_thread_t * p_input, int i_teletext, const char * psz_text)
References INPUT_EVENT_TELETEXT, and VarListAdd().
Referenced by EsOutESVarUpdateGeneric().
input_SendEventTeletextDel()
void input_SendEventTeletextDel (input_thread_t * p_input, int i_teletext)
References INPUT_EVENT_TELETEXT, and VarListDel().
Referenced by EsOutESVarUpdateGeneric(), and EsOutProgramSelect().
input_SendEventTeletextSelect()
void input_SendEventTeletextSelect (input_thread_t * p_input, int i_teletext)
References INPUT_EVENT_TELETEXT, and VarListSelect().
Referenced by EsSelect(), and EsUnselect().
input_SendEventTitle()
void input_SendEventTitle (input_thread_t * p_input, int i_title)
References vlc_value_t::i_int, input_ControlVarTitle(), INPUT_EVENT_TITLE, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by Control(), InitTitle(), and UpdateTitleSeekpointFromDemux().
input_SendEventVout()
void input_SendEventVout (input_thread_t * p_input)
References INPUT_EVENT_VOUT, and Trigger().
Referenced by aout_request_vout(), DeleteDecoder(), and vout_update_format().
Trigger()
static void Trigger (input_thread_t * p_input, int i_type) static
References i_type, and var_SetInteger.
Referenced by input_SendEventAout(), input_SendEventAudioDelay(), input_SendEventBookmark(), input_SendEventCache(), input_SendEventDead(), input_SendEventLength(), input_SendEventMeta(), input_SendEventMetaEpg(), input_SendEventMetaInfo(), input_SendEventPosition(), input_SendEventProgramScrambled(), input_SendEventRate(), input_SendEventRecord(), input_SendEventSeekpoint(), input_SendEventSignal(), input_SendEventState(), input_SendEventStatistics(), input_SendEventSubtitleDelay(), input_SendEventTitle(), input_SendEventVout(), VarListAdd(), VarListDel(), and VarListSelect().
VarListAdd()
static void VarListAdd (input_thread_t * p_input, const char * psz_variable, int i_event, int i_value, const char * psz_text) static
References vlc_value_t::i_int, i_value, vlc_value_t::psz_string, Trigger(), var_Change, and VLC_VAR_ADDCHOICE.
Referenced by input_SendEventEsAdd(), input_SendEventProgramAdd(), and input_SendEventTeletextAdd().
VarListDel()
static void VarListDel (input_thread_t * p_input, const char * psz_variable, int i_event, int i_value) static
References vlc_value_t::i_int, i_value, Trigger(), var_Change, VLC_VAR_CLEARCHOICES, and VLC_VAR_DELCHOICE.
Referenced by input_SendEventEsDel(), input_SendEventProgramDel(), and input_SendEventTeletextDel().
VarListSelect()
static void VarListSelect (input_thread_t * p_input, const char * psz_variable, int i_event, int i_value) static
References vlc_value_t::i_int, i_value, Trigger(), var_Change, and VLC_VAR_SETVALUE.
Referenced by input_SendEventEsSelect(), input_SendEventProgramSelect(), and input_SendEventTeletextSelect().