VLC: src/misc/exit.c File Reference
exit.c File Reference
Functions
void vlc_ExitInit (vlc_exit_t *exit)
void vlc_ExitDestroy (vlc_exit_t *exit)
void libvlc_SetExitHandler (libvlc_int_t *p_libvlc, void(*handler)(void *), void *opaque)
Registers a callback for the LibVLC exit event.
void libvlc_Quit (libvlc_int_t *p_libvlc)
Posts an exit signal to LibVLC instance.
Function Documentation
libvlc_SetExitHandler()
void libvlc_SetExitHandler (libvlc_int_t * p_libvlc, void(* handler)(void *), void * opaque)
Registers a callback for the LibVLC exit event.
References libvlc_priv_t::exit, vlc_exit::handler, libvlc_priv(), vlc_exit::lock, vlc_exit::opaque, vlc_mutex_lock(), and vlc_mutex_unlock().
vlc_ExitDestroy()
void vlc_ExitDestroy (vlc_exit_t * exit)
References vlc_exit::lock, and vlc_mutex_destroy().
Referenced by libvlc_InternalDestroy().
vlc_ExitInit()
void vlc_ExitInit (vlc_exit_t * exit)
References vlc_exit::handler, vlc_exit::lock, vlc_exit::opaque, and vlc_mutex_init().
Referenced by libvlc_InternalCreate().