VLC: src/playlist/fetcher.h File Reference
fetcher.h File Reference
Typedefs
typedef struct playlist_fetcher_t playlist_fetcher_t
Fetcher opaque structure.
Functions
playlist_fetcher_t * playlist_fetcher_New (vlc_object_t *)
This function creates the fetcher object and thread.
int playlist_fetcher_Push (playlist_fetcher_t *, input_item_t *, input_item_meta_request_option_t, int)
This function enqueues the provided item to be art fetched.
void playlist_fetcher_Delete (playlist_fetcher_t *)
This function destroys the fetcher object and thread.
Typedef Documentation
playlist_fetcher_t
typedef struct playlist_fetcher_t playlist_fetcher_t
Fetcher opaque structure.
The fetcher object will retrieve the art album data for any given input item in an asynchronous way.
Function Documentation
playlist_fetcher_Delete()
void playlist_fetcher_Delete (playlist_fetcher_t * fetcher)
This function destroys the fetcher object and thread.
All pending input items will be released.
References playlist_fetcher_t::album_cache, background_worker_Delete(), playlist_fetcher_t::downloader, FreeCacheEntry(), playlist_fetcher_t::local, playlist_fetcher_t::lock, playlist_fetcher_t::network, vlc_dictionary_clear(), and vlc_mutex_destroy().
Referenced by playlist_preparser_Delete().
playlist_fetcher_New()
playlist_fetcher_t * playlist_fetcher_New (vlc_object_t * owner)
This function creates the fetcher object and thread.
References playlist_fetcher_t::album_cache, background_worker_Delete(), playlist_fetcher_t::downloader, playlist_fetcher_t::local, playlist_fetcher_t::lock, playlist_fetcher_t::network, playlist_fetcher_t::owner, StartDownloader(), StartSearchLocal(), StartSearchNetwork(), unlikely, vlc_dictionary_init(), vlc_mutex_init(), and WorkerInit().
Referenced by playlist_preparser_New().
playlist_fetcher_Push()
int playlist_fetcher_Push (playlist_fetcher_t * fetcher, input_item_t * item, input_item_meta_request_option_t options, int preparse_status)
This function enqueues the provided item to be art fetched.
The input item is retained until the art fetching is done or until the fetcher object is destroyed.
< Not enough memory
< No error
References background_worker_Push(), input_item_Hold(), fetcher_request::item, playlist_fetcher_t::local, fetcher_request::options, fetcher_request::preparse_status, fetcher_request::refs, RequestRelease(), SetPreparsed(), unlikely, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by playlist_preparser_fetcher_Push(), and PreparserCloseInput().