VLC: src/misc/filter_chain.c File Reference
filter_chain.c File Reference
Data Structures
struct chained_filter_t
struct filter_chain_t
Typedefs
typedef struct chained_filter_t chained_filter_t
Functions
static chained_filter_t * chained (filter_t *filter)
static void FilterDeletePictures (picture_t *)
Local prototypes.
static filter_chain_t * filter_chain_NewInner (const filter_owner_t *callbacks, const char *cap, const char *conv_cap, bool fmt_out_change, const filter_owner_t *owner, enum es_format_category_e cat)
filter_chain_t * filter_chain_New (vlc_object_t *obj, const char *cap, enum es_format_category_e cat)
Filter chain initialisation.
static picture_t * filter_chain_VideoBufferNew (filter_t *filter)
Chained filter picture allocator function.
filter_chain_t * filter_chain_NewVideo (vlc_object_t *obj, bool allow_change, const filter_owner_t *restrict owner)
void filter_chain_Delete (filter_chain_t *p_chain)
Filter chain destruction.
void filter_chain_Reset (filter_chain_t *p_chain, const es_format_t *p_fmt_in, const es_format_t *p_fmt_out)
Filter chain reinitialisation.
static filter_t * filter_chain_AppendInner (filter_chain_t *chain, const char *name, const char *capability, config_chain_t *cfg, const es_format_t *fmt_in, const es_format_t *fmt_out)
filter_t * filter_chain_AppendFilter (filter_chain_t *chain, const char *name, config_chain_t *cfg, const es_format_t *fmt_in, const es_format_t *fmt_out)
Append a filter to the chain.
int filter_chain_AppendConverter (filter_chain_t *chain, const es_format_t *fmt_in, const es_format_t *fmt_out)
Append a conversion to the chain.
void filter_chain_DeleteFilter (filter_chain_t *chain, filter_t *filter)
Delete filter from filter chain.
int filter_chain_AppendFromString (filter_chain_t *chain, const char *str)
Append new filter to filter chain from string.
int filter_chain_ForEach (filter_chain_t *chain, int(*cb)(filter_t *, void *), void *opaque)
bool filter_chain_IsEmpty (const filter_chain_t *chain)
Checks if the filter chain is empty.
const es_format_t * filter_chain_GetFmtOut (filter_chain_t *p_chain)
Get last output format of the last element in the filter chain.
static picture_t * FilterChainVideoFilter (chained_filter_t *f, picture_t *p_pic)
picture_t * filter_chain_VideoFilter (filter_chain_t *p_chain, picture_t *p_pic)
Apply the filter chain to a video picture.
void filter_chain_VideoFlush (filter_chain_t *p_chain)
Flush a video filter chain.
void filter_chain_SubSource (filter_chain_t *p_chain, spu_t *spu, mtime_t display_date)
Generate subpictures from a chain of subpicture source "filters".
subpicture_t * filter_chain_SubFilter (filter_chain_t *p_chain, subpicture_t *p_subpic)
Apply filter chain to subpictures.
int filter_chain_MouseFilter (filter_chain_t *p_chain, vlc_mouse_t *p_dst, const vlc_mouse_t *p_src)
int filter_chain_MouseEvent (filter_chain_t *p_chain, const vlc_mouse_t *p_mouse, const video_format_t *p_fmt)
Typedef Documentation
chained_filter_t
typedef struct chained_filter_t chained_filter_t
Function Documentation
chained()
static chained_filter_t * chained (filter_t * filter) inline static
References container_of, and chained_filter_t::filter.
Referenced by filter_chain_AppendInner(), filter_chain_DeleteFilter(), and filter_chain_VideoBufferNew().
filter_chain_AppendInner()
static filter_t * filter_chain_AppendInner (filter_chain_t * chain, const char * name, const char * capability, config_chain_t * cfg, const es_format_t * fmt_in, const es_format_t * fmt_out) static
References filter_chain_t::b_allow_fmt_out_change, filter_t::b_allow_fmt_out_change, filter_chain_t::callbacks, chained(), es_format_Clean(), es_format_Copy(), chained_filter_t::filter, filter_chain_t::first, filter_chain_t::fmt_in, filter_t::fmt_in, filter_chain_t::fmt_out, filter_t::fmt_out, filter_chain_t::last, likely, module_get_name(), module_need, chained_filter_t::mouse, msg_Dbg, msg_Err, name, chained_filter_t::next, filter_t::owner, filter_t::p_cfg, filter_t::p_module, chained_filter_t::pending, chained_filter_t::prev, filter_t::psz_name, filter_owner_t::sys, unlikely, vlc_custom_create, vlc_mouse_Init(), and vlc_object_release.
Referenced by filter_chain_AppendConverter(), and filter_chain_AppendFilter().
filter_chain_MouseEvent()
int filter_chain_MouseEvent (filter_chain_t * p_chain, const vlc_mouse_t * p_mouse, const video_format_t * p_fmt)
< Unspecified error
< No error
References filter_chain_t::first, filter_t::pf_sub_mouse, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by spu_ProcessMouse().
filter_chain_MouseFilter()
int filter_chain_MouseFilter (filter_chain_t * p_chain, vlc_mouse_t * p_dst, const vlc_mouse_t * p_src)
< Unspecified error
< No error
References filter_chain_t::last, filter_t::pf_video_mouse, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by vout_SendDisplayEventMouse().
filter_chain_NewInner()
static filter_chain_t * filter_chain_NewInner (const filter_owner_t * callbacks, const char * cap, const char * conv_cap, bool fmt_out_change, const filter_owner_t * owner, enum es_format_category_e cat) static
References filter_chain_t::b_allow_fmt_out_change, filter_chain_t::callbacks, filter_chain_t::conv_cap, es_format_Init(), filter_chain_t::filter_cap, filter_chain_t::first, filter_chain_t::fmt_in, filter_chain_t::fmt_out, filter_chain_t::last, filter_chain_t::owner, filter_owner_t::sys, and unlikely.
Referenced by filter_chain_New(), and filter_chain_NewVideo().
filter_chain_NewVideo()
filter_chain_t * filter_chain_NewVideo (vlc_object_t * obj, bool allow_change, const filter_owner_t *restrict owner)
References filter_chain_NewInner(), filter_chain_VideoBufferNew(), filter_owner_t::sys, and VIDEO_ES.
filter_chain_VideoBufferNew()
static picture_t * filter_chain_VideoBufferNew (filter_t * filter) static
Chained filter picture allocator function.
References filter_owner_t::buffer_new, chained(), filter_t::fmt_out, msg_Err, filter_chain_t::owner, filter_t::owner, picture_NewFromFormat(), filter_owner_t::sys, es_format_t::video, and filter_owner_t::video.
Referenced by filter_chain_NewVideo().
FilterChainVideoFilter()
static picture_t * FilterChainVideoFilter (chained_filter_t * f, picture_t * p_pic) static
References chained_filter_t::filter, FilterDeletePictures(), msg_Warn, chained_filter_t::next, picture_t::p_next, chained_filter_t::pending, and filter_t::pf_video_filter.
Referenced by filter_chain_VideoFilter().
FilterDeletePictures()
static void FilterDeletePictures (picture_t * picture) static
Local prototypes.
References picture_t::p_next, and picture_Release().
Referenced by filter_chain_DeleteFilter(), filter_chain_VideoFlush(), and FilterChainVideoFilter().