VLC: src/misc/filter.c File Reference
filter.c File Reference
Functions
static int TriggerFilterCallback (vlc_object_t *p_this, char const *psz_var, vlc_value_t oldval, vlc_value_t newval, void *p_data)
void filter_AddProxyCallbacks (vlc_object_t *obj, filter_t *filter, vlc_callback_t restart_cb)
This function duplicates every variables from the filter, and adds a proxy callback to trigger filter events from obj.
void filter_DelProxyCallbacks (vlc_object_t *obj, filter_t *filter, vlc_callback_t restart_cb)
This function removes the callbacks previously added to every duplicated variables, and removes them afterward.
filter_t * filter_NewBlend (vlc_object_t *p_this, const video_format_t *p_dst_chroma)
It creates a blend filter.
int filter_ConfigureBlend (filter_t *p_blend, int i_dst_width, int i_dst_height, const video_format_t *p_src)
It configures blend filter parameters that are allowed to changed after the creation.
int filter_Blend (filter_t *p_blend, picture_t *p_dst, int i_dst_x, int i_dst_y, const picture_t *p_src, int i_alpha)
It blends a picture into another one.
void filter_DeleteBlend (filter_t *p_blend)
It destroys a blend filter created by filter_NewBlend.
video_splitter_t * video_splitter_New (vlc_object_t *p_this, const char *psz_name, const video_format_t *p_fmt)
void video_splitter_Delete (video_splitter_t *p_splitter)
Function Documentation
TriggerFilterCallback()
static int TriggerFilterCallback (vlc_object_t * p_this, char const * psz_var, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
References var_Set.
Referenced by filter_AddProxyCallbacks(), and filter_DelProxyCallbacks().
video_splitter_Delete()
void video_splitter_Delete (video_splitter_t * p_splitter)
References video_splitter_t::fmt, module_unneed, video_splitter_t::p_module, video_format_Clean(), and vlc_object_release.
Referenced by SplitterClose(), video_splitter_New(), and vout_NewSplitter().
video_splitter_New()
video_splitter_t * video_splitter_New (vlc_object_t * p_this, const char * psz_name, const video_format_t * p_fmt)
References video_splitter_t::fmt, module_need, video_splitter_t::p_module, psz_name, video_format_Copy(), video_splitter_Delete(), and vlc_custom_create.
Referenced by vout_NewSplitter().