VLC: src/misc/fourcc.c File Reference
fourcc.c File Reference
Macros
#define VLC_CODEC_YUV_PLANAR_410 VLC_CODEC_I410, VLC_CODEC_YV9
#define VLC_CODEC_YUV_PLANAR_420 VLC_CODEC_I420, VLC_CODEC_YV12, VLC_CODEC_J420
#define VLC_CODEC_YUV_SEMIPLANAR_420 VLC_CODEC_NV12, VLC_CODEC_NV21
#define VLC_CODEC_YUV_PLANAR_420_16 VLC_CODEC_I420_16L, VLC_CODEC_I420_16B, VLC_CODEC_I420_12L, VLC_CODEC_I420_12B, VLC_CODEC_I420_10L, VLC_CODEC_I420_10B, VLC_CODEC_I420_9L, VLC_CODEC_I420_9B
#define VLC_CODEC_YUV_SEMIPLANAR_420_16 VLC_CODEC_P010
#define VLC_CODEC_YUV_PLANAR_422 VLC_CODEC_I422, VLC_CODEC_J422
#define VLC_CODEC_YUV_SEMIPLANAR_422 VLC_CODEC_NV16, VLC_CODEC_NV61
#define VLC_CODEC_YUV_PLANAR_422_16 VLC_CODEC_I422_12L, VLC_CODEC_I422_12B, VLC_CODEC_I422_10L, VLC_CODEC_I422_10B, VLC_CODEC_I422_9L, VLC_CODEC_I422_9B
#define VLC_CODEC_YUV_PLANAR_440 VLC_CODEC_I440, VLC_CODEC_J440
#define VLC_CODEC_YUV_PLANAR_444 VLC_CODEC_I444, VLC_CODEC_J444
#define VLC_CODEC_YUV_SEMIPLANAR_444 VLC_CODEC_NV24, VLC_CODEC_NV42
#define VLC_CODEC_YUV_PLANAR_444_16
#define VLC_CODEC_YUV_PACKED
#define VLC_CODEC_FALLBACK_420
#define VLC_CODEC_FALLBACK_420_16 VLC_CODEC_I420, VLC_CODEC_YV12, VLC_CODEC_J420, VLC_CODEC_FALLBACK_420
#define VLC_CODEC_FALLBACK_422
#define VLC_CODEC_FALLBACK_422_16 VLC_CODEC_I422, VLC_CODEC_J422, VLC_CODEC_FALLBACK_422
#define VLC_CODEC_FALLBACK_444
#define VLC_CODEC_FALLBACK_444_16 VLC_CODEC_I444, VLC_CODEC_J444, VLC_CODEC_FALLBACK_444
#define VLC_CODEC_FALLBACK_PACKED
#define PLANAR(n, w_den, h_den, size, bits)
#define PLANAR_8(n, w_den, h_den) PLANAR(n, w_den, h_den, 1, 8)
#define PLANAR_16(n, w_den, h_den, bits) PLANAR(n, w_den, h_den, 2, bits)
#define SEMIPLANAR(w_den, h_den, size, bits)
#define PACKED_FMT(size, bits)
#define FAKE_FMT()
Functions
static int fourcc_cmp (const void *key, const void *ent)
static vlc_fourcc_t Lookup (vlc_fourcc_t fourcc, const char **restrict dsc, const struct fourcc_mapping *mapv, size_t mapc, const struct fourcc_desc *dscv, size_t dscc)
static vlc_fourcc_t LookupVideo (vlc_fourcc_t fourcc, const char **restrict dsc)
static vlc_fourcc_t LookupAudio (vlc_fourcc_t fourcc, const char **restrict dsc)
static vlc_fourcc_t LookupSpu (vlc_fourcc_t fourcc, const char **restrict dsc)
static vlc_fourcc_t LookupCat (vlc_fourcc_t fourcc, const char **restrict dsc, int cat)
vlc_fourcc_t vlc_fourcc_GetCodec (int cat, vlc_fourcc_t fourcc)
It returns the codec associated to a fourcc within an ES category.
vlc_fourcc_t vlc_fourcc_GetCodecFromString (int i_cat, const char *psz_fourcc)
It returns the codec associated to a fourcc stored in a zero terminated string.
vlc_fourcc_t vlc_fourcc_GetCodecAudio (vlc_fourcc_t i_fourcc, int i_bits)
It converts the given fourcc to an audio codec when possible.
const char * vlc_fourcc_GetDescription (int cat, vlc_fourcc_t fourcc)
It returns the description of the given fourcc or NULL if not found.
static const vlc_fourcc_t * GetFallback (vlc_fourcc_t i_fourcc, const vlc_fourcc_t *pp_fallback[], const vlc_fourcc_t p_list[])
const vlc_fourcc_t * vlc_fourcc_GetYUVFallback (vlc_fourcc_t i_fourcc)
It returns a list (terminated with the value 0) of YUV fourccs in decreasing priority order for the given chroma.
const vlc_fourcc_t * vlc_fourcc_GetRGBFallback (vlc_fourcc_t i_fourcc)
It returns a list (terminated with the value 0) of RGB fourccs in decreasing priority order for the given chroma.
bool vlc_fourcc_AreUVPlanesSwapped (vlc_fourcc_t a, vlc_fourcc_t b)
It returns true if the two fourccs are equivalent if their U&V planes are swapped.
bool vlc_fourcc_IsYUV (vlc_fourcc_t fcc)
It returns true if the given fourcc is YUV and false otherwise.
const vlc_chroma_description_t * vlc_fourcc_GetChromaDescription (vlc_fourcc_t i_fourcc)
It returns a vlc_chroma_description_t describing the requested fourcc or NULL if not found.
Variables
static const vlc_fourcc_t p_I420_fallback []
static const vlc_fourcc_t p_J420_fallback []
static const vlc_fourcc_t p_YV12_fallback []
static const vlc_fourcc_t p_NV12_fallback []
static const vlc_fourcc_t p_I420_9L_fallback []
static const vlc_fourcc_t p_I420_9B_fallback []
static const vlc_fourcc_t p_I420_10L_fallback []
static const vlc_fourcc_t p_I420_10B_fallback []
static const vlc_fourcc_t p_I420_12L_fallback []
static const vlc_fourcc_t p_I420_12B_fallback []
static const vlc_fourcc_t p_I420_16L_fallback []
static const vlc_fourcc_t p_I420_16B_fallback []
static const vlc_fourcc_t p_P010_fallback []
static const vlc_fourcc_t p_I422_fallback []
static const vlc_fourcc_t p_J422_fallback []
static const vlc_fourcc_t p_I422_9L_fallback []
static const vlc_fourcc_t p_I422_9B_fallback []
static const vlc_fourcc_t p_I422_10L_fallback []
static const vlc_fourcc_t p_I422_10B_fallback []
static const vlc_fourcc_t p_I422_12L_fallback []
static const vlc_fourcc_t p_I422_12B_fallback []
static const vlc_fourcc_t p_I444_fallback []
static const vlc_fourcc_t p_J444_fallback []
static const vlc_fourcc_t p_I444_9L_fallback []
static const vlc_fourcc_t p_I444_9B_fallback []
static const vlc_fourcc_t p_I444_10L_fallback []
static const vlc_fourcc_t p_I444_10B_fallback []
static const vlc_fourcc_t p_I444_12L_fallback []
static const vlc_fourcc_t p_I444_12B_fallback []
static const vlc_fourcc_t p_I444_16L_fallback []
static const vlc_fourcc_t p_I444_16B_fallback []
static const vlc_fourcc_t p_CVPX_VIDEO_NV12_fallback []
static const vlc_fourcc_t p_CVPX_VIDEO_UYVY_fallback []
static const vlc_fourcc_t p_CVPX_VIDEO_I420_fallback []
static const vlc_fourcc_t p_CVPX_VIDEO_BGRA_fallback []
static const vlc_fourcc_t p_CVPX_VIDEO_P010_fallback []
static const vlc_fourcc_t p_VAAPI_420_fallback []
static const vlc_fourcc_t p_VAAPI_420_10BPP_fallback []
static const vlc_fourcc_t p_D3D9_OPAQUE_fallback []
static const vlc_fourcc_t p_D3D9_OPAQUE_10B_fallback []
static const vlc_fourcc_t p_D3D11_OPAQUE_fallback []
static const vlc_fourcc_t p_D3D11_OPAQUE_10B_fallback []
static const vlc_fourcc_t p_I440_fallback []
static const vlc_fourcc_t p_YUYV_fallback []
static const vlc_fourcc_t p_YVYU_fallback []
static const vlc_fourcc_t p_UYVY_fallback []
static const vlc_fourcc_t p_VYUY_fallback []
static const vlc_fourcc_t * pp_YUV_fallback []
static const vlc_fourcc_t p_list_YUV []
static const vlc_fourcc_t p_RGB32_fallback []
static const vlc_fourcc_t p_RGB24_fallback []
static const vlc_fourcc_t p_RGB16_fallback []
static const vlc_fourcc_t p_RGB15_fallback []
static const vlc_fourcc_t p_RGB8_fallback []
static const vlc_fourcc_t * pp_RGB_fallback []
struct {
vlc_fourcc_t p_fourcc [4]
vlc_chroma_description_t description
} p_list_chroma_description []
Macro Definition Documentation
FAKE_FMT
#define FAKE_FMT ()
Value:
    { .plane_count = 0, \
      .p = { {.w = {1,1}, .h = {1,1}} }, \
      .pixel_size = 0, \
      .pixel_bits = 0 }
PACKED_FMT
#define PACKED_FMT (size, bits)
Value:
    { .plane_count = 1, \
      .p = { {.w = {1,1}, .h = {1,1}} }, \
      .pixel_size = size, \
      .pixel_bits = bits }
PLANAR
#define PLANAR (n, w_den, h_den, size, bits)
Value:
    { .plane_count = n, \
      .p = { {.w = {1,    1}, .h = {1,    1}}, \
             {.w = {1,w_den}, .h = {1,h_den}}, \
             {.w = {1,w_den}, .h = {1,h_den}}, \
             {.w = {1,    1}, .h = {1,    1}} }, \
      .pixel_size = size, \
      .pixel_bits = bits }
PLANAR_16
#define PLANAR_16 (n, w_den, h_den, bits) PLANAR(n, w_den, h_den, 2, bits)
PLANAR_8
#define PLANAR_8 (n, w_den, h_den) PLANAR(n, w_den, h_den, 1, 8)
SEMIPLANAR
#define SEMIPLANAR (w_den, h_den, size, bits)
Value:
    { .plane_count = 2, \
      .p = { {.w = {1,    1}, .h = {1,    1}}, \
             {.w = {2,w_den}, .h = {1,h_den}} }, \
      .pixel_size = size, \
      .pixel_bits = bits }
VLC_CODEC_FALLBACK_420
#define VLC_CODEC_FALLBACK_420
Value:
    VLC_CODEC_YUV_PLANAR_422, VLC_CODEC_YUV_PACKED, \
    VLC_CODEC_YUV_PLANAR_444, VLC_CODEC_YUV_PLANAR_440, \
    VLC_CODEC_I411, VLC_CODEC_YUV_PLANAR_410, VLC_CODEC_Y211
VLC_CODEC_FALLBACK_420_16
#define VLC_CODEC_FALLBACK_420_16 VLC_CODEC_I420, VLC_CODEC_YV12, VLC_CODEC_J420, VLC_CODEC_FALLBACK_420
VLC_CODEC_FALLBACK_422
#define VLC_CODEC_FALLBACK_422
Value:
    VLC_CODEC_YUV_PACKED, VLC_CODEC_YUV_PLANAR_420, \
    VLC_CODEC_YUV_PLANAR_444, VLC_CODEC_YUV_PLANAR_440, \
    VLC_CODEC_I411, VLC_CODEC_YUV_PLANAR_410, VLC_CODEC_Y211
VLC_CODEC_FALLBACK_422_16
#define VLC_CODEC_FALLBACK_422_16 VLC_CODEC_I422, VLC_CODEC_J422, VLC_CODEC_FALLBACK_422
VLC_CODEC_FALLBACK_444
#define VLC_CODEC_FALLBACK_444
Value:
    VLC_CODEC_YUV_PLANAR_422, VLC_CODEC_YUV_PACKED, \
    VLC_CODEC_YUV_PLANAR_420, VLC_CODEC_YUV_PLANAR_440, \
    VLC_CODEC_I411, VLC_CODEC_YUV_PLANAR_410, VLC_CODEC_Y211
VLC_CODEC_FALLBACK_444_16
#define VLC_CODEC_FALLBACK_444_16 VLC_CODEC_I444, VLC_CODEC_J444, VLC_CODEC_FALLBACK_444
VLC_CODEC_FALLBACK_PACKED
#define VLC_CODEC_FALLBACK_PACKED
Value:
    VLC_CODEC_YUV_PLANAR_422, VLC_CODEC_YUV_PLANAR_420, \
    VLC_CODEC_YUV_PLANAR_444, VLC_CODEC_YUV_PLANAR_440, \
    VLC_CODEC_I411, VLC_CODEC_YUV_PLANAR_410, VLC_CODEC_Y211
VLC_CODEC_YUV_PACKED
#define VLC_CODEC_YUV_PACKED
Value:
    VLC_CODEC_YUYV, VLC_CODEC_YVYU, \
    VLC_CODEC_UYVY, VLC_CODEC_VYUY
VLC_CODEC_YUV_PLANAR_410
#define VLC_CODEC_YUV_PLANAR_410 VLC_CODEC_I410, VLC_CODEC_YV9
VLC_CODEC_YUV_PLANAR_420
#define VLC_CODEC_YUV_PLANAR_420 VLC_CODEC_I420, VLC_CODEC_YV12, VLC_CODEC_J420
VLC_CODEC_YUV_PLANAR_420_16
#define VLC_CODEC_YUV_PLANAR_420_16 VLC_CODEC_I420_16L, VLC_CODEC_I420_16B, VLC_CODEC_I420_12L, VLC_CODEC_I420_12B, VLC_CODEC_I420_10L, VLC_CODEC_I420_10B, VLC_CODEC_I420_9L, VLC_CODEC_I420_9B
VLC_CODEC_YUV_PLANAR_422
#define VLC_CODEC_YUV_PLANAR_422 VLC_CODEC_I422, VLC_CODEC_J422
VLC_CODEC_YUV_PLANAR_422_16
#define VLC_CODEC_YUV_PLANAR_422_16 VLC_CODEC_I422_12L, VLC_CODEC_I422_12B, VLC_CODEC_I422_10L, VLC_CODEC_I422_10B, VLC_CODEC_I422_9L, VLC_CODEC_I422_9B
VLC_CODEC_YUV_PLANAR_440
#define VLC_CODEC_YUV_PLANAR_440 VLC_CODEC_I440, VLC_CODEC_J440
VLC_CODEC_YUV_PLANAR_444
#define VLC_CODEC_YUV_PLANAR_444 VLC_CODEC_I444, VLC_CODEC_J444
VLC_CODEC_YUV_PLANAR_444_16
#define VLC_CODEC_YUV_PLANAR_444_16
Value:
    VLC_CODEC_I444_10L, VLC_CODEC_I444_10B, VLC_CODEC_I444_9L, VLC_CODEC_I444_9B, \
    VLC_CODEC_I444_16L, VLC_CODEC_I444_16B, VLC_CODEC_I444_12L, VLC_CODEC_I444_12B
VLC_CODEC_YUV_SEMIPLANAR_420
#define VLC_CODEC_YUV_SEMIPLANAR_420 VLC_CODEC_NV12, VLC_CODEC_NV21
VLC_CODEC_YUV_SEMIPLANAR_420_16
#define VLC_CODEC_YUV_SEMIPLANAR_420_16 VLC_CODEC_P010
VLC_CODEC_YUV_SEMIPLANAR_422
#define VLC_CODEC_YUV_SEMIPLANAR_422 VLC_CODEC_NV16, VLC_CODEC_NV61
VLC_CODEC_YUV_SEMIPLANAR_444
#define VLC_CODEC_YUV_SEMIPLANAR_444 VLC_CODEC_NV24, VLC_CODEC_NV42
Function Documentation
fourcc_cmp()
static int fourcc_cmp (const void * key, const void * ent) static
Referenced by Lookup().
GetFallback()
static const vlc_fourcc_t * GetFallback (vlc_fourcc_t i_fourcc, const vlc_fourcc_t * pp_fallback[], const vlc_fourcc_t p_list[]) static
References i_fourcc.
Referenced by vlc_fourcc_GetRGBFallback(), and vlc_fourcc_GetYUVFallback().
Lookup()
static vlc_fourcc_t Lookup (vlc_fourcc_t fourcc, const char **restrict dsc, const struct fourcc_mapping * mapv, size_t mapc, const struct fourcc_desc * dscv, size_t dscc) static
References fourcc_cmp().
Referenced by LookupAudio(), LookupSpu(), and LookupVideo().
LookupAudio()
static vlc_fourcc_t LookupAudio (vlc_fourcc_t fourcc, const char **restrict dsc) static
References Lookup().
Referenced by LookupCat().
LookupCat()
static vlc_fourcc_t LookupCat (vlc_fourcc_t fourcc, const char **restrict dsc, int cat) static
References AUDIO_ES, LookupAudio(), LookupSpu(), LookupVideo(), SPU_ES, and VIDEO_ES.
Referenced by vlc_fourcc_GetCodec(), and vlc_fourcc_GetDescription().
LookupSpu()
static vlc_fourcc_t LookupSpu (vlc_fourcc_t fourcc, const char **restrict dsc) static
References Lookup().
Referenced by LookupCat().
LookupVideo()
static vlc_fourcc_t LookupVideo (vlc_fourcc_t fourcc, const char **restrict dsc) static
References Lookup().
Referenced by LookupCat().
vlc_fourcc_AreUVPlanesSwapped()
bool vlc_fourcc_AreUVPlanesSwapped (vlc_fourcc_t a, vlc_fourcc_t b)
It returns true if the two fourccs are equivalent if their U&V planes are swapped.
References VLC_CODEC_I410, VLC_CODEC_I420, VLC_CODEC_J420, VLC_CODEC_YV12, and VLC_CODEC_YV9.
vlc_fourcc_GetChromaDescription()
const vlc_chroma_description_t * vlc_fourcc_GetChromaDescription (vlc_fourcc_t i_fourcc)
It returns a vlc_chroma_description_t describing the requested fourcc or NULL if not found.
References i_fourcc, p_fourcc, and p_list_chroma_description.
Referenced by picture_Setup(), and vout_update_format().
vlc_fourcc_GetCodec()
vlc_fourcc_t vlc_fourcc_GetCodec (int i_cat, vlc_fourcc_t i_fourcc)
It returns the codec associated to a fourcc within an ES category.
If not found, it will return the given fourcc. If found, it will always be one of the VLC_CODEC_ defined above.
You may use UNKNOWN_ES for the ES category if you don't have the information.
References LookupCat().
Referenced by aout_BitsPerSample(), es_format_IsSimilar(), EsOutAddSlave(), video_format_Setup(), vlc_fourcc_GetCodecAudio(), vlc_fourcc_GetCodecFromString(), and VoutValidateFormat().
vlc_fourcc_GetCodecAudio()
vlc_fourcc_t vlc_fourcc_GetCodecAudio (vlc_fourcc_t i_fourcc, int i_bits)
It converts the given fourcc to an audio codec when possible.
The fourccs converted are aflt, araw/pcm , twos, sowt. When an incompatible i_bits is detected, 0 is returned. The other fourccs go through vlc_fourcc_GetCodec and i_bits is not checked.
References AUDIO_ES, i_fourcc, VLC_CODEC_FL32, VLC_CODEC_FL64, VLC_CODEC_S16B, VLC_CODEC_S16L, VLC_CODEC_S24B, VLC_CODEC_S24L, VLC_CODEC_S32B, VLC_CODEC_S32L, VLC_CODEC_S8, VLC_CODEC_U8, VLC_FOURCC, and vlc_fourcc_GetCodec().
Referenced by EsOutAddSlave().
vlc_fourcc_GetCodecFromString()
vlc_fourcc_t vlc_fourcc_GetCodecFromString (int i_cat, const char * psz_fourcc)
It returns the codec associated to a fourcc stored in a zero terminated string.
If the string is NULL or does not have exactly 4 characters, it will return 0, otherwise it behaves like vlc_fourcc_GetCodec.
Provided for convenience.
References VLC_FOURCC, and vlc_fourcc_GetCodec().
vlc_fourcc_GetDescription()
const char * vlc_fourcc_GetDescription (int i_cat, vlc_fourcc_t i_fourcc)
It returns the description of the given fourcc or NULL if not found.
You may use UNKNOWN_ES for the ES category if you don't have the information.
References LookupCat().
Referenced by DecoderUnsupportedCodec(), and EsOutUpdateInfo().
vlc_fourcc_GetRGBFallback()
const vlc_fourcc_t * vlc_fourcc_GetRGBFallback (vlc_fourcc_t i_fourcc)
It returns a list (terminated with the value 0) of RGB fourccs in decreasing priority order for the given chroma.
It will always return a non NULL pointer that must not be freed.
References GetFallback(), i_fourcc, p_RGB32_fallback, and pp_RGB_fallback.
vlc_fourcc_GetYUVFallback()
const vlc_fourcc_t * vlc_fourcc_GetYUVFallback (vlc_fourcc_t i_fourcc)
It returns a list (terminated with the value 0) of YUV fourccs in decreasing priority order for the given chroma.
It will always return a non NULL pointer that must not be freed.
References GetFallback(), i_fourcc, p_list_YUV, and pp_YUV_fallback.
vlc_fourcc_IsYUV()
bool vlc_fourcc_IsYUV (vlc_fourcc_t fcc)
It returns true if the given fourcc is YUV and false otherwise.
References p_list_YUV.
Referenced by spu_Render(), and vout_update_format().
Variable Documentation
description
vlc_chroma_description_t description
p_CVPX_VIDEO_BGRA_fallback
const vlc_fourcc_t p_CVPX_VIDEO_BGRA_fallback[] static
Initial value:
= {
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'B') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'R') << 16 ) | ( ((uint32_t)'A') << 24 ) ) , 0,
}
p_CVPX_VIDEO_I420_fallback
const vlc_fourcc_t p_CVPX_VIDEO_I420_fallback[] static
Initial value:
= {
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'I') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , 0,
}
p_CVPX_VIDEO_NV12_fallback
const vlc_fourcc_t p_CVPX_VIDEO_NV12_fallback[] static
Initial value:
= {
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'N') << 24 ) ) , ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , 0,
}
p_CVPX_VIDEO_P010_fallback
const vlc_fourcc_t p_CVPX_VIDEO_P010_fallback[] static
Initial value:
= {
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'P') << 24 ) ) , ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , 0
}
p_CVPX_VIDEO_UYVY_fallback
const vlc_fourcc_t p_CVPX_VIDEO_UYVY_fallback[] static
Initial value:
= {
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , 0,
}
p_D3D11_OPAQUE_10B_fallback
const vlc_fourcc_t p_D3D11_OPAQUE_10B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , 0,
}
p_D3D11_OPAQUE_fallback
const vlc_fourcc_t p_D3D11_OPAQUE_fallback[] static
Initial value:
= {
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , 0,
}
p_D3D9_OPAQUE_10B_fallback
const vlc_fourcc_t p_D3D9_OPAQUE_10B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , 0,
}
p_D3D9_OPAQUE_fallback
const vlc_fourcc_t p_D3D9_OPAQUE_fallback[] static
Initial value:
= {
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , 0,
}
p_fourcc
vlc_fourcc_t p_fourcc[4]
Referenced by vlc_fourcc_GetChromaDescription().
p_I420_10B_fallback
const vlc_fourcc_t p_I420_10B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_10L_fallback
const vlc_fourcc_t p_I420_10L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_12B_fallback
const vlc_fourcc_t p_I420_12B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_12L_fallback
const vlc_fourcc_t p_I420_12L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_16B_fallback
const vlc_fourcc_t p_I420_16B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_16L_fallback
const vlc_fourcc_t p_I420_16L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_9B_fallback
const vlc_fourcc_t p_I420_9B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_9L_fallback
const vlc_fourcc_t p_I420_9L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I420_fallback
const vlc_fourcc_t p_I420_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_10B_fallback
const vlc_fourcc_t p_I422_10B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_10L_fallback
const vlc_fourcc_t p_I422_10L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_12B_fallback
const vlc_fourcc_t p_I422_12B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_12L_fallback
const vlc_fourcc_t p_I422_12L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_9B_fallback
const vlc_fourcc_t p_I422_9B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_9L_fallback
const vlc_fourcc_t p_I422_9L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I422_fallback
const vlc_fourcc_t p_I422_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I440_fallback
const vlc_fourcc_t p_I440_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_10B_fallback
const vlc_fourcc_t p_I444_10B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_10L_fallback
const vlc_fourcc_t p_I444_10L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_12B_fallback
const vlc_fourcc_t p_I444_12B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_12L_fallback
const vlc_fourcc_t p_I444_12L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_16B_fallback
const vlc_fourcc_t p_I444_16B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_16L_fallback
const vlc_fourcc_t p_I444_16L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_9B_fallback
const vlc_fourcc_t p_I444_9B_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_9L_fallback
const vlc_fourcc_t p_I444_9L_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_I444_fallback
const vlc_fourcc_t p_I444_fallback[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_J420_fallback
const vlc_fourcc_t p_J420_fallback[] static
Initial value:
= {
    ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_J422_fallback
const vlc_fourcc_t p_J422_fallback[] static
Initial value:
= {
    ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_J444_fallback
const vlc_fourcc_t p_J444_fallback[] static
Initial value:
= {
    ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
[struct]
const struct { ... } p_list_chroma_description[]
Referenced by vlc_fourcc_GetChromaDescription().
p_list_YUV
const vlc_fourcc_t p_list_YUV[] static
Initial value:
= {
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'1') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) , ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'6') << 16 ) | ( ((uint32_t)'1') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) ,
    ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'9') << 16 ) | ( ((uint32_t)'B') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'F') << 16 ) | ( ((uint32_t)'B') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'C') << 16 ) | ( ((uint32_t)'B') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'D') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'D') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'D') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'N') << 24 ) ) ,
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'I') << 24 ) ) ,
    ( ((uint32_t)'C') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'P') << 16 ) | ( ((uint32_t)'P') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'A') << 8 )   | ( ((uint32_t)'O') << 16 ) | ( ((uint32_t)'P') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'A') << 8 )   | ( ((uint32_t)'O') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'9') << 24 ) ) ,
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) ,
    ( ((uint32_t)'D') | ( ((uint32_t)'X') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,
    0,
}
Referenced by vlc_fourcc_GetYUVFallback(), and vlc_fourcc_IsYUV().
p_NV12_fallback
const vlc_fourcc_t p_NV12_fallback[] static
Initial value:
= {
    ( ((uint32_t)'N') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_P010_fallback
const vlc_fourcc_t p_P010_fallback[] static
Initial value:
= {
    ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_RGB15_fallback
const vlc_fourcc_t p_RGB15_fallback[] static
Initial value:
= {
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'5') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'3') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'B') << 16 ) | ( ((uint32_t)'8') << 24 ) ) ,
    0,
}
p_RGB16_fallback
const vlc_fourcc_t p_RGB16_fallback[] static
Initial value:
= {
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'3') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'5') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'B') << 16 ) | ( ((uint32_t)'8') << 24 ) ) ,
    0,
}
p_RGB24_fallback
const vlc_fourcc_t p_RGB24_fallback[] static
Initial value:
= {
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'3') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'5') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'B') << 16 ) | ( ((uint32_t)'8') << 24 ) ) ,
    0,
}
p_RGB32_fallback
const vlc_fourcc_t p_RGB32_fallback[] static
Initial value:
= {
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'3') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'5') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'B') << 16 ) | ( ((uint32_t)'8') << 24 ) ) ,
    0,
}
Referenced by vlc_fourcc_GetRGBFallback().
p_RGB8_fallback
const vlc_fourcc_t p_RGB8_fallback[] static
Initial value:
= {
    ( ((uint32_t)'R') | ( ((uint32_t)'G') << 8 )   | ( ((uint32_t)'B') << 16 ) | ( ((uint32_t)'8') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'5') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'6') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'4') << 24 ) ) ,
    ( ((uint32_t)'R') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'3') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    0,
}
p_UYVY_fallback
const vlc_fourcc_t p_UYVY_fallback[] static
Initial value:
= {
    ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_VAAPI_420_10BPP_fallback
const vlc_fourcc_t p_VAAPI_420_10BPP_fallback[] static
Initial value:
= {
    ( ((uint32_t)'V') | ( ((uint32_t)'A') << 8 )   | ( ((uint32_t)'O') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'P') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'0') << 8 )   | ( ((uint32_t)'A') << 16 ) | ( ((uint32_t)'L') << 24 ) ) , 0,
}
p_VAAPI_420_fallback
const vlc_fourcc_t p_VAAPI_420_fallback[] static
Initial value:
= {
    ( ((uint32_t)'V') | ( ((uint32_t)'A') << 8 )   | ( ((uint32_t)'O') << 16 ) | ( ((uint32_t)'P') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , 0,
}
p_VYUY_fallback
const vlc_fourcc_t p_VYUY_fallback[] static
Initial value:
= {
    ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_YUYV_fallback
const vlc_fourcc_t p_YUYV_fallback[] static
Initial value:
= {
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,
    ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_YV12_fallback
const vlc_fourcc_t p_YV12_fallback[] static
Initial value:
= {
    ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,   ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) , ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
p_YVYU_fallback
const vlc_fourcc_t p_YVYU_fallback[] static
Initial value:
= {
    ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'U') << 24 ) ) ,
    ( ((uint32_t)'Y') | ( ((uint32_t)'U') << 8 )   | ( ((uint32_t)'Y') << 16 ) | ( ((uint32_t)'2') << 24 ) ) ,
    ( ((uint32_t)'U') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'V') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'V') | ( ((uint32_t)'Y') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'Y') << 24 ) ) ,
    ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'2') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'2') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'4') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'J') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'4') << 16 ) | ( ((uint32_t)'0') << 24 ) ) ,   ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , ( ((uint32_t)'I') | ( ((uint32_t)'4') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'0') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'V') << 8 )   | ( ((uint32_t)'U') << 16 ) | ( ((uint32_t)'9') << 24 ) ) , ( ((uint32_t)'Y') | ( ((uint32_t)'2') << 8 )   | ( ((uint32_t)'1') << 16 ) | ( ((uint32_t)'1') << 24 ) ) , 0
}
pp_RGB_fallback
const vlc_fourcc_t* pp_RGB_fallback[] static
Initial value:
= {
    p_RGB32_fallback,
    p_RGB24_fallback,
    p_RGB16_fallback,
    p_RGB15_fallback,
    p_RGB8_fallback,
    p_CVPX_VIDEO_BGRA_fallback,
    NULL,
}
Referenced by vlc_fourcc_GetRGBFallback().
pp_YUV_fallback
const vlc_fourcc_t* pp_YUV_fallback[] static
Referenced by vlc_fourcc_GetYUVFallback().