VLC: src/config/getopt.c File Reference
getopt.c File Reference
Macros
#define NONOPTION_P (argv[state->ind][0] != '-' || argv[state->ind][1] == '\0')
Functions
static void exchange (char **argv, vlc_getopt_t *restrict state)
int vlc_getopt_long (int argc, char *const *argv, const char *optstring, const struct vlc_option *restrict longopts, int *longind, vlc_getopt_t *restrict state)
Macro Definition Documentation
NONOPTION_P
#define NONOPTION_P (argv[state->ind][0] != '-' || argv[state->ind][1] == '\0')
Referenced by vlc_getopt_long().
Function Documentation
exchange()
static void exchange (char ** argv, vlc_getopt_t *restrict state) static
Referenced by vlc_getopt_long().
vlc_getopt_long()
int vlc_getopt_long (int argc, char *const * argv, const char * optstring, const struct vlc_option *restrict longopts, int * longind, vlc_getopt_t *restrict state)
References exchange(), vlc_option::flag, vlc_option::has_arg, NONOPTION_P, p, and vlc_option::val.
Referenced by config_LoadCmdLine().