VLC: Access output
Access output
Output » Stream output
Raw output byte streams
Data Structures
struct sout_access_out_t
Stream output access_output.
Macros
#define sout_AccessOutNew(obj, access, name) sout_AccessOutNew(VLC_OBJECT(obj), access, name)
Enumerations
enum access_out_query_e { ACCESS_OUT_CONTROLS_PACE , ACCESS_OUT_CAN_SEEK }
Functions
sout_access_out_t * sout_AccessOutNew (vlc_object_t *, const char *psz_access, const char *psz_name)
void sout_AccessOutDelete (sout_access_out_t *)
int sout_AccessOutSeek (sout_access_out_t *, off_t)
ssize_t sout_AccessOutRead (sout_access_out_t *, block_t *)
ssize_t sout_AccessOutWrite (sout_access_out_t *, block_t *)
int sout_AccessOutControl (sout_access_out_t *, int,...)
sout_AccessOutControl
static bool sout_AccessOutCanControlPace (sout_access_out_t *p_ao)
Detailed Description
Raw output byte streams
Macro Definition Documentation
sout_AccessOutNew
#define sout_AccessOutNew (obj, access, name) sout_AccessOutNew(VLC_OBJECT(obj), access, name)
Enumeration Type Documentation
access_out_query_e
enum access_out_query_e
Enumerator
ACCESS_OUT_CONTROLS_PACE
ACCESS_OUT_CAN_SEEK
Function Documentation
sout_AccessOutCanControlPace()
static bool sout_AccessOutCanControlPace (sout_access_out_t * p_ao) inline static
References ACCESS_OUT_CONTROLS_PACE, and sout_AccessOutControl().
sout_AccessOutControl()
int sout_AccessOutControl (sout_access_out_t * out, int query, ...)
sout_AccessOutControl
< Unspecified error
References sout_access_out_t::pf_control, vlc_assert_unreachable, VLC_EGENERIC, and VLC_UNUSED.
Referenced by sout_AccessOutCanControlPace().
sout_AccessOutDelete()
void sout_AccessOutDelete (sout_access_out_t * out)
References config_ChainDestroy(), module_unneed, sout_access_out_t::p_cfg, sout_access_out_t::p_module, sout_access_out_t::psz_access, sout_access_out_t::psz_path, vlc_assert_unreachable, vlc_object_release, and VLC_UNUSED.
sout_AccessOutNew()
sout_access_out_t * sout_AccessOutNew (vlc_object_t * obj, const char * psz_access, const char * psz_name)
References config_ChainCreate(), module_need, msg_Err, name, sout_access_out_t::p_cfg, sout_access_out_t::p_module, sout_access_out_t::p_sys, sout_access_out_t::pf_control, sout_access_out_t::pf_read, sout_access_out_t::pf_seek, sout_access_out_t::pf_write, sout_access_out_t::psz_access, psz_name, sout_access_out_t::psz_path, strdup(), vlc_custom_create, vlc_object_release, and VLC_UNUSED.
sout_AccessOutRead()
ssize_t sout_AccessOutRead (sout_access_out_t * out, block_t * block)
< Unspecified error
References sout_access_out_t::pf_read, vlc_assert_unreachable, VLC_EGENERIC, and VLC_UNUSED.
sout_AccessOutSeek()
int sout_AccessOutSeek (sout_access_out_t * out, off_t offset)
< Unspecified error
References sout_access_out_t::pf_seek, vlc_assert_unreachable, VLC_EGENERIC, and VLC_UNUSED.
sout_AccessOutWrite()
ssize_t sout_AccessOutWrite (sout_access_out_t * out, block_t * block)
References sout_access_out_t::pf_write, vlc_assert_unreachable, and VLC_UNUSED.