VLC: VLC extension dialog functions
VLC extension dialog functions
Interface » VLC dialog
Macros
#define vlc_ext_dialog_update(a, b) vlc_ext_dialog_update(VLC_OBJECT(a), b)
#define vlc_dialog_provider_set_ext_callback(a, b, c) vlc_dialog_provider_set_ext_callback(VLC_OBJECT(a), b, c)
Typedefs
typedef void(* vlc_dialog_ext_update_cb) (extension_dialog_t *p_ext_dialog, void *p_data)
Dialog extension callback to be implemented.
Functions
int vlc_ext_dialog_update (vlc_object_t *p_obj, extension_dialog_t *dialog)
void vlc_dialog_provider_set_ext_callback (vlc_object_t *p_obj, vlc_dialog_ext_update_cb pf_update, void *p_data)
Register a callback for VLC extension dialog.
Detailed Description
Macro Definition Documentation
vlc_dialog_provider_set_ext_callback
#define vlc_dialog_provider_set_ext_callback (a, b, c) vlc_dialog_provider_set_ext_callback(VLC_OBJECT(a), b, c)
vlc_ext_dialog_update
#define vlc_ext_dialog_update (a, b) vlc_ext_dialog_update(VLC_OBJECT(a), b)
Typedef Documentation
vlc_dialog_ext_update_cb
typedef void(* vlc_dialog_ext_update_cb) (extension_dialog_t *p_ext_dialog, void *p_data)
Dialog extension callback to be implemented.
Function Documentation
vlc_dialog_provider_set_ext_callback()
void vlc_dialog_provider_set_ext_callback (vlc_object_t * p_obj, vlc_dialog_ext_update_cb pf_update, void * p_data)
Register a callback for VLC extension dialog.
Parameters
pf_update a pointer to the update callback, or NULL to unregister callback
p_data opaque pointer for the callback
References get_dialog_provider(), vlc_dialog_provider::lock, vlc_dialog_provider::p_ext_data, vlc_dialog_provider::pf_ext_update, vlc_mutex_lock(), and vlc_mutex_unlock().
vlc_ext_dialog_update()
int vlc_ext_dialog_update (vlc_object_t * p_obj, extension_dialog_t * dialog)
< Unspecified error
< No error
References get_dialog_provider(), vlc_dialog_provider::lock, vlc_dialog_provider::p_ext_data, vlc_dialog_provider::pf_ext_update, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.