VLC: HTTP/2 output
HTTP/2 output
HTTP » Connection manager » Connections » HTTP/2.0
Functions
int vlc_h2_output_send_prio (struct vlc_h2_output *, struct vlc_h2_frame *)
int vlc_h2_output_send (struct vlc_h2_output *, struct vlc_h2_frame *)
struct vlc_h2_output * vlc_h2_output_create (struct vlc_tls *, bool client)
void vlc_h2_output_destroy (struct vlc_h2_output *)
Detailed Description
Function Documentation
vlc_h2_output_create()
struct vlc_h2_output * vlc_h2_output_create (struct vlc_tls * tls, bool client)
References vlc_h2_output::closing, vlc_h2_output::failed, vlc_h2_queue::first, vlc_h2_queue::last, vlc_h2_output::lock, vlc_h2_output::prio, vlc_h2_output::queue, vlc_h2_output::size, vlc_h2_output::thread, vlc_h2_output::tls, unlikely, vlc_clone(), vlc_cond_destroy(), vlc_cond_init(), vlc_h2_client_output_thread(), vlc_h2_output_thread(), vlc_mutex_destroy(), vlc_mutex_init(), VLC_THREAD_PRIORITY_INPUT, and vlc_h2_output::wait.
Referenced by vlc_h2_conn_create().
vlc_h2_output_destroy()
void vlc_h2_output_destroy (struct vlc_h2_output * out)
References vlc_h2_output::closing, vlc_h2_output::lock, vlc_h2_output::thread, vlc_cancel(), vlc_cond_destroy(), vlc_cond_signal(), vlc_h2_output_flush_unlocked(), vlc_join(), vlc_mutex_destroy(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_h2_output::wait.
Referenced by vlc_h2_conn_create(), and vlc_h2_conn_destroy().
vlc_h2_output_send()
int vlc_h2_output_send (struct vlc_h2_output * out, struct vlc_h2_frame * f)
References vlc_h2_output::queue, and vlc_h2_output_queue().
Referenced by vlc_h2_conn_queue().
vlc_h2_output_send_prio()
int vlc_h2_output_send_prio (struct vlc_h2_output * out, struct vlc_h2_frame * f)
References vlc_h2_output::prio, and vlc_h2_output_queue().
Referenced by vlc_h2_conn_queue_prio().