VLC: Networking
Networking
Operating system
Topics
Internet sockets
Transport layer sockets
Network stream abstraction
Files
file vlc_network.h
Definitions for sockets and low-level networking.
Macros
#define NI_MAXNUMERICHOST 64
#define AI_NUMERICSERV 0
#define AI_IDN 0 /* GNU/libc extension */
Functions
int vlc_getnameinfo (const struct sockaddr *, int, char *, int, int *, int)
int vlc_getaddrinfo (const char *, unsigned, const struct addrinfo *, struct addrinfo **)
Resolves a host name to a list of socket addresses (like getaddrinfo()).
int vlc_getaddrinfo_i11e (const char *, unsigned, const struct addrinfo *, struct addrinfo **)
static bool net_SockAddrIsMulticast (const struct sockaddr *addr, socklen_t len)
static int net_GetSockAddress (int fd, char *address, int *port)
static int net_GetPeerAddress (int fd, char *address, int *port)
static uint16_t net_GetPort (const struct sockaddr *addr)
static void net_SetPort (struct sockaddr *addr, uint16_t port)
char * vlc_getProxyUrl (const char *)
Determines the network proxy server to use (if any).
Detailed Description
Macro Definition Documentation
AI_IDN
#define AI_IDN 0 /* GNU/libc extension */
Referenced by net_Connect(), net_ConnectDgram(), net_Listen(), net_ListenSingle(), net_OpenDgram(), and SocksHandshakeTCP().
AI_NUMERICSERV
#define AI_NUMERICSERV 0
Referenced by net_Connect(), net_ConnectDgram(), net_Listen(), net_ListenSingle(), and net_OpenDgram().
NI_MAXNUMERICHOST
#define NI_MAXNUMERICHOST 64
Referenced by httpd_HandlerCallBack(), net_GetPeerAddress(), net_GetSockAddress(), and sout_AnnounceRegisterSDP().
Function Documentation
net_GetPeerAddress()
static int net_GetPeerAddress (int fd, char * address, int * port) inline static
< Unspecified error
References NI_MAXNUMERICHOST, VLC_EGENERIC, and vlc_getnameinfo().
Referenced by httpd_ClientIP().
net_GetPort()
static uint16_t net_GetPort (const struct sockaddr * addr) inline static
net_GetSockAddress()
static int net_GetSockAddress (int fd, char * address, int * port) inline static
< Unspecified error
References NI_MAXNUMERICHOST, VLC_EGENERIC, and vlc_getnameinfo().
Referenced by httpd_ServerIP().
net_SetPort()
static void net_SetPort (struct sockaddr * addr, uint16_t port) inline static
net_SockAddrIsMulticast()
static bool net_SockAddrIsMulticast (const struct sockaddr * addr, socklen_t len) inline static
Referenced by AddressToSDP(), net_Listen(), net_ListenSingle(), net_OpenDgram(), and net_SetupDgramSocket().
vlc_getaddrinfo()
int vlc_getaddrinfo (const char * node, unsigned port, const struct addrinfo * hints, struct addrinfo ** res)
Resolves a host name to a list of socket addresses (like getaddrinfo()).
Parameters
node host name to resolve (encoded as UTF-8), or NULL
i_port port number for the socket addresses
p_hints parameters (see getaddrinfo() manual page)
res pointer set to the resulting chained list.
Returns
0 on success, a getaddrinfo() error otherwise. On failure, *res is undefined. On success, it must be freed with freeaddrinfo().
References getaddrinfo().
Referenced by net_ConnectDgram(), net_Listen(), net_ListenSingle(), net_OpenDgram(), and sout_AnnounceRegisterSDP().
vlc_getaddrinfo_i11e()
int vlc_getaddrinfo_i11e (const char * name, unsigned port, const struct addrinfo * hints, struct addrinfo ** res)
References vlc_gai_req::done, vlc_gai_req::error, vlc_gai_req::hints, name, vlc_gai_req::name, vlc_gai_req::result, vlc_gai_req::service, vlc_cancel(), vlc_clone(), vlc_gai_thread(), vlc_getaddrinfo_notify(), vlc_join(), vlc_sem_destroy(), vlc_sem_init(), vlc_sem_wait(), vlc_sem_wait_i11e(), and VLC_THREAD_PRIORITY_LOW.
Referenced by net_Connect(), SocksHandshakeTCP(), vlc_h1_request(), vlc_tls_SocketOpenTCP(), and vlc_tls_SocketOpenTLS().
vlc_getnameinfo()
int vlc_getnameinfo (const struct sockaddr * sa, int salen, char * host, int hostlen, int * portnum, int flags)
References getnameinfo().
Referenced by AddressToSDP(), net_GetPeerAddress(), net_GetSockAddress(), and sout_AnnounceRegisterSDP().
vlc_getProxyUrl()
char * vlc_getProxyUrl (const char * url)
Determines the network proxy server to use (if any).
This function fetch the Android proxy using the System.getProperty() method with "http.proxyHost" and "http.proxyPort" keys. This is working only for Android 4.0 and after.
Parameters
url absolute URL for which to get the proxy server (unused)
Returns
proxy URL, NULL if no proxy or error
Parameters
url absolute URL for which to get the proxy server (not used)
Returns
proxy URL, NULL if no proxy or error
Parameters
url absolute URL for which to get the proxy server
Returns
proxy URL, NULL if no proxy or error
References asprintf(), config_GetPsz, environ, fields, get_env(), getenv(), vlc_url_t::psz_password, release_env(), strdup(), vlc_close(), vlc_pipe(), VLC_UNUSED, vlc_uri_compose(), vlc_UrlClean(), and vlc_UrlParse().
Referenced by vlc_http_proxy_find().