VLC: Connection manager
Connection manager
HTTP
HTTP connection management
Topics
Connections
HTTP connections
Streams
Files
file connmgr.h
Functions
struct vlc_http_msg * vlc_http_mgr_request (struct vlc_http_mgr *mgr, bool https, const char *host, unsigned port, const struct vlc_http_msg *req)
Sends an HTTP request.
struct vlc_http_cookie_jar_t * vlc_http_mgr_get_jar (struct vlc_http_mgr *)
struct vlc_http_mgr * vlc_http_mgr_create (vlc_object_t *obj, struct vlc_http_cookie_jar_t *jar)
Creates an HTTP connection manager.
void vlc_http_mgr_destroy (struct vlc_http_mgr *mgr)
Destroys an HTTP connection manager.
Detailed Description
HTTP connection management
Function Documentation
vlc_http_mgr_create()
struct vlc_http_mgr * vlc_http_mgr_create (vlc_object_t * obj, struct vlc_http_cookie_jar_t * jar)
Creates an HTTP connection manager.
Allocates an HTTP client connections manager.
Parameters
obj parent VLC object
jar HTTP cookies jar (NULL to disable cookies)
References vlc_http_mgr::conn, vlc_http_mgr::creds, vlc_http_mgr::jar, vlc_http_mgr::obj, and unlikely.
Referenced by Open().
vlc_http_mgr_destroy()
void vlc_http_mgr_destroy (struct vlc_http_mgr * mgr)
Destroys an HTTP connection manager.
Deallocates an HTTP client connections manager created by vlc_http_msg_destroy(). Any remaining connection is closed and destroyed.
References vlc_http_mgr::conn, vlc_http_mgr::creds, vlc_http_mgr_release(), and vlc_tls_Delete().
Referenced by Close(), and Open().
vlc_http_mgr_get_jar()
struct vlc_http_cookie_jar_t * vlc_http_mgr_get_jar (struct vlc_http_mgr * mgr)
References vlc_http_mgr::jar.
Referenced by vlc_http_res_open(), and vlc_http_res_req().
vlc_http_mgr_request()
struct vlc_http_msg * vlc_http_mgr_request (struct vlc_http_mgr * mgr, bool https, const char * host, unsigned port, const struct vlc_http_msg * req)
Sends an HTTP request.
Sends an HTTP request, by either reusing an existing HTTP connection or establishing a new one. If succesful, the initial HTTP response header is returned.
Parameters
mgr HTTP connection manager
https whether to use HTTPS (true) or unencrypted HTTP (false)
host name of authoritative HTTP server to send the request to
port TCP server port number, or 0 for the default port number
req HTTP request header to send
Returns
The initial HTTP response header, or NULL in case of failure.
References vlc_http_request(), and vlc_https_request().
Referenced by vlc_http_res_open().