VLC: HPACK compression
HPACK compression
HTTP » Connection manager » Connections » HTTP/2.0
HTTP/2 header compression (HPACK)
Functions
struct hpack_decoder * hpack_decode_init (size_t header_table_size)
void hpack_decode_destroy (struct hpack_decoder *)
int hpack_decode (struct hpack_decoder *dec, const uint8_t *data, size_t length, char *headers[][2], unsigned max)
size_t hpack_encode_hdr_neverindex (uint8_t *restrict buf, size_t size, const char *name, const char *value)
size_t hpack_encode (uint8_t *restrict buf, size_t size, const char *const headers[][2], unsigned count)
Detailed Description
HTTP/2 header compression (HPACK)
Function Documentation
hpack_decode()
int hpack_decode (struct hpack_decoder * dec, const uint8_t * data, size_t length, char * headers[][2], unsigned max)
References count, hpack_decode_hdr(), and name.
Referenced by vlc_h2_parse_headers_end().
hpack_decode_destroy()
void hpack_decode_destroy (struct hpack_decoder * dec)
References hpack_decoder::entries, and hpack_decoder::table.
Referenced by vlc_h2_parse_destroy().
hpack_decode_init()
struct hpack_decoder * hpack_decode_init (size_t header_table_size)
References hpack_decoder::entries, hpack_decoder::max_size, hpack_decoder::size, and hpack_decoder::table.
Referenced by vlc_h2_parse_init().
hpack_encode()
size_t hpack_encode (uint8_t *restrict buf, size_t size, const char *const headers[][2], unsigned count)
References count, and hpack_encode_hdr_neverindex().
Referenced by vlc_h2_frame_headers().
hpack_encode_hdr_neverindex()
size_t hpack_encode_hdr_neverindex (uint8_t *restrict buf, size_t size, const char * name, const char * value)
References hpack_encode_str_raw(), hpack_encode_str_raw_lower(), and name.
Referenced by hpack_encode().