VLC: Stream output
Stream output
Output
Topics
Access output
Raw output byte streams
Multiplexer
Multiplexers (file formatters)
Files
file vlc_sout.h
Stream output modules interface.
Data Structures
struct sout_instance_t
Stream output instance (FIXME: should be private to src/ to avoid invalid unsynchronized access)
struct sout_stream_t
struct sout_description_data_t
Description module.
Macros
#define sout_EncoderCreate(o) sout_EncoderCreate(VLC_OBJECT(o))
#define sout_AnnounceRegisterSDP(o, sdp, addr) sout_AnnounceRegisterSDP(VLC_OBJECT (o), sdp, addr)
#define sout_AnnounceUnRegister(o, a) sout_AnnounceUnRegister(VLC_OBJECT (o), a)
Typedefs
typedef struct sout_stream_id_sys_t sout_stream_id_sys_t
typedef struct sout_description_data_t sout_description_data_t
Description module.
Enumerations
enum sout_stream_query_e { SOUT_STREAM_EMPTY }
Functions
void sout_StreamChainDelete (sout_stream_t *p_first, sout_stream_t *p_last)
sout_stream_t * sout_StreamChainNew (sout_instance_t *p_sout, const char *psz_chain, sout_stream_t *p_next, sout_stream_t **p_last)
static sout_stream_id_sys_t * sout_StreamIdAdd (sout_stream_t *s, const es_format_t *fmt)
static void sout_StreamIdDel (sout_stream_t *s, sout_stream_id_sys_t *id)
static int sout_StreamIdSend (sout_stream_t *s, sout_stream_id_sys_t *id, block_t *b)
static void sout_StreamFlush (sout_stream_t *s, sout_stream_id_sys_t *id)
static int sout_StreamControl (sout_stream_t *s, int i_query,...)
encoder_t * sout_EncoderCreate (vlc_object_t *obj)
session_descriptor_t * sout_AnnounceRegisterSDP (vlc_object_t *, const char *, const char *)
Registers a new session with the announce handler, using a pregenerated SDP.
void sout_AnnounceUnRegister (vlc_object_t *, session_descriptor_t *)
Unregisters an existing session.
int vlc_sdp_Start (struct vlc_memstream *, vlc_object_t *obj, const char *cfgpref, const struct sockaddr *src, size_t slen, const struct sockaddr *addr, size_t alen)
void sdp_AddMedia (struct vlc_memstream *, const char *type, const char *protocol, int dport, unsigned pt, bool bw_indep, unsigned bw, const char *ptname, unsigned clockrate, unsigned channels, const char *fmtp)
void sdp_AddAttribute (struct vlc_memstream *, const char *name, const char *fmt,...)
Detailed Description
Macro Definition Documentation
sout_AnnounceRegisterSDP
#define sout_AnnounceRegisterSDP (o, sdp, addr) sout_AnnounceRegisterSDP(VLC_OBJECT (o), sdp, addr)
sout_AnnounceUnRegister
#define sout_AnnounceUnRegister (o, a) sout_AnnounceUnRegister(VLC_OBJECT (o), a)
sout_EncoderCreate
#define sout_EncoderCreate (o) sout_EncoderCreate(VLC_OBJECT(o))
Referenced by CreateEncoder().
Typedef Documentation
sout_description_data_t
typedef struct sout_description_data_t sout_description_data_t
Description module.
sout_stream_id_sys_t
typedef struct sout_stream_id_sys_t sout_stream_id_sys_t
Enumeration Type Documentation
sout_stream_query_e
enum sout_stream_query_e
Enumerator
SOUT_STREAM_EMPTY
Function Documentation
sdp_AddAttribute()
void sdp_AddAttribute (struct vlc_memstream * sdp, const char * name, const char * fmt, ...)
References name, and VLC_UNUSED.
sdp_AddMedia()
void sdp_AddMedia (struct vlc_memstream * sdp, const char * type, const char * protocol, int dport, unsigned pt, bool bw_indep, unsigned bw, const char * ptname, unsigned clockrate, unsigned channels, const char * fmtp)
References VLC_UNUSED.
sout_AnnounceRegisterSDP()
session_descriptor_t * sout_AnnounceRegisterSDP (vlc_object_t * obj, const char * sdp, const char * dst)
Registers a new session with the announce handler, using a pregenerated SDP.
Parameters
obj a VLC object
sdp the SDP to register
dst session address (needed for SAP address auto detection)
Returns
the new session descriptor structure
References AddressCreate(), session_descriptor_t::data, sap_address_t::first, sap_address_t::group, session_descriptor_t::length, vlc_memstream::length, sap_address_t::lock, mdate(), msg_Dbg, msg_Err, sap_address_t::next, session_descriptor_t::next, NI_MAXNUMERICHOST, sap_address_t::orig, vlc_memstream::ptr, sap_addrs, sap_mutex, sap_address_t::session_count, vlc_memstream::stream, unlikely, vlc_assert_unreachable, vlc_cond_signal(), vlc_getaddrinfo(), vlc_getnameinfo(), vlc_memstream_close(), vlc_memstream_open(), vlc_memstream_putc(), vlc_memstream_puts(), vlc_memstream_write(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_UNUSED, and sap_address_t::wait.
sout_AnnounceUnRegister()
void sout_AnnounceUnRegister (vlc_object_t * obj, session_descriptor_t * session)
Unregisters an existing session.
Parameters
obj a VLC object
session the session descriptor
References AddressDestroy(), session_descriptor_t::data, sap_address_t::first, sap_address_t::lock, msg_Dbg, sap_address_t::next, session_descriptor_t::next, sap_addrs, sap_mutex, sap_address_t::session_count, vlc_assert_unreachable, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_UNUSED, and sap_address_t::wait.
sout_EncoderCreate()
encoder_t * sout_EncoderCreate (vlc_object_t * obj)
References msg_Err, and vlc_custom_create.
sout_StreamChainDelete()
void sout_StreamChainDelete (sout_stream_t * p_first, sout_stream_t * p_last)
References sout_stream_t::p_next, sout_StreamDelete(), vlc_assert_unreachable, and VLC_UNUSED.
Referenced by sout_DeleteInstance().
sout_StreamChainNew()
sout_stream_t * sout_StreamChainNew (sout_instance_t * p_sout, const char * psz_chain, sout_stream_t * p_next, sout_stream_t ** p_last)
References config_ChainCreate(), config_ChainDestroy(), modules, name, psz_name, sout_StreamDelete(), sout_StreamNew(), strdup(), vlc_array_append_or_abort(), vlc_array_clear(), vlc_array_count(), vlc_array_init(), vlc_array_item_at_index, vlc_assert_unreachable, and VLC_UNUSED.
Referenced by sout_NewInstance().
sout_StreamControl()
static int sout_StreamControl (sout_stream_t * s, int i_query, ...) inline static
< Unspecified error
References sout_stream_t::pf_control, and VLC_EGENERIC.
Referenced by sout_InputIsEmpty().
sout_StreamFlush()
static void sout_StreamFlush (sout_stream_t * s, sout_stream_id_sys_t * id) inline static
References sout_stream_t::pf_flush.
Referenced by sout_InputFlush().
sout_StreamIdAdd()
static sout_stream_id_sys_t * sout_StreamIdAdd (sout_stream_t * s, const es_format_t * fmt) inline static
References sout_stream_t::pf_add.
sout_StreamIdDel()
static void sout_StreamIdDel (sout_stream_t * s, sout_stream_id_sys_t * id) inline static
References sout_stream_t::pf_del.
sout_StreamIdSend()
static int sout_StreamIdSend (sout_stream_t * s, sout_stream_id_sys_t * id, block_t * b) inline static
References sout_stream_t::pf_send.
vlc_sdp_Start()
int vlc_sdp_Start (struct vlc_memstream * sdp, vlc_object_t * obj, const char * cfgpref, const struct sockaddr * src, size_t slen, const struct sockaddr * addr, size_t alen)
References VLC_UNUSED.