VLC: Software updates
Software updates
Interface
Over-the-air VLC software updates
Files
file vlc_update.h
VLC software update interface.
Data Structures
struct update_release_t
Describes an update VLC release number.
Macros
#define update_New(a) update_New(VLC_OBJECT(a))
Typedefs
typedef struct update_release_t update_release_t
Functions
update_t * update_New (vlc_object_t *)
Create a new update VLC struct.
void update_Delete (update_t *)
Delete an update_t struct.
void update_Check (update_t *, void(*callback)(void *, bool), void *)
Check for updates.
bool update_NeedUpgrade (update_t *)
void update_Download (update_t *, const char *)
Download the file given in the update_t.
update_release_t * update_GetRelease (update_t *)
Detailed Description
Over-the-air VLC software updates
Macro Definition Documentation
update_New
#define update_New (a) update_New(VLC_OBJECT(a))
Typedef Documentation
update_release_t
typedef struct update_release_t update_release_t
Function Documentation
update_Check()
void update_Check (update_t * p_update, void(* pf_callback)(void *, bool), void * p_data)
Check for updates.
Parameters
p_update pointer to update struct
pf_callback pointer to a function to call when the update_check is finished
p_data pointer to some datas to give to the callback
Returns
nothing
References update_t::p_check, update_check_thread_t::p_data, update_check_thread_t::p_update, update_check_thread_t::pf_callback, update_check_thread_t::thread, update_CheckReal(), vlc_assert_unreachable, vlc_clone(), vlc_join(), and VLC_THREAD_PRIORITY_LOW.
update_Delete()
void update_Delete (update_t * p_update)
Delete an update_t struct.
Parameters
p_update update_t* pointer
Returns
nothing
References update_download_thread_t::aborted, update_t::lock, update_t::p_check, update_t::p_download, update_t::p_pkey, update_release_t::psz_desc, update_release_t::psz_url, update_t::release, update_check_thread_t::thread, update_download_thread_t::thread, vlc_assert_unreachable, vlc_join(), vlc_mutex_destroy(), and vlc_object_release.
update_Download()
void update_Download (update_t * p_update, const char * psz_destdir)
Download the file given in the update_t.
Parameters
p_update structure
dir to store the download file
Returns
nothing
References update_download_thread_t::aborted, update_t::p_download, update_t::p_libvlc, update_download_thread_t::p_update, update_download_thread_t::psz_destdir, strdup(), update_download_thread_t::thread, update_DownloadReal(), vlc_assert_unreachable, vlc_clone(), vlc_custom_create, vlc_join(), vlc_object_release, and VLC_THREAD_PRIORITY_LOW.
update_GetRelease()
update_release_t * update_GetRelease (update_t * p_update)
References update_t::release, and vlc_assert_unreachable.
update_NeedUpgrade()
bool update_NeedUpgrade (update_t * p_update)
References update_release_t::i_extra, update_release_t::i_major, update_release_t::i_minor, update_release_t::i_revision, update_t::release, and vlc_assert_unreachable.
update_New()
update_t * update_New (vlc_object_t * p_this)
Create a new update VLC struct.
Parameters
p_this the calling vlc_object
Returns
pointer to new update_t or NULL
References vlc_common_members::libvlc, update_t::lock, vlc_object_t::obj, update_t::p_check, update_t::p_download, update_t::p_libvlc, update_t::p_pkey, update_release_t::psz_desc, update_release_t::psz_url, update_t::release, vlc_gcrypt_init(), and vlc_mutex_init().