VLC: On-screen display
On-screen display
Output » Video output » Sub-picture channels
Files
file vlc_vout_osd.h
Overlay text and widgets.
Enumerations
enum {
OSD_PLAY_ICON = 1 , OSD_PAUSE_ICON , OSD_SPEAKER_ICON , OSD_MUTE_ICON ,
OSD_HOR_SLIDER , OSD_VERT_SLIDER
}
OSD menu position and picture type defines.
Functions
int vout_OSDEpg (vout_thread_t *, input_item_t *)
Show EPG information about the current program of an input item.
void vout_OSDText (vout_thread_t *vout, int channel, int position, mtime_t duration, const char *text)
Write an informative message if the OSD option is enabled.
void vout_OSDMessage (vout_thread_t *, int, const char *,...)
Write an informative message at the default location, for the default duration and only if the OSD option is enabled.
void vout_OSDSlider (vout_thread_t *, int, int, short)
Display a slider on the video output.
void vout_OSDIcon (vout_thread_t *, int, short)
Display an Icon on the video output.
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
OSD menu position and picture type defines.
Enumerator
OSD_PLAY_ICON
OSD_PAUSE_ICON
OSD_SPEAKER_ICON
OSD_MUTE_ICON
OSD_HOR_SLIDER
OSD_VERT_SLIDER
Function Documentation
vout_OSDEpg()
int vout_OSDEpg (vout_thread_t * vout, input_item_t * input)
Show EPG information about the current program of an input item.
Parameters
vout pointer to the vout the information is to be showed on
p_input pointer to the input item the information is to be showed
i_action osd_epg_action_e action
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References subpicture_updater_sys_t::art, subpicture_t::b_absolute, subpicture_t::b_ephemer, subpicture_t::b_fade, subpicture_t::b_subtitle, subpicture_updater_sys_t::epg, GetDefaultArtUri(), subpicture_t::i_channel, vlc_epg_event_t::i_duration, input_item_t::i_epg_time, vlc_epg_t::i_event, vlc_epg_event_t::i_id, vlc_epg_t::i_id, vlc_epg_t::i_source_id, subpicture_t::i_start, vlc_epg_event_t::i_start, subpicture_t::i_stop, input_item_GetMeta(), input_item_t::lock, mdate(), subpicture_updater_sys_t::obj, OSDEpgDestroy(), OSDEpgUpdate(), OSDEpgValidate(), vlc_epg_t::p_current, input_item_t::p_epg_table, subpicture_updater_t::pf_validate, vlc_epg_t::pp_event, vlc_epg_t::psz_name, strdup(), subpicture_New(), subpicture_updater_sys_t::time, VLC_EGENERIC, vlc_epg_AddEvent(), vlc_epg_Delete(), vlc_epg_event_Delete(), vlc_epg_event_Duplicate(), vlc_epg_New(), vlc_epg_SetCurrent(), vlc_meta_ArtworkURL, vlc_meta_Title, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, VLC_SUCCESS, vout_PutSubpicture(), and VOUT_SPU_CHANNEL_OSD.
vout_OSDIcon()
void vout_OSDIcon (vout_thread_t * vout, int channel, short type)
Display an Icon on the video output.
Parameters
p_this The object that called the function.
i_channel Subpicture channel
i_type Types are: OSD_PLAY_ICON, OSD_PAUSE_ICON, OSD_SPEAKER_ICON, OSD_MUTE_ICON
References OSDWidget().
vout_OSDMessage()
void vout_OSDMessage (vout_thread_t * vout, int channel, const char * format, ...)
Write an informative message at the default location, for the default duration and only if the OSD option is enabled.
Parameters
vout The vout on which the message will be displayed
channel Subpicture channel
format printf style formatting
Provided for convenience.
References SUBPICTURE_ALIGN_RIGHT, SUBPICTURE_ALIGN_TOP, vasprintf(), and vout_OSDText().
Referenced by ControlNavDisplayPosition(), ControlNavDisplayVolume(), input_vaControl(), and VoutOsdSnapshot().
vout_OSDSlider()
void vout_OSDSlider (vout_thread_t * vout, int channel, int position, short type)
Display a slider on the video output.
Parameters
p_this The object that called the function.
i_channel Subpicture channel
i_postion Current position in the slider
i_type Types are: OSD_HOR_SLIDER and OSD_VERT_SLIDER.
References OSDWidget().
vout_OSDText()
void vout_OSDText (vout_thread_t * vout, int channel, int position, mtime_t duration, const char * text)
Write an informative message if the OSD option is enabled.
Parameters
vout The vout on which the message will be displayed
channel Subpicture channel
position Position of the text
duration Duration of the text being displayed
text Text to be displayed
References subpicture_t::b_absolute, subpicture_t::b_ephemer, subpicture_t::b_fade, subpicture_t::i_channel, subpicture_t::i_start, subpicture_t::i_stop, mdate(), OSDTextDestroy(), OSDTextUpdate(), OSDTextValidate(), subpicture_updater_t::pf_validate, subpicture_updater_sys_t::position, strdup(), SUBPICTURE_ALIGN_MASK, subpicture_New(), subpicture_updater_sys_t::text, var_InheritBool, and vout_PutSubpicture().
Referenced by ThreadDisplayOsdTitle(), and vout_OSDMessage().