VLC: VLM
VLM
VLC stream manager
Topics
Video on Demand (VoD)
Video on Demand (VOD) functionality provided by VLM
Files
file vlc_vlm.h
VLC stream manager interface.
Data Structures
struct vlm_media_t
VLM media.
struct vlm_media_instance_t
VLM media instance.
struct vlm_event_t
struct vlm_message_t
Macros
#define vlm_New(a) vlm_New(VLC_OBJECT(a))
Enumerations
enum vlm_event_type_e {
VLM_EVENT_MEDIA_ADDED = 0x100 , VLM_EVENT_MEDIA_REMOVED , VLM_EVENT_MEDIA_CHANGED , VLM_EVENT_MEDIA_INSTANCE_STARTED = 0x200 ,
VLM_EVENT_MEDIA_INSTANCE_STOPPED , VLM_EVENT_MEDIA_INSTANCE_STATE
}
VLM events You can catch vlm event by adding a callback on the variable "intf-event" of the VLM object.
enum vlm_query_e {
VLM_GET_MEDIAS , VLM_CLEAR_MEDIAS , VLM_ADD_MEDIA , VLM_DEL_MEDIA ,
VLM_CHANGE_MEDIA , VLM_GET_MEDIA , VLM_GET_MEDIA_ID , VLM_GET_MEDIA_INSTANCES ,
VLM_CLEAR_MEDIA_INSTANCES , VLM_START_MEDIA_BROADCAST_INSTANCE , VLM_START_MEDIA_VOD_INSTANCE , VLM_STOP_MEDIA_INSTANCE ,
VLM_PAUSE_MEDIA_INSTANCE , VLM_GET_MEDIA_INSTANCE_TIME , VLM_SET_MEDIA_INSTANCE_TIME , VLM_GET_MEDIA_INSTANCE_POSITION ,
VLM_SET_MEDIA_INSTANCE_POSITION , VLM_CLEAR_SCHEDULES
}
VLM control query.
Functions
vlm_t * vlm_New (vlc_object_t *)
void vlm_Delete (vlm_t *)
int vlm_ExecuteCommand (vlm_t *, const char *, vlm_message_t **)
int vlm_Control (vlm_t *p_vlm, int i_query,...)
vlm_message_t * vlm_MessageSimpleNew (const char *)
vlm_message_t * vlm_MessageNew (const char *, const char *,...)
vlm_message_t * vlm_MessageAdd (vlm_message_t *, vlm_message_t *)
void vlm_MessageDelete (vlm_message_t *)
static void vlm_media_Init (vlm_media_t *p_media)
Initialize a vlm_media_t instance.
static void vlm_media_Copy (vlm_media_t *restrict p_dst, const vlm_media_t *restrict p_src)
Copy a vlm_media_t instance into another vlm_media_t instance.
static void vlm_media_Clean (vlm_media_t *p_media)
Cleanup and release memory associated with this vlm_media_t instance.
static vlm_media_t * vlm_media_New (void)
Allocate a new vlm_media_t instance.
static void vlm_media_Delete (vlm_media_t *p_media)
Delete a vlm_media_t instance.
static vlm_media_t * vlm_media_Duplicate (vlm_media_t *p_src)
Copy a vlm_media_t instance.
static void vlm_media_instance_Init (vlm_media_instance_t *p_instance)
Initialize vlm_media_instance_t.
static void vlm_media_instance_Clean (vlm_media_instance_t *p_instance)
Cleanup vlm_media_instance_t.
static vlm_media_instance_t * vlm_media_instance_New (void)
Allocate a new vlm_media_instance_t.
static void vlm_media_instance_Delete (vlm_media_instance_t *p_instance)
Delete a vlm_media_instance_t.
Detailed Description
VLC stream manager
VLM is the server core in vlc that allows streaming of multiple media streams at the same time. It provides broadcast, schedule and video on demand features for streaming using several streaming and network protocols.
Macro Definition Documentation
vlm_New
#define vlm_New (a) vlm_New(VLC_OBJECT(a))
Referenced by libvlc_InternalInit().
Enumeration Type Documentation
vlm_event_type_e
enum vlm_event_type_e
VLM events You can catch vlm event by adding a callback on the variable "intf-event" of the VLM object.
This variable is an address that will hold a vlm_event_t* value.
Enumerator
VLM_EVENT_MEDIA_ADDED
VLM_EVENT_MEDIA_REMOVED
VLM_EVENT_MEDIA_CHANGED
VLM_EVENT_MEDIA_INSTANCE_STARTED
VLM_EVENT_MEDIA_INSTANCE_STOPPED
VLM_EVENT_MEDIA_INSTANCE_STATE
vlm_query_e
enum vlm_query_e
VLM control query.
Enumerator
VLM_GET_MEDIAS
VLM_CLEAR_MEDIAS
VLM_ADD_MEDIA
VLM_DEL_MEDIA
VLM_CHANGE_MEDIA
VLM_GET_MEDIA
VLM_GET_MEDIA_ID
VLM_GET_MEDIA_INSTANCES
VLM_CLEAR_MEDIA_INSTANCES
VLM_START_MEDIA_BROADCAST_INSTANCE
VLM_START_MEDIA_VOD_INSTANCE
VLM_STOP_MEDIA_INSTANCE
VLM_PAUSE_MEDIA_INSTANCE
VLM_GET_MEDIA_INSTANCE_TIME
VLM_SET_MEDIA_INSTANCE_TIME
VLM_GET_MEDIA_INSTANCE_POSITION
VLM_SET_MEDIA_INSTANCE_POSITION
VLM_CLEAR_SCHEDULES
Function Documentation
vlm_Control()
int vlm_Control (vlm_t * p_vlm, int i_query, ...)
References vlm_t::lock, vlc_assert_unreachable, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_UNUSED, and vlm_vaControlInternal().
vlm_Delete()
void vlm_Delete (vlm_t * p_vlm)
References vlm_t::i_media, vlm_t::i_schedule, vlc_common_members::libvlc, libvlc_priv(), vlm_t::lock, vlm_t::lock_manage, vlm_t::media, module_unneed, vlm_t::obj, vod_t::p_module, libvlc_priv_t::p_vlm, vlm_t::p_vod, vlm_t::schedule, TAB_CLEAN, vlm_t::thread, vlm_t::users, vlc_assert_unreachable, vlc_cancel(), vlc_cond_destroy(), vlc_join(), vlc_mutex_destroy(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, VLC_UNUSED, VLM_CLEAR_MEDIAS, VLM_CLEAR_SCHEDULES, vlm_ControlInternal(), vlm_mutex, and vlm_t::wait_manage.
Referenced by libvlc_InternalCleanup().
vlm_ExecuteCommand()
int vlm_ExecuteCommand (vlm_t * p_vlm, const char * psz_command, vlm_message_t ** pp_message)
References ExecuteCommand(), vlm_t::lock, vlc_assert_unreachable, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_UNUSED.
Referenced by vlm_New().
vlm_media_Clean()
static void vlm_media_Clean (vlm_media_t * p_media) inline static
Cleanup and release memory associated with this vlm_media_t instance.
You still need to release p_media itself with vlm_media_Delete().
Parameters
p_media vlm_media_t to cleanup
References vlm_media_t::b_vod, vlm_media_t::i_input, vlm_media_t::i_option, vlm_media_t::ppsz_input, vlm_media_t::ppsz_option, vlm_media_t::psz_mux, vlm_media_t::psz_name, vlm_media_t::psz_output, TAB_CLEAN, and vlm_media_t::vod.
Referenced by vlm_ControlMediaChange(), vlm_ControlMediaDel(), and vlm_media_Delete().
vlm_media_Copy()
static void vlm_media_Copy (vlm_media_t *restrict p_dst, const vlm_media_t *restrict p_src) inline static
Copy a vlm_media_t instance into another vlm_media_t instance.
Parameters
p_dst vlm_media_t instance to copy to
p_src vlm_media_t instance to copy from
References vlm_media_t::b_enabled, vlm_media_t::b_loop, vlm_media_t::b_vod, vlm_media_t::broadcast, vlm_media_t::i_input, vlm_media_t::i_option, vlm_media_t::id, vlm_media_t::ppsz_input, vlm_media_t::ppsz_option, vlm_media_t::psz_mux, vlm_media_t::psz_name, vlm_media_t::psz_output, strdup(), TAB_APPEND_CAST, and vlm_media_t::vod.
Referenced by vlm_ControlMediaAdd(), vlm_ControlMediaChange(), and vlm_media_Duplicate().
vlm_media_Delete()
static void vlm_media_Delete (vlm_media_t * p_media) inline static
Delete a vlm_media_t instance.
Parameters
p_media vlm_media_t instance to delete
References vlm_media_Clean().
vlm_media_Duplicate()
static vlm_media_t * vlm_media_Duplicate (vlm_media_t * p_src) inline static
Copy a vlm_media_t instance.
Parameters
p_src vlm_media_t instance to copy
Returns
vlm_media_t duplicate of p_src
References vlm_media_Copy(), and vlm_media_New().
Referenced by vlm_ControlMediaGet(), and vlm_ControlMediaGets().
vlm_media_Init()
static void vlm_media_Init (vlm_media_t * p_media) inline static
Initialize a vlm_media_t instance.
Parameters
p_media vlm_media_t instance to initialize
References TAB_INIT.
Referenced by vlm_media_New().
vlm_media_instance_Clean()
static void vlm_media_instance_Clean (vlm_media_instance_t * p_instance) inline static
Cleanup vlm_media_instance_t.
Parameters
p_instance vlm_media_instance_t to cleanup
References vlm_media_instance_t::psz_name.
Referenced by vlm_media_instance_Delete().
vlm_media_instance_Delete()
static void vlm_media_instance_Delete (vlm_media_instance_t * p_instance) inline static
Delete a vlm_media_instance_t.
Parameters
p_instance vlm_media_instance_t to delete
References vlm_media_instance_Clean().
vlm_media_instance_Init()
static void vlm_media_instance_Init (vlm_media_instance_t * p_instance) inline static
Initialize vlm_media_instance_t.
Parameters
p_instance vlm_media_instance_t to initialize
References vlm_media_instance_t::b_paused, vlm_media_instance_t::d_position, vlm_media_instance_t::i_length, vlm_media_instance_t::i_rate, vlm_media_instance_t::i_time, INPUT_RATE_DEFAULT, and vlm_media_instance_t::psz_name.
Referenced by vlm_media_instance_New().
vlm_media_instance_New()
static vlm_media_instance_t * vlm_media_instance_New (void) inline static
Allocate a new vlm_media_instance_t.
Returns
a new vlm_media_instance_t
References vlm_media_instance_Init().
Referenced by vlm_ControlMediaInstanceGets().
vlm_media_New()
static vlm_media_t * vlm_media_New (void) inline static
Allocate a new vlm_media_t instance.
Returns
vlm_media_t instance
References vlm_media_Init().
Referenced by vlm_media_Duplicate().
vlm_MessageAdd()
vlm_message_t * vlm_MessageAdd (vlm_message_t * a, vlm_message_t * b)
References vlc_assert_unreachable, and VLC_UNUSED.
vlm_MessageDelete()
void vlm_MessageDelete (vlm_message_t * m)
References vlc_assert_unreachable, and VLC_UNUSED.
Referenced by Manage(), and vlm_New().
vlm_MessageNew()
vlm_message_t * vlm_MessageNew (const char * a, const char * fmt, ...)
References VLC_UNUSED, and vlm_MessageSimpleNew().
vlm_MessageSimpleNew()
vlm_message_t * vlm_MessageSimpleNew (const char * a)
References VLC_UNUSED.
Referenced by vlm_MessageNew().
vlm_New()
vlm_t * vlm_New (vlc_object_t * p_this)
References asprintf(), vlm_t::i_id, vlm_t::i_media, vlm_t::i_schedule, vlm_t::input_state_changed, vlc_common_members::libvlc, libvlc_priv(), likely, vlm_t::lock, vlm_t::lock_manage, Manage(), vlm_t::media, msg_Dbg, msg_Err, msg_Warn, vlc_object_t::obj, libvlc_priv_t::p_vlm, vlm_t::p_vod, vlm_t::schedule, TAB_INIT, vlm_t::thread, vlm_t::users, var_Create, var_CreateGetString, vlc_clone(), vlc_cond_destroy(), vlc_cond_init_daytime(), vlc_custom_create, vlc_mutex_destroy(), vlc_mutex_init(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, VLC_THREAD_PRIORITY_LOW, VLC_VAR_ADDRESS, vlm_ExecuteCommand(), vlm_MessageDelete(), vlm_mutex, and vlm_t::wait_manage.