VLC: Resources
Resources
HTTP
Remote HTTP resources identified by a URL
Topics
Files
HTTP read-only files
Live streams
Trivial HTTP-based live streams
Data Structures
struct vlc_http_resource_cbs
struct vlc_http_resource
Functions
int vlc_http_res_init (struct vlc_http_resource *, const struct vlc_http_resource_cbs *cbs, struct vlc_http_mgr *mgr, const char *uri, const char *ua, const char *ref)
void vlc_http_res_destroy (struct vlc_http_resource *)
Destroys an HTTP resource.
struct vlc_http_msg * vlc_http_res_open (struct vlc_http_resource *res, void *)
int vlc_http_res_get_status (struct vlc_http_resource *res)
char * vlc_http_res_get_redirect (struct vlc_http_resource *)
Gets redirection URL.
char * vlc_http_res_get_type (struct vlc_http_resource *)
Gets MIME type.
struct block_t * vlc_http_res_read (struct vlc_http_resource *)
Reads data.
int vlc_http_res_set_login (struct vlc_http_resource *res, const char *username, const char *password)
char * vlc_http_res_get_basic_realm (struct vlc_http_resource *res)
Detailed Description
Remote HTTP resources identified by a URL
Function Documentation
vlc_http_res_destroy()
void vlc_http_res_destroy (struct vlc_http_resource * res)
Destroys an HTTP resource.
Releases all underlying resources allocated or held by the HTTP resource object.
References vlc_http_res_deinit().
Referenced by Close(), and Open().
vlc_http_res_get_basic_realm()
char * vlc_http_res_get_basic_realm (struct vlc_http_resource * res)
References vlc_http_resource::response, vlc_http_msg_get_basic_realm(), and vlc_http_res_get_status().
Referenced by Open().
vlc_http_res_get_redirect()
char * vlc_http_res_get_redirect (struct vlc_http_resource *)
Gets redirection URL.
Checks if the resource URL lead to a redirection. If so, return the redirect location.
Returns
Heap-allocated URL or NULL if no redirection.
vlc_http_res_get_status()
int vlc_http_res_get_status (struct vlc_http_resource * res)
References vlc_http_resource::failure, vlc_http_resource::response, vlc_http_msg_get_status(), and vlc_http_res_open().
Referenced by Open(), vlc_http_file_can_seek(), vlc_http_file_get_size(), vlc_http_res_get_basic_realm(), vlc_http_res_get_redirect(), vlc_http_res_get_type(), and vlc_http_res_read().
vlc_http_res_get_type()
char * vlc_http_res_get_type (struct vlc_http_resource * res)
Gets MIME type.
Returns
Heap-allocated MIME type string, or NULL if unknown.
References vlc_http_resource::response, vlc_http_msg::status, strdup(), vlc_http_msg_get_header(), and vlc_http_res_get_status().
vlc_http_res_init()
int vlc_http_res_init (struct vlc_http_resource * , const struct vlc_http_resource_cbs * cbs, struct vlc_http_mgr * mgr, const char * uri, const char * ua, const char * ref)
vlc_http_res_open()
struct vlc_http_msg * vlc_http_res_open (struct vlc_http_resource * res, void * opaque)
References vlc_http_resource::cbs, vlc_http_resource::host, vlc_http_resource::manager, vlc_http_resource::negotiate, vlc_http_resource::path, vlc_http_resource::port, vlc_http_resource_cbs::response_validate, vlc_http_resource::secure, vlc_http_msg::status, unlikely, vlc_http_mgr_get_jar(), vlc_http_mgr_request(), vlc_http_msg_destroy(), vlc_http_msg_get_cookies(), vlc_http_msg_get_final(), vlc_http_msg_get_status(), and vlc_http_res_req().
Referenced by vlc_http_file_seek(), and vlc_http_res_get_status().
vlc_http_res_read()
struct block_t * vlc_http_res_read (struct vlc_http_resource * res)
Reads data.
References vlc_http_resource::response, vlc_http_msg_read(), and vlc_http_res_get_status().
Referenced by vlc_http_file_read(), and vlc_http_live_read().
vlc_http_res_set_login()
int vlc_http_res_set_login (struct vlc_http_resource * res, const char * username, const char * password)
References vlc_http_resource::password, vlc_http_resource::response, strdup(), unlikely, vlc_http_resource::username, vlc_http_msg_destroy(), and vlc_http_msg_get_status().
Referenced by Open().