VLC: ES output
ES output
Input
Elementary streams output
Files
file vlc_es_out.h
Elementary streams output interface.
Data Structures
struct es_out_t
Enumerations
enum es_out_query_e {
ES_OUT_SET_ES , ES_OUT_RESTART_ES , ES_OUT_RESTART_ALL_ES , ES_OUT_SET_ES_DEFAULT ,
ES_OUT_SET_ES_STATE , ES_OUT_GET_ES_STATE , ES_OUT_SET_ES_CAT_POLICY , ES_OUT_SET_GROUP ,
ES_OUT_SET_PCR , ES_OUT_SET_GROUP_PCR , ES_OUT_RESET_PCR , ES_OUT_SET_ES_FMT ,
ES_OUT_SET_NEXT_DISPLAY_TIME , ES_OUT_SET_GROUP_META , ES_OUT_SET_GROUP_EPG , ES_OUT_SET_GROUP_EPG_EVENT ,
ES_OUT_SET_EPG_TIME , ES_OUT_DEL_GROUP , ES_OUT_SET_ES_SCRAMBLED_STATE , ES_OUT_GET_EMPTY ,
ES_OUT_SET_META , ES_OUT_GET_PCR_SYSTEM , ES_OUT_MODIFY_PCR_SYSTEM , ES_OUT_POST_SUBNODE ,
ES_OUT_PRIVATE_START = 0x10000
}
enum es_out_policy_e { ES_OUT_ES_POLICY_EXCLUSIVE = 0 , ES_OUT_ES_POLICY_SIMULTANEOUS }
Functions
static es_out_id_t * es_out_Add (es_out_t *out, const es_format_t *fmt)
static void es_out_Del (es_out_t *out, es_out_id_t *id)
static int es_out_Send (es_out_t *out, es_out_id_t *id, block_t *p_block)
static int es_out_vaControl (es_out_t *out, int i_query, va_list args)
static int es_out_Control (es_out_t *out, int i_query,...)
static void es_out_Delete (es_out_t *p_out)
static int es_out_SetPCR (es_out_t *out, int64_t pcr)
static int es_out_ControlSetMeta (es_out_t *out, const vlc_meta_t *p_meta)
static int es_out_ControlGetPcrSystem (es_out_t *out, mtime_t *pi_system, mtime_t *pi_delay)
static int es_out_ControlModifyPcrSystem (es_out_t *out, bool b_absolute, mtime_t i_system)
Detailed Description
Elementary streams output
Enumeration Type Documentation
es_out_policy_e
enum es_out_policy_e
Enumerator
ES_OUT_ES_POLICY_EXCLUSIVE
ES_OUT_ES_POLICY_SIMULTANEOUS
es_out_query_e
enum es_out_query_e
Enumerator
ES_OUT_SET_ES
ES_OUT_RESTART_ES
ES_OUT_RESTART_ALL_ES
ES_OUT_SET_ES_DEFAULT
ES_OUT_SET_ES_STATE
ES_OUT_GET_ES_STATE
ES_OUT_SET_ES_CAT_POLICY
ES_OUT_SET_GROUP
ES_OUT_SET_PCR
ES_OUT_SET_GROUP_PCR
ES_OUT_RESET_PCR
ES_OUT_SET_ES_FMT
ES_OUT_SET_NEXT_DISPLAY_TIME
ES_OUT_SET_GROUP_META
ES_OUT_SET_GROUP_EPG
ES_OUT_SET_GROUP_EPG_EVENT
ES_OUT_SET_EPG_TIME
ES_OUT_DEL_GROUP
ES_OUT_SET_ES_SCRAMBLED_STATE
ES_OUT_GET_EMPTY
ES_OUT_SET_META
ES_OUT_GET_PCR_SYSTEM
ES_OUT_MODIFY_PCR_SYSTEM
ES_OUT_POST_SUBNODE
ES_OUT_PRIVATE_START
Function Documentation
es_out_Add()
static es_out_id_t * es_out_Add (es_out_t * out, const es_format_t * fmt) inline static
References es_out_t::pf_add.
Referenced by CmdExecuteAdd().
es_out_Control()
static int es_out_Control (es_out_t * out, int i_query, ...) inline static
References es_out_vaControl().
Referenced by CmdExecuteControl(), Control(), ControlLocked(), es_out_ControlGetPcrSystem(), es_out_ControlModifyPcrSystem(), es_out_ControlSetMeta(), es_out_Eos(), es_out_GetBuffering(), es_out_GetEmpty(), es_out_GetEsObjects(), es_out_GetGroupForced(), es_out_GetWakeup(), es_out_SetDelay(), es_out_SetFrameNext(), es_out_SetJitter(), es_out_SetMode(), es_out_SetPauseState(), es_out_SetPCR(), es_out_SetRate(), es_out_SetRecordState(), es_out_SetTime(), es_out_SetTimes(), EsOutControlLocked(), input_SlaveSourceAdd(), and input_vaControl().
es_out_ControlGetPcrSystem()
static int es_out_ControlGetPcrSystem (es_out_t * out, mtime_t * pi_system, mtime_t * pi_delay) inline static
References es_out_Control(), and ES_OUT_GET_PCR_SYSTEM.
Referenced by input_vaControl().
es_out_ControlModifyPcrSystem()
static int es_out_ControlModifyPcrSystem (es_out_t * out, bool b_absolute, mtime_t i_system) inline static
References es_out_Control(), and ES_OUT_MODIFY_PCR_SYSTEM.
Referenced by ControlLocked(), and input_vaControl().
es_out_ControlSetMeta()
static int es_out_ControlSetMeta (es_out_t * out, const vlc_meta_t * p_meta) inline static
References es_out_Control(), and ES_OUT_SET_META.
Referenced by Init(), and InputUpdateMeta().
es_out_Del()
static void es_out_Del (es_out_t * out, es_out_id_t * id) inline static
References es_out_t::pf_del.
Referenced by CmdExecuteDel().
es_out_Delete()
static void es_out_Delete (es_out_t * p_out) inline static
References es_out_t::pf_destroy.
Referenced by End(), Init(), and input_Destructor().
es_out_Send()
static int es_out_Send (es_out_t * out, es_out_id_t * id, block_t * p_block) inline static
References es_out_t::pf_send.
Referenced by CmdExecuteSend().
es_out_SetPCR()
static int es_out_SetPCR (es_out_t * out, int64_t pcr) inline static
References es_out_Control(), and ES_OUT_SET_PCR.
es_out_vaControl()
static int es_out_vaControl (es_out_t * out, int i_query, va_list args) inline static
References es_out_t::pf_control.
Referenced by ControlLocked(), and es_out_Control().