VLC: HTTP/2.0
HTTP/2.0
HTTP » Connection manager » Connections
Topics
HTTP/2 frames
HTTP/2 output
HPACK compression
HTTP/2 header compression (HPACK)
Functions
struct vlc_http_conn * vlc_h2_conn_create (void *ctx, struct vlc_tls *)
Detailed Description
Function Documentation
vlc_h2_conn_create()
struct vlc_http_conn * vlc_h2_conn_create (void * ctx, struct vlc_tls * tls)
References vlc_http_conn::cbs, vlc_h2_conn::conn, vlc_http_conn::tls, unlikely, vlc_clone(), vlc_h2_conn_callbacks, vlc_h2_conn_queue(), vlc_h2_frame_settings(), vlc_h2_output_create(), vlc_h2_output_destroy(), vlc_h2_recv_thread(), vlc_mutex_destroy(), vlc_mutex_init(), and VLC_THREAD_PRIORITY_INPUT.
Referenced by vlc_https_request().