VLC: Sub-picture channels
Sub-picture channels
Output » Video output
Topics
On-screen display
Files
file vlc_spu.h
Data Structures
struct spu_t
Subpicture unit descriptor.
Macros
#define spu_Create(a, b) spu_Create(VLC_OBJECT(a),b)
Typedefs
typedef struct spu_private_t spu_private_t
Functions
spu_t * spu_Create (vlc_object_t *, vout_thread_t *)
Creates the subpicture unit.
void spu_Destroy (spu_t *)
Destroy the subpicture unit.
void spu_PutSubpicture (spu_t *, subpicture_t *)
This function sends a subpicture to the spu_t core.
subpicture_t * spu_Render (spu_t *, const vlc_fourcc_t *p_chroma_list, const video_format_t *p_fmt_dst, const video_format_t *p_fmt_src, mtime_t render_subtitle_date, mtime_t render_osd_date, bool ignore_osd)
This function will return an unique subpicture containing the OSD and subtitles visibles at the requested date.
int spu_RegisterChannel (spu_t *)
It registers a new SPU channel.
void spu_ClearChannel (spu_t *, int)
It clears all subpictures associated to a SPU channel.
void spu_ChangeSources (spu_t *, const char *)
It changes the sub sources list.
void spu_ChangeFilters (spu_t *, const char *)
It changes the sub filters list.
Detailed Description
Macro Definition Documentation
spu_Create
#define spu_Create (a, b) spu_Create(VLC_OBJECT(a),b)
Referenced by VoutCreate().
Typedef Documentation
spu_private_t
typedef struct spu_private_t spu_private_t
Function Documentation
spu_ChangeFilters()
void spu_ChangeFilters (spu_t * spu, const char * filters)
It changes the sub filters list.
References spu_private_t::filter_chain_current, spu_private_t::filter_chain_update, spu_private_t::lock, spu_t::p, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadChangeSubFilters().
spu_ChangeSources()
void spu_ChangeSources (spu_t * spu, const char * filters)
It changes the sub sources list.
References spu_private_t::lock, spu_t::p, spu_private_t::source_chain_current, spu_private_t::source_chain_update, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadChangeSubSources().
spu_ClearChannel()
void spu_ClearChannel (spu_t * spu, int channel)
It clears all subpictures associated to a SPU channel.
References spu_heap_t::entry, spu_private_t::heap, subpicture_t::i_channel, spu_private_t::lock, spu_t::p, vlc_mutex_lock(), vlc_mutex_unlock(), VOUT_MAX_SUBPICTURES, and VOUT_SPU_CHANNEL_OSD.
Referenced by spu_PutSubpicture(), SubSourceClean(), and ThreadFlushSubpicture().
spu_Create()
spu_t * spu_Create (vlc_object_t * object, vout_thread_t * vout)
Creates the subpicture unit.
Parameters
p_this the parent object which creates the subpicture unit
References spu_private_t::channel, spu_private_t::filter_chain, spu_private_t::filter_chain_lock, filter_chain_New, spu_private_t::filter_chain_update, spu_private_t::heap, spu_private_t::last_sort_date, spu_private_t::lock, spu_private_t::margin, spu_t::p, spu_private_t::scale, spu_private_t::scale_yuvp, spu_private_t::source_chain, spu_private_t::source_chain_lock, spu_private_t::source_chain_update, SPU_ES, SpuHeapInit(), SpuRenderCreateAndLoadScale(), SpuRenderCreateAndLoadText(), spu_private_t::text, var_InheritInteger, VLC_CODEC_RGBA, VLC_CODEC_YUVA, VLC_CODEC_YUVP, vlc_custom_create, vlc_mutex_init(), VLC_OBJECT, spu_private_t::vout, and VOUT_SPU_CHANNEL_AVAIL_FIRST.
spu_Destroy()
void spu_Destroy (spu_t * spu)
Destroy the subpicture unit.
Parameters
p_this the parent object which destroys the subpicture unit
References spu_private_t::filter_chain, spu_private_t::filter_chain_current, filter_chain_Delete(), filter_chain_ForEach(), spu_private_t::filter_chain_lock, spu_private_t::filter_chain_update, FilterRelease(), spu_private_t::heap, spu_private_t::lock, spu_t::p, spu_private_t::scale, spu_private_t::scale_yuvp, spu_private_t::source_chain, spu_private_t::source_chain_current, spu_private_t::source_chain_lock, spu_private_t::source_chain_update, SpuHeapClean(), SubFilterDelProxyCallbacks(), SubSourceClean(), SubSourceDelProxyCallbacks(), spu_private_t::text, vlc_mutex_destroy(), vlc_object_release, and spu_private_t::vout.
Referenced by vout_Close(), and VoutCreate().
spu_PutSubpicture()
void spu_PutSubpicture (spu_t * spu, subpicture_t * subpic)
This function sends a subpicture to the spu_t core.
You cannot use the provided subpicture anymore. The spu_t core will destroy it at its convenience.
This function sends a subpicture to the spu_t core.
Remove the reservation flag of a subpicture, which will cause it to be ready for display.
Parameters
spu the subpicture unit object
subpic the subpicture to display
References spu_private_t::filter_chain, filter_chain_AppendFromString(), filter_chain_ForEach(), filter_chain_IsEmpty(), spu_private_t::filter_chain_lock, filter_chain_Reset(), filter_chain_SubFilter(), spu_private_t::filter_chain_update, spu_private_t::heap, subpicture_t::i_channel, spu_private_t::lock, msg_Err, spu_t::p, subpicture_t::p_region, spu_private_t::source_chain_current, spu_private_t::source_chain_update, spu_ClearChannel(), SpuHeapPush(), strdup(), SubFilterAddProxyCallbacks(), SubFilterDelProxyCallbacks(), subpicture_Delete(), vlc_mutex_lock(), vlc_mutex_unlock(), spu_private_t::vout, and VOUT_SPU_CHANNEL_OSD.
Referenced by filter_chain_SubSource(), and ThreadDisplaySubpicture().
spu_RegisterChannel()
int spu_RegisterChannel (spu_t * spu)
It registers a new SPU channel.
References spu_private_t::channel, spu_private_t::lock, spu_t::p, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by SubSourceInit(), and vout_RegisterSubpictureChannel().
spu_Render()
subpicture_t * spu_Render (spu_t * spu, const vlc_fourcc_t * p_chroma_list, const video_format_t * p_fmt_dst, const video_format_t * p_fmt_src, mtime_t render_subtitle_date, mtime_t render_osd_date, bool ignore_osd)
This function will return an unique subpicture containing the OSD and subtitles visibles at the requested date.
Parameters
p_chroma_list is a list of supported chroma for the output (can be NULL)
p_fmt_dst is the format of the picture on which the return subpicture will be rendered.
p_fmt_src is the format of the original(source) video.
The returned value if non NULL must be released by subpicture_Delete().
References subpicture_t::b_subtitle, filter_chain_AppendFromString(), filter_chain_ForEach(), filter_chain_Reset(), filter_chain_SubSource(), video_format_t::i_chroma, spu_private_t::lock, spu_t::p, spu_private_t::source_chain, spu_private_t::source_chain_lock, spu_private_t::source_chain_update, SpuRenderSubpictures(), SpuSelectSubpictures(), subpicture_Update(), SubpictureCmp(), SubSourceAddProxyCallbacks(), SubSourceClean(), SubSourceDelProxyCallbacks(), SubSourceInit(), VLC_CODEC_ARGB, VLC_CODEC_BGRA, VLC_CODEC_RGBA, VLC_CODEC_YUVA, VLC_CODEC_YUVP, vlc_fourcc_IsYUV(), vlc_mutex_lock(), vlc_mutex_unlock(), spu_private_t::vout, and VOUT_MAX_SUBPICTURES.
Referenced by ThreadDisplayRenderPicture().