VLC: Audio output
Audio output
Output
Topics
Audio output volume
Files
file vlc_aout.h
Audio output modules interface.
Data Structures
struct audio_output
Audio output object.
struct aout_filters_cfg_t
Macros
#define AOUT_MAX_ADVANCE_TIME (AOUT_MAX_PREPARE_TIME + CLOCK_FREQ)
#define AOUT_MAX_PREPARE_TIME (2 * CLOCK_FREQ)
#define AOUT_MIN_PREPARE_TIME AOUT_MAX_PTS_ADVANCE
#define AOUT_MAX_PTS_ADVANCE (CLOCK_FREQ / 25)
Maximum advance of actual audio playback time to coded PTS, above which downsampling will be performed.
#define AOUT_MAX_PTS_DELAY (3 * CLOCK_FREQ / 50)
Maximum delay of actual audio playback time from coded PTS, above which upsampling will be performed.
#define AOUT_MAX_RESAMPLING 10
#define AOUT_FMTS_IDENTICAL(p_first, p_second)
#define AOUT_FMTS_SIMILAR(p_first, p_second)
#define AOUT_FMT_LINEAR(p_format) (aout_BitsPerSample((p_format)->i_format) != 0)
#define VLC_CODEC_SPDIFL VLC_FOURCC('s','p','d','i')
#define VLC_CODEC_SPDIFB VLC_FOURCC('s','p','d','b')
#define AOUT_FMT_SPDIF(p_format)
#define AOUT_FMT_HDMI(p_format)
#define AOUT_VAR_CHAN_UNSET 0 /* must be zero */
#define AOUT_VAR_CHAN_STEREO 1
#define AOUT_VAR_CHAN_RSTEREO 2
#define AOUT_VAR_CHAN_LEFT 3
#define AOUT_VAR_CHAN_RIGHT 4
#define AOUT_VAR_CHAN_DOLBYS 5
#define AOUT_VAR_CHAN_HEADPHONES 6
#define AOUT_VAR_CHAN_MONO 7
#define AOUT_SPDIF_SIZE 6144
#define A52_FRAME_NB 1536
#define AOUT_CHAN_REMAP_INIT
#define AOUT_RESTART_FILTERS 0x1
#define AOUT_RESTART_OUTPUT (AOUT_RESTART_FILTERS|0x2)
#define AOUT_RESTART_STEREOMODE (AOUT_RESTART_OUTPUT|0x4)
#define aout_FormatPrint(o, t, f) aout_FormatPrint(VLC_OBJECT(o), t, f)
#define AOUT_VOLUME_DEFAULT 256
#define AOUT_VOLUME_MAX 512
#define AOUT_FILTERS_CFG_INIT
#define aout_FiltersNew(o, inf, outf, rv, remap) aout_FiltersNew(VLC_OBJECT(o),inf,outf,rv,remap)
#define aout_FiltersDelete(o, f) aout_FiltersDelete(VLC_OBJECT(o),f)
Typedefs
typedef struct aout_filters aout_filters_t
typedef struct aout_request_vout aout_request_vout_t
Enumerations
enum vlc_chan_order_idx_t {
AOUT_CHANIDX_DISABLE = -1 , AOUT_CHANIDX_LEFT , AOUT_CHANIDX_RIGHT , AOUT_CHANIDX_MIDDLELEFT ,
AOUT_CHANIDX_MIDDLERIGHT , AOUT_CHANIDX_REARLEFT , AOUT_CHANIDX_REARRIGHT , AOUT_CHANIDX_REARCENTER ,
AOUT_CHANIDX_CENTER , AOUT_CHANIDX_LFE , AOUT_CHANIDX_MAX
}
Functions
unsigned aout_CheckChannelReorder (const uint32_t *, const uint32_t *, uint32_t mask, uint8_t *table)
This function computes the reordering needed to go from pi_chan_order_in to pi_chan_order_out.
void aout_ChannelReorder (void *, size_t, uint8_t, const uint8_t *, vlc_fourcc_t)
void aout_Interleave (void *dst, const void *const *planes, unsigned samples, unsigned channels, vlc_fourcc_t fourcc)
void aout_Deinterleave (void *dst, const void *src, unsigned samples, unsigned channels, vlc_fourcc_t fourcc)
bool aout_CheckChannelExtraction (int *pi_selection, uint32_t *pi_layout, int *pi_channels, const uint32_t pi_order_dst[9], const uint32_t *pi_order_src, int i_channels)
This function will compute the extraction parameter into pi_selection to go from i_channels with their type given by pi_order_src[] into the order describe by pi_order_dst.
void aout_ChannelExtract (void *p_dst, int i_dst_channels, const void *p_src, int i_src_channels, int i_sample_count, const int *pi_selection, int i_bits_per_sample)
Do the actual channels extraction using the parameters created by aout_CheckChannelExtraction.
static unsigned aout_FormatNbChannels (const audio_sample_format_t *fmt)
unsigned int aout_BitsPerSample (vlc_fourcc_t i_format)
void aout_FormatPrepare (audio_sample_format_t *p_format)
void aout_FormatPrint (vlc_object_t *, const char *, const audio_sample_format_t *)
Prints an audio sample format in a human-readable form.
const char * aout_FormatPrintChannels (const audio_sample_format_t *)
float aout_VolumeGet (audio_output_t *)
Gets the volume of the audio output stream (independent of mute).
int aout_VolumeSet (audio_output_t *, float)
Sets the volume of the audio output stream.
int aout_VolumeUpdate (audio_output_t *, int, float *)
Raises the volume.
int aout_MuteGet (audio_output_t *)
Gets the audio output stream mute flag.
int aout_MuteSet (audio_output_t *, bool)
Sets the audio output stream mute flag.
char * aout_DeviceGet (audio_output_t *)
Gets the currently selected device.
int aout_DeviceSet (audio_output_t *, const char *)
Selects an audio output device.
int aout_DevicesList (audio_output_t *, char ***, char ***)
Enumerates possible audio output devices.
static void aout_VolumeReport (audio_output_t *aout, float volume)
Report change of configured audio volume to the core and UI.
static void aout_MuteReport (audio_output_t *aout, bool mute)
Report change of muted flag to the core and UI.
static void aout_PolicyReport (audio_output_t *aout, bool cork)
Report audio policy status.
static void aout_DeviceReport (audio_output_t *aout, const char *id)
Report change of output device.
static void aout_HotplugReport (audio_output_t *aout, const char *id, const char *name)
Report a device hot-plug event.
static int aout_GainRequest (audio_output_t *aout, float gain)
Request a change of software audio amplification.
static void aout_RestartRequest (audio_output_t *aout, unsigned mode)
aout_filters_t * aout_FiltersNew (vlc_object_t *, const audio_sample_format_t *, const audio_sample_format_t *, const aout_request_vout_t *, const aout_filters_cfg_t *cfg)
void aout_FiltersDelete (vlc_object_t *, aout_filters_t *)
Destroys a chain of audio filters.
bool aout_FiltersAdjustResampling (aout_filters_t *, int)
block_t * aout_FiltersPlay (aout_filters_t *, block_t *, int rate)
block_t * aout_FiltersDrain (aout_filters_t *)
void aout_FiltersFlush (aout_filters_t *)
void aout_FiltersChangeViewpoint (aout_filters_t *, const vlc_viewpoint_t *vp)
vout_thread_t * aout_filter_RequestVout (filter_t *, vout_thread_t *p_vout, const video_format_t *p_fmt)
Variables
static const uint32_t pi_vlc_chan_order_wg4 []
It describes the audio channel order VLC expect.
Detailed Description
Macro Definition Documentation
A52_FRAME_NB
#define A52_FRAME_NB 1536
AOUT_CHAN_REMAP_INIT
#define AOUT_CHAN_REMAP_INIT
Value:
    { \
    AOUT_CHANIDX_LEFT,  \
    AOUT_CHANIDX_RIGHT, \
    AOUT_CHANIDX_MIDDLELEFT, \
    AOUT_CHANIDX_MIDDLERIGHT, \
    AOUT_CHANIDX_REARLEFT, \
    AOUT_CHANIDX_REARRIGHT, \
    AOUT_CHANIDX_REARCENTER, \
    AOUT_CHANIDX_CENTER, \
    AOUT_CHANIDX_LFE, \
}
AOUT_FILTERS_CFG_INIT
#define AOUT_FILTERS_CFG_INIT
Value:
    (aout_filters_cfg_t) \
    { .remap = AOUT_CHAN_REMAP_INIT, \
      .headphones = false, \
    };
Referenced by aout_CheckReady(), and aout_DecNew().
aout_FiltersDelete
#define aout_FiltersDelete (o, f) aout_FiltersDelete(VLC_OBJECT(o),f)
Referenced by aout_CheckReady(), and aout_DecDelete().
aout_FiltersNew
#define aout_FiltersNew (o, inf, outf, rv, remap) aout_FiltersNew(VLC_OBJECT(o),inf,outf,rv,remap)
Referenced by aout_CheckReady(), and aout_DecNew().
AOUT_FMT_HDMI
#define AOUT_FMT_HDMI (p_format)
Value:
    ( (p_format)->i_format == VLC_CODEC_EAC3        \
    ||(p_format)->i_format == VLC_CODEC_TRUEHD      \
    ||(p_format)->i_format == VLC_CODEC_MLP         \
    )
AOUT_FMT_LINEAR
#define AOUT_FMT_LINEAR (p_format) (aout_BitsPerSample((p_format)->i_format) != 0)
Referenced by aout_FiltersNew(), aout_FiltersPipelineCreate(), aout_OutputNew(), and aout_PrepareStereoMode().
AOUT_FMT_SPDIF
#define AOUT_FMT_SPDIF (p_format)
Value:
    ( ((p_format)->i_format == VLC_CODEC_SPDIFL)       \
       || ((p_format)->i_format == VLC_CODEC_SPDIFB)   \
       || ((p_format)->i_format == VLC_CODEC_A52)      \
       || ((p_format)->i_format == VLC_CODEC_DTS) )
AOUT_FMTS_IDENTICAL
#define AOUT_FMTS_IDENTICAL (p_first, p_second)
Value:
    (                          \
    ((p_first)->i_format == (p_second)->i_format)                           \
      && AOUT_FMTS_SIMILAR(p_first, p_second) )
Referenced by aout_FiltersNew(), aout_update_format(), and CreateFilter().
AOUT_FMTS_SIMILAR
#define AOUT_FMTS_SIMILAR (p_first, p_second)
Value:
    (                            \
    ((p_first)->i_rate == (p_second)->i_rate)                               \
      && ((p_first)->channel_type == (p_second)->channel_type)            \
      && ((p_first)->i_physical_channels == (p_second)->i_physical_channels)\
      && ((p_first)->i_chan_mode == (p_second)->i_chan_mode) )
aout_FormatPrint
#define aout_FormatPrint (o, t, f) aout_FormatPrint(VLC_OBJECT(o), t, f)
Referenced by aout_FiltersNew(), and aout_OutputNew().
AOUT_MAX_ADVANCE_TIME
#define AOUT_MAX_ADVANCE_TIME (AOUT_MAX_PREPARE_TIME + CLOCK_FREQ)
Referenced by aout_DecPlay(), and DecoderPlayAudio().
AOUT_MAX_PREPARE_TIME
#define AOUT_MAX_PREPARE_TIME (2 * CLOCK_FREQ)
Referenced by DecoderPlayAudio().
AOUT_MAX_PTS_ADVANCE
#define AOUT_MAX_PTS_ADVANCE (CLOCK_FREQ / 25)
Maximum advance of actual audio playback time to coded PTS, above which downsampling will be performed.
Referenced by aout_DecSynchronize().
AOUT_MAX_PTS_DELAY
#define AOUT_MAX_PTS_DELAY (3 * CLOCK_FREQ / 50)
Maximum delay of actual audio playback time from coded PTS, above which upsampling will be performed.
Referenced by aout_DecPlay(), and aout_DecSynchronize().
AOUT_MAX_RESAMPLING
#define AOUT_MAX_RESAMPLING 10
AOUT_MIN_PREPARE_TIME
#define AOUT_MIN_PREPARE_TIME AOUT_MAX_PTS_ADVANCE
AOUT_RESTART_FILTERS
#define AOUT_RESTART_FILTERS 0x1
Referenced by aout_InputRequestRestart().
AOUT_RESTART_OUTPUT
#define AOUT_RESTART_OUTPUT (AOUT_RESTART_FILTERS|0x2)
Referenced by aout_CheckReady().
AOUT_RESTART_STEREOMODE
#define AOUT_RESTART_STEREOMODE (AOUT_RESTART_OUTPUT|0x4)
Referenced by StereoModeCallback().
AOUT_SPDIF_SIZE
#define AOUT_SPDIF_SIZE 6144
AOUT_VAR_CHAN_DOLBYS
#define AOUT_VAR_CHAN_DOLBYS 5
Referenced by aout_PrepareStereoMode().
AOUT_VAR_CHAN_HEADPHONES
#define AOUT_VAR_CHAN_HEADPHONES 6
Referenced by aout_PrepareStereoMode().
AOUT_VAR_CHAN_LEFT
#define AOUT_VAR_CHAN_LEFT 3
Referenced by aout_OutputNew(), and aout_PrepareStereoMode().
AOUT_VAR_CHAN_MONO
#define AOUT_VAR_CHAN_MONO 7
Referenced by aout_PrepareStereoMode().
AOUT_VAR_CHAN_RIGHT
#define AOUT_VAR_CHAN_RIGHT 4
Referenced by aout_OutputNew(), and aout_PrepareStereoMode().
AOUT_VAR_CHAN_RSTEREO
#define AOUT_VAR_CHAN_RSTEREO 2
Referenced by aout_PrepareStereoMode().
AOUT_VAR_CHAN_STEREO
#define AOUT_VAR_CHAN_STEREO 1
Referenced by aout_PrepareStereoMode().
AOUT_VAR_CHAN_UNSET
#define AOUT_VAR_CHAN_UNSET 0 /* must be zero */
Referenced by aout_OutputNew(), and aout_PrepareStereoMode().
AOUT_VOLUME_DEFAULT
#define AOUT_VOLUME_DEFAULT 256
Referenced by aout_VolumeUpdate().
AOUT_VOLUME_MAX
#define AOUT_VOLUME_MAX 512
VLC_CODEC_SPDIFB
#define VLC_CODEC_SPDIFB VLC_FOURCC('s','p','d','b')
VLC_CODEC_SPDIFL
#define VLC_CODEC_SPDIFL VLC_FOURCC('s','p','d','i')
Typedef Documentation
aout_filters_t
typedef struct aout_filters aout_filters_t
aout_request_vout_t
typedef struct aout_request_vout aout_request_vout_t
Enumeration Type Documentation
vlc_chan_order_idx_t
enum vlc_chan_order_idx_t
Enumerator
AOUT_CHANIDX_DISABLE
AOUT_CHANIDX_LEFT
AOUT_CHANIDX_RIGHT
AOUT_CHANIDX_MIDDLELEFT
AOUT_CHANIDX_MIDDLERIGHT
AOUT_CHANIDX_REARLEFT
AOUT_CHANIDX_REARRIGHT
AOUT_CHANIDX_REARCENTER
AOUT_CHANIDX_CENTER
AOUT_CHANIDX_LFE
AOUT_CHANIDX_MAX
Function Documentation
aout_BitsPerSample()
unsigned int aout_BitsPerSample (vlc_fourcc_t i_format)
References AUDIO_ES, VLC_CODEC_ALAW, VLC_CODEC_F32B, VLC_CODEC_F32L, VLC_CODEC_F64B, VLC_CODEC_F64L, VLC_CODEC_MULAW, VLC_CODEC_S16B, VLC_CODEC_S16L, VLC_CODEC_S24B, VLC_CODEC_S24B32, VLC_CODEC_S24L, VLC_CODEC_S24L32, VLC_CODEC_S32B, VLC_CODEC_S32L, VLC_CODEC_S8, VLC_CODEC_U16B, VLC_CODEC_U16L, VLC_CODEC_U24B, VLC_CODEC_U24L, VLC_CODEC_U32B, VLC_CODEC_U32L, VLC_CODEC_U8, and vlc_fourcc_GetCodec().
Referenced by aout_ChannelReorder(), aout_FormatPrepare(), and EsOutUpdateInfo().
aout_ChannelExtract()
void aout_ChannelExtract (void * p_dst, int i_dst_channels, const void * p_src, int i_src_channels, int i_sample_count, const int * pi_selection, int i_bits_per_sample)
Do the actual channels extraction using the parameters created by aout_CheckChannelExtraction.
XXX this function does not work in place (p_dst and p_src must not overlap). XXX Only 8, 16, 32, 64 bits per sample are supported.
References ExtractChannel().
aout_ChannelReorder()
void aout_ChannelReorder (void * , size_t , uint8_t , const uint8_t * , vlc_fourcc_t)
aout_CheckChannelExtraction()
bool aout_CheckChannelExtraction (int * pi_selection, uint32_t * pi_layout, int * pi_channels, const uint32_t pi_order_dst[9], const uint32_t * pi_order_src, int i_channels)
This function will compute the extraction parameter into pi_selection to go from i_channels with their type given by pi_order_src[] into the order describe by pi_order_dst.
It will also set :
*pi_channels as the number of channels that will be extracted which is lower (in case of non understood channels type) or equal to i_channels.
the layout of the channels (*pi_layout).
It will return true if channel extraction is really needed, in which case aout_ChannelExtract must be used
XXX It must be used when the source may have channel type not understood by VLC. In this case the channel type pi_order_src[] must be set to 0. XXX It must also be used if multiple channels have the same type.
References AOUT_CHAN_MAX, and pi_vlc_chan_order_wg4.
aout_CheckChannelReorder()
unsigned aout_CheckChannelReorder (const uint32_t * , const uint32_t * , uint32_t mask, uint8_t * table)
This function computes the reordering needed to go from pi_chan_order_in to pi_chan_order_out.
If pi_chan_order_in or pi_chan_order_out is NULL, it will assume that vlc internal (WG4) order is requested.
aout_Deinterleave()
void aout_Deinterleave (void * dst, const void * src, unsigned samples, unsigned channels, vlc_fourcc_t fourcc)
aout_DeviceGet()
char * aout_DeviceGet (audio_output_t * aout)
Gets the currently selected device.
Returns
the selected device ID (caller must free() it) NULL if no device is selected or in case of error.
References var_GetNonEmptyString.
aout_DeviceReport()
static void aout_DeviceReport (audio_output_t * aout, const char * id) inline static
Report change of output device.
References device_report, and event.
aout_DeviceSet()
int aout_DeviceSet (audio_output_t * aout, const char * id)
Selects an audio output device.
Parameters
id device ID to select, or NULL for the default device
Returns
zero on success, non-zero on error (TODO).
References aout_OutputTryLock(), aout_OutputUnlock(), aout_owner(), aout_owner_t::device, aout_owner_t::lock, aout_owner_t::req, strdup(), unlikely, unset_str, vlc_mutex_lock(), and vlc_mutex_unlock().
aout_DevicesList()
int aout_DevicesList (audio_output_t * aout, char *** ids, char *** names)
Enumerates possible audio output devices.
The function will heap-allocate two tables of heap-allocated strings; the caller is responsible for freeing all strings and both tables.
Parameters
ids pointer to a table of device identifiers [OUT]
names pointer to a table of device human-readable descriptions [OUT]
Returns
the number of devices, or negative on error.
Note
In case of error, *ids and *names are undefined.
References aout_owner(), aout_owner_t::count, aout_owner_t::dev, aout_owner_t::list, aout_owner_t::lock, strdup(), unlikely, vlc_alloc(), vlc_mutex_lock(), and vlc_mutex_unlock().
aout_filter_RequestVout()
vout_thread_t * aout_filter_RequestVout (filter_t * filter, vout_thread_t * p_vout, const video_format_t * p_fmt)
References filter_t::obj, filter_t::owner, aout_request_vout::p_private, vlc_common_members::parent, aout_request_vout::pf_request_vout, filter_owner_t::sys, and var_InheritString.
aout_FiltersAdjustResampling()
bool aout_FiltersAdjustResampling (aout_filters_t * filters, int adjust)
References aout_filters::resampler, and aout_filters::resampling.
Referenced by aout_DecSynchronize(), and aout_StopResampling().
aout_FiltersChangeViewpoint()
void aout_FiltersChangeViewpoint (aout_filters_t * filters, const vlc_viewpoint_t * vp)
References aout_FiltersPipelineChangeViewpoint(), aout_filters::count, and aout_filters::tab.
Referenced by aout_DecPlay().
aout_FiltersDelete()
void aout_FiltersDelete (vlc_object_t * obj, aout_filters_t * filters)
Destroys a chain of audio filters.
Parameters
obj object used with aout_FiltersNew()
filters chain to be destroyed
Bug
obj must be NULL iff request_vout was NULL in aout_FiltersNew() (this implies obj is an audio_output_t pointer if non NULL).
References aout_FiltersPipelineDestroy(), aout_filters::count, aout_filters::resampler, aout_filters::tab, var_DelCallback, and VisualizationCallback().
aout_FiltersDrain()
block_t * aout_FiltersDrain (aout_filters_t * filters)
References aout_FiltersPipelineDrain(), aout_FiltersPipelinePlay(), es_format_t::audio, block_ChainAppend(), block_ChainGather(), aout_filters::count, filter_t::fmt_in, audio_format_t::i_rate, aout_filters::resampler, aout_filters::resampling, and aout_filters::tab.
Referenced by aout_DecFlush().
aout_FiltersFlush()
void aout_FiltersFlush (aout_filters_t * filters)
References aout_FiltersPipelineFlush(), aout_filters::count, aout_filters::resampler, and aout_filters::tab.
Referenced by aout_DecFlush().
aout_FiltersNew()
aout_filters_t * aout_FiltersNew (vlc_object_t * , const audio_sample_format_t * , const audio_sample_format_t * , const aout_request_vout_t * , const aout_filters_cfg_t * cfg)
aout_FiltersPlay()
block_t * aout_FiltersPlay (aout_filters_t * filters, block_t * block, int rate)
References aout_FiltersPipelinePlay(), es_format_t::audio, block_Release(), aout_filters::count, filter_t::fmt_in, audio_format_t::i_rate, INPUT_RATE_DEFAULT, aout_filters::rate_filter, aout_filters::resampler, aout_filters::resampling, and aout_filters::tab.
Referenced by aout_DecPlay().
aout_FormatNbChannels()
static unsigned aout_FormatNbChannels (const audio_sample_format_t * fmt) inline static
References audio_format_t::i_physical_channels, and popcount().
Referenced by aout_DecNew(), aout_FiltersNew(), aout_FormatPrepare(), aout_OutputNew(), and CreateFilter().
aout_FormatPrepare()
void aout_FormatPrepare (audio_sample_format_t * p_format)
References aout_BitsPerSample(), aout_FormatNbChannels(), audio_format_t::i_bitspersample, audio_format_t::i_bytes_per_frame, audio_format_t::i_channels, audio_format_t::i_format, and audio_format_t::i_frame_length.
Referenced by aout_FiltersNew(), aout_FiltersPipelineCreate(), aout_OutputNew(), aout_SetWavePhysicalChannels(), aout_update_format(), and TryFormat().
aout_FormatPrint()
void aout_FormatPrint (vlc_object_t * obj, const char * psz_text, const audio_sample_format_t * p_format)
Prints an audio sample format in a human-readable form.
References aout_FormatPrintChannels(), audio_format_t::i_bytes_per_frame, audio_format_t::i_format, audio_format_t::i_frame_length, audio_format_t::i_rate, and msg_Dbg.
aout_FormatPrintChannels()
const char * aout_FormatPrintChannels (const audio_sample_format_t * p_format)
References AOUT_CHAN_CENTER, AOUT_CHAN_LEFT, AOUT_CHAN_LFE, AOUT_CHAN_MIDDLELEFT, AOUT_CHAN_MIDDLERIGHT, AOUT_CHAN_REARCENTER, AOUT_CHAN_REARLEFT, AOUT_CHAN_REARRIGHT, AOUT_CHAN_RIGHT, AOUT_CHANMODE_DOLBYSTEREO, AOUT_CHANMODE_DUALMONO, AUDIO_CHANNEL_TYPE_AMBISONICS, audio_format_t::channel_type, audio_format_t::i_chan_mode, and audio_format_t::i_physical_channels.
Referenced by aout_FormatPrint(), aout_FormatsPrint(), and EsOutUpdateInfo().
aout_GainRequest()
static int aout_GainRequest (audio_output_t * aout, float gain) inline static
Request a change of software audio amplification.
Parameters
gain linear amplitude gain (must be positive)
Warning
Values in excess 1.0 may cause overflow and distorsion.
References event, and gain_request.
aout_HotplugReport()
static void aout_HotplugReport (audio_output_t * aout, const char * id, const char * name) inline static
Report a device hot-plug event.
Parameters
id device ID
name human-readable device name (NULL for hot unplug)
References event, hotplug_report, and name.
aout_Interleave()
void aout_Interleave (void * dst, const void *const * planes, unsigned samples, unsigned channels, vlc_fourcc_t fourcc)
aout_MuteGet()
int aout_MuteGet (audio_output_t * aout)
Gets the audio output stream mute flag.
Returns
0 if not muted, 1 if muted, -1 if undefined.
References var_InheritBool.
Referenced by playlist_MuteGet().
aout_MuteReport()
static void aout_MuteReport (audio_output_t * aout, bool mute) inline static
Report change of muted flag to the core and UI.
References event, and mute_report.
aout_MuteSet()
int aout_MuteSet (audio_output_t * aout, bool mute)
Sets the audio output stream mute flag.
Returns
0 on success, -1 on failure (TODO).
References aout_OutputTryLock(), aout_OutputUnlock(), aout_owner(), aout_owner_t::lock, aout_owner_t::mute, aout_owner_t::req, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by playlist_MuteSet().
aout_PolicyReport()
static void aout_PolicyReport (audio_output_t * aout, bool cork) inline static
Report audio policy status.
Parameters
cork true to request a cork, false to undo any pending cork.
References event, and policy_report.
aout_RestartRequest()
static void aout_RestartRequest (audio_output_t * aout, unsigned mode) inline static
References event, and restart_request.
Referenced by StereoModeCallback().
aout_VolumeGet()
float aout_VolumeGet (audio_output_t * aout)
Gets the volume of the audio output stream (independent of mute).
Returns
Current audio volume (0. = silent, 1. = nominal), or a strictly negative value if undefined.
References var_GetFloat.
Referenced by aout_VolumeUpdate(), playlist_VolumeGet(), and vlc_strfinput().
aout_VolumeReport()
static void aout_VolumeReport (audio_output_t * aout, float volume) inline static
Report change of configured audio volume to the core and UI.
References event, and volume_report.
aout_VolumeSet()
int aout_VolumeSet (audio_output_t * aout, float vol)
Sets the volume of the audio output stream.
Note
The mute status is not changed.
Returns
0 on success, -1 on failure (TODO).
References aout_OutputTryLock(), aout_OutputUnlock(), aout_owner(), aout_owner_t::lock, aout_owner_t::req, vlc_mutex_lock(), vlc_mutex_unlock(), and aout_owner_t::volume.
Referenced by aout_VolumeUpdate(), and playlist_VolumeSet().
aout_VolumeUpdate()
int aout_VolumeUpdate (audio_output_t * aout, int value, float * volp)
Raises the volume.
Parameters
value how much to increase (> 0) or decrease (< 0) the volume
volp if non-NULL, will contain contain the resulting volume
References AOUT_VOLUME_DEFAULT, aout_VolumeGet(), aout_VolumeSet(), and var_InheritFloat.
Referenced by ControlNav(), and playlist_VolumeUp().
Variable Documentation
pi_vlc_chan_order_wg4
const uint32_t pi_vlc_chan_order_wg4[] static
Initial value:
=
{
    0x2 , 0x4 ,
    0x100 , 0x200 ,
    0x20 , 0x40 , 0x10 ,
    0x1 , 0x1000 , 0
}
It describes the audio channel order VLC expect.
Referenced by aout_CheckChannelExtraction(), and aout_CheckChannelReorder().