VLC: VLC dialog
VLC dialog
Interface
Topics
VLC dialog functions
In order to interact with the user
VLC dialog callbacks
Need to be implemented by GUI modules or libvlc
VLC extension dialog functions
Files
file vlc_dialog.h
This file declares VLC dialog functions.
Data Structures
struct vlc_dialog_provider
Variables
void(* vlc_dialog_cbs::pf_display_error)(void *p_data, const char *psz_title, const char *psz_text)
Called when an error message needs to be displayed.
void(* vlc_dialog_cbs::pf_display_login)(void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, const char *psz_default_username, bool b_ask_store)
Called when a login dialog needs to be displayed.
void(* vlc_dialog_cbs::pf_display_question)(void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2)
Called when a question dialog needs to be displayed.
void(* vlc_dialog_cbs::pf_display_progress)(void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, bool b_indeterminate, float f_position, const char *psz_cancel)
Called when a progress dialog needs to be displayed.
void(* vlc_dialog_cbs::pf_cancel)(void *p_data, vlc_dialog_id *p_id)
Called when a displayed dialog needs to be cancelled.
void(* vlc_dialog_cbs::pf_update_progress)(void *p_data, vlc_dialog_id *p_id, float f_position, const char *psz_text)
Called when a progress dialog needs to be updated.
Detailed Description
Variable Documentation
pf_cancel
void(* vlc_dialog_cbs::pf_cancel) (void *p_data, vlc_dialog_id *p_id)
Called when a displayed dialog needs to be cancelled.
The implementation must call vlc_dialog_id_dismiss() to really release the dialog.
Parameters
p_data opaque pointer for the callback
p_id id of the dialog
Referenced by dialog_cancel_locked(), dialog_display_login_va(), dialog_display_question_va(), and display_progress_va().
pf_display_error
void(* vlc_dialog_cbs::pf_display_error) (void *p_data, const char *psz_title, const char *psz_text)
Called when an error message needs to be displayed.
Parameters
p_data opaque pointer for the callback
psz_title title of the dialog
psz_text text of the dialog
Referenced by dialog_display_error_va().
pf_display_login
void(* vlc_dialog_cbs::pf_display_login) (void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, const char *psz_default_username, bool b_ask_store)
Called when a login dialog needs to be displayed.
You can interact with this dialog by calling vlc_dialog_id_post_login() to post an answer or vlc_dialog_id_dismiss() to cancel this dialog.
Note
to receive this callback, vlc_dialog_cbs.pf_cancel should not be NULL.
Parameters
p_data opaque pointer for the callback
p_id id used to interact with the dialog
psz_title title of the dialog
psz_text text of the dialog
psz_default_username user name that should be set on the user form
b_ask_store if true, ask the user if he wants to save the credentials
Referenced by dialog_display_login_va().
pf_display_progress
void(* vlc_dialog_cbs::pf_display_progress) (void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, bool b_indeterminate, float f_position, const char *psz_cancel)
Called when a progress dialog needs to be displayed.
If cancellable (psz_cancel != NULL), you can cancel this dialog by calling vlc_dialog_id_dismiss()
Note
to receive this callback, vlc_dialog_cbs.pf_cancel and vlc_dialog_cbs.pf_update_progress should not be NULL.
Parameters
p_data opaque pointer for the callback
p_id id used to interact with the dialog
psz_title title of the dialog
psz_text text of the dialog
b_indeterminate true if the progress dialog is indeterminate
f_position initial position of the progress bar (between 0.0 and 1.0)
psz_cancel text of the cancel button, if NULL the dialog is not cancellable
Referenced by display_progress_va().
pf_display_question
void(* vlc_dialog_cbs::pf_display_question) (void *p_data, vlc_dialog_id *p_id, const char *psz_title, const char *psz_text, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2)
Called when a question dialog needs to be displayed.
You can interact with this dialog by calling vlc_dialog_id_post_action() to post an answer or vlc_dialog_id_dismiss() to cancel this dialog.
Note
to receive this callback, vlc_dialog_cbs.pf_cancel should not be NULL.
Parameters
p_data opaque pointer for the callback
p_id id used to interact with the dialog
psz_title title of the dialog
psz_text text of the dialog
i_type question type (or severity) of the dialog
psz_cancel text of the cancel button
psz_action1 text of the first button, if NULL, don't display this button
psz_action2 text of the second button, if NULL, don't display this button
Referenced by dialog_display_question_va().
pf_update_progress
void(* vlc_dialog_cbs::pf_update_progress) (void *p_data, vlc_dialog_id *p_id, float f_position, const char *psz_text)
Called when a progress dialog needs to be updated.
Parameters
p_data opaque pointer for the callback
p_id id of the dialog
f_position osition of the progress bar (between 0.0 and 1.0)
psz_text new text of the progress dialog
Referenced by dialog_update_progress(), and display_progress_va().