VLC: Video output display
Video output display
Output » Video output
Video output display: output buffers and rendering
Files
file vlc_vout_display.h
Video output display modules interface.
Data Structures
struct vout_display_cfg_t
Initial/Current configuration for a vout_display_t.
struct vout_display_info_t
Information from a vout_display_t to configure the core behaviour.
struct vout_display_owner_t
Vout owner structures.
struct vout_display_t
struct vout_display_place_t
Structure used to store the result of a vout_display_PlacePicture.
Typedefs
typedef struct vout_display_t vout_display_t
typedef struct vout_display_sys_t vout_display_sys_t
typedef struct vout_display_owner_t vout_display_owner_t
Enumerations
enum vout_display_align_t {
VOUT_DISPLAY_ALIGN_CENTER , VOUT_DISPLAY_ALIGN_LEFT , VOUT_DISPLAY_ALIGN_RIGHT , VOUT_DISPLAY_ALIGN_TOP ,
VOUT_DISPLAY_ALIGN_BOTTOM
}
Possible alignments for vout_display.
enum { VOUT_WINDOW_STATE_NORMAL =0 , VOUT_WINDOW_STATE_ABOVE =1 , VOUT_WINDOW_STATE_BELOW =2 , VOUT_WINDOW_STACK_MASK =3 }
Window management state.
enum {
VOUT_DISPLAY_HIDE_MOUSE , VOUT_DISPLAY_RESET_PICTURES , VOUT_DISPLAY_CHANGE_DISPLAY_SIZE , VOUT_DISPLAY_CHANGE_DISPLAY_FILLED ,
VOUT_DISPLAY_CHANGE_ZOOM , VOUT_DISPLAY_CHANGE_SOURCE_ASPECT , VOUT_DISPLAY_CHANGE_SOURCE_CROP , VOUT_DISPLAY_CHANGE_VIEWPOINT
}
Control query for vout_display_t.
enum {
VOUT_DISPLAY_EVENT_PICTURES_INVALID , VOUT_DISPLAY_EVENT_DISPLAY_SIZE , VOUT_DISPLAY_EVENT_CLOSE , VOUT_DISPLAY_EVENT_KEY ,
VOUT_DISPLAY_EVENT_MOUSE_STATE , VOUT_DISPLAY_EVENT_MOUSE_MOVED , VOUT_DISPLAY_EVENT_MOUSE_PRESSED , VOUT_DISPLAY_EVENT_MOUSE_RELEASED ,
VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK , VOUT_DISPLAY_EVENT_VIEWPOINT_MOVED
}
Event from vout_display_t.
Functions
static void vout_display_SendEvent (vout_display_t *vd, int query,...)
static void vout_display_SendEventDisplaySize (vout_display_t *vd, int width, int height)
static void vout_display_SendEventPicturesInvalid (vout_display_t *vd)
static void vout_display_SendEventClose (vout_display_t *vd)
static void vout_display_SendEventKey (vout_display_t *vd, int key)
static void vout_display_SendEventMouseState (vout_display_t *vd, int x, int y, int button_mask)
static void vout_display_SendEventMouseMoved (vout_display_t *vd, int x, int y)
static void vout_display_SendEventMousePressed (vout_display_t *vd, int button)
static void vout_display_SendEventMouseReleased (vout_display_t *vd, int button)
static void vout_display_SendEventMouseDoubleClick (vout_display_t *vd)
static void vout_display_SendEventViewpointMoved (vout_display_t *vd, const vlc_viewpoint_t *vp)
static vout_window_t * vout_display_NewWindow (vout_display_t *vd, unsigned type)
Asks for a new window of a given type.
static void vout_display_DeleteWindow (vout_display_t *vd, vout_window_t *window)
Deletes a window created by vout_display_NewWindow if window is non NULL or any unused windows otherwise.
static bool vout_display_IsWindowed (vout_display_t *vd)
void vout_display_GetDefaultDisplaySize (unsigned *width, unsigned *height, const video_format_t *source, const vout_display_cfg_t *)
Computes the default display size given the source and the display configuration.
void vout_display_PlacePicture (vout_display_place_t *place, const video_format_t *source, const vout_display_cfg_t *cfg, bool do_clipping)
Computes how to place a picture inside the display to respect the given parameters.
void vout_display_SendMouseMovedDisplayCoordinates (vout_display_t *vd, video_orientation_t orient_display, int m_x, int m_y, vout_display_place_t *place)
Helper function that applies the necessary transforms to the mouse position and then calls vout_display_SendEventMouseMoved.
Detailed Description
Video output display: output buffers and rendering
Typedef Documentation
vout_display_owner_t
typedef struct vout_display_owner_t vout_display_owner_t
vout_display_sys_t
typedef struct vout_display_sys_t vout_display_sys_t
vout_display_t
typedef struct vout_display_t vout_display_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Window management state.
Enumerator
VOUT_WINDOW_STATE_NORMAL
VOUT_WINDOW_STATE_ABOVE
VOUT_WINDOW_STATE_BELOW
VOUT_WINDOW_STACK_MASK
anonymous enum
anonymous enum
Control query for vout_display_t.
Enumerator
VOUT_DISPLAY_HIDE_MOUSE
VOUT_DISPLAY_RESET_PICTURES
VOUT_DISPLAY_CHANGE_DISPLAY_SIZE
VOUT_DISPLAY_CHANGE_DISPLAY_FILLED
VOUT_DISPLAY_CHANGE_ZOOM
VOUT_DISPLAY_CHANGE_SOURCE_ASPECT
VOUT_DISPLAY_CHANGE_SOURCE_CROP
VOUT_DISPLAY_CHANGE_VIEWPOINT
anonymous enum
anonymous enum
Event from vout_display_t.
Events modifiying the state may be sent multiple times. Only the transition will be retained and acted upon.
Enumerator
VOUT_DISPLAY_EVENT_PICTURES_INVALID
VOUT_DISPLAY_EVENT_DISPLAY_SIZE
VOUT_DISPLAY_EVENT_CLOSE
VOUT_DISPLAY_EVENT_KEY
VOUT_DISPLAY_EVENT_MOUSE_STATE
VOUT_DISPLAY_EVENT_MOUSE_MOVED
VOUT_DISPLAY_EVENT_MOUSE_PRESSED
VOUT_DISPLAY_EVENT_MOUSE_RELEASED
VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK
VOUT_DISPLAY_EVENT_VIEWPOINT_MOVED
vout_display_align_t
enum vout_display_align_t
Possible alignments for vout_display.
Enumerator
VOUT_DISPLAY_ALIGN_CENTER
VOUT_DISPLAY_ALIGN_LEFT
VOUT_DISPLAY_ALIGN_RIGHT
VOUT_DISPLAY_ALIGN_TOP
VOUT_DISPLAY_ALIGN_BOTTOM
Function Documentation
vout_display_DeleteWindow()
static void vout_display_DeleteWindow (vout_display_t * vd, vout_window_t * window) inline static
Deletes a window created by vout_display_NewWindow if window is non NULL or any unused windows otherwise.
References vout_display_t::owner, and vout_display_owner_t::window_del.
Referenced by vout_display_IsWindowed().
vout_display_GetDefaultDisplaySize()
void vout_display_GetDefaultDisplaySize (unsigned * width, unsigned * height, const video_format_t * source, const vout_display_cfg_t * cfg)
Computes the default display size given the source and the display configuration.
This asssumes that the picture is already cropped.
References vlc_rational_t::den, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_display_cfg_t::height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, vlc_rational_t::num, vout_display_cfg_t::num, ORIENT_IS_SWAP, video_format_t::orientation, vout_display_cfg_t::sar, vout_display_cfg_t::width, and vout_display_cfg_t::zoom.
Referenced by DisplayNew(), vout_display_PlacePicture(), and VoutDisplayFitWindow().
vout_display_IsWindowed()
static bool vout_display_IsWindowed (vout_display_t * vd) inline static
References vout_display_DeleteWindow(), vout_display_NewWindow(), and VOUT_WINDOW_TYPE_INVALID.
vout_display_NewWindow()
static vout_window_t * vout_display_NewWindow (vout_display_t * vd, unsigned type) inline static
Asks for a new window of a given type.
References vout_display_t::owner, and vout_display_owner_t::window_new.
Referenced by vout_display_IsWindowed().
vout_display_PlacePicture()
void vout_display_PlacePicture (vout_display_place_t * place, const video_format_t * source, const vout_display_cfg_t * cfg, bool do_clipping)
Computes how to place a picture inside the display to respect the given parameters.
This assumes that cropping is done by an external mean.
Parameters
p_place Place inside the window (window pixel unit)
p_source Video source format
p_cfg Display configuration
b_clip If true, prevent the video to go outside the display (break zoom).
References vout_display_cfg_t::align, vlc_rational_t::den, vout_display_cfg_t::display, vout_display_cfg_t::height, vout_display_place_t::height, vout_display_cfg_t::horizontal, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, vout_display_cfg_t::is_display_filled, vlc_rational_t::num, video_format_t::projection_mode, PROJECTION_MODE_RECTANGULAR, vout_display_cfg_t::sar, vout_display_cfg_t::vertical, video_format_ApplyRotation(), VOUT_DISPLAY_ALIGN_BOTTOM, VOUT_DISPLAY_ALIGN_LEFT, VOUT_DISPLAY_ALIGN_RIGHT, VOUT_DISPLAY_ALIGN_TOP, vout_display_GetDefaultDisplaySize(), vout_display_cfg_t::width, vout_display_place_t::width, vout_display_place_t::x, and vout_display_place_t::y.
Referenced by ThreadChangeWindowMouse(), and ThreadDisplayRenderPicture().
vout_display_SendEvent()
static void vout_display_SendEvent (vout_display_t * vd, int query, ...) inline static
References vout_display_owner_t::event, and vout_display_t::owner.
Referenced by vout_display_SendEventClose(), vout_display_SendEventDisplaySize(), vout_display_SendEventKey(), vout_display_SendEventMouseDoubleClick(), vout_display_SendEventMouseMoved(), vout_display_SendEventMousePressed(), vout_display_SendEventMouseReleased(), vout_display_SendEventMouseState(), vout_display_SendEventPicturesInvalid(), and vout_display_SendEventViewpointMoved().
vout_display_SendEventClose()
static void vout_display_SendEventClose (vout_display_t * vd) inline static
References VOUT_DISPLAY_EVENT_CLOSE, and vout_display_SendEvent().
vout_display_SendEventDisplaySize()
static void vout_display_SendEventDisplaySize (vout_display_t * vd, int width, int height) inline static
References VOUT_DISPLAY_EVENT_DISPLAY_SIZE, and vout_display_SendEvent().
Referenced by vout_display_window_Attach(), vout_display_window_ResizeNotify(), and vout_SetDisplayWindowSize().
vout_display_SendEventKey()
static void vout_display_SendEventKey (vout_display_t * vd, int key) inline static
References VOUT_DISPLAY_EVENT_KEY, and vout_display_SendEvent().
vout_display_SendEventMouseDoubleClick()
static void vout_display_SendEventMouseDoubleClick (vout_display_t * vd) inline static
References VOUT_DISPLAY_EVENT_MOUSE_DOUBLE_CLICK, and vout_display_SendEvent().
Referenced by ThreadChangeWindowMouse().
vout_display_SendEventMouseMoved()
static void vout_display_SendEventMouseMoved (vout_display_t * vd, int x, int y) inline static
References VOUT_DISPLAY_EVENT_MOUSE_MOVED, and vout_display_SendEvent().
Referenced by ThreadChangeWindowMouse(), and vout_display_SendMouseMovedDisplayCoordinates().
vout_display_SendEventMousePressed()
static void vout_display_SendEventMousePressed (vout_display_t * vd, int button) inline static
References VOUT_DISPLAY_EVENT_MOUSE_PRESSED, and vout_display_SendEvent().
Referenced by ThreadChangeWindowMouse().
vout_display_SendEventMouseReleased()
static void vout_display_SendEventMouseReleased (vout_display_t * vd, int button) inline static
References VOUT_DISPLAY_EVENT_MOUSE_RELEASED, and vout_display_SendEvent().
Referenced by ThreadChangeWindowMouse().
vout_display_SendEventMouseState()
static void vout_display_SendEventMouseState (vout_display_t * vd, int x, int y, int button_mask) inline static
References VOUT_DISPLAY_EVENT_MOUSE_STATE, and vout_display_SendEvent().
Referenced by ThreadChangeWindowMouse().
vout_display_SendEventPicturesInvalid()
static void vout_display_SendEventPicturesInvalid (vout_display_t * vd) inline static
References VOUT_DISPLAY_EVENT_PICTURES_INVALID, and vout_display_SendEvent().
vout_display_SendEventViewpointMoved()
static void vout_display_SendEventViewpointMoved (vout_display_t * vd, const vlc_viewpoint_t * vp) inline static
References VOUT_DISPLAY_EVENT_VIEWPOINT_MOVED, and vout_display_SendEvent().
vout_display_SendMouseMovedDisplayCoordinates()
void vout_display_SendMouseMovedDisplayCoordinates (vout_display_t * vd, video_orientation_t orient_display, int m_x, int m_y, vout_display_place_t * place)
Helper function that applies the necessary transforms to the mouse position and then calls vout_display_SendEventMouseMoved.
Parameters
vd vout_display_t.
orient_display The orientation of the picture as seen on screen (probably ORIENT_NORMAL).
m_x Mouse x position (relative to place, origin is top left).
m_y Mouse y position (relative to place, origin is top left).
place Place of the picture.
References vout_display_place_t::height, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, video_format_t::orientation, vout_display_t::source, transform(), TRANSFORM_ANTI_TRANSPOSE, TRANSFORM_HFLIP, TRANSFORM_R180, TRANSFORM_R270, TRANSFORM_R90, TRANSFORM_TRANSPOSE, TRANSFORM_VFLIP, video_format_GetTransform(), video_format_TransformTo(), vout_display_SendEventMouseMoved(), vout_display_place_t::width, vout_display_place_t::x, and vout_display_place_t::y.