VLC: Output
Output
Topics
Audio output
Filters
Audio, video, text filters
Stream output
Video output
Video rendering, output and window management
Files
file vlc_viewpoint.h
Video and audio viewpoint struct and helpers.
Data Structures
struct vlc_viewpoint_t
Viewpoints.
Macros
#define FIELD_OF_VIEW_DEGREES_DEFAULT 80.f
#define FIELD_OF_VIEW_DEGREES_MAX 150.f
#define FIELD_OF_VIEW_DEGREES_MIN 20.f
Functions
static void vlc_viewpoint_init (vlc_viewpoint_t *p_vp)
static void vlc_viewpoint_clip (vlc_viewpoint_t *p_vp)
Detailed Description
Macro Definition Documentation
FIELD_OF_VIEW_DEGREES_DEFAULT
#define FIELD_OF_VIEW_DEGREES_DEFAULT 80.f
Referenced by vlc_viewpoint_init().
FIELD_OF_VIEW_DEGREES_MAX
#define FIELD_OF_VIEW_DEGREES_MAX 150.f
Referenced by vlc_viewpoint_clip().
FIELD_OF_VIEW_DEGREES_MIN
#define FIELD_OF_VIEW_DEGREES_MIN 20.f
Referenced by vlc_viewpoint_clip().
Function Documentation
vlc_viewpoint_clip()
static void vlc_viewpoint_clip (vlc_viewpoint_t * p_vp) inline static
References FIELD_OF_VIEW_DEGREES_MAX, FIELD_OF_VIEW_DEGREES_MIN, vlc_viewpoint_t::fov, vlc_viewpoint_t::pitch, vlc_viewpoint_t::roll, VLC_CLIP, and vlc_viewpoint_t::yaw.
Referenced by ViewpointApply().
vlc_viewpoint_init()
static void vlc_viewpoint_init (vlc_viewpoint_t * p_vp) inline static
References FIELD_OF_VIEW_DEGREES_DEFAULT, vlc_viewpoint_t::fov, vlc_viewpoint_t::pitch, vlc_viewpoint_t::roll, and vlc_viewpoint_t::yaw.
Referenced by aout_New(), Create(), and video_format_Init().