VLC: Connections
Connections
HTTP » Connection manager
HTTP connections
Topics
HTTP/1.x
HTTP/2.0
Data Structures
struct vlc_http_conn_cbs
struct vlc_http_conn
Functions
static struct vlc_http_stream * vlc_http_stream_open (struct vlc_http_conn *conn, const struct vlc_http_msg *m)
static void vlc_http_conn_release (struct vlc_http_conn *conn)
void vlc_http_err (void *, const char *msg,...) VLC_FORMAT(2
void void vlc_http_dbg (void *, const char *msg,...) VLC_FORMAT(2
Detailed Description
HTTP connections
Function Documentation
vlc_http_conn_release()
static void vlc_http_conn_release (struct vlc_http_conn * conn) inline static
References vlc_http_conn::cbs, and vlc_http_conn_cbs::release.
Referenced by vlc_h1_request(), vlc_http_mgr_release(), vlc_http_request(), and vlc_https_connect_proxy().
vlc_http_dbg()
void void vlc_http_dbg (void * , const char * msg, ...)
Referenced by vlc_h1_request(), vlc_h1_stream_fatal(), vlc_h1_stream_open(), vlc_h1_stream_wait(), vlc_h2_error(), vlc_h2_frame_dump(), vlc_h2_recv_thread(), vlc_h2_reset(), vlc_h2_setting(), vlc_h2_stream_end(), vlc_h2_stream_error(), vlc_h2_stream_headers(), and vlc_h2_stream_open().
vlc_http_err()
void vlc_http_err (void * , const char * msg, ...)
Referenced by vlc_h1_request(), vlc_h2_error(), vlc_h2_reset(), vlc_h2_stream_error(), and vlc_h2_stream_reset().
vlc_http_stream_open()
static struct vlc_http_stream * vlc_http_stream_open (struct vlc_http_conn * conn, const struct vlc_http_msg * m) inline static
References vlc_http_conn::cbs, and vlc_http_conn_cbs::stream_open.
Referenced by vlc_h1_request(), vlc_http_mgr_reuse(), and vlc_http_tunnel_open().