VLC: String helpers
String helpers
Files
file vlc_charset.h
Characters sets handling.
file vlc_strings.h
Helper functions for nul-terminated strings.
file vlc_url.h
This file defines functions for manipulating URL in vlc.
Functions
static int vlc_ascii_toupper (int c)
static int vlc_ascii_tolower (int c)
static int vlc_ascii_strcasecmp (const char *psz1, const char *psz2)
Compare two ASCII strings ignoring case.
static int vlc_ascii_strncasecmp (const char *psz1, const char *psz2, size_t n)
void vlc_xml_decode (char *st)
Decodes XML entities.
char * vlc_xml_encode (const char *str)
Encodes XML entites.
char * vlc_b64_encode_binary (const uint8_t *, size_t)
char * vlc_b64_encode (const char *)
size_t vlc_b64_decode_binary_to_buffer (uint8_t *p_dst, size_t i_dst_max, const char *psz_src)
size_t vlc_b64_decode_binary (uint8_t **pp_dst, const char *psz_src)
char * vlc_b64_decode (const char *psz_src)
char * vlc_strftime (const char *)
Convenience wrapper for strftime().
char * vlc_strfinput (input_thread_t *, const char *)
Formats input meta-data.
static char * str_format (input_thread_t *input, const char *fmt)
int vlc_filenamecmp (const char *, const char *)
void filename_sanitize (char *)
Sanitize a file name.
Detailed Description
Function Documentation
filename_sanitize()
void filename_sanitize (char * str)
Sanitize a file name.
Remove forbidden, potentially forbidden and otherwise evil characters from file names. That includes slashes, and popular characters like colon (on Unix anyway).
Warning
This function should only be used for automatically generated file names. Do not use this on full paths, only single file names without any directory separator!
References EnsureUTF8().
Referenced by ArtCacheGetDirPath(), ArtCacheName(), input_CreateFilename(), and vout_snapshot_SaveImage().
str_format()
static char * str_format (input_thread_t * input, const char * fmt) inline static
References vlc_strfinput(), and vlc_strftime().
Referenced by input_CreateFilename(), and vout_snapshot_SaveImage().
vlc_ascii_strcasecmp()
static int vlc_ascii_strcasecmp (const char * psz1, const char * psz2) inline static
Compare two ASCII strings ignoring case.
The result is independent of the locale. If there are non-ASCII characters in the strings, their cases are NOT ignored in the comparison.
References vlc_ascii_tolower().
Referenced by cookie_domain_matches(), demux_mapping_cmp(), vlc_http_cookies_store(), vlc_http_res_get_redirect(), and vlc_http_res_init().
vlc_ascii_strncasecmp()
static int vlc_ascii_strncasecmp (const char * psz1, const char * psz2, size_t n) inline static
References vlc_ascii_tolower().
Referenced by cookie_get_attribute_value(), and cookie_has_attribute().
vlc_ascii_tolower()
static int vlc_ascii_tolower (int c) inline static
Referenced by vlc_ascii_strcasecmp(), and vlc_ascii_strncasecmp().
vlc_ascii_toupper()
static int vlc_ascii_toupper (int c) inline static
vlc_b64_decode()
char * vlc_b64_decode (const char * psz_src)
References vlc_b64_decode_binary_to_buffer().
Referenced by httpdAuthOk().
vlc_b64_decode_binary()
size_t vlc_b64_decode_binary (uint8_t ** pp_dst, const char * psz_src)
References vlc_b64_decode_binary_to_buffer().
vlc_b64_decode_binary_to_buffer()
size_t vlc_b64_decode_binary_to_buffer (uint8_t * p_dst, size_t i_dst_max, const char * psz_src)
References p.
Referenced by pgp_unarmor(), vlc_b64_decode(), and vlc_b64_decode_binary().
vlc_b64_encode()
char * vlc_b64_encode (const char * src)
References vlc_b64_encode_binary().
Referenced by vlc_http_auth_FormatAuthorizationHeader().
vlc_b64_encode_binary()
char * vlc_b64_encode_binary (const uint8_t * src, size_t i_src)
Referenced by vlc_b64_encode(), and vlc_http_msg_add_creds_basic().
vlc_filenamecmp()
int vlc_filenamecmp (const char * a, const char * b)
References strcoll.
Referenced by rdh_compar_filename().
vlc_strfinput()
char * vlc_strfinput (input_thread_t * input, const char * s)
Formats input meta-data.
Formats input and input item meta-informations into a heap-allocated string.
References aout_VolumeGet(), input_GetAout(), input_GetItem(), input_item_GetDuration(), input_item_GetName(), input_item_GetNowPlayingFb(), input_item_GetTitleFbName(), input_item_GetURI(), name, vlc_memstream::stream, var_GetFloat, var_GetInteger, var_GetNonEmptyString, vlc_memstream_close(), vlc_memstream_open(), vlc_memstream_printf(), vlc_memstream_putc(), vlc_memstream_puts(), vlc_meta_Album, vlc_meta_Artist, vlc_meta_Copyright, vlc_meta_Date, vlc_meta_Description, vlc_meta_EncodedBy, vlc_meta_Genre, vlc_meta_Language, vlc_meta_Publisher, vlc_meta_Rating, vlc_meta_Title, vlc_meta_TrackNumber, vlc_meta_TrackTotal, vlc_meta_URL, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, write_duration(), and write_meta().
Referenced by str_format().
vlc_strftime()
char * vlc_strftime (const char * tformat)
Convenience wrapper for strftime().
Formats the current time into a heap-allocated string.
Parameters
tformat time format (as with C strftime())
Returns
an allocated string (must be free()'d), or NULL on memory error.
References localtime_r(), strdup(), and vlc_assert_unreachable.
Referenced by str_format().
vlc_xml_decode()
void vlc_xml_decode (char * st)
Decodes XML entities.
Decodes a null-terminated UTF-8 string of XML character data into a regular nul-terminated UTF-8 string. In other words, replaces XML entities and numerical character references with the corresponding characters.
This function operates in place (the output is always of smaller or equal length than the input) and always succeeds.
Parameters
str null-terminated string [IN/OUT]
References ARRAY_SIZE, cmp_entity(), xml_entity_s::psz_char, xml_entity_s::psz_entity, psz_value, and xml_entities.
vlc_xml_encode()
char * vlc_xml_encode (const char * str)
Encodes XML entites.
Substitutes unsafe characters in a null-terminated UTF-8 strings with an XML entity or numerical character reference.
Parameters
str null terminated UTF-8 string
Returns
On success, a heap-allocated null-terminated string is returned. If the input string was not a valid UTF-8 sequence, NULL is returned and errno is set to EILSEQ. If there was not enough memory, NULL is returned and errno is to ENOMEM.
References vlc_memstream::stream, unlikely, vlc_memstream_close(), vlc_memstream_open(), vlc_memstream_printf(), vlc_memstream_puts(), vlc_memstream_write(), and vlc_towc().
Referenced by httpd_HtmlError().