VLC: VLC playlist internals
VLC playlist internals
VLC playlist
Topics
Playlist_NodeDeleteExplicit_flags
Flags for playlist_NodeDeleteExplicit .
Files
file playlist_internal.h
VLC playlist internal interface.
Data Structures
struct playlist_private_t
Macros
#define pl_priv(pl) container_of(pl, playlist_private_t, public_data)
#define PLAYLIST_DEBUG 1
#define PL_DEBUG(...) msg_Dbg(p_playlist, __VA_ARGS__)
#define PL_DEBUG2(msg, ...) {}
#define PLI_NAME(p) p && p->p_input ? p->p_input->psz_name : "null"
#define PL_LOCK_IF(cond) pl_lock_if(p_playlist, cond)
#define PL_UNLOCK_IF(cond) pl_unlock_if(p_playlist, cond)
Typedefs
typedef struct vlc_sd_internal_t vlc_sd_internal_t
typedef struct playlist_private_t playlist_private_t
Functions
void playlist_ServicesDiscoveryKillAll (playlist_t *p_playlist)
playlist_t * playlist_Create (vlc_object_t *)
Create playlist.
void playlist_Destroy (playlist_t *)
Destroy playlist.
void playlist_Activate (playlist_t *)
Creates the main playlist thread.
playlist_item_t * playlist_ItemNewFromInput (playlist_t *p_playlist, input_item_t *p_input)
playlist_item_t * get_current_status_item (playlist_t *p_playlist)
Accessor for status item and status nodes.
playlist_item_t * get_current_status_node (playlist_t *p_playlist)
void set_current_status_item (playlist_t *, playlist_item_t *)
void set_current_status_node (playlist_t *, playlist_item_t *)
int playlist_MLLoad (playlist_t *p_playlist)
int playlist_MLDump (playlist_t *p_playlist)
void playlist_SendAddNotify (playlist_t *p_playlist, playlist_item_t *item)
Send a notification that an item has been added to a node.
int playlist_InsertInputItemTree (playlist_t *, playlist_item_t *, input_item_node_t *, int, bool)
Insert a tree of input items into a given playlist node.
int playlist_NodeInsert (playlist_item_t *, playlist_item_t *, int)
void playlist_NodeDeleteExplicit (playlist_t *, playlist_item_t *, int flags)
Delete a node with explicit semantics.
void playlist_ItemRelease (playlist_t *, playlist_item_t *)
Release an item.
void ResetCurrentlyPlaying (playlist_t *p_playlist, playlist_item_t *p_cur)
Reset the currently playing playlist.
void ResyncCurrentIndex (playlist_t *p_playlist, playlist_item_t *p_cur)
Synchronise the current index of the playlist to match the index of the current item.
playlist_item_t * playlist_GetNextLeaf (playlist_t *, playlist_item_t *p_root, playlist_item_t *p_item, bool b_ena, bool b_unplayed)
Finds the next item to play.
static void pl_lock_if (playlist_t *p_playlist, bool cond)
static void pl_unlock_if (playlist_t *p_playlist, bool cond)
Detailed Description
Macro Definition Documentation
PL_DEBUG
#define PL_DEBUG (...) msg_Dbg(p_playlist, __VA_ARGS__)
Referenced by LoopInput(), NextItem(), PlayItem(), playlist_NodeDeleteExplicit(), ResetCurrentlyPlaying(), and ResyncCurrentIndex().
PL_DEBUG2
#define PL_DEBUG2 (msg, ...) {}
Referenced by GetNextItem(), GetNextUncle(), GetPrevItem(), and playlist_GetNextLeaf().
PL_LOCK_IF
#define PL_LOCK_IF (cond) pl_lock_if(p_playlist, cond)
Referenced by playlist_Clear(), and playlist_vaControl().
pl_priv
#define pl_priv (pl) container_of(pl, playlist_private_t, public_data)
Referenced by get_current_status_item(), get_current_status_node(), input_item_add_subitem_tree(), InputEvent(), intf_Create(), intf_DestroyAll(), LoopInput(), NextItem(), PlayItem(), playlist_Activate(), playlist_AssertLocked(), playlist_Create(), playlist_CurrentInputLocked(), playlist_CurrentPlayingItem(), playlist_Deactivate(), playlist_Destroy(), playlist_GetAout(), playlist_IsServicesDiscoveryLoaded(), playlist_ItemGetById(), playlist_ItemGetByInput(), playlist_ItemNewFromInput(), playlist_ItemRelease(), playlist_LiveSearchUpdate(), playlist_Lock(), playlist_NodeAddCopy(), playlist_NodeDeleteExplicit(), playlist_Preparse(), playlist_RecursiveNodeSort(), playlist_SendAddNotify(), playlist_ServicesDiscoveryAdd(), playlist_ServicesDiscoveryControl(), playlist_ServicesDiscoveryKillAll(), playlist_ServicesDiscoveryRemove(), playlist_SetRenderer(), playlist_Status(), playlist_TreeMove(), playlist_TreeMoveMany(), playlist_Unlock(), playlist_vaControl(), RandomCallback(), RateCallback(), RateOffsetCallback(), ResetCurrentlyPlaying(), set_current_status_item(), set_current_status_node(), Thread(), and VideoSplitterCallback().
PL_UNLOCK_IF
#define PL_UNLOCK_IF (cond) pl_unlock_if(p_playlist, cond)
Referenced by playlist_Clear(), and playlist_vaControl().
PLAYLIST_DEBUG
#define PLAYLIST_DEBUG 1
PLI_NAME
#define PLI_NAME (p) p && p->p_input ? p->p_input->psz_name : "null"
Referenced by NextItem(), playlist_GetNextLeaf(), ResetCurrentlyPlaying(), and ResyncCurrentIndex().
Typedef Documentation
playlist_private_t
typedef struct playlist_private_t playlist_private_t
vlc_sd_internal_t
typedef struct vlc_sd_internal_t vlc_sd_internal_t
Function Documentation
get_current_status_item()
playlist_item_t * get_current_status_item (playlist_t * p_playlist)
Accessor for status item and status nodes.
References PL_ASSERT_LOCKED, and pl_priv.
Referenced by input_item_add_subitem_tree(), NextItem(), playlist_NodeDeleteExplicit(), and playlist_vaControl().
get_current_status_node()
playlist_item_t * get_current_status_node (playlist_t * p_playlist)
References PL_ASSERT_LOCKED, and pl_priv.
Referenced by NextItem(), and playlist_vaControl().
pl_lock_if()
static void pl_lock_if (playlist_t * p_playlist, bool cond) inline static
References PL_ASSERT_LOCKED, and PL_LOCK.
pl_unlock_if()
static void pl_unlock_if (playlist_t * p_playlist, bool cond) inline static
References PL_UNLOCK.
playlist_Activate()
void playlist_Activate (playlist_t * p_playlist)
Creates the main playlist thread.
References msg_Err, pl_priv, Thread(), playlist_private_t::thread, vlc_clone(), and VLC_THREAD_PRIORITY_LOW.
Referenced by playlist_Create().
playlist_Create()
playlist_t * playlist_Create (vlc_object_t * p_parent)
Create playlist.
Create a playlist structure.
Parameters
p_parent the vlc object that is to be the parent of this playlist
Returns
a pointer to the created playlist, or NULL on error
References _, ARRAY_INIT, playlist_t::current, playlist_item_t::i_children, playlist_t::i_current_index, playlist_item_t::i_flags, playlist_item_t::i_id, playlist_item_t::i_nb_played, input_resource_GetAout(), input_resource_New(), input_resource_PutAout(), playlist_t::items, likely, p, vlc_value_t::p_address, playlist_item_t::p_input, playlist_t::p_media_library, playlist_t::p_playing, PL_LOCK, pl_priv, PL_UNLOCK, playlist_Activate(), PLAYLIST_END, playlist_MLLoad(), PLAYLIST_NO_INHERIT_FLAG, playlist_NodeCreate(), PLAYLIST_RO_FLAG, playlist_ServicesDiscoveryAdd(), playlist_item_t::pp_children, playlist_t::root, strsep(), TAB_INIT, unlikely, var_Create, var_InheritBool, var_InheritString, var_SetChecked, VariablesInit(), vlc_cond_init(), vlc_custom_create, vlc_http_cookies_new(), vlc_mutex_init(), VLC_OBJECT, and VLC_VAR_ADDRESS.
Referenced by intf_GetPlaylist().
playlist_Destroy()
void playlist_Destroy (playlist_t * p_playlist)
Destroy playlist.
This is not thread-safe. Any reference to the playlist is assumed gone. (In particular, all interface and services threads must have been joined).
Parameters
p_playlist the playlist object
< delete node even if read-only
< delete node even if read-only
References ARRAY_RESET, playlist_t::current, playlist_item_t::i_children, input_resource_Release(), playlist_t::items, playlist_private_t::lock, msg_Dbg, playlist_private_t::p_input, playlist_private_t::p_input_resource, playlist_t::p_media_library, playlist_t::p_playing, playlist_private_t::p_renderer, PL_LOCK, pl_priv, PL_UNLOCK, playlist_Deactivate(), PLAYLIST_DELETE_FORCE, playlist_MLDump(), playlist_NodeDeleteExplicit(), playlist_ServicesDiscoveryKillAll(), playlist_t::root, set_current_status_item(), set_current_status_node(), playlist_private_t::signal, var_Destroy, var_GetAddress, vlc_cond_destroy(), vlc_http_cookies_destroy(), vlc_mutex_destroy(), vlc_object_release, and vlc_renderer_item_release().
Referenced by intf_DestroyAll().
playlist_GetNextLeaf()
playlist_item_t * playlist_GetNextLeaf (playlist_t * p_playlist, playlist_item_t * p_root, playlist_item_t * p_item, bool b_ena, bool b_unplayed)
Finds the next item to play.
Parameters
p_playlist the playlist
p_root the root node
p_item the previous item (NULL if none)
Returns
the next item to play, or NULL if none found
References GetNextItem(), playlist_item_t::i_children, playlist_item_t::i_flags, playlist_item_t::i_nb_played, PL_ASSERT_LOCKED, PL_DEBUG2, PLAYLIST_DBL_FLAG, and PLI_NAME.
Referenced by NextItem(), and ResetCurrentlyPlaying().
playlist_InsertInputItemTree()
int playlist_InsertInputItemTree (playlist_t * p_playlist, playlist_item_t * p_parent, input_item_node_t * p_node, int i_pos, bool b_flat)
Insert a tree of input items into a given playlist node.
Parameters
p_playlist the playlist to insert into
p_parent the receiving playlist node (can be an item)
p_node the root of input item tree, only it's contents will be inserted
i_pos the position in the playlist where to insert. If this is PLAYLIST_END the items will be added at the end of the playlist regardless of its size
b_flat TRUE if the new tree contents should be flattened into a list
Returns
the first new leaf inserted (in playing order)
References RecursiveAddIntoParent().
Referenced by input_item_add_subitem_tree(), and input_item_subitem_tree_added().
playlist_ItemNewFromInput()
playlist_item_t * playlist_ItemNewFromInput (playlist_t * p_playlist, input_item_t * p_input)
References input_item_t::event_manager, playlist_item_t::i_children, playlist_item_t::i_flags, playlist_item_t::i_id, playlist_item_t::i_nb_played, input_item_t::i_type, input_item_add_subitem_tree(), input_item_changed(), input_item_Hold(), ITEM_TYPE_NODE, p, playlist_item_t::p_input, playlist_item_t::p_parent, PL_ASSERT_LOCKED, pl_priv, playlist_ItemCmpId(), playlist_ItemCmpInput(), playlist_item_t::pp_children, tdelete(), tsearch(), unlikely, vlc_event_attach(), vlc_InputItemDurationChanged, vlc_InputItemErrorWhenReadingChanged, vlc_InputItemInfoChanged, vlc_InputItemMetaChanged, vlc_InputItemNameChanged, and vlc_InputItemSubItemTreeAdded.
Referenced by playlist_NodeAddInput(), and playlist_NodeCreate().
playlist_ItemRelease()
void playlist_ItemRelease (playlist_t * p_playlist, playlist_item_t * p_item)
Release an item.
Parameters
p_item item to delete
References input_item_t::event_manager, input_item_add_subitem_tree(), input_item_changed(), input_item_Release(), p, playlist_item_t::p_input, PL_ASSERT_LOCKED, pl_priv, playlist_ItemCmpId(), playlist_ItemCmpInput(), playlist_item_t::pp_children, tdelete(), vlc_event_detach(), vlc_InputItemDurationChanged, vlc_InputItemErrorWhenReadingChanged, vlc_InputItemInfoChanged, vlc_InputItemMetaChanged, vlc_InputItemNameChanged, and vlc_InputItemSubItemTreeAdded.
Referenced by playlist_NodeDeleteExplicit().
playlist_MLDump()
int playlist_MLDump (playlist_t * p_playlist)
< Unspecified error
< Unspecified error
< Unspecified error
< No error
< Unspecified error
< No error
References asprintf(), config_CreateDir(), config_GetUserDir(), DIR_SEP, getpid(), msg_Err, playlist_Export(), VLC_DATA_DIR, VLC_EGENERIC, vlc_rename(), vlc_strerror_c(), VLC_SUCCESS, and vlc_unlink().
Referenced by playlist_Destroy().
playlist_MLLoad()
int playlist_MLLoad (playlist_t * p_playlist)
< Unspecified error
< Not enough memory
< Unspecified error
< Not enough memory
< Unspecified error
< No error
References _, asprintf(), config_GetUserDir(), DIR_SEP, input_item_t::event_manager, input_item_New, input_item_Release(), input_item_subitem_tree_added(), input_Read, msg_Err, var_Create, VLC_DATA_DIR, VLC_EGENERIC, VLC_ENOMEM, vlc_event_attach(), vlc_event_detach(), vlc_InputItemSubItemTreeAdded, vlc_object_create, vlc_object_release, vlc_path2uri(), vlc_stat(), VLC_SUCCESS, and VLC_VAR_VOID.
Referenced by playlist_Create().
playlist_NodeDeleteExplicit()
void playlist_NodeDeleteExplicit (playlist_t * p_playlist, playlist_item_t * p_root, int flags)
Delete a node with explicit semantics.
This function acts like playlist_NodeDelete with the advantage of the caller being able control some of the semantics of the function.
p_playlist the playlist where the node is to be deleted p_node the node to delete flags a bitfield consisting of Playlist_NodeDeleteExplicit_flags
< delete node even if read-only
< delete node even if read-only
< stop playlist playback if node is currently the one played
References ARRAY_BSEARCH, ARRAY_REMOVE, playlist_t::current, get_current_status_item(), playlist_item_t::i_children, playlist_item_t::i_flags, playlist_item_t::i_id, playlist_item_array_t::i_size, playlist_t::items, playlist_item_array_t::p_elems, playlist_item_t::p_input, playlist_item_t::p_parent, PL_ASSERT_LOCKED, PL_DEBUG, pl_Locked, pl_priv, playlist_Control(), PLAYLIST_DELETE_FORCE, PLAYLIST_DELETE_STOP_IF_CURRENT, playlist_ItemRelease(), playlist_NodeDeleteExplicit(), PLAYLIST_RO_FLAG, PLAYLIST_STOP, playlist_item_t::pp_children, input_item_t::psz_name, set_current_status_item(), TAB_REMOVE, and var_SetAddress.
Referenced by input_item_add_subitem_tree(), playlist_Destroy(), playlist_NodeDelete(), playlist_NodeDeleteExplicit(), playlist_sd_item_removed(), and playlist_ServicesDiscoveryInternalRemoveLocked().
playlist_NodeInsert()
int playlist_NodeInsert (playlist_item_t * p_parent, playlist_item_t * p_item, int i_position)
< No error
References playlist_item_t::i_children, playlist_item_t::i_flags, playlist_item_t::p_parent, PLAYLIST_NO_INHERIT_FLAG, PLAYLIST_RO_FLAG, playlist_item_t::pp_children, TAB_INSERT, and VLC_SUCCESS.
Referenced by playlist_NodeAddInput(), and playlist_NodeCreate().
playlist_SendAddNotify()
void playlist_SendAddNotify (playlist_t * p_playlist, playlist_item_t * item)
Send a notification that an item has been added to a node.
Parameters
p_playlist the playlist object
i_item_id id of the item added
i_node_id id of the node in which the item was added
Returns
nothing
References playlist_private_t::b_reset_currently_playing, PL_ASSERT_LOCKED, pl_priv, playlist_private_t::signal, var_SetAddress, and vlc_cond_signal().
Referenced by playlist_NodeAddInput(), and playlist_NodeCreate().
playlist_ServicesDiscoveryKillAll()
void playlist_ServicesDiscoveryKillAll (playlist_t * p_playlist)
References playlist_private_t::i_sds, pl_priv, playlist_Lock(), playlist_ServicesDiscoveryInternalRemoveLocked(), playlist_Unlock(), playlist_private_t::pp_sds, and TAB_ERASE.
Referenced by playlist_Destroy().
ResetCurrentlyPlaying()
void ResetCurrentlyPlaying (playlist_t * p_playlist, playlist_item_t * p_cur)
Reset the currently playing playlist.
Parameters
p_playlist the playlist structure
p_cur the current playlist item
Returns
nothing
FIXME: this is slow
References ARRAY_APPEND, ARRAY_RESET, ARRAY_VAL, playlist_private_t::b_reset_currently_playing, playlist_t::current, playlist_t::i_current_index, playlist_item_array_t::i_size, playlist_private_t::p_node, PL_DEBUG, pl_priv, playlist_GetNextLeaf(), PLI_NAME, playlist_private_t::status, var_GetBool, and vlc_lrand48().
Referenced by input_item_add_subitem_tree(), NextItem(), and RandomCallback().
ResyncCurrentIndex()
void ResyncCurrentIndex (playlist_t * p_playlist, playlist_item_t * p_cur)
Synchronise the current index of the playlist to match the index of the current item.
Parameters
p_playlist the playlist structure
p_cur the current playlist item
Returns
nothing
References ARRAY_VAL, playlist_t::current, playlist_t::i_current_index, playlist_item_array_t::i_size, PL_ASSERT_LOCKED, PL_DEBUG, and PLI_NAME.
Referenced by Next(), NextItem(), and RandomCallback().
set_current_status_item()
void set_current_status_item (playlist_t * p_playlist, playlist_item_t * p_item)
References PL_ASSERT_LOCKED, and pl_priv.
Referenced by PlayItem(), playlist_Destroy(), and playlist_NodeDeleteExplicit().
set_current_status_node()
void set_current_status_node (playlist_t * p_playlist, playlist_item_t * p_node)
References PL_ASSERT_LOCKED, and pl_priv.
Referenced by NextItem(), and playlist_Destroy().