VLC: VLC renderer items returned by the discovery
VLC renderer items returned by the discovery
VLC renderer discovery
Macros
#define VLC_RENDERER_CAN_AUDIO 0x0001
#define VLC_RENDERER_CAN_VIDEO 0x0002
Functions
vlc_renderer_item_t * vlc_renderer_item_new (const char *psz_type, const char *psz_name, const char *psz_uri, const char *psz_extra_sout, const char *psz_demux_filter, const char *psz_icon_uri, int i_flags)
Create a new renderer item.
vlc_renderer_item_t * vlc_renderer_item_hold (vlc_renderer_item_t *p_item)
Hold a renderer item, i.e.
void vlc_renderer_item_release (vlc_renderer_item_t *p_item)
Releases a renderer item, i.e.
const char * vlc_renderer_item_name (const vlc_renderer_item_t *p_item)
Get the human readable name of a renderer item.
const char * vlc_renderer_item_type (const vlc_renderer_item_t *p_item)
Get the type (not translated) of a renderer item.
const char * vlc_renderer_item_demux_filter (const vlc_renderer_item_t *p_item)
Get the demux filter to use with a renderer item.
const char * vlc_renderer_item_sout (const vlc_renderer_item_t *p_item)
Get the sout command of a renderer item.
const char * vlc_renderer_item_icon_uri (const vlc_renderer_item_t *p_item)
Get the icon uri of a renderer item.
int vlc_renderer_item_flags (const vlc_renderer_item_t *p_item)
Get the flags of a renderer item.
Detailed Description
Macro Definition Documentation
VLC_RENDERER_CAN_AUDIO
#define VLC_RENDERER_CAN_AUDIO 0x0001
VLC_RENDERER_CAN_VIDEO
#define VLC_RENDERER_CAN_VIDEO 0x0002
Function Documentation
vlc_renderer_item_demux_filter()
const char * vlc_renderer_item_demux_filter (const vlc_renderer_item_t * p_item)
Get the demux filter to use with a renderer item.
References vlc_renderer_item_t::psz_demux_filter.
Referenced by Control(), and InputSourceNew().
vlc_renderer_item_flags()
int vlc_renderer_item_flags (const vlc_renderer_item_t * p_item)
Get the flags of a renderer item.
References vlc_renderer_item_t::i_flags.
vlc_renderer_item_hold()
vlc_renderer_item_t * vlc_renderer_item_hold (vlc_renderer_item_t * p_item)
Hold a renderer item, i.e.
creates a new reference
References vlc_renderer_item_t::refs.
Referenced by Control(), Create(), input_vaControl(), PlayItem(), and playlist_SetRenderer().
vlc_renderer_item_icon_uri()
const char * vlc_renderer_item_icon_uri (const vlc_renderer_item_t * p_item)
Get the icon uri of a renderer item.
References vlc_renderer_item_t::psz_icon_uri.
vlc_renderer_item_name()
const char * vlc_renderer_item_name (const vlc_renderer_item_t * p_item)
Get the human readable name of a renderer item.
References vlc_renderer_item_t::psz_name.
vlc_renderer_item_new()
vlc_renderer_item_t * vlc_renderer_item_new (const char * psz_type, const char * psz_name, const char * psz_uri, const char * psz_extra_sout, const char * psz_demux_filter, const char * psz_icon_uri, int i_flags)
Create a new renderer item.
Parameters
psz_type type of the item
psz_name name of the item
psz_uri uri of the renderer item, must contains a valid protocol and a valid host
psz_extra_sout extra sout options
psz_demux_filter demux filter to use with the renderer
psz_icon_uri icon uri of the renderer item
i_flags flags for the item
Returns
a renderer item or NULL in case of error
References asprintf(), vlc_renderer_item_t::i_flags, vlc_url_t::i_port, item_free(), vlc_renderer_item_t::psz_demux_filter, vlc_url_t::psz_host, vlc_renderer_item_t::psz_icon_uri, psz_name, vlc_renderer_item_t::psz_name, vlc_url_t::psz_protocol, vlc_renderer_item_t::psz_sout, vlc_renderer_item_t::psz_type, vlc_renderer_item_t::refs, strdup(), unlikely, vlc_UrlClean(), and vlc_UrlParse().
vlc_renderer_item_release()
void vlc_renderer_item_release (vlc_renderer_item_t * p_item)
Releases a renderer item, i.e.
decrements its reference counter
References item_free(), and vlc_renderer_item_t::refs.
Referenced by Control(), ControlRelease(), input_Destructor(), PlayItem(), playlist_Destroy(), and playlist_SetRenderer().
vlc_renderer_item_sout()
const char * vlc_renderer_item_sout (const vlc_renderer_item_t * p_item)
Get the sout command of a renderer item.
References vlc_renderer_item_t::psz_sout.
vlc_renderer_item_type()
const char * vlc_renderer_item_type (const vlc_renderer_item_t * p_item)
Get the type (not translated) of a renderer item.
For now, the type can only be "chromecast" ("upnp", "airplay" may come later).
References vlc_renderer_item_t::psz_type.