VLC: Block chain
Block chain
Input » Data blocks
Functions
static void block_ChainAppend (block_t **pp_list, block_t *p_block)
static void block_ChainLastAppend (block_t ***ppp_last, block_t *p_block)
static void block_ChainRelease (block_t *p_block)
static size_t block_ChainExtract (block_t *p_list, void *p_data, size_t i_max)
static void block_ChainProperties (block_t *p_list, int *pi_count, size_t *pi_size, mtime_t *pi_length)
static block_t * block_ChainGather (block_t *p_list)
Detailed Description
Function Documentation
block_ChainAppend()
static void block_ChainAppend (block_t ** pp_list, block_t * p_block) inline static
References p, and block_t::p_next.
Referenced by aout_FiltersDrain(), and aout_FiltersPipelineDrain().
block_ChainExtract()
static size_t block_ChainExtract (block_t * p_list, void * p_data, size_t i_max) static
References block_t::i_buffer, p, block_t::p_buffer, and block_t::p_next.
Referenced by block_ChainGather().
block_ChainGather()
static block_t * block_ChainGather (block_t * p_list) inline static
References block_Alloc(), block_ChainExtract(), block_ChainProperties(), block_ChainRelease(), block_t::i_buffer, block_t::i_dts, block_t::i_flags, block_t::i_length, block_t::i_pts, block_t::p_buffer, and block_t::p_next.
Referenced by aout_FiltersDrain(), and aout_FiltersPipelineDrain().
block_ChainLastAppend()
static void block_ChainLastAppend (block_t *** ppp_last, block_t * p_block) inline static
References block_t::p_next.
Referenced by block_BytestreamPush().
block_ChainProperties()
static void block_ChainProperties (block_t * p_list, int * pi_count, size_t * pi_size, mtime_t * pi_length) inline static
References block_t::i_buffer, block_t::i_length, and block_t::p_next.
Referenced by block_ChainGather().
block_ChainRelease()
static void block_ChainRelease (block_t * p_block) inline static
References block_Release(), and block_t::p_next.
Referenced by block_BytestreamRelease(), block_ChainGather(), block_FifoEmpty(), block_FifoRelease(), DecoderProcess(), input_DecoderDecode(), input_DecoderFlush(), module_EndBank(), and vlc_stream_fifo_Destroy().