VLC: Live streams
Live streams
HTTP » Resources
Trivial HTTP-based live streams
Macros
#define vlc_http_live_get_status vlc_http_res_get_status
#define vlc_http_live_get_redirect vlc_http_res_get_redirect
#define vlc_http_live_get_type vlc_http_res_get_type
#define vlc_http_live_destroye vlc_http_res_destroy
Functions
struct vlc_http_resource * vlc_http_live_create (struct vlc_http_mgr *mgr, const char *uri, const char *ua, const char *ref)
struct block_t * vlc_http_live_read (struct vlc_http_resource *)
Detailed Description
Trivial HTTP-based live streams
Macro Definition Documentation
vlc_http_live_destroye
#define vlc_http_live_destroye vlc_http_res_destroy
vlc_http_live_get_redirect
#define vlc_http_live_get_redirect vlc_http_res_get_redirect
vlc_http_live_get_status
#define vlc_http_live_get_status vlc_http_res_get_status
vlc_http_live_get_type
#define vlc_http_live_get_type vlc_http_res_get_type
Referenced by LiveControl().
Function Documentation
vlc_http_live_create()
struct vlc_http_resource * vlc_http_live_create (struct vlc_http_mgr * mgr, const char * uri, const char * ua, const char * ref)
References unlikely, vlc_http_live_callbacks, and vlc_http_res_init().
Referenced by Open().
vlc_http_live_read()
struct block_t * vlc_http_live_read (struct vlc_http_resource * res)
References vlc_http_resource::response, vlc_http_error, vlc_http_msg_destroy(), and vlc_http_res_read().
Referenced by LiveRead().