VLC: modules/access/http/h1conn.c File Reference
h1conn.c File Reference
Data Structures
struct vlc_h1_conn
Macros
#define CO(conn) ((conn)->opaque)
Functions
static unsigned vlc_http_can_read (const char *buf, size_t len)
static char * vlc_https_headers_recv (struct vlc_tls *tls, size_t *restrict lenp)
Receives HTTP headers.
static int vlc_http_minor (const char *msg)
Gets minor HTTP version.
static void vlc_h1_conn_destroy (struct vlc_h1_conn *conn)
static void * vlc_h1_stream_fatal (struct vlc_h1_conn *conn)
static struct vlc_h1_conn * vlc_h1_stream_conn (struct vlc_http_stream *stream)
static struct vlc_http_stream * vlc_h1_stream_open (struct vlc_http_conn *c, const struct vlc_http_msg *req)
static struct vlc_http_msg * vlc_h1_stream_wait (struct vlc_http_stream *stream)
static block_t * vlc_h1_stream_read (struct vlc_http_stream *stream)
static void vlc_h1_stream_close (struct vlc_http_stream *stream, bool abort)
static void vlc_h1_conn_release (struct vlc_http_conn *c)
struct vlc_http_conn * vlc_h1_conn_create (void *ctx, vlc_tls_t *tls, bool proxy)
struct vlc_http_stream * vlc_h1_request (void *ctx, const char *hostname, unsigned port, bool proxy, const struct vlc_http_msg *req, bool idempotent, struct vlc_http_conn **restrict connp)
Sends an HTTP/1.x request through a new connection.
Variables
static const struct vlc_http_stream_cbs vlc_h1_stream_callbacks
static const struct vlc_http_conn_cbs vlc_h1_conn_callbacks
Macro Definition Documentation
CO
#define CO (conn) ((conn)->opaque)
Referenced by vlc_h1_stream_fatal(), vlc_h1_stream_open(), and vlc_h1_stream_wait().
Function Documentation
vlc_h1_conn_destroy()
static void vlc_h1_conn_destroy (struct vlc_h1_conn * conn) static
References vlc_h1_conn::active, vlc_h1_conn::conn, vlc_h1_conn::released, vlc_http_conn::tls, vlc_tls_Close(), and vlc_tls_Shutdown().
Referenced by vlc_h1_conn_release(), and vlc_h1_stream_close().
vlc_h1_conn_release()
static void vlc_h1_conn_release (struct vlc_http_conn * c) static
References vlc_h1_conn::conn, container_of, and vlc_h1_conn_destroy().
vlc_h1_stream_close()
static void vlc_h1_stream_close (struct vlc_http_stream * stream, bool abort) static
References vlc_h1_conn::conn, vlc_h1_conn::stream, vlc_h1_conn_destroy(), vlc_h1_stream_conn(), and vlc_h1_stream_fatal().
vlc_h1_stream_conn()
static struct vlc_h1_conn * vlc_h1_stream_conn (struct vlc_http_stream * stream) static
References container_of, and vlc_h1_conn::stream.
Referenced by vlc_h1_stream_close(), vlc_h1_stream_read(), and vlc_h1_stream_wait().
vlc_h1_stream_fatal()
static void * vlc_h1_stream_fatal (struct vlc_h1_conn * conn) static
References CO, vlc_h1_conn::conn, vlc_http_conn::tls, vlc_http_dbg(), vlc_tls_Close(), and vlc_tls_Shutdown().
Referenced by vlc_h1_stream_close(), vlc_h1_stream_open(), and vlc_h1_stream_wait().
vlc_h1_stream_open()
static struct vlc_http_stream * vlc_h1_stream_open (struct vlc_http_conn * c, const struct vlc_http_msg * req) static
References CO, vlc_h1_conn::conn, container_of, vlc_http_conn::tls, unlikely, vlc_h1_stream_fatal(), vlc_http_dbg(), vlc_http_msg_format(), and vlc_tls_Write().
vlc_h1_stream_read()
static block_t * vlc_h1_stream_read (struct vlc_http_stream * stream) static
References block_Alloc(), block_Release(), vlc_h1_conn::conn, block_t::i_buffer, block_t::p_buffer, vlc_h1_conn::stream, vlc_http_conn::tls, unlikely, vlc_h1_stream_conn(), vlc_http_error, and vlc_tls_Read().
vlc_h1_stream_wait()
static struct vlc_http_msg * vlc_h1_stream_wait (struct vlc_http_stream * stream) static
References vlc_h1_conn::active, CO, vlc_h1_conn::conn, vlc_h1_conn::connection_close, vlc_h1_conn::content_length, vlc_http_msg::payload, vlc_h1_conn::stream, vlc_http_conn::tls, unlikely, vlc_chunked_open(), vlc_h1_stream_conn(), vlc_h1_stream_fatal(), vlc_http_dbg(), vlc_http_minor(), vlc_http_msg_attach(), vlc_http_msg_destroy(), vlc_http_msg_get_size(), vlc_http_msg_get_token(), vlc_http_msg_headers(), vlc_http_next_token(), and vlc_https_headers_recv().
vlc_http_can_read()
static unsigned vlc_http_can_read (const char * buf, size_t len) static
Referenced by vlc_https_headers_recv().
vlc_http_minor()
static int vlc_http_minor (const char * msg) static
Gets minor HTTP version.
Referenced by vlc_h1_stream_wait().
vlc_https_headers_recv()
static char * vlc_https_headers_recv (struct vlc_tls * tls, size_t *restrict lenp) static
Receives HTTP headers.
Receives HTTP 1.x response line and headers.
Returns
A heap-allocated null-terminated string contained the full headers, including the final CRLF.
References unlikely, vlc_http_can_read(), and vlc_tls_Read().
Referenced by vlc_h1_stream_wait().
Variable Documentation
vlc_h1_conn_callbacks
const struct vlc_http_conn_cbs vlc_h1_conn_callbacks static
Initial value:
=
{
    vlc_h1_stream_open,
    vlc_h1_conn_release,
}
Referenced by vlc_h1_conn_create().
vlc_h1_stream_callbacks
const struct vlc_http_stream_cbs vlc_h1_stream_callbacks static
Initial value:
=
{
    vlc_h1_stream_wait,
    vlc_h1_stream_read,
    vlc_h1_stream_close,
}
Referenced by vlc_h1_conn_create().