VLC: src/config/help.c File Reference
help.c File Reference
Macros
#define ShowConsole() (void)0
#define PauseConsole() (void)0
#define COL(x) "\033[" #x ";1m"
#define RED COL(31)
#define GREEN COL(32)
#define YELLOW COL(33)
#define BLUE COL(34)
#define MAGENTA COL(35)
#define CYAN COL(36)
#define WHITE COL(0)
#define GRAY "\033[0m"
#define LINE_START 8
#define PADDING_SPACES 25
#define OPTION_VALUE_SEP " "
Functions
static void Help (vlc_object_t *, const char *)
static void Usage (vlc_object_t *, const char *)
static void Version (void)
static void ListModules (vlc_object_t *, bool)
static unsigned ConsoleWidth (void)
Returns the console width or a best guess.
bool config_PrintHelp (vlc_object_t *obj)
Checks for help command line options such as –help or –version.
static void print_help_on_full_help (void)
static void print_section (const module_t *m, const module_config_t **sect, bool color, bool desc)
static void print_desc (const char *str, unsigned margin, bool color)
static int vlc_swidth (const char *str)
static void print_item (const vlc_object_t *p_this, const module_t *m, const module_config_t *item, const module_config_t **section, bool color, bool desc)
static bool module_match (const module_t *m, const char *pattern, bool strict)
static bool plugin_show (const vlc_plugin_t *plugin, bool advanced)
Variables
static const char vlc_usage []
Macro Definition Documentation
BLUE
#define BLUE COL(34)
Referenced by print_desc().
COL
#define COL (x) "\033[" #x ";1m"
CYAN
#define CYAN COL(36)
Referenced by ListModules(), print_item(), and Usage().
GRAY
#define GRAY "\033[0m"
Referenced by ListModules(), print_desc(), print_item(), print_section(), and Usage().
GREEN
#define GREEN COL(32)
Referenced by ListModules(), print_item(), and Usage().
LINE_START
#define LINE_START 8
Referenced by print_item().
MAGENTA
#define MAGENTA COL(35)
Referenced by ListModules(), and print_section().
OPTION_VALUE_SEP
#define OPTION_VALUE_SEP " "
Referenced by print_item().
PADDING_SPACES
#define PADDING_SPACES 25
Referenced by print_item().
PauseConsole
#define PauseConsole () (void)0
Referenced by Help(), ListModules(), and Version().
RED
#define RED COL(31)
Referenced by print_section().
ShowConsole
#define ShowConsole () (void)0
Referenced by Help(), ListModules(), and Version().
WHITE
#define WHITE COL(0)
Referenced by ListModules(), print_item(), and Usage().
YELLOW
#define YELLOW COL(33)
Referenced by print_item().
Function Documentation
config_PrintHelp()
bool config_PrintHelp (vlc_object_t * obj)
Checks for help command line options such as –help or –version.
If one is found, print the corresponding text.
Returns
true if a command line options caused some help message to be printed, false otherwise.
References Help(), ListModules(), var_Create, var_InheritBool, var_InheritString, var_SetBool, Version(), and VLC_VAR_BOOL.
Referenced by libvlc_InternalInit().
ConsoleWidth()
static unsigned ConsoleWidth (void) static
Returns the console width or a best guess.
Referenced by print_desc().
Help()
static void Help (vlc_object_t * p_this, const char * psz_help_name) static
References _, PauseConsole, print_help_on_full_help(), ShowConsole, Usage(), and vlc_usage.
Referenced by config_PrintHelp().
ListModules()
static void ListModules (vlc_object_t * p_this, bool b_verbose) static
References count, CYAN, GRAY, GREEN, module_t::i_score, module_t::i_shortcuts, list, MAGENTA, module_get_object(), module_gettext(), module_list_free(), module_list_get(), PauseConsole, module_t::pp_shortcuts, module_t::psz_capability, module_t::psz_longname, ShowConsole, var_InheritBool, and WHITE.
Referenced by config_PrintHelp().
module_match()
static bool module_match (const module_t * m, const char * pattern, bool strict) static
References module_t::i_shortcuts, module_get_object(), and module_t::pp_shortcuts.
Referenced by Usage().
plugin_show()
static bool plugin_show (const vlc_plugin_t * plugin, bool advanced) static
References module_config_t::b_advanced, module_config_t::b_removed, vlc_plugin_t::conf, CONFIG_ITEM, module_config_t::i_type, vlc_plugin_t::items, and vlc_plugin_t::size.
Referenced by Usage().
print_desc()
static void print_desc (const char * str, unsigned margin, bool color) static
References BLUE, ConsoleWidth(), GRAY, unlikely, and vlc_towc().
Referenced by print_item().
print_help_on_full_help()
static void print_help_on_full_help (void) inline static
References _.
Referenced by Help().
print_item()
static void print_item (const vlc_object_t * p_this, const module_t * m, const module_config_t * item, const module_config_t ** section, bool color, bool desc) static
References _, asprintf(), CONFIG_CLASS, config_GetIntChoices(), config_GetPszChoices(), CONFIG_HINT_CATEGORY, CONFIG_HINT_USAGE, CONFIG_ITEM_BOOL, CONFIG_ITEM_FLOAT, CONFIG_ITEM_INTEGER, CONFIG_ITEM_STRING, CONFIG_SECTION, CYAN, module_value_t::f, GRAY, GREEN, module_value_t::i, module_config_t::i_short, module_config_t::i_type, LINE_START, module_config_t::list_count, module_config_t::max, module_config_t::min, module_gettext(), OPTION_VALUE_SEP, PADDING_SPACES, print_desc(), print_section(), module_config_t::psz_longtext, module_config_t::psz_name, module_config_t::psz_text, module_config_t::value, VLC_OBJECT, vlc_swidth(), WHITE, and YELLOW.
Referenced by Usage().
print_section()
static void print_section (const module_t * m, const module_config_t ** sect, bool color, bool desc) static
References GRAY, MAGENTA, module_gettext(), module_config_t::psz_longtext, module_config_t::psz_text, and RED.
Referenced by print_item().
Usage()
static void Usage (vlc_object_t * p_this, const char * psz_search) static
References _, module_config_t::b_advanced, module_config_t::b_removed, CYAN, GRAY, GREEN, module_get_object(), module_gettext(), module_match(), vlc_plugin_t::next, p, plugin_show(), print_item(), module_t::psz_help, module_t::psz_longname, var_InheritBool, vlc_ngettext(), vlc_plugins, and WHITE.
Referenced by Help().
Version()
static void Version (void) static
References _, LICENSE_MSG, PauseConsole, psz_vlc_changeset, ShowConsole, VLC_CompileBy(), VLC_CompileHost(), and VLC_Compiler().
Referenced by config_PrintHelp().
vlc_swidth()
static int vlc_swidth (const char * str) static
References vlc_towc().
Referenced by print_item().
Variable Documentation
vlc_usage
const char vlc_usage[] static
Referenced by Help().