VLC: modules/access/http/hpackenc.c File Reference
hpackenc.c File Reference
Functions
static size_t hpack_encode_int (uint8_t *restrict buf, size_t size, uintmax_t value, unsigned n)
static size_t hpack_encode_str_raw (uint8_t *restrict buf, size_t size, const char *str)
static size_t hpack_encode_str_raw_lower (uint8_t *restrict buf, size_t size, const char *str)
size_t hpack_encode_hdr_neverindex (uint8_t *restrict buf, size_t size, const char *name, const char *value)
size_t hpack_encode (uint8_t *restrict buf, size_t size, const char *const headers[][2], unsigned count)
Function Documentation
hpack_encode_int()
static size_t hpack_encode_int (uint8_t *restrict buf, size_t size, uintmax_t value, unsigned n) static
Referenced by hpack_encode_str_raw(), and hpack_encode_str_raw_lower().
hpack_encode_str_raw()
static size_t hpack_encode_str_raw (uint8_t *restrict buf, size_t size, const char * str) static
References hpack_encode_int().
Referenced by hpack_encode_hdr_neverindex().
hpack_encode_str_raw_lower()
static size_t hpack_encode_str_raw_lower (uint8_t *restrict buf, size_t size, const char * str) static
References hpack_encode_int().
Referenced by hpack_encode_hdr_neverindex().