VLC: src/network/httpd.c File Reference
httpd.c File Reference
Data Structures
struct httpd_host_t
struct httpd_url_t
struct httpd_client_t
struct httpd_file_t
struct httpd_handler_t
struct httpd_redirect_t
struct httpd_stream_t
struct httpd
Macros
#define HTTPD_CL_BUFSIZE 10000
Enumerations
enum {
HTTPD_CLIENT_RECEIVING , HTTPD_CLIENT_RECEIVE_DONE , HTTPD_CLIENT_SENDING , HTTPD_CLIENT_SEND_DONE ,
HTTPD_CLIENT_WAITING , HTTPD_CLIENT_DEAD , HTTPD_CLIENT_TLS_HS_IN , HTTPD_CLIENT_TLS_HS_OUT
}
Functions
static void httpd_ClientDestroy (httpd_client_t *cl)
static void httpd_AppendData (httpd_stream_t *stream, uint8_t *p_data, int i_data)
static const char * httpd_ReasonFromCode (unsigned i_code)
static size_t httpd_HtmlError (char **body, int code, const char *url)
static int httpd_FileCallBack (httpd_callback_sys_t *p_sys, httpd_client_t *cl, httpd_message_t *answer, const httpd_message_t *query)
httpd_file_t * httpd_FileNew (httpd_host_t *host, const char *psz_url, const char *psz_mime, const char *psz_user, const char *psz_password, httpd_file_callback_t pf_fill, httpd_file_sys_t *p_sys)
httpd_file_sys_t * httpd_FileDelete (httpd_file_t *file)
static int httpd_HandlerCallBack (httpd_callback_sys_t *p_sys, httpd_client_t *cl, httpd_message_t *answer, const httpd_message_t *query)
httpd_handler_t * httpd_HandlerNew (httpd_host_t *host, const char *psz_url, const char *psz_user, const char *psz_password, httpd_handler_callback_t pf_fill, void *p_sys)
void * httpd_HandlerDelete (httpd_handler_t *handler)
static int httpd_RedirectCallBack (httpd_callback_sys_t *p_sys, httpd_client_t *cl, httpd_message_t *answer, const httpd_message_t *query)
httpd_redirect_t * httpd_RedirectNew (httpd_host_t *host, const char *psz_url_dst, const char *psz_url_src)
void httpd_RedirectDelete (httpd_redirect_t *rdir)
static int httpd_StreamCallBack (httpd_callback_sys_t *p_sys, httpd_client_t *cl, httpd_message_t *answer, const httpd_message_t *query)
httpd_stream_t * httpd_StreamNew (httpd_host_t *host, const char *psz_url, const char *psz_mime, const char *psz_user, const char *psz_password)
int httpd_StreamHeader (httpd_stream_t *stream, uint8_t *p_data, int i_data)
int httpd_StreamSend (httpd_stream_t *stream, const block_t *p_block)
void httpd_StreamDelete (httpd_stream_t *stream)
static void * httpd_HostThread (void *)
static httpd_host_t * httpd_HostCreate (vlc_object_t *, const char *, const char *, vlc_tls_creds_t *)
httpd_host_t * vlc_http_HostNew (vlc_object_t *p_this)
httpd_host_t * vlc_https_HostNew (vlc_object_t *obj)
httpd_host_t * vlc_rtsp_HostNew (vlc_object_t *p_this)
void httpd_HostDelete (httpd_host_t *host)
httpd_url_t * httpd_UrlNew (httpd_host_t *host, const char *psz_url, const char *psz_user, const char *psz_password)
int httpd_UrlCatch (httpd_url_t *url, int i_msg, httpd_callback_t cb, httpd_callback_sys_t *p_sys)
void httpd_UrlDelete (httpd_url_t *url)
static void httpd_MsgInit (httpd_message_t *msg)
static void httpd_MsgClean (httpd_message_t *msg)
const char * httpd_MsgGet (const httpd_message_t *msg, const char *name)
void httpd_MsgAdd (httpd_message_t *msg, const char *name, const char *psz_value,...)
static void httpd_ClientInit (httpd_client_t *cl, mtime_t now)
char * httpd_ClientIP (const httpd_client_t *cl, char *ip, int *port)
char * httpd_ServerIP (const httpd_client_t *cl, char *ip, int *port)
static httpd_client_t * httpd_ClientNew (vlc_tls_t *sock, mtime_t now)
static ssize_t httpd_NetRecv (httpd_client_t *cl, uint8_t *p, size_t i_len)
static ssize_t httpd_NetSend (httpd_client_t *cl, const uint8_t *p, size_t i_len)
static void httpd_ClientRecv (httpd_client_t *cl)
static void httpd_ClientSend (httpd_client_t *cl)
static void httpd_ClientTlsHandshake (httpd_host_t *host, httpd_client_t *cl)
static bool httpdAuthOk (const char *user, const char *pass, const char *b64)
static void httpdLoop (httpd_host_t *host)
int httpd_StreamSetHTTPHeaders (httpd_stream_t *p_stream, const httpd_header *p_headers, size_t i_headers)
Variables
static struct httpd httpd = { PTHREAD_MUTEX_INITIALIZER , NULL, 0 }
struct {
const char name [16]
int i_type
int i_proto
} msg_type []
Macro Definition Documentation
HTTPD_CL_BUFSIZE
#define HTTPD_CL_BUFSIZE 10000
Referenced by httpd_ClientInit(), and httpd_StreamCallBack().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HTTPD_CLIENT_RECEIVING
HTTPD_CLIENT_RECEIVE_DONE
HTTPD_CLIENT_SENDING
HTTPD_CLIENT_SEND_DONE
HTTPD_CLIENT_WAITING
HTTPD_CLIENT_DEAD
HTTPD_CLIENT_TLS_HS_IN
HTTPD_CLIENT_TLS_HS_OUT
Function Documentation
httpd_AppendData()
static void httpd_AppendData (httpd_stream_t * stream, uint8_t * p_data, int i_data) static
References httpd_stream_t::i_buffer_pos, httpd_stream_t::i_buffer_size, and httpd_stream_t::p_buffer.
Referenced by httpd_StreamSend().
httpd_ClientDestroy()
static void httpd_ClientDestroy (httpd_client_t * cl) static
References httpd_client_t::answer, httpd_MsgClean(), httpd_client_t::p_buffer, httpd_client_t::query, httpd_client_t::sock, and vlc_tls_Close().
Referenced by httpd_HostDelete(), httpd_UrlDelete(), and httpdLoop().
httpd_ClientInit()
static void httpd_ClientInit (httpd_client_t * cl, mtime_t now) static
References httpd_client_t::answer, httpd_client_t::b_stream_mode, HTTPD_CL_BUFSIZE, HTTPD_CLIENT_RECEIVING, httpd_MsgInit(), httpd_client_t::i_activity_date, httpd_client_t::i_activity_timeout, httpd_client_t::i_buffer, httpd_client_t::i_buffer_size, httpd_client_t::i_keyframe_wait_to_pass, httpd_client_t::i_state, httpd_client_t::p_buffer, httpd_client_t::query, and xmalloc().
Referenced by httpd_ClientNew().
httpd_ClientIP()
char * httpd_ClientIP (const httpd_client_t * cl, char * ip, int * port)
References net_GetPeerAddress(), httpd_client_t::sock, and vlc_tls_GetFD().
Referenced by httpd_HandlerCallBack().
httpd_ClientNew()
static httpd_client_t * httpd_ClientNew (vlc_tls_t * sock, mtime_t now) static
References httpd_ClientInit(), httpd_client_t::i_ref, httpd_client_t::sock, and httpd_client_t::url.
Referenced by httpdLoop().
httpd_ClientRecv()
static void httpd_ClientRecv (httpd_client_t * cl) static
References HTTPD_CLIENT_DEAD, HTTPD_CLIENT_RECEIVE_DONE, HTTPD_MSG_ANSWER, HTTPD_MSG_NONE, httpd_MsgAdd(), httpd_NetRecv(), httpd_NetSend(), HTTPD_PROTO_HTTP, HTTPD_PROTO_HTTP0, HTTPD_PROTO_NONE, HTTPD_PROTO_RTSP, httpd_client_t::i_activity_timeout, httpd_message_t::i_body, httpd_client_t::i_buffer, httpd_client_t::i_buffer_size, httpd_message_t::i_proto, httpd_client_t::i_state, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, msg_type, name, p, httpd_message_t::p_body, httpd_client_t::p_buffer, httpd_message_t::psz_args, httpd_message_t::psz_url, httpd_client_t::query, strcasecmp(), strdup(), and vlc_assert_unreachable.
Referenced by httpdLoop().
httpd_ClientSend()
static void httpd_ClientSend (httpd_client_t * cl) static
References httpd_client_t::answer, httpd_url_t::catch, httpd_url_t::cb, HTTPD_CLIENT_DEAD, HTTPD_CLIENT_SEND_DONE, httpd_MsgClean(), httpd_NetSend(), HTTPD_PROTO_HTTP, httpd_ReasonFromCode(), httpd_message_t::i_body, httpd_message_t::i_body_offset, httpd_client_t::i_buffer, httpd_client_t::i_buffer_size, httpd_message_t::i_headers, httpd_message_t::i_proto, httpd_client_t::i_state, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, httpd_header::name, p, httpd_message_t::p_body, httpd_client_t::p_buffer, httpd_message_t::p_headers, httpd_url_t::p_sys, httpd_client_t::query, httpd_client_t::url, httpd_header::value, and xmalloc().
Referenced by httpdLoop().
httpd_ClientTlsHandshake()
static void httpd_ClientTlsHandshake (httpd_host_t * host, httpd_client_t * cl) static
References HTTPD_CLIENT_DEAD, HTTPD_CLIENT_RECEIVING, HTTPD_CLIENT_TLS_HS_IN, HTTPD_CLIENT_TLS_HS_OUT, httpd_client_t::i_state, httpd_host_t::p_tls, httpd_client_t::sock, and vlc_tls_SessionHandshake().
Referenced by httpdLoop().
httpd_FileCallBack()
static int httpd_FileCallBack (httpd_callback_sys_t * p_sys, httpd_client_t * cl, httpd_message_t * answer, const httpd_message_t * query) static
< No error
< No error
References HTTPD_MSG_ANSWER, HTTPD_MSG_HEAD, HTTPD_MSG_POST, httpd_MsgAdd(), httpd_MsgGet(), HTTPD_PROTO_HTTP, httpd_message_t::i_body, httpd_message_t::i_proto, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, httpd_file_t::mime, httpd_message_t::p_body, httpd_file_t::p_sys, httpd_file_t::pf_fill, httpd_message_t::psz_args, httpd_client_t::query, and VLC_SUCCESS.
Referenced by httpd_FileNew().
httpd_FileDelete()
httpd_file_sys_t * httpd_FileDelete (httpd_file_t * file)
References httpd_UrlDelete(), httpd_file_t::p_sys, and httpd_file_t::url.
httpd_FileNew()
httpd_file_t * httpd_FileNew (httpd_host_t * host, const char * psz_url, const char * psz_mime, const char * psz_user, const char * psz_password, httpd_file_callback_t pf_fill, httpd_file_sys_t * p_sys)
References httpd_FileCallBack(), HTTPD_MSG_GET, HTTPD_MSG_HEAD, HTTPD_MSG_POST, httpd_UrlCatch(), httpd_UrlNew(), httpd_file_t::mime, httpd_file_t::p_sys, httpd_file_t::pf_fill, psz_mime, unlikely, httpd_file_t::url, and vlc_mime_Ext2Mime().
httpd_HandlerCallBack()
static int httpd_HandlerCallBack (httpd_callback_sys_t * p_sys, httpd_client_t * cl, httpd_message_t * answer, const httpd_message_t * query) static
< No error
< No error
References httpd_ClientIP(), HTTPD_MSG_ANSWER, HTTPD_MSG_HEAD, HTTPD_PROTO_NONE, httpd_ReasonFromCode(), httpd_message_t::i_body, httpd_message_t::i_proto, httpd_message_t::i_status, httpd_message_t::i_type, NI_MAXNUMERICHOST, p, httpd_message_t::p_body, httpd_handler_t::p_sys, httpd_handler_t::pf_fill, httpd_message_t::psz_args, httpd_message_t::psz_url, VLC_SUCCESS, xmalloc(), and xrealloc().
Referenced by httpd_HandlerNew().
httpd_HandlerDelete()
void * httpd_HandlerDelete (httpd_handler_t * handler)
References httpd_UrlDelete(), httpd_handler_t::p_sys, and httpd_handler_t::url.
httpd_HandlerNew()
httpd_handler_t * httpd_HandlerNew (httpd_host_t * host, const char * psz_url, const char * psz_user, const char * psz_password, httpd_handler_callback_t pf_fill, void * p_sys)
References httpd_HandlerCallBack(), HTTPD_MSG_GET, HTTPD_MSG_HEAD, HTTPD_MSG_POST, httpd_UrlCatch(), httpd_UrlNew(), httpd_handler_t::p_sys, httpd_handler_t::pf_fill, and httpd_handler_t::url.
httpd_HostCreate()
static httpd_host_t * httpd_HostCreate (vlc_object_t * p_this, const char * hostvar, const char * portvar, vlc_tls_creds_t * p_tls) static
References httpd_host_t::client, httpd_host_t::fds, httpd::host, httpd_HostThread(), httpd_host_t::i_client, httpd::i_host, httpd_host_t::i_ref, httpd_host_t::i_url, httpd_host_t::lock, msg_Err, httpd::mutex, net_ListenClose(), net_ListenTCP, httpd_host_t::nfd, httpd_host_t::p_tls, httpd_host_t::port, TAB_APPEND, httpd_host_t::thread, httpd_host_t::url, var_InheritInteger, var_InheritString, vlc_clone(), vlc_cond_destroy(), vlc_cond_init(), vlc_custom_create, vlc_mutex_destroy(), vlc_mutex_init(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, VLC_THREAD_PRIORITY_LOW, vlc_tls_Delete(), and httpd_host_t::wait.
Referenced by vlc_http_HostNew(), vlc_https_HostNew(), and vlc_rtsp_HostNew().
httpd_HostDelete()
void httpd_HostDelete (httpd_host_t * host)
References httpd_host_t::client, httpd_host_t::fds, httpd::host, httpd_ClientDestroy(), httpd_host_t::i_client, httpd::i_host, httpd_host_t::i_ref, httpd_host_t::i_url, httpd_host_t::lock, msg_Dbg, msg_Err, msg_Warn, httpd::mutex, net_ListenClose(), httpd_host_t::p_tls, httpd_url_t::psz_url, TAB_CLEAN, TAB_REMOVE, httpd_host_t::thread, httpd_host_t::url, vlc_cancel(), vlc_cond_destroy(), vlc_join(), vlc_mutex_destroy(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, vlc_tls_Delete(), and httpd_host_t::wait.
httpd_HostThread()
static void * httpd_HostThread (void * data) static
References httpdLoop(), httpd_host_t::i_ref, httpd_host_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by httpd_HostCreate().
httpd_HtmlError()
static size_t httpd_HtmlError (char ** body, int code, const char * url) static
References asprintf(), httpd_ReasonFromCode(), and vlc_xml_encode().
Referenced by httpd_RedirectCallBack(), and httpdLoop().
httpd_MsgAdd()
void httpd_MsgAdd (httpd_message_t * msg, const char * name, const char * psz_value, ...)
References httpd_message_t::i_headers, httpd_header::name, name, httpd_message_t::p_headers, psz_value, strdup(), us_vasprintf(), and httpd_header::value.
Referenced by httpd_ClientRecv(), httpd_FileCallBack(), httpd_RedirectCallBack(), httpd_StreamCallBack(), and httpdLoop().
httpd_MsgClean()
static void httpd_MsgClean (httpd_message_t * msg) static
References httpd_MsgInit(), httpd_message_t::i_headers, httpd_header::name, httpd_message_t::p_body, httpd_message_t::p_headers, httpd_message_t::psz_args, httpd_message_t::psz_url, and httpd_header::value.
Referenced by httpd_ClientDestroy(), httpd_ClientSend(), and httpdLoop().
httpd_MsgGet()
const char * httpd_MsgGet (const httpd_message_t * msg, const char * name)
References httpd_message_t::i_headers, httpd_header::name, name, httpd_message_t::p_headers, strcasecmp(), and httpd_header::value.
Referenced by httpd_FileCallBack(), httpd_RedirectCallBack(), and httpdLoop().
httpd_MsgInit()
static void httpd_MsgInit (httpd_message_t * msg) static
References httpd_message_t::cl, HTTPD_MSG_NONE, HTTPD_PROTO_NONE, httpd_message_t::i_body, httpd_message_t::i_body_offset, httpd_message_t::i_headers, httpd_message_t::i_proto, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, httpd_message_t::p_body, httpd_message_t::p_headers, httpd_message_t::psz_args, and httpd_message_t::psz_url.
Referenced by httpd_ClientInit(), httpd_MsgClean(), and httpdLoop().
httpd_NetRecv()
static ssize_t httpd_NetRecv (httpd_client_t * cl, uint8_t * p, size_t i_len) static
References p, vlc_tls::readv, and httpd_client_t::sock.
Referenced by httpd_ClientRecv().
httpd_NetSend()
static ssize_t httpd_NetSend (httpd_client_t * cl, const uint8_t * p, size_t i_len) static
References p, httpd_client_t::sock, and vlc_tls::writev.
Referenced by httpd_ClientRecv(), and httpd_ClientSend().
httpd_ReasonFromCode()
static const char * httpd_ReasonFromCode (unsigned i_code) static
References p.
Referenced by httpd_ClientSend(), httpd_HandlerCallBack(), and httpd_HtmlError().
httpd_RedirectCallBack()
static int httpd_RedirectCallBack (httpd_callback_sys_t * p_sys, httpd_client_t * cl, httpd_message_t * answer, const httpd_message_t * query) static
< No error
< No error
References httpd_redirect_t::dst, httpd_HtmlError(), HTTPD_MSG_ANSWER, httpd_MsgAdd(), httpd_MsgGet(), HTTPD_PROTO_HTTP, httpd_message_t::i_body, httpd_message_t::i_proto, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, httpd_message_t::p_body, httpd_client_t::query, and VLC_SUCCESS.
Referenced by httpd_RedirectNew().
httpd_RedirectDelete()
void httpd_RedirectDelete (httpd_redirect_t * rdir)
References httpd_UrlDelete(), and httpd_redirect_t::url.
httpd_RedirectNew()
httpd_redirect_t * httpd_RedirectNew (httpd_host_t * host, const char * psz_url_dst, const char * psz_url_src)
References httpd_redirect_t::dst, HTTPD_MSG_DESCRIBE, HTTPD_MSG_GET, HTTPD_MSG_HEAD, HTTPD_MSG_POST, httpd_RedirectCallBack(), httpd_UrlCatch(), httpd_UrlNew(), unlikely, and httpd_redirect_t::url.
httpd_ServerIP()
char * httpd_ServerIP (const httpd_client_t * cl, char * ip, int * port)
References net_GetSockAddress(), httpd_client_t::sock, and vlc_tls_GetFD().
httpd_StreamCallBack()
static int httpd_StreamCallBack (httpd_callback_sys_t * p_sys, httpd_client_t * cl, httpd_message_t * answer, const httpd_message_t * query) static
< No error
< Unspecified error
< Unspecified error
< Unspecified error
< No error
< No error
References httpd_stream_t::b_has_keyframes, httpd_client_t::b_stream_mode, HTTPD_CL_BUFSIZE, HTTPD_MSG_ANSWER, HTTPD_MSG_HEAD, httpd_MsgAdd(), HTTPD_PROTO_HTTP, httpd_message_t::i_body, httpd_message_t::i_body_offset, httpd_stream_t::i_buffer_last_pos, httpd_stream_t::i_buffer_pos, httpd_stream_t::i_buffer_size, httpd_stream_t::i_header, httpd_message_t::i_headers, httpd_stream_t::i_http_headers, httpd_client_t::i_keyframe_wait_to_pass, httpd_stream_t::i_last_keyframe_seen_pos, httpd_message_t::i_proto, httpd_message_t::i_status, httpd_message_t::i_type, httpd_message_t::i_version, httpd_stream_t::lock, httpd_header::name, httpd_message_t::p_body, httpd_stream_t::p_buffer, httpd_stream_t::p_header, httpd_message_t::p_headers, httpd_stream_t::p_http_headers, httpd_stream_t::psz_mime, strcasecmp(), httpd_header::value, VLC_EGENERIC, vlc_mrand48(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and xmalloc().
Referenced by httpd_StreamNew().
httpd_StreamDelete()
void httpd_StreamDelete (httpd_stream_t * stream)
References httpd_UrlDelete(), httpd_stream_t::i_http_headers, httpd_stream_t::lock, httpd_header::name, httpd_stream_t::p_buffer, httpd_stream_t::p_header, httpd_stream_t::p_http_headers, httpd_stream_t::psz_mime, httpd_stream_t::url, httpd_header::value, and vlc_mutex_destroy().
httpd_StreamHeader()
int httpd_StreamHeader (httpd_stream_t * stream, uint8_t * p_data, int i_data)
< No error
References httpd_stream_t::i_header, httpd_stream_t::lock, httpd_stream_t::p_header, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and xmalloc().
httpd_StreamNew()
httpd_stream_t * httpd_StreamNew (httpd_host_t * host, const char * psz_url, const char * psz_mime, const char * psz_user, const char * psz_password)
References httpd_stream_t::b_has_keyframes, HTTPD_MSG_GET, HTTPD_MSG_HEAD, HTTPD_MSG_POST, httpd_StreamCallBack(), httpd_UrlCatch(), httpd_UrlNew(), httpd_stream_t::i_buffer_last_pos, httpd_stream_t::i_buffer_pos, httpd_stream_t::i_buffer_size, httpd_stream_t::i_header, httpd_stream_t::i_http_headers, httpd_stream_t::i_last_keyframe_seen_pos, httpd_stream_t::lock, httpd_stream_t::p_buffer, httpd_stream_t::p_header, httpd_stream_t::p_http_headers, httpd_stream_t::psz_mime, psz_mime, httpd_stream_t::url, vlc_mime_Ext2Mime(), vlc_mutex_init(), xmalloc(), and xstrdup().
httpd_StreamSend()
int httpd_StreamSend (httpd_stream_t * stream, const block_t * p_block)
< No error
< No error
References httpd_stream_t::b_has_keyframes, BLOCK_FLAG_TYPE_I, httpd_AppendData(), block_t::i_buffer, httpd_stream_t::i_buffer_last_pos, httpd_stream_t::i_buffer_pos, block_t::i_flags, httpd_stream_t::i_last_keyframe_seen_pos, httpd_stream_t::lock, block_t::p_buffer, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
httpd_StreamSetHTTPHeaders()
int httpd_StreamSetHTTPHeaders (httpd_stream_t * p_stream, const httpd_header * p_headers, size_t i_headers)
< Unspecified error
< No error
< Not enough memory
< No error
References httpd_stream_t::i_http_headers, httpd_stream_t::lock, httpd_header::name, name, httpd_stream_t::p_http_headers, strdup(), unlikely, httpd_header::value, vlc_alloc(), VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
httpd_UrlCatch()
int httpd_UrlCatch (httpd_url_t * url, int i_msg, httpd_callback_t cb, httpd_callback_sys_t * p_sys)
< No error
References httpd_url_t::catch, httpd_url_t::cb, httpd_url_t::lock, httpd_url_t::p_sys, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by httpd_FileNew(), httpd_HandlerNew(), httpd_RedirectNew(), and httpd_StreamNew().
httpd_UrlDelete()
void httpd_UrlDelete (httpd_url_t * url)
References httpd_host_t::client, httpd_url_t::host, httpd_ClientDestroy(), httpd_host_t::i_client, httpd_host_t::i_url, httpd_host_t::lock, httpd_url_t::lock, msg_Warn, httpd_url_t::psz_password, httpd_url_t::psz_url, httpd_url_t::psz_user, TAB_REMOVE, httpd_client_t::url, httpd_host_t::url, vlc_mutex_destroy(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by httpd_FileDelete(), httpd_HandlerDelete(), httpd_RedirectDelete(), and httpd_StreamDelete().
httpd_UrlNew()
httpd_url_t * httpd_UrlNew (httpd_host_t * host, const char * psz_url, const char * psz_user, const char * psz_password)
References httpd_url_t::catch, httpd_url_t::cb, httpd_url_t::host, HTTPD_MSG_MAX, httpd_host_t::i_url, httpd_host_t::lock, httpd_url_t::lock, msg_Warn, httpd_url_t::p_sys, httpd_url_t::psz_password, httpd_url_t::psz_url, httpd_url_t::psz_user, TAB_APPEND, httpd_host_t::url, vlc_cond_signal(), vlc_mutex_init(), vlc_mutex_lock(), vlc_mutex_unlock(), httpd_host_t::wait, xmalloc(), and xstrdup().
Referenced by httpd_FileNew(), httpd_HandlerNew(), httpd_RedirectNew(), and httpd_StreamNew().
httpdAuthOk()
static bool httpdAuthOk (const char * user, const char * pass, const char * b64) static
References vlc_b64_decode().
Referenced by httpdLoop().
httpdLoop()
static void httpdLoop (httpd_host_t * host) static
References httpd_client_t::answer, httpd_client_t::b_stream_mode, httpd_url_t::catch, httpd_url_t::cb, httpd_host_t::client, pollfd::events, pollfd::fd, httpd_host_t::fds, HTTPD_CLIENT_DEAD, HTTPD_CLIENT_RECEIVE_DONE, HTTPD_CLIENT_RECEIVING, HTTPD_CLIENT_SEND_DONE, HTTPD_CLIENT_SENDING, HTTPD_CLIENT_TLS_HS_IN, HTTPD_CLIENT_TLS_HS_OUT, HTTPD_CLIENT_WAITING, httpd_ClientDestroy(), httpd_ClientNew(), httpd_ClientRecv(), httpd_ClientSend(), httpd_ClientTlsHandshake(), httpd_HtmlError(), HTTPD_MSG_ANSWER, HTTPD_MSG_NONE, HTTPD_MSG_OPTIONS, httpd_MsgAdd(), httpd_MsgClean(), httpd_MsgGet(), httpd_MsgInit(), HTTPD_PROTO_HTTP, HTTPD_PROTO_NONE, HTTPD_PROTO_RTSP, httpdAuthOk(), httpd_client_t::i_activity_date, httpd_client_t::i_activity_timeout, httpd_message_t::i_body, httpd_message_t::i_body_offset, httpd_client_t::i_buffer, httpd_client_t::i_buffer_size, httpd_host_t::i_client, httpd_message_t::i_proto, httpd_client_t::i_ref, httpd_client_t::i_state, httpd_message_t::i_status, httpd_message_t::i_type, httpd_host_t::i_url, httpd_message_t::i_version, httpd_host_t::lock, mdate(), msg_Err, mutex_cleanup_push, httpd_host_t::nfd, p, httpd_message_t::p_body, httpd_client_t::p_buffer, httpd_url_t::p_sys, httpd_host_t::p_tls, poll(), POLLIN, POLLOUT, httpd_url_t::psz_password, httpd_message_t::psz_url, httpd_url_t::psz_url, httpd_url_t::psz_user, httpd_client_t::query, pollfd::revents, httpd_client_t::sock, strcasecmp(), TAB_APPEND, TAB_REMOVE, unlikely, httpd_client_t::url, httpd_host_t::url, vlc_accept(), vlc_cleanup_pop, vlc_close(), vlc_cond_wait(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), vlc_savecancel(), vlc_strerror_c(), vlc_tls_GetFD(), vlc_tls_ServerSessionCreate(), vlc_tls_SessionDelete(), vlc_tls_SocketOpen(), httpd_host_t::wait, and xmalloc().
Referenced by httpd_HostThread().
vlc_http_HostNew()
httpd_host_t * vlc_http_HostNew (vlc_object_t * p_this)
References httpd_HostCreate().
vlc_https_HostNew()
httpd_host_t * vlc_https_HostNew (vlc_object_t * obj)
References httpd_HostCreate(), msg_Err, var_InheritString, and vlc_tls_ServerCreate().
vlc_rtsp_HostNew()
httpd_host_t * vlc_rtsp_HostNew (vlc_object_t * p_this)
References httpd_HostCreate().
Variable Documentation
httpd
struct httpd httpd = { PTHREAD_MUTEX_INITIALIZER , NULL, 0 } static
i_proto
int i_proto
i_type
int i_type
Referenced by AddCallback(), config_ChainParse(), config_LoadCmdLine(), Control(), ControlIsSeekRequest(), ControlNav(), ControlRelease(), DelCallback(), dialog_add_locked(), dialog_display_question_va(), dialog_wait(), find_sorting_fn(), input_ControlPush(), input_item_slave_GetType(), input_item_slave_New(), input_SlaveSourceAdd(), input_UpdateStatistic(), MainLoop(), parse_public_key(), playlist_preparser_Push(), playlist_RecursiveNodeSort(), Trigger(), Trigger(), TriggerInstanceState(), var_Create(), var_Inherit(), var_OptionParse(), var_Type(), vlc_dialog_wait_question(), vlc_dialog_wait_question_va(), and vlc_readdir_helper_additem().
[struct]
const struct { ... } msg_type[]
Initial value:
=
{
    { "OPTIONS",       HTTPD_MSG_OPTIONS,      HTTPD_PROTO_RTSP },
    { "DESCRIBE",      HTTPD_MSG_DESCRIBE,     HTTPD_PROTO_RTSP },
    { "SETUP",         HTTPD_MSG_SETUP,        HTTPD_PROTO_RTSP },
    { "PLAY",          HTTPD_MSG_PLAY,         HTTPD_PROTO_RTSP },
    { "PAUSE",         HTTPD_MSG_PAUSE,        HTTPD_PROTO_RTSP },
    { "GET_PARAMETER", HTTPD_MSG_GETPARAMETER, HTTPD_PROTO_RTSP },
    { "TEARDOWN",      HTTPD_MSG_TEARDOWN,     HTTPD_PROTO_RTSP },
    { "GET",           HTTPD_MSG_GET,          HTTPD_PROTO_HTTP },
    { "HEAD",          HTTPD_MSG_HEAD,         HTTPD_PROTO_HTTP },
    { "POST",          HTTPD_MSG_POST,         HTTPD_PROTO_HTTP },
    { "",              HTTPD_MSG_NONE,         HTTPD_PROTO_NONE }
}
Referenced by httpd_ClientRecv().
name
const char name[16]
Referenced by AboveCallback(), aout_FiltersNew(), aout_HotplugNotify(), aout_HotplugReport(), AppendFilter(), AppendRemapFilter(), AutoScaleCallback(), cmp_entity(), config_ChainParse(), config_FindConfig(), config_GetIntChoices(), config_GetPszChoices(), config_IsSafe(), config_LoadCmdLine(), config_Write(), CreateFilter(), demux_IsPathExtension(), filter_AddProxyCallbacks(), filter_chain_AppendFilter(), filter_chain_AppendFromString(), filter_chain_AppendInner(), filter_DelProxyCallbacks(), FindName(), getaddrinfo(), getAppDependentDir(), getenv(), hpack_append_hdr(), hpack_decode(), hpack_decode_hdr_index(), hpack_decode_hdr_indexed(), hpack_decode_hdr_noindex(), hpack_decode_tbl_update(), hpack_encode_hdr_neverindex(), httpd_ClientRecv(), httpd_MsgAdd(), httpd_MsgGet(), httpd_StreamSetHTTPHeaders(), info_category_AddInfo(), info_category_DeleteInfo(), info_category_FindInfo(), info_category_New(), info_category_VaAddInfo(), info_New(), input_ControlVarStop(), input_ExtractAttachmentAndCacheArt(), input_item_AddOpaque(), libvlc_InternalActionsInit(), libvlc_InternalAddIntf(), makeipv4info(), module_find(), module_list_cap(), module_match_name(), module_need(), playlist_EnableAudioFilter(), playlist_ServicesDiscoveryRemove(), process_list(), sdp_AddAttribute(), sdp_AddAttribute(), SelectClockSource(), sout_AccessOutNew(), sout_StreamChainNew(), stream_FilterChainNew(), stream_HasExtension(), system_ConfigureDbus(), ThreadChangeFilters(), TriggerCallback(), TriggerListCallback(), var_Copy(), var_CopyDevice(), var_GetCoords(), var_InheritAddress(), var_InheritBool(), var_InheritFloat(), var_InheritInteger(), var_InheritString(), var_NAndInteger(), var_OrInteger(), var_SetCoords(), vlc_actions_get_id(), vlc_demux_chained_New(), vlc_getaddrinfo_i11e(), vlc_gl_Create(), vlc_gl_GetProcAddress(), vlc_http_msg_add_header(), vlc_http_msg_find_header(), vlc_http_msg_get_header(), vlc_http_msg_get_time(), vlc_http_msg_h2_headers(), vlc_http_msg_headers(), vlc_http_msg_vadd_header(), vlc_https_connect(), vlc_keycode2str(), vlc_module_load(), vlc_module_store(), vlc_object_get_name(), vlc_object_set_name(), vlc_plugin_desc_cb(), vlc_plugin_get_symbol(), vlc_plugin_gpa_cb(), vlc_sd_probe_Add(), vlc_str2keycode(), vlc_strfinput(), vlc_tls_SocketOpenTCP(), vlc_tls_SocketOpenTLS(), vout_snapshot_SaveImage(), vsdp_AddAttribute(), WallPaperCallback(), and ZoomCallback().