VLC: src/network/http_auth.c File Reference
http_auth.c File Reference
Functions
static char * AuthGetParam (const char *psz_header, const char *psz_param)
static char * AuthGetParamNoQuotes (const char *psz_header, const char *psz_param)
static char * GenerateCnonce ()
static char * AuthDigest (vlc_object_t *p_this, vlc_http_auth_t *p_auth, const char *psz_method, const char *psz_path, const char *psz_username, const char *psz_password)
void vlc_http_auth_ParseWwwAuthenticateHeader (vlc_object_t *p_this, vlc_http_auth_t *p_auth, const char *psz_header)
int vlc_http_auth_ParseAuthenticationInfoHeader (vlc_object_t *p_this, vlc_http_auth_t *p_auth, const char *psz_header, const char *psz_method, const char *psz_path, const char *psz_username, const char *psz_password)
char * vlc_http_auth_FormatAuthorizationHeader (vlc_object_t *p_this, vlc_http_auth_t *p_auth, const char *psz_method, const char *psz_path, const char *psz_username, const char *psz_password)
void vlc_http_auth_Init (vlc_http_auth_t *p_auth)
void vlc_http_auth_Deinit (vlc_http_auth_t *p_auth)
Function Documentation
AuthDigest()
static char * AuthDigest (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_method, const char * psz_path, const char * psz_username, const char * psz_password) static
References AddMD5(), EndMD5(), vlc_http_auth_t::i_nonce, InitMD5(), msg_Warn, vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_HA1, psz_md5_hash(), vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and strdup().
Referenced by vlc_http_auth_FormatAuthorizationHeader(), and vlc_http_auth_ParseAuthenticationInfoHeader().
AuthGetParam()
static char * AuthGetParam (const char * psz_header, const char * psz_param) static
References strdup(), and strndup().
Referenced by vlc_http_auth_ParseAuthenticationInfoHeader(), and vlc_http_auth_ParseWwwAuthenticateHeader().
AuthGetParamNoQuotes()
static char * AuthGetParamNoQuotes (const char * psz_header, const char * psz_param) static
References strdup(), and strndup().
Referenced by vlc_http_auth_ParseAuthenticationInfoHeader(), and vlc_http_auth_ParseWwwAuthenticateHeader().
GenerateCnonce()
static char * GenerateCnonce () static
References AddMD5(), EndMD5(), InitMD5(), psz_md5_hash(), and vlc_rand_bytes().
Referenced by vlc_http_auth_FormatAuthorizationHeader().
vlc_http_auth_Deinit()
void vlc_http_auth_Deinit (vlc_http_auth_t * p_auth)
References vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_domain, vlc_http_auth_t::psz_HA1, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_http_auth_t::psz_stale.
vlc_http_auth_FormatAuthorizationHeader()
char * vlc_http_auth_FormatAuthorizationHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_method, const char * psz_path, const char * psz_username, const char * psz_password)
References asprintf(), AuthDigest(), GenerateCnonce(), vlc_http_auth_t::i_nonce, msg_Err, vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_b64_encode().
vlc_http_auth_Init()
void vlc_http_auth_Init (vlc_http_auth_t * p_auth)
vlc_http_auth_ParseAuthenticationInfoHeader()
int vlc_http_auth_ParseAuthenticationInfoHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_header, const char * psz_method, const char * psz_path, const char * psz_username, const char * psz_password)
< No error
< Unspecified error
< Unspecified error
< Unspecified error
References AuthDigest(), AuthGetParam(), AuthGetParamNoQuotes(), vlc_http_auth_t::i_nonce, msg_Err, msg_Warn, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_qop, VLC_EGENERIC, and VLC_SUCCESS.
vlc_http_auth_ParseWwwAuthenticateHeader()
void vlc_http_auth_ParseWwwAuthenticateHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_header)
References AuthGetParam(), AuthGetParamNoQuotes(), vlc_http_auth_t::i_nonce, msg_Dbg, msg_Warn, vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_domain, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_http_auth_t::psz_stale.