VLC: src/misc/image.c File Reference
image.c File Reference
This file contains the functions to handle the image_handler_t type.
Functions
static picture_t * ImageRead (image_handler_t *, block_t *, const video_format_t *, video_format_t *)
static picture_t * ImageReadUrl (image_handler_t *, const char *, video_format_t *, video_format_t *)
static block_t * ImageWrite (image_handler_t *p_image, picture_t *p_pic, const video_format_t *p_fmt_in, const video_format_t *p_fmt_out)
Write an image.
static int ImageWriteUrl (image_handler_t *, picture_t *, const video_format_t *, video_format_t *, const char *)
static picture_t * ImageConvert (image_handler_t *p_image, picture_t *p_pic, const video_format_t *p_fmt_in, video_format_t *p_fmt_out)
Convert an image to a different format.
static decoder_t * CreateDecoder (vlc_object_t *, const video_format_t *)
static void DeleteDecoder (decoder_t *)
static encoder_t * CreateEncoder (vlc_object_t *, const video_format_t *, const video_format_t *)
static void DeleteEncoder (encoder_t *)
static filter_t * CreateFilter (vlc_object_t *, const es_format_t *, const video_format_t *)
static void DeleteFilter (filter_t *)
vlc_fourcc_t image_Type2Fourcc (const char *)
vlc_fourcc_t image_Ext2Fourcc (const char *)
image_handler_t * image_HandlerCreate (vlc_object_t *p_this)
Create an image_handler_t instance.
void image_HandlerDelete (image_handler_t *p_image)
Delete the image_handler_t instance.
static int ImageQueueVideo (decoder_t *p_dec, picture_t *p_pic)
Read an image.
static bool BitMapFormatIsSimilar (const video_format_t *f1, const video_format_t *f2)
vlc_fourcc_t image_Mime2Fourcc (const char *psz_mime)
static int video_update_format (decoder_t *p_dec)
static picture_t * video_new_buffer (decoder_t *p_dec)
static picture_t * filter_new_picture (filter_t *p_filter)
Variables
struct {
vlc_fourcc_t i_codec
const char psz_ext [7]
} ext_table []
Misc functions.
struct {
vlc_fourcc_t i_codec
const char * psz_mime
} mime_table []
Detailed Description
This file contains the functions to handle the image_handler_t type.
Function Documentation
BitMapFormatIsSimilar()
static bool BitMapFormatIsSimilar (const video_format_t * f1, const video_format_t * f2) static
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_rmask, video_format_FixRgb(), VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, and VLC_CODEC_RGB32.
Referenced by ImageWrite().
CreateDecoder()
static decoder_t * CreateDecoder (vlc_object_t * p_this, const video_format_t * fmt) static
References decoder_t::b_frame_drop_allowed, DeleteDecoder(), es_format_Init(), es_format_InitFromVideo(), decoder_t::fmt_in, decoder_t::fmt_out, es_format_t::i_codec, module_need, msg_Err, decoder_t::p_module, decoder_t::pf_vout_buffer_new, decoder_t::pf_vout_format_update, VIDEO_ES, video_new_buffer(), video_update_format(), and vlc_custom_create.
Referenced by ImageRead().
CreateEncoder()
static encoder_t * CreateEncoder (vlc_object_t * p_this, const video_format_t * fmt_in, const video_format_t * fmt_out) static
References DeleteEncoder(), es_format_InitFromVideo(), encoder_t::fmt_in, encoder_t::fmt_out, video_format_t::i_chroma, es_format_t::i_codec, video_format_t::i_frame_rate, video_format_t::i_frame_rate_base, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, module_need, msg_Err, encoder_t::p_module, sout_EncoderCreate, and es_format_t::video.
Referenced by ImageWrite().
CreateFilter()
static filter_t * CreateFilter (vlc_object_t * p_this, const es_format_t * p_fmt_in, const video_format_t * p_fmt_out) static
References filter_owner_t::buffer_new, DeleteFilter(), es_format_Copy(), filter_new_picture(), filter_t::fmt_in, filter_t::fmt_out, video_format_t::i_chroma, es_format_t::i_codec, video_format_t::i_x_offset, video_format_t::i_y_offset, module_need, msg_Dbg, filter_t::owner, filter_t::p_module, es_format_t::video, filter_owner_t::video, video_format_Copy(), and vlc_custom_create.
Referenced by ImageConvert(), ImageRead(), and ImageWrite().
DeleteDecoder()
static void DeleteDecoder (decoder_t * p_dec) static
References es_format_Clean(), decoder_t::fmt_in, decoder_t::fmt_out, module_unneed, decoder_t::p_description, decoder_t::p_module, vlc_meta_Delete(), and vlc_object_release.
Referenced by CreateDecoder(), image_HandlerDelete(), and ImageRead().
DeleteEncoder()
static void DeleteEncoder (encoder_t * p_enc) static
References es_format_Clean(), encoder_t::fmt_in, encoder_t::fmt_out, module_unneed, encoder_t::p_module, and vlc_object_release.
Referenced by CreateEncoder(), image_HandlerDelete(), and ImageWrite().
DeleteFilter()
static void DeleteFilter (filter_t * p_filter) static
References es_format_Clean(), filter_t::fmt_in, filter_t::fmt_out, module_unneed, filter_t::p_module, and vlc_object_release.
Referenced by CreateFilter(), image_HandlerDelete(), ImageConvert(), ImageRead(), and ImageWrite().
filter_new_picture()
static picture_t * filter_new_picture (filter_t * p_filter) static
References filter_t::fmt_out, picture_NewFromFormat(), and es_format_t::video.
Referenced by CreateFilter().
image_Ext2Fourcc()
vlc_fourcc_t image_Ext2Fourcc (const char * psz_name)
References image_Type2Fourcc(), and psz_name.
Referenced by ImageReadUrl(), and ImageWriteUrl().
image_HandlerCreate()
image_handler_t * image_HandlerCreate (vlc_object_t * p_this)
Create an image_handler_t instance.
References ImageConvert(), ImageRead(), ImageReadUrl(), ImageWrite(), ImageWriteUrl(), image_handler_t::outfifo, image_handler_t::p_parent, image_handler_t::pf_convert, image_handler_t::pf_read, image_handler_t::pf_read_url, image_handler_t::pf_write, image_handler_t::pf_write_url, and picture_fifo_New().
image_HandlerDelete()
void image_HandlerDelete (image_handler_t * p_image)
Delete the image_handler_t instance.
References DeleteDecoder(), DeleteEncoder(), DeleteFilter(), image_handler_t::outfifo, image_handler_t::p_dec, image_handler_t::p_enc, image_handler_t::p_filter, and picture_fifo_Delete().
Referenced by picture_Export(), spuregion_CreateFromPicture(), and subpicture_NewFromPicture().
image_Mime2Fourcc()
vlc_fourcc_t image_Mime2Fourcc (const char * psz_mime)
References mime_table, and psz_mime.
Referenced by ImageReadUrl().
image_Type2Fourcc()
vlc_fourcc_t image_Type2Fourcc (const char * psz_type)
References ARRAY_SIZE, ext_table, i_codec, psz_ext, and strcasecmp().
Referenced by image_Ext2Fourcc(), and vout_GetSnapshot().
ImageConvert()
static picture_t * ImageConvert (image_handler_t * p_image, picture_t * p_pic, const video_format_t * p_fmt_in, video_format_t * p_fmt_out) static
Convert an image to a different format.
References CreateFilter(), DeleteFilter(), es_format_Init(), filter_NewPicture(), filter_t::fmt_in, filter_t::fmt_out, video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, image_handler_t::p_filter, image_handler_t::p_parent, filter_t::pf_video_filter, picture_Copy(), picture_Hold(), picture_Release(), es_format_t::video, and VIDEO_ES.
Referenced by image_HandlerCreate().
ImageQueueVideo()
static int ImageQueueVideo (decoder_t * p_dec, picture_t * p_pic) static
Read an image.
References image_handler_t::outfifo, decoder_t::p_queue_ctx, and picture_fifo_Push().
Referenced by ImageRead().
ImageRead()
static picture_t * ImageRead (image_handler_t * p_image, block_t * p_block, const video_format_t * p_fmt_in, video_format_t * p_fmt_out) static
< No error
References block_Release(), CreateDecoder(), CreateFilter(), DeleteDecoder(), DeleteFilter(), decoder_t::fmt_in, filter_t::fmt_in, decoder_t::fmt_out, filter_t::fmt_out, es_format_t::i_cat, video_format_t::i_chroma, es_format_t::i_codec, block_t::i_dts, video_format_t::i_height, block_t::i_pts, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, ImageQueueVideo(), mdate(), msg_Warn, image_handler_t::outfifo, image_handler_t::p_dec, image_handler_t::p_filter, image_handler_t::p_parent, decoder_t::p_queue_ctx, decoder_t::pf_decode, decoder_t::pf_queue_video, filter_t::pf_video_filter, picture_fifo_Pop(), picture_Release(), es_format_t::video, VIDEO_ES, video_format_Clean(), video_format_Copy(), and VLCDEC_SUCCESS.
Referenced by image_HandlerCreate(), and ImageReadUrl().
ImageReadUrl()
static picture_t * ImageReadUrl (image_handler_t * p_image, const char * psz_url, video_format_t * p_fmt_in, video_format_t * p_fmt_out) static
References video_format_t::i_chroma, image_Ext2Fourcc(), image_Mime2Fourcc(), ImageRead(), msg_Dbg, image_handler_t::p_parent, psz_mime, stream_MimeType(), vlc_stream_Block(), vlc_stream_Delete(), vlc_stream_GetSize(), and vlc_stream_NewURL.
Referenced by image_HandlerCreate().
ImageWrite()
static block_t * ImageWrite (image_handler_t * p_image, picture_t * p_pic, const video_format_t * p_fmt_in, const video_format_t * p_fmt_out) static
Write an image.
References BitMapFormatIsSimilar(), CreateEncoder(), CreateFilter(), DeleteEncoder(), DeleteFilter(), es_format_Init(), encoder_t::fmt_in, filter_t::fmt_in, encoder_t::fmt_out, filter_t::fmt_out, video_format_t::i_chroma, es_format_t::i_codec, video_format_t::i_height, video_format_t::i_width, likely, msg_Dbg, image_handler_t::p_enc, image_handler_t::p_filter, image_handler_t::p_parent, encoder_t::pf_encode_video, filter_t::pf_video_filter, picture_Hold(), picture_Release(), es_format_t::video, and VIDEO_ES.
Referenced by image_HandlerCreate(), and ImageWriteUrl().
ImageWriteUrl()
static int ImageWriteUrl (image_handler_t * p_image, picture_t * p_pic, const video_format_t * p_fmt_in, video_format_t * p_fmt_out, const char * psz_url) static
< Unspecified error
< Unspecified error
< No error
References block_Release(), block_t::i_buffer, video_format_t::i_chroma, image_Ext2Fourcc(), ImageWrite(), msg_Err, block_t::p_buffer, image_handler_t::p_parent, VLC_EGENERIC, vlc_fopen(), vlc_strerror_c(), and VLC_SUCCESS.
Referenced by image_HandlerCreate().
video_new_buffer()
static picture_t * video_new_buffer (decoder_t * p_dec) static
References decoder_t::fmt_out, picture_NewFromFormat(), and es_format_t::video.
Referenced by CreateDecoder().
video_update_format()
static int video_update_format (decoder_t * p_dec) static
References decoder_t::fmt_out, video_format_t::i_chroma, es_format_t::i_codec, and es_format_t::video.
Referenced by CreateDecoder().
Variable Documentation
[struct]
const struct { ... } ext_table[]
Initial value:
=
{
    { ( ((uint32_t)'j') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'e') << 16 ) | ( ((uint32_t)'g') << 24 ) ) ,              "jpeg" },
    { ( ((uint32_t)'j') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'e') << 16 ) | ( ((uint32_t)'g') << 24 ) ) ,              "jpg"  },
    { ( ((uint32_t)'M') | ( ((uint32_t)'J') << 8 )   | ( ((uint32_t)'L') << 16 ) | ( ((uint32_t)'S') << 24 ) ) ,            "ljpg" },
    { ( ((uint32_t)'B') | ( ((uint32_t)'P') << 8 )   | ( ((uint32_t)'G') << 16 ) | ( ((uint32_t)0xFB) << 24 ) ) ,               "bpg" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'g') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "png" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'g') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "pgm" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'g') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)'y') << 24 ) ) ,            "pgmyuv" },
    {  ( ((uint32_t)'p') | ( ((uint32_t)'b') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "pbm" },
    {  ( ((uint32_t)'p') | ( ((uint32_t)'a') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "pam" },
    { ( ((uint32_t)'t') | ( ((uint32_t)'g') << 8 )   | ( ((uint32_t)'a') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,             "tga" },
    { ( ((uint32_t)'b') | ( ((uint32_t)'m') << 8 )   | ( ((uint32_t)'p') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "bmp" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "pnm" },
    {  ( ((uint32_t)'x') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "xpm" },
    {  ( ((uint32_t)'x') | ( ((uint32_t)'c') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "xcf" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'c') << 8 )   | ( ((uint32_t)'x') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "pcx" },
    { ( ((uint32_t)'g') | ( ((uint32_t)'i') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "gif" },
    { ( ((uint32_t)'s') | ( ((uint32_t)'v') << 8 )   | ( ((uint32_t)'g') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "svg" },
    { ( ((uint32_t)'t') | ( ((uint32_t)'i') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)'f') << 24 ) ) ,              "tif" },
    { ( ((uint32_t)'t') | ( ((uint32_t)'i') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)'f') << 24 ) ) ,              "tiff" },
    {  ( ((uint32_t)'l') | ( ((uint32_t)'b') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "lbm" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "ppm" },
}
Misc functions.
Referenced by image_Type2Fourcc().
i_codec
vlc_fourcc_t i_codec
Referenced by es_format_Change(), es_format_Init(), and image_Type2Fourcc().
[struct]
const struct { ... } mime_table[]
Initial value:
=
{
    { ( ((uint32_t)'b') | ( ((uint32_t)'m') << 8 )   | ( ((uint32_t)'p') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/bmp" },
    { ( ((uint32_t)'b') | ( ((uint32_t)'m') << 8 )   | ( ((uint32_t)'p') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-bmp" },
    { ( ((uint32_t)'b') | ( ((uint32_t)'m') << 8 )   | ( ((uint32_t)'p') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-bitmap" },
    { ( ((uint32_t)'b') | ( ((uint32_t)'m') << 8 )   | ( ((uint32_t)'p') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-ms-bmp" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-portable-anymap" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-portable-bitmap" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-portable-graymap" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/x-portable-pixmap" },
    { ( ((uint32_t)'g') | ( ((uint32_t)'i') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/gif" },
    { ( ((uint32_t)'j') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'e') << 16 ) | ( ((uint32_t)'g') << 24 ) ) ,              "image/jpeg" },
    { ( ((uint32_t)'B') | ( ((uint32_t)'P') << 8 )   | ( ((uint32_t)'G') << 16 ) | ( ((uint32_t)0xFB) << 24 ) ) ,               "image/bpg" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'c') << 8 )   | ( ((uint32_t)'x') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/pcx" },
    { ( ((uint32_t)'p') | ( ((uint32_t)'n') << 8 )   | ( ((uint32_t)'g') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/png" },
    { ( ((uint32_t)'s') | ( ((uint32_t)'v') << 8 )   | ( ((uint32_t)'g') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,               "image/svg+xml" },
    { ( ((uint32_t)'t') | ( ((uint32_t)'i') << 8 )   | ( ((uint32_t)'f') << 16 ) | ( ((uint32_t)'f') << 24 ) ) ,              "image/tiff" },
    { ( ((uint32_t)'t') | ( ((uint32_t)'g') << 8 )   | ( ((uint32_t)'a') << 16 ) | ( ((uint32_t)' ') << 24 ) ) ,             "image/x-tga" },
    {  ( ((uint32_t)'x') | ( ((uint32_t)'p') << 8 )   | ( ((uint32_t)'m') << 16 ) | ( ((uint32_t)' ') << 24 ) ) , "image/x-xpixmap" },
    { 0, NULL }
}
Referenced by image_Mime2Fourcc().
psz_ext
const char psz_ext[7]
Referenced by ArtCacheName(), demux_IsPathExtension(), demux_NewAdvanced(), image_Type2Fourcc(), input_item_IsMaster(), input_item_slave_GetType(), rdh_get_slave_priority(), rdh_should_match_idx(), and subtitles_Detect().
psz_mime
const char* psz_mime
Referenced by httpd_FileNew(), httpd_StreamNew(), image_Mime2Fourcc(), ImageReadUrl(), and vlc_input_attachment_New().