VLC: src/input/info.h File Reference
info.h File Reference
Functions
static info_t * info_New (const char *name, const char *value)
static void info_Delete (info_t *i)
static info_category_t * info_category_New (const char *name)
static info_t * info_category_FindInfo (const info_category_t *cat, int *index, const char *name)
static void info_category_ReplaceInfo (info_category_t *cat, info_t *info)
static info_t * info_category_VaAddInfo (info_category_t *cat, const char *name, const char *format, va_list args)
static info_t * info_category_AddInfo (info_category_t *cat, const char *name, const char *format,...)
static int info_category_DeleteInfo (info_category_t *cat, const char *name)
static void info_category_Delete (info_category_t *cat)
Function Documentation
info_category_AddInfo()
static info_t * info_category_AddInfo (info_category_t * cat, const char * name, const char * format, ...) inline static
References info_category_VaAddInfo(), and name.
Referenced by EsOutProgramMeta(), and EsOutUpdateInfo().
info_category_Delete()
static void info_category_Delete (info_category_t * cat) inline static
References info_category_t::i_infos, info_Delete(), info_category_t::pp_infos, and info_category_t::psz_name.
Referenced by input_item_DelInfo(), input_item_MergeInfos(), input_item_Release(), and input_item_ReplaceInfos().
info_category_DeleteInfo()
static int info_category_DeleteInfo (info_category_t * cat, const char * name) inline static
< No error
< Unspecified error
References info_category_t::i_infos, info_category_FindInfo(), info_Delete(), name, info_category_t::pp_infos, TAB_ERASE, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by input_item_DelInfo().
info_category_FindInfo()
static info_t * info_category_FindInfo (const info_category_t * cat, int * index, const char * name) inline static
References info_category_t::i_infos, name, info_category_t::pp_infos, and info_t::psz_name.
Referenced by info_category_DeleteInfo(), info_category_ReplaceInfo(), info_category_VaAddInfo(), and input_item_GetInfo().
info_category_New()
static info_category_t * info_category_New (const char * name) inline static
References info_category_t::i_infos, name, info_category_t::pp_infos, info_category_t::psz_name, and strdup().
Referenced by EsOutProgramMeta(), EsOutUpdateInfo(), and InputItemVaAddInfo().
info_category_ReplaceInfo()
static void info_category_ReplaceInfo (info_category_t * cat, info_t * info) inline static
References info_category_t::i_infos, info_category_FindInfo(), info_Delete(), info_category_t::pp_infos, info_t::psz_name, and TAB_APPEND.
Referenced by input_item_MergeInfos().
info_category_VaAddInfo()
static info_t * info_category_VaAddInfo (info_category_t * cat, const char * name, const char * format, va_list args) inline static
References info_category_t::i_infos, info_category_FindInfo(), info_New(), name, info_category_t::pp_infos, info_t::psz_value, TAB_APPEND, and vasprintf().
Referenced by info_category_AddInfo(), and InputItemVaAddInfo().
info_Delete()
static void info_Delete (info_t * i) inline static
References info_t::psz_name, and info_t::psz_value.
Referenced by info_category_Delete(), info_category_DeleteInfo(), and info_category_ReplaceInfo().
info_New()
static info_t * info_New (const char * name, const char * value) inline static
References name, info_t::psz_name, info_t::psz_value, and strdup().
Referenced by info_category_VaAddInfo().