VLC: src/input/input_interface.h File Reference
input_interface.h File Reference
Enumerations
enum input_statistic_t {
INPUT_STATISTIC_DECODED_VIDEO , INPUT_STATISTIC_DECODED_AUDIO , INPUT_STATISTIC_DECODED_SUBTITLE , INPUT_STATISTIC_SENT_PACKET ,
INPUT_STATISTIC_SENT_BYTE
}
Functions
void input_item_SignalPreparseEnded (input_item_t *p_i, int new_status)
void input_item_SetPreparsed (input_item_t *p_i, bool b_preparsed)
void input_item_SetArtNotFound (input_item_t *p_i, bool b_not_found)
void input_item_SetArtFetched (input_item_t *p_i, bool b_art_fetched)
void input_item_SetEpg (input_item_t *p_item, const vlc_epg_t *p_epg, bool)
void input_item_ChangeEPGSource (input_item_t *p_item, int i_source_id)
void input_item_SetEpgEvent (input_item_t *p_item, const vlc_epg_event_t *p_epg_evt)
void input_item_SetEpgTime (input_item_t *, int64_t)
void input_item_SetEpgOffline (input_item_t *)
input_thread_t * input_CreatePreparser (vlc_object_t *obj, input_item_t *item)
Creates an item preparser.
input_stats_t * stats_NewInputStats (input_thread_t *p_input)
void input_resource_TerminateSout (input_resource_t *p_resource)
This function deletes the current sout in the resources.
bool input_resource_HasVout (input_resource_t *p_resource)
This function return true if there is at least one vout in the resources.
void input_UpdateStatistic (input_thread_t *, input_statistic_t, int i_delta)
It will update internal input statistics from external sources.
Enumeration Type Documentation
input_statistic_t
enum input_statistic_t
Enumerator
INPUT_STATISTIC_DECODED_VIDEO
INPUT_STATISTIC_DECODED_AUDIO
INPUT_STATISTIC_DECODED_SUBTITLE
INPUT_STATISTIC_SENT_PACKET
INPUT_STATISTIC_SENT_BYTE
Function Documentation
input_CreatePreparser()
input_thread_t * input_CreatePreparser (vlc_object_t * obj, input_item_t * item)
Creates an item preparser.
Creates an input thread to preparse an item. The input needs to be started with input_Start() afterwards.
Parameters
obj parent object
item input item to preparse
Returns
an input thread or NULL on error
References Create().
Referenced by PreparserOpenInput().
input_item_ChangeEPGSource()
void input_item_ChangeEPGSource (input_item_t * p_item, int i_source_id)
References vlc_epg_t::b_present, input_item_t::i_epg, vlc_epg_t::i_source_id, input_item_t::lock, input_item_t::p_epg_table, input_item_t::pp_epg, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramSelect(), and input_item_SetEpgOffline().
input_item_SetArtFetched()
void input_item_SetArtFetched (input_item_t * p_i, bool b_art_fetched)
References ITEM_ART_FETCHED, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Downloader().
input_item_SetArtNotFound()
void input_item_SetArtNotFound (input_item_t * p_i, bool b_not_found)
References ITEM_ART_NOTFOUND, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by SearchLocal(), and SearchNetwork().
input_item_SetEpg()
void input_item_SetEpg (input_item_t * p_item, const vlc_epg_t * p_epg, bool b_current_source)
References asprintf(), vlc_epg_t::b_present, input_item_t::event_manager, vlc_epg_event_t::i_duration, input_item_t::i_epg, vlc_epg_t::i_event, vlc_epg_t::i_id, vlc_epg_t::i_source_id, vlc_epg_event_t::i_start, input_item_DelInfo(), localtime_r(), input_item_t::lock, input_item_t::p_epg_table, input_item_t::pp_epg, vlc_epg_t::pp_event, vlc_epg_event_t::psz_description, vlc_epg_event_t::psz_name, vlc_epg_t::psz_name, vlc_epg_event_t::psz_short_description, TAB_APPEND, vlc_epg_Delete(), vlc_epg_Duplicate(), vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramEpg().
input_item_SetEpgEvent()
void input_item_SetEpgEvent (input_item_t * p_item, const vlc_epg_event_t * p_epg_evt)
References input_item_t::event_manager, input_item_t::i_epg, vlc_epg_t::i_event, vlc_epg_event_t::i_id, input_item_t::lock, vlc_epg_t::p_current, input_item_t::pp_epg, vlc_epg_t::pp_event, vlc_epg_event_Delete(), vlc_epg_event_Duplicate(), vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramEpgEvent().
input_item_SetEpgOffline()
void input_item_SetEpgOffline (input_item_t * p_item)
References asprintf(), input_item_t::event_manager, input_item_t::i_epg, input_item_ChangeEPGSource(), input_item_DelInfo(), input_item_t::lock, input_item_t::pp_epg, vlc_epg_t::psz_name, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutTerminate().
input_item_SetEpgTime()
void input_item_SetEpgTime (input_item_t * p_item, int64_t i_time)
References input_item_t::i_epg_time, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutEpgTime().
input_item_SetPreparsed()
void input_item_SetPreparsed (input_item_t * p_i, bool b_preparsed)
References input_item_t::event_manager, ITEM_PREPARSED, input_item_t::lock, input_item_t::p_meta, vlc_event_send(), vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutMeta(), PreparserCloseInput(), and SetPreparsed().
input_item_SignalPreparseEnded()
void input_item_SignalPreparseEnded (input_item_t * p_i, int new_status)
References input_item_t::event_manager, and vlc_event_send().
Referenced by playlist_preparser_Push(), PreparserCloseInput(), PreparserOpenInput(), and SetPreparsed().
input_resource_HasVout()
bool input_resource_HasVout (input_resource_t * p_resource)
This function return true if there is at least one vout in the resources.
It can only be called on detached resources.
References input_resource_t::lock, input_resource_t::p_input, input_resource_t::p_vout_free, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Thread().
input_resource_TerminateSout()
void input_resource_TerminateSout (input_resource_t * p_resource)
This function deletes the current sout in the resources.
References input_resource_RequestSout().
Referenced by input_resource_Terminate(), LoopInput(), and vlm_ControlMediaInstanceStart().
input_UpdateStatistic()
void input_UpdateStatistic (input_thread_t * p_input, input_statistic_t i_type, int i_delta)
It will update internal input statistics from external sources.
XXX For now, the only one allowed to do it is stream_out and input core.
References input_thread_private_t::counters_lock, I, i_type, INIT_S, input_priv(), INPUT_STATISTIC_DECODED_AUDIO, INPUT_STATISTIC_DECODED_SUBTITLE, INPUT_STATISTIC_DECODED_VIDEO, INPUT_STATISTIC_SENT_BYTE, INPUT_STATISTIC_SENT_PACKET, msg_Err, input_thread_private_t::p_sout_send_bitrate, input_thread_private_t::p_sout_sent_bytes, stats_Update(), vlc_mutex_lock(), and vlc_mutex_unlock().
stats_NewInputStats()
input_stats_t * stats_NewInputStats (input_thread_t * p_input)
References input_stats_t::lock, stats_ReinitInputStats(), and vlc_mutex_init().
Referenced by Create().