VLC: src/input/input.c File Reference
input.c File Reference
Macros
#define SLAVE_ADD_NOFLAG 0
#define SLAVE_ADD_FORCED (1<<0)
#define SLAVE_ADD_CANFAIL (1<<1)
#define SLAVE_ADD_SET_TIME (1<<2)
#define INIT_COUNTER(c, compute)
#define EXIT_COUNTER(c)
#define CL_CO(c)
#define I(c) stats_Update(input_priv(p_input)->counters.c, i_delta, NULL)
Functions
static void * Run (void *)
static void * Preparse (void *)
static input_thread_t * Create (vlc_object_t *, input_item_t *, const char *, bool, input_resource_t *, vlc_renderer_item_t *)
static int Init (input_thread_t *p_input)
static void End (input_thread_t *p_input)
static void MainLoop (input_thread_t *p_input, bool b_interactive)
MainLoop The main input loop.
static int ControlPop (input_thread_t *, int *, vlc_value_t *, mtime_t i_deadline, bool b_postpone_seek)
static void ControlRelease (int i_type, vlc_value_t val)
static bool ControlIsSeekRequest (int i_type)
static bool Control (input_thread_t *, int, vlc_value_t)
static void ControlPause (input_thread_t *, mtime_t)
static int UpdateTitleSeekpointFromDemux (input_thread_t *)
static void UpdateGenericFromDemux (input_thread_t *)
static void UpdateTitleListfromDemux (input_thread_t *)
static void MRLSections (const char *, int *, int *, int *, int *)
static input_source_t * InputSourceNew (input_thread_t *, const char *, const char *psz_forced_demux, bool b_in_can_fail)
static void InputSourceDestroy (input_source_t *)
static void InputSourceMeta (input_thread_t *, input_source_t *, vlc_meta_t *)
static void SlaveDemux (input_thread_t *p_input)
static void SlaveSeek (input_thread_t *p_input)
static void InputMetaUser (input_thread_t *p_input, vlc_meta_t *p_meta)
static void InputUpdateMeta (input_thread_t *p_input, demux_t *p_demux)
static void InputGetExtraFiles (input_thread_t *p_input, int *pi_list, char ***pppsz_list, const char **psz_access, const char *psz_path)
static void AppendAttachment (int *pi_attachment, input_attachment_t ***ppp_attachment, const demux_t ***ppp_attachment_demux, int i_new, input_attachment_t **pp_new, const demux_t *p_demux)
static int input_SlaveSourceAdd (input_thread_t *, enum slave_type, const char *, unsigned)
static char * input_SubtitleFile2Uri (input_thread_t *, const char *)
static void input_ChangeState (input_thread_t *p_input, int i_state)
input_thread_t * input_Create (vlc_object_t *p_parent, input_item_t *p_item, const char *psz_log, input_resource_t *p_resource, vlc_renderer_item_t *p_renderer)
Create a new input_thread_t.
int input_Read (vlc_object_t *p_parent, input_item_t *p_item)
Initialize an input thread and run it until it stops by itself.
input_thread_t * input_CreatePreparser (vlc_object_t *parent, input_item_t *item)
Creates an item preparser.
int input_Start (input_thread_t *p_input)
Start a input_thread_t created by input_Create.
void input_Stop (input_thread_t *p_input)
Request a running input thread to stop and die.
void input_Close (input_thread_t *p_input)
Close an input.
static void input_Destructor (vlc_object_t *obj)
Input destructor (called when the object's refcount reaches 0).
input_item_t * input_GetItem (input_thread_t *p_input)
Get the item from an input thread FIXME it does not increase ref count of the item.
bool input_Stopped (input_thread_t *input)
static void MainLoopDemux (input_thread_t *p_input, bool *pb_changed)
MainLoopDemux It asks the demuxer to demux some data.
static int MainLoopTryRepeat (input_thread_t *p_input)
static void MainLoopStatistics (input_thread_t *p_input)
Update timing infos and statistics.
static void InitStatistics (input_thread_t *p_input)
static void InitTitle (input_thread_t *p_input)
static void StartTitle (input_thread_t *p_input)
static int SlaveCompare (const void *a, const void *b)
static bool SlaveExists (input_item_slave_t **pp_slaves, int i_slaves, const char *psz_uri)
static void SetSubtitlesOptions (input_thread_t *p_input)
static void GetVarSlaves (input_thread_t *p_input, input_item_slave_t ***ppp_slaves, int *p_slaves)
static void LoadSlaves (input_thread_t *p_input)
static void UpdatePtsDelay (input_thread_t *p_input)
static void InitPrograms (input_thread_t *p_input)
void input_ControlPush (input_thread_t *p_input, int i_type, vlc_value_t *p_val)
static int ControlGetReducedIndexLocked (input_thread_t *p_input)
static void ControlUnpause (input_thread_t *p_input, mtime_t i_control_date)
static void ViewpointApply (input_thread_t *p_input)
static void ControlNavDisplayVolume (vout_thread_t *p_vout, float vol)
static void ControlNavDisplayPosition (vout_thread_t *p_vout, input_thread_t *p_input)
static void ControlNav (input_thread_t *p_input, int i_type)
static void ControlInsertDemuxFilter (input_thread_t *p_input, const char *psz_demux_chain)
static int UpdateTitleSeekpoint (input_thread_t *p_input, int i_title, int i_seekpoint)
static int InputStreamHandleAnchor (input_source_t *source, stream_t **stream, char const *anchor)
static demux_t * InputDemuxNew (input_thread_t *p_input, input_source_t *p_source, const char *psz_access, const char *psz_demux, const char *psz_path, const char *psz_anchor)
static void InputGetExtraFilesPattern (input_thread_t *p_input, int *pi_list, char ***pppsz_list, const char *psz_path, const char *psz_match, const char *psz_format, int i_start, int i_stop)
void input_SplitMRL (const char **access, const char **demux, const char **path, const char **anchor, char *buf)
static const char * MRLSeekPoint (const char *str, int *title, int *chapter)
void input_UpdateStatistic (input_thread_t *p_input, input_statistic_t i_type, int i_delta)
It will update internal input statistics from external sources.
char * input_CreateFilename (input_thread_t *input, const char *dir, const char *filenamefmt, const char *ext)
This function creates a sane filename path.
Macro Definition Documentation
CL_CO
#define CL_CO (c)
Value:
do { \
    stats_CounterClean( priv->counters.p_##c ); \
    priv->counters.p_##c = NULL; \
} while (0)
Referenced by End().
EXIT_COUNTER
#define EXIT_COUNTER (c)
Value:
                                   do { if( input_priv(p_input)->counters.p_##c ) \
                                   stats_CounterClean( input_priv(p_input)->counters.p_##c );\
                               input_priv(p_input)->counters.p_##c = NULL; } while(0)
Referenced by Init().
I
#define I (c) stats_Update(input_priv(p_input)->counters.c, i_delta, NULL)
Referenced by input_UpdateStatistic().
INIT_COUNTER
#define INIT_COUNTER (c, compute)
Value:
    free( priv->counters.p_##c ); \
    priv->counters.p_##c = \
 stats_CounterCreate( STATS_##compute);
Referenced by InitStatistics().
SLAVE_ADD_CANFAIL
#define SLAVE_ADD_CANFAIL (1<<1)
Referenced by Control(), input_SlaveSourceAdd(), and LoadSlaves().
SLAVE_ADD_FORCED
#define SLAVE_ADD_FORCED (1<<0)
Referenced by Control(), input_SlaveSourceAdd(), and LoadSlaves().
SLAVE_ADD_NOFLAG
#define SLAVE_ADD_NOFLAG 0
Referenced by LoadSlaves().
SLAVE_ADD_SET_TIME
#define SLAVE_ADD_SET_TIME (1<<2)
Referenced by Control(), and input_SlaveSourceAdd().
Function Documentation
AppendAttachment()
static void AppendAttachment (int * pi_attachment, input_attachment_t *** ppp_attachment, const demux_t *** ppp_attachment_demux, int i_new, input_attachment_t ** pp_new, const demux_t * p_demux) static
References likely, and vlc_input_attachment_Delete().
Referenced by InputSourceMeta(), InputSourceNew(), and InputUpdateMeta().
Control()
static bool Control (input_thread_t * p_input, int i_type, vlc_value_t val) static
< No error
References vlc_value_t::b_bool, input_thread_private_t::b_can_pace_control, input_thread_private_t::b_can_rate_control, input_source_t::b_eof, input_item_slave::b_forced, input_thread_private_t::b_recording, Control(), ControlInsertDemuxFilter(), ControlNav(), ControlPause(), ControlRelease(), ControlUnpause(), demux_Control(), demux_FilterDisable(), demux_FilterEnable(), DEMUX_GET_LENGTH, demux_GetSeekpoint(), demux_GetTitle(), DEMUX_SET_ES, DEMUX_SET_GROUP, DEMUX_SET_POSITION, DEMUX_SET_RATE, DEMUX_SET_RECORD_STATE, DEMUX_SET_SEEKPOINT, DEMUX_SET_TIME, DEMUX_SET_TITLE, es_out_Control(), ES_OUT_RESET_PCR, ES_OUT_RESTART_ES_BY_ID, ES_OUT_SET_ES_BY_ID, ES_OUT_SET_GROUP, es_out_SetFrameNext(), es_out_SetRate(), es_out_SetRecordState(), es_out_SetTime(), ES_OUT_START_ALL_ES, ES_OUT_STOP_ALL_ES, vlc_value_t::f_float, vlc_viewpoint_t::fov, vlc_value_t::i_int, input_thread_private_t::i_rate, input_title_t::i_seekpoint, seekpoint_t::i_time_offset, input_thread_private_t::i_title, i_type, input_item_slave::i_type, INPUT_CONTROL_ADD_SLAVE, INPUT_CONTROL_NAV_ACTIVATE, INPUT_CONTROL_NAV_DOWN, INPUT_CONTROL_NAV_LEFT, INPUT_CONTROL_NAV_MENU, INPUT_CONTROL_NAV_POPUP, INPUT_CONTROL_NAV_RIGHT, INPUT_CONTROL_NAV_UP, INPUT_CONTROL_RESTART_ES, INPUT_CONTROL_SET_AUDIO_DELAY, INPUT_CONTROL_SET_BOOKMARK, INPUT_CONTROL_SET_ES, INPUT_CONTROL_SET_FRAME_NEXT, INPUT_CONTROL_SET_INITIAL_VIEWPOINT, INPUT_CONTROL_SET_POSITION, INPUT_CONTROL_SET_PROGRAM, INPUT_CONTROL_SET_RATE, INPUT_CONTROL_SET_RECORD_STATE, INPUT_CONTROL_SET_RENDERER, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_SEEKPOINT_NEXT, INPUT_CONTROL_SET_SEEKPOINT_PREV, INPUT_CONTROL_SET_SPU_DELAY, INPUT_CONTROL_SET_STATE, INPUT_CONTROL_SET_TIME, INPUT_CONTROL_SET_TITLE, INPUT_CONTROL_SET_TITLE_NEXT, INPUT_CONTROL_SET_TITLE_PREV, INPUT_CONTROL_SET_VIEWPOINT, INPUT_CONTROL_UPDATE_VIEWPOINT, input_item_AddSlave(), input_priv(), INPUT_RATE_DEFAULT, INPUT_RATE_MAX, INPUT_RATE_MIN, input_resource_TerminateVout(), input_SendEventAudioDelay(), input_SendEventRate(), input_SendEventRecord(), input_SendEventSeekpoint(), input_SendEventSubtitleDelay(), input_SendEventTitle(), input_SlaveSourceAdd(), input_thread_private_t::master, mdate(), msg_Dbg, msg_Err, msg_Warn, vlc_value_t::p_address, input_source_t::p_demux, input_thread_private_t::p_renderer, input_thread_private_t::p_resource, PAUSE_S, vlc_viewpoint_t::pitch, PLAYING_S, input_thread_private_t::pp_bookmark, input_item_slave::psz_uri, vlc_viewpoint_t::roll, input_title_t::seekpoint, SLAVE_ADD_CANFAIL, SLAVE_ADD_FORCED, SLAVE_ADD_SET_TIME, SlaveSeek(), input_source_t::title, input_thread_private_t::title, UpdatePtsDelay(), var_GetInteger, input_thread_private_t::viewpoint, input_thread_private_t::viewpoint_changed, ViewpointApply(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_renderer_item_demux_filter(), vlc_renderer_item_hold(), vlc_renderer_item_release(), VLC_SUCCESS, and vlc_viewpoint_t::yaw.
Referenced by Control(), and MainLoop().
ControlGetReducedIndexLocked()
static int ControlGetReducedIndexLocked (input_thread_t * p_input) static
References input_thread_private_t::control, input_thread_private_t::i_control, input_control_t::i_type, INPUT_CONTROL_SET_BOOKMARK, INPUT_CONTROL_SET_POSITION, INPUT_CONTROL_SET_PROGRAM, INPUT_CONTROL_SET_RATE, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_STATE, INPUT_CONTROL_SET_TIME, INPUT_CONTROL_SET_TITLE, and input_priv().
Referenced by ControlPop().
ControlInsertDemuxFilter()
static void ControlInsertDemuxFilter (input_thread_t * p_input, const char * psz_demux_chain) static
References demux_FilterChainNew(), input_priv(), input_thread_private_t::master, msg_Dbg, and input_source_t::p_demux.
Referenced by Control().
ControlIsSeekRequest()
static bool ControlIsSeekRequest (int i_type) static
References i_type, INPUT_CONTROL_NAV_ACTIVATE, INPUT_CONTROL_NAV_DOWN, INPUT_CONTROL_NAV_LEFT, INPUT_CONTROL_NAV_MENU, INPUT_CONTROL_NAV_POPUP, INPUT_CONTROL_NAV_RIGHT, INPUT_CONTROL_NAV_UP, INPUT_CONTROL_SET_BOOKMARK, INPUT_CONTROL_SET_POSITION, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_SEEKPOINT_NEXT, INPUT_CONTROL_SET_SEEKPOINT_PREV, INPUT_CONTROL_SET_TIME, INPUT_CONTROL_SET_TITLE, INPUT_CONTROL_SET_TITLE_NEXT, and INPUT_CONTROL_SET_TITLE_PREV.
Referenced by ControlPop(), and MainLoop().
ControlNav()
static void ControlNav (input_thread_t * p_input, int i_type) static
References aout_VolumeUpdate(), CLOCK_FREQ, ControlNavDisplayPosition(), ControlNavDisplayVolume(), demux_Control(), DEMUX_NAV_ACTIVATE, vlc_viewpoint_t::fov, i_type, INPUT_CONTROL_NAV_ACTIVATE, INPUT_CONTROL_NAV_DOWN, INPUT_CONTROL_NAV_LEFT, INPUT_CONTROL_NAV_MENU, INPUT_CONTROL_NAV_POPUP, INPUT_CONTROL_NAV_RIGHT, INPUT_CONTROL_NAV_UP, input_priv(), input_resource_HoldAout(), input_resource_HoldVouts(), input_thread_private_t::master, input_source_t::p_demux, input_thread_private_t::p_resource, vlc_viewpoint_t::pitch, vlc_viewpoint_t::roll, var_GetBool, var_InheritInteger, var_SetInteger, input_thread_private_t::viewpoint, input_thread_private_t::viewpoint_changed, ViewpointApply(), vlc_assert_unreachable, vlc_object_release, and vlc_viewpoint_t::yaw.
Referenced by Control().
ControlNavDisplayPosition()
static void ControlNavDisplayPosition (vout_thread_t * p_vout, input_thread_t * p_input) static
References CLOCK_FREQ, MSTRTIME_MAX_SIZE, secstotimestr(), var_GetInteger, vout_FlushSubpictureChannel(), vout_OSDMessage(), and VOUT_SPU_CHANNEL_OSD.
Referenced by ControlNav().
ControlNavDisplayVolume()
static void ControlNavDisplayVolume (vout_thread_t * p_vout, float vol) static
References _, vout_FlushSubpictureChannel(), vout_OSDMessage(), and VOUT_SPU_CHANNEL_OSD.
Referenced by ControlNav().
ControlPause()
static void ControlPause (input_thread_t * p_input, mtime_t i_control_date) static
References demux_Control(), DEMUX_SET_PAUSE_STATE, es_out_SetPauseState(), input_ChangeState(), input_priv(), input_thread_private_t::master, msg_Warn, input_source_t::p_demux, and PAUSE_S.
Referenced by Control(), and MainLoop().
ControlPop()
static int ControlPop (input_thread_t * p_input, int * pi_type, vlc_value_t * p_val, mtime_t i_deadline, bool b_postpone_seek) inline static
< Unspecified error
< Unspecified error
< No error
References input_thread_private_t::control, ControlGetReducedIndexLocked(), ControlIsSeekRequest(), ControlRelease(), input_thread_private_t::i_control, input_control_t::i_type, input_priv(), input_thread_private_t::is_stopped, input_thread_private_t::lock_control, input_control_t::val, vlc_cond_timedwait(), vlc_cond_wait(), VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and input_thread_private_t::wait_control.
Referenced by MainLoop().
ControlRelease()
static void ControlRelease (int i_type, vlc_value_t val) static
References i_type, INPUT_CONTROL_ADD_SLAVE, INPUT_CONTROL_SET_INITIAL_VIEWPOINT, INPUT_CONTROL_SET_RENDERER, INPUT_CONTROL_SET_VIEWPOINT, INPUT_CONTROL_UPDATE_VIEWPOINT, input_item_slave_Delete, vlc_value_t::p_address, and vlc_renderer_item_release().
Referenced by Control(), ControlPop(), input_ControlPush(), input_Destructor(), and input_Stop().
ControlUnpause()
static void ControlUnpause (input_thread_t * p_input, mtime_t i_control_date) static
References demux_Control(), DEMUX_SET_PAUSE_STATE, ERROR_S, es_out_SetPauseState(), input_ChangeState(), input_priv(), input_thread_private_t::master, msg_Err, input_source_t::p_demux, and PLAYING_S.
Referenced by Control().
Create()
static input_thread_t * Create (vlc_object_t * p_parent, input_item_t * p_item, const char * psz_header, bool b_preparsing, input_resource_t * p_resource, vlc_renderer_item_t * p_renderer) static
References atof(), input_thread_private_t::attachment, input_thread_private_t::attachment_demux, input_thread_private_t::b_can_pace_control, input_thread_private_t::b_out_pace_control, input_item_t::b_preparse_interact, input_thread_private_t::b_preparsing, input_thread_private_t::b_recording, input_thread_private_t::bookmark, CLOCK_FREQ, input_thread_private_t::counters, input_thread_private_t::counters_lock, vlc_common_members::flags, vlc_common_members::header, input_thread_private_t::i_attachment, input_thread_private_t::i_bookmark, input_thread_private_t::i_control, input_item_t::i_preparse_depth, input_thread_private_t::i_rate, input_thread_private_t::i_seekpoint_offset, input_thread_private_t::i_slave, input_thread_private_t::i_start, input_thread_private_t::i_state, input_thread_private_t::i_stop, input_thread_private_t::i_time, seekpoint_t::i_time_offset, input_thread_private_t::i_title, input_thread_private_t::i_title_offset, INIT_S, input_thread_private_t::input, INPUT_ADD_BOOKMARK, input_ConfigVarInit(), input_Control(), input_ControlVarInit(), input_Destructor(), input_EsOutNew(), input_item_ApplyOptions(), input_item_GetName(), input_item_Hold(), input_item_SetESNowPlaying(), input_item_SetNowPlaying(), input_priv(), INPUT_RATE_DEFAULT, input_resource_Hold(), input_resource_New(), input_resource_SetInput(), input_SendEventMeta(), input_thread_private_t::interrupt, input_thread_private_t::is_running, input_thread_private_t::is_stopped, input_item_t::lock, input_thread_private_t::lock_control, input_thread_private_t::master, msg_Dbg, input_thread_t::obj, OBJECT_FLAGS_NOINTERACT, OBJECT_FLAGS_QUIET, input_thread_private_t::p_es_out, input_thread_private_t::p_es_out_display, input_thread_private_t::p_item, input_thread_private_t::p_renderer, input_thread_private_t::p_resource, input_thread_private_t::p_resource_private, input_thread_private_t::p_sout, input_item_t::p_stats, input_thread_private_t::pp_bookmark, psz_name, seekpoint_t::psz_name, input_thread_private_t::slave, stats_NewInputStats(), strcasecmp(), strdup(), TAB_INIT, input_thread_private_t::title, unlikely, var_GetNonEmptyString, var_InheritAddress, var_InheritBool, var_InheritString, input_thread_private_t::viewpoint, input_thread_private_t::viewpoint_changed, vlc_cond_init(), vlc_custom_create, vlc_interrupt_init(), vlc_mutex_init(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, vlc_object_set_destructor, vlc_renderer_item_hold(), vlc_seekpoint_Delete(), vlc_seekpoint_New(), vlc_viewpoint_init(), and input_thread_private_t::wait_control.
Referenced by input_Create(), input_CreatePreparser(), and input_Read().
End()
static void End (input_thread_t * p_input) static
References input_thread_private_t::attachment, input_thread_private_t::attachment_demux, input_thread_private_t::b_preparsing, CL_CO, END_S, es_out_Delete(), ES_OUT_MODE_END, ES_OUT_MODE_NONE, es_out_SetMode(), input_thread_private_t::i_attachment, input_thread_private_t::i_bookmark, input_thread_private_t::i_seekpoint_offset, input_thread_private_t::i_slave, input_thread_private_t::i_title, input_thread_private_t::i_title_offset, input_ChangeState(), input_ControlVarStop(), input_priv(), input_resource_RequestSout(), input_resource_SetInput(), input_resource_Terminate(), InputSourceDestroy(), libvlc_stats, input_item_t::lock, input_thread_private_t::master, input_thread_private_t::p_es_out, input_thread_private_t::p_es_out_display, input_thread_private_t::p_item, input_thread_private_t::p_sout, input_item_t::p_stats, input_thread_private_t::pp_bookmark, input_thread_private_t::slave, stats_ComputeInputStats(), TAB_CLEAN, input_thread_private_t::title, vlc_input_attachment_Delete(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_seekpoint_Delete().
Referenced by input_Read(), Preparse(), and Run().
GetVarSlaves()
static void GetVarSlaves (input_thread_t * p_input, input_item_slave_t *** ppp_slaves, int * p_slaves) static
References input_item_slave_New(), SLAVE_PRIORITY_USER, SLAVE_TYPE_AUDIO, strdup(), TAB_APPEND, unlikely, var_GetNonEmptyString, and vlc_path2uri().
Referenced by LoadSlaves().
Init()
static int Init (input_thread_t * p_input) static
< No error
< Unspecified error
References input_thread_private_t::b_out_pace_control, input_thread_private_t::b_preparsing, demux_Control(), DEMUX_GET_LENGTH, ERROR_S, es_out_ControlSetMeta(), es_out_Delete(), ES_OUT_MODE_END, es_out_SetMode(), EXIT_COUNTER, vlc_value_t::i_int, sout_instance_t::i_out_pace_nocontrol, input_thread_private_t::i_rate, input_thread_private_t::i_slave, InitPrograms(), InitStatistics(), InitTitle(), input_ChangeState(), INPUT_CONTROL_SET_RATE, input_ControlPush(), input_EsOutTimeshiftNew(), input_item_GetDuration(), input_priv(), INPUT_RATE_DEFAULT, input_resource_RequestSout(), input_resource_SetInput(), input_resource_Terminate(), input_SendEventCache(), input_SendEventLength(), input_SendEventPosition(), InputMetaUser(), InputSourceMeta(), InputSourceNew(), libvlc_stats, LoadSlaves(), input_thread_private_t::master, msg_Dbg, input_thread_t::obj, OPENING_S, input_source_t::p_demux, input_thread_private_t::p_es_out, input_thread_private_t::p_es_out_display, input_thread_private_t::p_item, input_thread_private_t::p_sout, vlc_common_members::parent, PLAYING_S, input_item_t::psz_uri, SetSubtitlesOptions(), input_thread_private_t::slave, StartTitle(), var_InheritFloat, var_SetBool, var_SetInteger, var_SetString, var_Type, VLC_EGENERIC, vlc_meta_Delete(), vlc_meta_New(), and VLC_SUCCESS.
Referenced by input_Read(), Preparse(), and Run().
InitPrograms()
static void InitPrograms (input_thread_t * p_input) static
References demux_Control(), DEMUX_SET_GROUP, es_out_GetGroupForced(), ES_OUT_MODE_ALL, ES_OUT_MODE_AUTO, ES_OUT_MODE_PARTIAL, es_out_SetMode(), vlc_value_t::i_int, input_priv(), list, strtok_r(), TAB_APPEND, TAB_CLEAN, TAB_INIT, UpdatePtsDelay(), var_GetBool, and var_GetNonEmptyString.
Referenced by Init().
InitStatistics()
static void InitStatistics (input_thread_t * p_input) static
References input_thread_private_t::b_preparsing, input_thread_private_t::counters, INIT_COUNTER, input_priv(), libvlc_stats, input_thread_private_t::p_sout_send_bitrate, input_thread_private_t::p_sout_sent_bytes, and input_thread_private_t::p_sout_sent_packets.
Referenced by Init().
InitTitle()
static void InitTitle (input_thread_t * p_input) static
References input_source_t::b_can_pace_control, input_thread_private_t::b_can_pace_control, input_source_t::b_can_pause, input_thread_private_t::b_can_pause, input_source_t::b_can_rate_control, input_thread_private_t::b_can_rate_control, input_thread_private_t::b_preparsing, input_source_t::i_seekpoint_offset, input_thread_private_t::i_seekpoint_offset, input_source_t::i_title, input_thread_private_t::i_title, input_source_t::i_title_offset, input_thread_private_t::i_title_offset, input_ControlVarNavigation(), input_priv(), input_SendEventTitle(), input_item_t::lock, input_thread_private_t::master, input_thread_private_t::p_item, input_source_t::title, input_thread_private_t::title, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Init(), and UpdateTitleListfromDemux().
input_ChangeState()
static void input_ChangeState (input_thread_t * p_input, int i_state) static
References ERROR_S, input_thread_private_t::i_state, input_item_SetErrorWhenReading(), input_priv(), and input_SendEventState().
Referenced by ControlPause(), ControlUnpause(), End(), Init(), input_Start(), and MainLoopDemux().
input_Close()
void input_Close (input_thread_t * p_input)
Close an input.
It does not call input_Stop itself.
References input_priv(), thread, vlc_interrupt_deinit(), vlc_join(), and vlc_object_release.
Referenced by LoopInput(), PreparserCloseInput(), PreparserOpenInput(), vlm_ControlMediaInstanceStart(), vlm_MediaInstanceDelete(), and vlm_OnMediaUpdate().
input_ControlPush()
void input_ControlPush (input_thread_t * p_input, int i_type, vlc_value_t * p_val)
References input_thread_private_t::control, ControlRelease(), input_thread_private_t::i_control, i_type, input_control_t::i_type, INPUT_CONTROL_FIFO_SIZE, input_priv(), input_thread_private_t::is_stopped, input_thread_private_t::lock_control, msg_Dbg, msg_Err, input_control_t::val, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and input_thread_private_t::wait_control.
Referenced by BookmarkCallback(), EsAudioCallback(), EsDelayCallback(), EsSpuCallback(), EsVideoCallback(), FrameNextCallback(), Init(), input_vaControl(), MainLoopTryRepeat(), NavigationCallback(), PositionCallback(), ProgramCallback(), RateCallback(), RecordCallback(), SeekpointCallback(), StartTitle(), StateCallback(), TimeCallback(), TitleCallback(), and TsRun().
input_Create()
input_thread_t * input_Create (vlc_object_t * p_parent, input_item_t * p_item, const char * psz_log, input_resource_t * p_resource, vlc_renderer_item_t * p_renderer)
Create a new input_thread_t.
You need to call input_Start on it when you are done adding callback on the variables/events you want to monitor.
Parameters
p_parent a vlc_object
p_item an input item
psz_log an optional prefix for this input logs
p_resource an optional input ressource
Returns
a pointer to the spawned input thread
References Create().
input_CreateFilename()
char * input_CreateFilename (input_thread_t * input, const char * dir, const char * filenamefmt, const char * ext)
This function creates a sane filename path.
References asprintf(), DIR_SEP, filename_sanitize(), str_format(), and unlikely.
Referenced by EsOutSetRecord().
input_CreatePreparser()
input_thread_t * input_CreatePreparser (vlc_object_t * obj, input_item_t * item)
Creates an item preparser.
Creates an input thread to preparse an item. The input needs to be started with input_Start() afterwards.
Parameters
obj parent object
item input item to preparse
Returns
an input thread or NULL on error
References Create().
Referenced by PreparserOpenInput().
input_Destructor()
static void input_Destructor (vlc_object_t * obj) static
Input destructor (called when the object's refcount reaches 0).
References input_thread_private_t::control, ControlRelease(), input_thread_private_t::counters, input_thread_private_t::counters_lock, es_out_Delete(), input_thread_private_t::i_control, input_control_t::i_type, input_item_GetName(), input_item_Release(), input_priv(), input_resource_Release(), input_thread_private_t::lock_control, msg_Dbg, input_thread_private_t::p_es_out_display, input_thread_private_t::p_item, input_thread_private_t::p_renderer, input_thread_private_t::p_resource, input_thread_private_t::p_resource_private, psz_name, input_control_t::val, vlc_cond_destroy(), vlc_mutex_destroy(), vlc_renderer_item_release(), and input_thread_private_t::wait_control.
Referenced by Create().
input_GetItem()
input_item_t * input_GetItem (input_thread_t * p_input)
Get the item from an input thread FIXME it does not increase ref count of the item.
Get the input item for an input thread.
if it is used after p_input is destroyed nothing prevent it from being freed.
References input_priv(), and input_thread_private_t::p_item.
Referenced by DisplayVoutTitle(), EsOutMeta(), EsOutUpdateInfo(), and vlc_strfinput().
input_Read()
int input_Read (vlc_object_t * p_parent, input_item_t * p_item)
Initialize an input thread and run it until it stops by itself.
Parameters
p_parent a vlc_object
p_item an input item
Returns
an error code, VLC_SUCCESS on success
< Unspecified error
< No error
References Create(), End(), Init(), MainLoop(), VLC_EGENERIC, vlc_object_release, and VLC_SUCCESS.
input_SlaveSourceAdd()
static int input_SlaveSourceAdd (input_thread_t * p_input, enum slave_type i_type, const char * psz_uri, unsigned i_flags) static
< Unspecified error
< Unspecified error
< Unspecified error
< No error
< No error
< No error
References count, demux_Control(), DEMUX_GET_TIME, DEMUX_SET_TIME, es_out_Control(), ES_OUT_SET_ES_BY_ID, ES_OUT_SET_ES_DEFAULT_BY_ID, i_type, input_priv(), InputSourceDestroy(), InputSourceNew(), InputUpdateMeta(), list, msg_Dbg, msg_Err, msg_Warn, input_source_t::p_demux, SLAVE_ADD_CANFAIL, SLAVE_ADD_FORCED, SLAVE_ADD_SET_TIME, SLAVE_TYPE_AUDIO, SLAVE_TYPE_SPU, TAB_APPEND, var_Change, var_FreeList(), vlc_assert_unreachable, VLC_EGENERIC, VLC_SUCCESS, VLC_VAR_CHOICESCOUNT, and VLC_VAR_GETCHOICES.
Referenced by Control(), and LoadSlaves().
input_SplitMRL()
void input_SplitMRL (const char ** access, const char ** demux, const char ** path, const char ** anchor, char * buf)
References p.
Referenced by InputSourceNew().
input_Start()
int input_Start (input_thread_t * p_input)
Start a input_thread_t created by input_Create.
You must not start an already running input_thread_t.
Parameters
the input thread to start
< Unspecified error
< No error
References input_thread_private_t::b_preparsing, ERROR_S, input_ChangeState(), input_priv(), input_thread_private_t::is_running, msg_Err, Preparse(), Run(), input_thread_private_t::thread, vlc_clone(), VLC_EGENERIC, VLC_SUCCESS, and VLC_THREAD_PRIORITY_INPUT.
Referenced by input_CreateAndStart(), PlayItem(), PreparserOpenInput(), vlm_ControlMediaInstanceStart(), and vlm_OnMediaUpdate().
input_Stop()
void input_Stop (input_thread_t * p_input)
Request a running input thread to stop and die.
Parameters
p_input the input thread to stop
References input_thread_private_t::control, ControlRelease(), input_thread_private_t::i_control, input_control_t::i_type, input_priv(), input_thread_private_t::interrupt, input_thread_private_t::is_stopped, input_thread_private_t::lock_control, input_control_t::val, vlc_cond_signal(), vlc_interrupt_kill(), vlc_mutex_lock(), vlc_mutex_unlock(), and input_thread_private_t::wait_control.
Referenced by LoopInput(), PreparserCloseInput(), vlm_ControlMediaInstanceStart(), vlm_MediaInstanceDelete(), and vlm_OnMediaUpdate().
input_Stopped()
bool input_Stopped (input_thread_t * input)
References input_priv(), input_thread_private_t::is_stopped, input_thread_private_t::lock_control, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutDel(), InputSourceNew(), and MainLoop().
input_SubtitleFile2Uri()
static char * input_SubtitleFile2Uri (input_thread_t * p_input, const char * psz_subtitle) static
References msg_Dbg, strdup(), vlc_path2uri(), and vlc_stat().
Referenced by LoadSlaves().
input_UpdateStatistic()
void input_UpdateStatistic (input_thread_t * p_input, input_statistic_t i_type, int i_delta)
It will update internal input statistics from external sources.
XXX For now, the only one allowed to do it is stream_out and input core.
References input_thread_private_t::counters_lock, I, i_type, INIT_S, input_priv(), INPUT_STATISTIC_DECODED_AUDIO, INPUT_STATISTIC_DECODED_SUBTITLE, INPUT_STATISTIC_DECODED_VIDEO, INPUT_STATISTIC_SENT_BYTE, INPUT_STATISTIC_SENT_PACKET, msg_Err, input_thread_private_t::p_sout_send_bitrate, input_thread_private_t::p_sout_sent_bytes, stats_Update(), vlc_mutex_lock(), and vlc_mutex_unlock().
InputDemuxNew()
static demux_t * InputDemuxNew (input_thread_t * p_input, input_source_t * p_source, const char * psz_access, const char * psz_demux, const char * psz_path, const char * psz_anchor) static
References asprintf(), input_thread_private_t::b_preparsing, demux_NewAdvanced, FREENULL, input_source_t::i_seekpoint_end, input_source_t::i_seekpoint_start, input_source_t::i_title_end, input_source_t::i_title_start, input_priv(), InputStreamHandleAnchor(), MRLSections(), input_thread_private_t::p_es_out, stream_AccessNew(), stream_FilterChainNew(), var_InheritBool, var_InheritString, VLC_OBJECT, and vlc_stream_Delete().
Referenced by InputSourceNew().
InputGetExtraFiles()
static void InputGetExtraFiles (input_thread_t * p_input, int * pi_list, char *** pppsz_list, const char ** psz_access, const char * psz_path) static
References ARRAY_SIZE, InputGetExtraFilesPattern(), and TAB_INIT.
Referenced by InputSourceNew().
InputGetExtraFilesPattern()
static void InputGetExtraFilesPattern (input_thread_t * p_input, int * pi_list, char *** pppsz_list, const char * psz_path, const char * psz_match, const char * psz_format, int i_start, int i_stop) static
References asprintf(), get_path(), msg_Dbg, strdup(), TAB_APPEND, TAB_INIT, vlc_path2uri(), and vlc_stat().
Referenced by InputGetExtraFiles().
InputMetaUser()
static void InputMetaUser (input_thread_t * p_input, vlc_meta_t * p_meta) static
References EnsureUTF8(), psz_name, var_GetNonEmptyString, vlc_meta_Artist, vlc_meta_Copyright, vlc_meta_Date, vlc_meta_Description, vlc_meta_Genre, vlc_meta_Set(), vlc_meta_Title, and vlc_meta_URL.
Referenced by Init().
InputSourceDestroy()
static void InputSourceDestroy (input_source_t * in) static
References demux_Delete(), input_source_t::i_title, input_source_t::p_demux, TAB_CLEAN, input_source_t::title, vlc_input_title_Delete(), and vlc_object_release.
Referenced by End(), and input_SlaveSourceAdd().
InputSourceMeta()
static void InputSourceMeta (input_thread_t * p_input, input_source_t * p_source, vlc_meta_t * p_meta) static
References AppendAttachment(), demux_meta_t::attachments, demux_Control(), DEMUX_GET_META, DEMUX_HAS_UNSUPPORTED_META, demux_meta_t::i_attachments, input_priv(), module_need, module_unneed, input_source_t::p_demux, demux_meta_t::p_item, input_thread_private_t::p_item, demux_meta_t::p_meta, unlikely, vlc_custom_create, vlc_meta_Delete(), vlc_meta_Merge(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_release.
Referenced by Init().
InputSourceNew()
static input_source_t * InputSourceNew (input_thread_t * p_input, const char * psz_mrl, const char * psz_forced_demux, bool b_in_can_fail) static
References _, AppendAttachment(), asprintf(), input_source_t::b_can_pace_control, input_source_t::b_can_pause, input_source_t::b_can_rate_control, input_source_t::b_can_stream_record, input_source_t::b_rescale_ts, input_source_t::b_title_demux, count, DEMUX_CAN_CONTROL_PACE, DEMUX_CAN_CONTROL_RATE, DEMUX_CAN_PAUSE, DEMUX_CAN_RECORD, DEMUX_CAN_SEEK, demux_Control(), demux_FilterChainNew(), DEMUX_GET_ATTACHMENTS, DEMUX_GET_FPS, DEMUX_GET_PTS_DELAY, DEMUX_GET_TITLE_INFO, input_source_t::f_fps, input_source_t::i_pts_delay, input_source_t::i_seekpoint_offset, input_source_t::i_title, input_source_t::i_title_offset, input_priv(), INPUT_PTS_DELAY_MAX, input_SplitMRL(), input_Stopped(), InputDemuxNew(), InputGetExtraFiles(), likely, list, msg_Dbg, msg_Err, input_source_t::p_demux, input_thread_private_t::p_renderer, demux_t::pf_demux, strcasecmp(), strdup(), TAB_CLEAN, TAB_INIT, input_source_t::title, unlikely, var_Create, var_GetBool, var_GetInteger, var_GetNonEmptyString, var_InheritString, var_SetBool, var_SetString, vlc_custom_create, vlc_dialog_display_error, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, vlc_renderer_item_demux_filter(), and VLC_VAR_STRING.
Referenced by Init(), and input_SlaveSourceAdd().
InputStreamHandleAnchor()
static int InputStreamHandleAnchor (input_source_t * source, stream_t ** stream, char const * anchor) static
< Unspecified error
< No error
References input_source_t::i_seekpoint_end, input_source_t::i_seekpoint_start, input_source_t::i_title_end, input_source_t::i_title_start, MRLSections(), msg_Dbg, msg_Err, stream_extractor_AttachParsed(), VLC_EGENERIC, vlc_stream_directory_Attach(), and VLC_SUCCESS.
Referenced by InputDemuxNew().
InputUpdateMeta()
static void InputUpdateMeta (input_thread_t * p_input, demux_t * p_demux) static
References AppendAttachment(), input_thread_private_t::attachment, input_thread_private_t::attachment_demux, demux_Control(), DEMUX_GET_ATTACHMENTS, DEMUX_GET_META, es_out_ControlSetMeta(), input_thread_private_t::i_attachment, input_priv(), unlikely, vlc_input_attachment_Delete(), vlc_meta_Delete(), vlc_meta_New(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_SlaveSourceAdd(), and UpdateGenericFromDemux().
LoadSlaves()
static void LoadSlaves (input_thread_t * p_input) static
< No error
< No error
< No error
References asprintf(), input_thread_private_t::attachment, input_item_slave::b_forced, GetVarSlaves(), input_thread_private_t::i_attachment, input_item_slave::i_priority, input_item_t::i_slaves, input_item_slave::i_type, input_item_AddSlave(), input_item_slave_Delete, input_item_slave_New(), input_priv(), input_SlaveSourceAdd(), input_SubtitleFile2Uri(), input_item_t::lock, msg_Dbg, input_thread_private_t::p_item, input_item_t::pp_slaves, input_attachment_t::psz_description, input_attachment_t::psz_mime, input_attachment_t::psz_name, input_item_slave::psz_uri, SLAVE_ADD_CANFAIL, SLAVE_ADD_FORCED, SLAVE_ADD_NOFLAG, SLAVE_PRIORITY_USER, SLAVE_TYPE_AUDIO, SLAVE_TYPE_SPU, SlaveCompare(), SlaveExists(), subtitles_Detect(), TAB_APPEND, TAB_CLEAN, TAB_INIT, var_Create, var_Destroy, var_GetBool, var_GetNonEmptyString, var_SetString, vlc_input_attachment_Delete(), vlc_input_attachment_New(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, and VLC_VAR_STRING.
Referenced by Init().
MainLoop()
static void MainLoop (input_thread_t * p_input, bool b_interactive) static
MainLoop The main input loop.
References input_source_t::b_eof, Control(), ControlIsSeekRequest(), ControlPause(), ControlPop(), ERROR_S, es_out_GetBuffering(), es_out_GetEmpty(), es_out_GetWakeup(), vlc_value_t::i_int, input_thread_private_t::i_state, i_type, INPUT_CONTROL_SET_STATE, INPUT_IDLE_SLEEP, input_priv(), input_Stopped(), MainLoopDemux(), MainLoopStatistics(), MainLoopTryRepeat(), input_thread_private_t::master, mdate(), msg_Dbg, input_source_t::p_demux, PAUSE_S, demux_t::pf_demux, and var_InheritBool.
Referenced by input_Read(), Preparse(), and Run().
MainLoopDemux()
static void MainLoopDemux (input_thread_t * p_input, bool * pb_changed) static
MainLoopDemux It asks the demuxer to demux some data.
References input_source_t::b_eof, input_source_t::b_title_demux, demux_Control(), demux_Demux(), DEMUX_GET_TIME, demux_TestAndClearFlags(), ERROR_S, es_out_Eos(), input_thread_private_t::i_slave, input_thread_private_t::i_stop, input_thread_private_t::i_time, input_ChangeState(), input_priv(), INPUT_UPDATE_TITLE_LIST, input_thread_private_t::master, msg_Dbg, input_source_t::p_demux, input_thread_private_t::p_es_out, SlaveDemux(), UpdateGenericFromDemux(), UpdateTitleListfromDemux(), UpdateTitleSeekpointFromDemux(), VLC_DEMUXER_EGENERIC, VLC_DEMUXER_EOF, and VLC_DEMUXER_SUCCESS.
Referenced by MainLoop().
MainLoopStatistics()
static void MainLoopStatistics (input_thread_t * p_input) static
Update timing infos and statistics.
References input_thread_private_t::bookmark, demux_Control(), DEMUX_GET_LENGTH, DEMUX_GET_POSITION, DEMUX_GET_TIME, es_out_SetTimes(), input_thread_private_t::i_time, seekpoint_t::i_time_offset, input_priv(), input_SendEventStatistics(), stats_ComputeInputStats(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by MainLoop().
MainLoopTryRepeat()
static int MainLoopTryRepeat (input_thread_t * p_input) static
< Unspecified error
< No error
References vlc_value_t::f_float, vlc_value_t::i_int, input_source_t::i_seekpoint_offset, input_source_t::i_seekpoint_start, input_thread_private_t::i_start, input_thread_private_t::i_title, input_source_t::i_title_offset, input_source_t::i_title_start, INPUT_CONTROL_SET_POSITION, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_TIME, INPUT_CONTROL_SET_TITLE, input_ControlPush(), input_priv(), input_thread_private_t::master, msg_Dbg, var_GetInteger, var_SetInteger, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by MainLoop().
MRLSections()
static void MRLSections (const char * p, int * pi_title_start, int * pi_title_end, int * pi_chapter_start, int * pi_chapter_end) static
References MRLSeekPoint(), and p.
Referenced by InputDemuxNew(), and InputStreamHandleAnchor().
MRLSeekPoint()
static const char * MRLSeekPoint (const char * str, int * title, int * chapter) static
Referenced by MRLSections().
Preparse()
static void * Preparse (void * data) static
References demux_Control(), DEMUX_IS_PLAYLIST, End(), Init(), input_thread_private_t::input, input_item_ShouldPreparseSubItems(), input_SendEventDead(), input_thread_private_t::interrupt, MainLoop(), input_thread_private_t::master, input_source_t::p_demux, input_thread_private_t::p_item, and vlc_interrupt_set().
Referenced by input_Start().
Run()
static void * Run (void * data) static
References input_thread_private_t::b_can_pace_control, input_thread_private_t::b_out_pace_control, End(), Init(), input_thread_private_t::input, input_SendEventDead(), input_thread_private_t::interrupt, MainLoop(), input_thread_private_t::thread, vlc_interrupt_set(), vlc_set_priority(), and VLC_THREAD_PRIORITY_LOW.
Referenced by input_Start().
SetSubtitlesOptions()
static void SetSubtitlesOptions (input_thread_t * p_input) static
References input_source_t::f_fps, input_priv(), input_thread_private_t::master, var_Create, var_CreateGetFloat, var_CreateGetInteger, var_SetFloat, var_SetInteger, VLC_VAR_DOINHERIT, and VLC_VAR_FLOAT.
Referenced by Init().
SlaveCompare()
static int SlaveCompare (const void * a, const void * b) static
References input_item_slave::i_priority.
Referenced by LoadSlaves().
SlaveDemux()
static void SlaveDemux (input_thread_t * p_input) static
References input_source_t::b_eof, demux_Control(), demux_Demux(), DEMUX_GET_TIME, DEMUX_SET_NEXT_DEMUX_TIME, input_thread_private_t::i_slave, input_priv(), msg_Dbg, msg_Err, input_source_t::p_demux, and input_thread_private_t::slave.
Referenced by MainLoopDemux().
SlaveExists()
static bool SlaveExists (input_item_slave_t ** pp_slaves, int i_slaves, const char * psz_uri) static
Referenced by LoadSlaves().
SlaveSeek()
static void SlaveSeek (input_thread_t * p_input) static
References input_source_t::b_eof, demux_Control(), DEMUX_GET_TIME, DEMUX_SET_TIME, input_thread_private_t::i_slave, input_priv(), msg_Err, input_source_t::p_demux, and input_thread_private_t::slave.
Referenced by Control().
StartTitle()
static void StartTitle (input_thread_t * p_input) static
References input_thread_private_t::b_fast_seek, CLOCK_FREQ, vlc_value_t::i_int, input_source_t::i_seekpoint_offset, input_source_t::i_seekpoint_start, input_thread_private_t::i_start, input_thread_private_t::i_stop, input_source_t::i_title, input_source_t::i_title_offset, input_source_t::i_title_start, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_TIME, INPUT_CONTROL_SET_TITLE, input_ControlPush(), input_priv(), input_thread_private_t::master, msg_Dbg, msg_Warn, var_GetBool, and var_GetFloat.
Referenced by Init().
UpdateGenericFromDemux()
static void UpdateGenericFromDemux (input_thread_t * p_input) static
References demux_Control(), DEMUX_GET_SIGNAL, demux_TestAndClearFlags(), input_priv(), input_SendEventSignal(), INPUT_UPDATE_META, InputUpdateMeta(), input_thread_private_t::master, and input_source_t::p_demux.
Referenced by MainLoopDemux().
UpdatePtsDelay()
static void UpdatePtsDelay (input_thread_t * p_input) static
References AUDIO_ES, DEFAULT_PTS_DELAY, es_out_SetDelay(), es_out_SetJitter(), input_source_t::i_pts_delay, input_thread_private_t::i_slave, input_priv(), input_thread_private_t::master, input_thread_private_t::slave, SPU_ES, and var_GetInteger.
Referenced by Control(), and InitPrograms().
UpdateTitleListfromDemux()
static void UpdateTitleListfromDemux (input_thread_t * p_input) static
References input_source_t::b_title_demux, demux_Control(), DEMUX_GET_TITLE_INFO, input_source_t::i_seekpoint_offset, input_source_t::i_title, input_thread_private_t::i_title, input_source_t::i_title_offset, InitTitle(), input_priv(), input_thread_private_t::master, input_source_t::p_demux, TAB_CLEAN, TAB_INIT, input_source_t::title, input_thread_private_t::title, and vlc_input_title_Delete().
Referenced by MainLoopDemux().
UpdateTitleSeekpoint()
static int UpdateTitleSeekpoint (input_thread_t * p_input, int i_title, int i_seekpoint) static
References input_source_t::i_seekpoint_end, input_source_t::i_seekpoint_offset, input_source_t::i_title_end, input_source_t::i_title_offset, input_priv(), input_thread_private_t::master, VLC_DEMUXER_EOF, and VLC_DEMUXER_SUCCESS.
Referenced by UpdateTitleSeekpointFromDemux().
UpdateTitleSeekpointFromDemux()
static int UpdateTitleSeekpointFromDemux (input_thread_t * p_input) static
References demux_GetSeekpoint(), demux_GetTitle(), demux_TestAndClearFlags(), input_priv(), input_SendEventSeekpoint(), input_SendEventTitle(), INPUT_UPDATE_SEEKPOINT, INPUT_UPDATE_TITLE, input_thread_private_t::master, input_source_t::p_demux, and UpdateTitleSeekpoint().
Referenced by MainLoopDemux().
ViewpointApply()
static void ViewpointApply (input_thread_t * p_input) static
References input_priv(), input_resource_HoldAout(), input_resource_HoldVouts(), input_thread_private_t::p_resource, var_Change, var_SetAddress, input_thread_private_t::viewpoint, vlc_object_release, VLC_VAR_SETVALUE, and vlc_viewpoint_clip().
Referenced by Control(), and ControlNav().