VLC: src/input/services_discovery.c File Reference
services_discovery.c File Reference
Data Structures
struct vlc_sd_probe_t
Functions
int vlc_sd_probe_Add (vlc_probe_t *probe, const char *name, const char *longname, int category)
char ** vlc_sd_GetNames (vlc_object_t *obj, char ***pppsz_longnames, int **pp_categories)
Gets the list of available services discovery plugins.
services_discovery_t * vlc_sd_Create (vlc_object_t *parent, const char *cfg, const struct services_discovery_owner_t *restrict owner)
void vlc_sd_Destroy (services_discovery_t *sd)
Function Documentation
vlc_sd_Create()
services_discovery_t * vlc_sd_Create (vlc_object_t * parent, const char * cfg, const struct services_discovery_owner_t *restrict owner)
References config_ChainCreate(), services_discovery_t::description, module_need, msg_Err, services_discovery_t::owner, services_discovery_t::p_cfg, services_discovery_t::p_module, services_discovery_t::psz_name, unlikely, vlc_custom_create, and vlc_sd_Destroy().
Referenced by playlist_ServicesDiscoveryAdd().
vlc_sd_Destroy()
void vlc_sd_Destroy (services_discovery_t * sd)
References config_ChainDestroy(), module_unneed, services_discovery_t::p_cfg, services_discovery_t::p_module, services_discovery_t::psz_name, and vlc_object_release.
Referenced by playlist_ServicesDiscoveryInternalRemoveLocked(), and vlc_sd_Create().
vlc_sd_GetNames()
char ** vlc_sd_GetNames (vlc_object_t * obj, char *** pppsz_longnames, int ** pp_categories)
Gets the list of available services discovery plugins.
References vlc_sd_probe_t::category, count, vlc_sd_probe_t::longname, vlc_sd_probe_t::name, unlikely, vlc_alloc(), and vlc_probe.
vlc_sd_probe_Add()
int vlc_sd_probe_Add (vlc_probe_t * probe, const char * name, const char * longname, int category)
< Not enough memory
< Unspecified error
References vlc_sd_probe_t::longname, name, vlc_sd_probe_t::name, strdup(), unlikely, VLC_ENOMEM, vlc_probe_add(), and VLC_PROBE_CONTINUE.