VLC: src/input/control.c File Reference
control.c File Reference
Functions
static void UpdateBookmarksOption (input_thread_t *)
int input_Control (input_thread_t *p_input, int i_query,...)
Control function for inputs.
int input_vaControl (input_thread_t *p_input, int i_query, va_list args)
Function Documentation
input_Control()
int input_Control (input_thread_t * p_input, int i_query, ...)
Control function for inputs.
Parameters
p_input input handle
i_query query type
Returns
VLC_SUCCESS if ok
References input_vaControl().
Referenced by Create(), DecoderGetInputAttachments(), EsDeleteInfo(), EsOutProgramEpg(), EsOutProgramMeta(), EsOutProgramUpdateScrambled(), EsOutUpdateInfo(), input_AddSlave(), input_GetAout(), input_GetEsObjects(), input_GetPcrSystem(), input_GetState(), input_GetVout(), input_ModifyPcrSystem(), input_UpdateViewpoint(), playlist_SetRenderer(), RequestVout(), spu_get_attachments(), and VideoSplitterCallback().
input_vaControl()
int input_vaControl (input_thread_t * p_input, int i_query, va_list args)
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< No error
< Unspecified error
< No error
< No error
< Unspecified error
< No error
< Unspecified error
< No error
< Unspecified error
< No error
< Unspecified error
< No error
< No error
< No error
< No error
< Unspecified error
< Not enough memory
< No error
< Unspecified error
< No error
< Not enough memory
< No error
< Unspecified error
< Unspecified error
< Not enough memory
< No error
< Unspecified error
< No error
< No error
< Unspecified error
< No error
< No error
< No error
< Not enough memory
< No error
< Unspecified error
< No error
< Unspecified error
< No error
< No error
< Unspecified error
References _, asprintf(), input_thread_private_t::attachment, input_item_slave::b_forced, input_thread_private_t::b_preparsing, input_thread_private_t::bookmark, count, es_out_Control(), es_out_ControlGetPcrSystem(), es_out_ControlModifyPcrSystem(), ES_OUT_GET_ES_OBJECTS_BY_ID, input_thread_private_t::i_attachment, input_thread_private_t::i_bookmark, vlc_value_t::i_int, input_title_t::i_seekpoint, input_thread_private_t::i_title, INPUT_ADD_BOOKMARK, INPUT_ADD_INFO, INPUT_ADD_SLAVE, INPUT_CHANGE_BOOKMARK, INPUT_CLEAR_BOOKMARKS, INPUT_CONTROL_ADD_SLAVE, INPUT_CONTROL_NAV_ACTIVATE, INPUT_CONTROL_RESTART_ES, INPUT_CONTROL_SET_BOOKMARK, INPUT_CONTROL_SET_INITIAL_VIEWPOINT, INPUT_CONTROL_SET_RENDERER, INPUT_CONTROL_SET_VIEWPOINT, INPUT_CONTROL_UPDATE_VIEWPOINT, input_ControlPush(), INPUT_DEL_BOOKMARK, INPUT_DEL_INFO, INPUT_GET_AOUT, INPUT_GET_ATTACHMENT, INPUT_GET_ATTACHMENTS, INPUT_GET_AUDIO_DELAY, INPUT_GET_BOOKMARK, INPUT_GET_BOOKMARKS, INPUT_GET_ES_OBJECTS, INPUT_GET_FULL_TITLE_INFO, INPUT_GET_LENGTH, INPUT_GET_PCR_SYSTEM, INPUT_GET_POSITION, INPUT_GET_RATE, INPUT_GET_RECORD_STATE, INPUT_GET_SEEKPOINTS, INPUT_GET_SPU_DELAY, INPUT_GET_STATE, INPUT_GET_TIME, INPUT_GET_TITLE_INFO, INPUT_GET_VOUTS, input_GetVout(), input_item_AddInfo(), input_item_DelInfo(), input_item_MergeInfos(), input_item_ReplaceInfos(), input_item_slave_New(), INPUT_MERGE_INFOS, INPUT_MODIFY_PCR_SYSTEM, INPUT_NAV_ACTIVATE, INPUT_NAV_DOWN, INPUT_NAV_LEFT, INPUT_NAV_MENU, INPUT_NAV_POPUP, INPUT_NAV_RIGHT, INPUT_NAV_UP, input_priv(), INPUT_RATE_DEFAULT, INPUT_REPLACE_INFOS, input_resource_HoldAout(), input_resource_HoldVouts(), INPUT_RESTART_ES, input_SendEventMetaInfo(), INPUT_SET_AUDIO_DELAY, INPUT_SET_BOOKMARK, INPUT_SET_INITIAL_VIEWPOINT, INPUT_SET_POSITION, INPUT_SET_RATE, INPUT_SET_RECORD_STATE, INPUT_SET_RENDERER, INPUT_SET_SPU_DELAY, INPUT_SET_STATE, INPUT_SET_TIME, INPUT_UPDATE_VIEWPOINT, input_item_t::lock, msg_Err, vlc_value_t::p_address, input_thread_private_t::p_es_out_display, input_thread_private_t::p_item, input_thread_private_t::p_resource, input_thread_private_t::pp_bookmark, input_attachment_t::psz_name, psz_name, seekpoint_t::psz_name, psz_value, input_title_t::seekpoint, SLAVE_PRIORITY_USER, SLAVE_TYPE_AUDIO, SLAVE_TYPE_SPU, subtitles_Filter(), TAB_APPEND, TAB_CLEAN, TAB_REMOVE, input_thread_private_t::title, unlikely, UpdateBookmarksOption(), var_GetBool, var_GetFloat, var_GetInteger, var_SetBool, var_SetFloat, var_SetInteger, vasprintf(), vlc_alloc(), VLC_EGENERIC, VLC_ENOMEM, vlc_gettext(), vlc_input_attachment_Duplicate(), vlc_input_title_Duplicate(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, vlc_renderer_item_hold(), vlc_seekpoint_Delete(), vlc_seekpoint_Duplicate(), VLC_SUCCESS, vout_OSDMessage(), and VOUT_SPU_CHANNEL_OSD.
Referenced by input_Control().
UpdateBookmarksOption()
static void UpdateBookmarksOption (input_thread_t * p_input) static
References CLOCK_FREQ, input_thread_private_t::i_bookmark, input_item_t::i_options, seekpoint_t::i_time_offset, input_item_AddOption(), input_priv(), input_SendEventBookmark(), input_item_t::lock, input_thread_private_t::p_item, input_thread_private_t::pp_bookmark, input_item_t::ppsz_options, seekpoint_t::psz_name, vlc_memstream::ptr, var_Change, VLC_INPUT_OPTION_UNIQUE, vlc_memstream_close(), vlc_memstream_open(), vlc_memstream_printf(), vlc_memstream_puts(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_VAR_ADDCHOICE, and VLC_VAR_CLEARCHOICES.
Referenced by input_vaControl().