VLC: src/input/input_internal.h File Reference
input_internal.h File Reference
Data Structures
struct input_source_t
struct input_control_t
struct input_thread_private_t
Private input fields.
Macros
#define INPUT_CONTROL_FIFO_SIZE 100
#define INPUT_PTS_DELAY_MAX INT64_C(60000000)
Typedefs
typedef struct input_thread_private_t input_thread_private_t
Private input fields.
Enumerations
enum input_control_e {
INPUT_CONTROL_SET_STATE , INPUT_CONTROL_SET_RATE , INPUT_CONTROL_SET_POSITION , INPUT_CONTROL_SET_TIME ,
INPUT_CONTROL_SET_PROGRAM , INPUT_CONTROL_SET_TITLE , INPUT_CONTROL_SET_TITLE_NEXT , INPUT_CONTROL_SET_TITLE_PREV ,
INPUT_CONTROL_SET_SEEKPOINT , INPUT_CONTROL_SET_SEEKPOINT_NEXT , INPUT_CONTROL_SET_SEEKPOINT_PREV , INPUT_CONTROL_SET_BOOKMARK ,
INPUT_CONTROL_NAV_ACTIVATE , INPUT_CONTROL_NAV_UP , INPUT_CONTROL_NAV_DOWN , INPUT_CONTROL_NAV_LEFT ,
INPUT_CONTROL_NAV_RIGHT , INPUT_CONTROL_NAV_POPUP , INPUT_CONTROL_NAV_MENU , INPUT_CONTROL_SET_ES ,
INPUT_CONTROL_RESTART_ES , INPUT_CONTROL_SET_VIEWPOINT , INPUT_CONTROL_SET_INITIAL_VIEWPOINT , INPUT_CONTROL_UPDATE_VIEWPOINT ,
INPUT_CONTROL_SET_AUDIO_DELAY , INPUT_CONTROL_SET_SPU_DELAY , INPUT_CONTROL_ADD_SLAVE , INPUT_CONTROL_SET_RECORD_STATE ,
INPUT_CONTROL_SET_FRAME_NEXT , INPUT_CONTROL_SET_RENDERER
}
Functions
static input_thread_private_t * input_priv (input_thread_t *input)
void input_ControlPush (input_thread_t *, int i_type, vlc_value_t *)
bool input_Stopped (input_thread_t *)
void input_ExtractAttachmentAndCacheArt (input_thread_t *, const char *name)
void input_ControlVarInit (input_thread_t *)
void input_ControlVarStop (input_thread_t *)
void input_ControlVarNavigation (input_thread_t *)
void input_ControlVarTitle (input_thread_t *, int i_title)
void input_ConfigVarInit (input_thread_t *)
int subtitles_Detect (input_thread_t *, char *, const char *, input_item_slave_t ***, int *)
Detect subtitle files.
int subtitles_Filter (const char *)
void input_SplitMRL (const char **, const char **, const char **, const char **, char *)
void vlc_audio_replay_gain_MergeFromMeta (audio_replay_gain_t *p_dst, const vlc_meta_t *p_meta)
void input_item_node_PostAndDelete (input_item_node_t *p_node)
Macro Definition Documentation
INPUT_CONTROL_FIFO_SIZE
#define INPUT_CONTROL_FIFO_SIZE 100
Referenced by input_ControlPush().
INPUT_PTS_DELAY_MAX
#define INPUT_PTS_DELAY_MAX INT64_C(60000000)
Referenced by EsOutControlLocked(), and InputSourceNew().
Typedef Documentation
input_thread_private_t
typedef struct input_thread_private_t input_thread_private_t
Private input fields.
Enumeration Type Documentation
input_control_e
enum input_control_e
Enumerator
INPUT_CONTROL_SET_STATE
INPUT_CONTROL_SET_RATE
INPUT_CONTROL_SET_POSITION
INPUT_CONTROL_SET_TIME
INPUT_CONTROL_SET_PROGRAM
INPUT_CONTROL_SET_TITLE
INPUT_CONTROL_SET_TITLE_NEXT
INPUT_CONTROL_SET_TITLE_PREV
INPUT_CONTROL_SET_SEEKPOINT
INPUT_CONTROL_SET_SEEKPOINT_NEXT
INPUT_CONTROL_SET_SEEKPOINT_PREV
INPUT_CONTROL_SET_BOOKMARK
INPUT_CONTROL_NAV_ACTIVATE
INPUT_CONTROL_NAV_UP
INPUT_CONTROL_NAV_DOWN
INPUT_CONTROL_NAV_LEFT
INPUT_CONTROL_NAV_RIGHT
INPUT_CONTROL_NAV_POPUP
INPUT_CONTROL_NAV_MENU
INPUT_CONTROL_SET_ES
INPUT_CONTROL_RESTART_ES
INPUT_CONTROL_SET_VIEWPOINT
INPUT_CONTROL_SET_INITIAL_VIEWPOINT
INPUT_CONTROL_UPDATE_VIEWPOINT
INPUT_CONTROL_SET_AUDIO_DELAY
INPUT_CONTROL_SET_SPU_DELAY
INPUT_CONTROL_ADD_SLAVE
INPUT_CONTROL_SET_RECORD_STATE
INPUT_CONTROL_SET_FRAME_NEXT
INPUT_CONTROL_SET_RENDERER
Function Documentation
input_ConfigVarInit()
void input_ConfigVarInit (input_thread_t * p_input)
References input_priv(), var_Create, var_SetBool, var_SetFloat, var_SetInteger, VLC_VAR_BOOL, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_STRING.
Referenced by Create().
input_ControlPush()
void input_ControlPush (input_thread_t * p_input, int i_type, vlc_value_t * p_val)
References input_thread_private_t::control, ControlRelease(), input_thread_private_t::i_control, i_type, input_control_t::i_type, INPUT_CONTROL_FIFO_SIZE, input_priv(), input_thread_private_t::is_stopped, input_thread_private_t::lock_control, msg_Dbg, msg_Err, input_control_t::val, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), and input_thread_private_t::wait_control.
Referenced by BookmarkCallback(), EsAudioCallback(), EsDelayCallback(), EsSpuCallback(), EsVideoCallback(), FrameNextCallback(), Init(), input_vaControl(), MainLoopTryRepeat(), NavigationCallback(), PositionCallback(), ProgramCallback(), RateCallback(), RecordCallback(), SeekpointCallback(), StartTitle(), StateCallback(), TimeCallback(), TitleCallback(), and TsRun().
input_ControlVarInit()
void input_ControlVarInit (input_thread_t * p_input)
References _, vlc_value_t::i_int, input_thread_private_t::i_state, input_priv(), InputAddCallbacks(), p_input_callbacks, vlc_value_t::psz_string, var_Change, var_Create, var_Get, var_GetInteger, var_SetInteger, VLC_VAR_DELCHOICE, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, VLC_VAR_SETVALUE, VLC_VAR_STRING, and VLC_VAR_VOID.
Referenced by Create().
input_ControlVarNavigation()
void input_ControlVarNavigation (input_thread_t * p_input)
References _, asprintf(), CLOCK_FREQ, vlc_value_t::i_int, input_title_t::i_length, input_title_t::i_seekpoint, input_thread_private_t::i_title, input_priv(), MSTRTIME_MAX_SIZE, NavigationCallback(), psz_name, seekpoint_t::psz_name, vlc_value_t::psz_string, secstotimestr(), input_title_t::seekpoint, strdup(), input_thread_private_t::title, TitleCallback(), var_AddCallback, var_Change, var_Create, var_Destroy, var_Type, VLC_VAR_ADDCHOICE, VLC_VAR_CLEARCHOICES, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, and VLC_VAR_VOID.
Referenced by InitTitle().
input_ControlVarStop()
void input_ControlVarStop (input_thread_t * p_input)
References input_thread_private_t::i_title, input_priv(), InputDelCallbacks(), name, NavigationCallback(), p_input_callbacks, p_input_title_navigation_callbacks, var_DelCallback, var_Destroy, and var_Type.
Referenced by End().
input_ControlVarTitle()
void input_ControlVarTitle (input_thread_t * p_input, int i_title)
References _, asprintf(), vlc_value_t::i_int, input_title_t::i_seekpoint, input_priv(), seekpoint_t::psz_name, vlc_value_t::psz_string, input_title_t::seekpoint, SeekpointCallback(), strdup(), input_thread_private_t::title, var_AddCallback, var_Change, var_Create, var_Destroy, var_Type, VLC_VAR_ADDCHOICE, VLC_VAR_CLEARCHOICES, VLC_VAR_SETTEXT, and VLC_VAR_VOID.
Referenced by input_SendEventTitle().
input_ExtractAttachmentAndCacheArt()
void input_ExtractAttachmentAndCacheArt (input_thread_t * p_input, const char * name)
< No error
References input_thread_private_t::attachment, input_thread_private_t::i_attachment, input_attachment_t::i_data, input_item_IsArtFetched(), input_priv(), likely, input_item_t::lock, msg_Warn, name, input_attachment_t::p_data, input_thread_private_t::p_item, playlist_FindArtInCache(), playlist_SaveArt(), input_attachment_t::psz_mime, input_attachment_t::psz_name, vlc_input_attachment_Delete(), vlc_input_attachment_Duplicate(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, and VLC_SUCCESS.
Referenced by EsOutMeta().
input_item_node_PostAndDelete()
void input_item_node_PostAndDelete (input_item_node_t * p_node)
References input_item_t::event_manager, input_item_node_Delete(), input_item_node_t::p_item, and vlc_event_send().
Referenced by EsOutControlLocked().
input_priv()
static input_thread_private_t * input_priv (input_thread_t * input) inline static
References container_of.
Referenced by AStreamReadBlock(), AStreamReadStream(), Control(), ControlGetReducedIndexLocked(), ControlInsertDemuxFilter(), ControlLockedGetWakeup(), ControlLockedSetPauseState(), ControlLockedSetRate(), ControlNav(), ControlPause(), ControlPop(), ControlUnpause(), Create(), DecoderQueueSpu(), DecoderUpdateStatAudio(), DecoderUpdateStatVideo(), End(), EsCreateDecoder(), EsOutAddSlave(), EsOutControlLocked(), EsOutDecodersStopBuffering(), EsOutEpgTime(), EsOutGetWakeup(), EsOutMeta(), EsOutProgramEpg(), EsOutProgramEpgEvent(), EsOutProgramMeta(), EsOutProgramSelect(), EsOutPropsInit(), EsOutSend(), EsOutTerminate(), EsSelect(), Init(), InitPrograms(), InitStatistics(), InitTitle(), input_ChangeState(), input_Close(), input_ConfigVarInit(), input_ControlPush(), input_ControlVarInit(), input_ControlVarNavigation(), input_ControlVarStop(), input_ControlVarTitle(), input_DecoderNew(), input_Destructor(), input_ExtractAttachmentAndCacheArt(), input_GetItem(), input_SendEventLength(), input_SlaveSourceAdd(), input_Start(), input_Stop(), input_Stopped(), input_UpdateStatistic(), input_vaControl(), InputDemuxNew(), InputSourceMeta(), InputSourceNew(), InputUpdateMeta(), LoadSlaves(), MainLoop(), MainLoopDemux(), MainLoopStatistics(), MainLoopTryRepeat(), PreparserCloseInput(), SetSubtitlesOptions(), SlaveDemux(), SlaveSeek(), StartTitle(), stats_ComputeInputStats(), UpdateBookmarksOption(), UpdateGenericFromDemux(), UpdatePtsDelay(), UpdateTitleListfromDemux(), UpdateTitleSeekpoint(), UpdateTitleSeekpointFromDemux(), and ViewpointApply().
input_SplitMRL()
void input_SplitMRL (const char ** access, const char ** demux, const char ** path, const char ** anchor, char * buf)
References p.
Referenced by InputSourceNew().
input_Stopped()
bool input_Stopped (input_thread_t * input)
References input_priv(), input_thread_private_t::is_stopped, input_thread_private_t::lock_control, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutDel(), InputSourceNew(), and MainLoop().
subtitles_Detect()
int subtitles_Detect (input_thread_t * p_this, char * psz_path, const char * psz_name_org, input_item_slave_t *** ppp_slaves, int * p_slaves)
Detect subtitle files.
When called this function will split up the psz_name string into a directory, filename and extension. It then opens the directory in which the file resides and tries to find possible matches of subtitles files.
Parameters
p_this the calling input_thread_t
psz_path a list of subdirectories (separated by a ',') to look in.
psz_name_org the complete filename to base the search on.
pp_slaves an initialized input item slave list to append detected subtitles to
p_slaves pointer to the size of the slave list
Returns
VLC_SUCCESS if ok
< Unspecified error
< Unspecified error
< Unspecified error
< Not enough memory
< Unspecified error
< Not enough memory
< No error
References asprintf(), input_item_slave::b_forced, DIR_SEP, DIR_SEP_CHAR, input_item_slave::i_priority, input_item_slave_Delete, input_item_slave_New(), msg_Dbg, paths_to_list(), psz_ext, psz_name, input_item_slave::psz_uri, SLAVE_PRIORITY_MATCH_ALL, SLAVE_PRIORITY_MATCH_LEFT, SLAVE_PRIORITY_MATCH_NONE, SLAVE_PRIORITY_MATCH_RIGHT, slave_strcmp(), SLAVE_TYPE_SPU, strcasecmp(), strcpy_get_ext(), strcpy_strip_ext(), strcpy_trim(), strdup(), subtitles_Filter(), TAB_APPEND, var_GetInteger, VLC_EGENERIC, VLC_ENOMEM, vlc_opendir(), vlc_path2uri(), vlc_readdir(), vlc_stat(), VLC_SUCCESS, vlc_uri2path(), and whiteonly().
Referenced by LoadSlaves().
subtitles_Filter()
int subtitles_Filter (const char * psz_dir_content)
References strcasecmp(), and sub_exts.
Referenced by input_vaControl(), and subtitles_Detect().
vlc_audio_replay_gain_MergeFromMeta()
void vlc_audio_replay_gain_MergeFromMeta (audio_replay_gain_t * p_dst, const vlc_meta_t * p_meta)
References AUDIO_REPLAY_GAIN_ALBUM, AUDIO_REPLAY_GAIN_TRACK, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pb_peak, audio_replay_gain_t::pf_gain, audio_replay_gain_t::pf_peak, psz_value, us_atof(), and vlc_meta_GetExtra().
Referenced by EsOutAddSlave().