VLC: src/input/item.c File Reference
item.c File Reference
Data Structures
struct input_item_opaque
struct item_type_entry
struct rdh_slave
struct rdh_dir
Functions
static int GuessType (const input_item_t *p_item, bool *p_net)
void input_item_SetErrorWhenReading (input_item_t *p_i, bool b_error)
void input_item_SignalPreparseEnded (input_item_t *p_i, int status)
void input_item_SetPreparsed (input_item_t *p_i, bool b_preparsed)
void input_item_SetArtNotFound (input_item_t *p_i, bool b_not_found)
void input_item_SetArtFetched (input_item_t *p_i, bool b_art_fetched)
void input_item_SetMeta (input_item_t *p_i, vlc_meta_type_t meta_type, const char *psz_val)
void input_item_CopyOptions (input_item_t *p_child, input_item_t *p_parent)
bool input_item_HasErrorWhenReading (input_item_t *p_item)
bool input_item_MetaMatch (input_item_t *p_i, vlc_meta_type_t meta_type, const char *psz)
char * input_item_GetMeta (input_item_t *p_i, vlc_meta_type_t meta_type)
char * input_item_GetTitleFbName (input_item_t *p_item)
char * input_item_GetName (input_item_t *p_item)
void input_item_SetName (input_item_t *p_item, const char *psz_name)
char * input_item_GetURI (input_item_t *p_i)
void input_item_SetURI (input_item_t *p_i, const char *psz_uri)
mtime_t input_item_GetDuration (input_item_t *p_i)
void input_item_SetDuration (input_item_t *p_i, mtime_t i_duration)
char * input_item_GetNowPlayingFb (input_item_t *p_item)
bool input_item_IsPreparsed (input_item_t *p_item)
bool input_item_IsArtFetched (input_item_t *p_item)
bool input_item_ShouldPreparseSubItems (input_item_t *p_item)
input_item_t * input_item_Hold (input_item_t *p_item)
Holds an input item, i.e.
void input_item_Release (input_item_t *p_item)
Releases an input item, i.e.
int input_item_AddOption (input_item_t *p_input, const char *psz_option, unsigned flags)
This function allows to add an option to an existing input_item_t.
int input_item_AddOptions (input_item_t *p_item, int i_options, const char *const *ppsz_options, unsigned i_flags)
This function add several options to an existing input_item_t.
int input_item_AddOpaque (input_item_t *item, const char *name, void *value)
void input_item_ApplyOptions (vlc_object_t *obj, input_item_t *item)
static int bsearch_strcmp_cb (const void *a, const void *b)
static bool input_item_IsMaster (const char *psz_filename)
bool input_item_slave_GetType (const char *psz_filename, enum slave_type *p_slave_type)
input_item_slave_t * input_item_slave_New (const char *psz_uri, enum slave_type i_type, enum slave_priority i_priority)
int input_item_AddSlave (input_item_t *p_item, input_item_slave_t *p_slave)
This function allows adding a slave to an existing input item.
static info_category_t * InputItemFindCat (input_item_t *p_item, int *pi_index, const char *psz_cat)
char * input_item_GetInfo (input_item_t *p_i, const char *psz_cat, const char *psz_name)
Get a info item from a given category in a given input item.
static int InputItemVaAddInfo (input_item_t *p_i, const char *psz_cat, const char *psz_name, const char *psz_format, va_list args)
int input_item_AddInfo (input_item_t *p_i, const char *psz_cat, const char *psz_name, const char *psz_format,...)
int input_item_DelInfo (input_item_t *p_i, const char *psz_cat, const char *psz_name)
void input_item_ReplaceInfos (input_item_t *p_item, info_category_t *p_cat)
void input_item_MergeInfos (input_item_t *p_item, info_category_t *p_cat)
void input_item_SetEpgEvent (input_item_t *p_item, const vlc_epg_event_t *p_epg_evt)
void input_item_SetEpg (input_item_t *p_item, const vlc_epg_t *p_update, bool b_current_source)
void input_item_ChangeEPGSource (input_item_t *p_item, int i_source_id)
void input_item_SetEpgTime (input_item_t *p_item, int64_t i_time)
void input_item_SetEpgOffline (input_item_t *p_item)
input_item_t * input_item_NewExt (const char *psz_uri, const char *psz_name, mtime_t duration, int type, enum input_item_net_type i_net)
This function creates a new input_item_t with the provided information.
input_item_t * input_item_Copy (input_item_t *p_input)
This function creates a new input_item_t as a copy of another.
static int typecmp (const void *key, const void *entry)
input_item_node_t * input_item_node_Create (input_item_t *p_input)
Start adding multiple subitems.
void input_item_node_Delete (input_item_node_t *p_node)
Delete a node created with input_item_node_Create() and all its children.
input_item_node_t * input_item_node_AppendItem (input_item_node_t *p_node, input_item_t *p_item)
Add a new child node to this parent node that will point to this subitem.
void input_item_node_AppendNode (input_item_node_t *p_parent, input_item_node_t *p_child)
Add an already created node to children of this parent node.
void input_item_node_RemoveNode (input_item_node_t *parent, input_item_node_t *child)
Remove a node from its parent.
void input_item_node_PostAndDelete (input_item_node_t *p_root)
void input_item_UpdateTracksInfo (input_item_t *item, const es_format_t *fmt)
static int rdh_compar_type (input_item_t *p1, input_item_t *p2)
static int rdh_compar_filename (const void *a, const void *b)
static void rdh_sort (input_item_node_t *p_node)
static bool rdh_file_has_ext (const char *psz_filename, const char *psz_ignored_exts)
Does the provided file name has one of the extension provided ?
static bool rdh_file_is_ignored (struct vlc_readdir_helper *p_rdh, const char *psz_filename)
static char * rdh_name_from_filename (const char *psz_filename)
static uint8_t rdh_get_slave_priority (input_item_t *p_item, input_item_slave_t *p_slave, const char *psz_slave_filename)
static int rdh_should_match_idx (struct vlc_readdir_helper *p_rdh, struct rdh_slave *p_rdh_sub)
static void rdh_attach_slaves (struct vlc_readdir_helper *p_rdh, input_item_node_t *p_parent_node)
static int rdh_unflatten (struct vlc_readdir_helper *p_rdh, input_item_node_t **pp_node, const char *psz_path, int i_net)
void vlc_readdir_helper_init (struct vlc_readdir_helper *p_rdh, vlc_object_t *p_obj, input_item_node_t *p_node)
Init a vlc_readdir_helper struct.
void vlc_readdir_helper_finish (struct vlc_readdir_helper *p_rdh, bool b_success)
Finish adding items to the node.
int vlc_readdir_helper_additem (struct vlc_readdir_helper *p_rdh, const char *psz_uri, const char *psz_flatpath, const char *psz_filename, int i_type, int i_net)
Add a new input_item_t entry to the node of the vlc_readdir_helper struct.
Function Documentation
bsearch_strcmp_cb()
static int bsearch_strcmp_cb (const void * a, const void * b) static
References strcasecmp().
Referenced by input_item_IsMaster(), and input_item_slave_GetType().
GuessType()
static int GuessType (const input_item_t * p_item, bool * p_net) static
References ARRAY_SIZE, item_type_entry::b_net, item_type_entry::i_type, ITEM_TYPE_CARD, ITEM_TYPE_DIRECTORY, ITEM_TYPE_DISC, ITEM_TYPE_FILE, ITEM_TYPE_PLAYLIST, ITEM_TYPE_STREAM, ITEM_TYPE_UNKNOWN, item_type_entry::psz_scheme, input_item_t::psz_uri, and typecmp().
Referenced by input_item_SetURI().
input_item_AddInfo()
int input_item_AddInfo (input_item_t * p_i, const char * psz_cat, const char * psz_name, const char * psz_format, ...)
References input_item_t::event_manager, InputItemVaAddInfo(), input_item_t::lock, psz_name, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_vaControl().
input_item_AddOpaque()
int input_item_AddOpaque (input_item_t * item, const char * name, void * value)
< Not enough memory
< No error
References input_item_t::lock, name, input_item_t::opaques, unlikely, input_item_opaque::value, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
input_item_AddOption()
int input_item_AddOption (input_item_t * p_input, const char * psz_option, unsigned flags)
This function allows to add an option to an existing input_item_t.
< No error
< Unspecified error
< Not enough memory
< Not enough memory
References input_item_t::i_options, input_item_t::lock, input_item_t::optflagc, input_item_t::optflagv, input_item_t::ppsz_options, strdup(), TAB_APPEND, unlikely, VLC_EGENERIC, VLC_ENOMEM, VLC_INPUT_OPTION_UNIQUE, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by input_item_AddOptions(), UpdateBookmarksOption(), vlm_ControlMediaInstanceStart(), and vlm_OnMediaUpdate().
input_item_AddOptions()
int input_item_AddOptions (input_item_t * p_item, int i_options, const char *const * ppsz_options, unsigned i_flags)
This function add several options to an existing input_item_t.
< No error
< No error
References input_item_AddOption(), and VLC_SUCCESS.
Referenced by intf_InsertItem(), and playlist_AddExt().
input_item_AddSlave()
int input_item_AddSlave (input_item_t * p_item, input_item_slave_t * p_slave)
This function allows adding a slave to an existing input item.
The slave is owned by the input item after this call.
< Unspecified error
< No error
References input_item_slave::i_priority, input_item_t::i_slaves, input_item_t::lock, input_item_t::pp_slaves, SLAVE_PRIORITY_MATCH_NONE, TAB_APPEND, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by Control(), LoadSlaves(), and rdh_attach_slaves().
input_item_ApplyOptions()
void input_item_ApplyOptions (vlc_object_t * obj, input_item_t * item)
References input_item_t::i_options, input_item_t::lock, input_item_t::opaques, input_item_t::optflagc, input_item_t::optflagv, input_item_t::ppsz_options, var_Create, var_OptionParse(), var_SetAddress, VLC_INPUT_OPTION_TRUSTED, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_VAR_ADDRESS.
Referenced by Create(), and vlc_readdir_helper_init().
input_item_ChangeEPGSource()
void input_item_ChangeEPGSource (input_item_t * p_item, int i_source_id)
References vlc_epg_t::b_present, input_item_t::i_epg, vlc_epg_t::i_source_id, input_item_t::lock, input_item_t::p_epg_table, input_item_t::pp_epg, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramSelect(), and input_item_SetEpgOffline().
input_item_Copy()
input_item_t * input_item_Copy (input_item_t * p_input)
This function creates a new input_item_t as a copy of another.
References input_item_t::b_net, input_item_t::i_duration, input_item_t::i_type, input_item_CopyOptions(), input_item_NewExt(), ITEM_NET_UNKNOWN, likely, input_item_t::lock, input_item_t::p_meta, input_item_t::psz_name, input_item_t::psz_uri, vlc_meta_Merge(), vlc_meta_New(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by RecursiveInsertCopy().
input_item_CopyOptions()
void input_item_CopyOptions (input_item_t * p_child, input_item_t * p_parent)
References input_item_t::i_options, likely, input_item_t::lock, input_item_t::optflagc, input_item_t::optflagv, input_item_t::ppsz_options, strdup(), unlikely, vlc_alloc(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_item_Copy(), rdh_unflatten(), and vlc_readdir_helper_additem().
input_item_DelInfo()
int input_item_DelInfo (input_item_t * p_i, const char * psz_cat, const char * psz_name)
< Unspecified error
< Unspecified error
< No error
References input_item_t::event_manager, input_item_t::i_categories, info_category_Delete(), info_category_DeleteInfo(), InputItemFindCat(), input_item_t::lock, input_item_t::pp_categories, psz_name, TAB_ERASE, VLC_EGENERIC, vlc_event_send(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by input_item_SetEpg(), input_item_SetEpgOffline(), and input_vaControl().
input_item_GetDuration()
mtime_t input_item_GetDuration (input_item_t * p_i)
References input_item_t::i_duration, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Init(), playlist_GetNodeDuration(), proto_SORT_DURATION(), and vlc_strfinput().
input_item_GetInfo()
char * input_item_GetInfo (input_item_t * p_i, const char * psz_cat, const char * psz_name)
Get a info item from a given category in a given input item.
Parameters
p_i The input item to get info from
psz_cat String representing the category for the info
psz_name String representing the name of the desired info
Returns
A pointer to the string with the given info if found, or an empty string otherwise. The caller should free the returned pointer.
References info_category_FindInfo(), InputItemFindCat(), input_item_t::lock, psz_name, info_t::psz_value, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by playlist_FindArtInCacheUsingItemUID(), and playlist_SaveArt().
input_item_GetMeta()
char * input_item_GetMeta (input_item_t * p_i, vlc_meta_type_t meta_type)
References input_item_t::lock, input_item_t::p_meta, strdup(), vlc_meta_Get(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_item_GetNowPlayingFb(), meta_sort(), vout_OSDEpg(), and write_meta().
input_item_GetName()
char * input_item_GetName (input_item_t * p_item)
References input_item_t::lock, input_item_t::psz_name, psz_name, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Create(), DisplayVoutTitle(), input_Destructor(), and vlc_strfinput().
input_item_GetNowPlayingFb()
char * input_item_GetNowPlayingFb (input_item_t * p_item)
References input_item_GetMeta(), vlc_meta_ESNowPlaying, and vlc_meta_NowPlaying.
Referenced by DisplayVoutTitle(), and vlc_strfinput().
input_item_GetTitleFbName()
char * input_item_GetTitleFbName (input_item_t * p_item)
References EMPTY_STR, input_item_t::lock, input_item_t::p_meta, input_item_t::psz_name, strdup(), vlc_meta_Get(), vlc_meta_Title, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by meta_strcasecmp_title(), proto_SORT_TITLE_NUMERIC(), and vlc_strfinput().
input_item_GetURI()
char * input_item_GetURI (input_item_t * p_i)
References input_item_t::lock, input_item_t::psz_uri, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_item_WriteMeta(), proto_SORT_URI(), and vlc_strfinput().
input_item_HasErrorWhenReading()
bool input_item_HasErrorWhenReading (input_item_t * p_item)
References input_item_t::b_error_when_reading, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
input_item_Hold()
input_item_t * input_item_Hold (input_item_t * p_item)
Holds an input item, i.e.
creates a new reference.
References item_owner, and input_item_owner::refs.
Referenced by Create(), fingerprint_request_New(), input_item_node_Create(), InputItemHold(), playlist_fetcher_Push(), and playlist_ItemNewFromInput().
input_item_IsArtFetched()
bool input_item_IsArtFetched (input_item_t * p_item)
References ITEM_ART_FETCHED, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_ExtractAttachmentAndCacheArt().
input_item_IsMaster()
static bool input_item_IsMaster (const char * psz_filename) static
References ARRAY_SIZE, bsearch_strcmp_cb(), MASTER_EXTENSIONS, and psz_ext.
Referenced by rdh_attach_slaves().
input_item_IsPreparsed()
bool input_item_IsPreparsed (input_item_t * p_item)
References ITEM_PREPARSED, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by playlist_Preparse().
input_item_MergeInfos()
void input_item_MergeInfos (input_item_t * p_item, info_category_t * p_cat)
References input_item_t::event_manager, input_item_t::i_categories, info_category_t::i_infos, info_category_Delete(), info_category_ReplaceInfo(), InputItemFindCat(), input_item_t::lock, input_item_t::pp_categories, info_category_t::pp_infos, info_category_t::psz_name, TAB_APPEND, TAB_CLEAN, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_vaControl().
input_item_MetaMatch()
bool input_item_MetaMatch (input_item_t * p_i, vlc_meta_type_t meta_type, const char * psz)
References input_item_t::lock, input_item_t::p_meta, strcasestr(), vlc_meta_Get(), vlc_mutex_lock(), and vlc_mutex_unlock().
input_item_NewExt()
input_item_t * input_item_NewExt (const char * psz_uri, const char * psz_name, mtime_t i_duration, int i_type, enum input_item_net_type i_net)
This function creates a new input_item_t with the provided information.
XXX You may also use input_item_New, as they need less arguments.
References input_item_t::b_error_when_reading, input_item_t::b_net, input_item_t::es, input_item_t::event_manager, input_item_t::i_categories, input_item_t::i_duration, input_item_t::i_epg, input_item_t::i_es, input_item_t::i_options, input_item_t::i_slaves, input_item_t::i_type, input_item_SetName(), input_item_SetURI(), input_item_owner::item, ITEM_NET, ITEM_NET_UNKNOWN, ITEM_TYPE_UNKNOWN, input_item_t::lock, input_item_t::opaques, input_item_t::optflagc, input_item_t::optflagv, input_item_t::p_meta, input_item_t::p_stats, input_item_t::pp_categories, input_item_t::pp_epg, input_item_t::pp_slaves, input_item_t::ppsz_options, input_item_t::psz_name, psz_name, input_item_t::psz_uri, input_item_owner::refs, TAB_INIT, unlikely, vlc_event_manager_init(), and vlc_mutex_init().
Referenced by input_item_Copy(), playlist_NodeCreate(), rdh_unflatten(), and vlc_readdir_helper_additem().
input_item_node_AppendItem()
input_item_node_t * input_item_node_AppendItem (input_item_node_t * p_node, input_item_t * p_item)
Add a new child node to this parent node that will point to this subitem.
References input_item_t::i_preparse_depth, input_item_node_AppendNode(), input_item_node_Create(), input_item_t::lock, input_item_node_t::p_item, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by rdh_unflatten(), and vlc_readdir_helper_additem().
input_item_node_AppendNode()
void input_item_node_AppendNode (input_item_node_t * p_parent, input_item_node_t * p_child)
Add an already created node to children of this parent node.
References input_item_node_t::i_children, input_item_node_t::pp_children, and TAB_APPEND.
Referenced by input_item_node_AppendItem().
input_item_node_Create()
input_item_node_t * input_item_node_Create (input_item_t * p_input)
Start adding multiple subitems.
Create a root node to hold a tree of subitems for given item
References input_item_node_t::i_children, input_item_Hold(), input_item_node_t::p_item, and input_item_node_t::pp_children.
Referenced by input_item_node_AppendItem().
input_item_node_Delete()
void input_item_node_Delete (input_item_node_t * p_node)
Delete a node created with input_item_node_Create() and all its children.
References input_item_node_t::i_children, input_item_node_Delete(), input_item_Release(), input_item_node_t::p_item, and input_item_node_t::pp_children.
Referenced by input_item_node_Delete(), input_item_node_PostAndDelete(), and rdh_attach_slaves().
input_item_node_PostAndDelete()
void input_item_node_PostAndDelete (input_item_node_t * p_root)
References input_item_t::event_manager, input_item_node_Delete(), input_item_node_t::p_item, and vlc_event_send().
Referenced by EsOutControlLocked().
input_item_node_RemoveNode()
void input_item_node_RemoveNode (input_item_node_t * parent, input_item_node_t * child)
Remove a node from its parent.
References input_item_node_t::i_children, input_item_node_t::pp_children, and TAB_REMOVE.
Referenced by rdh_attach_slaves().
input_item_Release()
void input_item_Release (input_item_t * p_item)
Releases an input item, i.e.
decrements its reference counter.
References input_item_t::es, es_format_Clean(), input_item_t::event_manager, input_item_t::i_categories, input_item_t::i_epg, input_item_t::i_es, input_item_t::i_options, input_item_t::i_slaves, info_category_Delete(), input_item_slave_Delete, item_owner, input_item_t::lock, input_stats_t::lock, input_item_opaque::next, input_item_t::opaques, input_item_t::optflagv, input_item_t::p_meta, input_item_t::p_stats, input_item_t::pp_categories, input_item_t::pp_epg, input_item_t::pp_slaves, input_item_t::ppsz_options, input_item_t::psz_name, input_item_t::psz_uri, input_item_owner::refs, TAB_CLEAN, vlc_epg_Delete(), vlc_event_manager_fini(), vlc_meta_Delete(), and vlc_mutex_destroy().
Referenced by fingerprint_request_Delete(), input_Destructor(), input_item_node_Delete(), InputItemRelease(), intf_InsertItem(), playlist_AddExt(), playlist_ItemRelease(), playlist_MLLoad(), playlist_NodeCreate(), rdh_unflatten(), RecursiveInsertCopy(), RequestRelease(), vlc_readdir_helper_additem(), vlm_ControlMediaDel(), vlm_MediaInstanceDelete(), and vlm_OnMediaUpdate().
input_item_ReplaceInfos()
void input_item_ReplaceInfos (input_item_t * p_item, info_category_t * p_cat)
References input_item_t::event_manager, input_item_t::i_categories, info_category_Delete(), InputItemFindCat(), input_item_t::lock, input_item_t::pp_categories, info_category_t::psz_name, TAB_APPEND, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_vaControl().
input_item_SetArtFetched()
void input_item_SetArtFetched (input_item_t * p_i, bool b_art_fetched)
References ITEM_ART_FETCHED, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Downloader().
input_item_SetArtNotFound()
void input_item_SetArtNotFound (input_item_t * p_i, bool b_not_found)
References ITEM_ART_NOTFOUND, input_item_t::lock, input_item_t::p_meta, vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by SearchLocal(), and SearchNetwork().
input_item_SetDuration()
void input_item_SetDuration (input_item_t * p_i, mtime_t i_duration)
References input_item_t::event_manager, input_item_t::i_duration, input_item_t::lock, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_SendEventLength().
input_item_SetEpg()
void input_item_SetEpg (input_item_t * p_item, const vlc_epg_t * p_update, bool b_current_source)
References asprintf(), vlc_epg_t::b_present, input_item_t::event_manager, vlc_epg_event_t::i_duration, input_item_t::i_epg, vlc_epg_t::i_event, vlc_epg_t::i_id, vlc_epg_t::i_source_id, vlc_epg_event_t::i_start, input_item_DelInfo(), localtime_r(), input_item_t::lock, input_item_t::p_epg_table, input_item_t::pp_epg, vlc_epg_t::pp_event, vlc_epg_event_t::psz_description, vlc_epg_event_t::psz_name, vlc_epg_t::psz_name, vlc_epg_event_t::psz_short_description, TAB_APPEND, vlc_epg_Delete(), vlc_epg_Duplicate(), vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramEpg().
input_item_SetEpgEvent()
void input_item_SetEpgEvent (input_item_t * p_item, const vlc_epg_event_t * p_epg_evt)
References input_item_t::event_manager, input_item_t::i_epg, vlc_epg_t::i_event, vlc_epg_event_t::i_id, input_item_t::lock, vlc_epg_t::p_current, input_item_t::pp_epg, vlc_epg_t::pp_event, vlc_epg_event_Delete(), vlc_epg_event_Duplicate(), vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutProgramEpgEvent().
input_item_SetEpgOffline()
void input_item_SetEpgOffline (input_item_t * p_item)
References asprintf(), input_item_t::event_manager, input_item_t::i_epg, input_item_ChangeEPGSource(), input_item_DelInfo(), input_item_t::lock, input_item_t::pp_epg, vlc_epg_t::psz_name, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutTerminate().
input_item_SetEpgTime()
void input_item_SetEpgTime (input_item_t * p_item, int64_t i_time)
References input_item_t::i_epg_time, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutEpgTime().
input_item_SetErrorWhenReading()
void input_item_SetErrorWhenReading (input_item_t * p_i, bool b_error)
References input_item_t::b_error_when_reading, input_item_t::event_manager, input_item_t::lock, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_ChangeState().
input_item_SetMeta()
void input_item_SetMeta (input_item_t * p_i, vlc_meta_type_t meta_type, const char * psz_val)
References input_item_t::event_manager, input_item_t::lock, input_item_t::p_meta, vlc_event_send(), vlc_meta_New(), vlc_meta_Set(), vlc_mutex_lock(), and vlc_mutex_unlock().
input_item_SetName()
void input_item_SetName (input_item_t * p_item, const char * psz_name)
References input_item_t::lock, input_item_t::psz_name, psz_name, strdup(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutMeta(), and input_item_NewExt().
input_item_SetPreparsed()
void input_item_SetPreparsed (input_item_t * p_i, bool b_preparsed)
References input_item_t::event_manager, ITEM_PREPARSED, input_item_t::lock, input_item_t::p_meta, vlc_event_send(), vlc_meta_GetStatus(), vlc_meta_New(), vlc_meta_SetStatus(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutMeta(), PreparserCloseInput(), and SetPreparsed().
input_item_SetURI()
void input_item_SetURI (input_item_t * p_i, const char * psz_uri)
References asprintf(), input_item_t::b_net, EnsureUTF8(), GuessType(), vlc_url_t::i_port, input_item_t::i_type, ITEM_TYPE_DIRECTORY, ITEM_TYPE_FILE, input_item_t::lock, vlc_url_t::psz_host, input_item_t::psz_name, vlc_url_t::psz_path, vlc_url_t::psz_protocol, input_item_t::psz_uri, strdup(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_uri_decode(), vlc_UrlClean(), and vlc_UrlParse().
Referenced by input_item_NewExt(), and vlm_ControlMediaInstanceStart().
input_item_ShouldPreparseSubItems()
bool input_item_ShouldPreparseSubItems (input_item_t * p_item)
References input_item_t::i_preparse_depth, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Preparse().
input_item_SignalPreparseEnded()
void input_item_SignalPreparseEnded (input_item_t * p_i, int status)
References input_item_t::event_manager, and vlc_event_send().
Referenced by playlist_preparser_Push(), PreparserCloseInput(), PreparserOpenInput(), and SetPreparsed().
input_item_slave_GetType()
bool input_item_slave_GetType (const char * psz_filename, enum slave_type * p_slave_type)
References ARRAY_SIZE, bsearch_strcmp_cb(), i_type, psz_ext, SLAVE_AUDIO_EXTENSIONS, SLAVE_SPU_EXTENSIONS, SLAVE_TYPE_AUDIO, and SLAVE_TYPE_SPU.
Referenced by rdh_attach_slaves(), and vlc_readdir_helper_additem().
input_item_slave_New()
input_item_slave_t * input_item_slave_New (const char * psz_uri, enum slave_type i_type, enum slave_priority i_priority)
References input_item_slave::b_forced, input_item_slave::i_priority, i_type, input_item_slave::i_type, and input_item_slave::psz_uri.
Referenced by GetVarSlaves(), input_vaControl(), LoadSlaves(), rdh_attach_slaves(), subtitles_Detect(), and vlc_readdir_helper_additem().
input_item_UpdateTracksInfo()
void input_item_UpdateTracksInfo (input_item_t * item, const es_format_t * fmt)
References input_item_t::es, es_format_Clean(), es_format_Copy(), input_item_t::i_es, es_format_t::i_id, input_item_t::lock, TAB_APPEND, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutUpdateInfo().
InputItemFindCat()
static info_category_t * InputItemFindCat (input_item_t * p_item, int * pi_index, const char * psz_cat) static
References input_item_t::i_categories, input_item_t::lock, input_item_t::pp_categories, info_category_t::psz_name, and vlc_assert_locked().
Referenced by input_item_DelInfo(), input_item_GetInfo(), input_item_MergeInfos(), input_item_ReplaceInfos(), and InputItemVaAddInfo().
InputItemVaAddInfo()
static int InputItemVaAddInfo (input_item_t * p_i, const char * psz_cat, const char * psz_name, const char * psz_format, va_list args) static
< Not enough memory
< Unspecified error
< No error
References input_item_t::i_categories, info_category_New(), info_category_VaAddInfo(), InputItemFindCat(), input_item_t::lock, input_item_t::pp_categories, psz_name, info_t::psz_value, TAB_APPEND, vlc_assert_locked(), VLC_EGENERIC, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by input_item_AddInfo().
rdh_attach_slaves()
static void rdh_attach_slaves (struct vlc_readdir_helper * p_rdh, input_item_node_t * p_parent_node) static
< No error
References input_item_node_t::i_children, input_item_slave::i_priority, vlc_readdir_helper::i_slaves, vlc_readdir_helper::i_sub_autodetect_fuzzy, input_item_slave::i_type, input_item_AddSlave(), input_item_IsMaster(), input_item_node_Delete(), input_item_node_RemoveNode(), input_item_slave_Delete, input_item_slave_GetType(), input_item_slave_New(), input_item_node_t::p_item, rdh_slave::p_node, rdh_slave::p_slave, input_item_node_t::pp_children, vlc_readdir_helper::pp_slaves, rdh_slave::psz_filename, input_item_t::psz_name, input_item_slave::psz_uri, rdh_attach_slaves(), rdh_get_slave_priority(), rdh_should_match_idx(), SLAVE_PRIORITY_MATCH_ALL, SLAVE_TYPE_SPU, and VLC_SUCCESS.
Referenced by rdh_attach_slaves(), and vlc_readdir_helper_finish().
rdh_compar_filename()
static int rdh_compar_filename (const void * a, const void * b) static
References input_item_t::psz_name, rdh_compar_type(), and vlc_filenamecmp().
Referenced by rdh_sort().
rdh_compar_type()
static int rdh_compar_type (input_item_t * p1, input_item_t * p2) static
References input_item_t::i_type, and ITEM_TYPE_DIRECTORY.
Referenced by rdh_compar_filename().
rdh_file_has_ext()
static bool rdh_file_has_ext (const char * psz_filename, const char * psz_ignored_exts) static
Does the provided file name has one of the extension provided ?
Referenced by rdh_file_is_ignored().
rdh_file_is_ignored()
static bool rdh_file_is_ignored (struct vlc_readdir_helper * p_rdh, const char * psz_filename) static
References vlc_readdir_helper::b_show_hiddenfiles, vlc_readdir_helper::psz_ignored_exts, and rdh_file_has_ext().
Referenced by vlc_readdir_helper_additem().
rdh_get_slave_priority()
static uint8_t rdh_get_slave_priority (input_item_t * p_item, input_item_slave_t * p_slave, const char * psz_slave_filename) static
References input_item_slave::i_type, psz_ext, input_item_t::psz_name, rdh_name_from_filename(), SLAVE_PRIORITY_MATCH_ALL, SLAVE_PRIORITY_MATCH_LEFT, SLAVE_PRIORITY_MATCH_NONE, SLAVE_PRIORITY_MATCH_RIGHT, SLAVE_TYPE_SPU, and strcasecmp().
Referenced by rdh_attach_slaves().
rdh_name_from_filename()
static char * rdh_name_from_filename (const char * psz_filename) static
References psz_name, and strdup().
Referenced by rdh_get_slave_priority().
rdh_should_match_idx()
static int rdh_should_match_idx (struct vlc_readdir_helper * p_rdh, struct rdh_slave * p_rdh_sub) static
References input_item_slave::i_priority, vlc_readdir_helper::i_slaves, rdh_slave::p_slave, vlc_readdir_helper::pp_slaves, psz_ext, rdh_slave::psz_filename, and strcasecmp().
Referenced by rdh_attach_slaves().
rdh_sort()
static void rdh_sort (input_item_node_t * p_node) static
References input_item_node_t::i_children, input_item_node_t::pp_children, rdh_compar_filename(), and rdh_sort().
Referenced by rdh_sort(), and vlc_readdir_helper_finish().
rdh_unflatten()
static int rdh_unflatten (struct vlc_readdir_helper * p_rdh, input_item_node_t ** pp_node, const char * psz_path, int i_net) static
< Not enough memory
< Not enough memory
< Not enough memory
< No error
References vlc_readdir_helper::i_dirs, input_item_CopyOptions(), input_item_NewExt(), input_item_node_AppendItem(), input_item_Release(), ITEM_TYPE_DIRECTORY, rdh_dir::p_node, vlc_readdir_helper::pp_dirs, rdh_dir::psz_path, TAB_APPEND, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by vlc_readdir_helper_additem().
typecmp()
static int typecmp (const void * key, const void * entry) static
References item_type_entry::psz_scheme.
Referenced by GuessType().
vlc_readdir_helper_additem()
int vlc_readdir_helper_additem (struct vlc_readdir_helper * p_rdh, const char * psz_uri, const char * psz_flatpath, const char * psz_filename, int i_type, int i_net)
Add a new input_item_t entry to the node of the vlc_readdir_helper struct.
Parameters
p_rdh previously inited vlc_readdir_helper struct
psz_uri uri of the new item
psz_flatpath flattened path of the new item. If not NULL, this function will create an input item for each sub folders (separated by '/') of psz_flatpath (so, this will un-flatten the folder hierarchy). Either psz_flatpath or psz_filename must be valid.
psz_filename file name of the new item. If NULL, the file part of path will be used as a filename. Either psz_flatpath or psz_filename must be valid.
i_type see input_item_type_e
i_net see input_item_net_type
< Not enough memory
< Not enough memory
< No error
< No error
< Not enough memory
< Not enough memory
< No error
References vlc_readdir_helper::b_flatten, vlc_readdir_helper::i_slaves, vlc_readdir_helper::i_sub_autodetect_fuzzy, i_type, input_item_CopyOptions(), input_item_NewExt(), input_item_node_AppendItem(), input_item_Release(), input_item_slave_GetType(), input_item_slave_New(), input_item_node_t::p_item, rdh_slave::p_node, vlc_readdir_helper::p_node, rdh_slave::p_slave, vlc_readdir_helper::pp_slaves, rdh_slave::psz_filename, rdh_file_is_ignored(), rdh_unflatten(), SLAVE_PRIORITY_MATCH_NONE, strdup(), TAB_APPEND, VLC_ENOMEM, and VLC_SUCCESS.
vlc_readdir_helper_finish()
void vlc_readdir_helper_finish (struct vlc_readdir_helper * p_rdh, bool b_success)
Finish adding items to the node.
Parameters
b_success if true, items of the node will be sorted.
References vlc_readdir_helper::i_dirs, vlc_readdir_helper::i_slaves, input_item_slave_Delete, vlc_readdir_helper::p_node, rdh_slave::p_slave, vlc_readdir_helper::pp_dirs, vlc_readdir_helper::pp_slaves, rdh_slave::psz_filename, vlc_readdir_helper::psz_ignored_exts, rdh_attach_slaves(), rdh_sort(), and TAB_CLEAN.
vlc_readdir_helper_init()
void vlc_readdir_helper_init (struct vlc_readdir_helper * p_rdh, vlc_object_t * p_obj, input_item_node_t * p_node)
Init a vlc_readdir_helper struct.
Parameters
p_rdh need to be cleaned with vlc_readdir_helper_finish()
p_node node that will be used to add items
References vlc_readdir_helper::b_flatten, vlc_readdir_helper::b_show_hiddenfiles, vlc_readdir_helper::i_dirs, vlc_readdir_helper::i_slaves, vlc_readdir_helper::i_sub_autodetect_fuzzy, input_item_ApplyOptions(), input_item_node_t::p_item, rdh_dir::p_node, vlc_readdir_helper::p_node, vlc_readdir_helper::pp_dirs, vlc_readdir_helper::pp_slaves, vlc_readdir_helper::psz_ignored_exts, TAB_INIT, var_InheritBool, var_InheritInteger, var_InheritString, vlc_object_create, and vlc_object_release.