VLC: src/misc/interrupt.h File Reference
interrupt.h File Reference
Data Structures
struct vlc_interrupt
Functions
void vlc_interrupt_init (vlc_interrupt_t *)
Initializes an interruption context.
void vlc_interrupt_deinit (vlc_interrupt_t *)
Deinitializes an interruption context.
Function Documentation
vlc_interrupt_deinit()
void vlc_interrupt_deinit (vlc_interrupt_t * ctx)
Deinitializes an interruption context.
The context shall no longer be used by any thread.
References vlc_interrupt::callback, vlc_interrupt::lock, and vlc_mutex_destroy().
Referenced by CloseWorker(), input_Close(), StartWorker(), and vlc_interrupt_destroy().