VLC: src/video_output/interlacing.c File Reference
interlacing.c File Reference
Functions
static bool DeinterlaceIsModeValid (const char *mode)
static int DeinterlaceCallback (vlc_object_t *object, char const *cmd, vlc_value_t oldval, vlc_value_t newval, void *data)
void vout_InitInterlacingSupport (vout_thread_t *vout, bool is_interlaced)
void vout_ReinitInterlacingSupport (vout_thread_t *vout)
void vout_SetInterlacingState (vout_thread_t *vout, bool is_interlaced)
Variables
static const char deinterlace_modes [][9]
Function Documentation
DeinterlaceCallback()
static int DeinterlaceCallback (vlc_object_t * object, char const * cmd, vlc_value_t oldval, vlc_value_t newval, void * data) static
< Unspecified error
< No error
References vout_thread_sys_t::control, DeinterlaceIsModeValid(), msg_Dbg, vout_thread_t::p, var_CreateGetString, var_GetBool, var_GetInteger, var_GetString, var_SetString, VLC_EGENERIC, VLC_SUCCESS, VLC_UNUSED, VOUT_CONTROL_CHANGE_INTERLACE, and vout_control_PushBool().
Referenced by vout_InitInterlacingSupport().
DeinterlaceIsModeValid()
static bool DeinterlaceIsModeValid (const char * mode) static
References ARRAY_SIZE, and deinterlace_modes.
Referenced by DeinterlaceCallback(), and vout_InitInterlacingSupport().
vout_InitInterlacingSupport()
void vout_InitInterlacingSupport (vout_thread_t * vout, bool is_interlaced)
References _, vlc_value_t::b_bool, config_FindConfig(), vout_thread_sys_t::date, DeinterlaceCallback(), DeinterlaceIsModeValid(), vout_thread_sys_t::filter, vout_thread_sys_t::has_deint, module_config_t::i, vlc_value_t::i_int, vout_thread_sys_t::interlacing, vout_thread_sys_t::is_interlaced, likely, module_config_t::list, module_config_t::list_count, module_config_t::list_text, mdate(), msg_Dbg, module_config_t::orig, vout_thread_t::p, module_config_t::psz, module_value_t::psz, vlc_value_t::psz_string, var_AddCallback, var_Change, var_Create, var_CreateGetNonEmptyString, var_GetInteger, var_GetNonEmptyString, var_SetInteger, vlc_gettext(), VLC_VAR_ADDCHOICE, VLC_VAR_BOOL, VLC_VAR_CLEARCHOICES, VLC_VAR_DOINHERIT, VLC_VAR_INTEGER, VLC_VAR_SETTEXT, VLC_VAR_SETVALUE, and VLC_VAR_STRING.
Referenced by VoutCreate().
vout_ReinitInterlacingSupport()
void vout_ReinitInterlacingSupport (vout_thread_t * vout)
References vout_thread_sys_t::interlacing, vout_thread_sys_t::is_interlaced, vout_thread_t::p, and var_SetBool.
Referenced by ThreadReinit().
vout_SetInterlacingState()
void vout_SetInterlacingState (vout_thread_t * vout, bool is_interlaced)
References vout_thread_sys_t::date, vout_thread_sys_t::interlacing, vout_thread_sys_t::is_interlaced, mdate(), msg_Dbg, vout_thread_t::p, and var_SetBool.
Referenced by Thread().
Variable Documentation
deinterlace_modes
const char deinterlace_modes[][9] static
Initial value:
= {
    "auto",
    "discard",
    "blend",
    "mean",
    "bob",
    "linear",
    "x",
    "yadif",
    "yadif2x",
    "phosphor",
    "ivtc",
}
Referenced by DeinterlaceIsModeValid().