VLC: src/interface/interface.c File Reference
interface.c File Reference
This file contains functions related to interface management.
Functions
static int AddIntfCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
int intf_Create (playlist_t *playlist, const char *chain)
Create and start an interface.
static playlist_t * intf_GetPlaylist (libvlc_int_t *libvlc)
Creates the playlist if necessary, and return a pointer to it.
int intf_InsertItem (libvlc_int_t *libvlc, const char *mrl, unsigned optc, const char *const *optv, unsigned flags)
Inserts an item in the playlist.
void libvlc_InternalPlay (libvlc_int_t *libvlc)
int libvlc_InternalAddIntf (libvlc_int_t *libvlc, const char *name)
Starts an interface plugin.
void intf_DestroyAll (libvlc_int_t *libvlc)
Stops and destroys all interfaces, then the playlist.
Variables
static vlc_mutex_t lock = PTHREAD_MUTEX_INITIALIZER
Detailed Description
This file contains functions related to interface management.
Function Documentation
AddIntfCallback()
static int AddIntfCallback (vlc_object_t * obj, char const * var, vlc_value_t old, vlc_value_t cur, void * data) static
References intf_Create(), msg_Err, and vlc_value_t::psz_string.
Referenced by intf_Create(), and intf_DestroyAll().
intf_DestroyAll()
void intf_DestroyAll (libvlc_int_t * libvlc)
Stops and destroys all interfaces, then the playlist.
Warning
FIXME
Parameters
libvlc the LibVLC instance
References AddIntfCallback(), config_ChainDestroy(), libvlc_priv(), lock, module_unneed, intf_thread_t::p_cfg, intf_thread_t::p_module, intf_thread_t::p_next, pl_priv, libvlc_priv_t::playlist, playlist_Destroy(), var_DelCallback, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_release.
Referenced by libvlc_InternalCleanup().
intf_GetPlaylist()
static playlist_t * intf_GetPlaylist (libvlc_int_t * libvlc) static
Creates the playlist if necessary, and return a pointer to it.
Note
The playlist is not reference-counted. So the pointer is only valid until intf_DestroyAll() destroys interfaces.
References libvlc_priv(), lock, libvlc_priv_t::playlist, playlist_Create(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_OBJECT.
Referenced by intf_InsertItem(), and libvlc_InternalAddIntf().
intf_InsertItem()
int intf_InsertItem (libvlc_int_t * libvlc, const char * mrl, unsigned optc, const char *const * optv, unsigned flags)
Inserts an item in the playlist.
This function is used during initialization. Unlike playlist_Add() and variants, it inserts an item to the beginning of the playlist. That is meant to compensate for the reverse parsing order of the command line.
Note
This function may not be called at the same time as intf_DestroyAll().
< No error
References input_item_AddOptions(), input_item_New, input_item_Release(), intf_GetPlaylist(), playlist_t::p_playing, playlist_Lock(), playlist_NodeAddInput(), playlist_Unlock(), unlikely, and VLC_SUCCESS.
Referenced by GetFilenames(), and libvlc_InternalInit().
libvlc_InternalAddIntf()
int libvlc_InternalAddIntf (libvlc_int_t * libvlc, const char * name)
Starts an interface plugin.
< Not enough memory
< No error
References _, intf_Create(), intf_GetPlaylist(), msg_Err, msg_Info, name, unlikely, var_InheritString, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by libvlc_InternalInit(), system_Configure(), and system_ConfigureDbus().
libvlc_InternalPlay()
void libvlc_InternalPlay (libvlc_int_t * libvlc)
References libvlc_priv(), lock, libvlc_priv_t::playlist, playlist_Control(), PLAYLIST_PLAY, var_GetBool, vlc_mutex_lock(), and vlc_mutex_unlock().
Variable Documentation
lock
vlc_mutex_t lock = PTHREAD_MUTEX_INITIALIZER static
Referenced by config_GetLibDir(), config_SaveConfigFile(), intf_Create(), intf_DestroyAll(), intf_GetPlaylist(), libvlc_InternalPlay(), playlist_AssertLocked(), playlist_Lock(), playlist_Unlock(), vlc_cleanup_lock(), vlc_global_mutex(), vlc_rwlock_destroy(), vlc_rwlock_init(), vlc_rwlock_rdlock(), vlc_rwlock_unlock(), vlc_rwlock_wrlock(), and vlc_threads_setup().