VLC: src/text/iso_lang.c File Reference
iso_lang.c File Reference
Functions
const iso639_lang_t * GetLang_1 (const char *psz_code)
const iso639_lang_t * GetLang_2T (const char *psz_code)
const iso639_lang_t * GetLang_2B (const char *psz_code)
Variables
static const iso639_lang_t unknown_language
Function Documentation
GetLang_1()
const iso639_lang_t * GetLang_1 (const char * psz_code)
References p_languages, iso639_lang_t::psz_eng_name, iso639_lang_t::psz_iso639_1, and unknown_language.
Referenced by LanguageGetName().
GetLang_2B()
const iso639_lang_t * GetLang_2B (const char * psz_code)
References p_languages, iso639_lang_t::psz_eng_name, iso639_lang_t::psz_iso639_2B, and unknown_language.
Referenced by LanguageGetName().
GetLang_2T()
const iso639_lang_t * GetLang_2T (const char * psz_code)
References p_languages, iso639_lang_t::psz_eng_name, iso639_lang_t::psz_iso639_2T, and unknown_language.
Referenced by LanguageGetName().
Variable Documentation
unknown_language
const iso639_lang_t unknown_language static
Initial value:
=
    { "Unknown", "??", "???", "???" }
Referenced by GetLang_1(), GetLang_2B(), and GetLang_2T().