VLC: src/input/item.h File Reference
item.h File Reference
Data Structures
struct input_item_owner
Macros
#define item_owner(item) ((struct input_item_owner *)(item))
Typedefs
typedef struct input_item_owner input_item_owner_t
Functions
void input_item_SetErrorWhenReading (input_item_t *p_i, bool b_error)
void input_item_UpdateTracksInfo (input_item_t *item, const es_format_t *fmt)
bool input_item_ShouldPreparseSubItems (input_item_t *p_i)
Macro Definition Documentation
item_owner
#define item_owner (item) ((struct input_item_owner *)(item))
Referenced by input_item_Hold(), and input_item_Release().
Typedef Documentation
input_item_owner_t
typedef struct input_item_owner input_item_owner_t
Function Documentation
input_item_SetErrorWhenReading()
void input_item_SetErrorWhenReading (input_item_t * p_i, bool b_error)
References input_item_t::b_error_when_reading, input_item_t::event_manager, input_item_t::lock, vlc_event_send(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_ChangeState().
input_item_ShouldPreparseSubItems()
bool input_item_ShouldPreparseSubItems (input_item_t * p_i)
References input_item_t::i_preparse_depth, input_item_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Preparse().
input_item_UpdateTracksInfo()
void input_item_UpdateTracksInfo (input_item_t * item, const es_format_t * fmt)
References input_item_t::es, es_format_Clean(), es_format_Copy(), input_item_t::i_es, es_format_t::i_id, input_item_t::lock, TAB_APPEND, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by EsOutUpdateInfo().