VLC: src/misc/keystore.c File Reference
keystore.c File Reference
Functions
static vlc_keystore * keystore_create (vlc_object_t *p_parent, const char *psz_name)
vlc_keystore * vlc_keystore_create (vlc_object_t *p_parent)
Create a keystore object.
void vlc_keystore_release (vlc_keystore *p_keystore)
Release a keystore object.
int vlc_keystore_store (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX], const uint8_t *p_secret, ssize_t i_secret_len, const char *psz_label)
Store a secret associated with a set of key/values.
unsigned int vlc_keystore_find (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX], vlc_keystore_entry **pp_entries)
Find all entries that match a set of key/values.
unsigned int vlc_keystore_remove (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX])
Remove all entries that match a set of key/values.
void vlc_keystore_release_entries (vlc_keystore_entry *p_entries, unsigned int i_count)
Release the list of entries returned by vlc_keystore_find()
int libvlc_InternalKeystoreInit (libvlc_int_t *p_libvlc)
void libvlc_InternalKeystoreClean (libvlc_int_t *p_libvlc)
static vlc_keystore * get_memory_keystore (vlc_object_t *p_obj)
static vlc_keystore_entry * find_closest_path (vlc_keystore_entry *p_entries, unsigned i_count, const char *psz_path)
static bool is_credential_valid (vlc_credential *p_credential)
static bool is_url_valid (const vlc_url_t *p_url)
static bool protocol_set_port (const vlc_url_t *p_url, char *psz_port)
static bool protocol_is_smb (const vlc_url_t *p_url)
static bool protocol_store_path (const vlc_url_t *p_url)
static void smb_split_domain (vlc_credential *p_credential)
static void credential_find_keystore (vlc_credential *p_credential, vlc_keystore *p_keystore)
void vlc_credential_init (vlc_credential *p_credential, const vlc_url_t *p_url)
Init a credential struct.
void vlc_credential_clean (vlc_credential *p_credential)
Clean a credential struct.
bool vlc_credential_get (vlc_credential *p_credential, vlc_object_t *p_parent, const char *psz_option_username, const char *psz_option_password, const char *psz_dialog_title, const char *psz_dialog_fmt,...)
Get a username/password couple.
bool vlc_credential_store (vlc_credential *p_credential, vlc_object_t *p_parent)
Store the last dialog credential returned by vlc_credential_get()
Variables
struct {
const char * psz_protocol
uint16_t i_port
} protocol_default_ports []
Function Documentation
credential_find_keystore()
static void credential_find_keystore (vlc_credential * p_credential, vlc_keystore * p_keystore) static
References vlc_credential::b_from_keystore, find_closest_path(), vlc_credential::i_entries_count, vlc_keystore_entry::i_secret_len, KEY_AUTHTYPE, KEY_MAX, KEY_PORT, KEY_PROTOCOL, KEY_REALM, KEY_SERVER, KEY_USER, vlc_credential::p_entries, vlc_keystore_entry::p_secret, vlc_credential::p_url, vlc_keystore_entry::ppsz_values, protocol_set_port(), protocol_store_path(), vlc_credential::psz_authtype, vlc_url_t::psz_host, vlc_credential::psz_password, vlc_url_t::psz_path, vlc_url_t::psz_protocol, vlc_credential::psz_realm, vlc_credential::psz_username, vlc_keystore_find(), and vlc_keystore_release_entries().
Referenced by vlc_credential_get().
find_closest_path()
static vlc_keystore_entry * find_closest_path (vlc_keystore_entry * p_entries, unsigned i_count, const char * psz_path) static
References KEY_PATH, vlc_keystore_entry::ppsz_values, and vlc_uri_decode_duplicate().
Referenced by credential_find_keystore().
get_memory_keystore()
static vlc_keystore * get_memory_keystore (vlc_object_t * p_obj) static
References vlc_common_members::libvlc, libvlc_priv(), vlc_object_t::obj, and libvlc_priv_t::p_memory_keystore.
Referenced by vlc_credential_get(), and vlc_credential_store().
is_credential_valid()
static bool is_credential_valid (vlc_credential * p_credential) static
References vlc_credential::psz_password, and vlc_credential::psz_username.
Referenced by vlc_credential_get(), and vlc_credential_store().
is_url_valid()
static bool is_url_valid (const vlc_url_t * p_url) static
References vlc_url_t::psz_host, and vlc_url_t::psz_protocol.
Referenced by vlc_credential_get().
keystore_create()
static vlc_keystore * keystore_create (vlc_object_t * p_parent, const char * psz_name) static
References module_need, vlc_keystore::p_module, vlc_keystore::pf_find, vlc_keystore::pf_remove, vlc_keystore::pf_store, psz_name, unlikely, vlc_custom_create, and vlc_object_release.
Referenced by libvlc_InternalKeystoreInit(), and vlc_keystore_create().
libvlc_InternalKeystoreClean()
void libvlc_InternalKeystoreClean (libvlc_int_t * p_libvlc)
References libvlc_priv(), libvlc_priv_t::p_memory_keystore, and vlc_keystore_release().
Referenced by libvlc_InternalCleanup().
libvlc_InternalKeystoreInit()
int libvlc_InternalKeystoreInit (libvlc_int_t * p_libvlc)
< No error
< Unspecified error
References keystore_create(), libvlc_priv(), libvlc_priv_t::p_memory_keystore, VLC_EGENERIC, VLC_OBJECT, and VLC_SUCCESS.
Referenced by libvlc_InternalInit().
protocol_is_smb()
static bool protocol_is_smb (const vlc_url_t * p_url) static
References vlc_url_t::psz_protocol, and strcasecmp().
Referenced by protocol_store_path(), vlc_credential_get(), and vlc_credential_store().
protocol_set_port()
static bool protocol_set_port (const vlc_url_t * p_url, char * psz_port) static
References i_port, vlc_url_t::i_port, protocol_default_ports, vlc_url_t::psz_protocol, and strcasecmp().
Referenced by credential_find_keystore(), and vlc_credential_store().
protocol_store_path()
static bool protocol_store_path (const vlc_url_t * p_url) static
References protocol_is_smb(), vlc_url_t::psz_path, vlc_url_t::psz_protocol, and strcasecmp().
Referenced by credential_find_keystore(), and vlc_credential_store().
smb_split_domain()
static void smb_split_domain (vlc_credential * p_credential) static
References vlc_credential::psz_realm, vlc_credential::psz_split_domain, vlc_credential::psz_username, and strndup().
Referenced by vlc_credential_get().
Variable Documentation
i_port
uint16_t i_port
Referenced by net_Connect(), net_ConnectDgram(), net_Listen(), protocol_set_port(), SocksHandshakeTCP(), and vlc_keystore_store().
[struct]
struct { ... } protocol_default_ports[]
Initial value:
= {
    { "rtsp", 80 },
    { "http", 80 },
    { "https", 443 },
    { "ftp", 21 },
    { "sftp", 22 },
    { "smb", 445 },
}
Referenced by protocol_set_port().
psz_protocol
const char* psz_protocol