VLC: src/libvlc.c File Reference
libvlc.c File Reference
This file contains functions to create and destroy libvlc instances.
Functions
static void GetFilenames (libvlc_int_t *, unsigned, const char *const [])
libvlc_int_t * libvlc_InternalCreate (void)
Allocate a blank libvlc instance, also setting the exit handler.
int libvlc_InternalInit (libvlc_int_t *p_libvlc, int i_argc, const char *ppsz_argv[])
Initialize a libvlc instance This function initializes a previously allocated libvlc instance:
void libvlc_InternalCleanup (libvlc_int_t *p_libvlc)
Cleanup a libvlc instance.
void libvlc_InternalDestroy (libvlc_int_t *p_libvlc)
Destroy everything.
int vlc_MetadataRequest (libvlc_int_t *libvlc, input_item_t *item, input_item_meta_request_option_t i_options, int timeout, void *id)
int libvlc_MetadataRequest (libvlc_int_t *libvlc, input_item_t *item, input_item_meta_request_option_t i_options, int timeout, void *id)
Requests extraction of the meta data for an input item (a.k.a.
int libvlc_ArtRequest (libvlc_int_t *libvlc, input_item_t *item, input_item_meta_request_option_t i_options)
Requests retrieving/downloading art for an input item.
void libvlc_MetadataCancel (libvlc_int_t *libvlc, void *id)
Cancels extraction of the meta data for an input item.
Detailed Description
This file contains functions to create and destroy libvlc instances.
Function Documentation
GetFilenames()
static void GetFilenames (libvlc_int_t * p_vlc, unsigned n, const char * const args[]) static
References intf_InsertItem(), msg_Warn, VLC_INPUT_OPTION_TRUSTED, and vlc_path2uri().
Referenced by libvlc_InternalInit().
libvlc_ArtRequest()
int libvlc_ArtRequest (libvlc_int_t * libvlc, input_item_t * item, input_item_meta_request_option_t i_options)
Requests retrieving/downloading art for an input item.
The retrieval is performed asynchronously.
< Not enough memory
< No error
References libvlc_priv(), libvlc_priv_t::parser, playlist_preparser_fetcher_Push(), unlikely, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by PlayItem().
libvlc_InternalCleanup()
void libvlc_InternalCleanup (libvlc_int_t * p_libvlc)
Cleanup a libvlc instance.
The instance is not completely deallocated
Parameters
p_libvlc the instance to clean
References config_AutoSaveConfigFile(), intf_DestroyAll(), libvlc_InternalActionsClean(), libvlc_InternalDialogClean(), libvlc_InternalKeystoreClean(), libvlc_priv(), module_EndBank(), msg_Dbg, msg_Warn, libvlc_priv_t::p_vlm, libvlc_priv_t::parser, playlist_preparser_Deactivate(), playlist_preparser_Delete(), system_End(), var_InheritBool, var_InheritString, vlc_LogDeinit(), VLC_OBJECT, vlc_strerror_c(), and vlm_Delete().
Referenced by libvlc_InternalInit().
libvlc_InternalCreate()
libvlc_int_t * libvlc_InternalCreate (void)
Allocate a blank libvlc instance, also setting the exit handler.
Vlc's threading system must have been initialized first
References libvlc_priv_t::exit, libvlc_priv(), libvlc_priv_t::p_vlm, libvlc_priv_t::playlist, vlc_custom_create, and vlc_ExitInit().
libvlc_InternalDestroy()
void libvlc_InternalDestroy (libvlc_int_t * p_libvlc)
Destroy everything.
This function requests the running threads to finish, waits for their termination, and destroys their structure. It stops the thread systems: no instance can run after this has run
Parameters
p_libvlc the instance to destroy
References libvlc_priv_t::exit, libvlc_priv(), vlc_ExitDestroy(), vlc_internals, and vlc_object_release.
libvlc_InternalInit()
int libvlc_InternalInit (libvlc_int_t * p_libvlc, int i_argc, const char * ppsz_argv[])
Initialize a libvlc instance This function initializes a previously allocated libvlc instance:
CPU detection
gettext initialization
message queue, module bank and playlist initialization
configuration and commandline parsing
< Unspecified error
< Unspecified error
< Module not found
< Not enough memory
< No error
< No error
< No error
< No error
References _, asprintf(), libvlc_priv_t::b_stats, config_LoadCmdLine, config_LoadConfigFile, config_PrintHelp(), config_SaveConfigFile, GetFilenames(), getpid(), intf_InsertItem(), libvlc_InternalActionsInit(), libvlc_InternalAddIntf(), libvlc_InternalCleanup(), libvlc_InternalDialogInit(), libvlc_InternalKeystoreInit(), libvlc_priv(), module_EndBank(), module_InitBank(), module_LoadPlugins, msg_Dbg, msg_Err, msg_Warn, libvlc_priv_t::p_vlm, libvlc_priv_t::parser, playlist_preparser_New(), strdup(), system_Configure(), system_Init(), var_Create, var_CreateGetNonEmptyString, var_InheritBool, var_InheritString, var_SetBool, var_SetString, vlc_bindtextdomain(), vlc_CPU_dump(), VLC_EGENERIC, VLC_ENOMEM, VLC_ENOMOD, vlc_fopen(), vlc_LogInit(), vlc_LogPreinit(), VLC_OBJECT, vlc_strerror_c(), VLC_SUCCESS, vlc_threads_setup(), VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_INTEGER, VLC_VAR_STRING, VLC_VAR_VOID, and vlm_New.
libvlc_MetadataCancel()
void libvlc_MetadataCancel (libvlc_int_t * libvlc, void * id)
Cancels extraction of the meta data for an input item.
This does nothing if the input item is already processed or if it was not added with libvlc_MetadataRequest()
References libvlc_priv(), libvlc_priv_t::parser, playlist_preparser_Cancel(), and unlikely.
Referenced by PlayItem().
libvlc_MetadataRequest()
int libvlc_MetadataRequest (libvlc_int_t * libvlc, input_item_t * item, input_item_meta_request_option_t i_options, int timeout, void * id)
Requests extraction of the meta data for an input item (a.k.a.
preparsing). The actual extraction is asynchronous. It can be cancelled with libvlc_MetadataCancel()
< Not enough memory
< No error
References input_item_t::b_preparse_interact, input_item_t::i_preparse_depth, libvlc_priv(), input_item_t::lock, META_REQUEST_OPTION_DO_INTERACT, libvlc_priv_t::parser, playlist_preparser_Push(), unlikely, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
vlc_MetadataRequest()
int vlc_MetadataRequest (libvlc_int_t * libvlc, input_item_t * item, input_item_meta_request_option_t i_options, int timeout, void * id)
< Not enough memory
< No error
References input_item_t::b_preparse_interact, libvlc_priv(), input_item_t::lock, META_REQUEST_OPTION_DO_INTERACT, libvlc_priv_t::parser, playlist_preparser_Push(), unlikely, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by playlist_Preparse().