VLC: src/linux/dirs.c File Reference
dirs.c File Reference
Functions
char * config_GetLibDir (void)
char * config_GetDataDir (void)
Function Documentation
config_GetDataDir()
char * config_GetDataDir (void)
References asprintf(), config_GetLibDir(), getenv(), p, strdup(), and unlikely.
config_GetLibDir()
char * config_GetLibDir (void)
References asprintf(), config_GetLibDir(), getline(), likely, lock, strdup(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_STATIC_MUTEX.