VLC: src/linux/thread.c File Reference
thread.c File Reference
Macros
#define FUTEX_WAKE_PRIVATE FUTEX_WAKE
#define FUTEX_WAIT_PRIVATE FUTEX_WAIT
Functions
unsigned long vlc_thread_id (void)
Thread identifier.
static int sys_futex (void *addr, int op, unsigned val, const struct timespec *to, void *addr2, int val3)
static int vlc_futex_wake (void *addr, int nr)
static int vlc_futex_wait (void *addr, unsigned val, const struct timespec *to)
void vlc_addr_signal (void *addr)
Wakes up one thread on an address.
void vlc_addr_broadcast (void *addr)
Wakes up all thread on an address.
void vlc_addr_wait (void *addr, unsigned val)
Waits on an address.
bool vlc_addr_timedwait (void *addr, unsigned val, mtime_t delay)
Waits on an address with a time-out.
Macro Definition Documentation
FUTEX_WAIT_PRIVATE
#define FUTEX_WAIT_PRIVATE FUTEX_WAIT
Referenced by vlc_futex_wait().
FUTEX_WAKE_PRIVATE
#define FUTEX_WAKE_PRIVATE FUTEX_WAKE
Referenced by vlc_futex_wake().
Function Documentation
sys_futex()
static int sys_futex (void * addr, int op, unsigned val, const struct timespec * to, void * addr2, int val3) static
Referenced by vlc_futex_wait(), and vlc_futex_wake().
vlc_futex_wait()
static int vlc_futex_wait (void * addr, unsigned val, const struct timespec * to) static
References FUTEX_WAIT_PRIVATE, and sys_futex().
Referenced by vlc_addr_timedwait(), and vlc_addr_wait().
vlc_futex_wake()
static int vlc_futex_wake (void * addr, int nr) static
References FUTEX_WAKE_PRIVATE, and sys_futex().
Referenced by vlc_addr_broadcast(), and vlc_addr_signal().