VLC: src/misc/md5.c File Reference
md5.c File Reference
Macros
#define rol(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define FF(b, c, d) (d ^ (b & (c ^ d)))
#define FG(b, c, d) FF (d, b, c)
#define FH(b, c, d) (b ^ c ^ d)
#define FI(b, c, d) (c ^ (b | ~d))
#define OP(a, b, c, d, s, T)
#define OP(f, a, b, c, d, k, s, T)
#define X(a) do { *(u32*)p = (*hd).a ; p += 4; } while(0)
Typedefs
typedef uint32_t u32
typedef uint8_t byte
typedef struct md5_s MD5_CONTEXT
Functions
static void md5_init (void *context)
static void transform (MD5_CONTEXT *ctx, const unsigned char *data)
static void md5_write (void *context, const void *inbuf_arg, size_t inlen)
static void md5_final (void *context)
void InitMD5 (struct md5_s *h)
void AddMD5 (struct md5_s *restrict h, const void *data, size_t len)
void EndMD5 (struct md5_s *h)
Macro Definition Documentation
FF
#define FF (b, c, d) (d ^ (b & (c ^ d)))
FG
#define FG (b, c, d) FF (d, b, c)
Referenced by transform().
FH
#define FH (b, c, d) (b ^ c ^ d)
Referenced by transform().
FI
#define FI (b, c, d) (c ^ (b | ~d))
Referenced by transform().
OP [1/2]
#define OP (a, b, c, d, s, T)
Value:
  do                           \
    {                      \
      a += FF (b, c, d) + (*cwp++) + T;    \
      a = rol(a, s);               \
      a += b;                  \
    }                      \
  while (0)
Referenced by transform().
OP [2/2]
#define OP (f, a, b, c, d, k, s, T)
Value:
    do                                    \
      {                                   \
    a += f (b, c, d) + correct_words[k] + T;              \
    a = rol(a, s);                            \
    a += b;                               \
      }                                   \
    while (0)
rol
#define rol (x, n) (((x) << (n)) | ((x) >> (32-(n))))
X
#define X (a) do { *(u32*)p = (*hd).a ; p += 4; } while(0)
Referenced by md5_final().
Typedef Documentation
byte
typedef uint8_t byte
MD5_CONTEXT
typedef struct md5_s MD5_CONTEXT
u32
typedef uint32_t u32
Function Documentation
AddMD5()
void AddMD5 (struct md5_s *restrict h, const void * data, size_t len)
References md5_write().
Referenced by ArtCacheGetDirPath(), AuthDigest(), GenerateCnonce(), and vlc_rand_bytes().
EndMD5()
void EndMD5 (struct md5_s * h)
References md5_final().
Referenced by ArtCacheGetDirPath(), AuthDigest(), GenerateCnonce(), and vlc_rand_bytes().
InitMD5()
void InitMD5 (struct md5_s * h)
References md5_init().
Referenced by ArtCacheGetDirPath(), AuthDigest(), GenerateCnonce(), and vlc_rand_bytes().
md5_final()
static void md5_final (void * context) static
References A, B, md5_s::buf, md5_s::C, md5_s::count, md5_s::D, md5_write(), md5_s::nblocks, p, transform(), and X.
Referenced by EndMD5().
md5_init()
static void md5_init (void * context) static
References md5_s::A, md5_s::B, md5_s::C, md5_s::count, md5_s::D, and md5_s::nblocks.
Referenced by InitMD5().
md5_write()
static void md5_write (void * context, const void * inbuf_arg, size_t inlen) static
References md5_s::buf, md5_s::count, md5_write(), md5_s::nblocks, and transform().
Referenced by AddMD5(), md5_final(), and md5_write().
transform()
static void transform (MD5_CONTEXT * ctx, const unsigned char * data) static
References A, md5_s::A, B, md5_s::B, md5_s::C, md5_s::D, FG, FH, FI, and OP.
Referenced by md5_final(), md5_write(), transform_GetBasicOps(), transform_Inverse(), video_format_TransformBy(), video_format_TransformTo(), and vout_display_SendMouseMovedDisplayCoordinates().