VLC: src/misc/messages.c File Reference
messages.c File Reference
Data Structures
struct vlc_logger_t
struct vlc_log_early_t
struct vlc_logger_early_t
Typedefs
typedef struct vlc_log_early_t vlc_log_early_t
Functions
static void vlc_vaLogCallback (libvlc_int_t *vlc, int type, const vlc_log_t *item, const char *format, va_list ap)
static void vlc_LogCallback (libvlc_int_t *vlc, int type, const vlc_log_t *item, const char *format,...)
void vlc_vaLog (vlc_object_t *obj, int type, const char *module, const char *file, unsigned line, const char *func, const char *format, va_list args)
Emit a log message.
void vlc_Log (vlc_object_t *obj, int type, const char *module, const char *file, unsigned line, const char *func, const char *format,...)
Emit a log message.
static void vlc_vaLogEarly (void *d, int type, const vlc_log_t *item, const char *format, va_list ap)
static int vlc_LogEarlyOpen (vlc_logger_t *logger)
static void vlc_LogEarlyClose (vlc_logger_t *logger, void *d)
static void vlc_vaLogDiscard (void *d, int type, const vlc_log_t *item, const char *format, va_list ap)
static int vlc_logger_load (void *func, va_list ap)
static void vlc_logger_unload (void *func, va_list ap)
int vlc_LogPreinit (libvlc_int_t *vlc)
Performs preinitialization of the messages logging subsystem.
int vlc_LogInit (libvlc_int_t *vlc)
Initializes the messages logging subsystem and drain the early messages to the configured log.
void vlc_LogSet (libvlc_int_t *vlc, vlc_log_cb cb, void *opaque)
Sets the message logging callback.
void vlc_LogDeinit (libvlc_int_t *vlc)
Typedef Documentation
vlc_log_early_t
typedef struct vlc_log_early_t vlc_log_early_t
Function Documentation
vlc_LogCallback()
static void vlc_LogCallback (libvlc_int_t * vlc, int type, const vlc_log_t * item, const char * format, ...) static
References vlc_vaLogCallback().
Referenced by vlc_LogEarlyClose().
vlc_LogDeinit()
void vlc_LogDeinit (libvlc_int_t * vlc)
References libvlc_priv(), vlc_logger_t::lock, vlc_logger_t::log, libvlc_priv_t::logger, vlc_logger_t::module, vlc_logger_t::sys, unlikely, vlc_LogEarlyClose(), vlc_logger_unload(), vlc_module_unload, vlc_object_release, vlc_rwlock_destroy(), vlc_vaLogDiscard(), and vlc_vaLogEarly().
Referenced by libvlc_InternalCleanup().
vlc_LogEarlyClose()
static void vlc_LogEarlyClose (vlc_logger_t * logger, void * d) static
References vlc_logger_early_t::head, vlc_common_members::libvlc, vlc_logger_early_t::lock, vlc_log_early_t::next, vlc_logger_t::obj, vlc_LogCallback(), and vlc_mutex_destroy().
Referenced by vlc_LogDeinit(), and vlc_LogInit().
vlc_LogEarlyOpen()
static int vlc_LogEarlyOpen (vlc_logger_t * logger) static
References vlc_logger_early_t::head, vlc_logger_early_t::lock, vlc_logger_t::log, vlc_logger_t::sys, vlc_logger_early_t::tailp, unlikely, vlc_mutex_init(), and vlc_vaLogEarly().
Referenced by vlc_LogPreinit().
vlc_logger_load()
static int vlc_logger_load (void * func, va_list ap) static
< No error
< Unspecified error
References VLC_EGENERIC, VLC_OBJECT, and VLC_SUCCESS.
Referenced by vlc_LogInit().
vlc_logger_unload()
static void vlc_logger_unload (void * func, va_list ap) static
Referenced by vlc_LogDeinit(), and vlc_LogSet().
vlc_LogInit()
int vlc_LogInit (libvlc_int_t * vlc)
Initializes the messages logging subsystem and drain the early messages to the configured log.
Returns
0 on success, -1 on error.
References libvlc_priv(), vlc_logger_t::lock, vlc_logger_t::log, libvlc_priv_t::logger, vlc_logger_t::module, vlc_logger_t::sys, unlikely, vlc_LogEarlyClose(), vlc_logger_load(), vlc_module_load, vlc_rwlock_unlock(), vlc_rwlock_wrlock(), vlc_vaLogDiscard(), and vlc_vaLogEarly().
Referenced by libvlc_InternalInit().
vlc_LogPreinit()
int vlc_LogPreinit (libvlc_int_t * vlc)
Performs preinitialization of the messages logging subsystem.
Early log messages will be stored in memory until the subsystem is fully initialized with vlc_LogInit(). This enables logging before the configuration and modules bank are ready.
Returns
0 on success, -1 on error.
References libvlc_priv(), vlc_logger_t::lock, vlc_logger_t::log, libvlc_priv_t::logger, msg_Dbg, psz_vlc_changeset, unlikely, vlc_custom_create, vlc_LogEarlyOpen(), vlc_rwlock_init(), and vlc_vaLogDiscard().
Referenced by libvlc_InternalInit().
vlc_vaLogCallback()
static void vlc_vaLogCallback (libvlc_int_t * vlc, int type, const vlc_log_t * item, const char * format, va_list ap) static
References libvlc_priv(), vlc_logger_t::lock, vlc_logger_t::log, libvlc_priv_t::logger, vlc_logger_t::sys, vlc_restorecancel(), vlc_rwlock_rdlock(), vlc_rwlock_unlock(), and vlc_savecancel().
Referenced by vlc_LogCallback(), and vlc_vaLog().
vlc_vaLogDiscard()
static void vlc_vaLogDiscard (void * d, int type, const vlc_log_t * item, const char * format, va_list ap) static
References vlc_log_early_t::type.
Referenced by vlc_LogDeinit(), vlc_LogInit(), vlc_LogPreinit(), and vlc_LogSet().
vlc_vaLogEarly()
static void vlc_vaLogEarly (void * d, int type, const vlc_log_t * item, const char * format, va_list ap) static
References vlc_log_t::file, vlc_log_t::func, vlc_log_t::i_object_id, vlc_log_t::line, vlc_logger_early_t::lock, vlc_log_early_t::meta, vlc_log_early_t::msg, vlc_log_early_t::next, vlc_log_t::psz_header, vlc_log_t::psz_module, vlc_log_t::psz_object_type, strdup(), vlc_logger_early_t::tailp, vlc_log_early_t::type, unlikely, vasprintf(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vlc_LogDeinit(), vlc_LogEarlyOpen(), and vlc_LogInit().