VLC: src/input/meta.c File Reference
meta.c File Reference
Data Structures
struct vlc_meta_t
Functions
const char * vlc_meta_TypeToLocalizedString (vlc_meta_type_t meta_type)
Returns a localizes string describing the meta.
vlc_meta_t * vlc_meta_New (void)
vlc_meta contructor.
static void vlc_meta_FreeExtraKey (void *p_data, void *p_obj)
void vlc_meta_Delete (vlc_meta_t *m)
void vlc_meta_Set (vlc_meta_t *p_meta, vlc_meta_type_t meta_type, const char *psz_val)
vlc_meta has two kinds of meta, the one in a table, and the one in a dictionary.
const char * vlc_meta_Get (const vlc_meta_t *p_meta, vlc_meta_type_t meta_type)
void vlc_meta_AddExtra (vlc_meta_t *m, const char *psz_name, const char *psz_value)
const char * vlc_meta_GetExtra (const vlc_meta_t *m, const char *psz_name)
unsigned vlc_meta_GetExtraCount (const vlc_meta_t *m)
char ** vlc_meta_CopyExtraNames (const vlc_meta_t *m)
Allocate a copy of all extra meta names and a table with it.
int vlc_meta_GetStatus (vlc_meta_t *m)
vlc_meta status (see vlc_meta_status_e)
void vlc_meta_SetStatus (vlc_meta_t *m, int status)
void vlc_meta_Merge (vlc_meta_t *dst, const vlc_meta_t *src)
Merging meta.
void input_ExtractAttachmentAndCacheArt (input_thread_t *p_input, const char *name)
int input_item_WriteMeta (vlc_object_t *obj, input_item_t *p_item)
void vlc_audio_replay_gain_MergeFromMeta (audio_replay_gain_t *p_dst, const vlc_meta_t *p_meta)
Function Documentation
input_ExtractAttachmentAndCacheArt()
void input_ExtractAttachmentAndCacheArt (input_thread_t * p_input, const char * name)
< No error
References input_thread_private_t::attachment, input_thread_private_t::i_attachment, input_attachment_t::i_data, input_item_IsArtFetched(), input_priv(), likely, input_item_t::lock, msg_Warn, name, input_attachment_t::p_data, input_thread_private_t::p_item, playlist_FindArtInCache(), playlist_SaveArt(), input_attachment_t::psz_mime, input_attachment_t::psz_name, vlc_input_attachment_Delete(), vlc_input_attachment_Duplicate(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, and VLC_SUCCESS.
Referenced by EsOutMeta().
input_item_WriteMeta()
int input_item_WriteMeta (vlc_object_t * obj, input_item_t * p_item)
< Not enough memory
< No error
< Unspecified error
References input_item_t::i_type, input_item_GetURI(), ITEM_TYPE_FILE, input_item_t::lock, module_need, module_unneed, msg_Err, meta_export_t::p_item, meta_export_t::psz_file, vlc_custom_create, VLC_EGENERIC, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_object_release, VLC_SUCCESS, and vlc_uri2path().
vlc_audio_replay_gain_MergeFromMeta()
void vlc_audio_replay_gain_MergeFromMeta (audio_replay_gain_t * p_dst, const vlc_meta_t * p_meta)
References AUDIO_REPLAY_GAIN_ALBUM, AUDIO_REPLAY_GAIN_TRACK, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pb_peak, audio_replay_gain_t::pf_gain, audio_replay_gain_t::pf_peak, psz_value, us_atof(), and vlc_meta_GetExtra().
Referenced by EsOutAddSlave().
vlc_meta_AddExtra()
void vlc_meta_AddExtra (vlc_meta_t * m, const char * psz_name, const char * psz_value)
References vlc_meta_t::extra_tags, kVLCDictionaryNotFound, psz_name, psz_value, strdup(), vlc_dictionary_insert(), vlc_dictionary_remove_value_for_key(), vlc_dictionary_value_for_key(), and vlc_meta_FreeExtraKey().
vlc_meta_CopyExtraNames()
char ** vlc_meta_CopyExtraNames (const vlc_meta_t * m)
Allocate a copy of all extra meta names and a table with it.
Be sure to free both the returned pointers and its name.
References vlc_meta_t::extra_tags, and vlc_dictionary_all_keys().
Referenced by EsOutProgramMeta(), and EsOutUpdateInfo().
vlc_meta_Delete()
void vlc_meta_Delete (vlc_meta_t * m)
References vlc_meta_t::extra_tags, vlc_meta_t::ppsz_meta, vlc_dictionary_clear(), vlc_meta_FreeExtraKey(), and VLC_META_TYPE_COUNT.
Referenced by CmdCleanControl(), DecoderUpdateFormatLocked(), DeleteDecoder(), DeleteDecoder(), demux_PacketizerDestroy(), EsOutProgramDel(), EsOutProgramMeta(), EsOutSend(), EsOutTerminate(), fingerprint_request_Delete(), Init(), input_item_Release(), InputSourceMeta(), InputUpdateMeta(), and UnloadDecoder().
vlc_meta_FreeExtraKey()
static void vlc_meta_FreeExtraKey (void * p_data, void * p_obj) static
References VLC_UNUSED.
Referenced by vlc_meta_AddExtra(), vlc_meta_Delete(), and vlc_meta_Merge().
vlc_meta_Get()
const char * vlc_meta_Get (const vlc_meta_t * p_meta, vlc_meta_type_t meta_type)
References vlc_meta_t::ppsz_meta.
Referenced by ArtCachePath(), CheckArt(), CheckMeta(), CreateCacheKey(), EsOutMeta(), EsOutProgramEpg(), EsOutProgramGetMetaName(), EsOutProgramGetProgramName(), EsOutProgramMeta(), EsOutProgramSelect(), input_item_GetMeta(), input_item_GetTitleFbName(), input_item_MetaMatch(), and playlist_LiveSearchUpdateInternal().
vlc_meta_GetExtra()
const char * vlc_meta_GetExtra (const vlc_meta_t * m, const char * psz_name)
References vlc_meta_t::extra_tags, psz_name, and vlc_dictionary_value_for_key().
Referenced by EsOutProgramMeta(), EsOutUpdateInfo(), and vlc_audio_replay_gain_MergeFromMeta().
vlc_meta_GetExtraCount()
unsigned vlc_meta_GetExtraCount (const vlc_meta_t * m)
References vlc_meta_t::extra_tags, and vlc_dictionary_keys_count().
vlc_meta_GetStatus()
int vlc_meta_GetStatus (vlc_meta_t * m)
vlc_meta status (see vlc_meta_status_e)
References vlc_meta_t::i_status.
Referenced by input_item_IsArtFetched(), input_item_IsPreparsed(), input_item_SetArtFetched(), input_item_SetArtNotFound(), and input_item_SetPreparsed().
vlc_meta_Merge()
void vlc_meta_Merge (vlc_meta_t * dst, const vlc_meta_t * src)
Merging meta.
References vlc_meta_t::extra_tags, vlc_meta_t::ppsz_meta, strdup(), vlc_dictionary_all_keys(), vlc_dictionary_insert(), vlc_dictionary_remove_value_for_key(), vlc_dictionary_value_for_key(), vlc_meta_FreeExtraKey(), and VLC_META_TYPE_COUNT.
Referenced by CmdInitControl(), EsOutMeta(), EsOutProgramMeta(), input_DecoderHasFormatChanged(), input_item_Copy(), and InputSourceMeta().
vlc_meta_New()
vlc_meta_t * vlc_meta_New (void)
vlc_meta contructor.
vlc_meta_Delete() will free the returned pointer.
References vlc_meta_t::extra_tags, vlc_meta_t::i_status, vlc_meta_t::ppsz_meta, and vlc_dictionary_init().
Referenced by ArtCachePath(), CmdInitControl(), EsOutProgramEpg(), EsOutProgramMeta(), Init(), input_DecoderHasFormatChanged(), input_item_Copy(), input_item_SetArtFetched(), input_item_SetArtNotFound(), input_item_SetMeta(), input_item_SetPreparsed(), and InputUpdateMeta().
vlc_meta_Set()
void vlc_meta_Set (vlc_meta_t * p_meta, vlc_meta_type_t meta_type, const char * psz_val)
vlc_meta has two kinds of meta, the one in a table, and the one in a dictionary.
FIXME - Why don't we merge those two?
References IsUTF8(), vlc_meta_t::ppsz_meta, and strdup().
Referenced by EsOutProgramEpg(), input_item_SetMeta(), and InputMetaUser().
vlc_meta_SetStatus()
void vlc_meta_SetStatus (vlc_meta_t * m, int status)
References vlc_meta_t::i_status.
Referenced by input_item_SetArtFetched(), input_item_SetArtNotFound(), and input_item_SetPreparsed().
vlc_meta_TypeToLocalizedString()
const char * vlc_meta_TypeToLocalizedString (vlc_meta_type_t meta_type)
Returns a localizes string describing the meta.
References N_, vlc_gettext(), vlc_meta_Actors, vlc_meta_Album, vlc_meta_AlbumArtist, vlc_meta_Artist, vlc_meta_ArtworkURL, vlc_meta_Copyright, vlc_meta_Date, vlc_meta_Description, vlc_meta_Director, vlc_meta_DiscNumber, vlc_meta_EncodedBy, vlc_meta_Episode, vlc_meta_ESNowPlaying, vlc_meta_Genre, vlc_meta_Language, vlc_meta_NowPlaying, vlc_meta_Publisher, vlc_meta_Rating, vlc_meta_Season, vlc_meta_Setting, vlc_meta_ShowName, vlc_meta_Title, vlc_meta_TrackID, vlc_meta_TrackNumber, vlc_meta_TrackTotal, and vlc_meta_URL.
Referenced by EsOutProgramEpg(), and EsOutProgramMeta().