VLC: src/misc/mime.c File Reference
mime.c File Reference
Functions
const char * vlc_mime_Ext2Mime (const char *psz_url)
Variables
struct {
const char psz_ext [8]
const char * psz_mime
} ext_mime []
Function Documentation
vlc_mime_Ext2Mime()
const char * vlc_mime_Ext2Mime (const char * psz_url)
References ext_mime, psz_ext, and strcasecmp().
Referenced by httpd_FileNew(), and httpd_StreamNew().
Variable Documentation
[struct]
const struct { ... } ext_mime[]
Referenced by vlc_mime_Ext2Mime().
psz_ext
const char psz_ext[8]
Referenced by vlc_mime_Ext2Mime().
psz_mime
const char* psz_mime