VLC: src/misc/cpu.c File Reference
cpu.c File Reference
Functions
void vlc_CPU_init (void)
Determines the CPU capabilities and stores them in cpu_flags.
unsigned vlc_CPU (void)
Retrieves pre-computed CPU capability flags.
void vlc_CPU_dump (vlc_object_t *obj)
Variables
static uint32_t cpu_flags
Function Documentation
vlc_CPU()
unsigned vlc_CPU (void)
Retrieves pre-computed CPU capability flags.
References cpu_flags, and vlc_CPU_init().
vlc_CPU_dump()
void vlc_CPU_dump (vlc_object_t * obj)
References msg_Dbg, vlc_memstream::stream, vlc_memstream_close(), vlc_memstream_open(), and vlc_memstream_puts().
Referenced by libvlc_InternalInit().
vlc_CPU_init()
void vlc_CPU_init (void)
Determines the CPU capabilities and stores them in cpu_flags.
The result can be retrieved with vlc_CPU().
References cpu_flags.
Referenced by _DLL_InitTerm(), DllMain(), and vlc_CPU().
Variable Documentation
cpu_flags
uint32_t cpu_flags static
Referenced by vlc_CPU(), and vlc_CPU_init().