VLC: modules/access/http/access.c File Reference
access.c File Reference
Data Structures
struct access_sys_t
Functions
static block_t * FileRead (stream_t *access, bool *restrict eof)
static int FileSeek (stream_t *access, uint64_t pos)
static int FileControl (stream_t *access, int query, va_list args)
static block_t * LiveRead (stream_t *access, bool *restrict eof)
static int NoSeek (stream_t *access, uint64_t pos)
static int LiveControl (stream_t *access, int query, va_list args)
static int Open (vlc_object_t *obj)
static void Close (vlc_object_t *obj)
int vlc_entry__MODULE_NAME (vlc_set_cb, void *)
Function Documentation
Close()
static void Close (vlc_object_t * obj) static
References access_sys_t::manager, stream_t::p_sys, access_sys_t::resource, vlc_http_mgr_destroy(), and vlc_http_res_destroy().
FileControl()
static int FileControl (stream_t * access, int query, va_list args) static
< Unspecified error
< Unspecified error
< No error
References stream_t::p_sys, access_sys_t::resource, STREAM_CAN_CONTROL_PACE, STREAM_CAN_FASTSEEK, STREAM_CAN_PAUSE, STREAM_CAN_SEEK, STREAM_GET_CONTENT_TYPE, STREAM_GET_PTS_DELAY, STREAM_GET_SIZE, STREAM_SET_PAUSE_STATE, var_InheritInteger, VLC_EGENERIC, vlc_http_file_can_seek(), vlc_http_file_get_size(), vlc_http_file_get_type, and VLC_SUCCESS.
Referenced by Open().
FileRead()
static block_t * FileRead (stream_t * access, bool *restrict eof) static
References stream_t::p_sys, access_sys_t::resource, and vlc_http_file_read().
Referenced by Open().
FileSeek()
static int FileSeek (stream_t * access, uint64_t pos) static
< Unspecified error
< No error
References stream_t::p_sys, access_sys_t::resource, VLC_EGENERIC, vlc_http_file_seek(), and VLC_SUCCESS.
Referenced by Open().
LiveControl()
static int LiveControl (stream_t * access, int query, va_list args) static
< Unspecified error
< No error
References stream_t::p_sys, access_sys_t::resource, STREAM_CAN_CONTROL_PACE, STREAM_CAN_FASTSEEK, STREAM_CAN_PAUSE, STREAM_CAN_SEEK, STREAM_GET_CONTENT_TYPE, STREAM_GET_PTS_DELAY, var_InheritInteger, VLC_EGENERIC, vlc_http_live_get_type, and VLC_SUCCESS.
Referenced by Open().
LiveRead()
static block_t * LiveRead (stream_t * access, bool *restrict eof) static
References stream_t::p_sys, access_sys_t::resource, and vlc_http_live_read().
Referenced by Open().
NoSeek()
static int NoSeek (stream_t * access, uint64_t pos) static
< Unspecified error
References VLC_EGENERIC.
Referenced by Open().
Open()
static int Open (vlc_object_t * obj) static
< Not enough memory
< Not enough memory
< Unspecified error
< Timeout
< No error
References _, FileControl(), FileRead(), FileSeek(), LiveControl(), LiveRead(), access_sys_t::manager, msg_Err, NoSeek(), stream_t::p_sys, stream_t::pf_block, stream_t::pf_control, stream_t::pf_read, stream_t::pf_seek, vlc_credential::psz_authtype, vlc_credential::psz_password, vlc_credential::psz_realm, stream_t::psz_url, vlc_credential::psz_username, access_sys_t::resource, unlikely, var_InheritAddress, var_InheritBool, var_InheritString, VLC_ACCESS_REDIRECT, vlc_credential_clean(), vlc_credential_get, vlc_credential_init(), vlc_credential_store, VLC_EGENERIC, VLC_ENOMEM, vlc_http_file_create(), vlc_http_live_create(), vlc_http_mgr_create(), vlc_http_mgr_destroy(), vlc_http_res_destroy(), vlc_http_res_get_basic_realm(), vlc_http_res_get_redirect(), vlc_http_res_get_status(), vlc_http_res_set_login(), VLC_SUCCESS, vlc_UrlClean(), and vlc_UrlParse().
vlc_entry__MODULE_NAME()
int vlc_entry__MODULE_NAME (vlc_set_cb vlc_set, void * opaque)