VLC: modules/access/http/file.c File Reference
file.c File Reference
Data Structures
struct vlc_http_file
Functions
static int vlc_http_file_req (const struct vlc_http_resource *res, struct vlc_http_msg *req, void *opaque)
static int vlc_http_file_resp (const struct vlc_http_resource *res, const struct vlc_http_msg *resp, void *opaque)
struct vlc_http_resource * vlc_http_file_create (struct vlc_http_mgr *mgr, const char *uri, const char *ua, const char *ref)
Creates an HTTP file.
static uintmax_t vlc_http_msg_get_file_size (const struct vlc_http_msg *resp)
static bool vlc_http_msg_can_seek (const struct vlc_http_msg *resp)
uintmax_t vlc_http_file_get_size (struct vlc_http_resource *res)
Gets file size.
bool vlc_http_file_can_seek (struct vlc_http_resource *res)
Checks seeking support.
int vlc_http_file_seek (struct vlc_http_resource *res, uintmax_t offset)
Sets the read offset.
block_t * vlc_http_file_read (struct vlc_http_resource *res)
Reads data.
Variables
static const struct vlc_http_resource_cbs vlc_http_file_callbacks
Function Documentation
vlc_http_file_req()
static int vlc_http_file_req (const struct vlc_http_resource * res, struct vlc_http_msg * req, void * opaque) static
References vlc_http_file::offset, vlc_http_file::resource, vlc_http_resource::response, vlc_http_msg_add_header(), vlc_http_msg_add_time(), vlc_http_msg_get_header(), and vlc_http_msg_get_mtime().
vlc_http_file_resp()
static int vlc_http_file_resp (const struct vlc_http_resource * res, const struct vlc_http_msg * resp, void * opaque) static
References vlc_http_file::offset, vlc_http_msg_get_header(), and vlc_http_msg_get_status().
vlc_http_msg_can_seek()
static bool vlc_http_msg_can_seek (const struct vlc_http_msg * resp) static
References vlc_http_msg_get_status(), and vlc_http_msg_get_token().
Referenced by vlc_http_file_can_seek(), and vlc_http_file_read().
vlc_http_msg_get_file_size()
static uintmax_t vlc_http_msg_get_file_size (const struct vlc_http_msg * resp) static
References unlikely, vlc_assert_unreachable, vlc_http_msg_get_header(), and vlc_http_msg_get_status().
Referenced by vlc_http_file_get_size(), and vlc_http_file_read().
Variable Documentation
vlc_http_file_callbacks
const struct vlc_http_resource_cbs vlc_http_file_callbacks static
Initial value:
=
{
    vlc_http_file_req,
    vlc_http_file_resp,
}
Referenced by vlc_http_file_create().