VLC: modules/access/http/resource.c File Reference
resource.c File Reference
Functions
static struct vlc_http_msg * vlc_http_res_req (const struct vlc_http_resource *res, void *opaque)
struct vlc_http_msg * vlc_http_res_open (struct vlc_http_resource *res, void *opaque)
int vlc_http_res_get_status (struct vlc_http_resource *res)
static void vlc_http_res_deinit (struct vlc_http_resource *res)
void vlc_http_res_destroy (struct vlc_http_resource *res)
Destroys an HTTP resource.
static char * vlc_http_authority (const char *host, unsigned port)
int vlc_http_res_init (struct vlc_http_resource *restrict res, const struct vlc_http_resource_cbs *cbs, struct vlc_http_mgr *mgr, const char *uri, const char *ua, const char *ref)
char * vlc_http_res_get_redirect (struct vlc_http_resource *restrict res)
char * vlc_http_res_get_type (struct vlc_http_resource *res)
Gets MIME type.
struct block_t * vlc_http_res_read (struct vlc_http_resource *res)
Reads data.
int vlc_http_res_set_login (struct vlc_http_resource *res, const char *username, const char *password)
char * vlc_http_res_get_basic_realm (struct vlc_http_resource *res)
Function Documentation
vlc_http_authority()
static char * vlc_http_authority (const char * host, unsigned port) static
References asprintf(), vlc_http_msg::authority, and unlikely.
Referenced by vlc_http_res_init().
vlc_http_res_deinit()
static void vlc_http_res_deinit (struct vlc_http_resource * res) static
References vlc_http_resource::agent, vlc_http_resource::authority, vlc_http_resource::host, vlc_http_resource::password, vlc_http_resource::path, vlc_http_resource::referrer, vlc_http_resource::response, vlc_http_resource::username, and vlc_http_msg_destroy().
Referenced by vlc_http_res_destroy(), and vlc_http_res_init().
vlc_http_res_get_redirect()
char * vlc_http_res_get_redirect (struct vlc_http_resource *restrict res)
References asprintf(), likely, vlc_http_msg::status, unlikely, vlc_ascii_strcasecmp(), vlc_http_msg_get_header(), vlc_http_res_get_status(), vlc_uri_fixup(), and vlc_uri_resolve().
Referenced by Open().
vlc_http_res_init()
int vlc_http_res_init (struct vlc_http_resource *restrict res, const struct vlc_http_resource_cbs * cbs, struct vlc_http_mgr * mgr, const char * uri, const char * ua, const char * ref)
References asprintf(), vlc_url_t::i_port, vlc_http_msg::path, vlc_url_t::psz_host, vlc_url_t::psz_option, vlc_url_t::psz_password, vlc_url_t::psz_path, vlc_url_t::psz_protocol, vlc_url_t::psz_username, strdup(), unlikely, vlc_ascii_strcasecmp(), vlc_http_authority(), vlc_http_res_deinit(), vlc_UrlClean(), and vlc_UrlParse().
Referenced by vlc_http_file_create(), and vlc_http_live_create().
vlc_http_res_req()
static struct vlc_http_msg * vlc_http_res_req (const struct vlc_http_resource * res, void * opaque) static
References vlc_http_resource::agent, vlc_http_resource::authority, vlc_http_resource::cbs, vlc_http_resource::manager, vlc_http_resource::negotiate, vlc_http_resource::password, vlc_http_resource::path, vlc_http_resource::referrer, vlc_http_resource_cbs::request_format, vlc_http_resource::secure, unlikely, vlc_http_resource::username, vlc_gettext(), vlc_http_mgr_get_jar(), vlc_http_msg_add_agent(), vlc_http_msg_add_cookies(), vlc_http_msg_add_creds_basic(), vlc_http_msg_add_header(), vlc_http_msg_destroy(), and vlc_http_req_create().
Referenced by vlc_http_res_open().