VLC: src/modules/modules.c File Reference
modules.c File Reference
Functions
bool module_provides (const module_t *m, const char *cap)
Checks whether a module implements a capability.
const char * module_get_object (const module_t *m)
Get the internal name of a module.
const char * module_get_name (const module_t *m, bool long_name)
Get the human-friendly name of a module.
const char * module_get_help (const module_t *m)
Get the help for a module.
const char * module_get_capability (const module_t *m)
Gets the capability of a module.
int module_get_score (const module_t *m)
Get the score for a module.
const char * module_gettext (const module_t *m, const char *str)
Translate a string using the module's text domain.
int module_start (vlc_object_t *obj, const module_t *m)
void module_stop (vlc_object_t *obj, const module_t *m)
static bool module_match_name (const module_t *m, const char *name)
static int module_load (vlc_object_t *obj, module_t *m, vlc_activate_t init, va_list args)
module_t * vlc_module_load (vlc_object_t *obj, const char *capability, const char *name, bool strict, vlc_activate_t probe,...)
Finds and instantiates the best module of a certain type.
void vlc_module_unload (vlc_object_t *obj, module_t *module, vlc_deactivate_t deinit,...)
Deinstantiates a module.
static int generic_start (void *func, va_list ap)
static void generic_stop (void *func, va_list ap)
module_t * module_need (vlc_object_t *obj, const char *cap, const char *name, bool strict)
void module_unneed (vlc_object_t *obj, module_t *module)
module_t * module_find (const char *name)
Get a pointer to a module_t given it's name.
bool module_exists (const char *psz_name)
Tell if a module exists.
module_config_t * module_config_get (const module_t *module, unsigned *restrict psize)
Get the configuration of a module.
void module_config_free (module_config_t *config)
Release the configuration.
Function Documentation
generic_start()
static int generic_start (void * func, va_list ap) static
Referenced by module_need().
generic_stop()
static void generic_stop (void * func, va_list ap) static
Referenced by module_unneed().
module_config_free()
void module_config_free (module_config_t * config)
Release the configuration.
Parameters
the configuration
Returns
nothing
References config.
module_config_get()
module_config_t * module_config_get (const module_t * module, unsigned *restrict psize)
Get the configuration of a module.
Parameters
module the module
psize the size of the configuration returned
Returns
the configuration as an array
References module_config_t::b_internal, module_config_t::b_removed, vlc_plugin_t::conf, config, vlc_plugin_t::items, vlc_plugin_t::module, vlc_plugin_t::size, and vlc_alloc().
module_exists()
bool module_exists (const char * psz_name)
Tell if a module exists.
Parameters
psz_name th name of the module
Returns
TRUE if the module exists
References module_find(), and psz_name.
Referenced by aout_New().
module_find()
module_t * module_find (const char * name)
Get a pointer to a module_t given it's name.
Parameters
name the name of the module
Returns
a pointer to the module or NULL in case of a failure
References count, module_t::i_shortcuts, list, module_list_free(), module_list_get(), name, module_t::pp_shortcuts, and unlikely.
Referenced by module_exists(), and module_get_main().
module_get_capability()
const char * module_get_capability (const module_t * m)
Gets the capability of a module.
Parameters
m the module
Returns
the capability, or "none" if unspecified
References module_t::psz_capability.
Referenced by module_provides(), and vlc_module_store().
module_get_help()
const char * module_get_help (const module_t * m)
Get the help for a module.
Parameters
m the module
Returns
the help
References module_t::psz_help.
module_get_name()
const char * module_get_name (const module_t * m, bool long_name)
Get the human-friendly name of a module.
Parameters
m the module
long_name TRUE to have the long name of the module
Returns
the short or long name of the module
References module_get_object(), module_t::psz_longname, and module_t::psz_shortname.
Referenced by config_ListModules(), DecoderFixTs(), demux_filter_enable_disable(), and filter_chain_AppendInner().
module_get_object()
const char * module_get_object (const module_t * m)
Get the internal name of a module.
Parameters
m the module
Returns
the module name
References module_t::i_shortcuts, module_t::pp_shortcuts, and unlikely.
Referenced by config_ListModules(), config_SaveConfigFile(), ListModules(), module_get_name(), module_is_main(), module_match(), module_unneed(), Usage(), and vlc_module_load().
module_get_score()
int module_get_score (const module_t * m)
Get the score for a module.
Parameters
m the module return the score for the capability
References module_t::i_score.
Referenced by vlc_module_load().
module_gettext()
const char * module_gettext (const module_t * m, const char * str)
Translate a string using the module's text domain.
Parameters
m the module
str the American English ASCII string to localize
Returns
the gettext-translated string
References module_t::plugin, vlc_plugin_t::textdomain, and unlikely.
Referenced by config_ListModules(), ListModules(), print_item(), print_section(), and Usage().
module_load()
static int module_load (vlc_object_t * obj, module_t * m, vlc_activate_t init, va_list args) static
< No error
< Unspecified error
< No error
References init, module_Map(), module_t::pf_activate, module_t::plugin, VLC_EGENERIC, vlc_objres_clear(), and VLC_SUCCESS.
Referenced by vlc_module_load().
module_match_name()
static bool module_match_name (const module_t * m, const char * name) static
References module_t::i_score, module_t::i_shortcuts, name, module_t::pp_shortcuts, and strcasecmp().
Referenced by vlc_module_load().
module_need()
module_t * module_need (vlc_object_t * obj, const char * cap, const char * name, bool strict)
References generic_start(), name, and vlc_module_load.
module_provides()
bool module_provides (const module_t * m, const char * cap)
Checks whether a module implements a capability.
Parameters
m the module
cap the capability to check
Returns
true if the module has the capability
References module_get_capability().
module_start()
int module_start (vlc_object_t * obj, const module_t * m)
< No error
References module_t::pf_activate, and VLC_SUCCESS.
module_stop()
void module_stop (vlc_object_t * obj, const module_t * m)
References module_t::pf_deactivate.
module_unneed()
void module_unneed (vlc_object_t * obj, module_t * module)
References generic_stop(), module_get_object(), msg_Dbg, and vlc_module_unload.
vlc_module_load()
module_t * vlc_module_load (vlc_object_t * obj, const char * capability, const char * name, bool strict, vlc_activate_t probe, ...)
Finds and instantiates the best module of a certain type.
All candidates modules having the specified capability and name will be sorted in decreasing order of priority. Then the probe callback will be invoked for each module, until it succeeds (returns 0), or all candidate module failed to initialize.
The probe callback first parameter is the address of the module entry point. Further parameters are passed as an argument list; it corresponds to the variable arguments passed to this function. This scheme is meant to support arbitrary prototypes for the module entry point.
Parameters
obj VLC object
capability capability, i.e. class of module
name name of the module asked, if any
strict if true, do not fallback to plugin with a different name but the same capability
probe module probe callback
Returns
the module or NULL in case of a failure
< No error
< Timeout
< No error
< Timeout
References vlc_common_members::force, likely, module_get_object(), module_get_score(), module_list_cap(), module_list_free(), module_load(), module_match_name(), msg_Dbg, name, vlc_object_t::obj, strcasecmp(), unlikely, var_InheritString, VLC_ETIMEOUT, vlc_object_set_name, and VLC_SUCCESS.
vlc_module_unload()
void vlc_module_unload (vlc_object_t * obj, module_t * module, vlc_deactivate_t deinit, ...)
Deinstantiates a module.
Parameters
module the module pointer as returned by vlc_module_load()
deinit deactivation callback
References module_t::pf_deactivate, and vlc_objres_clear().