VLC: src/os2/dirs.c File Reference
dirs.c File Reference
Functions
char * config_GetLibDir (void)
char * config_GetDataDir (void)
Determines the shared data directory.
static char * config_GetHomeDir (void)
char * config_GetUserDir (vlc_userdir_t type)
Function Documentation
config_GetDataDir()
char * config_GetDataDir (void)
Determines the shared data directory.
Returns
a nul-terminated string or NULL. Use free() to release it.
References config_GetLibDir(), getenv(), and strdup().
config_GetHomeDir()
static char * config_GetHomeDir (void) static
References config_GetLibDir(), FromLocaleDup, and getenv().
config_GetLibDir()
char * config_GetLibDir (void)
References FromLocaleDup, and system_Init().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References config_GetHomeDir(), VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.