VLC: src/os2/thread.c File Reference
thread.c File Reference
Data Structures
struct vlc_thread
struct vlc_static_cond_t
struct vlc_threadvar
struct vlc_timer
Macros
#define Q2LL(q) (*(long long *)&(q))
Typedefs
typedef struct vlc_static_cond_t vlc_static_cond_t
Functions
static void vlc_cancel_self (PVOID dummy)
static ULONG vlc_DosWaitEventSemEx (HEV hev, ULONG ulTimeout)
static ULONG vlc_WaitForSingleObject (HEV hev, ULONG ulTimeout)
static ULONG vlc_Sleep (ULONG ulTimeout)
static void vlc_static_cond_destroy_all (void)
int _CRT_init (void)
void _CRT_term (void)
unsigned long _System _DLL_InitTerm (unsigned long, unsigned long)
void vlc_mutex_init (vlc_mutex_t *p_mutex)
Initializes a fast mutex.
void vlc_mutex_init_recursive (vlc_mutex_t *p_mutex)
Initializes a recursive mutex.
void vlc_mutex_destroy (vlc_mutex_t *p_mutex)
Deinitializes a mutex.
void vlc_mutex_lock (vlc_mutex_t *p_mutex)
Acquires a mutex.
int vlc_mutex_trylock (vlc_mutex_t *p_mutex)
Tries to acquire a mutex.
void vlc_mutex_unlock (vlc_mutex_t *p_mutex)
Releases a mutex.
static void vlc_static_cond_init (vlc_cond_t *p_condvar)
void vlc_cond_init (vlc_cond_t *p_condvar)
Initializes a condition variable.
void vlc_cond_init_daytime (vlc_cond_t *p_condvar)
Initializes a condition variable (wall clock).
void vlc_cond_destroy (vlc_cond_t *p_condvar)
Deinitializes a condition variable.
void vlc_cond_signal (vlc_cond_t *p_condvar)
Wakes up one thread waiting on a condition variable.
void vlc_cond_broadcast (vlc_cond_t *p_condvar)
Wakes up all threads waiting on a condition variable.
static int vlc_cond_wait_common (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex, ULONG ulTimeout)
void vlc_cond_wait (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex)
Waits on a condition variable.
int vlc_cond_timedwait (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex, mtime_t deadline)
Waits on a condition variable up to a certain date.
int vlc_cond_timedwait_daytime (vlc_cond_t *p_condvar, vlc_mutex_t *p_mutex, time_t deadline)
int vlc_threadvar_create (vlc_threadvar_t *p_tls, void(*destr)(void *))
Allocates a thread-specific variable.
void vlc_threadvar_delete (vlc_threadvar_t *p_tls)
Deallocates a thread-specific variable.
int vlc_threadvar_set (vlc_threadvar_t key, void *value)
Sets a thread-specific variable.
void * vlc_threadvar_get (vlc_threadvar_t key)
Gets the value of a thread-local variable for the calling thread.
void vlc_threads_setup (libvlc_int_t *p_libvlc)
static void vlc_thread_cleanup (struct vlc_thread *th)
static void vlc_entry (void *p)
static int vlc_clone_attr (vlc_thread_t *p_handle, bool detached, void *(*entry)(void *), void *data, int priority)
int vlc_clone (vlc_thread_t *p_handle, void *(*entry)(void *), void *data, int priority)
Creates and starts a new thread.
void vlc_join (vlc_thread_t th, void **result)
Waits for a thread to complete (if needed), then destroys it.
int vlc_clone_detach (vlc_thread_t *p_handle, void *(*entry)(void *), void *data, int priority)
int vlc_set_priority (vlc_thread_t th, int priority)
vlc_thread_t vlc_thread_self (void)
Thread handle.
unsigned long vlc_thread_id (void)
Thread identifier.
void vlc_cancel (vlc_thread_t thread_id)
Marks a thread as cancelled.
int vlc_savecancel (void)
Disables thread cancellation.
void vlc_restorecancel (int state)
Restores the cancellation state.
void vlc_testcancel (void)
Issues an explicit deferred cancellation point.
void vlc_control_cancel (int cmd,...)
Internal handler for thread cancellation.
static int vlc_select (int nfds, fd_set *rdset, fd_set *wrset, fd_set *exset, struct timeval *timeout)
__declspec (dllexport)
mtime_t mdate (void)
Precision monotonic clock.
void mwait (mtime_t deadline)
void msleep (mtime_t delay)
static void vlc_timer_do (void *arg)
int vlc_timer_create (vlc_timer_t *id, void(*func)(void *), void *data)
Initializes an asynchronous timer.
void vlc_timer_destroy (vlc_timer_t timer)
Destroys an initialized timer.
void vlc_timer_schedule (vlc_timer_t timer, bool absolute, mtime_t value, mtime_t interval)
Arms or disarms an initialized timer.
unsigned vlc_timer_getoverrun (vlc_timer_t timer)
Fetches and resets the overrun counter for a timer.
unsigned vlc_GetCPUCount (void)
Count CPUs.
Variables
static vlc_threadvar_t thread_key
static vlc_mutex_t super_mutex
static vlc_cond_t super_variable
vlc_rwlock_t config_lock
static vlc_static_cond_t * static_condvar_start = NULL
struct vlc_threadvar * vlc_threadvar_last = NULL
Macro Definition Documentation
Q2LL
#define Q2LL (q) (*(long long *)&(q))
Referenced by mdate().
Typedef Documentation
vlc_static_cond_t
typedef struct vlc_static_cond_t vlc_static_cond_t
Function Documentation
__declspec()
__declspec (dllexport)
_CRT_init()
int _CRT_init (void)
Referenced by _DLL_InitTerm().
_CRT_term()
void _CRT_term (void)
Referenced by _DLL_InitTerm().
_DLL_InitTerm()
unsigned long _System _DLL_InitTerm (unsigned long hmod, unsigned long flag)
References _CRT_init(), _CRT_term(), config_lock, super_mutex, super_variable, thread_key, vlc_cond_destroy(), vlc_cond_init(), vlc_CPU_init(), vlc_mutex_destroy(), vlc_mutex_init(), vlc_rwlock_destroy(), vlc_rwlock_init(), vlc_static_cond_destroy_all(), vlc_threadvar_create(), vlc_threadvar_delete(), and VLC_UNUSED.
msleep()
void msleep (mtime_t delay)
References mdate(), and mwait.
mwait()
void mwait (mtime_t deadline)
References mdate(), unlikely, vlc_Sleep(), and vlc_testcancel().
vlc_cancel_self()
static void vlc_cancel_self (PVOID dummy) static
References vlc_thread::killed, and likely.
Referenced by vlc_cancel(), vlc_DosWaitEventSemEx(), and vlc_testcancel().
vlc_clone_attr()
static int vlc_clone_attr (vlc_thread_t * p_handle, bool detached, void *(* entry)(void *), void * data, int priority) static
References vlc_thread::cancel_event, vlc_thread::cancel_sock, vlc_thread::cleaners, vlc_thread::data, vlc_thread::detached, vlc_thread::done_event, vlc_thread::entry, vlc_thread::killable, vlc_thread::killed, vlc_thread::tid, unlikely, and vlc_entry().
vlc_clone_detach()
int vlc_clone_detach (vlc_thread_t * p_handle, void *(* entry)(void *), void * data, int priority)
References vlc_thread::data, and vlc_clone_attr().
vlc_cond_wait_common()
static int vlc_cond_wait_common (vlc_cond_t * p_condvar, vlc_mutex_t * p_mutex, ULONG ulTimeout) static
References vlc_mutex_lock(), vlc_mutex_unlock(), vlc_testcancel(), and vlc_WaitForSingleObject().
Referenced by vlc_cond_timedwait(), vlc_cond_timedwait_daytime(), and vlc_cond_wait().
vlc_DosWaitEventSemEx()
static ULONG vlc_DosWaitEventSemEx (HEV hev, ULONG ulTimeout) static
References vlc_thread::cancel_event, vlc_thread::killable, vlc_cancel_self(), and vlc_thread_self().
Referenced by vlc_Sleep(), and vlc_WaitForSingleObject().
vlc_entry()
static void vlc_entry (void * p) static
References vlc_thread::data, vlc_thread::done_event, vlc_thread::entry, vlc_thread::killable, p, thread_key, vlc_thread_cleanup(), and vlc_threadvar_set().
Referenced by vlc_clone_attr().
vlc_select()
static int vlc_select (int nfds, fd_set * rdset, fd_set * wrset, fd_set * exset, struct timeval * timeout) static
References vlc_thread::cancel_sock, vlc_testcancel(), and vlc_thread_self().
vlc_set_priority()
int vlc_set_priority (vlc_thread_t th, int priority)
< Unspecified error
< No error
References VLC_EGENERIC, and VLC_SUCCESS.
vlc_Sleep()
static ULONG vlc_Sleep (ULONG ulTimeout) static
References vlc_DosWaitEventSemEx().
Referenced by mwait().
vlc_static_cond_destroy_all()
static void vlc_static_cond_destroy_all (void) static
References vlc_static_cond_t::condvar, vlc_static_cond_t::next, static_condvar_start, and vlc_cond_destroy().
Referenced by _DLL_InitTerm().
vlc_static_cond_init()
static void vlc_static_cond_init (vlc_cond_t * p_condvar) static
References vlc_static_cond_t::condvar, vlc_static_cond_t::next, static_condvar_start, super_mutex, unlikely, vlc_cond_init(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vlc_cond_broadcast(), vlc_cond_signal(), and vlc_cond_wait().
vlc_thread_cleanup()
static void vlc_thread_cleanup (struct vlc_thread * th) static
References vlc_thread::cancel_event, vlc_thread::cancel_sock, vlc_thread::detached, vlc_thread::done_event, vlc_threadvar::prev, super_mutex, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_threadvar_get(), vlc_threadvar_last, and vlc_threadvar_set().
Referenced by vlc_entry(), and vlc_testcancel().
vlc_threads_setup()
void vlc_threads_setup (libvlc_int_t * p_libvlc)
vlc_timer_do()
static void vlc_timer_do (void * arg) static
References count, vlc_timer::data, vlc_timer::func, vlc_timer::hev, vlc_timer::htimer, vlc_timer::interval, and vlc_timer::quit.
Referenced by vlc_timer_create().
vlc_WaitForSingleObject()
static ULONG vlc_WaitForSingleObject (HEV hev, ULONG ulTimeout) static
References vlc_DosWaitEventSemEx().
Referenced by vlc_cond_wait_common(), and vlc_join().
Variable Documentation
config_lock
vlc_rwlock_t config_lock extern
Referenced by _DLL_InitTerm(), and DllMain().
static_condvar_start
vlc_static_cond_t* static_condvar_start = NULL static
Referenced by vlc_static_cond_destroy_all(), and vlc_static_cond_init().
super_mutex
vlc_mutex_t super_mutex static
Referenced by _DLL_InitTerm(), DllMain(), vlc_mutex_lock(), vlc_mutex_trylock(), vlc_mutex_unlock(), vlc_static_cond_init(), vlc_thread_cleanup(), vlc_threadvar_create(), vlc_threadvar_delete(), and vlc_threadvars_cleanup().
super_variable
vlc_cond_t super_variable static
Referenced by _DLL_InitTerm(), DllMain(), vlc_mutex_lock(), and vlc_mutex_unlock().
thread_key
vlc_threadvar_t thread_key static
Referenced by _DLL_InitTerm(), DllMain(), vlc_entry(), and vlc_thread_self().
vlc_threadvar_last
struct vlc_threadvar * vlc_threadvar_last = NULL
Referenced by vlc_thread_cleanup(), vlc_threadvar_create(), vlc_threadvar_delete(), and vlc_threadvars_cleanup().