VLC: src/os2/specific.c File Reference
specific.c File Reference
Macros
#define VLC_IPC_PIPE "\\PIPE\\VLC\\IPC\\"VERSION
#define IPC_CMD_GO 0x00
#define IPC_CMD_ENQUEUE 0x01
#define IPC_CMD_QUIT 0xFF
Functions
static void IPCHelperThread (void *arg)
void system_Init (void)
void system_Configure (libvlc_int_t *p_this, int i_argc, const char *const ppsz_argv[])
void system_End (void)
Cleans up after system_Init() and system_Configure().
Variables
int _fmode_bin
static HPIPE hpipeIPC = NULLHANDLE
static int tidIPCFirst = -1
static int tidIPCHelper = -1
Macro Definition Documentation
IPC_CMD_ENQUEUE
#define IPC_CMD_ENQUEUE 0x01
Referenced by IPCHelperThread(), and system_Configure().
IPC_CMD_GO
#define IPC_CMD_GO 0x00
Referenced by system_Configure().
IPC_CMD_QUIT
#define IPC_CMD_QUIT 0xFF
Referenced by IPCHelperThread(), and system_End().
VLC_IPC_PIPE
#define VLC_IPC_PIPE "\\PIPE\\VLC\\IPC\\"VERSION
Referenced by system_Configure(), and system_End().
Function Documentation
IPCHelperThread()
static void IPCHelperThread (void * arg) static
References hpipeIPC, IPC_CMD_ENQUEUE, IPC_CMD_QUIT, libvlc_priv(), libvlc_priv_t::playlist, playlist_AddExt(), tidIPCFirst, tidIPCHelper, vlc_alloc(), and VLC_INPUT_OPTION_TRUSTED.
Referenced by system_Configure().
system_Configure()
void system_Configure (libvlc_int_t * p_this, int i_argc, const char *const ppsz_argv[])
References hpipeIPC, IPC_CMD_ENQUEUE, IPC_CMD_GO, IPCHelperThread(), msg_Dbg, msg_Err, msg_Info, strdup(), system_End(), tidIPCFirst, tidIPCHelper, var_InheritBool, VLC_IPC_PIPE, and vlc_path2uri().
system_End()
void system_End (void)
Cleans up after system_Init() and system_Configure().
References IPC_CMD_QUIT, tidIPCFirst, tidIPCHelper, and VLC_IPC_PIPE.
Referenced by libvlc_InternalCleanup(), and system_Configure().
system_Init()
void system_Init (void)
References _fmode_bin.
Variable Documentation
_fmode_bin
int _fmode_bin extern
Referenced by system_Init().
hpipeIPC
HPIPE hpipeIPC = NULLHANDLE static
Referenced by IPCHelperThread(), and system_Configure().
tidIPCFirst
int tidIPCFirst = -1 static
Referenced by IPCHelperThread(), system_Configure(), and system_End().
tidIPCHelper
int tidIPCHelper = -1 static
Referenced by IPCHelperThread(), system_Configure(), and system_End().