VLC: src/misc/picture_fifo.c File Reference
picture_fifo.c File Reference
Data Structures
struct picture_fifo_t
Functions
static void PictureFifoReset (picture_fifo_t *fifo)
static void PictureFifoPush (picture_fifo_t *fifo, picture_t *picture)
static picture_t * PictureFifoPop (picture_fifo_t *fifo)
picture_fifo_t * picture_fifo_New (void)
It creates an empty picture_fifo_t.
void picture_fifo_Push (picture_fifo_t *fifo, picture_t *picture)
It saves a picture_t into the fifo.
picture_t * picture_fifo_Pop (picture_fifo_t *fifo)
It retreives a picture_t from the fifo.
picture_t * picture_fifo_Peek (picture_fifo_t *fifo)
It returns the first picture_t pointer from the fifo but does not remove it.
void picture_fifo_Flush (picture_fifo_t *fifo, mtime_t date, bool flush_before)
It release all picture inside the fifo that have a lower or equal date if flush_before or higher or equal to if not flush_before than the given one.
void picture_fifo_OffsetDate (picture_fifo_t *fifo, mtime_t delta)
It applies a delta on all the picture timestamp.
void picture_fifo_Delete (picture_fifo_t *fifo)
It destroys a fifo created by picture_fifo_New.
Function Documentation
picture_fifo_Delete()
void picture_fifo_Delete (picture_fifo_t * fifo)
It destroys a fifo created by picture_fifo_New.
All pictures inside the fifo will be released by picture_Release.
References picture_fifo_t::lock, picture_fifo_Flush(), and vlc_mutex_destroy().
Referenced by image_HandlerDelete(), ThreadStart(), and ThreadStop().
picture_fifo_Flush()
void picture_fifo_Flush (picture_fifo_t * fifo, mtime_t date, bool flush_before)
It release all picture inside the fifo that have a lower or equal date if flush_before or higher or equal to if not flush_before than the given one.
All pictures inside the fifo will be released by picture_Release.
References picture_t::date, picture_fifo_t::first, picture_fifo_t::lock, picture_t::p_next, picture_Release(), PictureFifoPop(), PictureFifoPush(), PictureFifoReset(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by picture_fifo_Delete(), and ThreadFlush().
picture_fifo_New()
picture_fifo_t * picture_fifo_New (void)
It creates an empty picture_fifo_t.
References picture_fifo_t::lock, PictureFifoReset(), and vlc_mutex_init().
Referenced by image_HandlerCreate(), and ThreadStart().
picture_fifo_OffsetDate()
void picture_fifo_OffsetDate (picture_fifo_t * fifo, mtime_t delta)
It applies a delta on all the picture timestamp.
References picture_fifo_t::first, picture_fifo_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadChangePause().
picture_fifo_Peek()
picture_t * picture_fifo_Peek (picture_fifo_t * fifo)
It returns the first picture_t pointer from the fifo but does not remove it.
The picture returned has been hold for you so you must call picture_Release on it.
If the fifo is empty, it return NULL without waiting.
References picture_fifo_t::first, picture_fifo_t::lock, picture_Hold(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vout_IsEmpty().
picture_fifo_Pop()
picture_t * picture_fifo_Pop (picture_fifo_t * fifo)
It retreives a picture_t from the fifo.
If the fifo is empty, it return NULL without waiting.
References picture_fifo_t::lock, PictureFifoPop(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ImageRead(), and ThreadDisplayPreparePicture().
picture_fifo_Push()
void picture_fifo_Push (picture_fifo_t * fifo, picture_t * picture)
It saves a picture_t into the fifo.
References picture_fifo_t::lock, PictureFifoPush(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ImageQueueVideo(), and vout_PutPicture().
PictureFifoPop()
static picture_t * PictureFifoPop (picture_fifo_t * fifo) static
References picture_fifo_t::first, picture_fifo_t::last_ptr, and picture_t::p_next.
Referenced by picture_fifo_Flush(), and picture_fifo_Pop().
PictureFifoPush()
static void PictureFifoPush (picture_fifo_t * fifo, picture_t * picture) static
References picture_fifo_t::last_ptr, and picture_t::p_next.
Referenced by picture_fifo_Flush(), and picture_fifo_Push().
PictureFifoReset()
static void PictureFifoReset (picture_fifo_t * fifo) static
References picture_fifo_t::first, and picture_fifo_t::last_ptr.
Referenced by picture_fifo_Flush(), and picture_fifo_New().