VLC: src/misc/picture.c File Reference
picture.c File Reference
Macros
#define PICTURE_SW_SIZE_MAX (1<<28) /* 256MB: 8K * 8K * 4*/
Functions
static int AllocatePicture (picture_t *p_pic)
Allocate a new picture in the heap.
static void PictureDestroyContext (picture_t *p_picture)
static void picture_DestroyFromResource (picture_t *p_picture)
Destroys a picture allocated by picture_NewFromResource() but without a custom destruction callback.
static void picture_Destroy (picture_t *p_picture)
Destroys a picture allocated with picture_NewFromFormat() (and thus AllocatePicture()).
void picture_Reset (picture_t *p_picture)
This function will reset a picture information (properties and quantizers).
static int LCM (int a, int b)
int picture_Setup (picture_t *p_picture, const video_format_t *restrict fmt)
picture_t * picture_NewFromResource (const video_format_t *p_fmt, const picture_resource_t *p_resource)
This function will create a new picture using the provided resource.
picture_t * picture_NewFromFormat (const video_format_t *p_fmt)
This function will create a new picture using the given format.
picture_t * picture_New (vlc_fourcc_t i_chroma, int i_width, int i_height, int i_sar_num, int i_sar_den)
This function will create a new picture.
picture_t * picture_Hold (picture_t *p_picture)
This function will increase the picture reference count.
void picture_Release (picture_t *p_picture)
This function will release a picture.
void plane_CopyPixels (plane_t *p_dst, const plane_t *p_src)
void picture_CopyProperties (picture_t *p_dst, const picture_t *p_src)
This function will copy all picture dynamic properties.
void picture_CopyPixels (picture_t *p_dst, const picture_t *p_src)
This function will copy the picture pixels.
void picture_Copy (picture_t *p_dst, const picture_t *p_src)
This function will copy both picture dynamic properties and pixels.
static void picture_DestroyClone (picture_t *clone)
picture_t * picture_Clone (picture_t *picture)
Perform a shallow picture copy.
int picture_Export (vlc_object_t *p_obj, block_t **pp_image, video_format_t *p_fmt, picture_t *p_picture, vlc_fourcc_t i_format, int i_override_width, int i_override_height)
This function will export a picture to an encoded bitstream.
Macro Definition Documentation
PICTURE_SW_SIZE_MAX
#define PICTURE_SW_SIZE_MAX (1<<28) /* 256MB: 8K * 8K * 4*/
Referenced by AllocatePicture().
Function Documentation
AllocatePicture()
static int AllocatePicture (picture_t * p_pic) static
Allocate a new picture in the heap.
This function allocates a fake direct buffer in memory, which can be used exactly like a video buffer. The video output thread then manages how it gets displayed.
< Not enough memory
< Not enough memory
< Unspecified error
< No error
References aligned_alloc(), plane_t::i_lines, plane_t::i_pitch, picture_t::i_planes, p, picture_t::p, plane_t::p_pixels, PICTURE_SW_SIZE_MAX, VLC_EGENERIC, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by picture_NewFromResource().
LCM()
static int LCM (int a, int b) static
References GCD().
Referenced by picture_Setup().
picture_Clone()
picture_t * picture_Clone (picture_t * pic)
Perform a shallow picture copy.
This function makes a shallow copy of an existing picture. The same planes and resources will be used, and the cloned picture reference count will be incremented.
Returns
A clone picture on success, NULL on error.
References picture_t::context, picture_context_t::copy, picture_t::format, picture_resource_t::i_lines, plane_t::i_lines, picture_resource_t::i_pitch, plane_t::i_pitch, picture_t::i_planes, likely, picture_resource_t::p, picture_t::p, picture_resource_t::p_pixels, plane_t::p_pixels, picture_resource_t::p_sys, picture_t::p_sys, picture_DestroyClone(), picture_Hold(), and picture_NewFromResource().
Referenced by vout_snapshot_Set().
picture_Copy()
void picture_Copy (picture_t * p_dst, const picture_t * p_src)
This function will copy both picture dynamic properties and pixels.
You have to notice that sometime a simple picture_Hold may do what you want without the copy overhead. Provided for convenience.
Parameters
p_dst pointer to the destination picture.
p_src pointer to the source picture.
References picture_CopyPixels(), and picture_CopyProperties().
Referenced by ImageConvert(), and ThreadDisplayRenderPicture().
picture_CopyPixels()
void picture_CopyPixels (picture_t * p_dst, const picture_t * p_src)
This function will copy the picture pixels.
You can safely copy between pictures that do not have the same size, only the compatible(smaller) part will be copied.
References picture_t::context, picture_context_t::copy, picture_t::i_planes, picture_t::p, and plane_CopyPixels().
Referenced by picture_Copy().
picture_CopyProperties()
void picture_CopyProperties (picture_t * p_dst, const picture_t * p_src)
This function will copy all picture dynamic properties.
References picture_t::b_force, picture_t::b_progressive, picture_t::b_top_field_first, picture_t::date, and picture_t::i_nb_fields.
Referenced by picture_Copy().
picture_Destroy()
static void picture_Destroy (picture_t * p_picture) static
Destroys a picture allocated with picture_NewFromFormat() (and thus AllocatePicture()).
References aligned_free, picture_t::p, and plane_t::p_pixels.
Referenced by picture_NewFromResource().
picture_DestroyClone()
static void picture_DestroyClone (picture_t * clone) static
References picture_Release().
Referenced by picture_Clone().
picture_DestroyFromResource()
static void picture_DestroyFromResource (picture_t * p_picture) static
Destroys a picture allocated by picture_NewFromResource() but without a custom destruction callback.
References picture_t::p_sys.
Referenced by picture_NewFromResource().
picture_Export()
int picture_Export (vlc_object_t * p_obj, block_t ** pp_image, video_format_t * p_fmt, picture_t * p_picture, vlc_fourcc_t i_format, int i_override_width, int i_override_height)
This function will export a picture to an encoded bitstream.
pp_image will contain the encoded bitstream in psz_format format.
p_fmt can be NULL otherwise it will be set with the format used for the picture before encoding.
i_override_width/height allow to override the width and/or the height of the picture to be encoded:
if strictly lower than 0, the original dimension will be used.
if equal to 0, it will be deduced from the other dimension which must be different to 0.
if strictly higher than 0, it will override the dimension. If at most one of them is > 0 then the picture aspect ratio will be kept.
< Not enough memory
< Unspecified error
< No error
References picture_t::date, picture_t::format, video_format_t::i_chroma, block_t::i_dts, video_format_t::i_height, block_t::i_pts, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, image_HandlerCreate, image_HandlerDelete(), image_Write, VLC_EGENERIC, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by vout_GetSnapshot().
picture_Hold()
picture_t * picture_Hold (picture_t * p_picture)
This function will increase the picture reference count.
It will not have any effect on picture obtained from vout
It returns the given picture for convenience.
References picture_priv_t::gc, and picture_priv_t::refs.
Referenced by ConvertRGB32AndBlend(), ImageConvert(), ImageWrite(), picture_Clone(), picture_fifo_Peek(), picture_pool_ClonePicture(), SplitterPrepare(), SpuRenderRegion(), ThreadDisplayPreparePicture(), and ThreadDisplayRenderPicture().
picture_New()
picture_t * picture_New (vlc_fourcc_t i_chroma, int i_width, int i_height, int i_sar_num, int i_sar_den)
This function will create a new picture.
The picture created will implement a default release management compatible with picture_Hold and picture_Release. This default management will release p_sys, gc.p_sys fields if non NULL.
References picture_NewFromFormat(), video_format_Init(), and video_format_Setup().
picture_NewFromFormat()
picture_t * picture_NewFromFormat (const video_format_t * p_fmt)
This function will create a new picture using the given format.
When possible, it is preferred to use this function over picture_New as more information about the format is kept.
References picture_NewFromResource().
Referenced by ConvertRGB32AndBlendBufferNew(), filter_chain_VideoBufferNew(), filter_new_picture(), picture_New(), picture_pool_NewFromFormat(), SplitterPictureNew(), spu_new_video_buffer(), subpicture_region_New(), video_new_buffer(), and VoutVideoFilterStaticNewPicture().
picture_NewFromResource()
picture_t * picture_NewFromResource (const video_format_t * p_fmt, const picture_resource_t * p_resource)
This function will create a new picture using the provided resource.
If the resource is NULL then a plain picture_NewFromFormat is returned.
References AllocatePicture(), picture_priv_t::destroy, picture_t::format, picture_priv_t::gc, video_format_t::i_chroma, video_format_t::i_height, picture_resource_t::i_lines, plane_t::i_lines, picture_resource_t::i_pitch, plane_t::i_pitch, picture_t::i_planes, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, picture_priv_t::opaque, picture_resource_t::p, picture_t::p, picture_resource_t::p_pixels, plane_t::p_pixels, picture_resource_t::p_sys, picture_t::p_sys, picture_resource_t::pf_destroy, picture_priv_t::picture, picture_Destroy(), picture_DestroyFromResource(), picture_Setup(), picture_priv_t::refs, unlikely, video_format_CopyCrop(), and video_format_Setup().
Referenced by picture_Clone(), picture_NewFromFormat(), and picture_pool_ClonePicture().
picture_Release()
void picture_Release (picture_t * p_picture)
This function will release a picture.
It will not have any effect on picture obtained from vout
References picture_priv_t::destroy, picture_priv_t::gc, PictureDestroyContext(), and picture_priv_t::refs.
Referenced by ConvertRGB32AndBlend(), DecoderPlayVideo(), FilterDeletePictures(), ImageConvert(), ImageRead(), ImageWrite(), picture_DestroyClone(), picture_fifo_Flush(), picture_pool_NewFromFormat(), picture_pool_Release(), picture_pool_ReleasePicture(), picture_pool_Reserve(), SplitterDisplay(), SplitterPictureDel(), SplitterPictureNew(), spuregion_CreateFromPicture(), SpuRenderRegion(), subpicture_NewFromPicture(), subpicture_region_Delete(), subpicture_region_private_Delete(), ThreadDisplayPicture(), ThreadDisplayPreparePicture(), ThreadDisplayRenderPicture(), ThreadFilterFlush(), ThreadFlush(), vout_FilterDisplay(), vout_GetSnapshot(), vout_IsEmpty(), vout_PutPicture(), vout_snapshot_Clean(), and VoutSaveSnapshot().
picture_Reset()
void picture_Reset (picture_t * p_picture)
This function will reset a picture information (properties and quantizers).
It is sometimes useful for reusing pictures (like from a pool).
References picture_t::b_force, picture_t::b_progressive, picture_t::b_top_field_first, picture_t::date, picture_t::i_nb_fields, PictureDestroyContext(), and VLC_TS_INVALID.
Referenced by vout_GetPicture(), and VoutVideoFilterInteractiveNewPicture().
picture_Setup()
int picture_Setup (picture_t * p_picture, const video_format_t *restrict fmt)
< Unspecified error
< No error
References vlc_rational_t::den, picture_t::format, vlc_chroma_description_t::h, video_format_t::i_chroma, plane_t::i_lines, picture_t::i_nb_fields, picture_t::i_planes, LCM(), vlc_rational_t::num, p, picture_t::p, vlc_chroma_description_t::p, plane_t::p_pixels, vlc_chroma_description_t::pixel_size, vlc_chroma_description_t::plane_count, video_format_Setup(), VLC_EGENERIC, vlc_fourcc_GetChromaDescription(), VLC_SUCCESS, VOUT_MAX_PLANES, and vlc_chroma_description_t::w.
Referenced by picture_NewFromResource().
PictureDestroyContext()
static void PictureDestroyContext (picture_t * p_picture) static
References picture_t::context, and picture_context_t::destroy.
Referenced by picture_Release(), and picture_Reset().
plane_CopyPixels()
void plane_CopyPixels (plane_t * p_dst, const plane_t * p_src)
References plane_t::i_lines, plane_t::i_pitch, plane_t::i_visible_pitch, and plane_t::p_pixels.
Referenced by picture_CopyPixels().