VLC: src/playlist/services_discovery.c File Reference
services_discovery.c File Reference
Data Structures
struct vlc_sd_internal_t
Functions
static void playlist_sd_item_added (services_discovery_t *sd, input_item_t *parent, input_item_t *p_input, const char *psz_cat)
static void playlist_sd_item_removed (services_discovery_t *sd, input_item_t *p_input)
int playlist_ServicesDiscoveryAdd (playlist_t *playlist, const char *chain)
Add a service discovery module.
static void playlist_ServicesDiscoveryInternalRemoveLocked (playlist_t *playlist, vlc_sd_internal_t *sds)
int playlist_ServicesDiscoveryRemove (playlist_t *playlist, const char *name)
Remove a services discovery module by name.
bool playlist_IsServicesDiscoveryLoaded (playlist_t *playlist, const char *psz_name)
Check whether a given SD is loaded.
int playlist_ServicesDiscoveryControl (playlist_t *playlist, const char *psz_name, int i_control,...)
Query a services discovery.
void playlist_ServicesDiscoveryKillAll (playlist_t *playlist)
Function Documentation
playlist_sd_item_added()
static void playlist_sd_item_added (services_discovery_t * sd, input_item_t * parent, input_item_t * p_input, const char * psz_cat) static
References services_discovery_t::description, msg_Dbg, vlc_sd_internal_t::node, services_discovery_t::obj, services_discovery_t::owner, vlc_common_members::parent, playlist_ChildSearchName(), PLAYLIST_END, playlist_ItemGetByInput(), playlist_Lock(), playlist_NodeAddInput(), playlist_NodeCreate(), PLAYLIST_RO_FLAG, playlist_Unlock(), input_item_t::psz_name, playlist_t::root, and services_discovery_owner_t::sys.
Referenced by playlist_ServicesDiscoveryAdd().
playlist_sd_item_removed()
static void playlist_sd_item_removed (services_discovery_t * sd, input_item_t * p_input) static
< delete node even if read-only
< stop playlist playback if node is currently the one played
References playlist_item_t::i_children, msg_Dbg, msg_Err, vlc_sd_internal_t::node, services_discovery_t::obj, services_discovery_t::owner, playlist_item_t::p_parent, vlc_common_members::parent, PLAYLIST_DELETE_FORCE, PLAYLIST_DELETE_STOP_IF_CURRENT, playlist_ItemGetByInput(), playlist_Lock(), playlist_NodeDeleteExplicit(), playlist_Unlock(), input_item_t::psz_name, services_discovery_owner_t::sys, and unlikely.
Referenced by playlist_ServicesDiscoveryAdd().
playlist_ServicesDiscoveryInternalRemoveLocked()
static void playlist_ServicesDiscoveryInternalRemoveLocked (playlist_t * playlist, vlc_sd_internal_t * sds) static
< delete node even if read-only
< stop playlist playback if node is currently the one played
References vlc_sd_internal_t::node, PLAYLIST_DELETE_FORCE, PLAYLIST_DELETE_STOP_IF_CURRENT, playlist_Lock(), playlist_NodeDeleteExplicit(), playlist_Unlock(), vlc_sd_internal_t::sd, and vlc_sd_Destroy().
Referenced by playlist_ServicesDiscoveryKillAll(), and playlist_ServicesDiscoveryRemove().