VLC: src/playlist/control.c File Reference
control.c File Reference
Functions
void playlist_Lock (playlist_t *pl)
Locks the playlist.
void playlist_Unlock (playlist_t *pl)
Unlocks the playlist.
void playlist_AssertLocked (playlist_t *pl)
static void playlist_vaControl (playlist_t *p_playlist, int i_query, bool locked, va_list args)
void playlist_Control (playlist_t *p_playlist, int query, int locked,...)
Do a playlist action.
Function Documentation
playlist_vaControl()
static void playlist_vaControl (playlist_t * p_playlist, int i_query, bool locked, va_list args) static
References get_current_status_item(), get_current_status_node(), PAUSE_S, PL_LOCK_IF, pl_priv, PL_UNLOCK_IF, PLAYING_S, PLAYLIST_PAUSE, PLAYLIST_PLAY, PLAYLIST_RESUME, PLAYLIST_SKIP, PLAYLIST_STOP, PLAYLIST_TOGGLE_PAUSE, PLAYLIST_VIEWPLAY, var_GetBool, var_GetInteger, var_SetInteger, and vlc_cond_signal().
Referenced by playlist_Control().