VLC: src/playlist/thread.c File Reference
thread.c File Reference
Functions
static void * Thread (void *data)
Run the main control thread itself.
void playlist_Activate (playlist_t *p_playlist)
Creates the main playlist thread.
void playlist_Deactivate (playlist_t *p_playlist)
Stops the playlist forever (but do not destroy it yet).
static int InputEvent (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
void ResyncCurrentIndex (playlist_t *p_playlist, playlist_item_t *p_cur)
Synchronise the current index of the playlist to match the index of the current item.
void ResetCurrentlyPlaying (playlist_t *p_playlist, playlist_item_t *p_cur)
Reset the currently playing playlist.
static bool PlayItem (playlist_t *p_playlist, playlist_item_t *p_item)
Start the input for an item.
static playlist_item_t * NextItem (playlist_t *p_playlist)
Compute the next playlist item depending on the playlist course mode (forward, backward, random, view,...).
static void LoopInput (playlist_t *p_playlist)
static bool Next (playlist_t *p_playlist)
Function Documentation
InputEvent()
static int InputEvent (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::i_int, playlist_private_t::input_dead, INPUT_EVENT_DEAD, PL_LOCK, pl_priv, PL_UNLOCK, playlist_private_t::request, playlist_private_t::signal, vlc_cond_signal(), VLC_SUCCESS, and VLC_UNUSED.
Referenced by LoopInput(), and PlayItem().
LoopInput()
static void LoopInput (playlist_t * p_playlist) static
References playlist_private_t::b_request, input_Close(), playlist_private_t::input_dead, input_resource_TerminateSout(), input_Stop(), InputEvent(), playlist_private_t::killed, playlist_private_t::lock, playlist_private_t::p_input, playlist_private_t::p_input_resource, PL_DEBUG, PL_LOCK, pl_priv, PL_UNLOCK, playlist_private_t::request, playlist_private_t::signal, var_DelCallback, var_InheritBool, var_SetAddress, and vlc_cond_wait().
Referenced by Thread().
Next()
static bool Next (playlist_t * p_playlist) static
References msg_Dbg, NextItem(), PlayItem(), and ResyncCurrentIndex().
Referenced by Thread().
NextItem()
static playlist_item_t * NextItem (playlist_t * p_playlist) static
Compute the next playlist item depending on the playlist course mode (forward, backward, random, view,...).
Parameters
p_playlist the playlist object
Returns
nothing
References ARRAY_VAL, playlist_private_t::b_request, playlist_private_t::b_reset_currently_playing, playlist_t::current, get_current_status_item(), get_current_status_node(), playlist_item_t::i_children, playlist_t::i_current_index, playlist_item_array_t::i_size, playlist_private_t::i_skip, playlist_t::items, msg_Dbg, msg_Info, playlist_private_t::p_item, playlist_private_t::p_node, PL_DEBUG, pl_priv, playlist_GetNextLeaf(), PLI_NAME, playlist_private_t::request, ResetCurrentlyPlaying(), ResyncCurrentIndex(), set_current_status_node(), var_GetBool, and var_InheritBool.
Referenced by Next().
PlayItem()
static bool PlayItem (playlist_t * p_playlist, playlist_item_t * p_item) static
Start the input for an item.
Parameters
p_playlist the playlist object
p_item the item to play
References EMPTY_STR, playlist_item_t::i_nb_played, input_Create, input_item_GetArtURL, input_Start(), InputEvent(), vlc_common_members::libvlc, libvlc_ArtRequest(), libvlc_MetadataCancel(), likely, META_REQUEST_OPTION_NONE, msg_Dbg, playlist_t::obj, playlist_item_t::p_input, playlist_private_t::p_input, playlist_private_t::p_input_resource, playlist_private_t::p_renderer, PL_ASSERT_LOCKED, PL_DEBUG, PL_LOCK, pl_priv, PL_UNLOCK, set_current_status_item(), var_AddCallback, var_DelCallback, var_SetAddress, vlc_object_release, vlc_renderer_item_hold(), and vlc_renderer_item_release().
Referenced by Next().
Thread()
static void * Thread (void * data) static
Run the main control thread itself.
References playlist_private_t::b_request, input_resource_HasVout(), input_resource_Terminate(), input_resource_TerminateVout(), playlist_private_t::killed, vlc_common_members::libvlc, libvlc_Quit(), playlist_private_t::lock, LoopInput(), msg_Dbg, msg_Info, Next(), playlist_t::obj, playlist_private_t::p_input, playlist_private_t::p_input_resource, PL_LOCK, pl_priv, PL_UNLOCK, playlist_private_t::request, playlist_private_t::signal, var_InheritBool, and vlc_cond_wait().
Referenced by playlist_Activate().