VLC: src/playlist/item.c File Reference
item.c File Reference
Functions
static void playlist_Preparse (playlist_t *, playlist_item_t *)
static int RecursiveAddIntoParent (playlist_t *p_playlist, playlist_item_t *p_parent, input_item_node_t *p_node, int i_pos, bool b_flat, playlist_item_t **pp_first_leaf)
static int RecursiveInsertCopy (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_parent, int i_pos, bool b_flat)
static void input_item_add_subitem_tree (const vlc_event_t *p_event, void *user_data)
static void input_item_changed (const vlc_event_t *p_event, void *user_data)
static int playlist_ItemCmpId (const void *a, const void *b)
static int playlist_ItemCmpInput (const void *a, const void *b)
playlist_item_t * playlist_ItemNewFromInput (playlist_t *p_playlist, input_item_t *p_input)
void playlist_ItemRelease (playlist_t *p_playlist, playlist_item_t *p_item)
Release an item.
playlist_item_t * playlist_ItemGetById (playlist_t *p_playlist, int id)
Finds a playlist item by ID.
playlist_item_t * playlist_ItemGetByInput (playlist_t *p_playlist, const input_item_t *item)
Finds a playlist item by input item.
void playlist_Clear (playlist_t *p_playlist, bool b_locked)
Clear the playlist.
int playlist_Add (playlist_t *p_playlist, const char *psz_uri, bool play_now)
Playlist add.
int playlist_AddExt (playlist_t *p_playlist, const char *psz_uri, const char *psz_name, bool play_now, int i_options, const char *const *ppsz_options, unsigned i_option_flags, bool b_playlist)
Add a MRL into the playlist or the media library, duration and options given.
int playlist_AddInput (playlist_t *p_playlist, input_item_t *p_input, bool play_now, bool b_playlist)
Add an input item to the playlist node.
playlist_item_t * playlist_NodeAddInput (playlist_t *p_playlist, input_item_t *p_input, playlist_item_t *p_parent, int i_pos)
Add an input item to a given node.
int playlist_NodeAddCopy (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_parent, int i_pos)
Copy an item (and all its children, if any) into another node.
int playlist_InsertInputItemTree (playlist_t *p_playlist, playlist_item_t *p_parent, input_item_node_t *p_node, int i_pos, bool b_flat)
Insert a tree of input items into a given playlist node.
static int ItemIndex (playlist_item_t *p_item)
int playlist_TreeMove (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_node, int i_newpos)
Moves an item.
int playlist_TreeMoveMany (playlist_t *p_playlist, int i_items, playlist_item_t **pp_items, playlist_item_t *p_node, int i_newpos)
Moves an array of items.
void playlist_SendAddNotify (playlist_t *p_playlist, playlist_item_t *item)
Send a notification that an item has been added to a node.
mtime_t playlist_GetNodeDuration (playlist_item_t *node)
Get the duration of all items in a node.
static void ChangeToNode (playlist_t *p_playlist, playlist_item_t *p_item)
Function Documentation
ChangeToNode()
static void ChangeToNode (playlist_t * p_playlist, playlist_item_t * p_item) static
References ARRAY_BSEARCH, ARRAY_REMOVE, playlist_item_t::i_children, playlist_item_t::i_id, input_item_t::i_type, ITEM_TYPE_NODE, playlist_t::items, input_item_t::lock, playlist_item_t::p_input, var_SetAddress, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by RecursiveAddIntoParent().
input_item_add_subitem_tree()
static void input_item_add_subitem_tree (const vlc_event_t * p_event, void * user_data) static
References ARRAY_VAL, playlist_private_t::b_request, playlist_t::current, get_current_status_item(), playlist_item_t::i_children, playlist_item_t::i_flags, playlist_item_t::i_id, playlist_item_array_t::i_size, vlc_event_t::vlc_event_type_specific::input_item_subitem_tree_added, playlist_private_t::p_item, playlist_private_t::p_node, vlc_event_t::p_obj, playlist_item_t::p_parent, playlist_t::p_playing, vlc_event_t::vlc_event_type_specific::vlc_input_item_subitem_tree_added::p_root, PL_LOCK, pl_Locked, pl_priv, PL_UNLOCK, playlist_Control(), playlist_InsertInputItemTree(), playlist_ItemGetByInput(), playlist_NodeDeleteExplicit(), PLAYLIST_STOP, PLAYLIST_SUBITEM_STOP_FLAG, playlist_ViewPlay(), playlist_item_t::pp_children, playlist_private_t::request, ResetCurrentlyPlaying(), vlc_event_t::u, var_GetBool, and var_SetInteger.
Referenced by playlist_ItemNewFromInput(), and playlist_ItemRelease().
input_item_changed()
static void input_item_changed (const vlc_event_t * p_event, void * user_data) static
References vlc_event_t::p_obj, and var_SetAddress.
Referenced by playlist_ItemNewFromInput(), and playlist_ItemRelease().
ItemIndex()
static int ItemIndex (playlist_item_t * p_item) static
References playlist_item_t::i_children, playlist_item_t::p_parent, playlist_item_t::pp_children, and TAB_FIND.
Referenced by playlist_TreeMove(), and playlist_TreeMoveMany().
playlist_ItemCmpId()
static int playlist_ItemCmpId (const void * a, const void * b) static
References playlist_item_t::i_id.
Referenced by playlist_ItemGetById(), playlist_ItemNewFromInput(), and playlist_ItemRelease().
playlist_ItemCmpInput()
static int playlist_ItemCmpInput (const void * a, const void * b) static
References playlist_item_t::p_input.
Referenced by playlist_ItemGetByInput(), playlist_ItemNewFromInput(), and playlist_ItemRelease().
playlist_Preparse()
static void playlist_Preparse (playlist_t * p_playlist, playlist_item_t * p_item) static
References playlist_private_t::b_preparse, EMPTY_STR, input_item_GetAlbum(), input_item_GetArtist(), input_item_IsPreparsed(), vlc_common_members::libvlc, playlist_t::obj, playlist_item_t::p_input, PL_ASSERT_LOCKED, pl_priv, and vlc_MetadataRequest().
Referenced by playlist_NodeAddInput().
RecursiveAddIntoParent()
static int RecursiveAddIntoParent (playlist_t * p_playlist, playlist_item_t * p_parent, input_item_node_t * p_node, int i_pos, bool b_flat, playlist_item_t ** pp_first_leaf) static
References ChangeToNode(), input_item_node_t::i_children, playlist_item_t::i_children, input_item_node_t::p_item, PLAYLIST_END, playlist_NodeAddInput(), input_item_node_t::pp_children, and RecursiveAddIntoParent().
Referenced by playlist_InsertInputItemTree(), and RecursiveAddIntoParent().
RecursiveInsertCopy()
static int RecursiveInsertCopy (playlist_t * p_playlist, playlist_item_t * p_item, playlist_item_t * p_parent, int i_pos, bool b_flat) static
References playlist_item_t::i_children, input_item_Copy(), input_item_Release(), likely, input_item_t::lock, playlist_item_t::p_input, PL_ASSERT_LOCKED, playlist_NodeAddInput(), playlist_NodeCreate(), playlist_item_t::pp_children, input_item_t::psz_name, RecursiveInsertCopy(), unlikely, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by playlist_NodeAddCopy(), and RecursiveInsertCopy().