VLC: src/posix/specific.c File Reference
specific.c File Reference
Functions
void system_Init (void)
static void system_ConfigureDbus (libvlc_int_t *vlc, int argc, const char *const argv[])
void system_Configure (libvlc_int_t *libvlc, int argc, const char *const argv[])
Function Documentation
system_Configure()
void system_Configure (libvlc_int_t * libvlc, int argc, const char *const argv[])
References system_ConfigureDbus().
system_ConfigureDbus()
static void system_ConfigureDbus (libvlc_int_t * vlc, int argc, const char *const argv[]) static
References libvlc_InternalAddIntf(), msg_Dbg, msg_Err, msg_Warn, name, unlikely, var_GetString, var_InheritBool, and vlc_path2uri().
Referenced by system_Configure().
system_Init()
void system_Init (void)