VLC: src/posix/timer.c File Reference
timer.c File Reference
Data Structures
struct vlc_timer
Functions
static noreturn void * vlc_timer_thread (void *data)
int vlc_timer_create (vlc_timer_t *id, void(*func)(void *), void *data)
Initializes an asynchronous timer.
void vlc_timer_destroy (vlc_timer_t timer)
Destroys an initialized timer.
void vlc_timer_schedule (vlc_timer_t timer, bool absolute, mtime_t value, mtime_t interval)
Arms or disarms an initialized timer.
unsigned vlc_timer_getoverrun (vlc_timer_t timer)
Fetches and resets the overrun counter for a timer.
Function Documentation
vlc_timer_thread()
static noreturn void * vlc_timer_thread (void * data) static
References vlc_timer::data, vlc_timer::func, vlc_timer::interval, likely, vlc_timer::lock, mdate(), mutex_cleanup_push, vlc_timer::overruns, vlc_timer::reschedule, vlc_timer::value, vlc_assert_unreachable, vlc_cleanup_pop, vlc_cond_timedwait(), vlc_cond_wait(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), and vlc_savecancel().
Referenced by vlc_timer_create().