VLC: src/posix/getaddrinfo.c File Reference
getaddrinfo.c File Reference
Data Structures
struct vlc_gai_req
Functions
static void * vlc_gai_thread (void *data)
int vlc_getaddrinfo_i11e (const char *name, unsigned port, const struct addrinfo *hints, struct addrinfo **res)
Function Documentation
vlc_gai_thread()
static void * vlc_gai_thread (void * data) static
References vlc_gai_req::done, vlc_gai_req::error, getaddrinfo(), vlc_gai_req::hints, vlc_gai_req::name, vlc_gai_req::result, vlc_gai_req::service, and vlc_sem_post().
Referenced by vlc_getaddrinfo_i11e().