VLC: src/posix/rand.c File Reference
rand.c File Reference
Macros
#define BLOCK_SIZE 64
Functions
static void vlc_rand_init (void)
void vlc_rand_bytes (void *buf, size_t len)
Variables
static uint8_t okey [64]
static uint8_t ikey [64]
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 64
Referenced by vlc_rand_init().
Function Documentation
vlc_rand_bytes()
void vlc_rand_bytes (void * buf, size_t len)
References AddMD5(), md5_s::buf, EndMD5(), ikey, InitMD5(), lock, NTPtime64(), okey, and vlc_rand_init().
vlc_rand_init()
static void vlc_rand_init (void) static
References BLOCK_SIZE, ikey, okey, vlc_close(), and vlc_open().
Referenced by vlc_rand_bytes().
Variable Documentation
ikey
uint8_t ikey[64] static
Referenced by vlc_rand_bytes(), and vlc_rand_init().
okey
uint8_t okey[64] static
Referenced by vlc_rand_bytes(), and vlc_rand_init().