VLC: src/posix/filesystem.c File Reference
filesystem.c File Reference
Macros
#define lstat(a, b) stat(a, b)
#define O_TMPFILE 0
Functions
static void vlc_cloexec (int fd)
int vlc_open (const char *filename, int flags,...)
Opens a system file handle.
int vlc_openat (int dir, const char *filename, int flags,...)
Opens a system file handle relative to an existing directory handle.
int vlc_mkstemp (char *template)
int vlc_memfd (void)
Creates an anonymous regular file descriptor, i.e.
int vlc_close (int fd)
Closes a file descriptor.
int vlc_mkdir (const char *dirname, mode_t mode)
Creates a directory.
DIR * vlc_opendir (const char *dirname)
Opens a DIR pointer.
const char * vlc_readdir (DIR *dir)
Reads the next file name from an open directory.
int vlc_stat (const char *filename, struct stat *buf)
Finds file/inode information - like stat().
int vlc_lstat (const char *filename, struct stat *buf)
Finds file/inode information, as lstat().
int vlc_unlink (const char *filename)
Removes a file.
int vlc_rename (const char *oldpath, const char *newpath)
Moves a file atomically.
char * vlc_getcwd (void)
Determines the current working directory.
int vlc_dup (int oldfd)
Duplicates a file descriptor.
int vlc_pipe (int fds[2])
Creates a pipe (see "man pipe" for further reference).
ssize_t vlc_write (int fd, const void *buf, size_t len)
Writes data to a file descriptor.
ssize_t vlc_writev (int fd, const struct iovec *iov, int count)
Writes data from an iovec structure to a file descriptor.
static void vlc_socket_setup (int fd, bool nonblock)
int vlc_socket (int pf, int type, int proto, bool nonblock)
Creates a socket file descriptor.
int vlc_socketpair (int pf, int type, int proto, int fds[2], bool nonblock)
Creates a pair of socket file descriptors.
int vlc_accept (int lfd, struct sockaddr *addr, socklen_t *alen, bool nonblock)
Accepts an inbound connection request on a listening socket.
Macro Definition Documentation
lstat
#define lstat (a, b) stat(a, b)
Referenced by vlc_lstat(), and vlc_statEx().
O_TMPFILE
#define O_TMPFILE 0
Referenced by vlc_memfd(), vlc_open(), and vlc_openat().
Function Documentation
vlc_cloexec()
static void vlc_cloexec (int fd) inline static
Referenced by vlc_dup(), vlc_mkstemp(), vlc_open(), vlc_pipe(), and vlc_socket_setup().
vlc_socket_setup()
static void vlc_socket_setup (int fd, bool nonblock) static
References vlc_cloexec().