VLC: src/posix/dirs.c File Reference
dirs.c File Reference
Functions
char * config_GetDataDir (void)
Determines the shared data directory.
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
static char * config_GetHomeDir (void)
static char * config_GetAppDir (const char *xdg_name, const char *xdg_default)
static char * config_GetTypeDir (const char *xdg_name)
char * config_GetUserDir (vlc_userdir_t type)
Function Documentation
config_GetAppDir()
static char * config_GetAppDir (const char * xdg_name, const char * xdg_default) static
References asprintf(), config_GetHomeDir(), and getenv().
config_GetDataDir()
char * config_GetDataDir (void)
Determines the shared data directory.
Returns
a nul-terminated string or NULL. Use free() to release it.
References getenv(), and strdup().
config_GetHomeDir()
static char * config_GetHomeDir (void) static
References getenv(), and strdup().
config_GetLibDir()
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
Returns
a string (always succeeds).
References strdup().
config_GetTypeDir()
static char * config_GetTypeDir (const char * xdg_name) static
References asprintf(), getenv(), getline(), and strdup().
Referenced by config_GetUserDir().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References config_GetAppDir(), config_GetHomeDir(), config_GetTypeDir(), VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.