VLC: src/misc/renderer_discovery.c File Reference
renderer_discovery.c File Reference
Data Structures
struct vlc_renderer_item_t
struct vlc_rd_probe
Functions
static void item_free (vlc_renderer_item_t *p_item)
vlc_renderer_item_t * vlc_renderer_item_new (const char *psz_type, const char *psz_name, const char *psz_uri, const char *psz_extra_sout, const char *psz_demux_filter, const char *psz_icon_uri, int i_flags)
Create a new renderer item.
const char * vlc_renderer_item_name (const vlc_renderer_item_t *p_item)
Get the human readable name of a renderer item.
const char * vlc_renderer_item_type (const vlc_renderer_item_t *p_item)
Get the type (not translated) of a renderer item.
const char * vlc_renderer_item_sout (const vlc_renderer_item_t *p_item)
Get the sout command of a renderer item.
const char * vlc_renderer_item_icon_uri (const vlc_renderer_item_t *p_item)
Get the icon uri of a renderer item.
const char * vlc_renderer_item_demux_filter (const vlc_renderer_item_t *p_item)
Get the demux filter to use with a renderer item.
int vlc_renderer_item_flags (const vlc_renderer_item_t *p_item)
Get the flags of a renderer item.
vlc_renderer_item_t * vlc_renderer_item_hold (vlc_renderer_item_t *p_item)
Hold a renderer item, i.e.
void vlc_renderer_item_release (vlc_renderer_item_t *p_item)
Releases a renderer item, i.e.
int vlc_rd_probe_add (vlc_probe_t *probe, const char *psz_name, const char *psz_longname)
Renderer Discovery proble helpers.
int vlc_rd_get_names (vlc_object_t *p_obj, char ***pppsz_names, char ***pppsz_longnames)
Return a list of renderer discovery modules.
void vlc_rd_release (vlc_renderer_discovery_t *p_rd)
vlc_renderer_discovery_t * vlc_rd_new (vlc_object_t *p_obj, const char *psz_name, const struct vlc_renderer_discovery_owner *restrict owner)
Function Documentation
item_free()
static void item_free (vlc_renderer_item_t * p_item) static
References vlc_renderer_item_t::psz_demux_filter, vlc_renderer_item_t::psz_icon_uri, vlc_renderer_item_t::psz_name, vlc_renderer_item_t::psz_sout, and vlc_renderer_item_t::psz_type.
Referenced by vlc_renderer_item_new(), and vlc_renderer_item_release().
vlc_rd_new()
vlc_renderer_discovery_t * vlc_rd_new (vlc_object_t * p_obj, const char * psz_name, const struct vlc_renderer_discovery_owner *restrict owner)
References config_ChainCreate(), config_ChainDestroy(), module_need, msg_Err, vlc_renderer_discovery_t::owner, vlc_renderer_discovery_t::p_cfg, vlc_renderer_discovery_t::p_module, psz_name, vlc_renderer_discovery_t::psz_name, vlc_custom_create, and vlc_object_release.