VLC: src/stream_output/sdp.c File Reference
sdp.c File Reference
Macros
#define MAXSDPADDRESS 47
Functions
static char * AddressToSDP (const struct sockaddr *addr, socklen_t addrlen, char *buf)
static bool IsSDPString (const char *str)
static void vsdp_AddAttribute (struct vlc_memstream *restrict stream, const char *name, const char *fmt, va_list ap)
void sdp_AddAttribute (struct vlc_memstream *restrict stream, const char *name, const char *fmt,...)
void sdp_AddMedia (struct vlc_memstream *restrict stream, const char *type, const char *proto, int dport, unsigned pt, bool bw_indep, unsigned bw, const char *ptname, unsigned clock, unsigned chans, const char *fmtp)
int vlc_sdp_Start (struct vlc_memstream *restrict stream, vlc_object_t *obj, const char *cfgpref, const struct sockaddr *src, size_t srclen, const struct sockaddr *addr, size_t addrlen)
Macro Definition Documentation
MAXSDPADDRESS
#define MAXSDPADDRESS 47
Referenced by AddressToSDP(), and vlc_sdp_Start().
Function Documentation
AddressToSDP()
static char * AddressToSDP (const struct sockaddr * addr, socklen_t addrlen, char * buf) static
References MAXSDPADDRESS, net_SockAddrIsMulticast(), and vlc_getnameinfo().
Referenced by vlc_sdp_Start().
IsSDPString()
static bool IsSDPString (const char * str) static
References IsUTF8().
Referenced by vlc_sdp_Start().
sdp_AddAttribute()
void sdp_AddAttribute (struct vlc_memstream *restrict stream, const char * name, const char * fmt, ...)
References name, and vsdp_AddAttribute().
sdp_AddMedia()
void sdp_AddMedia (struct vlc_memstream *restrict stream, const char * type, const char * proto, int dport, unsigned pt, bool bw_indep, unsigned bw, const char * ptname, unsigned clock, unsigned chans, const char * fmtp)
References vlc_memstream_printf(), and vlc_memstream_puts().
vlc_sdp_Start()
int vlc_sdp_Start (struct vlc_memstream *restrict stream, vlc_object_t * obj, const char * cfgpref, const struct sockaddr * src, size_t srclen, const struct sockaddr * addr, size_t addrlen)
References AddressToSDP(), IsSDPString(), MAXSDPADDRESS, NTPtime64(), var_GetNonEmptyString, vlc_memstream_close(), vlc_memstream_open(), vlc_memstream_printf(), and vlc_memstream_puts().
vsdp_AddAttribute()
static void vsdp_AddAttribute (struct vlc_memstream *restrict stream, const char * name, const char * fmt, va_list ap) static
References name, vlc_memstream_printf(), vlc_memstream_puts(), and vlc_memstream_vprintf().
Referenced by sdp_AddAttribute().