VLC: src/playlist/search.c File Reference
search.c File Reference
Functions
static void playlist_LiveSearchClean (playlist_item_t *p_root)
Enable all items in the playlist.
static bool playlist_LiveSearchUpdateInternal (playlist_item_t *p_root, const char *psz_string, bool b_recursive)
Enable/Disable items in the playlist according to the search argument.
int playlist_LiveSearchUpdate (playlist_t *p_playlist, playlist_item_t *p_root, const char *psz_string, bool b_recursive)
Launch the recursive search in the playlist.
Function Documentation
playlist_LiveSearchClean()
static void playlist_LiveSearchClean (playlist_item_t * p_root) static
Enable all items in the playlist.
Parameters
p_root the current root item
References playlist_item_t::i_children, playlist_item_t::i_flags, playlist_LiveSearchClean(), and playlist_item_t::pp_children.
Referenced by playlist_LiveSearchClean(), and playlist_LiveSearchUpdate().
playlist_LiveSearchUpdateInternal()
static bool playlist_LiveSearchUpdateInternal (playlist_item_t * p_root, const char * psz_string, bool b_recursive) static
Enable/Disable items in the playlist according to the search argument.
Parameters
p_root the current root item
psz_string the string to search
Returns
true if an item match
References playlist_item_t::i_children, playlist_item_t::i_flags, input_item_t::lock, playlist_item_t::p_input, input_item_t::p_meta, PLAYLIST_DBL_FLAG, playlist_LiveSearchUpdateInternal(), playlist_item_t::pp_children, input_item_t::psz_name, vlc_meta_Album, vlc_meta_Artist, vlc_meta_Get(), vlc_meta_Title, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_strcasestr().
Referenced by playlist_LiveSearchUpdate(), and playlist_LiveSearchUpdateInternal().