VLC: src/video_output/snapshot.h File Reference
snapshot.h File Reference
Data Structures
struct vout_snapshot_t
struct vout_snapshot_save_cfg_t
Functions
void vout_snapshot_Init (vout_snapshot_t *)
void vout_snapshot_Clean (vout_snapshot_t *)
void vout_snapshot_End (vout_snapshot_t *)
picture_t * vout_snapshot_Get (vout_snapshot_t *, mtime_t timeout)
bool vout_snapshot_IsRequested (vout_snapshot_t *)
It tells if they are pending snapshot request.
void vout_snapshot_Set (vout_snapshot_t *, const video_format_t *, picture_t *)
It set the picture used to create the snapshots.
char * vout_snapshot_GetDirectory (void)
This function will return the directory used for snapshots.
int vout_snapshot_SaveImage (char **name, int *sequential, const block_t *image, vout_thread_t *p_vout, const vout_snapshot_save_cfg_t *cfg)
This function will write an image to the disk an return the file name created.
Function Documentation
vout_snapshot_Clean()
void vout_snapshot_Clean (vout_snapshot_t * snap)
References vout_snapshot_t::lock, picture_t::p_next, vout_snapshot_t::picture, picture_Release(), vlc_cond_destroy(), vlc_mutex_destroy(), and vout_snapshot_t::wait.
Referenced by VoutDestructor().
vout_snapshot_End()
void vout_snapshot_End (vout_snapshot_t * snap)
References vout_snapshot_t::is_available, vout_snapshot_t::lock, vlc_cond_broadcast(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_snapshot_t::wait.
Referenced by vout_Close().
vout_snapshot_Get()
picture_t * vout_snapshot_Get (vout_snapshot_t * snap, mtime_t timeout)
References vout_snapshot_t::is_available, vout_snapshot_t::lock, mdate(), picture_t::p_next, vout_snapshot_t::picture, vout_snapshot_t::request_count, vlc_cond_timedwait(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_snapshot_t::wait.
Referenced by vout_GetSnapshot().
vout_snapshot_GetDirectory()
char * vout_snapshot_GetDirectory (void)
This function will return the directory used for snapshots.
References config_GetUserDir(), and VLC_PICTURES_DIR.
Referenced by VoutSaveSnapshot().
vout_snapshot_Init()
void vout_snapshot_Init (vout_snapshot_t * snap)
References vout_snapshot_t::is_available, vout_snapshot_t::lock, vout_snapshot_t::picture, vout_snapshot_t::request_count, vlc_cond_init(), vlc_mutex_init(), and vout_snapshot_t::wait.
Referenced by VoutCreate().
vout_snapshot_IsRequested()
bool vout_snapshot_IsRequested (vout_snapshot_t * snap)
It tells if they are pending snapshot request.
References vout_snapshot_t::lock, vout_snapshot_t::request_count, vlc_mutex_trylock(), and vlc_mutex_unlock().
Referenced by ThreadDisplayRenderPicture().
vout_snapshot_SaveImage()
int vout_snapshot_SaveImage (char ** name, int * sequential, const block_t * image, vout_thread_t * p_vout, const vout_snapshot_save_cfg_t * cfg)
This function will write an image to the disk an return the file name created.
< No error
< Unspecified error
References asprintf(), DIR_SEP, filename_sanitize(), vout_snapshot_save_cfg_t::format, gmtime_r(), block_t::i_buffer, vout_thread_sys_t::input, vout_snapshot_save_cfg_t::is_sequential, localtime_r(), msg_Err, name, vout_thread_t::p, block_t::p_buffer, vout_snapshot_save_cfg_t::path, vout_snapshot_save_cfg_t::prefix_fmt, vout_snapshot_save_cfg_t::sequence, str_format(), strdup(), TIME_UTC, timespec_get(), timespec::tv_nsec, timespec::tv_sec, VLC_EGENERIC, vlc_fopen(), vlc_stat(), and VLC_SUCCESS.
Referenced by VoutSaveSnapshot().
vout_snapshot_Set()
void vout_snapshot_Set (vout_snapshot_t * snap, const video_format_t * fmt, picture_t * picture)
It set the picture used to create the snapshots.
The given picture is cloned. If p_fmt is non NULL it will override the format of the p_picture (mainly used because of aspect/crop problems).
References picture_t::format, vout_snapshot_t::lock, picture_t::p_next, vout_snapshot_t::picture, picture_Clone(), vout_snapshot_t::request_count, video_format_CopyCrop(), vlc_cond_broadcast(), vlc_mutex_lock(), vlc_mutex_unlock(), and vout_snapshot_t::wait.
Referenced by ThreadDisplayRenderPicture().