VLC: src/playlist/sort.c File Reference
sort.c File Reference
Macros
#define VLC_INTERNAL_PLAYLIST_SORT_FUNCTIONS
#define SORTFN(SORT, first, second)
#define DEF(s)
#define DEF(a) { cmp_a_##a, cmp_d_##a },
Typedefs
typedef int(* sortfn_t) (const void *, const void *)
Return the comparison function appropriate for the SORT_* and ORDER_* arguments given, or NULL for SORT_RANDOM.
Functions
static int meta_strcasecmp_title (const playlist_item_t *first, const playlist_item_t *second)
Compare two items using their title or name.
static int meta_sort (const playlist_item_t *first, const playlist_item_t *second, vlc_meta_type_t meta, bool b_integer)
Compare two intems according to the given meta type.
static sortfn_t find_sorting_fn (unsigned i_mode, unsigned i_type)
static void playlist_ItemArraySort (unsigned i_items, playlist_item_t **pp_items, sortfn_t p_sortfn)
Sort an array of items recursively.
static int recursiveNodeSort (playlist_t *p_playlist, playlist_item_t *p_node, sortfn_t p_sortfn)
Sort a node recursively.
int playlist_RecursiveNodeSort (playlist_t *p_playlist, playlist_item_t *p_node, int i_mode, int i_type)
Sort a node recursively.
static int proto_SORT_TRACK_NUMBER (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_DISC_NUMBER (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_ALBUM (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_DATE (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_ARTIST (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_DESCRIPTION (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_DURATION (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_GENRE (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_ID (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_RATING (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_TITLE (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_TITLE_NODES_FIRST (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_TITLE_NUMERIC (const playlist_item_t *first, const playlist_item_t *second)
static int proto_SORT_URI (const playlist_item_t *first, const playlist_item_t *second)
Variables
static const sortfn_t sorting_fns [NUM_SORT_FNS][2]
Macro Definition Documentation
DEF [1/2]
#define DEF (a) { cmp_a_##a, cmp_d_##a },
DEF [2/2]
#define DEF (s)
Value:
    static int cmp_a_##s(const void *l,const void *r) \
    { return proto_##s(*(const playlist_item_t *const *)l, \
                           *(const playlist_item_t *const *)r); } \
    static int cmp_d_##s(const void *l,const void *r) \
    { return -1*proto_##s(*(const playlist_item_t * const *)l, \
                              *(const playlist_item_t * const *)r); }
SORTFN
#define SORTFN (SORT, first, second)
Value:
    static inline int proto_##SORT \
    ( const playlist_item_t *first, const playlist_item_t *second )
VLC_INTERNAL_PLAYLIST_SORT_FUNCTIONS
#define VLC_INTERNAL_PLAYLIST_SORT_FUNCTIONS
Typedef Documentation
sortfn_t
typedef int(* sortfn_t) (const void *, const void *)
Return the comparison function appropriate for the SORT_* and ORDER_* arguments given, or NULL for SORT_RANDOM.
Parameters
i_mode a SORT_* enum indicating the field to sort on
i_type ORDER_NORMAL or ORDER_REVERSE
Returns
function pointer, or NULL for SORT_RANDOM or invalid input
Function Documentation
find_sorting_fn()
static sortfn_t find_sorting_fn (unsigned i_mode, unsigned i_type) inline static
References i_type, NUM_SORT_FNS, and sorting_fns.
Referenced by playlist_RecursiveNodeSort().
meta_sort()
static int meta_sort (const playlist_item_t * first, const playlist_item_t * second, vlc_meta_type_t meta, bool b_integer) inline static
Compare two intems according to the given meta type.
Parameters
first the first item
second the second item
meta the meta type to use to sort the items
b_integer true if the meta are integers
Returns
-1, 0 or 1 like strcmp
References playlist_item_t::i_children, input_item_GetMeta(), meta_strcasecmp_title(), playlist_item_t::p_input, and strcasecmp().
Referenced by proto_SORT_ALBUM(), proto_SORT_ARTIST(), proto_SORT_DATE(), proto_SORT_DESCRIPTION(), proto_SORT_DISC_NUMBER(), proto_SORT_GENRE(), proto_SORT_RATING(), and proto_SORT_TRACK_NUMBER().
meta_strcasecmp_title()
static int meta_strcasecmp_title (const playlist_item_t * first, const playlist_item_t * second) inline static
Compare two items using their title or name.
Parameters
first the first item
second the second item
Returns
-1, 0 or 1 like strcmp
References input_item_GetTitleFbName(), playlist_item_t::p_input, and strcasecmp().
Referenced by meta_sort(), proto_SORT_TITLE(), and proto_SORT_TITLE_NODES_FIRST().
playlist_ItemArraySort()
static void playlist_ItemArraySort (unsigned i_items, playlist_item_t ** pp_items, sortfn_t p_sortfn) inline static
Sort an array of items recursively.
Parameters
i_items number of items
pp_items the array of items
p_sortfn the sorting function
Returns
nothing
References vlc_mrand48().
Referenced by recursiveNodeSort().
proto_SORT_ALBUM()
static int proto_SORT_ALBUM (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), proto_SORT_DISC_NUMBER(), and vlc_meta_Album.
Referenced by proto_SORT_DATE().
proto_SORT_ARTIST()
static int proto_SORT_ARTIST (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), proto_SORT_DATE(), and vlc_meta_Artist.
proto_SORT_DATE()
static int proto_SORT_DATE (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), proto_SORT_ALBUM(), and vlc_meta_Date.
Referenced by proto_SORT_ARTIST().
proto_SORT_DESCRIPTION()
static int proto_SORT_DESCRIPTION (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), and vlc_meta_Description.
proto_SORT_DISC_NUMBER()
static int proto_SORT_DISC_NUMBER (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), proto_SORT_TRACK_NUMBER(), and vlc_meta_DiscNumber.
Referenced by proto_SORT_ALBUM().
proto_SORT_DURATION()
static int proto_SORT_DURATION (const playlist_item_t * first, const playlist_item_t * second) inline static
References input_item_GetDuration().
proto_SORT_GENRE()
static int proto_SORT_GENRE (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), and vlc_meta_Genre.
proto_SORT_ID()
static int proto_SORT_ID (const playlist_item_t * first, const playlist_item_t * second) inline static
proto_SORT_RATING()
static int proto_SORT_RATING (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), and vlc_meta_Rating.
proto_SORT_TITLE()
static int proto_SORT_TITLE (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_strcasecmp_title().
proto_SORT_TITLE_NODES_FIRST()
static int proto_SORT_TITLE_NODES_FIRST (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_strcasecmp_title().
proto_SORT_TITLE_NUMERIC()
static int proto_SORT_TITLE_NUMERIC (const playlist_item_t * first, const playlist_item_t * second) inline static
References input_item_GetTitleFbName().
proto_SORT_TRACK_NUMBER()
static int proto_SORT_TRACK_NUMBER (const playlist_item_t * first, const playlist_item_t * second) inline static
References meta_sort(), and vlc_meta_TrackNumber.
Referenced by proto_SORT_DISC_NUMBER().
proto_SORT_URI()
static int proto_SORT_URI (const playlist_item_t * first, const playlist_item_t * second) inline static
References input_item_GetURI(), and strcasecmp().
recursiveNodeSort()
static int recursiveNodeSort (playlist_t * p_playlist, playlist_item_t * p_node, sortfn_t p_sortfn) static
Sort a node recursively.
This function must be entered with the playlist lock !
Parameters
p_playlist the playlist
p_node the node to sort
p_sortfn the sorting function
Returns
VLC_SUCCESS on success
< No error
References playlist_item_t::i_children, playlist_ItemArraySort(), playlist_item_t::pp_children, recursiveNodeSort(), and VLC_SUCCESS.
Referenced by playlist_RecursiveNodeSort(), and recursiveNodeSort().
Variable Documentation
sorting_fns
static VLC_DEFINE_SORT_FUNCTIONS const sortfn_t sorting_fns static
Initial value:
=
#define DEF(a)
{ VLC_DEFINE_SORT_FUNCTIONS }
Referenced by find_sorting_fn().