VLC: src/input/access.c File Reference
access.c File Reference
Macros
#define MAX_REDIR 5
Functions
char * get_path (const char *location)
static void vlc_access_Destroy (stream_t *access)
static stream_t * access_New (vlc_object_t *parent, input_thread_t *input, bool preparsing, const char *mrl)
stream_t * vlc_access_NewMRL (vlc_object_t *parent, const char *mrl)
Opens a new read-only byte stream.
int access_vaDirectoryControlHelper (stream_t *p_access, int i_query, va_list args)
Default pf_control callback for directory accesses.
static int AStreamNoReadDir (stream_t *s, input_item_node_t *p_node)
static block_t * AStreamReadBlock (stream_t *s, bool *restrict eof)
static ssize_t AStreamReadStream (stream_t *s, void *buf, size_t len)
static int AStreamReadDir (stream_t *s, input_item_node_t *p_node)
static int AStreamSeek (stream_t *s, uint64_t offset)
static int AStreamControl (stream_t *s, int cmd, va_list args)
static void AStreamDestroy (stream_t *s)
stream_t * stream_AccessNew (vlc_object_t *parent, input_thread_t *input, bool preparsing, const char *url)
This function creates a raw stream_t from an URL.
Macro Definition Documentation
MAX_REDIR
#define MAX_REDIR 5
Referenced by access_New().
Function Documentation
access_New()
static stream_t * access_New (vlc_object_t * parent, input_thread_t * input, bool preparsing, const char * mrl) static
References stream_t::b_preparsing, get_path(), MAX_REDIR, module_need, msg_Dbg, msg_Err, p, stream_t::p_input, stream_t::p_module, stream_t::pf_control, stream_t::psz_filepath, stream_t::psz_location, stream_t::psz_name, stream_t::psz_url, strdup(), stream_CommonDelete(), strndup(), unlikely, vlc_access_Destroy(), and vlc_stream_CommonNew().
Referenced by stream_AccessNew(), and vlc_access_NewMRL().
AStreamControl()
static int AStreamControl (stream_t * s, int cmd, va_list args) static
References stream_t::p_sys, and vlc_stream_vaControl().
Referenced by stream_AccessNew().
AStreamDestroy()
static void AStreamDestroy (stream_t * s) static
References stream_t::p_sys, and vlc_stream_Delete().
Referenced by stream_AccessNew().
AStreamNoReadDir()
static int AStreamNoReadDir (stream_t * s, input_item_node_t * p_node) static
< Unspecified error
References VLC_EGENERIC.
Referenced by stream_AccessNew().
AStreamReadBlock()
static block_t * AStreamReadBlock (stream_t * s, bool *restrict eof) static
References input_thread_private_t::counters_lock, block_t::i_buffer, input_priv(), stream_t::p_input, input_thread_private_t::p_input_bitrate, input_thread_private_t::p_read_bytes, input_thread_private_t::p_read_packets, stream_t::p_sys, stats_Update(), vlc_killed(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_stream_Eof(), and vlc_stream_ReadBlock().
Referenced by stream_AccessNew().
AStreamReadDir()
static int AStreamReadDir (stream_t * s, input_item_node_t * p_node) static
References stream_t::p_sys, and stream_t::pf_readdir.
Referenced by stream_AccessNew().
AStreamReadStream()
static ssize_t AStreamReadStream (stream_t * s, void * buf, size_t len) static
References input_thread_private_t::counters_lock, input_priv(), stream_t::p_input, input_thread_private_t::p_input_bitrate, input_thread_private_t::p_read_bytes, input_thread_private_t::p_read_packets, stream_t::p_sys, stats_Update(), vlc_killed(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_stream_Eof(), and vlc_stream_ReadPartial().
Referenced by stream_AccessNew().
AStreamSeek()
static int AStreamSeek (stream_t * s, uint64_t offset) static
References stream_t::p_sys, and vlc_stream_Seek().
Referenced by stream_AccessNew().
get_path()
char * get_path (const char * location)
References asprintf(), and vlc_uri2path().
Referenced by access_New(), demux_NewAdvanced(), and InputGetExtraFilesPattern().
stream_AccessNew()
stream_t * stream_AccessNew (vlc_object_t * parent, input_thread_t * input, bool preparsing, const char * url)
This function creates a raw stream_t from an URL.
References access_New(), AStreamControl(), AStreamDestroy(), AStreamNoReadDir(), AStreamReadBlock(), AStreamReadDir(), AStreamReadStream(), AStreamSeek(), stream_t::p_input, stream_t::p_sys, stream_t::pf_block, stream_t::pf_control, stream_t::pf_read, stream_t::pf_readdir, stream_t::pf_seek, stream_t::psz_url, strdup(), stream_CommonDelete(), stream_FilterAutoNew(), stream_FilterChainNew(), unlikely, VLC_OBJECT, and vlc_stream_CommonNew().
Referenced by InputDemuxNew(), and vlc_stream_NewURL().
vlc_access_Destroy()
static void vlc_access_Destroy (stream_t * access) static
References module_unneed, stream_t::p_module, stream_t::psz_filepath, and stream_t::psz_name.
Referenced by access_New().