VLC: src/config/file.c File Reference
file.c File Reference
Functions
static char * strdupnull (const char *src)
static char * config_GetConfigFile (vlc_object_t *obj)
Get the user's configuration file.
static FILE * config_OpenConfigFile (vlc_object_t *p_obj)
static int64_t vlc_strtoi (const char *str)
int config_LoadConfigFile (vlc_object_t *p_this)
int config_CreateDir (vlc_object_t *p_this, const char *psz_dirname)
static int config_Write (FILE *file, const char *desc, const char *type, bool comment, const char *name, const char *fmt,...)
static int config_PrepareDir (vlc_object_t *obj)
int config_SaveConfigFile (vlc_object_t *p_this)
Saves the in-memory configuration into a file.
int config_AutoSaveConfigFile (vlc_object_t *p_this)
Function Documentation
config_AutoSaveConfigFile()
int config_AutoSaveConfigFile (vlc_object_t * p_this)
References config_dirty, config_lock, config_SaveConfigFile, vlc_rwlock_rdlock(), and vlc_rwlock_unlock().
Referenced by libvlc_InternalCleanup().
config_CreateDir()
int config_CreateDir (vlc_object_t * p_this, const char * psz_dirname)
References config_CreateDir(), DIR_SEP_CHAR, msg_Warn, vlc_mkdir(), and vlc_strerror_c().
Referenced by config_CreateDir(), config_PrepareDir(), and playlist_MLDump().
config_GetConfigFile()
static char * config_GetConfigFile (vlc_object_t * obj) static
Get the user's configuration file.
References asprintf(), CONFIG_FILE, config_GetUserDir(), DIR_SEP, var_CreateGetNonEmptyString, var_Destroy, and VLC_CONFIG_DIR.
Referenced by config_OpenConfigFile(), and config_SaveConfigFile().
config_LoadConfigFile()
int config_LoadConfigFile (vlc_object_t * p_this)
< Unspecified error
References atof(), CONFIG_CLASS, config_FindConfig(), CONFIG_ITEM_BOOL, CONFIG_ITEM_FLOAT, CONFIG_ITEM_INTEGER, config_lock, config_OpenConfigFile(), module_value_t::f, freelocale(), getline(), module_value_t::i, module_config_t::i_type, LC_NUMERIC_MASK, module_config_t::max, msg_Err, msg_Warn, newlocale(), module_value_t::psz, rewind(), strdupnull(), uselocale(), module_config_t::value, VLC_EGENERIC, vlc_rwlock_unlock(), vlc_rwlock_wrlock(), vlc_strerror_c(), and vlc_strtoi().
config_OpenConfigFile()
static FILE * config_OpenConfigFile (vlc_object_t * p_obj) static
References asprintf(), CONFIG_FILE, config_GetConfigFile(), config_GetUserDir(), msg_Dbg, msg_Err, msg_Info, vlc_fopen(), VLC_HOME_DIR, and vlc_strerror_c().
Referenced by config_LoadConfigFile().
config_PrepareDir()
static int config_PrepareDir (vlc_object_t * obj) static
References config_CreateDir(), config_GetUserDir(), and VLC_CONFIG_DIR.
Referenced by config_SaveConfigFile().
config_SaveConfigFile()
int config_SaveConfigFile (vlc_object_t * p_this)
Saves the in-memory configuration into a file.
Returns
0 on success, -1 on error.
References asprintf(), module_config_t::b_removed, module_config_t::b_unsaveable, CONFIG_CLASS, config_GetConfigFile(), CONFIG_ITEM, CONFIG_ITEM_BOOL, config_lock, config_PrepareDir(), config_Write(), module_value_t::f, freelocale(), getpid(), module_value_t::i, module_config_t::i_type, IsConfigFloatType, IsConfigIntegerType, IsConfigStringType, LC_NUMERIC_MASK, lock, module_get_object(), msg_Err, N_, newlocale(), vlc_plugin_t::next, module_config_t::orig, p, module_value_t::psz, module_t::psz_longname, module_config_t::psz_name, module_config_t::psz_text, psz_value, uselocale(), module_config_t::value, vlc_close(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_open(), vlc_plugins, vlc_rename(), vlc_rwlock_rdlock(), vlc_rwlock_unlock(), VLC_STATIC_MUTEX, vlc_strerror_c(), and vlc_unlink().
config_Write()
static int config_Write (FILE * file, const char * desc, const char * type, bool comment, const char * name, const char * fmt, ...) static
References name, and vlc_gettext().
Referenced by config_SaveConfigFile().
strdupnull()
static char * strdupnull (const char * src) inline static
References strdup().
Referenced by config_LoadConfigFile().
vlc_strtoi()
static int64_t vlc_strtoi (const char * str) static
References strtoll().
Referenced by config_LoadConfigFile().