VLC: src/input/resource.c File Reference
resource.c File Reference
Data Structures
struct input_resource_t
Functions
static void DestroySout (input_resource_t *p_resource)
static sout_instance_t * RequestSout (input_resource_t *p_resource, sout_instance_t *p_sout, const char *psz_sout)
static void DestroyVout (input_resource_t *p_resource)
static void DisplayVoutTitle (input_resource_t *p_resource, vout_thread_t *p_vout)
static vout_thread_t * RequestVout (input_resource_t *p_resource, vout_thread_t *p_vout, const video_format_t *p_fmt, unsigned dpb_size, bool b_recycle)
static vout_thread_t * HoldVout (input_resource_t *p_resource)
static void HoldVouts (input_resource_t *p_resource, vout_thread_t ***ppp_vout, size_t *pi_vout)
audio_output_t * input_resource_GetAout (input_resource_t *p_resource)
This function creates or recycles an audio output.
void input_resource_PutAout (input_resource_t *p_resource, audio_output_t *p_aout)
This function retains or destroys an audio output.
audio_output_t * input_resource_HoldAout (input_resource_t *p_resource)
void input_resource_ResetAout (input_resource_t *p_resource)
Prevents the existing audio output (if any) from being recycled.
input_resource_t * input_resource_New (vlc_object_t *p_parent)
It creates an empty input resource handler.
void input_resource_Release (input_resource_t *p_resource)
It releases an input resource.
input_resource_t * input_resource_Hold (input_resource_t *p_resource)
This function holds the input_resource_t itself.
void input_resource_SetInput (input_resource_t *p_resource, input_thread_t *p_input)
This function set the associated input.
vout_thread_t * input_resource_RequestVout (input_resource_t *p_resource, vout_thread_t *p_vout, const video_format_t *p_fmt, unsigned dpb_size, bool b_recycle)
This function handles vout request.
vout_thread_t * input_resource_HoldVout (input_resource_t *p_resource)
This function returns one of the current vout if any.
void input_resource_HoldVouts (input_resource_t *p_resource, vout_thread_t ***ppp_vout, size_t *pi_vout)
This function returns all current vouts if any.
void input_resource_TerminateVout (input_resource_t *p_resource)
Forcefully destroys the video output (e.g.
bool input_resource_HasVout (input_resource_t *p_resource)
This function return true if there is at least one vout in the resources.
sout_instance_t * input_resource_RequestSout (input_resource_t *p_resource, sout_instance_t *p_sout, const char *psz_sout)
This function handles sout request.
void input_resource_TerminateSout (input_resource_t *p_resource)
This function deletes the current sout in the resources.
void input_resource_Terminate (input_resource_t *p_resource)
This function releases all resources (object).
Function Documentation
DestroySout()
static void DestroySout (input_resource_t * p_resource) static
References input_resource_t::p_sout, and sout_DeleteInstance().
Referenced by input_resource_Release(), and RequestSout().
DestroyVout()
static void DestroyVout (input_resource_t * p_resource) static
References input_resource_t::i_vout, input_resource_t::p_vout_free, and vout_CloseAndRelease().
Referenced by input_resource_Release().
DisplayVoutTitle()
static void DisplayVoutTitle (input_resource_t * p_resource, vout_thread_t * p_vout) static
References asprintf(), input_GetItem(), input_item_GetArtist(), input_item_GetName(), input_item_GetNowPlayingFb(), input_item_GetTitle(), input_resource_t::p_input, psz_name, and vout_DisplayTitle().
Referenced by RequestVout().
HoldVout()
static vout_thread_t * HoldVout (input_resource_t * p_resource) static
References input_resource_t::i_vout, input_resource_t::lock_hold, input_resource_t::pp_vout, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_hold.
Referenced by input_resource_HoldVout().
HoldVouts()
static void HoldVouts (input_resource_t * p_resource, vout_thread_t *** ppp_vout, size_t * pi_vout) static
References input_resource_t::i_vout, input_resource_t::lock_hold, input_resource_t::pp_vout, vlc_alloc(), vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_hold.
Referenced by input_resource_HoldVouts().
input_resource_GetAout()
audio_output_t * input_resource_GetAout (input_resource_t * p_resource)
This function creates or recycles an audio output.
References aout_New, input_resource_t::b_aout_busy, input_resource_t::lock_hold, msg_Dbg, input_resource_t::p_aout, input_resource_t::p_parent, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by aout_update_format(), and playlist_Create().
input_resource_HasVout()
bool input_resource_HasVout (input_resource_t * p_resource)
This function return true if there is at least one vout in the resources.
It can only be called on detached resources.
References input_resource_t::lock, input_resource_t::p_input, input_resource_t::p_vout_free, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Thread().
input_resource_Hold()
input_resource_t * input_resource_Hold (input_resource_t * p_resource)
This function holds the input_resource_t itself.
References input_resource_t::refs.
Referenced by Create().
input_resource_HoldAout()
audio_output_t * input_resource_HoldAout (input_resource_t * p_resource)
Returns
the current audio output if any. Use vlc_object_release() to drop the reference.
References input_resource_t::lock_hold, input_resource_t::p_aout, vlc_mutex_lock(), vlc_mutex_unlock(), and vlc_object_hold.
Referenced by ControlNav(), input_vaControl(), playlist_GetAout(), and ViewpointApply().
input_resource_HoldVout()
vout_thread_t * input_resource_HoldVout (input_resource_t * p_resource)
This function returns one of the current vout if any.
You must call vlc_object_release on the value returned (if non NULL).
References HoldVout().
Referenced by DecoderProcessFlush(), DecoderQueueSpu(), DeleteDecoder(), and spu_new_buffer().
input_resource_HoldVouts()
void input_resource_HoldVouts (input_resource_t * p_resource, vout_thread_t *** ppp_vout, size_t * pi_vout)
This function returns all current vouts if any.
You must call vlc_object_release on all values returned (if non NULL).
References HoldVouts().
Referenced by ControlNav(), input_vaControl(), and ViewpointApply().
input_resource_New()
input_resource_t * input_resource_New (vlc_object_t * p_parent)
It creates an empty input resource handler.
The given object MUST stay alive as long as the input_resource_t is not deleted.
References input_resource_t::lock, input_resource_t::lock_hold, input_resource_t::p_parent, input_resource_t::refs, and vlc_mutex_init().
Referenced by Create(), playlist_Create(), and vlm_MediaInstanceNew().
input_resource_PutAout()
void input_resource_PutAout (input_resource_t * p_resource, audio_output_t * p_aout)
This function retains or destroys an audio output.
References aout_Destroy(), input_resource_t::b_aout_busy, input_resource_t::lock_hold, msg_Dbg, input_resource_t::p_aout, input_resource_t::p_parent, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by aout_update_format(), DeleteDecoder(), playlist_Create(), and ReloadDecoder().
input_resource_Release()
void input_resource_Release (input_resource_t * p_resource)
It releases an input resource.
References aout_Destroy(), DestroySout(), DestroyVout(), input_resource_t::lock, input_resource_t::lock_hold, input_resource_t::p_aout, input_resource_t::refs, and vlc_mutex_destroy().
Referenced by input_Destructor(), playlist_Destroy(), and vlm_MediaInstanceDelete().
input_resource_RequestSout()
sout_instance_t * input_resource_RequestSout (input_resource_t * p_resource, sout_instance_t * p_sout, const char * psz_sout)
This function handles sout request.
References input_resource_t::lock, RequestSout(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by End(), Init(), and input_resource_TerminateSout().
input_resource_RequestVout()
vout_thread_t * input_resource_RequestVout (input_resource_t * p_resource, vout_thread_t * p_vout, const video_format_t * p_fmt, unsigned dpb_size, bool b_recycle)
This function handles vout request.
References input_resource_t::lock, RequestVout(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by aout_request_vout(), DeleteDecoder(), input_resource_TerminateVout(), and vout_update_format().
input_resource_ResetAout()
void input_resource_ResetAout (input_resource_t * p_resource)
Prevents the existing audio output (if any) from being recycled.
References aout_Destroy(), input_resource_t::b_aout_busy, input_resource_t::lock_hold, input_resource_t::p_aout, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_resource_Terminate().
input_resource_SetInput()
void input_resource_SetInput (input_resource_t * p_resource, input_thread_t * p_input)
This function set the associated input.
References input_resource_t::i_vout, input_resource_t::lock, input_resource_t::p_input, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Create(), End(), and Init().
input_resource_Terminate()
void input_resource_Terminate (input_resource_t * p_resource)
This function releases all resources (object).
References input_resource_ResetAout(), input_resource_TerminateSout(), and input_resource_TerminateVout().
Referenced by End(), Init(), Thread(), and vlm_MediaInstanceDelete().
input_resource_TerminateSout()
void input_resource_TerminateSout (input_resource_t * p_resource)
This function deletes the current sout in the resources.
References input_resource_RequestSout().
Referenced by input_resource_Terminate(), LoopInput(), and vlm_ControlMediaInstanceStart().
input_resource_TerminateVout()
void input_resource_TerminateVout (input_resource_t * p_resource)
Forcefully destroys the video output (e.g.
when the playlist is stopped).
References input_resource_RequestVout().
Referenced by Control(), EsOutControlLocked(), EsOutDecodersStopBuffering(), input_resource_Terminate(), Thread(), and vlm_ControlMediaInstanceStart().
RequestSout()
static sout_instance_t * RequestSout (input_resource_t * p_resource, sout_instance_t * p_sout, const char * psz_sout) static
References DestroySout(), msg_Dbg, input_resource_t::p_parent, input_resource_t::p_sout, sout_instance_t::psz_sout, sout_NewInstance, and VLC_UNUSED.
Referenced by input_resource_RequestSout().
RequestVout()
static vout_thread_t * RequestVout (input_resource_t * p_resource, vout_thread_t * p_vout, const video_format_t * p_fmt, unsigned dpb_size, bool b_recycle) static
References DisplayVoutTitle(), input_resource_t::i_vout, input_Control(), INPUT_SET_INITIAL_VIEWPOINT, input_resource_t::lock, input_resource_t::lock_hold, msg_Dbg, input_resource_t::p_input, input_resource_t::p_parent, input_resource_t::p_vout_free, video_format_t::pose, input_resource_t::pp_vout, TAB_APPEND, TAB_REMOVE, vlc_assert_locked(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, vout_configuration_t::vout, vout_CloseAndRelease(), vout_Flush(), vout_FlushSubpictureChannel(), and vout_Request.
Referenced by input_resource_RequestVout().