VLC: src/input/resource.h File Reference
resource.h File Reference
Functions
void input_resource_SetInput (input_resource_t *, input_thread_t *)
This function set the associated input.
sout_instance_t * input_resource_RequestSout (input_resource_t *, sout_instance_t *, const char *psz_sout)
This function handles sout request.
vout_thread_t * input_resource_RequestVout (input_resource_t *, vout_thread_t *, const video_format_t *, unsigned dpb_size, bool b_recycle)
This function handles vout request.
vout_thread_t * input_resource_HoldVout (input_resource_t *)
This function returns one of the current vout if any.
void input_resource_HoldVouts (input_resource_t *, vout_thread_t ***, size_t *)
This function returns all current vouts if any.
void input_resource_Terminate (input_resource_t *)
This function releases all resources (object).
input_resource_t * input_resource_Hold (input_resource_t *)
This function holds the input_resource_t itself.
Function Documentation
input_resource_Hold()
input_resource_t * input_resource_Hold (input_resource_t * p_resource)
This function holds the input_resource_t itself.
References input_resource_t::refs.
Referenced by Create().
input_resource_HoldVout()
vout_thread_t * input_resource_HoldVout (input_resource_t * p_resource)
This function returns one of the current vout if any.
You must call vlc_object_release on the value returned (if non NULL).
References HoldVout().
Referenced by DecoderProcessFlush(), DecoderQueueSpu(), DeleteDecoder(), and spu_new_buffer().
input_resource_HoldVouts()
void input_resource_HoldVouts (input_resource_t * p_resource, vout_thread_t *** ppp_vout, size_t * pi_vout)
This function returns all current vouts if any.
You must call vlc_object_release on all values returned (if non NULL).
References HoldVouts().
Referenced by ControlNav(), input_vaControl(), and ViewpointApply().
input_resource_RequestSout()
sout_instance_t * input_resource_RequestSout (input_resource_t * p_resource, sout_instance_t * p_sout, const char * psz_sout)
This function handles sout request.
References input_resource_t::lock, RequestSout(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by End(), Init(), and input_resource_TerminateSout().
input_resource_RequestVout()
vout_thread_t * input_resource_RequestVout (input_resource_t * p_resource, vout_thread_t * p_vout, const video_format_t * p_fmt, unsigned dpb_size, bool b_recycle)
This function handles vout request.
References input_resource_t::lock, RequestVout(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by aout_request_vout(), DeleteDecoder(), input_resource_TerminateVout(), and vout_update_format().
input_resource_SetInput()
void input_resource_SetInput (input_resource_t * p_resource, input_thread_t * p_input)
This function set the associated input.
References input_resource_t::i_vout, input_resource_t::lock, input_resource_t::p_input, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by Create(), End(), and Init().
input_resource_Terminate()
void input_resource_Terminate (input_resource_t * p_resource)
This function releases all resources (object).