VLC: src/video_output/statistic.h File Reference
statistic.h File Reference
Data Structures
struct vout_statistic_t
Functions
static void vout_statistic_Init (vout_statistic_t *stat)
static void vout_statistic_Clean (vout_statistic_t *stat)
static void vout_statistic_GetReset (vout_statistic_t *stat, unsigned *restrict displayed, unsigned *restrict lost)
static void vout_statistic_AddDisplayed (vout_statistic_t *stat, int displayed)
static void vout_statistic_AddLost (vout_statistic_t *stat, int lost)
Function Documentation
vout_statistic_AddDisplayed()
static void vout_statistic_AddDisplayed (vout_statistic_t * stat, int displayed) inline static
References vout_statistic_t::displayed.
Referenced by ThreadDisplayRenderPicture().
vout_statistic_AddLost()
static void vout_statistic_AddLost (vout_statistic_t * stat, int lost) inline static
References vout_statistic_t::lost.
Referenced by ThreadDisplayPreparePicture().
vout_statistic_Clean()
static void vout_statistic_Clean (vout_statistic_t * stat) inline static
Referenced by VoutDestructor().
vout_statistic_GetReset()
static void vout_statistic_GetReset (vout_statistic_t * stat, unsigned *restrict displayed, unsigned *restrict lost) inline static
References vout_statistic_t::displayed, and vout_statistic_t::lost.
Referenced by vout_GetResetStatistic().
vout_statistic_Init()
static void vout_statistic_Init (vout_statistic_t * stat) inline static
References vout_statistic_t::displayed, and vout_statistic_t::lost.
Referenced by VoutCreate().