VLC: src/input/stats.c File Reference
stats.c File Reference
Functions
counter_t * stats_CounterCreate (int i_compute_type)
Create a statistics counter.
static int64_t stats_GetTotal (const counter_t *counter)
static float stats_GetRate (const counter_t *counter)
input_stats_t * stats_NewInputStats (input_thread_t *p_input)
void stats_ComputeInputStats (input_thread_t *input, input_stats_t *st)
void stats_ReinitInputStats (input_stats_t *p_stats)
void stats_CounterClean (counter_t *p_c)
void stats_Update (counter_t *p_counter, uint64_t val, uint64_t *new_val)
Update a counter element with new values.
Function Documentation
stats_ComputeInputStats()
void stats_ComputeInputStats (input_thread_t * input, input_stats_t * st)
References input_thread_private_t::counters, input_thread_private_t::counters_lock, input_stats_t::f_demux_bitrate, input_stats_t::f_input_bitrate, input_stats_t::f_send_bitrate, input_stats_t::i_decoded_audio, input_stats_t::i_decoded_video, input_stats_t::i_demux_corrupted, input_stats_t::i_demux_discontinuity, input_stats_t::i_demux_read_bytes, input_stats_t::i_displayed_pictures, input_stats_t::i_lost_abuffers, input_stats_t::i_lost_pictures, input_stats_t::i_played_abuffers, input_stats_t::i_read_bytes, input_stats_t::i_read_packets, input_stats_t::i_sent_bytes, input_stats_t::i_sent_packets, input_priv(), libvlc_stats, input_stats_t::lock, input_thread_private_t::p_decoded_audio, input_thread_private_t::p_decoded_video, input_thread_private_t::p_demux_bitrate, input_thread_private_t::p_demux_corrupted, input_thread_private_t::p_demux_discontinuity, input_thread_private_t::p_demux_read, input_thread_private_t::p_displayed_pictures, input_thread_private_t::p_input_bitrate, input_thread_private_t::p_lost_abuffers, input_thread_private_t::p_lost_pictures, input_thread_private_t::p_played_abuffers, input_thread_private_t::p_read_bytes, input_thread_private_t::p_read_packets, input_thread_private_t::p_sout_send_bitrate, input_thread_private_t::p_sout_sent_bytes, input_thread_private_t::p_sout_sent_packets, stats_GetRate(), stats_GetTotal(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by End(), and MainLoopStatistics().
stats_CounterClean()
void stats_CounterClean (counter_t * p_c)
References counter_t::i_samples, counter_t::pp_samples, and TAB_CLEAN.
stats_CounterCreate()
counter_t * stats_CounterCreate (int i_compute_type)
Create a statistics counter.
Parameters
i_compute_type the aggregation type. One of STATS_LAST (always keep the last value), STATS_COUNTER (increment by the passed value), STATS_MAX (keep the maximum passed value), STATS_MIN, or STATS_DERIVATIVE (keep a time derivative of the value)
References counter_t::i_compute_type, counter_t::i_samples, counter_t::last_update, and counter_t::pp_samples.
stats_GetRate()
static float stats_GetRate (const counter_t * counter) inline static
References counter_sample_t::date, counter_t::i_samples, counter_t::pp_samples, and counter_sample_t::value.
Referenced by stats_ComputeInputStats().
stats_GetTotal()
static int64_t stats_GetTotal (const counter_t * counter) inline static
References counter_t::i_samples, counter_t::pp_samples, and counter_sample_t::value.
Referenced by stats_ComputeInputStats().
stats_NewInputStats()
input_stats_t * stats_NewInputStats (input_thread_t * p_input)
References input_stats_t::lock, stats_ReinitInputStats(), and vlc_mutex_init().
Referenced by Create().
stats_ReinitInputStats()
void stats_ReinitInputStats (input_stats_t * p_stats)
References input_stats_t::f_average_demux_bitrate, input_stats_t::f_average_input_bitrate, input_stats_t::f_demux_bitrate, input_stats_t::f_input_bitrate, input_stats_t::f_send_bitrate, input_stats_t::i_decoded_audio, input_stats_t::i_decoded_video, input_stats_t::i_demux_corrupted, input_stats_t::i_demux_discontinuity, input_stats_t::i_demux_read_bytes, input_stats_t::i_demux_read_packets, input_stats_t::i_displayed_pictures, input_stats_t::i_lost_abuffers, input_stats_t::i_lost_pictures, input_stats_t::i_played_abuffers, input_stats_t::i_read_bytes, input_stats_t::i_read_packets, input_stats_t::i_sent_bytes, input_stats_t::i_sent_packets, input_stats_t::lock, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by stats_NewInputStats().
stats_Update()
void stats_Update (counter_t * p_counter, uint64_t val, uint64_t * new_val)
Update a counter element with new values.
Parameters
p_counter the counter to update
val the vlc_value union containing the new value to aggregate. For more information on how data is aggregated,
See also
stats_Create
Parameters
val_new a pointer that will be filled with new data
References CLOCK_FREQ, counter_sample_t::date, counter_t::i_compute_type, counter_t::i_samples, counter_t::last_update, mdate(), counter_t::pp_samples, STATS_COUNTER, STATS_DERIVATIVE, TAB_APPEND, TAB_ERASE, TAB_INSERT, unlikely, and counter_sample_t::value.
Referenced by AStreamReadBlock(), AStreamReadStream(), DecoderQueueSpu(), DecoderUpdateStatAudio(), DecoderUpdateStatVideo(), EsOutSend(), and input_UpdateStatistic().