VLC: src/input/stream_memory.c File Reference
stream_memory.c File Reference
Data Structures
struct stream_sys_t
Functions
static ssize_t Read (stream_t *, void *p_read, size_t i_read)
static int Seek (stream_t *, uint64_t)
static int Control (stream_t *, int i_query, va_list)
static void stream_MemoryPreserveDelete (stream_t *s)
static void stream_MemoryDelete (stream_t *s)
stream_t * vlc_stream_MemoryNew (vlc_object_t *p_this, uint8_t *p_buffer, size_t i_size, bool preserve)
Create a stream from a memory buffer.
Function Documentation
Control()
static int Control (stream_t * s, int i_query, va_list args) static
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References stream_sys_t::i_size, msg_Err, stream_t::p_sys, STREAM_CAN_CONTROL_PACE, STREAM_CAN_FASTSEEK, STREAM_CAN_PAUSE, STREAM_CAN_SEEK, STREAM_GET_CONTENT_TYPE, STREAM_GET_META, STREAM_GET_PRIVATE_ID_STATE, STREAM_GET_PTS_DELAY, STREAM_GET_SEEKPOINT, STREAM_GET_SIGNAL, STREAM_GET_SIZE, STREAM_GET_TITLE, STREAM_GET_TITLE_INFO, STREAM_SET_PAUSE_STATE, STREAM_SET_PRIVATE_ID_CA, STREAM_SET_PRIVATE_ID_STATE, STREAM_SET_SEEKPOINT, STREAM_SET_TITLE, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by vlc_stream_MemoryNew().
Read()
static ssize_t Read (stream_t * s, void * p_read, size_t i_read) static
References stream_sys_t::i_pos, stream_sys_t::i_size, stream_sys_t::p_buffer, and stream_t::p_sys.
Referenced by vlc_stream_MemoryNew().
Seek()
static int Seek (stream_t * s, uint64_t offset) static
< No error
References stream_sys_t::i_pos, stream_sys_t::i_size, stream_t::p_sys, and VLC_SUCCESS.
Referenced by vlc_stream_MemoryNew().
stream_MemoryDelete()
static void stream_MemoryDelete (stream_t * s) static
References stream_sys_t::p_buffer, stream_t::p_sys, and stream_MemoryPreserveDelete().
Referenced by vlc_stream_MemoryNew().
stream_MemoryPreserveDelete()
static void stream_MemoryPreserveDelete (stream_t * s) static
References stream_t::p_sys.
Referenced by stream_MemoryDelete(), and vlc_stream_MemoryNew().