VLC: src/input/stream.c File Reference
stream.c File Reference
Data Structures
struct stream_priv_t
Macros
#define STREAM_PROBE_LINE 2048
Read from the stream until first newline.
#define STREAM_LINE_MAX (2048*100)
Typedefs
typedef struct stream_priv_t stream_priv_t
Functions
stream_t * vlc_stream_CommonNew (vlc_object_t *parent, void(*destroy)(stream_t *))
Allocates a VLC stream object.
void stream_CommonDelete (stream_t *s)
void vlc_stream_Delete (stream_t *s)
Destroy a stream.
stream_t * vlc_stream_NewURL (vlc_object_t *p_parent, const char *psz_url)
Create a stream_t reading from a URL.
stream_t * vlc_stream_NewMRL (vlc_object_t *parent, const char *mrl)
Create a stream for the data referred to by a Media Resource Locator (MRL).
char * vlc_stream_ReadLine (stream_t *s)
static ssize_t vlc_stream_CopyBlock (block_t **restrict pp, void *buf, size_t len)
static ssize_t vlc_stream_ReadRaw (stream_t *s, void *buf, size_t len)
ssize_t vlc_stream_ReadPartial (stream_t *s, void *buf, size_t len)
Reads partial data from a byte stream.
ssize_t vlc_stream_Read (stream_t *s, void *buf, size_t len)
Reads data from a byte stream.
ssize_t vlc_stream_Peek (stream_t *s, const uint8_t **restrict bufp, size_t len)
block_t * vlc_stream_ReadBlock (stream_t *s)
Reads a data block from a byte stream.
uint64_t vlc_stream_Tell (const stream_t *s)
Tells the current stream position.
bool vlc_stream_Eof (const stream_t *s)
Checks for end of stream.
int vlc_stream_Seek (stream_t *s, uint64_t offset)
Sets the current stream position.
int vlc_stream_vaControl (stream_t *s, int cmd, va_list args)
Use to control the "stream_t *".
block_t * vlc_stream_Block (stream_t *s, size_t size)
Read data into a block.
int vlc_stream_ReadDir (stream_t *s, input_item_node_t *p_node)
Returns a node containing all the input_item of the directory pointer by this stream.
Macro Definition Documentation
STREAM_LINE_MAX
#define STREAM_LINE_MAX (2048*100)
Referenced by vlc_stream_ReadLine().
STREAM_PROBE_LINE
#define STREAM_PROBE_LINE 2048
Read from the stream until first newline.
Parameters
s Stream handle to read from
Returns
A pointer to the allocated output string. You need to free this when you are done.
Referenced by vlc_stream_ReadLine().
Typedef Documentation
stream_priv_t
typedef struct stream_priv_t stream_priv_t
Function Documentation
stream_CommonDelete()
void stream_CommonDelete (stream_t * s)
References stream_priv_t::block, block_Release(), stream_priv_t::conv, stream_priv_t::peek, stream_t::psz_url, stream_priv_t::text, vlc_iconv_close(), and vlc_object_release.
Referenced by access_New(), se_AttachWrapper(), stream_AccessNew(), vlc_stream_Delete(), vlc_stream_FilterNew(), and vlc_stream_MemoryNew().
vlc_stream_CopyBlock()
static ssize_t vlc_stream_CopyBlock (block_t **restrict pp, void * buf, size_t len) static
References block_Release(), block_t::i_buffer, likely, and block_t::p_buffer.
Referenced by vlc_stream_ReadPartial(), and vlc_stream_ReadRaw().
vlc_stream_Peek()
ssize_t vlc_stream_Peek (stream_t * s, const uint8_t **restrict bufp, size_t len)
< Not enough memory
< Not enough memory
References stream_priv_t::block, block_Alloc(), block_TryRealloc(), block_t::i_buffer, block_t::p_buffer, stream_priv_t::peek, unlikely, VLC_ENOMEM, and vlc_stream_ReadRaw().
Referenced by vlc_stream_ReadLine().
vlc_stream_ReadRaw()
static ssize_t vlc_stream_ReadRaw (stream_t * s, void * buf, size_t len) static
References stream_priv_t::block, stream_t::pf_block, stream_t::pf_read, unlikely, vlc_killed(), and vlc_stream_CopyBlock().
Referenced by vlc_stream_Peek(), and vlc_stream_ReadPartial().