VLC: src/input/stream_fifo.c File Reference
stream_fifo.c File Reference
Data Structures
struct stream_sys_t
Functions
static void vlc_stream_fifo_Destroy (stream_t *s)
static block_t * vlc_stream_fifo_Block (stream_t *s, bool *restrict eof)
static int vlc_stream_fifo_Control (stream_t *s, int query, va_list ap)
stream_t * vlc_stream_fifo_New (vlc_object_t *parent)
Creates a FIFO stream.
int vlc_stream_fifo_Queue (stream_t *s, block_t *block)
Writes a block to a FIFO stream.
ssize_t vlc_stream_fifo_Write (stream_t *s, const void *buf, size_t len)
Writes data to a FIFO stream.
void vlc_stream_fifo_Close (stream_t *s)
Terminates a FIFO stream.
Function Documentation
vlc_stream_fifo_Block()
static block_t * vlc_stream_fifo_Block (stream_t * s, bool *restrict eof) static
References stream_sys_t::eof, stream_sys_t::fifo, stream_t::p_sys, vlc_fifo_DequeueUnlocked(), vlc_fifo_IsEmpty(), vlc_fifo_Lock(), vlc_fifo_Unlock(), and vlc_fifo_Wait().
Referenced by vlc_stream_fifo_New().
vlc_stream_fifo_Control()
static int vlc_stream_fifo_Control (stream_t * s, int query, va_list ap) static
< Unspecified error
< No error
References DEFAULT_PTS_DELAY, STREAM_CAN_CONTROL_PACE, STREAM_CAN_FASTSEEK, STREAM_CAN_PAUSE, STREAM_CAN_SEEK, STREAM_GET_PTS_DELAY, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by vlc_stream_fifo_New().
vlc_stream_fifo_Destroy()
static void vlc_stream_fifo_Destroy (stream_t * s) static
References block_ChainRelease(), block_FifoRelease(), stream_sys_t::eof, stream_sys_t::fifo, stream_t::p_sys, vlc_fifo_DequeueAllUnlocked(), vlc_fifo_Lock(), and vlc_fifo_Unlock().
Referenced by vlc_stream_fifo_New().