VLC: src/stream_output/stream_output.h File Reference
stream_output.h File Reference
Data Structures
struct sout_packetizer_input_t
Macros
#define sout_NewInstance(a, b) sout_NewInstance(VLC_OBJECT(a),b)
Functions
sout_instance_t * sout_NewInstance (vlc_object_t *, const char *)
void sout_DeleteInstance (sout_instance_t *)
sout_packetizer_input_t * sout_InputNew (sout_instance_t *, const es_format_t *)
int sout_InputDelete (sout_packetizer_input_t *)
int sout_InputSendBuffer (sout_packetizer_input_t *, block_t *)
bool sout_InputIsEmpty (sout_packetizer_input_t *)
void sout_InputFlush (sout_packetizer_input_t *)
Macro Definition Documentation
sout_NewInstance
#define sout_NewInstance (a, b) sout_NewInstance(VLC_OBJECT(a),b)
Referenced by EsOutSetRecord(), and RequestSout().
Function Documentation
sout_DeleteInstance()
void sout_DeleteInstance (sout_instance_t * p_sout)
References FREENULL, sout_instance_t::lock, sout_instance_t::p_stream, sout_instance_t::psz_sout, sout_StreamChainDelete(), vlc_mutex_destroy(), and vlc_object_release.
Referenced by DestroySout(), and EsOutSetRecord().
sout_InputDelete()
int sout_InputDelete (sout_packetizer_input_t * p_input)
< No error
References sout_packetizer_input_t::id, sout_instance_t::lock, msg_Dbg, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_del, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by DeleteDecoder().
sout_InputFlush()
void sout_InputFlush (sout_packetizer_input_t * p_input)
References sout_packetizer_input_t::id, sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_StreamFlush(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by DecoderProcessFlush().
sout_InputIsEmpty()
bool sout_InputIsEmpty (sout_packetizer_input_t * p_input)
< No error
References sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, SOUT_STREAM_EMPTY, sout_StreamControl(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by input_DecoderIsEmpty().
sout_InputNew()
sout_packetizer_input_t * sout_InputNew (sout_instance_t * p_sout, const es_format_t * p_fmt)
References es_format_t::i_codec, sout_packetizer_input_t::id, sout_instance_t::lock, msg_Dbg, msg_Warn, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_add, vlc_mutex_lock(), and vlc_mutex_unlock().
sout_InputSendBuffer()
int sout_InputSendBuffer (sout_packetizer_input_t * p_input, block_t * p_buffer)
References sout_packetizer_input_t::id, sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_send, vlc_mutex_lock(), and vlc_mutex_unlock().
sout_NewInstance()
sout_instance_t * sout_NewInstance (vlc_object_t * p_parent, const char * psz_dest)
References FREENULL, sout_instance_t::i_out_pace_nocontrol, sout_instance_t::lock, msg_Dbg, msg_Err, sout_instance_t::p_stream, sout_instance_t::psz_sout, sout_stream_url_to_chain(), sout_StreamChainNew(), strdup(), var_Create, var_InheritBool, vlc_custom_create, vlc_mutex_destroy(), vlc_mutex_init(), vlc_object_release, VLC_VAR_DOINHERIT, and VLC_VAR_INTEGER.