VLC: src/stream_output/stream_output.c File Reference
stream_output.c File Reference
Data Structures
struct mrl_t
Functions
static char * sout_stream_url_to_chain (bool, const char *)
static int mrl_Parse (mrl_t *p_mrl, const char *psz_mrl)
static void mrl_Clean (mrl_t *p_mrl)
sout_instance_t * sout_NewInstance (vlc_object_t *p_parent, const char *psz_dest)
void sout_DeleteInstance (sout_instance_t *p_sout)
sout_packetizer_input_t * sout_InputNew (sout_instance_t *p_sout, const es_format_t *p_fmt)
int sout_InputDelete (sout_packetizer_input_t *p_input)
bool sout_InputIsEmpty (sout_packetizer_input_t *p_input)
void sout_InputFlush (sout_packetizer_input_t *p_input)
int sout_InputSendBuffer (sout_packetizer_input_t *p_input, block_t *p_buffer)
sout_access_out_t * sout_AccessOutNew (vlc_object_t *p_sout, const char *psz_access, const char *psz_name)
void sout_AccessOutDelete (sout_access_out_t *p_access)
int sout_AccessOutSeek (sout_access_out_t *p_access, off_t i_pos)
ssize_t sout_AccessOutRead (sout_access_out_t *p_access, block_t *p_buffer)
ssize_t sout_AccessOutWrite (sout_access_out_t *p_access, block_t *p_buffer)
int sout_AccessOutControl (sout_access_out_t *access, int query,...)
sout_AccessOutControl
sout_mux_t * sout_MuxNew (sout_instance_t *p_sout, const char *psz_mux, sout_access_out_t *p_access)
void sout_MuxDelete (sout_mux_t *p_mux)
sout_input_t * sout_MuxAddStream (sout_mux_t *p_mux, const es_format_t *p_fmt)
void sout_MuxDeleteStream (sout_mux_t *p_mux, sout_input_t *p_input)
int sout_MuxSendBuffer (sout_mux_t *p_mux, sout_input_t *p_input, block_t *p_buffer)
void sout_MuxFlush (sout_mux_t *p_mux, sout_input_t *p_input)
int sout_MuxGetStream (sout_mux_t *p_mux, unsigned i_blocks, mtime_t *pi_dts)
static void sout_StreamDelete (sout_stream_t *p_stream)
void sout_StreamChainDelete (sout_stream_t *p_first, sout_stream_t *p_last)
static sout_stream_t * sout_StreamNew (sout_instance_t *p_sout, char *psz_name, config_chain_t *p_cfg, sout_stream_t *p_next)
sout_stream_t * sout_StreamChainNew (sout_instance_t *p_sout, const char *psz_chain, sout_stream_t *p_next, sout_stream_t **pp_last)
encoder_t * sout_EncoderCreate (vlc_object_t *p_this)
Function Documentation
mrl_Clean()
static void mrl_Clean (mrl_t * p_mrl) static
References FREENULL, mrl_t::psz_access, mrl_t::psz_name, and mrl_t::psz_way.
Referenced by sout_stream_url_to_chain().
mrl_Parse()
static int mrl_Parse (mrl_t * p_mrl, const char * psz_mrl) static
< No error
References mrl_t::psz_access, mrl_t::psz_name, psz_name, mrl_t::psz_way, strdup(), and VLC_SUCCESS.
Referenced by sout_stream_url_to_chain().
sout_DeleteInstance()
void sout_DeleteInstance (sout_instance_t * p_sout)
References FREENULL, sout_instance_t::lock, sout_instance_t::p_stream, sout_instance_t::psz_sout, sout_StreamChainDelete(), vlc_mutex_destroy(), and vlc_object_release.
Referenced by DestroySout(), and EsOutSetRecord().
sout_InputDelete()
int sout_InputDelete (sout_packetizer_input_t * p_input)
< No error
References sout_packetizer_input_t::id, sout_instance_t::lock, msg_Dbg, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_del, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by DeleteDecoder().
sout_InputFlush()
void sout_InputFlush (sout_packetizer_input_t * p_input)
References sout_packetizer_input_t::id, sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_StreamFlush(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by DecoderProcessFlush().
sout_InputIsEmpty()
bool sout_InputIsEmpty (sout_packetizer_input_t * p_input)
< No error
References sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, SOUT_STREAM_EMPTY, sout_StreamControl(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by input_DecoderIsEmpty().
sout_InputNew()
sout_packetizer_input_t * sout_InputNew (sout_instance_t * p_sout, const es_format_t * p_fmt)
References es_format_t::i_codec, sout_packetizer_input_t::id, sout_instance_t::lock, msg_Dbg, msg_Warn, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_add, vlc_mutex_lock(), and vlc_mutex_unlock().
sout_InputSendBuffer()
int sout_InputSendBuffer (sout_packetizer_input_t * p_input, block_t * p_buffer)
References sout_packetizer_input_t::id, sout_instance_t::lock, sout_packetizer_input_t::p_sout, sout_instance_t::p_stream, sout_stream_t::pf_send, vlc_mutex_lock(), and vlc_mutex_unlock().
sout_NewInstance()
sout_instance_t * sout_NewInstance (vlc_object_t * p_parent, const char * psz_dest)
References FREENULL, sout_instance_t::i_out_pace_nocontrol, sout_instance_t::lock, msg_Dbg, msg_Err, sout_instance_t::p_stream, sout_instance_t::psz_sout, sout_stream_url_to_chain(), sout_StreamChainNew(), strdup(), var_Create, var_InheritBool, vlc_custom_create, vlc_mutex_destroy(), vlc_mutex_init(), vlc_object_release, VLC_VAR_DOINHERIT, and VLC_VAR_INTEGER.
sout_stream_url_to_chain()
static char * sout_stream_url_to_chain (bool b_sout_display, const char * psz_url) static
References asprintf(), mrl_Clean(), mrl_Parse(), mrl_t::psz_access, mrl_t::psz_name, and mrl_t::psz_way.
Referenced by sout_NewInstance().
sout_StreamDelete()
static void sout_StreamDelete (sout_stream_t * p_stream) static
References config_ChainDestroy(), FREENULL, sout_instance_t::i_out_pace_nocontrol, module_unneed, msg_Dbg, sout_stream_t::obj, sout_stream_t::p_cfg, sout_stream_t::p_module, sout_stream_t::pace_nocontrol, vlc_common_members::parent, sout_stream_t::psz_name, and vlc_object_release.
Referenced by sout_StreamChainDelete(), sout_StreamChainNew(), and sout_StreamNew().
sout_StreamNew()
static sout_stream_t * sout_StreamNew (sout_instance_t * p_sout, char * psz_name, config_chain_t * p_cfg, sout_stream_t * p_next) static
References sout_instance_t::i_out_pace_nocontrol, module_need, msg_Dbg, sout_stream_t::p_cfg, sout_stream_t::p_module, sout_stream_t::p_next, sout_stream_t::p_sout, sout_stream_t::p_sys, sout_stream_t::pace_nocontrol, sout_stream_t::pf_control, sout_stream_t::pf_flush, psz_name, sout_stream_t::psz_name, sout_StreamDelete(), and vlc_custom_create.
Referenced by sout_StreamChainNew().