VLC: src/input/stream.h File Reference
stream.h File Reference
Functions
void stream_CommonDelete (stream_t *s)
stream_t * stream_AccessNew (vlc_object_t *, input_thread_t *, bool, const char *)
This function creates a raw stream_t from an URL.
stream_t * stream_FilterAutoNew (stream_t *source)
Probes stream filters automatically.
stream_t * stream_FilterChainNew (stream_t *source, const char *list)
Builds an explicit chain of stream filters.
int stream_extractor_AttachParsed (stream_t **stream, const char *psz_data, char const **out_extra)
Attach Stream Extractors according to specified data.
char * get_path (const char *location)
Function Documentation
get_path()
char * get_path (const char * location)
References asprintf(), and vlc_uri2path().
Referenced by access_New(), demux_NewAdvanced(), and InputGetExtraFilesPattern().
stream_AccessNew()
stream_t * stream_AccessNew (vlc_object_t * parent, input_thread_t * input, bool preparsing, const char * url)
This function creates a raw stream_t from an URL.
References access_New(), AStreamControl(), AStreamDestroy(), AStreamNoReadDir(), AStreamReadBlock(), AStreamReadDir(), AStreamReadStream(), AStreamSeek(), stream_t::p_input, stream_t::p_sys, stream_t::pf_block, stream_t::pf_control, stream_t::pf_read, stream_t::pf_readdir, stream_t::pf_seek, stream_t::psz_url, strdup(), stream_CommonDelete(), stream_FilterAutoNew(), stream_FilterChainNew(), unlikely, VLC_OBJECT, and vlc_stream_CommonNew().
Referenced by InputDemuxNew(), and vlc_stream_NewURL().
stream_CommonDelete()
void stream_CommonDelete (stream_t * s)
References stream_priv_t::block, block_Release(), stream_priv_t::conv, stream_priv_t::peek, stream_t::psz_url, stream_priv_t::text, vlc_iconv_close(), and vlc_object_release.
Referenced by access_New(), se_AttachWrapper(), stream_AccessNew(), vlc_stream_Delete(), vlc_stream_FilterNew(), and vlc_stream_MemoryNew().
stream_FilterAutoNew()
stream_t * stream_FilterAutoNew (stream_t * source)
Probes stream filters automatically.
This function automatically and repeatedly probes for applicable stream filters to append downstream of an existing stream. Any such filter will convert the stream into another stream, e.g. decompressing it or extracting the list of contained files (playlist).
This function transfers ownership of the supplied stream to the following stream filter, of the first stream filter to the second stream filter, and so on. Any attempt to access the original stream filter directly is explicitly undefined.
If, and only if, no filters were probed succesfully, a pointer to the unchanged source stream will be returned. Otherwise, this returns a stream filter. The return value is thus guaranteed to be non-NULL.
Parameters
source input stream around which to build a filter chain
Returns
the last, most downstream stream object.
Note
The return value must be freed with vlc_stream_Delete() after use. This will automatically free the whole chain and the underlying stream.
References msg_Dbg, and vlc_stream_FilterNew().
Referenced by stream_AccessNew().
stream_FilterChainNew()
stream_t * stream_FilterChainNew (stream_t * source, const char * list)
Builds an explicit chain of stream filters.
This function creates a chain of filters according to a supplied list.
See also stream_FilterAutoNew(). Those two functions have identical semantics; the only difference lies in how the list of probed filters is determined (manually versus automatically).
If the list is empty, or if probing each of the requested filters failed, this function will return a pointer to the supplied source stream.
Parameters
source input stream around which to build a filter chain
list colon-separated list of stream filters (upstream first)
Returns
The last stream (filter) in the chain. The return value is always a valid (non-NULL) stream pointer.
References msg_Warn, name, strdup(), strtok_r(), unlikely, and vlc_stream_FilterNew().
Referenced by InputDemuxNew(), se_AttachWrapper(), and stream_AccessNew().