VLC: src/text/strings.c File Reference
strings.c File Reference
Data Structures
struct xml_entity_s
Macros
#define strcoll strcasecmp
Functions
static int cmp_entity (const void *key, const void *elem)
void vlc_xml_decode (char *psz_value)
Decodes XML entities.
char * vlc_xml_encode (const char *str)
Encodes XML entites.
char * vlc_b64_encode_binary (const uint8_t *src, size_t i_src)
char * vlc_b64_encode (const char *src)
size_t vlc_b64_decode_binary_to_buffer (uint8_t *p_dst, size_t i_dst, const char *p_src)
size_t vlc_b64_decode_binary (uint8_t **pp_dst, const char *psz_src)
char * vlc_b64_decode (const char *psz_src)
char * vlc_strftime (const char *tformat)
Convenience wrapper for strftime().
static void write_duration (struct vlc_memstream *stream, int64_t duration)
static int write_meta (struct vlc_memstream *stream, input_item_t *item, vlc_meta_type_t type)
char * vlc_strfinput (input_thread_t *input, const char *s)
Formats input meta-data.
int vlc_filenamecmp (const char *a, const char *b)
void filename_sanitize (char *str)
Sanitize a file name.
Variables
static const struct xml_entity_s xml_entities []
Macro Definition Documentation
strcoll
#define strcoll strcasecmp
Referenced by slave_strcmp(), and vlc_filenamecmp().
Function Documentation
cmp_entity()
static int cmp_entity (const void * key, const void * elem) static
References name, and xml_entity_s::psz_entity.
Referenced by vlc_xml_decode().
write_duration()
static void write_duration (struct vlc_memstream * stream, int64_t duration) static
References CLOCK_FREQ, lldiv(), lldiv_t::quot, lldiv_t::rem, and vlc_memstream_printf().
Referenced by vlc_strfinput().
write_meta()
static int write_meta (struct vlc_memstream * stream, input_item_t * item, vlc_meta_type_t type) static
References input_item_GetMeta(), and vlc_memstream_puts().
Referenced by vlc_strfinput().
Variable Documentation
xml_entities
const struct xml_entity_s xml_entities[] static
Referenced by vlc_xml_decode().