VLC: audio_replay_gain_t Struct Reference
audio_replay_gain_t Struct Reference
#include <vlc_es.h>
Data Fields
bool pb_peak [(2)]
float pf_peak [(2)]
bool pb_gain [(2)]
float pf_gain [(2)]
Field Documentation
pb_gain
bool audio_replay_gain_t::pb_gain[(2)]
Referenced by aout_replaygain_changed(), aout_ReplayGainSelect(), CreateDecoder(), EsOutAddSlave(), EsOutUpdateInfo(), and vlc_audio_replay_gain_MergeFromMeta().
pb_peak
bool audio_replay_gain_t::pb_peak[(2)]
Referenced by aout_replaygain_changed(), aout_ReplayGainSelect(), CreateDecoder(), EsOutAddSlave(), and vlc_audio_replay_gain_MergeFromMeta().
pf_gain
float audio_replay_gain_t::pf_gain[(2)]
Referenced by aout_ReplayGainSelect(), CreateDecoder(), EsOutAddSlave(), EsOutUpdateInfo(), and vlc_audio_replay_gain_MergeFromMeta().
pf_peak
float audio_replay_gain_t::pf_peak[(2)]
Referenced by aout_ReplayGainSelect(), CreateDecoder(), EsOutAddSlave(), and vlc_audio_replay_gain_MergeFromMeta().
The documentation for this struct was generated from the following file:
include/vlc_es.h