VLC: services_discovery_owner_t Struct Reference
services_discovery_owner_t Struct Reference
#include <vlc_services_discovery.h>
Data Fields
void * sys
Private data for the owner callbacks.
void(* item_added)(struct services_discovery_t *sd, input_item_t *parent, input_item_t *item, const char *category)
void(* item_removed)(struct services_discovery_t *sd, input_item_t *item)
Field Documentation
item_added
void(* services_discovery_owner_t::item_added) (struct services_discovery_t *sd, input_item_t *parent, input_item_t *item, const char *category)
Referenced by services_discovery_AddItem(), services_discovery_AddItemCat(), and services_discovery_AddSubItem().
item_removed
void(* services_discovery_owner_t::item_removed) (struct services_discovery_t *sd, input_item_t *item)
Referenced by services_discovery_RemoveItem().
sys
void* services_discovery_owner_t::sys
Private data for the owner callbacks.
Referenced by playlist_sd_item_added(), and playlist_sd_item_removed().
The documentation for this struct was generated from the following file:
include/vlc_services_discovery.h