VLC: sout_stream_t Struct Reference
sout_stream_t Struct Reference
Output » Stream output
#include <vlc_sout.h>
Data Fields
struct vlc_common_members obj
module_t * p_module
sout_instance_t * p_sout
char * psz_name
config_chain_t * p_cfg
sout_stream_t * p_next
sout_stream_id_sys_t *(* pf_add)(sout_stream_t *, const es_format_t *)
void(* pf_del)(sout_stream_t *, sout_stream_id_sys_t *)
int(* pf_send)(sout_stream_t *, sout_stream_id_sys_t *, block_t *)
int(* pf_control)(sout_stream_t *, int, va_list)
void(* pf_flush)(sout_stream_t *, sout_stream_id_sys_t *)
sout_stream_sys_t * p_sys
bool pace_nocontrol
Field Documentation
obj
struct vlc_common_members sout_stream_t::obj
Referenced by sout_StreamDelete().
p_cfg
config_chain_t* sout_stream_t::p_cfg
Referenced by sout_StreamDelete(), and sout_StreamNew().
p_module
module_t* sout_stream_t::p_module
Referenced by sout_StreamDelete(), and sout_StreamNew().
p_next
sout_stream_t* sout_stream_t::p_next
Referenced by sout_StreamChainDelete(), and sout_StreamNew().
p_sout
sout_instance_t* sout_stream_t::p_sout
Referenced by sout_StreamNew().
p_sys
sout_stream_sys_t* sout_stream_t::p_sys
Referenced by sout_StreamNew().
pace_nocontrol
bool sout_stream_t::pace_nocontrol
Referenced by sout_StreamDelete(), and sout_StreamNew().
pf_add
sout_stream_id_sys_t *(* sout_stream_t::pf_add) (sout_stream_t *, const es_format_t *)
Referenced by sout_InputNew(), and sout_StreamIdAdd().
pf_control
int(* sout_stream_t::pf_control) (sout_stream_t *, int, va_list)
Referenced by sout_StreamControl(), and sout_StreamNew().
pf_del
void(* sout_stream_t::pf_del) (sout_stream_t *, sout_stream_id_sys_t *)
Referenced by sout_InputDelete(), and sout_StreamIdDel().
pf_flush
void(* sout_stream_t::pf_flush) (sout_stream_t *, sout_stream_id_sys_t *)
Referenced by sout_StreamFlush(), and sout_StreamNew().
pf_send
int(* sout_stream_t::pf_send) (sout_stream_t *, sout_stream_id_sys_t *, block_t *)
Referenced by sout_InputSendBuffer(), and sout_StreamIdSend().
psz_name
char* sout_stream_t::psz_name
Referenced by sout_StreamDelete(), and sout_StreamNew().
The documentation for this struct was generated from the following file:
include/vlc_sout.h