VLC: xml_reader_t Struct Reference
xml_reader_t Struct Reference
#include <vlc_xml.h>
Data Fields
struct vlc_common_members obj
xml_reader_sys_t * p_sys
stream_t * p_stream
module_t * p_module
int(* pf_next_node)(xml_reader_t *, const char **)
const char *(* pf_next_attr)(xml_reader_t *, const char **)
int(* pf_use_dtd)(xml_reader_t *)
int(* pf_is_empty)(xml_reader_t *)
Field Documentation
obj
struct vlc_common_members xml_reader_t::obj
p_module
module_t* xml_reader_t::p_module
Referenced by xml_ReaderCreate(), xml_ReaderDelete(), and xml_ReaderReset().
p_stream
stream_t* xml_reader_t::p_stream
Referenced by xml_ReaderCreate(), xml_ReaderDelete(), and xml_ReaderReset().
p_sys
xml_reader_sys_t* xml_reader_t::p_sys
pf_is_empty
int(* xml_reader_t::pf_is_empty) (xml_reader_t *)
Referenced by xml_ReaderIsEmptyElement().
pf_next_attr
const char *(* xml_reader_t::pf_next_attr) (xml_reader_t *, const char **)
Referenced by xml_ReaderNextAttr().
pf_next_node
int(* xml_reader_t::pf_next_node) (xml_reader_t *, const char **)
Referenced by xml_ReaderNextNode().
pf_use_dtd
int(* xml_reader_t::pf_use_dtd) (xml_reader_t *)
Referenced by xml_ReaderUseDTD().
The documentation for this struct was generated from the following file:
include/vlc_xml.h