VLC: variable_ops_t Struct Reference
variable_ops_t Struct Reference
Data Fields
int(* pf_cmp)(vlc_value_t, vlc_value_t)
void(* pf_dup)(vlc_value_t *)
void(* pf_free)(vlc_value_t *)
Field Documentation
pf_cmp
int(* variable_ops_t::pf_cmp) (vlc_value_t, vlc_value_t)
Referenced by var_Change().
pf_dup
void(* variable_ops_t::pf_dup) (vlc_value_t *)
Referenced by var_Change(), var_GetChecked(), and var_SetChecked().
pf_free
void(* variable_ops_t::pf_free) (vlc_value_t *)
Referenced by Destroy(), var_Change(), and var_SetChecked().
The documentation for this struct was generated from the following file:
src/misc/variables.c