VLC: video_splitter_t Struct Reference
video_splitter_t Struct Reference
Structure describing a video splitter.
#include <vlc_video_splitter.h>
Data Fields
struct vlc_common_members obj
module_t * p_module
config_chain_t * p_cfg
video_format_t fmt
int i_output
video_splitter_output_t * p_output
int(* pf_filter)(video_splitter_t *, picture_t *pp_dst[], picture_t *p_src)
int(* pf_mouse)(video_splitter_t *, vlc_mouse_t *, int i_index, const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
video_splitter_sys_t * p_sys
int(* pf_picture_new)(video_splitter_t *, picture_t *pp_picture[])
void(* pf_picture_del)(video_splitter_t *, picture_t *pp_picture[])
video_splitter_owner_t * p_owner
Detailed Description
Structure describing a video splitter.
Field Documentation
fmt
video_format_t video_splitter_t::fmt
Referenced by video_splitter_Delete(), and video_splitter_New().
i_output
int video_splitter_t::i_output
Referenced by vout_NewSplitter().
obj
struct vlc_common_members video_splitter_t::obj
p_cfg
config_chain_t* video_splitter_t::p_cfg
p_module
module_t* video_splitter_t::p_module
Referenced by video_splitter_Delete(), and video_splitter_New().
p_output
video_splitter_output_t* video_splitter_t::p_output
Referenced by vout_NewSplitter().
p_owner
video_splitter_owner_t* video_splitter_t::p_owner
Referenced by SplitterClose(), SplitterPictureDel(), SplitterPictureNew(), and vout_NewSplitter().
p_sys
video_splitter_sys_t* video_splitter_t::p_sys
pf_filter
int(* video_splitter_t::pf_filter) (video_splitter_t *, picture_t *pp_dst[], picture_t *p_src)
Referenced by video_splitter_Filter().
pf_mouse
int(* video_splitter_t::pf_mouse) (video_splitter_t *, vlc_mouse_t *, int i_index, const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
Referenced by video_splitter_Mouse().
pf_picture_del
void(* video_splitter_t::pf_picture_del) (video_splitter_t *, picture_t *pp_picture[])
Referenced by video_splitter_DeletePicture(), and vout_NewSplitter().
pf_picture_new
int(* video_splitter_t::pf_picture_new) (video_splitter_t *, picture_t *pp_picture[])
Referenced by video_splitter_NewPicture(), and vout_NewSplitter().
The documentation for this struct was generated from the following file:
include/vlc_video_splitter.h