VLC: vod_t Struct Reference
vod_t Struct Reference
VLM » Video on Demand (VoD)
#include <vlc_vod.h>
Data Fields
struct vlc_common_members obj
module_t * p_module
vod_sys_t * p_sys
vod_media_t *(* pf_media_new)(vod_t *, const char *, input_item_t *)
void(* pf_media_del)(vod_t *, vod_media_t *)
int(* pf_media_control)(void *, vod_media_t *, const char *, int, va_list)
void * p_data
Field Documentation
obj
struct vlc_common_members vod_t::obj
p_data
void* vod_t::p_data
Referenced by vlm_ControlMediaAdd(), and vod_MediaControl().
p_module
module_t* vod_t::p_module
Referenced by vlm_ControlMediaAdd(), and vlm_Delete().
p_sys
vod_sys_t* vod_t::p_sys
pf_media_control
int(* vod_t::pf_media_control) (void *, vod_media_t *, const char *, int, va_list)
Referenced by vlm_ControlMediaAdd(), and vod_MediaControl().
pf_media_del
void(* vod_t::pf_media_del) (vod_t *, vod_media_t *)
Referenced by vlm_ControlMediaDel(), and vlm_OnMediaUpdate().
pf_media_new
vod_media_t *(* vod_t::pf_media_new) (vod_t *, const char *, input_item_t *)
Referenced by vlm_OnMediaUpdate().
The documentation for this struct was generated from the following file:
include/vlc_vod.h