VLC: vlc_gl_t Struct Reference
vlc_gl_t Struct Reference
#include <vlc_opengl.h>
Public Types
enum { VLC_GL_EXT_DEFAULT , VLC_GL_EXT_EGL , VLC_GL_EXT_WGL }
Data Fields
struct vlc_common_members obj
struct vout_window_t * surface
module_t * module
void * sys
int(* makeCurrent)(vlc_gl_t *)
void(* releaseCurrent)(vlc_gl_t *)
void(* resize)(vlc_gl_t *, unsigned, unsigned)
void(* swap)(vlc_gl_t *)
void *(* getProcAddress)(vlc_gl_t *, const char *)
enum vlc_gl_t:: { ... } ext
union {
struct {
const char *(* queryString)(vlc_gl_t *, int32_t name)
void *(* createImageKHR)(vlc_gl_t *, unsigned target,
void *buffer, const int32_t
*attrib_list)
bool(* destroyImageKHR)(vlc_gl_t *, void *image)
} egl
struct {
const char *(* getExtensionsString)(vlc_gl_t *)
} wgl
};
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
VLC_GL_EXT_DEFAULT
VLC_GL_EXT_EGL
VLC_GL_EXT_WGL
Field Documentation
[union]
union { ... } vlc_gl_t
createImageKHR
void *(* vlc_gl_t::createImageKHR) (vlc_gl_t *, unsigned target, void *buffer, const int32_t *attrib_list)
destroyImageKHR
bool(* vlc_gl_t::destroyImageKHR) (vlc_gl_t *, void *image)
[struct]
struct { ... } vlc_gl_t::egl
[]
enum { ... } vlc_gl_t::ext
getExtensionsString
const char *(* vlc_gl_t::getExtensionsString) (vlc_gl_t *)
getProcAddress
void *(* vlc_gl_t::getProcAddress) (vlc_gl_t *, const char *)
Referenced by vlc_gl_GetProcAddress().
makeCurrent
int(* vlc_gl_t::makeCurrent) (vlc_gl_t *)
Referenced by vlc_gl_MakeCurrent().
module
module_t* vlc_gl_t::module
Referenced by vlc_gl_Create(), and vlc_gl_Release().
obj
struct vlc_common_members vlc_gl_t::obj
queryString
const char *(* vlc_gl_t::queryString) (vlc_gl_t *, int32_t name)
releaseCurrent
void(* vlc_gl_t::releaseCurrent) (vlc_gl_t *)
Referenced by vlc_gl_ReleaseCurrent().
resize
void(* vlc_gl_t::resize) (vlc_gl_t *, unsigned, unsigned)
Referenced by vlc_gl_Resize().
surface
struct vout_window_t* vlc_gl_t::surface
Referenced by vlc_gl_Create(), vlc_gl_surface_CheckSize(), and vlc_gl_surface_Destroy().
swap
void(* vlc_gl_t::swap) (vlc_gl_t *)
Referenced by vlc_gl_Swap().
sys
void* vlc_gl_t::sys
[struct]
struct { ... } vlc_gl_t::wgl
The documentation for this struct was generated from the following file:
include/vlc_opengl.h