VLC: sout_access_out_t Struct Reference
sout_access_out_t Struct Reference
Output » Stream output » Access output
Stream output access_output.
#include <vlc_sout.h>
Data Fields
struct vlc_common_members obj
module_t * p_module
char * psz_access
char * psz_path
sout_access_out_sys_t * p_sys
int(* pf_seek)(sout_access_out_t *, off_t)
ssize_t(* pf_read)(sout_access_out_t *, block_t *)
ssize_t(* pf_write)(sout_access_out_t *, block_t *)
int(* pf_control)(sout_access_out_t *, int, va_list)
config_chain_t * p_cfg
Detailed Description
Stream output access_output.
Field Documentation
obj
struct vlc_common_members sout_access_out_t::obj
p_cfg
config_chain_t* sout_access_out_t::p_cfg
Referenced by sout_AccessOutDelete(), and sout_AccessOutNew().
p_module
module_t* sout_access_out_t::p_module
Referenced by sout_AccessOutDelete(), and sout_AccessOutNew().
p_sys
sout_access_out_sys_t* sout_access_out_t::p_sys
Referenced by sout_AccessOutNew().
pf_control
int(* sout_access_out_t::pf_control) (sout_access_out_t *, int, va_list)
Referenced by sout_AccessOutControl(), and sout_AccessOutNew().
pf_read
ssize_t(* sout_access_out_t::pf_read) (sout_access_out_t *, block_t *)
Referenced by sout_AccessOutNew(), and sout_AccessOutRead().
pf_seek
int(* sout_access_out_t::pf_seek) (sout_access_out_t *, off_t)
Referenced by sout_AccessOutNew(), and sout_AccessOutSeek().
pf_write
ssize_t(* sout_access_out_t::pf_write) (sout_access_out_t *, block_t *)
Referenced by sout_AccessOutNew(), and sout_AccessOutWrite().
psz_access
char* sout_access_out_t::psz_access
Referenced by sout_AccessOutDelete(), and sout_AccessOutNew().
psz_path
char* sout_access_out_t::psz_path
Referenced by sout_AccessOutDelete(), and sout_AccessOutNew().
The documentation for this struct was generated from the following file:
include/vlc_sout.h