VLC: vlc_tls Struct Reference
vlc_tls Struct Reference
Operating system » Networking » Transport layer sockets
Transport layer socket.
#include <vlc_tls.h>
Data Fields
int(* get_fd)(struct vlc_tls *)
ssize_t(* readv)(struct vlc_tls *, struct iovec *, unsigned)
ssize_t(* writev)(struct vlc_tls *, const struct iovec *, unsigned)
int(* shutdown)(struct vlc_tls *, bool duplex)
void(* close)(struct vlc_tls *)
struct vlc_tls * p
Detailed Description
Transport layer socket.
Field Documentation
close
void(* vlc_tls::close) (struct vlc_tls *)
Referenced by vlc_https_connect_proxy(), vlc_tls_SessionDelete(), and vlc_tls_SocketAlloc().
get_fd
int(* vlc_tls::get_fd) (struct vlc_tls *)
Referenced by vlc_https_connect_proxy(), vlc_tls_GetFD(), and vlc_tls_SocketAlloc().
p
struct vlc_tls* vlc_tls::p
Referenced by vlc_https_connect_proxy(), vlc_tls_Close(), vlc_tls_SessionCreate(), and vlc_tls_SocketAlloc().
readv
ssize_t(* vlc_tls::readv) (struct vlc_tls *, struct iovec *, unsigned)
Referenced by httpd_NetRecv(), vlc_https_connect_proxy(), vlc_https_recv(), vlc_tls_ProxyRead(), vlc_tls_Read(), and vlc_tls_SocketAlloc().
shutdown
int(* vlc_tls::shutdown) (struct vlc_tls *, bool duplex)
Referenced by vlc_https_connect_proxy(), vlc_tls_Shutdown(), and vlc_tls_SocketAlloc().
writev
ssize_t(* vlc_tls::writev) (struct vlc_tls *, const struct iovec *, unsigned)
Referenced by httpd_NetSend(), vlc_https_connect_proxy(), vlc_https_send(), vlc_tls_ConnectWrite(), vlc_tls_ProxyWrite(), vlc_tls_SocketAlloc(), vlc_tls_SocketOpenAddrInfo(), and vlc_tls_Write().
The documentation for this struct was generated from the following file:
include/vlc_tls.h