VLC: vlc_tls_creds Struct Reference
vlc_tls_creds Struct Reference
Operating system » Networking » Transport layer sockets » Transport Layer Security
TLS credentials.
#include <vlc_tls.h>
Data Fields
struct vlc_common_members obj
module_t * module
void * sys
vlc_tls_t *(* open)(struct vlc_tls_creds *, vlc_tls_t *sock, const char *host, const char *const *alpn)
int(* handshake)(struct vlc_tls_creds *, vlc_tls_t *session, const char *hostname, const char *service, char **alp)
Detailed Description
TLS credentials.
This structure contains the credentials for establishing TLS sessions. This includes root Certificate Authorities (on client side), trust and cryptographic parameters, public certificates and private keys.
Field Documentation
handshake
int(* vlc_tls_creds::handshake) (struct vlc_tls_creds *, vlc_tls_t *session, const char *hostname, const char *service, char ** alp)
Referenced by vlc_tls_ClientSessionCreate(), and vlc_tls_SessionHandshake().
module
module_t* vlc_tls_creds::module
Referenced by vlc_tls_ClientCreate(), vlc_tls_Delete(), and vlc_tls_ServerCreate().
obj
struct vlc_common_members vlc_tls_creds::obj
Referenced by vlc_https_connect_proxy().
open
vlc_tls_t *(* vlc_tls_creds::open) (struct vlc_tls_creds *, vlc_tls_t *sock, const char *host, const char *const *alpn)
Referenced by vlc_tls_SessionCreate().
sys
void* vlc_tls_creds::sys
The documentation for this struct was generated from the following file:
include/vlc_tls.h