VLC: stream_extractor_t Struct Reference
stream_extractor_t Struct Reference
Input » Stream Extractor
#include <vlc_stream_extractor.h>
Data Fields
struct vlc_common_members obj
char const * identifier
the name of the entity to be extracted
stream_t * source
the source stream to be consumed
void * p_sys
private opaque handle to be used by the module
Callbacks for entity extraction
The following members shall be populated as specified by the documentation associated with stream_t for the equivalent name.
ssize_t(* pf_read)(struct stream_extractor_t *, void *buf, size_t len)
block_t *(* pf_block)(struct stream_extractor_t *, bool *eof)
int(* pf_seek)(struct stream_extractor_t *, uint64_t)
int(* pf_control)(struct stream_extractor_t *, int request, va_list args)
Field Documentation
identifier
char const* stream_extractor_t::identifier
the name of the entity to be extracted
Referenced by se_CleanStream(), se_InitStream(), and StreamExtractorAttach().
obj
struct vlc_common_members stream_extractor_t::obj
p_sys
void* stream_extractor_t::p_sys
private opaque handle to be used by the module
pf_block
block_t *(* stream_extractor_t::pf_block) (struct stream_extractor_t *, bool *eof)
Referenced by se_StreamBlock().
pf_control
int(* stream_extractor_t::pf_control) (struct stream_extractor_t *, int request, va_list args)
Referenced by se_StreamControl().
pf_read
ssize_t(* stream_extractor_t::pf_read) (struct stream_extractor_t *, void *buf, size_t len)
Referenced by se_InitStream(), and se_StreamRead().
pf_seek
int(* stream_extractor_t::pf_seek) (struct stream_extractor_t *, uint64_t)
Referenced by se_StreamSeek().
source
stream_t* stream_extractor_t::source
the source stream to be consumed
Referenced by se_InitStream(), and StreamExtractorAttach().
The documentation for this struct was generated from the following file:
include/vlc_stream_extractor.h