VLC: addons_manager_owner Struct Reference
addons_manager_owner Struct Reference
#include <vlc_addons.h>
Data Fields
void * sys
void(* addon_found)(struct addons_manager_t *, struct addon_entry_t *)
void(* discovery_ended)(struct addons_manager_t *)
void(* addon_changed)(struct addons_manager_t *, struct addon_entry_t *)
Field Documentation
addon_changed
void(* addons_manager_owner::addon_changed) (struct addons_manager_t *, struct addon_entry_t *)
Referenced by InstallerThread().
addon_found
void(* addons_manager_owner::addon_found) (struct addons_manager_t *, struct addon_entry_t *)
Referenced by MergeSources().
discovery_ended
void(* addons_manager_owner::discovery_ended) (struct addons_manager_t *)
Referenced by FinderThread().
sys
void* addons_manager_owner::sys
The documentation for this struct was generated from the following file:
include/vlc_addons.h