VLC: addons_storage_t Struct Reference
addons_storage_t Struct Reference
#include <vlc_addons.h>
Data Fields
struct vlc_common_members obj
int(* pf_install)(addons_storage_t *, addon_entry_t *)
int(* pf_remove)(addons_storage_t *, addon_entry_t *)
int(* pf_catalog)(addons_storage_t *, addon_entry_t **, int)
addons_storage_sys_t * p_sys
Field Documentation
obj
struct vlc_common_members addons_storage_t::obj
Referenced by addons_manager_WriteCatalog(), and installOrRemoveAddon().
p_sys
addons_storage_sys_t* addons_storage_t::p_sys
pf_catalog
int(* addons_storage_t::pf_catalog) (addons_storage_t *, addon_entry_t **, int)
Referenced by addons_manager_WriteCatalog().
pf_install
int(* addons_storage_t::pf_install) (addons_storage_t *, addon_entry_t *)
Referenced by installOrRemoveAddon().
pf_remove
int(* addons_storage_t::pf_remove) (addons_storage_t *, addon_entry_t *)
Referenced by installOrRemoveAddon().
The documentation for this struct was generated from the following file:
include/vlc_addons.h