VLC: src/misc/subpicture.c File Reference
subpicture.c File Reference
Data Structures
struct subpicture_private_t
Functions
subpicture_t * subpicture_New (const subpicture_updater_t *p_upd)
This function create a new empty subpicture.
void subpicture_Delete (subpicture_t *p_subpic)
This function delete a subpicture created by subpicture_New.
subpicture_t * subpicture_NewFromPicture (vlc_object_t *p_obj, picture_t *p_picture, vlc_fourcc_t i_chroma)
This function will create a subpicture having one region in the requested chroma showing the given picture.
void subpicture_Update (subpicture_t *p_subpicture, const video_format_t *p_fmt_src, const video_format_t *p_fmt_dst, mtime_t i_ts)
This function will update the content of a subpicture created with a non NULL subpicture_updater_t.
subpicture_region_private_t * subpicture_region_private_New (video_format_t *p_fmt)
void subpicture_region_private_Delete (subpicture_region_private_t *p_private)
subpicture_region_t * subpicture_region_New (const video_format_t *p_fmt)
This function will create a new subpicture region.
void subpicture_region_Delete (subpicture_region_t *p_region)
This function will destroy a subpicture region allocated by subpicture_region_New.
void subpicture_region_ChainDelete (subpicture_region_t *p_head)
This function will destroy a list of subpicture regions allocated by subpicture_region_New.
unsigned picture_BlendSubpicture (picture_t *dst, filter_t *blend, subpicture_t *src)
This function will blend a given subpicture onto a picture.
subpicture_region_t * subpicture_region_Copy (subpicture_region_t *p_region_src)
This function will copy a subpicture region to a new allocated one and transfer all the properties.
Function Documentation
subpicture_region_private_Delete()
void subpicture_region_private_Delete (subpicture_region_private_t * p_private)
References subpicture_region_private_t::fmt, subpicture_region_private_t::p_picture, picture_Release(), and video_format_Clean().
Referenced by SpuRenderRegion(), and subpicture_region_Delete().
subpicture_region_private_New()
subpicture_region_private_t * subpicture_region_private_New (video_format_t * p_fmt)
< No error
References subpicture_region_private_t::fmt, subpicture_region_private_t::p_picture, video_format_Copy(), and VLC_SUCCESS.
Referenced by SpuRenderRegion().