VLC: src/misc/subpicture.h File Reference
subpicture.h File Reference
Data Structures
struct subpicture_region_private_t
Functions
subpicture_region_private_t * subpicture_region_private_New (video_format_t *)
void subpicture_region_private_Delete (subpicture_region_private_t *)
Function Documentation
subpicture_region_private_Delete()
void subpicture_region_private_Delete (subpicture_region_private_t * p_private)
References subpicture_region_private_t::fmt, subpicture_region_private_t::p_picture, picture_Release(), and video_format_Clean().
Referenced by SpuRenderRegion(), and subpicture_region_Delete().
subpicture_region_private_New()
subpicture_region_private_t * subpicture_region_private_New (video_format_t * p_fmt)
< No error
References subpicture_region_private_t::fmt, subpicture_region_private_t::p_picture, video_format_Copy(), and VLC_SUCCESS.
Referenced by SpuRenderRegion().