VLC: src/network/tcp.c File Reference
tcp.c File Reference
Functions
static int SocksNegotiate (vlc_object_t *, int fd, int i_socks_version, const char *psz_user, const char *psz_passwd)
static int SocksHandshakeTCP (vlc_object_t *, int fd, int i_socks_version, const char *psz_user, const char *psz_passwd, const char *psz_host, int i_port)
int net_Socket (vlc_object_t *p_this, int i_family, int i_socktype, int i_protocol)
int net_Connect (vlc_object_t *p_this, const char *psz_host, int i_port, int type, int proto)
int net_AcceptSingle (vlc_object_t *obj, int lfd)
int net_Accept (vlc_object_t *p_this, int *pi_fd)
Accepts an new connection on a set of listening sockets.
void net_ListenClose (int *pi_fd)
Function Documentation
net_Socket()
int net_Socket (vlc_object_t * p_this, int i_family, int i_socktype, int i_protocol) extern
Referenced by net_Connect().
SocksHandshakeTCP()
static int SocksHandshakeTCP (vlc_object_t * p_obj, int fd, int i_socks_version, const char * psz_user, const char * psz_passwd, const char * psz_host, int i_port) static
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References AI_IDN, pollfd::fd, i_port, msg_Dbg, msg_Err, msg_Warn, net_Read, net_Write, SetWBE(), SocksNegotiate(), VLC_EGENERIC, vlc_getaddrinfo_i11e(), and VLC_SUCCESS.
Referenced by net_Connect().
SocksNegotiate()
static int SocksNegotiate (vlc_object_t * p_obj, int fd, int i_socks_version, const char * psz_user, const char * psz_passwd) static
< No error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References pollfd::fd, msg_Dbg, msg_Err, net_Read, net_Write, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by SocksHandshakeTCP().