VLC: src/modules/textdomain.c File Reference
textdomain.c File Reference
Functions
int vlc_bindtextdomain (const char *domain)
char * vlc_gettext (const char *msgid)
In-tree plugins share their gettext domain with LibVLC.
char * vlc_ngettext (const char *msgid, const char *plural, unsigned long n)
Function Documentation
vlc_bindtextdomain()
int vlc_bindtextdomain (const char * domain)
References asprintf(), config_GetDataDir(), DIR_SEP, ToLocaleDup, and unlikely.
Referenced by libvlc_InternalInit().
vlc_gettext()
char * vlc_gettext (const char * msgid)
In-tree plugins share their gettext domain with LibVLC.
References likely.
Referenced by aout_New(), config_CategoryHelpGet(), config_CategoryNameGet(), config_GetIntChoices(), config_GetPszChoices(), config_Write(), decoder_New(), EsOutProgramMeta(), EsOutUpdateInfo(), input_vaControl(), LanguageGetName(), vlc_http_res_req(), vlc_keycode2str(), vlc_meta_TypeToLocalizedString(), vlc_pgettext_aux(), vout_InitInterlacingSupport(), and vout_IntfInit().
vlc_ngettext()
char * vlc_ngettext (const char * msgid, const char * plural, unsigned long n)
References likely.
Referenced by Usage().