VLC: modules/access/http/transport.h File Reference
transport.h File Reference
Functions
struct vlc_tls * vlc_https_connect (struct vlc_tls_creds *creds, const char *name, unsigned port, bool *restrict two)
struct vlc_tls * vlc_https_connect_proxy (void *ctx, struct vlc_tls_creds *creds, const char *name, unsigned port, bool *restrict two, const char *proxy)
Function Documentation
vlc_https_connect()
struct vlc_tls * vlc_https_connect (struct vlc_tls_creds * creds, const char * name, unsigned port, bool *restrict two)
References name, and vlc_tls_SocketOpenTLS().
Referenced by vlc_https_connect_proxy(), and vlc_https_request().
vlc_https_connect_proxy()
struct vlc_tls * vlc_https_connect_proxy (void * ctx, struct vlc_tls_creds * creds, const char * name, unsigned port, bool *restrict two, const char * proxy)
References vlc_tls::close, vlc_tls::get_fd, vlc_url_t::i_port, vlc_tls_creds::obj, vlc_tls::p, vlc_common_members::parent, vlc_url_t::psz_host, vlc_url_t::psz_password, vlc_url_t::psz_protocol, vlc_url_t::psz_username, vlc_tls::readv, vlc_tls::shutdown, vlc_tls_proxy::sock, strcasecmp(), vlc_tls_proxy::tls, unlikely, vlc_h1_conn_create(), vlc_http_conn_release(), vlc_http_tunnel_open(), vlc_https_connect(), vlc_restorecancel(), vlc_savecancel(), vlc_tls_ClientSessionCreate(), vlc_tls_Close(), vlc_tls_ProxyClose(), vlc_tls_ProxyGetFD(), vlc_tls_ProxyRead(), vlc_tls_ProxyShutdown(), vlc_tls_ProxyWrite(), vlc_tls_SocketOpenTCP(), vlc_UrlClean(), vlc_UrlParse(), and vlc_tls::writev.
Referenced by vlc_https_request().