VLC: src/playlist/tree.c File Reference
tree.c File Reference
Functions
playlist_item_t * GetNextUncle (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_root)
playlist_item_t * GetPrevUncle (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_root)
playlist_item_t * GetNextItem (playlist_t *p_playlist, playlist_item_t *p_root, playlist_item_t *p_item)
Get the next item in the tree If p_item is NULL, return the first child of root.
playlist_item_t * GetPrevItem (playlist_t *p_playlist, playlist_item_t *p_item, playlist_item_t *p_root)
playlist_item_t * playlist_NodeCreate (playlist_t *p_playlist, const char *psz_name, playlist_item_t *p_parent, int i_pos, int i_flags)
Create a playlist node.
void playlist_NodeDelete (playlist_t *p_playlist, playlist_item_t *p_root)
Remove all the children of a node and removes the node.
void playlist_NodeDeleteExplicit (playlist_t *p_playlist, playlist_item_t *p_root, int flags)
Delete a node with explicit semantics.
int playlist_NodeInsert (playlist_item_t *p_parent, playlist_item_t *p_item, int i_position)
playlist_item_t * playlist_ChildSearchName (playlist_item_t *p_node, const char *psz_search)
Search a child of a node by its name.
playlist_item_t * playlist_GetNextLeaf (playlist_t *p_playlist, playlist_item_t *p_root, playlist_item_t *p_item, bool b_ena, bool b_unplayed)
Finds the next item to play.
Function Documentation
GetNextItem()
playlist_item_t * GetNextItem (playlist_t * p_playlist, playlist_item_t * p_root, playlist_item_t * p_item)
Get the next item in the tree If p_item is NULL, return the first child of root.
References GetNextUncle(), playlist_item_t::i_children, playlist_item_t::p_input, playlist_item_t::p_parent, PL_DEBUG2, playlist_item_t::pp_children, and input_item_t::psz_name.
Referenced by playlist_GetNextLeaf().
GetNextUncle()
playlist_item_t * GetNextUncle (playlist_t * p_playlist, playlist_item_t * p_item, playlist_item_t * p_root)
References playlist_item_t::i_children, playlist_item_t::p_input, playlist_item_t::p_parent, PL_DEBUG2, playlist_item_t::pp_children, and input_item_t::psz_name.
Referenced by GetNextItem().
GetPrevItem()
playlist_item_t * GetPrevItem (playlist_t * p_playlist, playlist_item_t * p_item, playlist_item_t * p_root)
References GetPrevUncle(), playlist_item_t::i_children, msg_Err, playlist_item_t::p_input, playlist_item_t::p_parent, PL_DEBUG2, playlist_item_t::pp_children, and input_item_t::psz_name.
GetPrevUncle()
playlist_item_t * GetPrevUncle (playlist_t * p_playlist, playlist_item_t * p_item, playlist_item_t * p_root)
References playlist_item_t::i_children, playlist_item_t::p_parent, and playlist_item_t::pp_children.
Referenced by GetPrevItem().