VLC: modules/access/http/tunnel.c File Reference
tunnel.c File Reference
Data Structures
struct vlc_tls_proxy
Typedefs
typedef struct vlc_tls_proxy vlc_tls_proxy_t
Functions
static char * vlc_http_authority (const char *host, unsigned port)
static struct vlc_http_msg * vlc_http_tunnel_open (struct vlc_http_conn *conn, const char *hostname, unsigned port, const char *username, const char *password)
static int vlc_tls_ProxyGetFD (vlc_tls_t *tls)
static ssize_t vlc_tls_ProxyRead (vlc_tls_t *tls, struct iovec *iov, unsigned count)
static ssize_t vlc_tls_ProxyWrite (vlc_tls_t *tls, const struct iovec *iov, unsigned count)
static int vlc_tls_ProxyShutdown (vlc_tls_t *tls, bool duplex)
static void vlc_tls_ProxyClose (vlc_tls_t *tls)
vlc_tls_t * vlc_https_connect_proxy (void *ctx, vlc_tls_creds_t *creds, const char *hostname, unsigned port, bool *restrict two, const char *proxy)
Typedef Documentation
vlc_tls_proxy_t
typedef struct vlc_tls_proxy vlc_tls_proxy_t
Function Documentation
vlc_http_authority()
static char * vlc_http_authority (const char * host, unsigned port) static
References asprintf(), and unlikely.
Referenced by vlc_http_tunnel_open().
vlc_http_tunnel_open()
static struct vlc_http_msg * vlc_http_tunnel_open (struct vlc_http_conn * conn, const char * hostname, unsigned port, const char * username, const char * password) static
References vlc_http_msg::authority, vlc_http_msg::status, unlikely, vlc_http_authority(), vlc_http_msg_add_agent(), vlc_http_msg_add_creds_basic(), vlc_http_msg_add_header(), vlc_http_msg_destroy(), vlc_http_msg_get_final(), vlc_http_msg_get_initial(), vlc_http_msg_get_status(), vlc_http_req_create(), and vlc_http_stream_open().
Referenced by vlc_https_connect_proxy().
vlc_https_connect_proxy()
vlc_tls_t * vlc_https_connect_proxy (void * ctx, vlc_tls_creds_t * creds, const char * hostname, unsigned port, bool *restrict two, const char * proxy)
References vlc_tls::close, vlc_tls::get_fd, vlc_url_t::i_port, vlc_tls_creds::obj, vlc_tls::p, vlc_common_members::parent, vlc_url_t::psz_host, vlc_url_t::psz_password, vlc_url_t::psz_protocol, vlc_url_t::psz_username, vlc_tls::readv, vlc_tls::shutdown, vlc_tls_proxy::sock, strcasecmp(), vlc_tls_proxy::tls, unlikely, vlc_h1_conn_create(), vlc_http_conn_release(), vlc_http_tunnel_open(), vlc_https_connect(), vlc_restorecancel(), vlc_savecancel(), vlc_tls_ClientSessionCreate(), vlc_tls_Close(), vlc_tls_ProxyClose(), vlc_tls_ProxyGetFD(), vlc_tls_ProxyRead(), vlc_tls_ProxyShutdown(), vlc_tls_ProxyWrite(), vlc_tls_SocketOpenTCP(), vlc_UrlClean(), vlc_UrlParse(), and vlc_tls::writev.
Referenced by vlc_https_request().
vlc_tls_ProxyClose()
static void vlc_tls_ProxyClose (vlc_tls_t * tls) static
Referenced by vlc_https_connect_proxy().
vlc_tls_ProxyGetFD()
static int vlc_tls_ProxyGetFD (vlc_tls_t * tls) static
References vlc_tls_proxy::sock, and vlc_tls_GetFD().
Referenced by vlc_https_connect_proxy().
vlc_tls_ProxyRead()
static ssize_t vlc_tls_ProxyRead (vlc_tls_t * tls, struct iovec * iov, unsigned count) static
References count, vlc_tls::readv, and vlc_tls_proxy::sock.
Referenced by vlc_https_connect_proxy().
vlc_tls_ProxyShutdown()
static int vlc_tls_ProxyShutdown (vlc_tls_t * tls, bool duplex) static
References vlc_tls_proxy::sock, and vlc_tls_Shutdown().
Referenced by vlc_https_connect_proxy().
vlc_tls_ProxyWrite()
static ssize_t vlc_tls_ProxyWrite (vlc_tls_t * tls, const struct iovec * iov, unsigned count) static
References count, vlc_tls_proxy::sock, and vlc_tls::writev.
Referenced by vlc_https_connect_proxy().