VLC: src/network/udp.c File Reference
udp.c File Reference
Macros
#define SOL_IP IPPROTO_IP
#define SOL_IPV6 IPPROTO_IPV6
#define IPPROTO_IPV6 41 /* IANA */
#define SOL_DCCP IPPROTO_DCCP
#define IPPROTO_DCCP 33 /* IANA */
#define SOL_UDPLITE IPPROTO_UDPLITE
#define IPPROTO_UDPLITE 136 /* IANA */
Functions
int net_Socket (vlc_object_t *p_this, int i_family, int i_socktype, int i_protocol)
static int net_SetupDgramSocket (vlc_object_t *p_obj, int fd, const struct addrinfo *ptr)
static int net_ListenSingle (vlc_object_t *obj, const char *host, int port, int protocol)
static int net_SetMcastHopLimit (vlc_object_t *p_this, int fd, int family, int hlim)
static int net_SetMcastOut (vlc_object_t *p_this, int fd, int family, const char *iface)
static unsigned var_GetIfIndex (vlc_object_t *obj)
static int net_SourceSubscribe (vlc_object_t *obj, int fd, const struct sockaddr *src, socklen_t srclen, const struct sockaddr *grp, socklen_t grplen)
IP-agnostic multicast join, with fallback to old APIs, and fallback from SSM to ASM.
int net_Subscribe (vlc_object_t *obj, int fd, const struct sockaddr *grp, socklen_t grplen)
static int net_SetDSCP (int fd, uint8_t dscp)
int net_ConnectDgram (vlc_object_t *p_this, const char *psz_host, int i_port, int i_hlim, int proto)
int net_OpenDgram (vlc_object_t *obj, const char *psz_bind, int i_bind, const char *psz_server, int i_server, int protocol)
int net_SetCSCov (int fd, int sendcov, int recvcov)
net_SetCSCov: Sets the send and receive checksum coverage of a socket:
Macro Definition Documentation
IPPROTO_DCCP
#define IPPROTO_DCCP 33 /* IANA */
IPPROTO_IPV6
#define IPPROTO_IPV6 41 /* IANA */
Referenced by net_Socket().
IPPROTO_UDPLITE
#define IPPROTO_UDPLITE 136 /* IANA */
SOL_DCCP
#define SOL_DCCP IPPROTO_DCCP
Referenced by net_SetCSCov(), and net_Socket().
SOL_IP
#define SOL_IP IPPROTO_IP
Referenced by net_SetDSCP(), net_SetMcastHopLimit(), net_SetMcastOut(), net_SourceSubscribe(), and net_Subscribe().
SOL_IPV6
#define SOL_IPV6 IPPROTO_IPV6
Referenced by net_ListenSingle(), net_SetDSCP(), net_SetMcastHopLimit(), net_SetMcastOut(), net_SourceSubscribe(), and net_Subscribe().
SOL_UDPLITE
#define SOL_UDPLITE IPPROTO_UDPLITE
Referenced by net_SetCSCov().
Function Documentation
net_ListenSingle()
static int net_ListenSingle (vlc_object_t * obj, const char * host, int port, int protocol) static
References AI_IDN, AI_NUMERICSERV, msg_Dbg, msg_Err, net_Close, net_errno, net_SetupDgramSocket(), net_SockAddrIsMulticast(), net_Socket(), net_Subscribe(), SOL_IPV6, vlc_getaddrinfo(), and vlc_strerror_c().
Referenced by net_OpenDgram().
net_SetDSCP()
static int net_SetDSCP (int fd, uint8_t dscp) static
References SOL_IP, and SOL_IPV6.
Referenced by net_ConnectDgram().
net_SetMcastHopLimit()
static int net_SetMcastHopLimit (vlc_object_t * p_this, int fd, int family, int hlim) static
< Unspecified error
< Unspecified error
< No error
References msg_Dbg, msg_Err, msg_Warn, net_errno, SOL_IP, SOL_IPV6, VLC_EGENERIC, vlc_strerror_c(), and VLC_SUCCESS.
Referenced by net_ConnectDgram().
net_SetMcastOut()
static int net_SetMcastOut (vlc_object_t * p_this, int fd, int family, const char * iface) static
References if_nametoindex, msg_Err, SOL_IP, SOL_IPV6, and vlc_strerror_c().
Referenced by net_ConnectDgram().
net_SetupDgramSocket()
static int net_SetupDgramSocket (vlc_object_t * p_obj, int fd, const struct addrinfo * ptr) static
References msg_Err, net_Close, net_errno, net_SockAddrIsMulticast(), and vlc_strerror_c().
Referenced by net_ListenSingle(), and net_OpenDgram().
net_Socket()
int net_Socket (vlc_object_t * p_this, int i_family, int i_socktype, int i_protocol) extern
Referenced by net_ConnectDgram(), net_ListenSingle(), and net_OpenDgram().
net_SourceSubscribe()
static int net_SourceSubscribe (vlc_object_t * obj, int fd, const struct sockaddr * src, socklen_t srclen, const struct sockaddr * grp, socklen_t grplen) static
IP-agnostic multicast join, with fallback to old APIs, and fallback from SSM to ASM.
References msg_Err, msg_Warn, net_errno, net_Subscribe(), SOL_IP, SOL_IPV6, var_GetIfIndex(), and vlc_strerror_c().
Referenced by net_OpenDgram().
var_GetIfIndex()
static unsigned var_GetIfIndex (vlc_object_t * obj) static
References if_nametoindex, msg_Err, and var_InheritString.
Referenced by net_SourceSubscribe(), and net_Subscribe().