VLC: src/misc/update.c File Reference
update.c File Reference
This file contains functions related to VLC update management.
Macros
#define UPDATE_OS_SUFFIX ""
#define UPDATE_VLC_STATUS_URL "http://update-test.videolan.org/vlc/status-win-x86"
#define dialog_FatalWait(p_obj, psz_title, psz_fmt, ...)
Functions
update_t * update_New (vlc_object_t *p_this)
Create a new update VLC struct.
void update_Delete (update_t *p_update)
Delete an update_t struct.
static void EmptyRelease (update_t *p_update)
Empty the release struct.
static bool GetUpdateFile (update_t *p_update)
Get the update file and parse it p_update has to be locked when calling this function.
static void * update_CheckReal (void *)
void update_Check (update_t *p_update, void(*pf_callback)(void *, bool), void *p_data)
Check for updates.
bool update_NeedUpgrade (update_t *p_update)
static char * size_str (uint64_t l_size)
Convert a long int size in bytes to a string.
static void * update_DownloadReal (void *)
void update_Download (update_t *p_update, const char *psz_destdir)
Download the file given in the update_t.
update_release_t * update_GetRelease (update_t *p_update)
Detailed Description
This file contains functions related to VLC update management.
Macro Definition Documentation
dialog_FatalWait
#define dialog_FatalWait (p_obj, psz_title, psz_fmt, ...)
Value:
    vlc_dialog_wait_question( p_obj, VLC_DIALOG_QUESTION_CRITICAL, "OK", NULL, \
                              NULL, psz_title, psz_fmt, ##__VA_ARGS__ );
Referenced by update_DownloadReal().
UPDATE_OS_SUFFIX
#define UPDATE_OS_SUFFIX ""
UPDATE_VLC_STATUS_URL
#define UPDATE_VLC_STATUS_URL "http://update-test.videolan.org/vlc/status-win-x86"
Referenced by GetUpdateFile().
Function Documentation
EmptyRelease()
static void EmptyRelease (update_t * p_update) static
Empty the release struct.
Parameters
p_update update_t* pointer
Returns
nothing
References FREENULL, update_release_t::i_major, update_release_t::i_minor, update_release_t::i_revision, update_release_t::psz_desc, update_release_t::psz_url, and update_t::release.
Referenced by update_CheckReal().
GetUpdateFile()
static bool GetUpdateFile (update_t * p_update) static
Get the update file and parse it p_update has to be locked when calling this function.
Parameters
p_update pointer to update struct
Returns
true if the update is valid and authenticated
< No error
< No error
< No error
< No error
References BINARY_SIGNATURE, download_key(), download_signature(), FREENULL, hash_from_public_key(), hash_from_text(), signature_packet_t::hash_verification, update_release_t::i_extra, update_release_t::i_major, update_release_t::i_minor, update_release_t::i_revision, signature_packet_t::issuer_longid, public_key_t::key, public_key_t::longid, msg_Dbg, msg_Err, msg_Info, msg_Warn, update_t::p_libvlc, update_t::p_pkey, parse_public_key(), update_release_t::psz_desc, update_release_t::psz_url, update_t::release, public_key_t::sig, TEXT_SIGNATURE, signature_packet_t::type, UPDATE_VLC_STATUS_URL, verify_signature(), videolan_public_key, videolan_public_key_longid, VLC_OBJECT, vlc_stream_Delete(), vlc_stream_GetSize(), vlc_stream_NewURL, vlc_stream_Read(), and VLC_SUCCESS.
Referenced by update_CheckReal().
size_str()
static char * size_str (uint64_t l_size) static
Convert a long int size in bytes to a string.
Parameters
l_size the size in bytes
Returns
the size as a string
References _, and asprintf().
Referenced by update_DownloadReal().
update_CheckReal()
void * update_CheckReal (void * obj) static
References EmptyRelease(), GetUpdateFile(), update_t::lock, update_check_thread_t::p_data, update_check_thread_t::p_update, update_check_thread_t::pf_callback, vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), and vlc_savecancel().
Referenced by update_Check().
update_DownloadReal()
static void * update_DownloadReal (void * obj) static
< No error
< No error
References _, update_download_thread_t::aborted, asprintf(), BINARY_SIGNATURE, dialog_FatalWait, download_signature(), hash_from_file(), signature_packet_t::hash_verification, signature_packet_t::issuer_longid, public_key_t::key, vlc_common_members::libvlc, libvlc_Quit(), public_key_t::longid, msg_Dbg, msg_Err, msg_Info, update_download_thread_t::obj, update_t::p_pkey, update_download_thread_t::p_update, update_download_thread_t::psz_destdir, update_release_t::psz_url, update_t::release, size_str(), signature_packet_t::type, unlikely, verify_signature(), vlc_dialog_display_progress, vlc_dialog_is_cancelled, VLC_DIALOG_QUESTION_NORMAL, vlc_dialog_release, vlc_dialog_update_progress_text, vlc_dialog_wait_question, vlc_fopen(), VLC_OBJECT, vlc_restorecancel(), vlc_savecancel(), vlc_stream_Delete(), vlc_stream_GetSize(), vlc_stream_NewURL, vlc_stream_Read(), VLC_SUCCESS, and vlc_unlink().
Referenced by update_Download().