VLC: src/misc/update.h File Reference
update.h File Reference
Data Structures
struct public_key_packet_t
struct signature_packet_t
struct public_key_t
struct update_download_thread_t
Non blocking binary download.
struct update_check_thread_t
Non blocking update availability verification.
struct update_t
The update object.
Typedefs
typedef struct public_key_packet_t public_key_packet_t
typedef struct signature_packet_t signature_packet_t
typedef struct public_key_t public_key_t
Enumerations
enum { SIGNATURE_PACKET = 0x02 , PUBLIC_KEY_PACKET = 0x06 , USER_ID_PACKET = 0x0d }
enum {
BINARY_SIGNATURE = 0x00 , TEXT_SIGNATURE = 0x01 , GENERIC_KEY_SIGNATURE = 0x10 , PERSONA_KEY_SIGNATURE = 0x11 ,
CASUAL_KEY_SIGNATURE = 0x12 , POSITIVE_KEY_SIGNATURE = 0x13
}
enum { ISSUER_SUBPACKET = 0x10 }
Functions
public_key_t * download_key (vlc_object_t *p_this, const uint8_t *p_longid, const uint8_t *p_signature_issuer)
int parse_public_key (const uint8_t *p_key_data, size_t i_key_len, public_key_t *p_key, const uint8_t *p_sig_issuer)
int verify_signature (signature_packet_t *sign, public_key_packet_t *p_key, uint8_t *p_hash)
int download_signature (vlc_object_t *p_this, signature_packet_t *p_sig, const char *psz_url)
uint8_t * hash_from_text (const char *psz_text, signature_packet_t *p_sig)
uint8_t * hash_from_file (const char *psz_file, signature_packet_t *p_sig)
uint8_t * hash_from_public_key (public_key_t *p_pkey)
Typedef Documentation
public_key_packet_t
typedef struct public_key_packet_t public_key_packet_t
public_key_t
typedef struct public_key_t public_key_t
signature_packet_t
typedef struct signature_packet_t signature_packet_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNATURE_PACKET
PUBLIC_KEY_PACKET
USER_ID_PACKET
anonymous enum
anonymous enum
Enumerator
BINARY_SIGNATURE
TEXT_SIGNATURE
GENERIC_KEY_SIGNATURE
PERSONA_KEY_SIGNATURE
CASUAL_KEY_SIGNATURE
POSITIVE_KEY_SIGNATURE
anonymous enum
anonymous enum
Enumerator
ISSUER_SUBPACKET
Function Documentation
download_key()
public_key_t * download_key (vlc_object_t * p_this, const uint8_t * p_longid, const uint8_t * p_signature_issuer)
< No error
References asprintf(), public_key_t::longid, msg_Dbg, parse_public_key(), vlc_stream_Delete(), vlc_stream_GetSize(), vlc_stream_NewURL, vlc_stream_Read(), and VLC_SUCCESS.
Referenced by GetUpdateFile().
download_signature()
int download_signature (vlc_object_t * p_this, signature_packet_t * p_sig, const char * psz_url)
< Not enough memory
< Not enough memory
< Unspecified error
< Not enough memory
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
< No error
< Unspecified error
< No error
References BINARY_SIGNATURE, signature_packet_t::hashed_data, msg_Dbg, packet_header_len, packet_type, parse_signature_packet(), pgp_unarmor(), scalar_number(), SIGNATURE_PACKET, signature_packet_t::specific, TEXT_SIGNATURE, signature_packet_t::type, signature_packet_t::unhashed_data, signature_packet_t::v4, signature_packet_t::version, VLC_EGENERIC, VLC_ENOMEM, vlc_stream_Delete(), vlc_stream_GetSize(), vlc_stream_NewURL, vlc_stream_Read(), and VLC_SUCCESS.
Referenced by GetUpdateFile(), and update_DownloadReal().
hash_from_file()
uint8_t * hash_from_file (const char * psz_file, signature_packet_t * p_sig)
References signature_packet_t::digest_algo, hash_finish(), and hash_from_binary_file().
Referenced by update_DownloadReal().
hash_from_public_key()
uint8_t * hash_from_public_key (public_key_t * p_pkey)
References public_key_packet_t::algo, signature_packet_t::digest_algo, public_key_packet_t::dsa, public_key_packet_t::e, public_key_packet_t::g, GENERIC_KEY_SIGNATURE, hash_finish(), signature_packet_t::hash_verification, public_key_t::key, mpi_len(), public_key_packet_t::n, public_key_packet_t::p, POSITIVE_KEY_SIGNATURE, public_key_t::psz_username, public_key_packet_t::q, public_key_packet_t::rsa, public_key_packet_t::sig, public_key_t::sig, public_key_packet_t::timestamp, signature_packet_t::type, public_key_packet_t::version, signature_packet_t::version, and public_key_packet_t::y.
Referenced by GetUpdateFile().
hash_from_text()
uint8_t * hash_from_text (const char * psz_text, signature_packet_t * p_sig)
References signature_packet_t::digest_algo, hash_finish(), TEXT_SIGNATURE, and signature_packet_t::type.
Referenced by GetUpdateFile().
parse_public_key()
int parse_public_key (const uint8_t * p_key_data, size_t i_key_len, public_key_t * p_key, const uint8_t * p_sig_issuer)
< Not enough memory
< No error
< No error
< Unspecified error
< Unspecified error
< No error
< Unspecified error
References signature_packet_t::hashed_data, i_type, signature_packet_t::issuer_longid, public_key_t::key, packet_header_len, packet_type, parse_public_key_packet(), parse_signature_packet(), pgp_unarmor(), public_key_t::psz_username, PUBLIC_KEY_FOUND, PUBLIC_KEY_PACKET, scalar_number(), public_key_t::sig, SIGNATURE_FOUND, SIGNATURE_PACKET, signature_packet_t::specific, signature_packet_t::unhashed_data, USER_ID_FOUND, USER_ID_PACKET, signature_packet_t::v4, signature_packet_t::version, VLC_EGENERIC, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by download_key(), and GetUpdateFile().
verify_signature()
int verify_signature (signature_packet_t * sign, public_key_packet_t * p_key, uint8_t * p_hash)
< Unspecified error
References signature_packet_t::public_key_algo, verify_signature_dsa(), verify_signature_rsa(), and VLC_EGENERIC.
Referenced by GetUpdateFile(), and update_DownloadReal().