VLC: src/input/var.c File Reference
var.c File Reference
Data Structures
struct vlc_input_callback_t
Macros
#define CALLBACK(name, cb) { name, cb }
Functions
static int StateCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int RateCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int PositionCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int TimeCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int TimeOffsetCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int ProgramCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int TitleCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int SeekpointCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int NavigationCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int EsVideoCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int EsAudioCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int EsSpuCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int EsDelayCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int BookmarkCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *)
static int RecordCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
static int FrameNextCallback (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
static void InputAddCallbacks (input_thread_t *, const vlc_input_callback_t *)
static void InputDelCallbacks (input_thread_t *, const vlc_input_callback_t *)
void input_ControlVarInit (input_thread_t *p_input)
void input_ControlVarStop (input_thread_t *p_input)
void input_ControlVarNavigation (input_thread_t *p_input)
void input_ControlVarTitle (input_thread_t *p_input, int i_title)
void input_ConfigVarInit (input_thread_t *p_input)
Variables
static const vlc_input_callback_t p_input_callbacks []
static const vlc_input_callback_t p_input_title_navigation_callbacks []
Macro Definition Documentation
CALLBACK
#define CALLBACK (name, cb) { name, cb }
Function Documentation
BookmarkCallback()
static int BookmarkCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References INPUT_CONTROL_SET_BOOKMARK, input_ControlPush(), VLC_SUCCESS, and VLC_UNUSED.
EsAudioCallback()
static int EsAudioCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References AUDIO_ES, vlc_value_t::i_int, INPUT_CONTROL_SET_ES, input_ControlPush(), var_SetBool, VLC_SUCCESS, and VLC_UNUSED.
EsDelayCallback()
static int EsDelayCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References INPUT_CONTROL_SET_AUDIO_DELAY, INPUT_CONTROL_SET_SPU_DELAY, input_ControlPush(), VLC_SUCCESS, and VLC_UNUSED.
EsSpuCallback()
static int EsSpuCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::i_int, INPUT_CONTROL_SET_ES, input_ControlPush(), SPU_ES, var_SetBool, VLC_SUCCESS, and VLC_UNUSED.
EsVideoCallback()
static int EsVideoCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::i_int, INPUT_CONTROL_SET_ES, input_ControlPush(), var_SetBool, VIDEO_ES, VLC_SUCCESS, and VLC_UNUSED.
FrameNextCallback()
static int FrameNextCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References INPUT_CONTROL_SET_FRAME_NEXT, input_ControlPush(), VLC_SUCCESS, and VLC_UNUSED.
input_ConfigVarInit()
void input_ConfigVarInit (input_thread_t * p_input)
References input_priv(), var_Create, var_SetBool, var_SetFloat, var_SetInteger, VLC_VAR_BOOL, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_STRING.
Referenced by Create().
input_ControlVarInit()
void input_ControlVarInit (input_thread_t * p_input)
References _, vlc_value_t::i_int, input_thread_private_t::i_state, input_priv(), InputAddCallbacks(), p_input_callbacks, vlc_value_t::psz_string, var_Change, var_Create, var_Get, var_GetInteger, var_SetInteger, VLC_VAR_DELCHOICE, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, VLC_VAR_SETVALUE, VLC_VAR_STRING, and VLC_VAR_VOID.
Referenced by Create().
input_ControlVarNavigation()
void input_ControlVarNavigation (input_thread_t * p_input)
References _, asprintf(), CLOCK_FREQ, vlc_value_t::i_int, input_title_t::i_length, input_title_t::i_seekpoint, input_thread_private_t::i_title, input_priv(), MSTRTIME_MAX_SIZE, NavigationCallback(), psz_name, seekpoint_t::psz_name, vlc_value_t::psz_string, secstotimestr(), input_title_t::seekpoint, strdup(), input_thread_private_t::title, TitleCallback(), var_AddCallback, var_Change, var_Create, var_Destroy, var_Type, VLC_VAR_ADDCHOICE, VLC_VAR_CLEARCHOICES, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, and VLC_VAR_VOID.
Referenced by InitTitle().
input_ControlVarStop()
void input_ControlVarStop (input_thread_t * p_input)
References input_thread_private_t::i_title, input_priv(), InputDelCallbacks(), name, NavigationCallback(), p_input_callbacks, p_input_title_navigation_callbacks, var_DelCallback, var_Destroy, and var_Type.
Referenced by End().
input_ControlVarTitle()
void input_ControlVarTitle (input_thread_t * p_input, int i_title)
References _, asprintf(), vlc_value_t::i_int, input_title_t::i_seekpoint, input_priv(), seekpoint_t::psz_name, vlc_value_t::psz_string, input_title_t::seekpoint, SeekpointCallback(), strdup(), input_thread_private_t::title, var_AddCallback, var_Change, var_Create, var_Destroy, var_Type, VLC_VAR_ADDCHOICE, VLC_VAR_CLEARCHOICES, VLC_VAR_SETTEXT, and VLC_VAR_VOID.
Referenced by input_SendEventTitle().
InputAddCallbacks()
static void InputAddCallbacks (input_thread_t * p_input, const vlc_input_callback_t * p_callbacks) static
References psz_name, vlc_input_callback_t::psz_name, and var_AddCallback.
Referenced by input_ControlVarInit().
InputDelCallbacks()
static void InputDelCallbacks (input_thread_t * p_input, const vlc_input_callback_t * p_callbacks) static
References psz_name, vlc_input_callback_t::psz_name, and var_DelCallback.
Referenced by input_ControlVarStop().
NavigationCallback()
static int NavigationCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::i_int, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_TITLE, input_ControlPush(), var_Change, VLC_SUCCESS, VLC_UNUSED, and VLC_VAR_SETVALUE.
Referenced by input_ControlVarNavigation(), and input_ControlVarStop().
PositionCallback()
static int PositionCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::f_float, vlc_value_t::i_int, INPUT_CONTROL_SET_POSITION, input_ControlPush(), var_Change, var_GetInteger, VLC_SUCCESS, VLC_UNUSED, and VLC_VAR_SETVALUE.
ProgramCallback()
static int ProgramCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References INPUT_CONTROL_SET_PROGRAM, input_ControlPush(), VLC_SUCCESS, and VLC_UNUSED.
RateCallback()
static int RateCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::f_float, vlc_value_t::i_int, INPUT_CONTROL_SET_RATE, input_ControlPush(), INPUT_RATE_DEFAULT, VLC_SUCCESS, and VLC_UNUSED.
RecordCallback()
static int RecordCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References INPUT_CONTROL_SET_RECORD_STATE, input_ControlPush(), VLC_SUCCESS, and VLC_UNUSED.
SeekpointCallback()
static int SeekpointCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References count, vlc_value_t::i_int, INPUT_CONTROL_SET_SEEKPOINT, INPUT_CONTROL_SET_SEEKPOINT_NEXT, INPUT_CONTROL_SET_SEEKPOINT_PREV, input_ControlPush(), var_Change, var_GetInteger, VLC_SUCCESS, VLC_UNUSED, VLC_VAR_CHOICESCOUNT, and VLC_VAR_SETVALUE.
Referenced by input_ControlVarTitle().
StateCallback()
static int StateCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
< Unspecified error
References vlc_value_t::i_int, INPUT_CONTROL_SET_STATE, input_ControlPush(), PAUSE_S, PLAYING_S, VLC_EGENERIC, VLC_SUCCESS, and VLC_UNUSED.
TimeCallback()
static int TimeCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::f_float, vlc_value_t::i_int, INPUT_CONTROL_SET_TIME, input_ControlPush(), INPUT_EVENT_POSITION, var_Change, var_GetInteger, var_SetInteger, VLC_SUCCESS, VLC_UNUSED, and VLC_VAR_SETVALUE.
TimeOffsetCallback()
static int TimeOffsetCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * data) static
< No error
References vlc_value_t::i_int, var_GetInteger, var_SetInteger, VLC_SUCCESS, and VLC_UNUSED.
TitleCallback()
static int TitleCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References count, vlc_value_t::i_int, INPUT_CONTROL_NAV_MENU, INPUT_CONTROL_NAV_POPUP, INPUT_CONTROL_SET_TITLE, INPUT_CONTROL_SET_TITLE_NEXT, INPUT_CONTROL_SET_TITLE_PREV, input_ControlPush(), var_Change, var_GetInteger, VLC_SUCCESS, VLC_UNUSED, VLC_VAR_CHOICESCOUNT, and VLC_VAR_SETVALUE.
Referenced by input_ControlVarNavigation().
Variable Documentation
p_input_callbacks
const vlc_input_callback_t p_input_callbacks[] static
Initial value:
=
{
    { "state", StateCallback } ,
    { "rate", RateCallback } ,
    { "position", PositionCallback } ,
    { "time", TimeCallback } ,
    { "time-offset", TimeOffsetCallback } ,
    { "bookmark", BookmarkCallback } ,
    { "program", ProgramCallback } ,
    { "title", TitleCallback } ,
    { "chapter", SeekpointCallback } ,
    { "audio-delay", EsDelayCallback } ,
    { "spu-delay", EsDelayCallback } ,
    { "video-es", EsVideoCallback } ,
    { "audio-es", EsAudioCallback } ,
    { "spu-es", EsSpuCallback } ,
    { "record", RecordCallback } ,
    { "frame-next", FrameNextCallback } ,
    { NULL, NULL }
}
Referenced by input_ControlVarInit(), and input_ControlVarStop().
p_input_title_navigation_callbacks
const vlc_input_callback_t p_input_title_navigation_callbacks[] static
Initial value:
=
{
    { "next-title", TitleCallback } ,
    { "prev-title", TitleCallback } ,
    { "menu-popup", TitleCallback } ,
    { "menu-title", TitleCallback } ,
    { NULL, NULL }
}
Referenced by input_ControlVarStop().