VLC: src/misc/variables.c File Reference
variables.c File Reference
Data Structures
struct callback_entry_t
struct variable_ops_t
struct callback_table_t
struct variable_t
The structure describing a variable.
Typedefs
typedef struct callback_entry_t callback_entry_t
typedef struct variable_ops_t variable_ops_t
typedef struct callback_table_t callback_table_t
Enumerations
enum vlc_callback_type_t { vlc_value_callback , vlc_list_callback }
Functions
static int CmpBool (vlc_value_t v, vlc_value_t w)
static int CmpInt (vlc_value_t v, vlc_value_t w)
static int CmpString (vlc_value_t v, vlc_value_t w)
static int CmpFloat (vlc_value_t v, vlc_value_t w)
static int CmpAddress (vlc_value_t v, vlc_value_t w)
static void DupDummy (vlc_value_t *p_val)
static void DupString (vlc_value_t *p_val)
static void FreeDummy (vlc_value_t *p_val)
static void FreeString (vlc_value_t *p_val)
static int varcmp (const void *a, const void *b)
static variable_t * Lookup (vlc_object_t *obj, const char *psz_name)
static void Destroy (variable_t *p_var)
static void CheckValue (variable_t *var, vlc_value_t *val)
Adjusts a value to fit the constraints for a certain variable:
static void WaitUnused (vlc_object_t *obj, variable_t *var)
Waits until the variable is inactive (i.e.
static void TriggerCallback (vlc_object_t *obj, variable_t *var, const char *name, vlc_value_t prev)
static void TriggerListCallback (vlc_object_t *obj, variable_t *var, const char *name, int action, vlc_value_t *val)
int var_Create (vlc_object_t *p_this, const char *psz_name, int i_type)
Initialize a vlc variable.
void var_Destroy (vlc_object_t *p_this, const char *psz_name)
Destroy a vlc variable.
static void CleanupVar (void *var)
void var_DestroyAll (vlc_object_t *obj)
int var_Change (vlc_object_t *p_this, const char *psz_name, int i_action, vlc_value_t *p_val, vlc_value_t *p_val2)
Perform an action on a variable.
int var_GetAndSet (vlc_object_t *p_this, const char *psz_name, int i_action, vlc_value_t *p_val)
Perform a Get and Set on a variable.
int var_Type (vlc_object_t *p_this, const char *psz_name)
Request a variable's type.
int var_SetChecked (vlc_object_t *p_this, const char *psz_name, int expected_type, vlc_value_t val)
int var_Set (vlc_object_t *p_this, const char *psz_name, vlc_value_t val)
Set a variable's value.
int var_GetChecked (vlc_object_t *p_this, const char *psz_name, int expected_type, vlc_value_t *p_val)
int var_Get (vlc_object_t *p_this, const char *psz_name, vlc_value_t *p_val)
Get a variable's value.
static void AddCallback (vlc_object_t *p_this, const char *psz_name, callback_entry_t entry, vlc_callback_type_t i_type)
void var_AddCallback (vlc_object_t *p_this, const char *psz_name, vlc_callback_t pf_callback, void *p_data)
Register a callback in a variable.
static void DelCallback (vlc_object_t *p_this, const char *psz_name, callback_entry_t entry, vlc_callback_type_t i_type)
void var_DelCallback (vlc_object_t *p_this, const char *psz_name, vlc_callback_t pf_callback, void *p_data)
Remove a callback from a variable.
void var_TriggerCallback (vlc_object_t *p_this, const char *psz_name)
Trigger callback on a variable.
void var_AddListCallback (vlc_object_t *p_this, const char *psz_name, vlc_list_callback_t pf_callback, void *p_data)
Register a callback for a list variable.
void var_DelListCallback (vlc_object_t *p_this, const char *psz_name, vlc_list_callback_t pf_callback, void *p_data)
Remove a callback from a list variable.
void var_OptionParse (vlc_object_t *p_obj, const char *psz_option, bool trusted)
Parse a stringified option This function parse a string option and create the associated object variable The option must be of the form "[no[-]]foo[=bar]" where foo is the option name and bar is the value of the option.
int var_LocationParse (vlc_object_t *obj, const char *mrl, const char *pref)
Parses a set of colon-separated or semicolon-separated name=value pairs.
int var_Inherit (vlc_object_t *p_this, const char *psz_name, int i_type, vlc_value_t *p_val)
Finds the value of a variable.
int var_InheritURational (vlc_object_t *object, unsigned *num, unsigned *den, const char *var)
It inherits a string as an unsigned rational number (it also accepts basic float number).
void var_FreeList (vlc_value_t *p_val, vlc_value_t *p_val2)
Free a list and the associated strings.
static void DumpVariable (const void *data, const VISIT which, const int depth)
void DumpVariables (vlc_object_t *obj)
static void TwalkGetNames (const void *data, const VISIT which, const int depth)
char ** var_GetAllNames (vlc_object_t *obj)
Return a list of all variable names.
Variables
static const struct variable_ops_t void_ops = { NULL, DupDummy, FreeDummy, }
static const struct variable_ops_t addr_ops = { CmpAddress, DupDummy, FreeDummy, }
static const struct variable_ops_t bool_ops = { CmpBool, DupDummy, FreeDummy, }
static const struct variable_ops_t float_ops = { CmpFloat, DupDummy, FreeDummy, }
static const struct variable_ops_t int_ops = { CmpInt, DupDummy, FreeDummy, }
static const struct variable_ops_t string_ops = { CmpString, DupString, FreeString, }
static const struct variable_ops_t coords_ops = { NULL, DupDummy, FreeDummy, }
static thread_local void * twalk_ctx
Typedef Documentation
callback_entry_t
typedef struct callback_entry_t callback_entry_t
callback_table_t
typedef struct callback_table_t callback_table_t
variable_ops_t
typedef struct variable_ops_t variable_ops_t
Enumeration Type Documentation
vlc_callback_type_t
enum vlc_callback_type_t
Enumerator
vlc_value_callback
vlc_list_callback
Function Documentation
AddCallback()
static void AddCallback (vlc_object_t * p_this, const char * psz_name, callback_entry_t entry, vlc_callback_type_t i_type) static
References callback_table_t::i_entries, i_type, variable_t::list_callbacks, Lookup(), msg_Err, callback_table_t::p_entries, psz_name, TAB_APPEND, variable_t::value_callbacks, vlc_object_internals::var_lock, vlc_internals, vlc_mutex_unlock(), vlc_value_callback, and WaitUnused().
Referenced by var_AddCallback(), and var_AddListCallback().
CheckValue()
static void CheckValue (variable_t * var, vlc_value_t * val) static
Adjusts a value to fit the constraints for a certain variable:
If the value is lower than the minimum, use the minimum.
If the value is higher than the maximum, use the maximum.
If the variable has steps, round the value to the nearest step.
References vlc_value_t::f_float, vlc_value_t::i_int, variable_t::i_type, variable_t::max, variable_t::min, variable_t::step, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_TYPE.
Referenced by var_Change(), var_GetAndSet(), and var_SetChecked().
CleanupVar()
static void CleanupVar (void * var) static
References Destroy().
Referenced by var_DestroyAll().
CmpAddress()
static int CmpAddress (vlc_value_t v, vlc_value_t w) static
References vlc_value_t::p_address.
CmpBool()
static int CmpBool (vlc_value_t v, vlc_value_t w) static
References vlc_value_t::b_bool.
CmpFloat()
static int CmpFloat (vlc_value_t v, vlc_value_t w) static
References vlc_value_t::f_float.
CmpInt()
static int CmpInt (vlc_value_t v, vlc_value_t w) static
References vlc_value_t::i_int.
CmpString()
static int CmpString (vlc_value_t v, vlc_value_t w) static
References vlc_value_t::psz_string.
DelCallback()
static void DelCallback (vlc_object_t * p_this, const char * psz_name, callback_entry_t entry, vlc_callback_type_t i_type) static
References callback_table_t::i_entries, i_type, variable_t::list_callbacks, Lookup(), msg_Err, callback_entry_t::p_callback, callback_entry_t::p_data, callback_table_t::p_entries, psz_name, TAB_ERASE, variable_t::value_callbacks, vlc_object_internals::var_lock, vlc_assert_unreachable, vlc_internals, vlc_mutex_unlock(), vlc_value_callback, and WaitUnused().
Referenced by var_DelCallback(), and var_DelListCallback().
Destroy()
static void Destroy (variable_t * p_var) static
References variable_t::choices, variable_t::choices_text, vlc_list_t::i_count, variable_t::ops, callback_table_t::p_entries, vlc_list_t::p_values, variable_ops_t::pf_free, variable_t::psz_name, vlc_value_t::psz_string, variable_t::psz_text, variable_t::val, and variable_t::value_callbacks.
Referenced by CleanupVar(), var_Create(), and var_Destroy().
DumpVariable()
static void DumpVariable (const void * data, const VISIT which, const int depth) static
References vlc_value_t::b_bool, vlc_value_t::coords, vlc_value_t::f_float, callback_table_t::i_entries, vlc_value_t::i_int, variable_t::i_type, leaf, vlc_value_t::p_address, postorder, variable_t::psz_name, vlc_value_t::psz_string, variable_t::psz_text, variable_t::val, variable_t::value_callbacks, VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_CLASS, VLC_VAR_COORDS, VLC_VAR_FLOAT, VLC_VAR_HASCHOICE, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_STRING, VLC_VAR_TYPE, VLC_VAR_VOID, vlc_value_t::x, and vlc_value_t::y.
Referenced by DumpVariables().
DumpVariables()
void DumpVariables (vlc_object_t * obj)
References DumpVariable(), twalk(), vlc_internals, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by VarsCommand().
DupDummy()
static void DupDummy (vlc_value_t * p_val) static
DupString()
static void DupString (vlc_value_t * p_val) static
References vlc_value_t::psz_string, and strdup().
FreeDummy()
static void FreeDummy (vlc_value_t * p_val) static
Referenced by var_Change().
FreeString()
static void FreeString (vlc_value_t * p_val) static
References vlc_value_t::psz_string.
Lookup()
static variable_t * Lookup (vlc_object_t * obj, const char * psz_name) static
References psz_name, tfind(), vlc_object_internals::var_lock, vlc_object_internals::var_root, varcmp(), vlc_internals, and vlc_mutex_lock().
Referenced by AddCallback(), DelCallback(), var_Change(), var_Destroy(), var_GetAndSet(), var_GetChecked(), var_SetChecked(), var_TriggerCallback(), and var_Type().
TriggerCallback()
static void TriggerCallback (vlc_object_t * obj, variable_t * var, const char * name, vlc_value_t prev) static
References variable_t::b_incallback, count, callback_table_t::i_entries, name, callback_entry_t::p_data, callback_table_t::p_entries, variable_t::val, variable_t::value_callbacks, vlc_object_internals::var_lock, vlc_object_internals::var_wait, vlc_cond_broadcast(), vlc_internals, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by var_GetAndSet(), var_SetChecked(), and var_TriggerCallback().
TriggerListCallback()
static void TriggerListCallback (vlc_object_t * obj, variable_t * var, const char * name, int action, vlc_value_t * val) static
References variable_t::b_incallback, count, callback_table_t::i_entries, variable_t::list_callbacks, name, callback_table_t::p_entries, vlc_object_internals::var_lock, vlc_object_internals::var_wait, vlc_cond_broadcast(), vlc_internals, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by var_Change().
TwalkGetNames()
static void TwalkGetNames (const void * data, const VISIT which, const int depth) static
References ARRAY_APPEND, DECL_ARRAY, leaf, postorder, variable_t::psz_name, strdup(), and twalk_ctx.
Referenced by var_GetAllNames().
var_AddCallback()
void var_AddCallback (vlc_object_t * p_this, const char * psz_name, vlc_callback_t pf_callback, void * p_data)
Register a callback in a variable.
We store a function pointer that will be called upon variable modification.
Parameters
p_this The object that holds the variable
psz_name The name of the variable
pf_callback The function pointer
p_data A generic pointer that will be passed as the last argument to the callback function.
Warning
The callback function is run in the thread that calls var_Set on the variable. Use proper locking. This thread may not have much time to spare, so keep callback functions short.
References AddCallback(), psz_name, and vlc_value_callback.
var_AddListCallback()
void var_AddListCallback (vlc_object_t * p_this, const char * psz_name, vlc_list_callback_t pf_callback, void * p_data)
Register a callback for a list variable.
The callback is triggered when an element is added/removed from the list or when the list is cleared.
See var_AddCallback().
References AddCallback(), psz_name, and vlc_list_callback.
var_Change()
int var_Change (vlc_object_t * p_this, const char * psz_name, int i_action, vlc_value_t * p_val, vlc_value_t * p_val2)
Perform an action on a variable.
Parameters
p_this The object that holds the variable
psz_name The name of the variable
i_action The action to perform. Must be one of Variable actions
p_val First action parameter
p_val2 Second action parameter
< No error
< Variable not found
< Unspecified error
< Unspecified error
< Unspecified error
< No error
< Unspecified error
References CheckValue(), variable_t::choices, variable_t::choices_text, vlc_value_t::f_float, FreeDummy(), vlc_list_t::i_count, vlc_value_t::i_int, variable_t::i_type, vlc_list_t::i_type, Lookup(), variable_t::max, variable_t::min, variable_t::ops, vlc_value_t::p_list, vlc_list_t::p_values, variable_ops_t::pf_cmp, variable_ops_t::pf_dup, variable_ops_t::pf_free, psz_name, vlc_value_t::psz_string, variable_t::psz_text, variable_t::step, strdup(), TAB_APPEND, TAB_ERASE, TriggerListCallback(), variable_t::val, vlc_object_internals::var_lock, VLC_EGENERIC, VLC_ENOVAR, vlc_internals, vlc_mutex_unlock(), VLC_SUCCESS, VLC_VAR_ADDCHOICE, VLC_VAR_CHOICESCOUNT, VLC_VAR_CLEARCHOICES, VLC_VAR_DELCHOICE, VLC_VAR_FLOAT, VLC_VAR_GETCHOICES, VLC_VAR_GETMAX, VLC_VAR_GETMIN, VLC_VAR_GETSTEP, VLC_VAR_GETTEXT, VLC_VAR_INTEGER, VLC_VAR_SETMINMAX, VLC_VAR_SETSTEP, VLC_VAR_SETTEXT, VLC_VAR_SETVALUE, VLC_VAR_STRING, VLC_VAR_TYPE, and xmalloc().
var_Create()
int var_Create (vlc_object_t * p_this, const char * psz_name, int i_type)
Initialize a vlc variable.
We hash the given string and insert it into the sorted list. The insertion may require slow memory copies, but think about what we gain in the log(n) lookup phase when setting/getting the variable value!
Parameters
p_this The object in which to create the variable
psz_name The name of the variable
i_type The variables type. Must be one of Variable types combined with zero or more Additive flags
< Not enough memory
< No error
< Not enough memory
References addr_ops, vlc_value_t::b_bool, variable_t::b_incallback, bool_ops, variable_t::choices, variable_t::choices_text, vlc_value_t::coords, coords_ops, Destroy(), vlc_value_t::f_float, float_ops, vlc_list_t::i_count, vlc_value_t::i_int, i_type, variable_t::i_type, variable_t::i_usage, int_ops, variable_t::max, variable_t::min, variable_t::ops, vlc_value_t::p_address, vlc_list_t::p_values, psz_name, variable_t::psz_name, vlc_value_t::psz_string, variable_t::psz_text, strdup(), string_ops, tsearch(), unlikely, variable_t::val, variable_t::value_callbacks, var_Inherit(), vlc_object_internals::var_lock, vlc_object_internals::var_root, varcmp(), vlc_assert_unreachable, VLC_ENOMEM, vlc_internals, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_CLASS, VLC_VAR_COORDS, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_STRING, VLC_VAR_VOID, void_ops, vlc_value_t::x, and vlc_value_t::y.
var_DelCallback()
void var_DelCallback (vlc_object_t * p_this, const char * psz_name, vlc_callback_t pf_callback, void * p_data)
Remove a callback from a variable.
pf_callback and p_data have to be given again, because different objects might have registered the same callback function.
References DelCallback(), psz_name, and vlc_value_callback.
var_DelListCallback()
void var_DelListCallback (vlc_object_t * p_this, const char * psz_name, vlc_list_callback_t pf_callback, void * p_data)
Remove a callback from a list variable.
See var_DelCallback().
References DelCallback(), psz_name, and vlc_list_callback.
var_Destroy()
void var_Destroy (vlc_object_t * p_this, const char * psz_name)
Destroy a vlc variable.
Look for the variable and destroy it if it is found. As in var_Create we do a call to memmove() but we have performance counterparts elsewhere.
Parameters
p_this The object that holds the variable
psz_name The name of the variable
References variable_t::b_incallback, Destroy(), variable_t::i_usage, Lookup(), msg_Dbg, psz_name, tdelete(), vlc_object_internals::var_lock, vlc_object_internals::var_root, varcmp(), vlc_internals, and vlc_mutex_unlock().
var_DestroyAll()
void var_DestroyAll (vlc_object_t * obj)
References CleanupVar(), tdestroy(), vlc_object_internals::var_root, and vlc_internals.
Referenced by vlc_object_destroy().
var_Get()
int var_Get (vlc_object_t * p_this, const char * psz_name, vlc_value_t * p_val)
Get a variable's value.
Parameters
p_this The object that holds the variable
psz_name The name of the variable
p_val Pointer to a vlc_value_t that will hold the variable's value after the function is finished
References psz_name, and var_GetChecked.
var_GetAllNames()
char ** var_GetAllNames (vlc_object_t * obj)
Return a list of all variable names.
There is no warranty that the returned variables will be still alive after the return of this function.
Returns
a NULL terminated list of char *, each elements and the return value must be freed by the caller
References ARRAY_APPEND, ARRAY_INIT, DECL_ARRAY, twalk(), twalk_ctx, TwalkGetNames(), vlc_object_internals::var_lock, vlc_object_internals::var_root, vlc_internals, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by filter_AddProxyCallbacks(), and filter_DelProxyCallbacks().
var_GetChecked()
int var_GetChecked (vlc_object_t * p_this, const char * psz_name, int expected_type, vlc_value_t * p_val)
< No error
< Variable not found
References variable_t::i_type, Lookup(), variable_t::ops, variable_ops_t::pf_dup, psz_name, variable_t::val, vlc_object_internals::var_lock, VLC_ENOVAR, vlc_internals, vlc_mutex_unlock(), VLC_SUCCESS, VLC_VAR_CLASS, and VLC_VAR_VOID.
var_InheritURational()
int var_InheritURational (vlc_object_t * object, unsigned * num, unsigned * den, const char * var)
It inherits a string as an unsigned rational number (it also accepts basic float number).
It returns an error if the rational number cannot be parsed (0/0 is valid). The rational is already reduced.
< No error
< Unspecified error
References var_InheritString, VLC_EGENERIC, VLC_SUCCESS, and vlc_ureduce().
var_LocationParse()
int var_LocationParse (vlc_object_t * obj, const char * mrl, const char * pref)
Parses a set of colon-separated or semicolon-separated name=value pairs.
Some access (or access_demux) plugins uses this scheme in media resource location.
Note
Only trusted/safe variables are allowed. This is intended.
Warning
Only use this for plugins implementing VLC-specific resource location schemes. This would not make any sense for standardized ones.
Parameters
obj VLC object on which to set variables (and emit error messages)
mrl string to parse
pref prefix to prepend to option names in the string
Returns
VLC_ENOMEM on error, VLC_SUCCESS on success.
< No error
< Not enough memory
References likely, var_OptionParse(), VLC_ENOMEM, and VLC_SUCCESS.
var_OptionParse()
void var_OptionParse (vlc_object_t * p_obj, const char * psz_option, bool trusted)
Parse a stringified option This function parse a string option and create the associated object variable The option must be of the form "[no[-]]foo[=bar]" where foo is the option name and bar is the value of the option.
Parameters
p_obj the object in which the variable must be created
psz_option the option to parse
trusted whether the option is set by a trusted input or not
Returns
nothing
References vlc_value_t::b_bool, config_GetType(), config_IsSafe(), vlc_value_t::f_float, vlc_value_t::i_int, i_type, msg_Err, psz_name, vlc_value_t::psz_string, psz_value, strdup(), strtoll(), us_atof(), var_Create, var_Set, VLC_VAR_BOOL, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_STRING.
Referenced by input_item_ApplyOptions(), and var_LocationParse().
var_Set()
int var_Set (vlc_object_t * p_this, const char * psz_name, vlc_value_t val)
Set a variable's value.
Parameters
p_this The object that hold the variable
psz_name The name of the variable
val the value to set
References psz_name, and var_SetChecked.
var_SetChecked()
int var_SetChecked (vlc_object_t * p_this, const char * psz_name, int expected_type, vlc_value_t val)
< Variable not found
< No error
References CheckValue(), variable_t::i_type, Lookup(), variable_t::ops, variable_ops_t::pf_dup, variable_ops_t::pf_free, psz_name, TriggerCallback(), variable_t::val, vlc_object_internals::var_lock, VLC_ENOVAR, vlc_internals, vlc_mutex_unlock(), VLC_SUCCESS, VLC_VAR_CLASS, VLC_VAR_VOID, and WaitUnused().
var_TriggerCallback()
void var_TriggerCallback (vlc_object_t * p_this, const char * psz_name)
Trigger callback on a variable.
Parameters
p_this The object that hold the variable
psz_name The name of the variable
References Lookup(), psz_name, TriggerCallback(), variable_t::val, vlc_object_internals::var_lock, vlc_internals, vlc_mutex_unlock(), and WaitUnused().
var_Type()
int var_Type (vlc_object_t * p_this, const char * psz_name)
Request a variable's type.
Returns
The variable type if it exists, or 0 if the variable could not be found.
See also
Variable types
References variable_t::choices, vlc_list_t::i_count, i_type, variable_t::i_type, Lookup(), psz_name, vlc_object_internals::var_lock, vlc_internals, vlc_mutex_unlock(), and VLC_VAR_HASCHOICE.
varcmp()
static int varcmp (const void * a, const void * b) static
References variable_t::psz_name.
Referenced by Lookup(), var_Create(), and var_Destroy().
WaitUnused()
static void WaitUnused (vlc_object_t * obj, variable_t * var) static
Waits until the variable is inactive (i.e.
not executing a callback)
References variable_t::b_incallback, mutex_cleanup_push, vlc_object_internals::var_lock, vlc_object_internals::var_wait, vlc_cleanup_pop, vlc_cond_wait(), and vlc_internals.
Referenced by AddCallback(), DelCallback(), var_GetAndSet(), var_SetChecked(), and var_TriggerCallback().
Variable Documentation
addr_ops
const struct variable_ops_t addr_ops = { CmpAddress, DupDummy, FreeDummy, } static
Referenced by var_Create().
bool_ops
const struct variable_ops_t bool_ops = { CmpBool, DupDummy, FreeDummy, } static
Referenced by var_Create().
coords_ops
const struct variable_ops_t coords_ops = { NULL, DupDummy, FreeDummy, } static
Referenced by var_Create().
float_ops
const struct variable_ops_t float_ops = { CmpFloat, DupDummy, FreeDummy, } static
Referenced by var_Create().
int_ops
const struct variable_ops_t int_ops = { CmpInt, DupDummy, FreeDummy, } static
Referenced by var_Create().
string_ops
const struct variable_ops_t string_ops = { CmpString, DupString, FreeString, } static
Referenced by var_Create().
twalk_ctx
thread_local void* twalk_ctx static
Referenced by TwalkGetNames(), and var_GetAllNames().
void_ops
const struct variable_ops_t void_ops = { NULL, DupDummy, FreeDummy, } static
Referenced by var_Create().