VLC: src/version.c File Reference
version.c File Reference
Macros
#define DECLARE_VLC_VERSION(func, var)
Functions
const char * VLC_CompileBy (void)
const char * VLC_CompileHost (void)
const char * VLC_Compiler (void)
Macro Definition Documentation
DECLARE_VLC_VERSION
#define DECLARE_VLC_VERSION (func, var)
Value:
const char * VLC_##func (void)                                            \
{                                                                           \
    return VLC_##var ;                                                      \
}
Function Documentation
VLC_CompileBy()
const char * VLC_CompileBy (void)
Referenced by Version().
VLC_CompileHost()
const char * VLC_CompileHost (void)
Referenced by Version().
VLC_Compiler()
const char * VLC_Compiler (void)
Referenced by Version().