VLC: src/video_output/video_text.c File Reference
video_text.c File Reference
Data Structures
struct subpicture_updater_sys_t
Functions
static int OSDTextValidate (subpicture_t *subpic, bool has_src_changed, const video_format_t *fmt_src, bool has_dst_changed, const video_format_t *fmt_dst, mtime_t ts)
static void OSDTextUpdate (subpicture_t *subpic, const video_format_t *fmt_src, const video_format_t *fmt_dst, mtime_t ts)
static void OSDTextDestroy (subpicture_t *subpic)
void vout_OSDText (vout_thread_t *vout, int channel, int position, mtime_t duration, const char *text)
Write an informative message if the OSD option is enabled.
void vout_OSDMessage (vout_thread_t *vout, int channel, const char *format,...)
Write an informative message at the default location, for the default duration and only if the OSD option is enabled.
Function Documentation
OSDTextDestroy()
static void OSDTextDestroy (subpicture_t * subpic) static
References subpicture_updater_t::p_sys, subpicture_updater_sys_t::text, and subpicture_t::updater.
Referenced by vout_OSDText().
OSDTextUpdate()
static void OSDTextUpdate (subpicture_t * subpic, const video_format_t * fmt_src, const video_format_t * fmt_dst, mtime_t ts) static
References subpicture_t::b_absolute, subpicture_region_t::fmt, subpicture_region_t::i_align, subpicture_t::i_original_picture_height, subpicture_t::i_original_picture_width, video_format_t::i_sar_den, video_format_t::i_sar_num, subpicture_region_t::i_text_align, video_format_t::i_visible_height, video_format_t::i_visible_width, subpicture_region_t::i_x, video_format_t::i_x_offset, subpicture_region_t::i_y, video_format_t::i_y_offset, video_format_t::mastering, subpicture_t::p_region, subpicture_updater_t::p_sys, subpicture_region_t::p_text, subpicture_updater_sys_t::position, video_format_t::primaries, video_format_t::space, SUBPICTURE_ALIGN_BOTTOM, SUBPICTURE_ALIGN_LEFT, SUBPICTURE_ALIGN_RIGHT, SUBPICTURE_ALIGN_TOP, subpicture_region_New(), subpicture_updater_sys_t::text, text_segment_New(), video_format_t::transfer, subpicture_t::updater, video_format_Init(), VLC_CODEC_TEXT, and VLC_UNUSED.
Referenced by vout_OSDText().
OSDTextValidate()
static int OSDTextValidate (subpicture_t * subpic, bool has_src_changed, const video_format_t * fmt_src, bool has_dst_changed, const video_format_t * fmt_dst, mtime_t ts) static
< No error
< Unspecified error
References VLC_EGENERIC, VLC_SUCCESS, and VLC_UNUSED.
Referenced by vout_OSDText().