VLC: src/video_output/video_output.c File Reference
video_output.c File Reference
Data Structures
struct vout_filter_t
Macros
#define VOUT_REDISPLAY_DELAY (INT64_C(80000))
#define VOUT_DISPLAY_LATE_THRESHOLD (INT64_C(20000))
Late pictures having a delay higher than this value are thrashed.
#define VOUT_MWAIT_TOLERANCE (INT64_C(4000))
Functions
static void * Thread (void *)
static void VoutDestructor (vlc_object_t *)
static int VoutValidateFormat (video_format_t *dst, const video_format_t *src)
static void VideoFormatCopyCropAr (video_format_t *dst, const video_format_t *src)
static bool VideoFormatIsCropArEqual (video_format_t *dst, const video_format_t *src)
static vout_thread_t * VoutCreate (vlc_object_t *object, const vout_configuration_t *cfg)
vout_thread_t * vout_Request (vlc_object_t *object, const vout_configuration_t *cfg)
Returns a suitable vout or release the given one.
void vout_Close (vout_thread_t *vout)
This function will close a vout created by vout_Request.
void vout_Cancel (vout_thread_t *vout, bool canceled)
void vout_ChangePause (vout_thread_t *vout, bool is_paused, mtime_t date)
This function will (un)pause the display of pictures.
void vout_GetResetStatistic (vout_thread_t *vout, unsigned *restrict displayed, unsigned *restrict lost)
void vout_Flush (vout_thread_t *vout, mtime_t date)
This function will ensure that all ready/displayed pictures have at most the provided date.
bool vout_IsEmpty (vout_thread_t *vout)
This function will return true if no more pictures are to be displayed.
void vout_NextPicture (vout_thread_t *vout, mtime_t *duration)
This function will force to display the next picture while paused.
void vout_DisplayTitle (vout_thread_t *vout, const char *title)
This function will ask the display of the input title.
void vout_WindowMouseEvent (vout_thread_t *vout, const vout_window_mouse_event_t *mouse)
void vout_PutSubpicture (vout_thread_t *vout, subpicture_t *subpic)
int vout_RegisterSubpictureChannel (vout_thread_t *vout)
void vout_FlushSubpictureChannel (vout_thread_t *vout, int channel)
picture_t * vout_GetPicture (vout_thread_t *vout)
Allocates a video output picture buffer.
void vout_PutPicture (vout_thread_t *vout, picture_t *picture)
It gives to the vout a picture to be displayed.
int vout_GetSnapshot (vout_thread_t *vout, block_t **image_dst, picture_t **picture_dst, video_format_t *fmt, const char *type, mtime_t timeout)
This function will handle a snapshot request.
void vout_ChangeAspectRatio (vout_thread_t *p_vout, unsigned int i_num, unsigned int i_den)
void vout_ControlChangeFullscreen (vout_thread_t *vout, bool fullscreen)
void vout_ControlChangeWindowState (vout_thread_t *vout, unsigned st)
void vout_ControlChangeDisplayFilled (vout_thread_t *vout, bool is_filled)
void vout_ControlChangeZoom (vout_thread_t *vout, int num, int den)
void vout_ControlChangeSampleAspectRatio (vout_thread_t *vout, unsigned num, unsigned den)
void vout_ControlChangeCropRatio (vout_thread_t *vout, unsigned num, unsigned den)
void vout_ControlChangeCropWindow (vout_thread_t *vout, int x, int y, int width, int height)
void vout_ControlChangeCropBorder (vout_thread_t *vout, int left, int top, int right, int bottom)
void vout_ControlChangeFilters (vout_thread_t *vout, const char *filters)
void vout_ControlChangeSubSources (vout_thread_t *vout, const char *filters)
void vout_ControlChangeSubFilters (vout_thread_t *vout, const char *filters)
void vout_ControlChangeSubMargin (vout_thread_t *vout, int margin)
void vout_ControlChangeViewpoint (vout_thread_t *vout, const vlc_viewpoint_t *p_viewpoint)
static void VoutGetDisplayCfg (vout_thread_t *vout, vout_display_cfg_t *cfg, const char *title)
vout_window_t * vout_NewDisplayWindow (vout_thread_t *vout, unsigned type)
void vout_DeleteDisplayWindow (vout_thread_t *vout, vout_window_t *window)
void vout_SetDisplayWindowSize (vout_thread_t *vout, unsigned width, unsigned height)
int vout_HideWindowMouse (vout_thread_t *vout, bool hide)
static int FilterRestartCallback (vlc_object_t *p_this, char const *psz_var, vlc_value_t oldval, vlc_value_t newval, void *p_data)
static int ThreadDelFilterCallbacks (filter_t *filter, void *opaque)
static void ThreadDelAllFilterCallbacks (vout_thread_t *vout)
static picture_t * VoutVideoFilterInteractiveNewPicture (filter_t *filter)
static picture_t * VoutVideoFilterStaticNewPicture (filter_t *filter)
static void ThreadFilterFlush (vout_thread_t *vout, bool is_locked)
static void ThreadChangeFilters (vout_thread_t *vout, const video_format_t *source, const char *filters, int deinterlace, bool is_locked)
static int ThreadDisplayPreparePicture (vout_thread_t *vout, bool reuse, bool frame_by_frame)
static picture_t * ConvertRGB32AndBlendBufferNew (filter_t *filter)
static picture_t * ConvertRGB32AndBlend (vout_thread_t *vout, picture_t *pic, subpicture_t *subpic)
static int ThreadDisplayRenderPicture (vout_thread_t *vout, bool is_forced)
static int ThreadDisplayPicture (vout_thread_t *vout, mtime_t *deadline)
static void ThreadDisplaySubpicture (vout_thread_t *vout, subpicture_t *subpicture)
static void ThreadFlushSubpicture (vout_thread_t *vout, int channel)
static void ThreadDisplayOsdTitle (vout_thread_t *vout, const char *string)
static void ThreadChangeSubSources (vout_thread_t *vout, const char *filters)
static void ThreadChangeSubFilters (vout_thread_t *vout, const char *filters)
static void ThreadChangeSubMargin (vout_thread_t *vout, int margin)
static void ThreadChangePause (vout_thread_t *vout, bool is_paused, mtime_t date)
static void ThreadFlush (vout_thread_t *vout, bool below, mtime_t date)
static void ThreadStep (vout_thread_t *vout, mtime_t *duration)
static void ThreadChangeFullscreen (vout_thread_t *vout, bool fullscreen)
static void ThreadChangeWindowState (vout_thread_t *vout, unsigned state)
static void ThreadChangeWindowMouse (vout_thread_t *vout, const vout_window_mouse_event_t *mouse)
static void ThreadChangeDisplayFilled (vout_thread_t *vout, bool is_filled)
static void ThreadChangeZoom (vout_thread_t *vout, int num, int den)
static void ThreadChangeAspectRatio (vout_thread_t *vout, unsigned num, unsigned den)
static void ThreadExecuteCropWindow (vout_thread_t *vout, unsigned x, unsigned y, unsigned width, unsigned height)
static void ThreadExecuteCropBorder (vout_thread_t *vout, unsigned left, unsigned top, unsigned right, unsigned bottom)
static void ThreadExecuteCropRatio (vout_thread_t *vout, unsigned num, unsigned den)
static void ThreadExecuteViewpoint (vout_thread_t *vout, const vlc_viewpoint_t *p_viewpoint)
static int ThreadStart (vout_thread_t *vout, vout_display_state_t *state)
static void ThreadStop (vout_thread_t *vout, vout_display_state_t *state)
static void ThreadInit (vout_thread_t *vout)
static void ThreadClean (vout_thread_t *vout)
static int ThreadReinit (vout_thread_t *vout, const vout_configuration_t *cfg)
static void ThreadCancel (vout_thread_t *vout, bool canceled)
static int ThreadControl (vout_thread_t *vout, vout_control_cmd_t cmd)
Macro Definition Documentation
VOUT_DISPLAY_LATE_THRESHOLD
#define VOUT_DISPLAY_LATE_THRESHOLD (INT64_C(20000))
Late pictures having a delay higher than this value are thrashed.
Referenced by ThreadDisplayPreparePicture().
VOUT_MWAIT_TOLERANCE
#define VOUT_MWAIT_TOLERANCE (INT64_C(4000))
Referenced by ThreadDisplayPicture().
VOUT_REDISPLAY_DELAY
#define VOUT_REDISPLAY_DELAY (INT64_C(80000))
Referenced by ThreadDisplayPicture().
Function Documentation
ConvertRGB32AndBlend()
static picture_t * ConvertRGB32AndBlend (vout_thread_t * vout, picture_t * pic, subpicture_t * subpic) static
References filter_owner_t::buffer_new, ConvertRGB32AndBlendBufferNew(), filter_chain_AppendConverter(), filter_chain_Delete(), filter_chain_NewVideo, filter_chain_VideoFilter(), filter_DeleteBlend(), filter_NewBlend(), filter_t::fmt_out, video_format_t::i_chroma, vout_thread_t::p, picture_BlendSubpicture(), picture_Hold(), picture_Release(), vout_thread_sys_t::spu_blend, es_format_t::video, filter_owner_t::video, video_format_FixRgb(), VLC_CODEC_RGB32, and VLC_OBJECT.
Referenced by ThreadDisplayRenderPicture().
ConvertRGB32AndBlendBufferNew()
static picture_t * ConvertRGB32AndBlendBufferNew (filter_t * filter) static
References filter_t::fmt_out, picture_NewFromFormat(), and es_format_t::video.
Referenced by ConvertRGB32AndBlend().
FilterRestartCallback()
static int FilterRestartCallback (vlc_object_t * p_this, char const * psz_var, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
References vout_ControlChangeFilters().
Referenced by ThreadChangeFilters(), and ThreadDelFilterCallbacks().
Thread()
static void * Thread (void * object) static
< No error
References vout_thread_sys_t::control, vout_thread_sys_t::displayed, vout_thread_sys_t::is_interlaced, mdate(), vout_thread_t::p, ThreadControl(), ThreadDisplayPicture(), VLC_SUCCESS, VLC_TS_INVALID, vout_control_Pop(), vout_ManageWrapper(), and vout_SetInterlacingState().
Referenced by VoutCreate().
ThreadCancel()
static void ThreadCancel (vout_thread_t * vout, bool canceled) static
References vout_thread_sys_t::decoder_pool, vout_thread_t::p, and picture_pool_Cancel().
Referenced by ThreadControl().
ThreadChangeAspectRatio()
static void ThreadChangeAspectRatio (vout_thread_t * vout, unsigned num, unsigned den) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayAspect().
Referenced by ThreadControl().
ThreadChangeDisplayFilled()
static void ThreadChangeDisplayFilled (vout_thread_t * vout, bool is_filled) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayFilled().
Referenced by ThreadControl().
ThreadChangeFilters()
static void ThreadChangeFilters (vout_thread_t * vout, const video_format_t * source, const char * filters, int deinterlace, bool is_locked) static
References vout_filter_t::cfg, vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, config_ChainCreate(), config_ChainDestroy(), vout_thread_sys_t::configuration, es_format_Clean(), es_format_InitFromVideo(), es_format_IsSimilar(), vout_thread_sys_t::filter, filter_AddProxyCallbacks, filter_chain_AppendConverter(), filter_chain_AppendFilter(), filter_chain_GetFmtOut(), filter_chain_Reset(), FilterRestartCallback(), vout_thread_sys_t::format, vout_thread_sys_t::has_deint, likely, vout_thread_sys_t::lock, msg_Dbg, msg_Err, name, vout_filter_t::name, vout_thread_t::p, strdup(), ThreadDelAllFilterCallbacks(), ThreadFilterFlush(), video_format_Clean(), video_format_Copy(), vlc_array_append_or_abort(), vlc_array_clear(), vlc_array_count(), vlc_array_init(), vlc_array_item_at_index, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadControl(), and ThreadDisplayPreparePicture().
ThreadChangeFullscreen()
static void ThreadChangeFullscreen (vout_thread_t * vout, bool fullscreen) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, VLC_SUCCESS, vout_window_SetFullScreen(), and vout_thread_sys_t::window.
Referenced by ThreadControl().
ThreadChangePause()
static void ThreadChangePause (vout_thread_t * vout, bool is_paused, mtime_t date) static
References picture_t::date, vout_thread_sys_t::date, vout_thread_sys_t::decoded, vout_thread_sys_t::decoder_fifo, vout_thread_sys_t::displayed, vout_thread_sys_t::is_on, vout_thread_sys_t::last, vout_thread_t::p, vout_thread_sys_t::pause, picture_fifo_OffsetDate(), vout_thread_sys_t::spu, spu_OffsetSubtitleDate(), vout_thread_sys_t::step, ThreadFilterFlush(), vout_thread_sys_t::timestamp, VLC_TS_INVALID, vout_window_SetInhibition(), and vout_thread_sys_t::window.
Referenced by ThreadControl().
ThreadChangeSubFilters()
static void ThreadChangeSubFilters (vout_thread_t * vout, const char * filters) static
References vout_thread_t::p, vout_thread_sys_t::spu, and spu_ChangeFilters().
Referenced by ThreadControl().
ThreadChangeSubMargin()
static void ThreadChangeSubMargin (vout_thread_t * vout, int margin) static
References vout_thread_t::p, vout_thread_sys_t::spu, and spu_ChangeMargin().
Referenced by ThreadControl().
ThreadChangeSubSources()
static void ThreadChangeSubSources (vout_thread_t * vout, const char * filters) static
References vout_thread_t::p, vout_thread_sys_t::spu, and spu_ChangeSources().
Referenced by ThreadControl().
ThreadChangeWindowMouse()
static void ThreadChangeWindowMouse (vout_thread_t * vout, const vout_window_mouse_event_t * mouse) static
References vout_window_mouse_event_t::button_mask, vout_display_t::cfg, vout_thread_sys_t::display, vout_display_place_t::height, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, vout_thread_t::p, vout_display_t::source, vout_window_mouse_event_t::type, vout_thread_sys_t::vd, vlc_assert_unreachable, vout_display_PlacePicture(), vout_display_SendEventMouseDoubleClick(), vout_display_SendEventMouseMoved(), vout_display_SendEventMousePressed(), vout_display_SendEventMouseReleased(), vout_display_SendEventMouseState(), VOUT_WINDOW_MOUSE_DOUBLE_CLICK, VOUT_WINDOW_MOUSE_MOVED, VOUT_WINDOW_MOUSE_PRESSED, VOUT_WINDOW_MOUSE_RELEASED, VOUT_WINDOW_MOUSE_STATE, vout_display_place_t::width, vout_display_place_t::x, vout_window_mouse_event_t::x, vout_display_place_t::y, and vout_window_mouse_event_t::y.
Referenced by ThreadControl().
ThreadChangeWindowState()
static void ThreadChangeWindowState (vout_thread_t * vout, unsigned state) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, vout_window_SetState(), and vout_thread_sys_t::window.
Referenced by ThreadControl().
ThreadChangeZoom()
static void ThreadChangeZoom (vout_thread_t * vout, int num, int den) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayZoom().
Referenced by ThreadControl().
ThreadClean()
static void ThreadClean (vout_thread_t * vout) static
References vout_thread_sys_t::control, vout_thread_sys_t::dead, vout_thread_t::p, vout_thread_sys_t::render, vout_chrono_Clean(), and vout_control_Dead().
Referenced by ThreadControl(), and ThreadReinit().
ThreadControl()
static int ThreadControl (vout_thread_t * vout, vout_control_cmd_t cmd) static
References vout_control_cmd_t::a, vout_control_cmd_t::b, vout_control_cmd_t::boolean, vout_control_cmd_t::border, vout_control_cmd_t::bottom, vout_control_cmd_t::cfg, vout_thread_sys_t::configuration, vout_control_cmd_t::date, vout_thread_sys_t::filter, vout_control_cmd_t::height, vout_control_cmd_t::integer, vout_control_cmd_t::is_on, vout_control_cmd_t::left, vout_thread_t::p, vout_control_cmd_t::pair, vout_control_cmd_t::pause, vout_control_cmd_t::right, vout_control_cmd_t::string, vout_control_cmd_t::subpicture, ThreadCancel(), ThreadChangeAspectRatio(), ThreadChangeDisplayFilled(), ThreadChangeFilters(), ThreadChangeFullscreen(), ThreadChangePause(), ThreadChangeSubFilters(), ThreadChangeSubMargin(), ThreadChangeSubSources(), ThreadChangeWindowMouse(), ThreadChangeWindowState(), ThreadChangeZoom(), ThreadClean(), ThreadDisplayOsdTitle(), ThreadDisplaySubpicture(), ThreadExecuteCropBorder(), ThreadExecuteCropRatio(), ThreadExecuteCropWindow(), ThreadExecuteViewpoint(), ThreadFlush(), ThreadFlushSubpicture(), ThreadInit(), ThreadReinit(), ThreadStart(), ThreadStep(), ThreadStop(), vout_control_cmd_t::time, vout_control_cmd_t::time_ptr, vout_control_cmd_t::top, vout_control_cmd_t::type, vout_control_cmd_t::u, vout_control_cmd_t::viewpoint, VOUT_CONTROL_ASPECT_RATIO, VOUT_CONTROL_CANCEL, VOUT_CONTROL_CHANGE_FILTERS, VOUT_CONTROL_CHANGE_INTERLACE, VOUT_CONTROL_CHANGE_SUB_FILTERS, VOUT_CONTROL_CHANGE_SUB_MARGIN, VOUT_CONTROL_CHANGE_SUB_SOURCES, VOUT_CONTROL_CLEAN, vout_control_cmd_Clean(), VOUT_CONTROL_CROP_BORDER, VOUT_CONTROL_CROP_RATIO, VOUT_CONTROL_CROP_WINDOW, VOUT_CONTROL_DISPLAY_FILLED, VOUT_CONTROL_FLUSH, VOUT_CONTROL_FLUSH_SUBPICTURE, VOUT_CONTROL_FULLSCREEN, VOUT_CONTROL_INIT, VOUT_CONTROL_OSD_TITLE, VOUT_CONTROL_PAUSE, VOUT_CONTROL_REINIT, VOUT_CONTROL_STEP, VOUT_CONTROL_SUBPICTURE, VOUT_CONTROL_VIEWPOINT, VOUT_CONTROL_WINDOW_MOUSE, VOUT_CONTROL_WINDOW_STATE, VOUT_CONTROL_ZOOM, vout_control_cmd_t::width, vout_control_cmd_t::window, vout_control_cmd_t::window_mouse, vout_control_cmd_t::x, and vout_control_cmd_t::y.
Referenced by Thread().
ThreadDelAllFilterCallbacks()
static void ThreadDelAllFilterCallbacks (vout_thread_t * vout) static
References vout_thread_sys_t::chain_interactive, vout_thread_sys_t::filter, filter_chain_ForEach(), vout_thread_t::p, and ThreadDelFilterCallbacks().
Referenced by ThreadChangeFilters(), ThreadStart(), and ThreadStop().
ThreadDelFilterCallbacks()
static int ThreadDelFilterCallbacks (filter_t * filter, void * opaque) static
< No error
References filter_DelProxyCallbacks, FilterRestartCallback(), and VLC_SUCCESS.
Referenced by ThreadDelAllFilterCallbacks().
ThreadDisplayOsdTitle()
static void ThreadDisplayOsdTitle (vout_thread_t * vout, const char * string) static
References vout_thread_t::p, vout_thread_sys_t::title, vout_OSDText(), and VOUT_SPU_CHANNEL_OSD.
Referenced by ThreadControl().
ThreadDisplayPicture()
static int ThreadDisplayPicture (vout_thread_t * vout, mtime_t * deadline) static
< Unspecified error
< Unspecified error
< Unspecified error
< Unspecified error
References picture_t::b_force, vout_thread_sys_t::current, picture_t::date, vout_thread_sys_t::date, vout_thread_sys_t::displayed, vout_thread_sys_t::is_on, mdate(), vout_thread_sys_t::next, vout_thread_t::p, vout_thread_sys_t::pause, picture_Release(), vout_thread_sys_t::render, ThreadDisplayPreparePicture(), ThreadDisplayRenderPicture(), VLC_EGENERIC, VLC_TS_INVALID, vout_chrono_GetHigh(), VOUT_MWAIT_TOLERANCE, and VOUT_REDISPLAY_DELAY.
Referenced by Thread(), and ThreadStep().
ThreadDisplayPreparePicture()
static int ThreadDisplayPreparePicture (vout_thread_t * vout, bool reuse, bool frame_by_frame) static
< Unspecified error
< No error
References picture_t::b_force, picture_t::b_progressive, vout_thread_sys_t::chain_static, CLOCK_FREQ, vout_thread_sys_t::configuration, vout_thread_sys_t::current, picture_t::date, vout_thread_sys_t::decoded, vout_thread_sys_t::decoder_fifo, vout_thread_sys_t::displayed, vout_thread_sys_t::filter, filter_chain_VideoFilter(), picture_t::format, vout_thread_sys_t::format, video_format_t::i_frame_rate, video_format_t::i_frame_rate_base, vout_thread_sys_t::is_interlaced, vout_thread_sys_t::is_late_dropped, vout_thread_sys_t::is_on, vout_thread_sys_t::lock, mdate(), msg_Dbg, msg_Warn, vout_thread_sys_t::next, vout_thread_t::p, vout_thread_sys_t::pause, picture_fifo_Pop(), picture_Hold(), picture_Release(), vout_thread_sys_t::statistic, ThreadChangeFilters(), vout_thread_sys_t::timestamp, VideoFormatIsCropArEqual(), VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, VOUT_DISPLAY_LATE_THRESHOLD, and vout_statistic_AddLost().
Referenced by ThreadDisplayPicture().
ThreadDisplayRenderPicture()
static int ThreadDisplayRenderPicture (vout_thread_t * vout, bool is_forced) static
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References vout_chrono_t::avg, vout_display_t::cfg, vout_thread_sys_t::chain_interactive, ConvertRGB32AndBlend(), vout_thread_sys_t::current, picture_t::date, vout_thread_sys_t::date, vout_thread_sys_t::decoder_pool, vlc_rational_t::den, vout_display_cfg_t::display, vout_thread_sys_t::display, vout_thread_sys_t::display_pool, vout_thread_sys_t::displayed, vout_thread_sys_t::filter, filter_chain_VideoFilter(), filter_DeleteBlend(), filter_NewBlend(), vout_display_t::fmt, filter_t::fmt_out, picture_t::format, vout_display_place_t::height, video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, vout_display_t::info, vout_thread_sys_t::is_on, vout_display_info_t::is_slow, likely, vout_thread_sys_t::lock, mdate(), msg_Err, msg_Info, msg_Warn, mwait, vlc_rational_t::num, ORIENT_NORMAL, video_format_t::orientation, vout_thread_t::p, vout_thread_sys_t::pause, picture_BlendSubpicture(), picture_Copy(), picture_Hold(), picture_pool_Get(), picture_Release(), vout_thread_sys_t::private_pool, vout_thread_sys_t::render, vout_display_cfg_t::sar, vout_thread_sys_t::snapshot, vout_display_t::source, vout_thread_sys_t::spu, vout_thread_sys_t::spu_blend, vout_thread_sys_t::spu_blend_chroma, spu_Render(), vout_thread_sys_t::statistic, vout_display_info_t::subpicture_chromas, subpicture_Delete(), vout_thread_sys_t::use_dr, vout_chrono_t::var, vout_thread_sys_t::vd, es_format_t::video, video_format_ApplyRotation(), VideoFormatCopyCropAr(), VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, VLC_SUCCESS, vout_chrono_Start(), vout_chrono_Stop(), vout_display_Display(), vout_display_PlacePicture(), vout_display_Prepare(), vout_FilterDisplay(), vout_IsDisplayFiltered(), vout_snapshot_IsRequested(), vout_snapshot_Set(), vout_statistic_AddDisplayed(), vout_UpdateDisplaySourceProperties(), and vout_display_place_t::width.
Referenced by ThreadDisplayPicture().
ThreadDisplaySubpicture()
static void ThreadDisplaySubpicture (vout_thread_t * vout, subpicture_t * subpicture) static
References vout_thread_t::p, vout_thread_sys_t::spu, and spu_PutSubpicture().
Referenced by ThreadControl().
ThreadExecuteCropBorder()
static void ThreadExecuteCropBorder (vout_thread_t * vout, unsigned left, unsigned top, unsigned right, unsigned bottom) static
References vout_thread_sys_t::display, msg_Dbg, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayCrop().
Referenced by ThreadControl().
ThreadExecuteCropRatio()
static void ThreadExecuteCropRatio (vout_thread_t * vout, unsigned num, unsigned den) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayCrop().
Referenced by ThreadControl().
ThreadExecuteCropWindow()
static void ThreadExecuteCropWindow (vout_thread_t * vout, unsigned x, unsigned y, unsigned width, unsigned height) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayCrop().
Referenced by ThreadControl().
ThreadExecuteViewpoint()
static void ThreadExecuteViewpoint (vout_thread_t * vout, const vlc_viewpoint_t * p_viewpoint) static
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, and vout_SetDisplayViewpoint().
Referenced by ThreadControl().
ThreadFilterFlush()
static void ThreadFilterFlush (vout_thread_t * vout, bool is_locked) static
References vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, vout_thread_sys_t::current, vout_thread_sys_t::displayed, vout_thread_sys_t::filter, filter_chain_VideoFlush(), vout_thread_sys_t::lock, vout_thread_sys_t::next, vout_thread_t::p, picture_Release(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadChangeFilters(), ThreadChangePause(), and ThreadFlush().
ThreadFlush()
static void ThreadFlush (vout_thread_t * vout, bool below, mtime_t date) static
References picture_t::date, vout_thread_sys_t::date, vout_thread_sys_t::decoded, vout_thread_sys_t::decoder_fifo, vout_thread_sys_t::display, vout_thread_sys_t::displayed, vout_thread_sys_t::last, vout_thread_t::p, picture_fifo_Flush(), picture_Release(), vout_thread_sys_t::step, ThreadFilterFlush(), vout_thread_sys_t::timestamp, vout_thread_sys_t::vd, VLC_TS_INVALID, and vout_FilterFlush().
Referenced by ThreadControl(), and ThreadStop().
ThreadFlushSubpicture()
static void ThreadFlushSubpicture (vout_thread_t * vout, int channel) static
References vout_thread_t::p, vout_thread_sys_t::spu, and spu_ClearChannel().
Referenced by ThreadControl().
ThreadInit()
static void ThreadInit (vout_thread_t * vout) static
References vout_thread_sys_t::date, vout_thread_sys_t::dead, vout_thread_sys_t::is_late_dropped, vout_thread_sys_t::is_on, vout_thread_t::p, vout_thread_sys_t::pause, vout_thread_sys_t::render, var_InheritBool, VLC_TS_INVALID, and vout_chrono_Init().
Referenced by ThreadControl().
ThreadReinit()
static int ThreadReinit (vout_thread_t * vout, const vout_configuration_t * cfg) static
< Unspecified error
< No error
< Unspecified error
< No error
References vout_display_state_t::cfg, vout_thread_sys_t::date, vlc_rational_t::den, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_configuration_t::dpb_size, vout_thread_sys_t::dpb_size, vout_configuration_t::fmt, vout_display_cfg_t::height, video_format_t::i_sar_den, video_format_t::i_sar_num, vout_thread_sys_t::is_on, msg_Warn, vlc_rational_t::num, vout_display_cfg_t::num, vout_thread_sys_t::original, vout_thread_t::p, vout_thread_sys_t::pause, vout_display_cfg_t::sar, vout_display_state_t::sar, ThreadClean(), ThreadStart(), ThreadStop(), video_format_Clean(), video_format_IsSimilar(), VLC_EGENERIC, VLC_SUCCESS, VLC_TS_INVALID, vout_ReinitInterlacingSupport(), VoutValidateFormat(), vout_display_cfg_t::width, and vout_display_cfg_t::zoom.
Referenced by ThreadControl().
ThreadStart()
static int ThreadStart (vout_thread_t * vout, vout_display_state_t * state) static
< No error
< Unspecified error
References filter_owner_t::buffer_new, vout_display_state_t::cfg, vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, vout_thread_sys_t::configuration, vout_thread_sys_t::current, vout_thread_sys_t::date, vout_thread_sys_t::decoded, vout_thread_sys_t::decoder_fifo, vout_thread_sys_t::decoder_pool, vlc_rational_t::den, vout_thread_sys_t::display, vout_thread_sys_t::display_pool, vout_thread_sys_t::displayed, vout_thread_sys_t::filter, filter_chain_Delete(), filter_chain_NewVideo, vout_thread_sys_t::format, vout_thread_sys_t::is_interlaced, vout_thread_sys_t::last, vout_thread_sys_t::mouse, vout_thread_sys_t::next, vlc_rational_t::num, vout_thread_sys_t::original, vout_thread_t::p, picture_fifo_Delete(), picture_fifo_New(), vout_thread_sys_t::private_pool, vout_display_state_t::sar, vout_thread_sys_t::splitter_name, vout_thread_sys_t::spu_blend, vout_thread_sys_t::spu_blend_chroma, vout_thread_sys_t::step, filter_owner_t::sys, ThreadDelAllFilterCallbacks(), vout_thread_sys_t::timestamp, vout_thread_sys_t::title, var_InheritBool, filter_owner_t::video, video_format_Clean(), video_format_Copy(), video_format_Print(), VLC_EGENERIC, vlc_mouse_Init(), VLC_OBJECT, VLC_SUCCESS, VLC_TS_INVALID, vout_CloseWrapper(), vout_InitWrapper(), vout_OpenWrapper(), VOUT_WINDOW_STATE_ABOVE, VOUT_WINDOW_STATE_BELOW, VOUT_WINDOW_STATE_NORMAL, VoutGetDisplayCfg(), VoutVideoFilterInteractiveNewPicture(), and VoutVideoFilterStaticNewPicture().
Referenced by ThreadControl(), and ThreadReinit().
ThreadStep()
static void ThreadStep (vout_thread_t * vout, mtime_t * duration) static
References vout_thread_sys_t::displayed, vout_thread_sys_t::last, vout_thread_t::p, vout_thread_sys_t::step, ThreadDisplayPicture(), vout_thread_sys_t::timestamp, and VLC_TS_INVALID.
Referenced by ThreadControl().
ThreadStop()
static void ThreadStop (vout_thread_t * vout, vout_display_state_t * state) static
References vout_thread_sys_t::chain_interactive, vout_thread_sys_t::chain_static, vout_thread_sys_t::configuration, vout_thread_sys_t::decoder_fifo, vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, vout_thread_sys_t::filter, filter_chain_Delete(), filter_DeleteBlend(), vout_thread_sys_t::format, vout_thread_t::p, picture_fifo_Delete(), vout_thread_sys_t::spu_blend, ThreadDelAllFilterCallbacks(), ThreadFlush(), vout_thread_sys_t::vd, video_format_Clean(), vout_CloseWrapper(), and vout_EndWrapper().
Referenced by ThreadControl(), and ThreadReinit().
VideoFormatCopyCropAr()
static void VideoFormatCopyCropAr (video_format_t * dst, const video_format_t * src) static
References video_format_t::i_sar_den, video_format_t::i_sar_num, and video_format_CopyCrop().
Referenced by ThreadDisplayRenderPicture(), vout_GetPicture(), and VoutVideoFilterInteractiveNewPicture().
VideoFormatIsCropArEqual()
static bool VideoFormatIsCropArEqual (video_format_t * dst, const video_format_t * src) static
References video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, and video_format_t::i_y_offset.
Referenced by ThreadDisplayPreparePicture().
vout_Cancel()
void vout_Cancel (vout_thread_t * vout, bool canceled)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CANCEL, vout_control_PushBool(), and vout_control_WaitEmpty().
Referenced by decoder_AbortPictures(), DeleteDecoder(), and input_DecoderDelete().
vout_ChangePause()
void vout_ChangePause (vout_thread_t * vout, bool b_paused, mtime_t i_date)
This function will (un)pause the display of pictures.
It is thread safe
References vout_thread_sys_t::control, vout_control_cmd_t::date, vout_control_cmd_t::is_on, vout_thread_t::p, vout_control_cmd_t::pause, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_PAUSE, vout_control_Push(), and vout_control_WaitEmpty().
Referenced by DecoderThread().
vout_ControlChangeCropBorder()
void vout_ControlChangeCropBorder (vout_thread_t * vout, int left, int top, int right, int bottom)
References vout_control_cmd_t::border, vout_control_cmd_t::bottom, vout_thread_sys_t::control, vout_control_cmd_t::left, vout_thread_t::p, vout_control_cmd_t::right, vout_control_cmd_t::top, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_CROP_BORDER, and vout_control_Push().
Referenced by CropCallback().
vout_ControlChangeCropRatio()
void vout_ControlChangeCropRatio (vout_thread_t * vout, unsigned num, unsigned den)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CROP_RATIO, and vout_control_PushPair().
Referenced by CropCallback().
vout_ControlChangeCropWindow()
void vout_ControlChangeCropWindow (vout_thread_t * vout, int x, int y, int width, int height)
References vout_thread_sys_t::control, vout_control_cmd_t::height, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_CROP_WINDOW, vout_control_Push(), vout_control_cmd_t::width, vout_control_cmd_t::window, vout_control_cmd_t::x, and vout_control_cmd_t::y.
Referenced by CropCallback().
vout_ControlChangeDisplayFilled()
void vout_ControlChangeDisplayFilled (vout_thread_t * vout, bool is_filled)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_DISPLAY_FILLED, and vout_control_PushBool().
Referenced by AutoScaleCallback().
vout_ControlChangeFilters()
void vout_ControlChangeFilters (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_FILTERS, and vout_control_PushString().
Referenced by FilterRestartCallback(), and VideoFilterCallback().
vout_ControlChangeFullscreen()
void vout_ControlChangeFullscreen (vout_thread_t * vout, bool fullscreen)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_FULLSCREEN, and vout_control_PushBool().
Referenced by FullscreenCallback(), and WallPaperCallback().
vout_ControlChangeSampleAspectRatio()
void vout_ControlChangeSampleAspectRatio (vout_thread_t * vout, unsigned num, unsigned den)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_ASPECT_RATIO, and vout_control_PushPair().
Referenced by AspectCallback(), and vout_ChangeAspectRatio().
vout_ControlChangeSubFilters()
void vout_ControlChangeSubFilters (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_FILTERS, and vout_control_PushString().
Referenced by RestartSubFilterCallback(), and SubFilterCallback().
vout_ControlChangeSubMargin()
void vout_ControlChangeSubMargin (vout_thread_t * vout, int margin)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_MARGIN, and vout_control_PushInteger().
Referenced by SubMarginCallback().
vout_ControlChangeSubSources()
void vout_ControlChangeSubSources (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_SOURCES, and vout_control_PushString().
Referenced by RestartSubSourceCallback(), and SubSourceCallback().
vout_ControlChangeViewpoint()
void vout_ControlChangeViewpoint (vout_thread_t * vout, const vlc_viewpoint_t * p_viewpoint)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_t::viewpoint, vout_control_cmd_Init(), vout_control_Push(), and VOUT_CONTROL_VIEWPOINT.
Referenced by ViewpointCallback().
vout_ControlChangeWindowState()
void vout_ControlChangeWindowState (vout_thread_t * vout, unsigned st)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_PushInteger(), and VOUT_CONTROL_WINDOW_STATE.
Referenced by AboveCallback(), and WallPaperCallback().
vout_ControlChangeZoom()
void vout_ControlChangeZoom (vout_thread_t * vout, int num, int den)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_PushPair(), and VOUT_CONTROL_ZOOM.
Referenced by ZoomCallback().
vout_DeleteDisplayWindow()
void vout_DeleteDisplayWindow (vout_thread_t * vout, vout_window_t * window)
References vout_thread_t::p, vout_display_window_Delete(), and vout_thread_sys_t::window.
Referenced by VoutDisplayDelWindow().
vout_DisplayTitle()
void vout_DisplayTitle (vout_thread_t * vout, const char * title)
This function will ask the display of the input title.
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_OSD_TITLE, and vout_control_PushString().
Referenced by DisplayVoutTitle().
vout_Flush()
void vout_Flush (vout_thread_t * vout, mtime_t date)
This function will ensure that all ready/displayed pictures have at most the provided date.
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_FLUSH, vout_control_PushTime(), and vout_control_WaitEmpty().
Referenced by DecoderPlayVideo(), DecoderProcessFlush(), and RequestVout().
vout_GetResetStatistic()
void vout_GetResetStatistic (vout_thread_t * vout, unsigned *restrict displayed, unsigned *restrict lost)
References vout_thread_t::p, vout_thread_sys_t::statistic, and vout_statistic_GetReset().
Referenced by DecoderUpdateStatVideo().
vout_HideWindowMouse()
int vout_HideWindowMouse (vout_thread_t * vout, bool hide)
< Unspecified error
References vout_thread_t::p, VLC_EGENERIC, vout_window_HideMouse(), and vout_thread_sys_t::window.
Referenced by vout_ManageDisplay().
vout_IsEmpty()
bool vout_IsEmpty (vout_thread_t * vout)
This function will return true if no more pictures are to be displayed.
References vout_thread_sys_t::decoder_fifo, vout_thread_t::p, picture_fifo_Peek(), and picture_Release().
Referenced by input_DecoderIsEmpty().
vout_NewDisplayWindow()
vout_window_t * vout_NewDisplayWindow (vout_thread_t * vout, unsigned type)
References vout_thread_t::p, vout_thread_sys_t::splitter_name, vout_window_t::type, VOUT_WINDOW_TYPE_INVALID, and vout_thread_sys_t::window.
Referenced by VoutDisplayNewWindow().
vout_NextPicture()
void vout_NextPicture (vout_thread_t * vout, mtime_t * duration)
This function will force to display the next picture while paused.
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::time_ptr, vout_control_cmd_t::u, vout_control_cmd_Init(), vout_control_Push(), VOUT_CONTROL_STEP, and vout_control_WaitEmpty().
Referenced by input_DecoderFrameNext().
vout_SetDisplayWindowSize()
void vout_SetDisplayWindowSize (vout_thread_t * vout, unsigned width, unsigned height)
References vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::vd, vout_display_SendEventDisplaySize(), vout_window_SetSize(), and vout_thread_sys_t::window.
Referenced by vout_ManageDisplay(), and VoutDisplayFitWindow().
vout_WindowMouseEvent()
void vout_WindowMouseEvent (vout_thread_t * vout, const vout_window_mouse_event_t * mouse)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_Init(), vout_control_Push(), VOUT_CONTROL_WINDOW_MOUSE, and vout_control_cmd_t::window_mouse.
Referenced by vout_display_window_MouseEvent().
VoutCreate()
static vout_thread_t * VoutCreate (vlc_object_t * object, const vout_configuration_t * cfg) static
References vout_thread_sys_t::control, vout_thread_sys_t::dead, vout_thread_sys_t::displayed, vout_configuration_t::dpb_size, vout_thread_sys_t::dpb_size, vout_thread_sys_t::filter, vout_configuration_t::fmt, video_format_t::i_visible_height, video_format_t::i_visible_width, vout_configuration_t::input, vout_thread_sys_t::input, vout_thread_sys_t::is_interlaced, vout_window_cfg_t::is_standalone, vout_thread_sys_t::lock, msg_Err, vout_thread_sys_t::original, vout_thread_t::p, vout_thread_sys_t::snapshot, vout_thread_sys_t::splitter_name, vout_thread_sys_t::spu, spu_Attach(), spu_Create, spu_Destroy(), vout_thread_sys_t::spu_lock, vout_thread_sys_t::statistic, Thread(), vout_thread_sys_t::thread, vout_thread_sys_t::title, var_GetBool, var_InheritBool, var_InheritInteger, var_InheritString, video_format_Clean(), vlc_clone(), vlc_custom_create, vlc_mutex_init(), vlc_object_release, vlc_object_set_destructor, VLC_THREAD_PRIORITY_OUTPUT, vout_CloseAndRelease(), VOUT_CONTROL_INIT, vout_control_Init(), vout_control_PushVoid(), vout_control_WaitEmpty(), vout_display_window_Delete(), vout_display_window_New(), vout_InitInterlacingSupport(), vout_IntfInit(), vout_snapshot_Init(), vout_statistic_Init(), vout_window_SetState(), VOUT_WINDOW_STATE_ABOVE, VOUT_WINDOW_STATE_BELOW, VOUT_WINDOW_TYPE_INVALID, VoutDestructor(), VoutValidateFormat(), and vout_thread_sys_t::window.
Referenced by vout_Request().
VoutDestructor()
static void VoutDestructor (vlc_object_t * object) static
References vout_thread_sys_t::control, vout_thread_sys_t::filter, vout_thread_sys_t::lock, vout_thread_sys_t::original, vout_thread_t::p, vout_thread_sys_t::snapshot, vout_thread_sys_t::splitter_name, vout_thread_sys_t::spu_lock, vout_thread_sys_t::statistic, video_format_Clean(), vlc_mutex_destroy(), vout_control_Clean(), vout_snapshot_Clean(), and vout_statistic_Clean().
Referenced by VoutCreate().
VoutGetDisplayCfg()
static void VoutGetDisplayCfg (vout_thread_t * vout, vout_display_cfg_t * cfg, const char * title) static
References vout_display_cfg_t::align, vlc_rational_t::den, vout_display_cfg_t::den, vout_display_cfg_t::display, vout_display_cfg_t::height, vout_display_cfg_t::horizontal, vout_display_cfg_t::is_display_filled, vlc_rational_t::num, vout_display_cfg_t::num, vout_thread_sys_t::original, vout_thread_t::p, video_format_t::pose, vout_display_cfg_t::sar, vout_display_cfg_t::title, var_GetBool, var_GetFloat, var_GetInteger, var_InheritURational, vout_display_cfg_t::vertical, vout_display_cfg_t::viewpoint, vlc_ureduce(), VOUT_DISPLAY_ALIGN_BOTTOM, VOUT_DISPLAY_ALIGN_CENTER, VOUT_DISPLAY_ALIGN_LEFT, VOUT_DISPLAY_ALIGN_RIGHT, VOUT_DISPLAY_ALIGN_TOP, vout_display_cfg_t::width, and vout_display_cfg_t::zoom.
Referenced by ThreadStart().
VoutValidateFormat()
static int VoutValidateFormat (video_format_t * dst, const video_format_t * src) static
< Unspecified error
< Unspecified error
< No error
References video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_width, VIDEO_ES, video_format_Copy(), video_format_FixRgb(), VLC_EGENERIC, vlc_fourcc_GetCodec(), VLC_SUCCESS, and vlc_ureduce().
Referenced by ThreadReinit(), and VoutCreate().
VoutVideoFilterInteractiveNewPicture()
static picture_t * VoutVideoFilterInteractiveNewPicture (filter_t * filter) static
References filter_t::fmt_out, picture_t::format, filter_t::owner, vout_thread_t::p, picture_pool_Get(), picture_Reset(), vout_thread_sys_t::private_pool, filter_owner_t::sys, es_format_t::video, and VideoFormatCopyCropAr().
Referenced by ThreadStart(), and VoutVideoFilterStaticNewPicture().
VoutVideoFilterStaticNewPicture()
static picture_t * VoutVideoFilterStaticNewPicture (filter_t * filter) static
References vout_thread_sys_t::chain_interactive, vout_thread_sys_t::filter, filter_chain_IsEmpty(), filter_t::fmt_out, vout_thread_sys_t::lock, filter_t::owner, vout_thread_t::p, picture_NewFromFormat(), filter_owner_t::sys, es_format_t::video, vlc_assert_locked(), and VoutVideoFilterInteractiveNewPicture().
Referenced by ThreadStart().