VLC: src/video_output/video_widgets.c File Reference
video_widgets.c File Reference
Data Structures
struct subpicture_updater_sys_t
Macros
#define STYLE_EMPTY 0
#define STYLE_FILLED 1
#define RGB_BLUE 0x2badde
#define COL_TRANSPARENT 0
#define COL_WHITE 1
#define COL_BLUE 2
#define COL_BLUE_SHADE 3
#define SET_PALETTE_COLOR(id, rgb, alpha)
#define SLIDER_MARGIN_BASE 0.10
Create the region for an OSD slider.
Functions
static void DrawRect (subpicture_region_t *r, int fill, uint8_t color, int x1, int y1, int x2, int y2)
Draws a rectangle at the given position in the region.
static void DrawTriangle (subpicture_region_t *r, int fill, uint8_t color, int x1, int y1, int x2, int y2)
Draws a triangle at the given position in the region.
static subpicture_region_t * OSDRegion (int x, int y, int width, int height)
Create a region with a white transparent picture.
static subpicture_region_t * OSDSlider (int type, int position, const video_format_t *fmt)
static subpicture_region_t * OSDIcon (int type, const video_format_t *fmt)
Create the region for an OSD slider.
static int OSDWidgetValidate (subpicture_t *subpic, bool has_src_changed, const video_format_t *fmt_src, bool has_dst_changed, const video_format_t *fmt_dst, mtime_t ts)
static void OSDWidgetUpdate (subpicture_t *subpic, const video_format_t *fmt_src, const video_format_t *fmt_dst, mtime_t ts)
static void OSDWidgetDestroy (subpicture_t *subpic)
static void OSDWidget (vout_thread_t *vout, int channel, int type, int position)
void vout_OSDSlider (vout_thread_t *vout, int channel, int position, short type)
Display a slider on the video output.
void vout_OSDIcon (vout_thread_t *vout, int channel, short type)
Display an Icon on the video output.
Macro Definition Documentation
COL_BLUE
#define COL_BLUE 2
Referenced by OSDIcon(), OSDRegion(), and OSDSlider().
COL_BLUE_SHADE
#define COL_BLUE_SHADE 3
Referenced by OSDRegion(), and OSDSlider().
COL_TRANSPARENT
#define COL_TRANSPARENT 0
Referenced by OSDIcon(), and OSDRegion().
COL_WHITE
#define COL_WHITE 1
Referenced by OSDIcon(), and OSDRegion().
RGB_BLUE
#define RGB_BLUE 0x2badde
Referenced by OSDRegion().
SET_PALETTE_COLOR
#define SET_PALETTE_COLOR (id, rgb, alpha)
Value:
{\
    uint8_t color[4] = { HEX2YUV(rgb), alpha };\
    memcpy( &palette.palette[id], &color, 4 );\
}
Referenced by OSDRegion().
SLIDER_MARGIN_BASE
#define SLIDER_MARGIN_BASE 0.10
Create the region for an OSD slider.
Types are: OSD_HOR_SLIDER and OSD_VERT_SLIDER.
Referenced by OSDSlider().
STYLE_EMPTY
#define STYLE_EMPTY 0
STYLE_FILLED
#define STYLE_FILLED 1
Referenced by DrawRect(), DrawTriangle(), OSDIcon(), and OSDSlider().
Function Documentation
DrawRect()
static void DrawRect (subpicture_region_t * r, int fill, uint8_t color, int x1, int y1, int x2, int y2) static
Draws a rectangle at the given position in the region.
It may be filled (fill == STYLE_FILLED) or empty (fill == STYLE_EMPTY).
References DrawRect(), plane_t::i_pitch, plane_t::i_visible_pitch, p, picture_t::p, subpicture_region_t::p_picture, plane_t::p_pixels, and STYLE_FILLED.
Referenced by DrawRect(), DrawTriangle(), OSDIcon(), and OSDSlider().
DrawTriangle()
static void DrawTriangle (subpicture_region_t * r, int fill, uint8_t color, int x1, int y1, int x2, int y2) static
Draws a triangle at the given position in the region.
It may be filled (fill == STYLE_FILLED) or empty (fill == STYLE_EMPTY).
References DrawRect(), plane_t::i_pitch, p, picture_t::p, subpicture_region_t::p_picture, plane_t::p_pixels, and STYLE_FILLED.
Referenced by OSDIcon().
OSDIcon()
static subpicture_region_t * OSDIcon (int type, const video_format_t * fmt) static
Create the region for an OSD slider.
Types are: OSD_PLAY_ICON, OSD_PAUSE_ICON, OSD_SPEAKER_ICON, OSD_MUTE_ICON
References COL_BLUE, COL_TRANSPARENT, COL_WHITE, DrawRect(), DrawTriangle(), video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, OSD_MUTE_ICON, OSD_PAUSE_ICON, OSD_PLAY_ICON, OSDRegion(), and STYLE_FILLED.
Referenced by OSDWidgetUpdate().
OSDRegion()
static subpicture_region_t * OSDRegion (int x, int y, int width, int height) static
Create a region with a white transparent picture.
References COL_BLUE, COL_BLUE_SHADE, COL_TRANSPARENT, COL_WHITE, video_palette_t::i_entries, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, subpicture_region_t::i_x, subpicture_region_t::i_y, video_format_t::p_palette, RGB_BLUE, SET_PALETTE_COLOR, STYLE_ALPHA_OPAQUE, STYLE_ALPHA_TRANSPARENT, subpicture_region_New(), video_format_Init(), and VLC_CODEC_YUVP.
Referenced by OSDIcon(), and OSDSlider().
OSDSlider()
static subpicture_region_t * OSDSlider (int type, int position, const video_format_t * fmt) static
References COL_BLUE, COL_BLUE_SHADE, DrawRect(), video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, OSD_HOR_SLIDER, OSDRegion(), SLIDER_MARGIN_BASE, and STYLE_FILLED.
Referenced by OSDWidgetUpdate().
OSDWidget()
static void OSDWidget (vout_thread_t * vout, int channel, int type, int position) static
References subpicture_t::b_absolute, subpicture_t::b_ephemer, subpicture_t::b_fade, subpicture_t::i_channel, subpicture_t::i_start, subpicture_t::i_stop, mdate(), OSD_HOR_SLIDER, OSD_VERT_SLIDER, OSDWidgetDestroy(), OSDWidgetUpdate(), OSDWidgetValidate(), subpicture_updater_t::pf_validate, subpicture_updater_sys_t::position, subpicture_New(), subpicture_updater_sys_t::type, var_InheritBool, VLC_CLIP, and vout_PutSubpicture().
Referenced by vout_OSDIcon(), and vout_OSDSlider().
OSDWidgetDestroy()
static void OSDWidgetDestroy (subpicture_t * subpic) static
References subpicture_updater_t::p_sys, and subpicture_t::updater.
Referenced by OSDWidget().
OSDWidgetUpdate()
static void OSDWidgetUpdate (subpicture_t * subpic, const video_format_t * fmt_src, const video_format_t * fmt_dst, mtime_t ts) static
References subpicture_t::i_original_picture_height, subpicture_t::i_original_picture_width, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, OSD_HOR_SLIDER, OSD_VERT_SLIDER, OSDIcon(), OSDSlider(), subpicture_t::p_region, subpicture_updater_t::p_sys, subpicture_updater_sys_t::position, subpicture_updater_sys_t::type, subpicture_t::updater, and VLC_UNUSED.
Referenced by OSDWidget().
OSDWidgetValidate()
static int OSDWidgetValidate (subpicture_t * subpic, bool has_src_changed, const video_format_t * fmt_src, bool has_dst_changed, const video_format_t * fmt_dst, mtime_t ts) static
< No error
< Unspecified error
References VLC_EGENERIC, VLC_SUCCESS, and VLC_UNUSED.
Referenced by OSDWidget().