VLC: src/video_output/event.h File Reference
event.h File Reference
Functions
static void vout_SendEventClose (vout_thread_t *vout)
static void vout_SendEventKey (vout_thread_t *vout, int key)
static void vout_SendEventMouseMoved (vout_thread_t *vout, int x, int y)
static void vout_SendEventViewpointMoved (vout_thread_t *vout, const vlc_viewpoint_t *p_viewpoint)
static void vout_SendEventMousePressed (vout_thread_t *vout, int button)
static void vout_SendEventMouseReleased (vout_thread_t *vout, int button)
static void vout_SendEventMouseDoubleClick (vout_thread_t *vout)
static void vout_SendEventViewpointChangeable (vout_thread_t *vout, bool b_can_change)
Function Documentation
vout_SendEventClose()
static void vout_SendEventClose (vout_thread_t * vout) inline static
Referenced by vout_display_window_CloseNotify(), and VoutDisplayEvent().
vout_SendEventKey()
static void vout_SendEventKey (vout_thread_t * vout, int key) inline static
References vlc_common_members::libvlc, vout_thread_t::obj, and var_SetInteger.
Referenced by vout_SendEventMousePressed(), and VoutDisplayEvent().
vout_SendEventMouseDoubleClick()
static void vout_SendEventMouseDoubleClick (vout_thread_t * vout) inline static
References var_ToggleBool.
Referenced by vout_SendDisplayEventMouse().
vout_SendEventMouseMoved()
static void vout_SendEventMouseMoved (vout_thread_t * vout, int x, int y) inline static
References var_SetCoords.
Referenced by vout_SendDisplayEventMouse().
vout_SendEventMousePressed()
static void vout_SendEventMousePressed (vout_thread_t * vout, int button) inline static
References KEY_MOUSEWHEELDOWN, KEY_MOUSEWHEELLEFT, KEY_MOUSEWHEELRIGHT, KEY_MOUSEWHEELUP, KEY_UNSET, vlc_common_members::libvlc, MOUSE_BUTTON_CENTER, MOUSE_BUTTON_LEFT, MOUSE_BUTTON_RIGHT, MOUSE_BUTTON_WHEEL_DOWN, MOUSE_BUTTON_WHEEL_LEFT, MOUSE_BUTTON_WHEEL_RIGHT, MOUSE_BUTTON_WHEEL_UP, vout_thread_t::obj, var_GetCoords, var_OrInteger, var_SetBool, var_SetCoords, var_ToggleBool, and vout_SendEventKey().
Referenced by vout_SendDisplayEventMouse().
vout_SendEventMouseReleased()
static void vout_SendEventMouseReleased (vout_thread_t * vout, int button) inline static
References vlc_common_members::libvlc, MOUSE_BUTTON_RIGHT, vout_thread_t::obj, var_NAndInteger, and var_SetBool.
Referenced by vout_SendDisplayEventMouse().
vout_SendEventViewpointChangeable()
static void vout_SendEventViewpointChangeable (vout_thread_t * vout, bool b_can_change) inline static
References var_SetBool.
Referenced by DisplayNew().
vout_SendEventViewpointMoved()
static void vout_SendEventViewpointMoved (vout_thread_t * vout, const vlc_viewpoint_t * p_viewpoint) inline static
References var_Change, var_SetAddress, and VLC_VAR_SETVALUE.
Referenced by VoutDisplayEvent().