VLC: src/video_output/video_epg.c File Reference
video_epg.c File Reference
Data Structures
struct subpicture_updater_sys_t
Macros
#define OSDEPG_MARGIN 0.025
#define OSDEPG_MARGINS (OSDEPG_MARGIN * 2)
#define OSDEPG_PADDING 0.05 /* inner margins */
#define OSDEPG_WIDTH (1.0 - OSDEPG_MARGINS)
#define OSDEPG_HEIGHT 0.25
#define OSDEPG_LEFT OSDEPG_MARGIN
#define OSDEPG_TOP (1.0 - OSDEPG_MARGINS - OSDEPG_HEIGHT + OSDEPG_MARGIN)
#define OSDEPG_ROWS_COUNT 10
#define OSDEPG_ROW_HEIGHT (1.0 / OSDEPG_ROWS_COUNT)
#define OSDEPG_LOGO_SIZE (OSDEPG_HEIGHT)
#define OSDEPG_RIGHT (1.0 - OSDEPG_MARGIN)
#define OSDEPG_ROWS(x) (OSDEPG_ROW_HEIGHT * x)
#define OSDEPG_ROW(x) (OSDEPG_ROWS(x))
#define EPGOSD_TEXTSIZE_NAME (OSDEPG_ROWS(2))
#define EPGOSD_TEXTSIZE_PROG (OSDEPG_ROWS(2))
#define EPGOSD_TEXTSIZE_NTWK (OSDEPG_ROWS(2))
#define RGB_COLOR1 0x2badde
#define ARGB_BGCOLOR 0xc003182d
#define GRADIENT_COLORS 40
Functions
static char * GetDefaultArtUri (void)
static subpicture_region_t * vout_OSDBackground (int x, int y, int width, int height, uint32_t i_argb)
static subpicture_region_t * vout_OSDEpgSlider (int x, int y, int width, int height, float ratio)
static void vout_OSDSegmentSetNoWrap (text_segment_t *p_segment)
static text_segment_t * vout_OSDSegment (const char *psz_text, int size, uint32_t color)
static subpicture_region_t * vout_OSDImage (vlc_object_t *p_obj, int x, int y, int w, int h, const char *psz_uri)
static void vout_OSDRegionConstrain (subpicture_region_t *p_region, int w, int h)
static subpicture_region_t * vout_OSDTextRegion (text_segment_t *p_segment, int x, int y)
static subpicture_region_t * vout_OSDEpgText (const char *text, int x, int y, int size, uint32_t color)
static char * vout_OSDPrintTime (time_t t)
static subpicture_region_t * vout_OSDEpgEvent (const vlc_epg_event_t *p_evt, int x, int y, int size)
static void vout_FillRightPanel (subpicture_updater_sys_t *p_sys, int x, int y, int width, int height, int rx, int ry, subpicture_region_t **last_ptr)
static subpicture_region_t * vout_BuildOSDEpg (subpicture_updater_sys_t *p_sys, int x, int y, int visible_width, int visible_height)
static int OSDEpgValidate (subpicture_t *subpic, bool has_src_changed, const video_format_t *fmt_src, bool has_dst_changed, const video_format_t *fmt_dst, mtime_t ts)
static void OSDEpgUpdate (subpicture_t *subpic, const video_format_t *fmt_src, const video_format_t *fmt_dst, mtime_t ts)
static void OSDEpgDestroy (subpicture_t *subpic)
int vout_OSDEpg (vout_thread_t *vout, input_item_t *input)
Show EPG information about the current program of an input item.
Macro Definition Documentation
ARGB_BGCOLOR
#define ARGB_BGCOLOR 0xc003182d
Referenced by vout_BuildOSDEpg().
EPGOSD_TEXTSIZE_NAME
#define EPGOSD_TEXTSIZE_NAME (OSDEPG_ROWS(2))
Referenced by vout_FillRightPanel().
EPGOSD_TEXTSIZE_NTWK
#define EPGOSD_TEXTSIZE_NTWK (OSDEPG_ROWS(2))
Referenced by vout_FillRightPanel().
EPGOSD_TEXTSIZE_PROG
#define EPGOSD_TEXTSIZE_PROG (OSDEPG_ROWS(2))
Referenced by vout_FillRightPanel().
GRADIENT_COLORS
#define GRADIENT_COLORS 40
Referenced by vout_OSDBackground().
OSDEPG_HEIGHT
#define OSDEPG_HEIGHT 0.25
Referenced by vout_BuildOSDEpg().
OSDEPG_LEFT
#define OSDEPG_LEFT OSDEPG_MARGIN
Referenced by vout_BuildOSDEpg().
OSDEPG_LOGO_SIZE
#define OSDEPG_LOGO_SIZE (OSDEPG_HEIGHT)
Referenced by vout_BuildOSDEpg().
OSDEPG_MARGIN
#define OSDEPG_MARGIN 0.025
OSDEPG_MARGINS
#define OSDEPG_MARGINS (OSDEPG_MARGIN * 2)
OSDEPG_PADDING
#define OSDEPG_PADDING 0.05 /* inner margins */
Referenced by vout_BuildOSDEpg().
OSDEPG_RIGHT
#define OSDEPG_RIGHT (1.0 - OSDEPG_MARGIN)
OSDEPG_ROW
#define OSDEPG_ROW (x) (OSDEPG_ROWS(x))
Referenced by vout_FillRightPanel().
OSDEPG_ROW_HEIGHT
#define OSDEPG_ROW_HEIGHT (1.0 / OSDEPG_ROWS_COUNT)
OSDEPG_ROWS
#define OSDEPG_ROWS (x) (OSDEPG_ROW_HEIGHT * x)
Referenced by vout_FillRightPanel().
OSDEPG_ROWS_COUNT
#define OSDEPG_ROWS_COUNT 10
OSDEPG_TOP
#define OSDEPG_TOP (1.0 - OSDEPG_MARGINS - OSDEPG_HEIGHT + OSDEPG_MARGIN)
Referenced by vout_BuildOSDEpg().
OSDEPG_WIDTH
#define OSDEPG_WIDTH (1.0 - OSDEPG_MARGINS)
Referenced by vout_BuildOSDEpg().
RGB_COLOR1
#define RGB_COLOR1 0x2badde
Referenced by vout_BuildOSDEpg(), vout_FillRightPanel(), vout_OSDEpgEvent(), and vout_OSDEpgSlider().
Function Documentation
GetDefaultArtUri()
static char * GetDefaultArtUri (void) static
References asprintf(), config_GetDataDir(), and vlc_path2uri().
Referenced by vout_OSDEpg().
OSDEpgDestroy()
static void OSDEpgDestroy (subpicture_t * subpic) static
References subpicture_updater_sys_t::art, subpicture_updater_sys_t::epg, subpicture_updater_t::p_sys, subpicture_t::updater, and vlc_epg_Delete().
Referenced by vout_OSDEpg().
OSDEpgUpdate()
static void OSDEpgUpdate (subpicture_t * subpic, const video_format_t * fmt_src, const video_format_t * fmt_dst, mtime_t ts) static
References subpicture_t::i_original_picture_height, subpicture_t::i_original_picture_width, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, subpicture_t::p_region, subpicture_updater_t::p_sys, subpicture_t::updater, VLC_UNUSED, and vout_BuildOSDEpg().
Referenced by vout_OSDEpg().
OSDEpgValidate()
static int OSDEpgValidate (subpicture_t * subpic, bool has_src_changed, const video_format_t * fmt_src, bool has_dst_changed, const video_format_t * fmt_dst, mtime_t ts) static
< No error
< Unspecified error
References VLC_EGENERIC, VLC_SUCCESS, and VLC_UNUSED.
Referenced by vout_OSDEpg().
vout_BuildOSDEpg()
static subpicture_region_t * vout_BuildOSDEpg (subpicture_updater_sys_t * p_sys, int x, int y, int visible_width, int visible_height) static
References ARGB_BGCOLOR, subpicture_updater_sys_t::art, subpicture_updater_sys_t::obj, OSDEPG_HEIGHT, OSDEPG_LEFT, OSDEPG_LOGO_SIZE, OSDEPG_PADDING, OSDEPG_TOP, OSDEPG_WIDTH, subpicture_region_t::p_next, RGB_COLOR1, vout_FillRightPanel(), vout_OSDBackground(), and vout_OSDImage().
Referenced by OSDEpgUpdate().
vout_FillRightPanel()
static void vout_FillRightPanel (subpicture_updater_sys_t * p_sys, int x, int y, int width, int height, int rx, int ry, subpicture_region_t ** last_ptr) static
References subpicture_updater_sys_t::epg, EPGOSD_TEXTSIZE_NAME, EPGOSD_TEXTSIZE_NTWK, EPGOSD_TEXTSIZE_PROG, vlc_epg_event_t::i_duration, vlc_epg_t::i_event, vlc_epg_event_t::i_id, vlc_epg_event_t::i_start, OSDEPG_ROW, OSDEPG_ROWS, vlc_epg_t::p_current, subpicture_region_t::p_next, vlc_epg_t::pp_event, vlc_epg_t::psz_name, RGB_COLOR1, SUBPICTURE_ALIGN_RIGHT, SUBPICTURE_ALIGN_TOP, subpicture_updater_sys_t::time, VLC_UNUSED, vout_OSDEpgEvent(), vout_OSDEpgSlider(), vout_OSDEpgText(), vout_OSDPrintTime(), and vout_OSDRegionConstrain().
Referenced by vout_BuildOSDEpg().
vout_OSDBackground()
static subpicture_region_t * vout_OSDBackground (int x, int y, int width, int height, uint32_t i_argb) static
References GRADIENT_COLORS, subpicture_region_t::i_align, video_palette_t::i_entries, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, subpicture_region_t::i_x, subpicture_region_t::i_y, picture_t::p, video_format_t::p_palette, subpicture_region_t::p_picture, spuregion_CreateVGradientFill(), spuregion_CreateVGradientPalette(), SUBPICTURE_ALIGN_LEFT, SUBPICTURE_ALIGN_TOP, subpicture_region_New(), video_format_Init(), and VLC_CODEC_YUVP.
Referenced by vout_BuildOSDEpg().
vout_OSDEpgEvent()
static subpicture_region_t * vout_OSDEpgEvent (const vlc_epg_event_t * p_evt, int x, int y, int size) static
References asprintf(), vlc_epg_event_t::i_duration, vlc_epg_event_t::i_start, text_segment_t::p_next, vlc_epg_event_t::psz_name, RGB_COLOR1, vout_OSDPrintTime(), vout_OSDSegment(), vout_OSDSegmentSetNoWrap(), and vout_OSDTextRegion().
Referenced by vout_FillRightPanel().
vout_OSDEpgSlider()
static subpicture_region_t * vout_OSDEpgSlider (int x, int y, int width, int height, float ratio) static
References HEX2YUV, subpicture_region_t::i_align, video_palette_t::i_entries, video_format_t::i_height, plane_t::i_pitch, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, subpicture_region_t::i_x, subpicture_region_t::i_y, picture_t::p, video_format_t::p_palette, subpicture_region_t::p_picture, plane_t::p_pixels, RGB_COLOR1, SUBPICTURE_ALIGN_LEFT, SUBPICTURE_ALIGN_TOP, subpicture_region_New(), video_format_Init(), VLC_CLIP, and VLC_CODEC_YUVP.
Referenced by vout_FillRightPanel().
vout_OSDEpgText()
static subpicture_region_t * vout_OSDEpgText (const char * text, int x, int y, int size, uint32_t color) static
References vout_OSDSegment(), and vout_OSDTextRegion().
Referenced by vout_FillRightPanel().
vout_OSDImage()
static subpicture_region_t * vout_OSDImage (vlc_object_t * p_obj, int x, int y, int w, int h, const char * psz_uri) static
References subpicture_region_t::i_align, video_format_t::i_height, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, subpicture_region_t::i_x, subpicture_region_t::i_y, spuregion_CreateFromPicture(), SUBPICTURE_ALIGN_LEFT, SUBPICTURE_ALIGN_TOP, video_format_Init(), and VLC_CODEC_YUVA.
Referenced by vout_BuildOSDEpg().
vout_OSDPrintTime()
static char * vout_OSDPrintTime (time_t t) static
References asprintf(), and localtime_r().
Referenced by vout_FillRightPanel(), and vout_OSDEpgEvent().
vout_OSDRegionConstrain()
static void vout_OSDRegionConstrain (subpicture_region_t * p_region, int w, int h) static
References subpicture_region_t::i_max_height, and subpicture_region_t::i_max_width.
Referenced by vout_FillRightPanel().
vout_OSDSegment()
static text_segment_t * vout_OSDSegment (const char * psz_text, int size, uint32_t color) static
References text_style_t::i_features, text_style_t::i_font_alpha, text_style_t::i_font_color, text_style_t::i_font_size, text_style_t::i_outline_alpha, text_style_t::i_shadow_alpha, text_segment_t::style, STYLE_ALPHA_OPAQUE, STYLE_ALPHA_TRANSPARENT, STYLE_HAS_FONT_ALPHA, STYLE_HAS_FONT_COLOR, STYLE_HAS_OUTLINE_ALPHA, STYLE_HAS_SHADOW_ALPHA, STYLE_NO_DEFAULTS, text_segment_Delete(), text_segment_New(), text_style_Create(), and unlikely.
Referenced by vout_OSDEpgEvent(), and vout_OSDEpgText().
vout_OSDSegmentSetNoWrap()
static void vout_OSDSegmentSetNoWrap (text_segment_t * p_segment) static
References text_style_t::e_wrapinfo, text_style_t::i_features, text_segment_t::p_next, text_segment_t::style, and STYLE_HAS_WRAP_INFO.
Referenced by vout_OSDEpgEvent().
vout_OSDTextRegion()
static subpicture_region_t * vout_OSDTextRegion (text_segment_t * p_segment, int x, int y) static
References subpicture_region_t::b_balanced_text, subpicture_region_t::i_align, video_format_t::i_sar_den, video_format_t::i_sar_num, subpicture_region_t::i_text_align, subpicture_region_t::i_x, subpicture_region_t::i_y, subpicture_region_t::p_text, SUBPICTURE_ALIGN_LEFT, SUBPICTURE_ALIGN_TOP, subpicture_region_New(), video_format_Init(), and VLC_CODEC_TEXT.
Referenced by vout_OSDEpgEvent(), and vout_OSDEpgText().