VLC: include/vlc_timestamp_helper.h File Reference
vlc_timestamp_helper.h File Reference
Data Structures
struct timestamp_fifo_t
Functions
static timestamp_fifo_t * timestamp_FifoNew (uint32_t capacity)
static void timestamp_FifoRelease (timestamp_fifo_t *fifo)
static bool timestamp_FifoIsEmpty (timestamp_fifo_t *fifo)
static bool timestamp_FifoIsFull (timestamp_fifo_t *fifo)
static void timestamp_FifoEmpty (timestamp_fifo_t *fifo)
static void timestamp_FifoPut (timestamp_fifo_t *fifo, int64_t ts)
static int64_t timestamp_FifoGet (timestamp_fifo_t *fifo)
Function Documentation
timestamp_FifoEmpty()
static void timestamp_FifoEmpty (timestamp_fifo_t * fifo) inline static
References timestamp_fifo_t::size.
timestamp_FifoGet()
static int64_t timestamp_FifoGet (timestamp_fifo_t * fifo) inline static
References timestamp_fifo_t::begin, timestamp_fifo_t::buffer, timestamp_fifo_t::capacity, timestamp_fifo_t::size, timestamp_FifoIsEmpty(), and VLC_TS_INVALID.
timestamp_FifoIsEmpty()
static bool timestamp_FifoIsEmpty (timestamp_fifo_t * fifo) inline static
References timestamp_fifo_t::size.
Referenced by timestamp_FifoGet().
timestamp_FifoIsFull()
static bool timestamp_FifoIsFull (timestamp_fifo_t * fifo) inline static
References timestamp_fifo_t::capacity, and timestamp_fifo_t::size.
Referenced by timestamp_FifoPut().
timestamp_FifoNew()
static timestamp_fifo_t * timestamp_FifoNew (uint32_t capacity) inline static
References timestamp_fifo_t::buffer, timestamp_fifo_t::capacity, and vlc_alloc().
timestamp_FifoPut()
static void timestamp_FifoPut (timestamp_fifo_t * fifo, int64_t ts) inline static
References timestamp_fifo_t::begin, timestamp_fifo_t::buffer, timestamp_fifo_t::capacity, timestamp_fifo_t::size, and timestamp_FifoIsFull().
timestamp_FifoRelease()
static void timestamp_FifoRelease (timestamp_fifo_t * fifo) inline static
References timestamp_fifo_t::buffer.