VLC: include/vlc_mtime.h File Reference
vlc_mtime.h File Reference
Data Structures
struct date_t
Macros
#define LAST_MDATE ((mtime_t)((uint64_t)(-1)/2))
#define MSTRTIME_MAX_SIZE 22
Functions
char * secstotimestr (char *psz_buffer, int32_t secs)
Convert seconds to a time in the format h:mm:ss.
void date_Init (date_t *, uint32_t, uint32_t)
Initialize a date_t.
void date_Change (date_t *, uint32_t, uint32_t)
Change a date_t.
void date_Set (date_t *, mtime_t)
Set the date value of a date_t.
mtime_t date_Get (const date_t *)
Get the date of a date_t.
void date_Move (date_t *, mtime_t)
Move forwards or backwards the date of a date_t.
mtime_t date_Increment (date_t *, uint32_t)
Increment the date and return the result, taking into account rounding errors.
mtime_t date_Decrement (date_t *, uint32_t)
Decrement the date and return the result, taking into account rounding errors.
uint64_t NTPtime64 (void)
Macro Definition Documentation
LAST_MDATE
#define LAST_MDATE ((mtime_t)((uint64_t)(-1)/2))
MSTRTIME_MAX_SIZE
#define MSTRTIME_MAX_SIZE 22
Referenced by ControlNavDisplayPosition(), input_ControlVarNavigation(), and secstotimestr().
Function Documentation
date_Change()
void date_Change (date_t * p_date, uint32_t i_divider_n, uint32_t i_divider_d)
Change a date_t.
Parameters
date to change
divider (sample rate) numerator
divider (sample rate) denominator
References date_t::i_divider_den, date_t::i_divider_num, and date_t::i_remainder.
date_Decrement()
mtime_t date_Decrement (date_t * p_date, uint32_t i_nb_samples)
Decrement the date and return the result, taking into account rounding errors.
Parameters
date to decrement
decrementation in number of samples
Returns
date value
References CLOCK_FREQ, date_t::date, date_t::i_divider_den, date_t::i_divider_num, and date_t::i_remainder.
date_Get()
mtime_t date_Get (const date_t * p_date)
Get the date of a date_t.
Parameters
date to get
Returns
date value
References date_t::date.
date_Increment()
mtime_t date_Increment (date_t * p_date, uint32_t i_nb_samples)
Increment the date and return the result, taking into account rounding errors.
Parameters
date to increment
incrementation in number of samples
Returns
date value
References CLOCK_FREQ, date_t::date, date_t::i_divider_den, date_t::i_divider_num, date_t::i_remainder, lldiv(), lldiv_t::quot, and lldiv_t::rem.
date_Init()
void date_Init (date_t * p_date, uint32_t i_divider_n, uint32_t i_divider_d)
Initialize a date_t.
Parameters
date to initialize
divider (sample rate) numerator
divider (sample rate) denominator
References date_t::date, date_t::i_divider_den, date_t::i_divider_num, and date_t::i_remainder.
date_Move()
void date_Move (date_t * p_date, mtime_t i_difference)
Move forwards or backwards the date of a date_t.
Parameters
date to move
difference value
References date_t::date.
date_Set()
void date_Set (date_t * p_date, mtime_t i_new_date)
Set the date value of a date_t.
Parameters
date to set
date value
References date_t::date, and date_t::i_remainder.
NTPtime64()
uint64_t NTPtime64 (void)
Returns
NTP 64-bits timestamp in host byte order.
References TIME_UTC, timespec_get(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by vlc_rand_bytes(), and vlc_sdp_Start().
secstotimestr()
char * secstotimestr (char * psz_buffer, int32_t i_seconds)
Convert seconds to a time in the format h:mm:ss.
This function is provided for any interface function which need to print a time string in the format h:mm:ss date.
Parameters
secs the date to be converted
psz_buffer should be a buffer at least MSTRTIME_MAX_SIZE characters
Returns
psz_buffer is returned so this can be used as printf parameter.
References MSTRTIME_MAX_SIZE, secstotimestr(), and unlikely.
Referenced by ControlNavDisplayPosition(), input_ControlVarNavigation(), and secstotimestr().