VLC: include/vlc_fixups.h File Reference
vlc_fixups.h File Reference
This file is a collection of portability fixes.
Data Structures
struct lldiv_t
struct max_align_t
struct pollfd
struct if_nameindex
struct timespec
struct entry
Macros
#define VLC_NOTHROW
#define TIME_UTC 1
#define aligned_free(ptr) free(ptr)
#define LC_ALL_MASK 0
#define LC_NUMERIC_MASK 0
#define LC_MESSAGES_MASK 0
#define LC_GLOBAL_LOCALE ((locale_t)(uintptr_t)1)
#define STATIC_ASSERT_CONCAT_(a, b) a##b
#define STATIC_ASSERT_CONCAT(a, b) STATIC_ASSERT_CONCAT_(a, b)
#define _Static_assert(x, s) extern char STATIC_ASSERT_CONCAT(static_assert_, __LINE__)[sizeof(struct { unsigned:-!(x); })]
#define static_assert _Static_assert
#define _(str) vlc_gettext (str)
#define N_(str) gettext_noop (str)
#define gettext_noop(str) (str)
#define POLLIN (POLLRDNORM|POLLRDBAND)
#define POLLOUT (POLLWRNORM|POLLWRBAND)
#define if_nametoindex(name) atoi(name)
#define if_nameindex() (errno = ENOBUFS, NULL)
#define if_freenameindex(list) (void)0
#define nanf(tagp) NAN
Typedefs
typedef void * locale_t
typedef struct entry ENTRY
Enumerations
enum {
POLLERR =0x1 , POLLHUP =0x2 , POLLNVAL =0x4 , POLLWRNORM =0x10 ,
POLLWRBAND =0x20 , POLLRDNORM =0x100 , POLLRDBAND =0x200 , POLLPRI =0x400
}
enum ACTION { FIND , ENTER }
enum VISIT { preorder , postorder , endorder , leaf }
Functions
int asprintf (char **, const char *,...)
void flockfile (FILE *)
void funlockfile (FILE *)
int getc_unlocked (FILE *)
int getchar_unlocked (void)
int putc_unlocked (int, FILE *)
int putchar_unlocked (int)
ssize_t getdelim (char **, size_t *, int, FILE *)
ssize_t getline (char **, size_t *, FILE *)
void rewind (FILE *)
int vasprintf (char **, const char *, va_list)
int ffsll (long long)
void * memrchr (const void *, int, size_t)
int strcasecmp (const char *, const char *)
char * strcasestr (const char *, const char *)
char * strdup (const char *)
int strverscmp (const char *, const char *)
size_t strnlen (const char *, size_t)
char * strnstr (const char *, const char *, size_t)
char * strndup (const char *, size_t)
size_t strlcpy (char *, const char *, size_t)
char * strsep (char **, const char *)
char * strtok_r (char *, const char *, char **)
double atof (const char *)
long long atoll (const char *)
lldiv_t lldiv (long long, long long)
float strtof (const char *, char **)
long long int strtoll (const char *, char **, int)
struct tm * gmtime_r (const time_t *, struct tm *)
struct tm * localtime_r (const time_t *, struct tm *)
time_t timegm (struct tm *)
int timespec_get (struct timespec *, int)
int gettimeofday (struct timeval *, struct timezone *)
pid_t getpid (void)
int fsync (int fd)
long pathconf (const char *path, int name)
int dirfd (DIR *)
DIR * fdopendir (int)
static char * getenv (const char *name)
int setenv (const char *, const char *, int)
int unsetenv (const char *)
void * aligned_alloc (size_t, size_t)
static void freelocale (locale_t loc)
static locale_t newlocale (int mask, const char *locale, locale_t base)
static locale_t uselocale (locale_t loc)
void swab (const void *, void *, ssize_t)
int inet_pton (int, const char *, void *)
const char * inet_ntop (int, const void *, char *, socklen_t)
int poll (struct pollfd *, unsigned, int)
ssize_t recvmsg (int, struct msghdr *, int)
ssize_t sendmsg (int, const struct msghdr *, int)
void * tsearch (const void *key, void **rootp, int(*cmp)(const void *, const void *))
void * tfind (const void *key, const void **rootp, int(*cmp)(const void *, const void *))
void * tdelete (const void *key, void **rootp, int(*cmp)(const void *, const void *))
void twalk (const void *root, void(*action)(const void *nodep, VISIT which, int depth))
void tdestroy (void *root, void(*free_node)(void *nodep))
double erand48 (unsigned short subi[3])
long jrand48 (unsigned short subi[3])
long nrand48 (unsigned short subi[3])
void sincos (double, double *, double *)
void sincosf (float, float *, float *)
char * realpath (const char *restrict pathname, char *restrict resolved_path)
Detailed Description
This file is a collection of portability fixes.
Macro Definition Documentation
_
#define _ (str) vlc_gettext (str)
Referenced by aout_FiltersPipelineCreate(), aout_New(), aout_PrepareStereoMode(), config_ListModules(), ControlNavDisplayVolume(), decoder_New(), DecoderUnsupportedCodec(), EnumClockSource(), EsInfoCategoryName(), EsOutESVarUpdateGeneric(), EsOutProgramGetMetaName(), EsOutProgramGetProgramName(), EsOutProgramUpdateScrambled(), EsOutSend(), EsOutUpdateInfo(), Help(), input_ControlVarInit(), input_ControlVarNavigation(), input_ControlVarTitle(), input_DecoderSetCcState(), input_vaControl(), InputSourceNew(), intf_Create(), libvlc_InternalAddIntf(), libvlc_InternalInit(), Open(), playlist_Create(), playlist_MLLoad(), playlist_NodeCreate(), print_help_on_full_help(), print_item(), size_str(), update_DownloadReal(), Usage(), Version(), vlc_strerror_c(), vlm_ControlMediaInstanceStart(), vlm_OnMediaUpdate(), vout_InitInterlacingSupport(), and vout_IntfInit().
_Static_assert
#define _Static_assert (x, s) extern char STATIC_ASSERT_CONCAT(static_assert_, __LINE__)[sizeof(struct { unsigned:-!(x); })]
aligned_free
#define aligned_free (ptr) free(ptr)
Referenced by picture_Destroy(), and picture_pool_Destroy().
gettext_noop
#define gettext_noop (str) (str)
if_freenameindex
#define if_freenameindex (list) (void)0
if_nameindex
#define if_nameindex () (errno = ENOBUFS, NULL)
if_nametoindex
#define if_nametoindex (name) atoi(name)
Referenced by net_SetMcastOut(), and var_GetIfIndex().
LC_ALL_MASK
#define LC_ALL_MASK 0
LC_GLOBAL_LOCALE
#define LC_GLOBAL_LOCALE ((locale_t)(uintptr_t)1)
LC_MESSAGES_MASK
#define LC_MESSAGES_MASK 0
Referenced by vlc_strerror_l().
LC_NUMERIC_MASK
#define LC_NUMERIC_MASK 0
Referenced by config_LoadConfigFile(), config_SaveConfigFile(), us_strtod(), us_strtof(), and us_vasprintf().
N_
#define N_ (str) gettext_noop (str)
Referenced by config_SaveConfigFile(), decoder_New(), DecoderUnsupportedCodec(), EsOutUpdateInfo(), vlc_keycode2str(), and vlc_meta_TypeToLocalizedString().
nanf
#define nanf (tagp) NAN
POLLIN
#define POLLIN (POLLRDNORM|POLLRDBAND)
Referenced by httpdLoop(), net_Accept(), vlc_accept_i11e(), vlc_https_recv(), vlc_poll_i11e_inner(), vlc_readv_i11e(), vlc_recvmsg_i11e(), vlc_tls_ClientSessionCreate(), and vlc_tls_Read().
POLLOUT
#define POLLOUT (POLLWRNORM|POLLWRBAND)
Referenced by httpdLoop(), net_Connect(), vlc_https_send(), vlc_sendmsg_i11e(), vlc_tls_ClientSessionCreate(), vlc_tls_WaitConnect(), vlc_tls_Write(), and vlc_writev_i11e().
static_assert
#define static_assert _Static_assert
STATIC_ASSERT_CONCAT
#define STATIC_ASSERT_CONCAT (a, b) STATIC_ASSERT_CONCAT_(a, b)
STATIC_ASSERT_CONCAT_
#define STATIC_ASSERT_CONCAT_ (a, b) a##b
TIME_UTC
#define TIME_UTC 1
Referenced by NTPtime64(), and vout_snapshot_SaveImage().
VLC_NOTHROW
#define VLC_NOTHROW
Typedef Documentation
ENTRY
typedef struct entry ENTRY
locale_t
typedef void* locale_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
POLLERR
POLLHUP
POLLNVAL
POLLWRNORM
POLLWRBAND
POLLRDNORM
POLLRDBAND
POLLPRI
ACTION
enum ACTION
Enumerator
FIND
ENTER
VISIT
enum VISIT
Enumerator
preorder
postorder
endorder
leaf
Function Documentation
aligned_alloc()
void * aligned_alloc (size_t , size_t)
Referenced by AllocatePicture(), and picture_pool_NewExtended().
asprintf()
int asprintf (char ** , const char * , ...)
Referenced by AppendRemapFilter(), ArtCacheGetDirPath(), ArtCacheName(), config_AddIntf(), config_GetAppDir(), config_GetAppDir(), config_GetConfigFile(), config_GetDataDir(), config_GetHomeDir(), config_GetLibDir(), config_GetTypeDir(), config_GetUserDir(), config_LoadCmdLine(), config_OpenConfigFile(), config_RemoveIntf(), config_SaveConfigFile(), CreateCacheKey(), DisplayVoutTitle(), download_key(), EsInfoCategoryName(), EsOutCreateCCChannels(), EsOutESVarUpdateGeneric(), EsOutProgramGetMetaName(), EsOutProgramGetProgramName(), EsOutProgramMeta(), EsOutSetRecord(), get_path(), getAppDependentDir(), GetDefaultArtUri(), GetDirByItemUIDs(), GetFileByItemUID(), GetTmpFile(), httpd_HtmlError(), input_ControlVarNavigation(), input_ControlVarTitle(), input_CreateFilename(), input_item_SetEpg(), input_item_SetEpgOffline(), input_item_SetURI(), input_vaControl(), InputDemuxNew(), InputGetExtraFilesPattern(), InputSourceNew(), libvlc_InternalInit(), LoadSlaves(), paths_to_list(), playlist_FindArtInCache(), playlist_MLDump(), playlist_MLLoad(), print_item(), size_str(), sout_stream_url_to_chain(), subtitles_Detect(), update_DownloadReal(), vlc_bindtextdomain(), vlc_credential_store(), vlc_getProxyUrl(), vlc_http_auth_FormatAuthorizationHeader(), vlc_http_authority(), vlc_http_authority(), vlc_http_cookies_fetch(), vlc_http_msg_add_creds_basic(), vlc_http_msg_vadd_header(), vlc_http_proxy_find(), vlc_http_res_get_redirect(), vlc_http_res_init(), vlc_keycode2str(), vlc_path2uri(), vlc_readdir(), vlc_renderer_item_new(), vlc_uri2path(), vlc_uri_merge_paths(), vlm_ControlMediaInstanceStart(), vlm_New(), vlm_OnMediaUpdate(), vout_OSDEpgEvent(), vout_OSDPrintTime(), and vout_snapshot_SaveImage().
atof()
double atof (const char *)
Referenced by config_LoadConfigFile(), and Create().
atoll()
long long atoll (const char *)
dirfd()
int dirfd (DIR *)
Referenced by vlc_readdir().
erand48()
double erand48 (unsigned short subi[3])
Referenced by vlc_drand48().
fdopendir()
DIR * fdopendir (int)
ffsll()
int ffsll (long long)
Referenced by fnsll(), picture_pool_Get(), and picture_pool_Wait().
flockfile()
void flockfile (FILE *)
freelocale()
static void freelocale (locale_t loc) inline static
Referenced by config_LoadConfigFile(), config_SaveConfigFile(), us_strtod(), us_strtof(), us_vasprintf(), and vlc_strerror_l().
fsync()
int fsync (int fd)
Referenced by vlc_trace().
funlockfile()
void funlockfile (FILE *)
getc_unlocked()
int getc_unlocked (FILE *)
getchar_unlocked()
int getchar_unlocked (void)
getdelim()
ssize_t getdelim (char ** , size_t * , int , FILE *)
getenv()
static char * getenv (const char * name) inline static
References name.
Referenced by config_GetAppDir(), config_GetDataDir(), config_GetHomeDir(), config_GetHomeDir(), config_GetTypeDir(), rootwrap_bind(), system_Init(), vlc_getcwd(), and vlc_getProxyUrl().
getline()
ssize_t getline (char ** , size_t * , FILE *)
Referenced by config_GetLibDir(), config_GetTypeDir(), and config_LoadConfigFile().
getpid()
pid_t getpid (void)
Referenced by config_SaveConfigFile(), libvlc_InternalInit(), and playlist_MLDump().
gettimeofday()
int gettimeofday (struct timeval * , struct timezone *)
Referenced by mdate(), and vlc_cond_timedwait_daytime().
gmtime_r()
struct tm * gmtime_r (const time_t * , struct tm *)
Referenced by vlc_http_msg_add_time(), and vout_snapshot_SaveImage().
inet_ntop()
const char * inet_ntop (int , const void * , char * , socklen_t)
inet_pton()
int inet_pton (int , const char * , void *)
jrand48()
long jrand48 (unsigned short subi[3])
Referenced by vlc_mrand48().
lldiv()
lldiv_t lldiv (long long , long long)
Referenced by date_Increment(), EsOutUpdateInfo(), mdate(), mdate_perf(), mtime_to_ts(), vlc_addr_timedwait(), and write_duration().
localtime_r()
struct tm * localtime_r (const time_t * , struct tm *)
Referenced by input_item_SetEpg(), vlc_strftime(), vout_OSDPrintTime(), and vout_snapshot_SaveImage().
memrchr()
void * memrchr (const void * , int , size_t)
Referenced by vlc_uri_remove_dot_segments().
newlocale()
static locale_t newlocale (int mask, const char * locale, locale_t base) inline static
Referenced by config_LoadConfigFile(), config_SaveConfigFile(), us_strtod(), us_strtof(), us_vasprintf(), and vlc_strerror_l().
nrand48()
long nrand48 (unsigned short subi[3])
Referenced by vlc_lrand48().
pathconf()
long pathconf (const char * path, int name)
Referenced by vlc_getcwd().
poll()
int poll (struct pollfd * , unsigned , int)
Referenced by httpdLoop(), net_Accept(), vlc_https_recv(), vlc_https_send(), vlc_poll_i11e(), and vlc_poll_i11e_inner().
putc_unlocked()
int putc_unlocked (int , FILE *)
putchar_unlocked()
int putchar_unlocked (int)
realpath()
char * realpath (const char *restrict pathname, char *restrict resolved_path)
recvmsg()
ssize_t recvmsg (int , struct msghdr * , int)
Referenced by recv_fd(), vlc_recvmsg_i11e(), and vlc_tls_SocketRead().
rewind()
void rewind (FILE *)
Referenced by config_LoadConfigFile().
sendmsg()
ssize_t sendmsg (int , const struct msghdr * , int)
Referenced by vlc_sendmsg_i11e(), vlc_tls_ConnectWrite(), and vlc_tls_SocketWrite().
setenv()
int setenv (const char * , const char * , int)
Referenced by system_Init().
sincos()
void sincos (double , double * , double *)
sincosf()
void sincosf (float , float * , float *)
strcasecmp()
int strcasecmp (const char * , const char *)
Referenced by aout_FiltersNew(), bsearch_strcmp_cb(), Create(), demux_IsPathExtension(), demux_NewAdvanced(), httpd_ClientRecv(), httpd_MsgGet(), httpd_StreamCallBack(), httpdLoop(), image_Type2Fourcc(), InputSourceNew(), LanguageArrayIndex(), LanguageGetCode(), meta_sort(), meta_strcasecmp_title(), module_match_name(), proto_SORT_URI(), protocol_is_smb(), protocol_set_port(), protocol_store_path(), rdh_get_slave_priority(), rdh_should_match_idx(), stream_HasExtension(), stream_IsMimeType(), subtitles_Detect(), subtitles_Filter(), VisualizationCallback(), vlc_html_color(), vlc_http_msg_add_cookies(), vlc_http_msg_find_header(), vlc_http_msg_get_cookies(), vlc_http_msg_h2_frame(), vlc_http_msg_vadd_header(), vlc_https_connect_proxy(), vlc_mime_Ext2Mime(), and vlc_module_load().
strcasestr()
char * strcasestr (const char * , const char *)
Referenced by input_item_MetaMatch().
strdup()
char * strdup (const char *)
Referenced by access_New(), addons_manager_Gather(), aout_DeviceSet(), aout_DevicesList(), aout_HotplugNotify(), ArtCacheGetDirPath(), ArtCacheName(), AuthDigest(), AuthGetParam(), AuthGetParamNoQuotes(), config_ChainCreate(), config_ChainDuplicate(), config_GetDataDir(), config_GetGenericDir(), config_GetHomeDir(), config_GetHomeDir(), config_GetIntChoices(), config_GetLibDir(), config_GetTypeDir(), config_LoadCmdLine(), config_PutPsz(), cookie_default_path(), cookie_parse(), Create(), demux_FilterChainNew(), demux_NewAdvanced(), DupString(), es_format_Copy(), EsOutESVarUpdateGeneric(), EsOutProgramGetProgramName(), EsOutProgramMeta(), get_java_string(), GetTmpFile(), GetVarSlaves(), hpack_lookup_name(), hpack_lookup_value(), httpd_ClientRecv(), httpd_MsgAdd(), httpd_StreamSetHTTPHeaders(), info_category_New(), info_New(), input_ControlVarNavigation(), input_ControlVarTitle(), input_EsOutTimeshiftNew(), input_item_AddOption(), input_item_CopyOptions(), input_item_GetInfo(), input_item_GetMeta(), input_item_GetName(), input_item_GetTitleFbName(), input_item_GetURI(), input_item_SetName(), input_item_SetURI(), input_SubtitleFile2Uri(), InputGetExtraFilesPattern(), InputSourceNew(), LanguageGetCode(), LanguageGetName(), LanguageSplit(), libvlc_InternalInit(), makeaddrinfo(), Manage(), mrl_Parse(), rdh_name_from_filename(), se_InitDirectory(), sout_AccessOutNew(), sout_NewInstance(), sout_StreamChainNew(), spu_ChangeFilters(), spu_ChangeSources(), spu_PutSubpicture(), strdupnull(), strdupnull(), stream_AccessNew(), stream_FilterChainNew(), StreamExtractorAttach(), subtitles_Detect(), system_Configure(), text_segment_New(), text_style_Copy(), text_style_Merge(), ThreadChangeFilters(), TwalkGetNames(), update_Download(), var_Change(), var_Create(), var_Inherit(), var_OptionParse(), vlc_dialog_id_post_login(), vlc_dictionary_all_keys(), vlc_dictionary_insert_impl_(), vlc_epg_Duplicate(), vlc_epg_event_Duplicate(), vlc_getProxyUrl(), vlc_getProxyUrl(), vlc_http_msg_h2_headers(), vlc_http_msg_vadd_header(), vlc_http_req_create(), vlc_http_res_get_type(), vlc_http_res_init(), vlc_http_res_set_login(), vlc_idna_to_ascii(), vlc_input_attachment_New(), vlc_input_title_Duplicate(), vlc_loaddir(), vlc_meta_AddExtra(), vlc_meta_Merge(), vlc_meta_Set(), vlc_module_store(), vlc_object_get_name(), vlc_object_set_name(), vlc_path2uri(), vlc_plugin_desc_cb(), vlc_rd_probe_add(), vlc_readdir(), vlc_readdir_helper_additem(), vlc_renderer_item_new(), vlc_sd_probe_Add(), vlc_seekpoint_Duplicate(), vlc_stream_FilterNew(), vlc_strftime(), vlc_uri2path(), vlc_uri_decode_duplicate(), vlc_uri_fixup(), vlc_uri_resolve(), vlc_UrlParseInner(), vlc_vaLogEarly(), vlm_ControlMediaInstanceGets(), vlm_media_Copy(), vlm_MediaInstanceNew(), vlm_OnMediaUpdate(), vout_control_PushMessage(), vout_control_PushString(), vout_OSDEpg(), vout_OSDText(), vout_snapshot_SaveImage(), and xstrdup().
strlcpy()
size_t strlcpy (char * , const char * , size_t)
Referenced by AddressCreate(), and strcpy_strip_ext().
strndup()
char * strndup (const char * , size_t)
Referenced by access_New(), AuthGetParam(), AuthGetParamNoQuotes(), ChainGetValue(), config_ChainCreate(), config_ChainParseOptions(), cookie_default_path(), cookie_get_attribute_value(), cookie_parse(), mrl_FragmentSplit(), smb_split_domain(), vlc_http_msg_add_cookies(), vlc_http_msg_headers(), and vlc_uri2path().
strnlen()
size_t strnlen (const char * , size_t)
strnstr()
char * strnstr (const char * , const char * , size_t)
strsep()
char * strsep (char ** , const char *)
Referenced by aout_FiltersNew(), and playlist_Create().
strtof()
float strtof (const char * , char **)
Referenced by us_strtof().
strtok_r()
char * strtok_r (char * , const char * , char **)
Referenced by EsOutSelect(), init_action(), InitPrograms(), stream_FilterChainNew(), and vlc_actions_get_keycodes().
strtoll()
long long int strtoll (const char * , char ** , int)
Referenced by config_LoadCmdLine(), var_OptionParse(), and vlc_strtoi().
strverscmp()
int strverscmp (const char * , const char *)
swab()
void swab (const void * , void * , ssize_t)
tdelete()
void * tdelete (const void * key, void ** rootp, int(* cmp)(const void *, const void *))
Referenced by playlist_ItemNewFromInput(), playlist_ItemRelease(), and var_Destroy().
tdestroy()
void tdestroy (void * root, void(* free_node)(void *nodep))
Referenced by libvlc_InternalActionsClean(), module_EndBank(), var_DestroyAll(), vlc_plugin_free_symbols(), and vlc_plugin_get_symbols().
tfind()
void * tfind (const void * key, const void ** rootp, int(* cmp)(const void *, const void *))
Referenced by Lookup(), module_list_cap(), playlist_ItemGetById(), playlist_ItemGetByInput(), vlc_key_to_action(), and vlc_plugin_get_symbol().
timegm()
time_t timegm (struct tm *)
Referenced by vlc_http_mktime().
timespec_get()
int timespec_get (struct timespec * , int)
Referenced by NTPtime64(), and vout_snapshot_SaveImage().
tsearch()
void * tsearch (const void * key, void ** rootp, int(* cmp)(const void *, const void *))
Referenced by add_mapping(), playlist_ItemNewFromInput(), var_Create(), vlc_module_store(), and vlc_plugin_gpa_cb().
twalk()
void twalk (const void * root, void(* action)(const void *nodep, VISIT which, int depth))
Referenced by DumpVariables(), module_LoadPlugins(), and var_GetAllNames().
unsetenv()
int unsetenv (const char *)
uselocale()
static locale_t uselocale (locale_t loc) inline static
Referenced by config_LoadConfigFile(), config_SaveConfigFile(), us_strtod(), us_strtof(), and us_vasprintf().
vasprintf()
int vasprintf (char ** , const char * , va_list)
Referenced by dialog_display_error_va(), dialog_display_login_va(), dialog_display_question_va(), display_progress_va(), info_category_VaAddInfo(), input_vaControl(), net_vaPrintf(), us_vasprintf(), utf8_vfprintf(), vlc_dialog_update_progress_text_va(), vlc_http_msg_vadd_header(), vlc_vaLogEarly(), and vout_OSDMessage().