VLC: include/vlc_fingerprinter.h File Reference
vlc_fingerprinter.h File Reference
Data Structures
struct fingerprint_request_t
struct fingerprinter_thread_t
Typedefs
typedef struct fingerprinter_sys_t fingerprinter_sys_t
typedef struct fingerprint_request_t fingerprint_request_t
typedef struct fingerprinter_thread_t fingerprinter_thread_t
Functions
static fingerprint_request_t * fingerprint_request_New (input_item_t *p_item)
static void fingerprint_request_Delete (fingerprint_request_t *p_f)
fingerprinter_thread_t * fingerprinter_Create (vlc_object_t *p_this)
void fingerprinter_Destroy (fingerprinter_thread_t *p_fingerprint)
Typedef Documentation
fingerprint_request_t
typedef struct fingerprint_request_t fingerprint_request_t
fingerprinter_sys_t
typedef struct fingerprinter_sys_t fingerprinter_sys_t
fingerprinter_thread_t
typedef struct fingerprinter_thread_t fingerprinter_thread_t
Function Documentation
fingerprint_request_Delete()
static void fingerprint_request_Delete (fingerprint_request_t * p_f) inline static
References input_item_Release(), fingerprint_request_t::metas_array, fingerprint_request_t::p_item, fingerprint_request_t::psz_fingerprint, fingerprint_request_t::results, vlc_array_count(), vlc_array_item_at_index, and vlc_meta_Delete().
fingerprint_request_New()
static fingerprint_request_t * fingerprint_request_New (input_item_t * p_item) inline static
References fingerprint_request_t::i_duration, input_item_Hold(), fingerprint_request_t::metas_array, fingerprint_request_t::p_item, fingerprint_request_t::psz_fingerprint, fingerprint_request_t::results, and vlc_array_init().
fingerprinter_Create()
fingerprinter_thread_t * fingerprinter_Create (vlc_object_t * p_this)
References module_need, msg_Err, fingerprinter_thread_t::p_module, vlc_custom_create, and vlc_object_release.
fingerprinter_Destroy()
void fingerprinter_Destroy (fingerprinter_thread_t * p_fingerprint)
References module_unneed, fingerprinter_thread_t::p_module, and vlc_object_release.