VLC: include/vlc_http.h File Reference
vlc_http.h File Reference
This file defines functions, structures, enums and macros shared between HTTP clients.
Data Structures
struct vlc_http_auth_t
Typedefs
typedef struct vlc_http_auth_t vlc_http_auth_t
typedef struct vlc_http_cookie_jar_t vlc_http_cookie_jar_t
Functions
void vlc_http_auth_Init (vlc_http_auth_t *)
void vlc_http_auth_Deinit (vlc_http_auth_t *)
void vlc_http_auth_ParseWwwAuthenticateHeader (vlc_object_t *, vlc_http_auth_t *, const char *)
int vlc_http_auth_ParseAuthenticationInfoHeader (vlc_object_t *, vlc_http_auth_t *, const char *, const char *, const char *, const char *, const char *)
char * vlc_http_auth_FormatAuthorizationHeader (vlc_object_t *, vlc_http_auth_t *, const char *, const char *, const char *, const char *)
vlc_http_cookie_jar_t * vlc_http_cookies_new (void)
void vlc_http_cookies_destroy (vlc_http_cookie_jar_t *p_jar)
bool vlc_http_cookies_store (vlc_http_cookie_jar_t *jar, const char *cookie, const char *host, const char *path)
Parse a value of an incoming Set-Cookie header and append the cookie to the cookie jar if appropriate.
char * vlc_http_cookies_fetch (vlc_http_cookie_jar_t *jar, bool secure, const char *host, const char *path)
Returns a cookie value that match the given URL.
Detailed Description
This file defines functions, structures, enums and macros shared between HTTP clients.
Typedef Documentation
vlc_http_auth_t
typedef struct vlc_http_auth_t vlc_http_auth_t
vlc_http_cookie_jar_t
typedef struct vlc_http_cookie_jar_t vlc_http_cookie_jar_t
Function Documentation
vlc_http_auth_Deinit()
void vlc_http_auth_Deinit (vlc_http_auth_t * p_auth)
References vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_domain, vlc_http_auth_t::psz_HA1, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_http_auth_t::psz_stale.
vlc_http_auth_FormatAuthorizationHeader()
char * vlc_http_auth_FormatAuthorizationHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_method, const char * psz_path, const char * psz_username, const char * psz_password)
References asprintf(), AuthDigest(), GenerateCnonce(), vlc_http_auth_t::i_nonce, msg_Err, vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_b64_encode().
vlc_http_auth_Init()
void vlc_http_auth_Init (vlc_http_auth_t * p_auth)
vlc_http_auth_ParseAuthenticationInfoHeader()
int vlc_http_auth_ParseAuthenticationInfoHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_header, const char * psz_method, const char * psz_path, const char * psz_username, const char * psz_password)
< No error
< Unspecified error
< Unspecified error
< Unspecified error
References AuthDigest(), AuthGetParam(), AuthGetParamNoQuotes(), vlc_http_auth_t::i_nonce, msg_Err, msg_Warn, vlc_http_auth_t::psz_cnonce, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_qop, VLC_EGENERIC, and VLC_SUCCESS.
vlc_http_auth_ParseWwwAuthenticateHeader()
void vlc_http_auth_ParseWwwAuthenticateHeader (vlc_object_t * p_this, vlc_http_auth_t * p_auth, const char * psz_header)
References AuthGetParam(), AuthGetParamNoQuotes(), vlc_http_auth_t::i_nonce, msg_Dbg, msg_Warn, vlc_http_auth_t::psz_algorithm, vlc_http_auth_t::psz_domain, vlc_http_auth_t::psz_nonce, vlc_http_auth_t::psz_opaque, vlc_http_auth_t::psz_qop, vlc_http_auth_t::psz_realm, and vlc_http_auth_t::psz_stale.
vlc_http_cookies_destroy()
void vlc_http_cookies_destroy (vlc_http_cookie_jar_t * p_jar)
References cookie_destroy(), vlc_http_cookie_jar_t::cookies, vlc_http_cookie_jar_t::lock, vlc_array_clear(), vlc_array_count(), vlc_array_item_at_index, and vlc_mutex_destroy().
Referenced by playlist_Destroy().
vlc_http_cookies_fetch()
char * vlc_http_cookies_fetch (vlc_http_cookie_jar_t * jar, bool secure, const char * host, const char * path)
Returns a cookie value that match the given URL.
Parameters
p_jar a cookie jar
p_url the URL for which the cookies are returned
Returns
A string consisting of semicolon-separated cookie NAME=VALUE pairs.
References asprintf(), cookie_should_be_sent(), vlc_http_cookie_jar_t::cookies, vlc_http_cookie_jar_t::lock, http_cookie_t::psz_name, http_cookie_t::psz_value, vlc_array_count(), vlc_array_item_at_index, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vlc_http_msg_add_cookies().
vlc_http_cookies_new()
vlc_http_cookie_jar_t * vlc_http_cookies_new (void)
References vlc_http_cookie_jar_t::cookies, vlc_http_cookie_jar_t::lock, unlikely, vlc_array_init(), and vlc_mutex_init().
Referenced by playlist_Create().
vlc_http_cookies_store()
bool vlc_http_cookies_store (vlc_http_cookie_jar_t * jar, const char * cookie, const char * host, const char * path)
Parse a value of an incoming Set-Cookie header and append the cookie to the cookie jar if appropriate.
Parameters
jar cookie jar object
cookie header field value of Set-Cookie
Returns
true, if the cookie was added, false otherwise
References cookie_destroy(), cookie_domain_matches(), cookie_parse(), vlc_http_cookie_jar_t::cookies, vlc_http_cookie_jar_t::lock, http_cookie_t::psz_domain, http_cookie_t::psz_name, http_cookie_t::psz_path, vlc_array_append(), vlc_array_count(), vlc_array_item_at_index, vlc_array_remove(), vlc_ascii_strcasecmp(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vlc_http_msg_get_cookies().