VLC: include/vlc_modules.h File Reference
vlc_modules.h File Reference
This file defines functions for modules in vlc.
Macros
#define vlc_module_load(o, c, n, s, ...) vlc_module_load(VLC_OBJECT(o),c,n,s,__VA_ARGS__)
#define vlc_module_unload(o, m, d, ...) vlc_module_unload(VLC_OBJECT(o),m,d,__VA_ARGS__)
#define module_need(a, b, c, d) module_need(VLC_OBJECT(a),b,c,d)
#define module_unneed(a, b) module_unneed(VLC_OBJECT(a),b)
#define module_start(o, m) module_start(VLC_OBJECT(o),m)
#define module_stop(o, m) module_stop(VLC_OBJECT(o),m)
#define module_GetLongName(m) module_get_name(m, true)
#define module_get_main(a) module_get_main()
Typedefs
typedef int(* vlc_activate_t) (void *func, va_list args)
typedef void(* vlc_deactivate_t) (void *func, va_list args)
Functions
module_t * vlc_module_load (vlc_object_t *obj, const char *cap, const char *name, bool strict, vlc_activate_t probe,...)
Finds and instantiates the best module of a certain type.
void vlc_module_unload (vlc_object_t *obj, module_t *, vlc_deactivate_t deinit,...)
Deinstantiates a module.
module_t * module_need (vlc_object_t *, const char *, const char *, bool)
void module_unneed (vlc_object_t *, module_t *)
bool module_exists (const char *)
Tell if a module exists.
module_t * module_find (const char *)
Get a pointer to a module_t given it's name.
int module_start (vlc_object_t *, const module_t *)
void module_stop (vlc_object_t *, const module_t *)
module_config_t * module_config_get (const module_t *, unsigned *)
void module_config_free (module_config_t *)
Release the configuration.
void module_list_free (module_t **)
Frees the flat list of VLC modules.
module_t ** module_list_get (size_t *n)
Gets the flat list of VLC modules.
bool module_provides (const module_t *m, const char *cap)
Checks whether a module implements a capability.
const char * module_get_object (const module_t *m)
Get the internal name of a module.
const char * module_get_name (const module_t *m, bool long_name)
Get the human-friendly name of a module.
const char * module_get_help (const module_t *m)
Get the help for a module.
const char * module_get_capability (const module_t *m)
Gets the capability of a module.
int module_get_score (const module_t *m)
Get the score for a module.
const char * module_gettext (const module_t *, const char *)
Translate a string using the module's text domain.
static module_t * module_get_main (void)
static bool module_is_main (const module_t *p_module)
Detailed Description
This file defines functions for modules in vlc.
Macro Definition Documentation
module_get_main
#define module_get_main (a) module_get_main()
module_GetLongName
#define module_GetLongName (m) module_get_name(m, true)
module_need
#define module_need (a, b, c, d) module_need(VLC_OBJECT(a),b,c,d)
Referenced by access_New(), addons_manager_WriteCatalog(), aout_New(), aout_volume_SetFormat(), CreateDecoder(), CreateEncoder(), CreateFilter(), CreateFilter(), demux_FilterNew(), demux_NewAdvanced(), demux_PacketizerNew(), filter_chain_AppendInner(), filter_ConfigureBlend(), FinderThread(), fingerprinter_Create(), input_item_WriteMeta(), InputSourceMeta(), installOrRemoveAddon(), intf_Create(), InvokeModule(), keystore_create(), LoadDecoder(), LoadLocalStorage(), playlist_Export(), sout_AccessOutNew(), sout_MuxNew(), sout_StreamNew(), SpuRenderCreateAndLoadScale(), SpuRenderCreateAndLoadText(), StreamExtractorAttach(), video_splitter_New(), vlc_gl_Create(), vlc_inhibit_Create(), vlc_probe(), vlc_rd_new(), vlc_sd_Create(), vlc_stream_FilterNew(), vlm_ControlMediaAdd(), vout_display_New(), xml_Create(), and xml_ReaderCreate().
module_start
#define module_start (o, m) module_start(VLC_OBJECT(o),m)
Referenced by xml_ReaderReset().
module_stop
#define module_stop (o, m) module_stop(VLC_OBJECT(o),m)
Referenced by xml_ReaderDelete(), and xml_ReaderReset().
module_unneed
#define module_unneed (a, b) module_unneed(VLC_OBJECT(a),b)
Referenced by addons_manager_WriteCatalog(), aout_Destroy(), aout_FiltersPipelineDestroy(), aout_volume_Delete(), aout_volume_SetFormat(), AppendFilter(), DeleteDecoder(), DeleteEncoder(), DeleteFilter(), demux_Delete(), demux_PacketizerDestroy(), filter_chain_DeleteFilter(), filter_ConfigureBlend(), filter_DeleteBlend(), FilterRelease(), FinderThread(), fingerprinter_Destroy(), input_item_WriteMeta(), InputSourceMeta(), installOrRemoveAddon(), intf_Create(), intf_DestroyAll(), InvokeModule(), LoadLocalStorage(), playlist_Export(), se_Release(), sout_AccessOutDelete(), sout_MuxDelete(), sout_StreamDelete(), StreamDelete(), UnloadDecoder(), video_splitter_Delete(), vlc_access_Destroy(), vlc_gl_Release(), vlc_inhibit_Destroy(), vlc_keystore_release(), vlc_probe(), vlc_rd_release(), vlc_sd_Destroy(), vlm_Delete(), vout_display_Delete(), and xml_Delete().
vlc_module_load
#define vlc_module_load (o, c, n, s, ...) vlc_module_load(VLC_OBJECT(o),c,n,s,__VA_ARGS__)
Referenced by demux_NewAdvanced(), module_need(), vlc_LogInit(), vlc_tls_ClientCreate(), vlc_tls_ServerCreate(), and vout_window_New().
vlc_module_unload
#define vlc_module_unload (o, m, d, ...) vlc_module_unload(VLC_OBJECT(o),m,d,__VA_ARGS__)
Referenced by module_unneed(), vlc_LogDeinit(), vlc_LogSet(), vlc_tls_Delete(), and vout_window_Delete().
Typedef Documentation
vlc_activate_t
typedef int(* vlc_activate_t) (void *func, va_list args)
vlc_deactivate_t
typedef void(* vlc_deactivate_t) (void *func, va_list args)
Function Documentation
module_config_free()
void module_config_free (module_config_t * config)
Release the configuration.
Parameters
the configuration
Returns
nothing
References config.
module_config_get()
module_config_t * module_config_get (const module_t * , unsigned *)
module_exists()
bool module_exists (const char * psz_name)
Tell if a module exists.
Parameters
psz_name th name of the module
Returns
TRUE if the module exists
References module_find(), and psz_name.
Referenced by aout_New().
module_find()
module_t * module_find (const char * name)
Get a pointer to a module_t given it's name.
Parameters
name the name of the module
Returns
a pointer to the module or NULL in case of a failure
References count, module_t::i_shortcuts, list, module_list_free(), module_list_get(), name, module_t::pp_shortcuts, and unlikely.
Referenced by module_exists(), and module_get_main().
module_get_capability()
const char * module_get_capability (const module_t * m)
Gets the capability of a module.
Parameters
m the module
Returns
the capability, or "none" if unspecified
References module_t::psz_capability.
Referenced by module_provides(), and vlc_module_store().
module_get_help()
const char * module_get_help (const module_t * m)
Get the help for a module.
Parameters
m the module
Returns
the help
References module_t::psz_help.
module_get_main()
static module_t * module_get_main (void) inline static
References module_find().
module_get_name()
const char * module_get_name (const module_t * m, bool long_name)
Get the human-friendly name of a module.
Parameters
m the module
long_name TRUE to have the long name of the module
Returns
the short or long name of the module
References module_get_object(), module_t::psz_longname, and module_t::psz_shortname.
Referenced by config_ListModules(), DecoderFixTs(), demux_filter_enable_disable(), and filter_chain_AppendInner().
module_get_object()
const char * module_get_object (const module_t * m)
Get the internal name of a module.
Parameters
m the module
Returns
the module name
References module_t::i_shortcuts, module_t::pp_shortcuts, and unlikely.
Referenced by config_ListModules(), config_SaveConfigFile(), ListModules(), module_get_name(), module_is_main(), module_match(), module_unneed(), Usage(), and vlc_module_load().
module_get_score()
int module_get_score (const module_t * m)
Get the score for a module.
Parameters
m the module return the score for the capability
References module_t::i_score.
Referenced by vlc_module_load().
module_gettext()
const char * module_gettext (const module_t * m, const char * str)
Translate a string using the module's text domain.
Parameters
m the module
str the American English ASCII string to localize
Returns
the gettext-translated string
References module_t::plugin, vlc_plugin_t::textdomain, and unlikely.
Referenced by config_ListModules(), ListModules(), print_item(), print_section(), and Usage().
module_is_main()
static bool module_is_main (const module_t * p_module) inline static
References module_get_object().
module_list_free()
void module_list_free (module_t ** list)
Frees the flat list of VLC modules.
Parameters
list list obtained by module_list_get()
length number of items on the list
Returns
nothing.
References list.
Referenced by config_ListModules(), ListModules(), module_find(), module_LoadPlugins(), and vlc_module_load().
module_list_get()
module_t ** module_list_get (size_t * n)
Gets the flat list of VLC modules.
Parameters
n [OUT] pointer to the number of modules
Returns
table of module pointers (release with module_list_free()), or NULL in case of error (in that case, *n is zeroed).
References vlc_plugin_t::next, unlikely, and vlc_plugins.
Referenced by ListModules(), module_find(), and module_LoadPlugins().
module_need()
module_t * module_need (vlc_object_t * obj, const char * cap, const char * name, bool strict)
References generic_start(), name, and vlc_module_load.
module_provides()
bool module_provides (const module_t * m, const char * cap)
Checks whether a module implements a capability.
Parameters
m the module
cap the capability to check
Returns
true if the module has the capability
References module_get_capability().
module_start()
int module_start (vlc_object_t * obj, const module_t * m)
< No error
References module_t::pf_activate, and VLC_SUCCESS.
module_stop()
void module_stop (vlc_object_t * obj, const module_t * m)
References module_t::pf_deactivate.
module_unneed()
void module_unneed (vlc_object_t * obj, module_t * module)
References generic_stop(), module_get_object(), msg_Dbg, and vlc_module_unload.
vlc_module_load()
module_t * vlc_module_load (vlc_object_t * obj, const char * capability, const char * name, bool strict, vlc_activate_t probe, ...)
Finds and instantiates the best module of a certain type.
All candidates modules having the specified capability and name will be sorted in decreasing order of priority. Then the probe callback will be invoked for each module, until it succeeds (returns 0), or all candidate module failed to initialize.
The probe callback first parameter is the address of the module entry point. Further parameters are passed as an argument list; it corresponds to the variable arguments passed to this function. This scheme is meant to support arbitrary prototypes for the module entry point.
Parameters
obj VLC object
capability capability, i.e. class of module
name name of the module asked, if any
strict if true, do not fallback to plugin with a different name but the same capability
probe module probe callback
Returns
the module or NULL in case of a failure
< No error
< Timeout
< No error
< Timeout
References vlc_common_members::force, likely, module_get_object(), module_get_score(), module_list_cap(), module_list_free(), module_load(), module_match_name(), msg_Dbg, name, vlc_object_t::obj, strcasecmp(), unlikely, var_InheritString, VLC_ETIMEOUT, vlc_object_set_name, and VLC_SUCCESS.
vlc_module_unload()
void vlc_module_unload (vlc_object_t * obj, module_t * module, vlc_deactivate_t deinit, ...)
Deinstantiates a module.
Parameters
module the module pointer as returned by vlc_module_load()
deinit deactivation callback
References module_t::pf_deactivate, and vlc_objres_clear().