VLC: include/vlc_configuration.h File Reference
vlc_configuration.h File Reference
This file describes the programming interface for the configuration module.
Data Structures
struct config_category_t
union module_value_t
struct module_config_t
struct config_chain_t
Macros
#define config_SaveConfigFile(a) config_SaveConfigFile(VLC_OBJECT(a))
#define config_ResetAll(a) config_ResetAll(VLC_OBJECT(a))
#define config_GetInt(a, b) config_GetInt(VLC_OBJECT(a),b)
#define config_PutInt(a, b, c) config_PutInt(VLC_OBJECT(a),b,c)
#define config_GetFloat(a, b) config_GetFloat(VLC_OBJECT(a),b)
#define config_PutFloat(a, b, c) config_PutFloat(VLC_OBJECT(a),b,c)
#define config_GetPsz(a, b) config_GetPsz(VLC_OBJECT(a),b)
#define config_PutPsz(a, b, c) config_PutPsz(VLC_OBJECT(a),b,c)
#define config_AddIntf(a, b) config_AddIntf(VLC_OBJECT(a),b)
#define config_RemoveIntf(a, b) config_RemoveIntf(VLC_OBJECT(a),b)
#define config_ExistIntf(a, b) config_ExistIntf(VLC_OBJECT(a),b)
#define config_ChainParse(a, b, c, d) config_ChainParse(VLC_OBJECT(a), b, c, d)
Typedefs
typedef int(* vlc_string_list_cb) (vlc_object_t *, const char *, char ***, char ***)
typedef int(* vlc_integer_list_cb) (vlc_object_t *, const char *, int64_t **, char ***)
typedef enum vlc_userdir vlc_userdir_t
Enumerations
enum vlc_userdir {
VLC_HOME_DIR , VLC_CONFIG_DIR , VLC_DATA_DIR , VLC_CACHE_DIR ,
VLC_DESKTOP_DIR =0x80 , VLC_DOWNLOAD_DIR , VLC_TEMPLATES_DIR , VLC_PUBLICSHARE_DIR ,
VLC_DOCUMENTS_DIR , VLC_MUSIC_DIR , VLC_PICTURES_DIR , VLC_VIDEOS_DIR
}
Functions
int config_GetType (const char *)
int64_t config_GetInt (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
void config_PutInt (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *, int64_t)
float config_GetFloat (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
void config_PutFloat (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *, float)
char * config_GetPsz (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
void config_PutPsz (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *, const char *)
ssize_t config_GetIntChoices (vlc_object_t *, const char *, int64_t **, char ***)
ssize_t config_GetPszChoices (vlc_object_t *, const char *, char ***, char ***)
int config_SaveConfigFile (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)))
void config_ResetAll (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)))
module_config_t * config_FindConfig (const char *)
char * config_GetDataDir (void)
Determines the shared data directory.
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
char * config_GetUserDir (vlc_userdir_t)
void config_AddIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
void config_RemoveIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
bool config_ExistIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
void config_ChainParse (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *psz_prefix, const char *const *ppsz_options, config_chain_t *)
This function will.
const char * config_ChainParseOptions (config_chain_t **pp_cfg, const char *ppsz_opts)
This function will parse a configuration string (psz_opts) and.
char * config_ChainCreate (char **ppsz_name, config_chain_t **pp_cfg, const char *psz_string)
This function will parse a configuration string (psz_string) and.
void config_ChainDestroy (config_chain_t *)
This function will release a linked list of config_chain_t (Including the head)
config_chain_t * config_ChainDuplicate (const config_chain_t *)
This function will duplicate a linked list of config_chain_t.
char * config_StringUnescape (char *psz_string)
This function will unescape a string in place and will return a pointer on the given string.
char * config_StringEscape (const char *psz_string)
This function will escape a string that can be unescaped by config_StringUnescape.
Detailed Description
This file describes the programming interface for the configuration module.
It includes functions allowing to declare, get or set configuration options.
Macro Definition Documentation
config_AddIntf
#define config_AddIntf (a, b) config_AddIntf(VLC_OBJECT(a),b)
config_ChainParse
#define config_ChainParse (a, b, c, d) config_ChainParse(VLC_OBJECT(a), b, c, d)
config_ExistIntf
#define config_ExistIntf (a, b) config_ExistIntf(VLC_OBJECT(a),b)
config_GetFloat
#define config_GetFloat (a, b) config_GetFloat(VLC_OBJECT(a),b)
Referenced by var_Inherit().
config_GetInt
#define config_GetInt (a, b) config_GetInt(VLC_OBJECT(a),b)
Referenced by var_Inherit().
config_GetPsz
#define config_GetPsz (a, b) config_GetPsz(VLC_OBJECT(a),b)
Referenced by config_AddIntf(), config_ExistIntf(), config_RemoveIntf(), var_Inherit(), and vlc_getProxyUrl().
config_PutFloat
#define config_PutFloat (a, b, c) config_PutFloat(VLC_OBJECT(a),b,c)
config_PutInt
#define config_PutInt (a, b, c) config_PutInt(VLC_OBJECT(a),b,c)
config_PutPsz
#define config_PutPsz (a, b, c) config_PutPsz(VLC_OBJECT(a),b,c)
Referenced by config_AddIntf(), and config_RemoveIntf().
config_RemoveIntf
#define config_RemoveIntf (a, b) config_RemoveIntf(VLC_OBJECT(a),b)
config_ResetAll
#define config_ResetAll (a) config_ResetAll(VLC_OBJECT(a))
config_SaveConfigFile
#define config_SaveConfigFile (a) config_SaveConfigFile(VLC_OBJECT(a))
Referenced by config_AutoSaveConfigFile(), and libvlc_InternalInit().
Typedef Documentation
vlc_integer_list_cb
typedef int(* vlc_integer_list_cb) (vlc_object_t *, const char *, int64_t **, char ***)
vlc_string_list_cb
typedef int(* vlc_string_list_cb) (vlc_object_t *, const char *, char ***, char ***)
vlc_userdir_t
typedef enum vlc_userdir vlc_userdir_t
Enumeration Type Documentation
vlc_userdir
enum vlc_userdir
Enumerator
VLC_HOME_DIR
VLC_CONFIG_DIR
VLC_DATA_DIR
VLC_CACHE_DIR
VLC_DESKTOP_DIR
VLC_DOWNLOAD_DIR
VLC_TEMPLATES_DIR
VLC_PUBLICSHARE_DIR
VLC_DOCUMENTS_DIR
VLC_MUSIC_DIR
VLC_PICTURES_DIR
VLC_VIDEOS_DIR
Function Documentation
config_AddIntf()
void config_AddIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_ChainCreate()
char * config_ChainCreate (char ** ppsz_name, config_chain_t ** pp_cfg, const char * psz_string)
This function will parse a configuration string (psz_string) and.
set the module name (*ppsz_name)
set all options for this module in a chained list (*pp_cfg)
returns a pointer on the next module if any.
The string format is module{option=*,option=*}[:modulenext{option=*,...}]
The options values are unescaped using config_StringUnescape.
References config_ChainParseOptions(), SKIPSPACE, strdup(), and strndup().
Referenced by AppendRemapFilter(), demux_FilterChainNew(), filter_chain_AppendFromString(), intf_Create(), sout_AccessOutNew(), sout_MuxNew(), sout_StreamChainNew(), ThreadChangeFilters(), vlc_rd_new(), and vlc_sd_Create().
config_ChainDestroy()
void config_ChainDestroy (config_chain_t * p_cfg)
This function will release a linked list of config_chain_t (Including the head)
References FREENULL, config_chain_t::p_next, config_chain_t::psz_name, and config_chain_t::psz_value.
Referenced by aout_FiltersPipelineCreate(), AppendRemapFilter(), demux_FilterChainNew(), filter_chain_AppendFromString(), intf_Create(), intf_DestroyAll(), sout_AccessOutDelete(), sout_MuxDelete(), sout_StreamChainNew(), sout_StreamDelete(), ThreadChangeFilters(), vlc_rd_new(), vlc_rd_release(), and vlc_sd_Destroy().
config_ChainDuplicate()
config_chain_t * config_ChainDuplicate (const config_chain_t * p_src)
This function will duplicate a linked list of config_chain_t.
References p, config_chain_t::p_next, config_chain_t::psz_name, config_chain_t::psz_value, and strdup().
config_ChainParse()
void config_ChainParse (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char * psz_prefix, const char *const * ppsz_options, config_chain_t *)
This function will.
create all options in the array ppsz_options (var_Create).
parse the given linked list of config_chain_t and set the value (var_Set).
The option names will be created by adding the psz_prefix prefix.
config_ChainParseOptions()
const char * config_ChainParseOptions (config_chain_t ** pp_cfg, const char * ppsz_opts)
This function will parse a configuration string (psz_opts) and.
set all options for this module in a chained list (*pp_cfg)
returns a pointer on the next module if any.
The string format is module{option=*,option=*}
The options values are unescaped using config_StringUnescape.
References ChainGetValue(), config_chain_t::p_next, config_chain_t::psz_name, config_chain_t::psz_value, SKIPSPACE, and strndup().
Referenced by aout_FiltersPipelineCreate(), and config_ChainCreate().
config_ExistIntf()
bool config_ExistIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_FindConfig()
module_config_t * config_FindConfig (const char * name)
References config, confnamecmp(), name, p, and unlikely.
Referenced by aout_New(), config_ChainParse(), config_GetFloat(), config_GetInt(), config_GetIntChoices(), config_GetPsz(), config_GetPszChoices(), config_GetType(), config_IsSafe(), config_LoadCmdLine(), config_LoadConfigFile(), config_PutFloat(), config_PutInt(), config_PutPsz(), and vout_InitInterlacingSupport().
config_GetDataDir()
char * config_GetDataDir (void)
Determines the shared data directory.
Returns
a nul-terminated string or NULL. Use free() to release it.
References asprintf(), config_GetLibDir(), getenv(), p, strdup(), and unlikely.
Referenced by GetDefaultArtUri(), and vlc_bindtextdomain().
config_GetFloat()
float config_GetFloat (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_GetInt()
int64_t config_GetInt (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_GetIntChoices()
ssize_t config_GetIntChoices (vlc_object_t * , const char * , int64_t ** , char ***)
config_GetLibDir()
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
Returns
a string (always succeeds).
References asprintf(), config_GetLibDir(), FromLocaleDup, getline(), likely, lock, p, strdup(), system_Init(), vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_STATIC_MUTEX.
Referenced by config_GetDataDir(), config_GetHomeDir(), and config_GetLibDir().
config_GetPsz()
char * config_GetPsz (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_GetPszChoices()
ssize_t config_GetPszChoices (vlc_object_t * , const char * , char *** , char ***)
config_GetType()
int config_GetType (const char * psz_name)
References CONFIG_CLASS, config_FindConfig(), CONFIG_ITEM_BOOL, CONFIG_ITEM_FLOAT, CONFIG_ITEM_INTEGER, CONFIG_ITEM_STRING, module_config_t::i_type, psz_name, VLC_VAR_BOOL, VLC_VAR_FLOAT, VLC_VAR_INTEGER, and VLC_VAR_STRING.
Referenced by config_ChainParse(), and var_OptionParse().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References asprintf(), config_GetAppDir(), config_GetGenericDir(), config_GetHomeDir(), config_GetShellDir(), config_GetTypeDir(), config_GetUserDir(), getAppDependentDir(), ppsz_generic_names, psz_name, vlc_assert_unreachable, VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.
Referenced by ArtCacheGetDirPath(), config_GetConfigFile(), config_GetUserDir(), config_OpenConfigFile(), config_PrepareDir(), EsOutSetRecord(), GetDirByItemUIDs(), playlist_MLDump(), playlist_MLLoad(), and vout_snapshot_GetDirectory().
config_PutFloat()
void config_PutFloat (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char * , float)
config_PutInt()
void config_PutInt (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char * , int64_t)
config_PutPsz()
void config_PutPsz (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char * , const char *)
config_RemoveIntf()
void config_RemoveIntf (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)), const char *)
config_ResetAll()
void config_ResetAll (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)))
config_SaveConfigFile()
int config_SaveConfigFile (_Generic((vlc_object_t *) ->obj, struct vlc_common_members:(vlc_object_t *)(&(vlc_object_t *) ->obj), const struct vlc_common_members:(const vlc_object_t *)(&(vlc_object_t *) ->obj)))
config_StringEscape()
char * config_StringEscape (const char * psz_string)
This function will escape a string that can be unescaped by config_StringUnescape.
The returned value is allocated by it. You have to free it once you do not need it anymore (unlike config_StringUnescape). If NULL is given as parameter nothing will be done (NULL will be returned).
The escaped characters are ' " and \
References IsEscapeNeeded(), p, and unlikely.
Referenced by EsOutSetRecord().
config_StringUnescape()
char * config_StringUnescape (char * psz_string)
This function will unescape a string in place and will return a pointer on the given string.
No memory is allocated by it (unlike config_StringEscape). If NULL is given as parameter nothing will be done (NULL will be returned).
The following sequences will be unescaped (only one time): \ \' and "
References IsEscape().
Referenced by ChainGetValue().