VLC: include/vlc_addons.h File Reference
vlc_addons.h File Reference
Data Structures
struct addon_file_t
struct addon_entry_t
struct addons_finder_t
struct addons_storage_t
struct addons_manager_owner
struct addons_manager_t
Macros
#define ADDON_MAX_SCORE (5 * 100)
#define ADDON_UUID_SIZE 16
#define ADDON_UUID_PSZ_SIZE (ADDON_UUID_SIZE * 2 + 4)
Typedefs
typedef enum addon_type_t addon_type_t
typedef enum addon_state_t addon_state_t
typedef enum addon_flags_t addon_flags_t
typedef uint8_t addon_uuid_t[16]
typedef struct addon_file_t addon_file_t
typedef struct addons_finder_t addons_finder_t
typedef struct addons_finder_sys_t addons_finder_sys_t
typedef struct addons_storage_t addons_storage_t
typedef struct addons_storage_sys_t addons_storage_sys_t
typedef struct addons_manager_t addons_manager_t
typedef struct addons_manager_private_t addons_manager_private_t
Enumerations
enum addon_type_t {
ADDON_UNKNOWN = 0 , ADDON_EXTENSION , ADDON_PLAYLIST_PARSER , ADDON_SERVICE_DISCOVERY ,
ADDON_SKIN2 , ADDON_PLUGIN , ADDON_INTERFACE , ADDON_META ,
ADDON_OTHER
}
enum addon_state_t { ADDON_NOTINSTALLED = 0 , ADDON_INSTALLING , ADDON_INSTALLED , ADDON_UNINSTALLING }
enum addon_flags_t { ADDON_BROKEN = 1 , ADDON_MANAGEABLE = 1 << 1 , ADDON_UPDATABLE = 1 << 2 }
Functions
addon_entry_t * addon_entry_New (void)
addon entry lifecycle
addon_entry_t * addon_entry_Hold (addon_entry_t *)
void addon_entry_Release (addon_entry_t *)
addons_manager_t * addons_manager_New (vlc_object_t *, const struct addons_manager_owner *)
addons manager lifecycle
void addons_manager_Delete (addons_manager_t *)
int addons_manager_LoadCatalog (addons_manager_t *)
Charge currently installed, usable and manageable addons (default "addons storage" module)
void addons_manager_Gather (addons_manager_t *, const char *psz_uri)
Gather addons info from repository (default "addons finder" module) If psz_uri is not NULL, only gather info from the pointed package.
int addons_manager_Install (addons_manager_t *p_manager, const addon_uuid_t uuid)
Install or Remove the addon identified by its uuid.
int addons_manager_Remove (addons_manager_t *p_manager, const addon_uuid_t uuid)
static bool addons_uuid_read (const char *psz_uuid, addon_uuid_t *p_uuid)
String uuid to binary uuid helpers.
static char * addons_uuid_to_psz (const addon_uuid_t *p_uuid)
Macro Definition Documentation
ADDON_MAX_SCORE
#define ADDON_MAX_SCORE (5 * 100)
ADDON_UUID_PSZ_SIZE
#define ADDON_UUID_PSZ_SIZE (ADDON_UUID_SIZE * 2 + 4)
Referenced by addons_uuid_read(), and addons_uuid_to_psz().
ADDON_UUID_SIZE
#define ADDON_UUID_SIZE 16
Referenced by addons_uuid_to_psz().
Typedef Documentation
addon_file_t
typedef struct addon_file_t addon_file_t
addon_flags_t
typedef enum addon_flags_t addon_flags_t
addon_state_t
typedef enum addon_state_t addon_state_t
addon_type_t
typedef enum addon_type_t addon_type_t
addon_uuid_t
typedef uint8_t addon_uuid_t[16]
addons_finder_sys_t
typedef struct addons_finder_sys_t addons_finder_sys_t
addons_finder_t
typedef struct addons_finder_t addons_finder_t
addons_manager_private_t
typedef struct addons_manager_private_t addons_manager_private_t
addons_manager_t
typedef struct addons_manager_t addons_manager_t
addons_storage_sys_t
typedef struct addons_storage_sys_t addons_storage_sys_t
addons_storage_t
typedef struct addons_storage_t addons_storage_t
Enumeration Type Documentation
addon_flags_t
enum addon_flags_t
Enumerator
ADDON_BROKEN
ADDON_MANAGEABLE
ADDON_UPDATABLE
addon_state_t
enum addon_state_t
Enumerator
ADDON_NOTINSTALLED
ADDON_INSTALLING
ADDON_INSTALLED
ADDON_UNINSTALLING
addon_type_t
enum addon_type_t
Enumerator
ADDON_UNKNOWN
ADDON_EXTENSION
ADDON_PLAYLIST_PARSER
ADDON_SERVICE_DISCOVERY
ADDON_SKIN2
ADDON_PLUGIN
ADDON_INTERFACE
ADDON_META
ADDON_OTHER
Function Documentation
addon_entry_Hold()
addon_entry_t * addon_entry_Hold (addon_entry_t * p_entry)
References addon_entry_owner::refs.
Referenced by getHeldEntryByUUID(), and InstallerThread().
addon_entry_New()
addon_entry_t * addon_entry_New (void)
addon entry lifecycle
References ARRAY_INIT, addon_entry_owner::entry, addon_entry_t::files, addon_entry_t::lock, addon_entry_owner::refs, unlikely, and vlc_mutex_init().
addon_entry_Release()
void addon_entry_Release (addon_entry_t * p_entry)
References ARRAY_RESET, addon_entry_t::files, FOREACH_ARRAY, FOREACH_END, addon_entry_t::lock, addon_entry_t::p_custom, addon_entry_t::psz_archive_uri, addon_entry_t::psz_author, addon_entry_t::psz_description, addon_file_t::psz_download_uri, addon_file_t::psz_filename, addon_entry_t::psz_image_data, addon_entry_t::psz_image_uri, addon_entry_t::psz_name, addon_entry_t::psz_source_module, addon_entry_t::psz_source_uri, addon_entry_t::psz_summary, addon_entry_t::psz_version, addon_entry_owner::refs, and vlc_mutex_destroy().
Referenced by addons_manager_Install(), InstallerThread(), and MergeSources().
addons_manager_Delete()
void addons_manager_Delete (addons_manager_t * p_manager)
References ARRAY_RESET, addons_manager_private_t::b_live, addons_manager_private_t::finder, FOREACH_ARRAY, FOREACH_END, FREE_QUEUE, addons_manager_private_t::installer, addons_manager_private_t::lock, addons_manager_private_t::p_interrupt, addons_manager_t::p_priv, addons_manager_private_t::thread, addons_manager_private_t::uris, vlc_interrupt_kill(), vlc_join(), vlc_mutex_lock(), and vlc_mutex_unlock().
addons_manager_Gather()
void addons_manager_Gather (addons_manager_t * p_manager, const char * psz_uri)
Gather addons info from repository (default "addons finder" module) If psz_uri is not NULL, only gather info from the pointed package.
References ARRAY_APPEND, addons_manager_private_t::b_live, addons_manager_private_t::finder, FinderThread(), addons_manager_private_t::lock, msg_Err, addons_manager_private_t::p_parent, addons_manager_t::p_priv, strdup(), addons_manager_private_t::thread, addons_manager_private_t::uris, vlc_clone(), vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_THREAD_PRIORITY_LOW, and addons_manager_private_t::waitcond.
addons_manager_Install()
int addons_manager_Install (addons_manager_t * p_manager, const addon_uuid_t uuid)
Install or Remove the addon identified by its uuid.
< Unspecified error
References addon_entry_Release(), getHeldEntryByUUID(), InstallEntry(), and VLC_EGENERIC.
Referenced by addons_manager_Remove().
addons_manager_LoadCatalog()
int addons_manager_LoadCatalog (addons_manager_t * p_manager)
Charge currently installed, usable and manageable addons (default "addons storage" module)
< No error
References LoadLocalStorage(), and VLC_SUCCESS.
addons_manager_New()
addons_manager_t * addons_manager_New (vlc_object_t * , const struct addons_manager_owner *)
addons manager lifecycle
addons_manager_Remove()
int addons_manager_Remove (addons_manager_t * p_manager, const addon_uuid_t uuid)
References addons_manager_Install().
addons_uuid_read()
static bool addons_uuid_read (const char * psz_uuid, addon_uuid_t * p_uuid) inline static
String uuid to binary uuid helpers.
References ADDON_UUID_PSZ_SIZE.
addons_uuid_to_psz()
static char * addons_uuid_to_psz (const addon_uuid_t * p_uuid) inline static
References ADDON_UUID_PSZ_SIZE, ADDON_UUID_SIZE, and p.