VLC: include/vlc_mouse.h File Reference
vlc_mouse.h File Reference
Data Structures
struct vlc_mouse_t
Mouse state.
Typedefs
typedef struct vlc_mouse_t vlc_mouse_t
Mouse state.
Enumerations
enum {
MOUSE_BUTTON_LEFT =0 , MOUSE_BUTTON_CENTER , MOUSE_BUTTON_RIGHT , MOUSE_BUTTON_WHEEL_UP ,
MOUSE_BUTTON_WHEEL_DOWN , MOUSE_BUTTON_WHEEL_LEFT , MOUSE_BUTTON_WHEEL_RIGHT , MOUSE_BUTTON_MAX
}
Mouse buttons.
Functions
static void vlc_mouse_Init (vlc_mouse_t *p_mouse)
static void vlc_mouse_SetPressed (vlc_mouse_t *p_mouse, int i_button)
static void vlc_mouse_SetReleased (vlc_mouse_t *p_mouse, int i_button)
static void vlc_mouse_SetPosition (vlc_mouse_t *p_mouse, int i_x, int i_y)
static bool vlc_mouse_IsPressed (const vlc_mouse_t *p_mouse, int i_button)
static bool vlc_mouse_IsLeftPressed (const vlc_mouse_t *p_mouse)
static bool vlc_mouse_IsCenterPressed (const vlc_mouse_t *p_mouse)
static bool vlc_mouse_IsRightPressed (const vlc_mouse_t *p_mouse)
static bool vlc_mouse_IsWheelUpPressed (const vlc_mouse_t *p_mouse)
static bool vlc_mouse_IsWheelDownPressed (const vlc_mouse_t *p_mouse)
static void vlc_mouse_GetMotion (int *pi_x, int *pi_y, const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
static bool vlc_mouse_HasChanged (const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
static bool vlc_mouse_HasMoved (const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
static bool vlc_mouse_HasButton (const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
static bool vlc_mouse_HasPressed (const vlc_mouse_t *p_old, const vlc_mouse_t *p_new, int i_button)
static bool vlc_mouse_HasReleased (const vlc_mouse_t *p_old, const vlc_mouse_t *p_new, int i_button)
Typedef Documentation
vlc_mouse_t
typedef struct vlc_mouse_t vlc_mouse_t
Mouse state.
Enumeration Type Documentation
anonymous enum
anonymous enum
Mouse buttons.
Enumerator
MOUSE_BUTTON_LEFT
MOUSE_BUTTON_CENTER
MOUSE_BUTTON_RIGHT
MOUSE_BUTTON_WHEEL_UP
MOUSE_BUTTON_WHEEL_DOWN
MOUSE_BUTTON_WHEEL_LEFT
MOUSE_BUTTON_WHEEL_RIGHT
MOUSE_BUTTON_MAX
Function Documentation
vlc_mouse_GetMotion()
static void vlc_mouse_GetMotion (int * pi_x, int * pi_y, const vlc_mouse_t * p_old, const vlc_mouse_t * p_new) inline static
References vlc_mouse_t::i_x, and vlc_mouse_t::i_y.
vlc_mouse_HasButton()
static bool vlc_mouse_HasButton (const vlc_mouse_t * p_old, const vlc_mouse_t * p_new) inline static
References vlc_mouse_t::i_pressed.
Referenced by vout_SendDisplayEventMouse().
vlc_mouse_HasChanged()
static bool vlc_mouse_HasChanged (const vlc_mouse_t * p_old, const vlc_mouse_t * p_new) inline static
References vlc_mouse_t::i_pressed, vlc_mouse_t::i_x, and vlc_mouse_t::i_y.
vlc_mouse_HasMoved()
static bool vlc_mouse_HasMoved (const vlc_mouse_t * p_old, const vlc_mouse_t * p_new) inline static
References vlc_mouse_t::i_x, and vlc_mouse_t::i_y.
Referenced by vout_SendDisplayEventMouse().
vlc_mouse_HasPressed()
static bool vlc_mouse_HasPressed (const vlc_mouse_t * p_old, const vlc_mouse_t * p_new, int i_button) inline static
References vlc_mouse_t::i_pressed.
Referenced by vout_SendDisplayEventMouse(), and VoutDisplayEventMouse().
vlc_mouse_HasReleased()
static bool vlc_mouse_HasReleased (const vlc_mouse_t * p_old, const vlc_mouse_t * p_new, int i_button) inline static
References vlc_mouse_t::i_pressed.
Referenced by vout_SendDisplayEventMouse().
vlc_mouse_Init()
static void vlc_mouse_Init (vlc_mouse_t * p_mouse) inline static
References vlc_mouse_t::b_double_click, vlc_mouse_t::i_pressed, vlc_mouse_t::i_x, and vlc_mouse_t::i_y.
Referenced by DisplayNew(), filter_chain_AppendInner(), ThreadStart(), and VoutDisplayEventMouse().
vlc_mouse_IsCenterPressed()
static bool vlc_mouse_IsCenterPressed (const vlc_mouse_t * p_mouse) inline static
References MOUSE_BUTTON_CENTER, and vlc_mouse_IsPressed().
vlc_mouse_IsLeftPressed()
static bool vlc_mouse_IsLeftPressed (const vlc_mouse_t * p_mouse) inline static
References MOUSE_BUTTON_LEFT, and vlc_mouse_IsPressed().
vlc_mouse_IsPressed()
static bool vlc_mouse_IsPressed (const vlc_mouse_t * p_mouse, int i_button) inline static
References vlc_mouse_t::i_pressed.
Referenced by vlc_mouse_IsCenterPressed(), vlc_mouse_IsLeftPressed(), vlc_mouse_IsRightPressed(), vlc_mouse_IsWheelDownPressed(), and vlc_mouse_IsWheelUpPressed().
vlc_mouse_IsRightPressed()
static bool vlc_mouse_IsRightPressed (const vlc_mouse_t * p_mouse) inline static
References MOUSE_BUTTON_RIGHT, and vlc_mouse_IsPressed().
vlc_mouse_IsWheelDownPressed()
static bool vlc_mouse_IsWheelDownPressed (const vlc_mouse_t * p_mouse) inline static
References MOUSE_BUTTON_WHEEL_DOWN, and vlc_mouse_IsPressed().
vlc_mouse_IsWheelUpPressed()
static bool vlc_mouse_IsWheelUpPressed (const vlc_mouse_t * p_mouse) inline static
References MOUSE_BUTTON_WHEEL_UP, and vlc_mouse_IsPressed().
vlc_mouse_SetPosition()
static void vlc_mouse_SetPosition (vlc_mouse_t * p_mouse, int i_x, int i_y) inline static
References vlc_mouse_t::i_x, and vlc_mouse_t::i_y.
vlc_mouse_SetPressed()
static void vlc_mouse_SetPressed (vlc_mouse_t * p_mouse, int i_button) inline static
References vlc_mouse_t::i_pressed.
vlc_mouse_SetReleased()
static void vlc_mouse_SetReleased (vlc_mouse_t * p_mouse, int i_button) inline static
References vlc_mouse_t::i_pressed.