VLC: include/vlc_vout_wrapper.h File Reference
vlc_vout_wrapper.h File Reference
Data Structures
struct vout_display_state_t
It holds a state for a vout display.
Functions
static picture_pool_t * vout_display_Pool (vout_display_t *vd, unsigned count)
It retreives a picture pool from the display.
static void vout_display_Prepare (vout_display_t *vd, picture_t *picture, subpicture_t *subpicture)
It preparse a picture for display.
static void vout_display_Display (vout_display_t *vd, picture_t *picture, subpicture_t *subpicture)
It display a picture.
vout_display_t * vout_NewDisplay (vout_thread_t *, const video_format_t *, const vout_display_state_t *, const char *module, mtime_t double_click_timeout, mtime_t hide_timeout)
It creates a vout managed display.
void vout_DeleteDisplay (vout_display_t *, vout_display_state_t *)
It destroy a vout managed display.
bool vout_IsDisplayFiltered (vout_display_t *)
picture_t * vout_FilterDisplay (vout_display_t *, picture_t *)
void vout_FilterFlush (vout_display_t *)
bool vout_AreDisplayPicturesInvalid (vout_display_t *)
bool vout_ManageDisplay (vout_display_t *, bool allow_reset_pictures)
void vout_SetDisplayFilled (vout_display_t *, bool is_filled)
void vout_SetDisplayZoom (vout_display_t *, unsigned num, unsigned den)
void vout_SetDisplayAspect (vout_display_t *, unsigned num, unsigned den)
void vout_SetDisplayCrop (vout_display_t *, unsigned num, unsigned den, unsigned left, unsigned top, int right, int bottom)
void vout_SetDisplayViewpoint (vout_display_t *, const vlc_viewpoint_t *)
Function Documentation
vout_AreDisplayPicturesInvalid()
bool vout_AreDisplayPicturesInvalid (vout_display_t * vd)
References vout_display_owner_sys_t::lock, vout_display_t::owner, vout_display_owner_sys_t::reset_pictures, vout_display_owner_t::sys, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by vout_ManageWrapper().
vout_DeleteDisplay()
void vout_DeleteDisplay (vout_display_t * vd, vout_display_state_t * state)
It destroy a vout managed display.
References vout_display_owner_sys_t::cfg, vout_display_state_t::cfg, vout_display_owner_sys_t::is_splitter, vout_display_owner_sys_t::lock, vout_display_t::owner, vout_display_state_t::sar, vout_display_owner_sys_t::sar_initial, SplitterClose(), vout_display_owner_t::sys, vlc_mutex_destroy(), vout_display_Delete(), and VoutDisplayDestroyRender().
Referenced by SplitterClose(), vout_CloseWrapper(), and vout_NewSplitter().
vout_display_Display()
static void vout_display_Display (vout_display_t * vd, picture_t * picture, subpicture_t * subpicture) inline static
It display a picture.
References vout_display_t::display.
Referenced by SplitterDisplay(), and ThreadDisplayRenderPicture().
vout_display_Pool()
static picture_pool_t * vout_display_Pool (vout_display_t * vd, unsigned count) inline static
It retreives a picture pool from the display.
References count, and vout_display_t::pool.
Referenced by NoDrInit(), SplitterPictureNew(), VideoBufferNew(), and vout_InitWrapper().
vout_display_Prepare()
static void vout_display_Prepare (vout_display_t * vd, picture_t * picture, subpicture_t * subpicture) inline static
It preparse a picture for display.
References vout_display_t::prepare.
Referenced by SplitterPrepare(), and ThreadDisplayRenderPicture().
vout_FilterDisplay()
picture_t * vout_FilterDisplay (vout_display_t * vd, picture_t * picture)
References filter_chain_VideoFilter(), vout_display_owner_sys_t::filters, vout_display_t::owner, picture_Release(), and vout_display_owner_t::sys.
Referenced by SplitterPrepare(), and ThreadDisplayRenderPicture().
vout_FilterFlush()
void vout_FilterFlush (vout_display_t * vd)
References filter_chain_VideoFlush(), vout_display_owner_sys_t::filters, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by ThreadFlush().
vout_IsDisplayFiltered()
bool vout_IsDisplayFiltered (vout_display_t * vd)
References filter_chain_IsEmpty(), vout_display_owner_sys_t::filters, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by SplitterPictureNew(), ThreadDisplayRenderPicture(), vout_InitWrapper(), and vout_ManageWrapper().
vout_ManageDisplay()
bool vout_ManageDisplay (vout_display_t * vd, bool allow_reset_pictures)
< No error
References vout_display_owner_sys_t::bottom, vout_display_owner_sys_t::cfg, vout_display_owner_sys_t::ch_activity, vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::ch_display_size, vout_display_owner_sys_t::ch_sar, vout_display_owner_sys_t::ch_viewpoint, vout_display_owner_sys_t::ch_zoom, vout_display_owner_sys_t::crop, vlc_rational_t::den, vout_display_cfg_t::den, vout_display_owner_sys_t::den, vout_display_cfg_t::display, vout_display_owner_sys_t::display_height, vout_display_owner_sys_t::display_width, vout_display_owner_sys_t::fit_window, vout_display_cfg_t::height, vout_display_owner_sys_t::hide_timeout, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, video_format_t::i_y_offset, vout_display_t::info, vout_display_cfg_t::is_display_filled, vout_display_owner_sys_t::is_display_filled, vout_display_owner_sys_t::is_hidden, vout_display_owner_sys_t::last_moved, vout_display_owner_sys_t::left, vout_display_owner_sys_t::lock, mdate(), vout_display_owner_sys_t::mouse, msg_Dbg, msg_Err, vout_display_info_t::needs_hide_mouse, vlc_rational_t::num, vout_display_cfg_t::num, vout_display_owner_sys_t::num, vout_display_t::owner, vout_display_owner_sys_t::reset_pictures, vout_display_owner_sys_t::right, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_t::source, vout_display_owner_t::sys, vout_display_owner_sys_t::top, video_format_Print(), vout_display_cfg_t::viewpoint, vout_display_owner_sys_t::viewpoint, VLC_CLIP, vlc_mutex_lock(), vlc_mutex_unlock(), VLC_OBJECT, VLC_SUCCESS, vout_display_owner_sys_t::vout, VOUT_DISPLAY_CHANGE_DISPLAY_FILLED, VOUT_DISPLAY_CHANGE_DISPLAY_SIZE, VOUT_DISPLAY_CHANGE_SOURCE_ASPECT, VOUT_DISPLAY_CHANGE_SOURCE_CROP, VOUT_DISPLAY_CHANGE_VIEWPOINT, VOUT_DISPLAY_CHANGE_ZOOM, vout_display_Control(), VOUT_DISPLAY_HIDE_MOUSE, vout_display_Manage(), VOUT_DISPLAY_RESET_PICTURES, vout_HideWindowMouse(), vout_SetDisplayWindowSize(), VoutDisplayCropRatio(), VoutDisplayFitWindow(), VoutDisplayResetRender(), vout_display_cfg_t::width, vout_display_cfg_t::zoom, and vout_display_owner_sys_t::zoom.
Referenced by SplitterManage(), and vout_ManageWrapper().
vout_NewDisplay()
vout_display_t * vout_NewDisplay (vout_thread_t * vout, const video_format_t * source, const vout_display_state_t * state, const char * module, mtime_t double_click_timeout, mtime_t hide_timeout)
It creates a vout managed display.
References DisplayNew().
Referenced by vout_OpenWrapper().
vout_SetDisplayAspect()
void vout_SetDisplayAspect (vout_display_t * vd, unsigned num, unsigned den)
References vout_display_owner_sys_t::ch_sar, vlc_rational_t::den, video_format_t::i_visible_height, video_format_t::i_visible_width, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_sys_t::sar, vout_display_owner_sys_t::source, vout_display_owner_t::sys, and vlc_ureduce().
Referenced by ThreadChangeAspectRatio().
vout_SetDisplayCrop()
void vout_SetDisplayCrop (vout_display_t * vd, unsigned num, unsigned den, unsigned left, unsigned top, int right, int bottom)
References vout_display_owner_sys_t::bottom, vout_display_owner_sys_t::ch_crop, vout_display_owner_sys_t::crop, vout_display_owner_sys_t::den, vout_display_owner_sys_t::left, vout_display_owner_sys_t::num, vout_display_t::owner, vout_display_owner_sys_t::right, vout_display_owner_t::sys, and vout_display_owner_sys_t::top.
Referenced by ThreadExecuteCropBorder(), ThreadExecuteCropRatio(), and ThreadExecuteCropWindow().
vout_SetDisplayFilled()
void vout_SetDisplayFilled (vout_display_t * vd, bool is_filled)
References vout_display_owner_sys_t::is_display_filled, vout_display_t::owner, and vout_display_owner_t::sys.
Referenced by ThreadChangeDisplayFilled().
vout_SetDisplayViewpoint()
void vout_SetDisplayViewpoint (vout_display_t * vd, const vlc_viewpoint_t * p_viewpoint)
References vout_display_owner_sys_t::ch_viewpoint, vlc_viewpoint_t::fov, vout_display_t::owner, vlc_viewpoint_t::pitch, vlc_viewpoint_t::roll, vout_display_owner_t::sys, vout_display_owner_sys_t::viewpoint, and vlc_viewpoint_t::yaw.
Referenced by ThreadExecuteViewpoint().
vout_SetDisplayZoom()
void vout_SetDisplayZoom (vout_display_t * vd, unsigned num, unsigned den)
References vout_display_owner_sys_t::ch_zoom, vlc_rational_t::den, vout_display_owner_sys_t::is_display_filled, vlc_rational_t::num, vout_display_t::owner, vout_display_owner_t::sys, vlc_ureduce(), and vout_display_owner_sys_t::zoom.
Referenced by ThreadChangeZoom().