VLC: include/vlc_memstream.h File Reference
vlc_memstream.h File Reference
Data Structures
struct vlc_memstream
Functions
int vlc_memstream_open (struct vlc_memstream *ms)
int vlc_memstream_flush (struct vlc_memstream *ms)
int vlc_memstream_close (struct vlc_memstream *ms)
size_t vlc_memstream_write (struct vlc_memstream *ms, const void *ptr, size_t len)
int vlc_memstream_putc (struct vlc_memstream *ms, int c)
int vlc_memstream_puts (struct vlc_memstream *ms, const char *str)
int vlc_memstream_vprintf (struct vlc_memstream *ms, const char *fmt, va_list args)
int vlc_memstream_printf (struct vlc_memstream *s, const char *fmt,...)
Function Documentation
vlc_memstream_close()
int vlc_memstream_close (struct vlc_memstream * ms)
References vlc_memstream::error, and vlc_memstream::ptr.
Referenced by Downloader(), mrl_EscapeFragmentIdentifier(), sout_AnnounceRegisterSDP(), StreamExtractorCreateMRL(), UpdateBookmarksOption(), vlc_CPU_dump(), vlc_http_msg_format(), vlc_sdp_Start(), vlc_strfinput(), vlc_uri_compose(), vlc_uri_fixup_inner(), and vlc_xml_encode().
vlc_memstream_flush()
int vlc_memstream_flush (struct vlc_memstream * ms)
References vlc_memstream::error.
vlc_memstream_open()
int vlc_memstream_open (struct vlc_memstream * ms)
References vlc_memstream::error, vlc_memstream::length, vlc_memstream::ptr, and unlikely.
Referenced by Downloader(), mrl_EscapeFragmentIdentifier(), sout_AnnounceRegisterSDP(), StreamExtractorCreateMRL(), UpdateBookmarksOption(), vlc_CPU_dump(), vlc_http_msg_format(), vlc_sdp_Start(), vlc_strfinput(), vlc_uri_compose(), vlc_uri_fixup_inner(), and vlc_xml_encode().
vlc_memstream_printf()
int vlc_memstream_printf (struct vlc_memstream * s, const char * fmt, ...)
References vlc_memstream_vprintf().
Referenced by mrl_EscapeFragmentIdentifier(), sdp_AddMedia(), StreamExtractorCreateMRL(), UpdateBookmarksOption(), vlc_http_msg_format(), vlc_sdp_Start(), vlc_strfinput(), vlc_uri_compose(), vlc_uri_fixup_inner(), vlc_xml_encode(), vsdp_AddAttribute(), and write_duration().
vlc_memstream_putc()
int vlc_memstream_putc (struct vlc_memstream * ms, int c)
References vlc_memstream_write().
Referenced by sout_AnnounceRegisterSDP(), StreamExtractorCreateMRL(), vlc_strfinput(), vlc_uri_compose(), and vlc_uri_fixup_inner().
vlc_memstream_puts()
int vlc_memstream_puts (struct vlc_memstream * ms, const char * str)
References vlc_memstream_write().
Referenced by sdp_AddMedia(), sout_AnnounceRegisterSDP(), StreamExtractorCreateMRL(), UpdateBookmarksOption(), vlc_CPU_dump(), vlc_http_msg_format(), vlc_sdp_Start(), vlc_strfinput(), vlc_uri_compose(), vlc_xml_encode(), vsdp_AddAttribute(), and write_meta().
vlc_memstream_vprintf()
int vlc_memstream_vprintf (struct vlc_memstream * ms, const char * fmt, va_list args)
References vlc_memstream::error, vlc_memstream::length, and vlc_memstream::ptr.
Referenced by vlc_memstream_printf(), and vsdp_AddAttribute().
vlc_memstream_write()
size_t vlc_memstream_write (struct vlc_memstream * ms, const void * ptr, size_t len)
References vlc_memstream::error, vlc_memstream::length, vlc_memstream::ptr, and unlikely.
Referenced by Downloader(), sout_AnnounceRegisterSDP(), vlc_memstream_putc(), vlc_memstream_puts(), vlc_uri_compose(), and vlc_xml_encode().