VLC: include/vlc_opengl.h File Reference
vlc_opengl.h File Reference
This file defines GL structures and functions.
Data Structures
struct vlc_gl_t
Typedefs
typedef struct vlc_gl_t vlc_gl_t
A VLC GL context (and its underlying surface)
Enumerations
enum { VLC_OPENGL , VLC_OPENGL_ES2 }
Functions
vlc_gl_t * vlc_gl_Create (struct vout_window_t *, unsigned, const char *)
Creates an OpenGL context (and its underlying surface).
void vlc_gl_Release (vlc_gl_t *)
void vlc_gl_Hold (vlc_gl_t *)
static int vlc_gl_MakeCurrent (vlc_gl_t *gl)
static void vlc_gl_ReleaseCurrent (vlc_gl_t *gl)
static void vlc_gl_Resize (vlc_gl_t *gl, unsigned w, unsigned h)
static void vlc_gl_Swap (vlc_gl_t *gl)
static void * vlc_gl_GetProcAddress (vlc_gl_t *gl, const char *name)
vlc_gl_t * vlc_gl_surface_Create (vlc_object_t *, const struct vout_window_cfg_t *, struct vout_window_t **)
bool vlc_gl_surface_CheckSize (vlc_gl_t *, unsigned *w, unsigned *h)
void vlc_gl_surface_Destroy (vlc_gl_t *)
Detailed Description
This file defines GL structures and functions.
Typedef Documentation
vlc_gl_t
typedef struct vlc_gl_t vlc_gl_t
A VLC GL context (and its underlying surface)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VLC_OPENGL
VLC_OPENGL_ES2
Function Documentation
vlc_gl_Create()
vlc_gl_t * vlc_gl_Create (struct vout_window_t * wnd, unsigned flags, const char * name)
Creates an OpenGL context (and its underlying surface).
Note
In most cases, you should vlc_gl_MakeCurrent() afterward.
Parameters
wnd window to use as OpenGL surface
flags OpenGL context type
name module name (or NULL for auto)
Returns
a new context, or NULL on failure
References vlc_gl_priv_t::gl, vlc_gl_t::module, module_need, name, vlc_gl_priv_t::ref_count, vlc_gl_t::surface, unlikely, vlc_custom_create, vlc_object_release, VLC_OPENGL, and VLC_OPENGL_ES2.
Referenced by vlc_gl_surface_Create().
vlc_gl_GetProcAddress()
static void * vlc_gl_GetProcAddress (vlc_gl_t * gl, const char * name) inline static
References vlc_gl_t::getProcAddress, and name.
vlc_gl_Hold()
void vlc_gl_Hold (vlc_gl_t * gl)
References vlc_gl_priv_t::gl, and vlc_gl_priv_t::ref_count.
vlc_gl_MakeCurrent()
static int vlc_gl_MakeCurrent (vlc_gl_t * gl) inline static
References vlc_gl_t::makeCurrent.
vlc_gl_Release()
void vlc_gl_Release (vlc_gl_t * gl)
References vlc_gl_priv_t::gl, vlc_gl_t::module, module_unneed, vlc_gl_priv_t::ref_count, and vlc_object_release.
Referenced by vlc_gl_surface_Destroy().
vlc_gl_ReleaseCurrent()
static void vlc_gl_ReleaseCurrent (vlc_gl_t * gl) inline static
References vlc_gl_t::releaseCurrent.
vlc_gl_Resize()
static void vlc_gl_Resize (vlc_gl_t * gl, unsigned w, unsigned h) inline static
References vlc_gl_t::resize.
Referenced by vlc_gl_surface_CheckSize(), and vlc_gl_surface_Create().
vlc_gl_surface_CheckSize()
bool vlc_gl_surface_CheckSize (vlc_gl_t * , unsigned * w, unsigned * h)
vlc_gl_surface_Create()
vlc_gl_t * vlc_gl_surface_Create (vlc_object_t * , const struct vout_window_cfg_t * , struct vout_window_t **)
vlc_gl_surface_Destroy()
void vlc_gl_surface_Destroy (vlc_gl_t * gl)
References vlc_gl_surface::lock, vout_window_t::owner, vlc_gl_t::surface, vout_window_owner::sys, vlc_gl_Release(), vlc_mutex_destroy(), and vout_window_Delete().
vlc_gl_Swap()
static void vlc_gl_Swap (vlc_gl_t * gl) inline static
References vlc_gl_t::swap.