VLC: include/vlc_image.h File Reference
vlc_image.h File Reference
This file defines functions and structures for image conversions in vlc.
Data Structures
struct image_handler_t
Macros
#define image_HandlerCreate(a) image_HandlerCreate(VLC_OBJECT(a))
#define image_Read(a, b, c, d) a->pf_read(a, b, c, d)
#define image_ReadUrl(a, b, c, d) a->pf_read_url(a, b, c, d)
#define image_Write(a, b, c, d) a->pf_write(a, b, c, d)
#define image_WriteUrl(a, b, c, d, e) a->pf_write_url(a, b, c, d, e)
#define image_Convert(a, b, c, d) a->pf_convert(a, b, c, d)
Functions
image_handler_t * image_HandlerCreate (vlc_object_t *)
Create an image_handler_t instance.
void image_HandlerDelete (image_handler_t *)
Delete the image_handler_t instance.
vlc_fourcc_t image_Type2Fourcc (const char *psz_name)
vlc_fourcc_t image_Ext2Fourcc (const char *psz_name)
vlc_fourcc_t image_Mime2Fourcc (const char *psz_mime)
Detailed Description
This file defines functions and structures for image conversions in vlc.
Macro Definition Documentation
image_Convert
#define image_Convert (a, b, c, d) a->pf_convert(a, b, c, d)
Referenced by subpicture_NewFromPicture().
image_HandlerCreate
#define image_HandlerCreate (a) image_HandlerCreate(VLC_OBJECT(a))
Referenced by picture_Export(), spuregion_CreateFromPicture(), and subpicture_NewFromPicture().
image_Read
#define image_Read (a, b, c, d) a->pf_read(a, b, c, d)
image_ReadUrl
#define image_ReadUrl (a, b, c, d) a->pf_read_url(a, b, c, d)
Referenced by spuregion_CreateFromPicture().
image_Write
#define image_Write (a, b, c, d) a->pf_write(a, b, c, d)
Referenced by picture_Export().
image_WriteUrl
#define image_WriteUrl (a, b, c, d, e) a->pf_write_url(a, b, c, d, e)
Function Documentation
image_Ext2Fourcc()
vlc_fourcc_t image_Ext2Fourcc (const char * psz_name)
References image_Type2Fourcc(), and psz_name.
Referenced by ImageReadUrl(), and ImageWriteUrl().
image_HandlerCreate()
image_handler_t * image_HandlerCreate (vlc_object_t * p_this)
Create an image_handler_t instance.
References ImageConvert(), ImageRead(), ImageReadUrl(), ImageWrite(), ImageWriteUrl(), image_handler_t::outfifo, image_handler_t::p_parent, image_handler_t::pf_convert, image_handler_t::pf_read, image_handler_t::pf_read_url, image_handler_t::pf_write, image_handler_t::pf_write_url, and picture_fifo_New().
image_HandlerDelete()
void image_HandlerDelete (image_handler_t * p_image)
Delete the image_handler_t instance.
References DeleteDecoder(), DeleteEncoder(), DeleteFilter(), image_handler_t::outfifo, image_handler_t::p_dec, image_handler_t::p_enc, image_handler_t::p_filter, and picture_fifo_Delete().
Referenced by picture_Export(), spuregion_CreateFromPicture(), and subpicture_NewFromPicture().
image_Mime2Fourcc()
vlc_fourcc_t image_Mime2Fourcc (const char * psz_mime)
References mime_table, and psz_mime.
Referenced by ImageReadUrl().
image_Type2Fourcc()
vlc_fourcc_t image_Type2Fourcc (const char * psz_name)
References ARRAY_SIZE, ext_table, i_codec, psz_ext, and strcasecmp().
Referenced by image_Ext2Fourcc(), and vout_GetSnapshot().