VLC: include/vlc_video_splitter.h File Reference
vlc_video_splitter.h File Reference
This file defines the structure and types used by video splitter filters.
Data Structures
struct video_splitter_output_t
Structure describing a video splitter output properties.
struct video_splitter_t
Structure describing a video splitter.
Typedefs
typedef struct video_splitter_t video_splitter_t
typedef struct video_splitter_sys_t video_splitter_sys_t
typedef struct video_splitter_owner_t video_splitter_owner_t
Functions
static int video_splitter_NewPicture (video_splitter_t *p_splitter, picture_t *pp_picture[])
It will create an array of pictures suitable as output.
static void video_splitter_DeletePicture (video_splitter_t *p_splitter, picture_t *pp_picture[])
It will release an array of pictures created by video_splitter_NewPicture.
video_splitter_t * video_splitter_New (vlc_object_t *, const char *psz_name, const video_format_t *)
void video_splitter_Delete (video_splitter_t *)
static int video_splitter_Filter (video_splitter_t *p_splitter, picture_t *pp_dst[], picture_t *p_src)
static int video_splitter_Mouse (video_splitter_t *p_splitter, vlc_mouse_t *p_mouse, int i_index, const vlc_mouse_t *p_old, const vlc_mouse_t *p_new)
Detailed Description
This file defines the structure and types used by video splitter filters.
Typedef Documentation
video_splitter_owner_t
typedef struct video_splitter_owner_t video_splitter_owner_t
video_splitter_sys_t
typedef struct video_splitter_sys_t video_splitter_sys_t
video_splitter_t
typedef struct video_splitter_t video_splitter_t
Function Documentation
video_splitter_Delete()
void video_splitter_Delete (video_splitter_t * p_splitter)
References video_splitter_t::fmt, module_unneed, video_splitter_t::p_module, video_format_Clean(), and vlc_object_release.
Referenced by SplitterClose(), video_splitter_New(), and vout_NewSplitter().
video_splitter_DeletePicture()
static void video_splitter_DeletePicture (video_splitter_t * p_splitter, picture_t * pp_picture[]) inline static
It will release an array of pictures created by video_splitter_NewPicture.
Provided for convenience.
References video_splitter_t::pf_picture_del.
video_splitter_Filter()
static int video_splitter_Filter (video_splitter_t * p_splitter, picture_t * pp_dst[], picture_t * p_src) inline static
References video_splitter_t::pf_filter.
Referenced by SplitterPrepare().
video_splitter_Mouse()
static int video_splitter_Mouse (video_splitter_t * p_splitter, vlc_mouse_t * p_mouse, int i_index, const vlc_mouse_t * p_old, const vlc_mouse_t * p_new) inline static
< No error
References video_splitter_t::pf_mouse, and VLC_SUCCESS.
video_splitter_New()
video_splitter_t * video_splitter_New (vlc_object_t * p_this, const char * psz_name, const video_format_t * p_fmt)
References video_splitter_t::fmt, module_need, video_splitter_t::p_module, psz_name, video_format_Copy(), video_splitter_Delete(), and vlc_custom_create.
Referenced by vout_NewSplitter().
video_splitter_NewPicture()
static int video_splitter_NewPicture (video_splitter_t * p_splitter, picture_t * pp_picture[]) inline static
It will create an array of pictures suitable as output.
You must either returned them through pf_filter or by calling video_splitter_DeletePicture.
If VLC_SUCCESS is not returned, pp_picture values are undefined.
References msg_Warn, and video_splitter_t::pf_picture_new.