VLC: include/vlc_epg.h File Reference
vlc_epg.h File Reference
This file defines functions and structures for storing dvb epg information.
Data Structures
struct vlc_epg_event_t
struct vlc_epg_t
Functions
vlc_epg_event_t * vlc_epg_event_New (uint16_t i_id, int64_t i_start, uint32_t i_duration)
Creates a new vlc_epg_event_t*.
void vlc_epg_event_Delete (vlc_epg_event_t *p_event)
Releases a vlc_epg_event_t*.
vlc_epg_event_t * vlc_epg_event_Duplicate (const vlc_epg_event_t *p_src)
Returns a vlc_epg_event_t * duplicated from p_src.
vlc_epg_t * vlc_epg_New (uint32_t i_id, uint16_t i_source_id)
It creates a new vlc_epg_t*.
void vlc_epg_Delete (vlc_epg_t *p_epg)
It releases a vlc_epg_t*.
bool vlc_epg_AddEvent (vlc_epg_t *p_epg, vlc_epg_event_t *p_evt)
It appends a new vlc_epg_event_t to a vlc_epg_t.
void vlc_epg_SetCurrent (vlc_epg_t *p_epg, int64_t i_start)
It set the current event of a vlc_epg_t given a start time.
vlc_epg_t * vlc_epg_Duplicate (const vlc_epg_t *p_src)
Returns a duplicated p_src and its associated events.
Detailed Description
This file defines functions and structures for storing dvb epg information.
Function Documentation
vlc_epg_AddEvent()
bool vlc_epg_AddEvent (vlc_epg_t * p_epg, vlc_epg_event_t * p_evt)
It appends a new vlc_epg_event_t to a vlc_epg_t.
Takes ownership of p_evt or returns false
p_evt a vlc_epg_event_t * created with vlc_epg_event_New.
References vlc_epg_t::i_event, vlc_epg_event_t::i_start, vlc_epg_t::p_current, vlc_epg_t::pp_event, TAB_APPEND, TAB_INSERT, and vlc_epg_event_Delete().
Referenced by vout_OSDEpg().
vlc_epg_Delete()
void vlc_epg_Delete (vlc_epg_t * p_epg)
It releases a vlc_epg_t*.
References vlc_epg_Clean().
Referenced by CmdCleanControl(), input_item_Release(), input_item_SetEpg(), OSDEpgDestroy(), and vout_OSDEpg().
vlc_epg_Duplicate()
vlc_epg_t * vlc_epg_Duplicate (const vlc_epg_t * p_src)
Returns a duplicated p_src and its associated events.
References vlc_epg_t::b_present, vlc_epg_t::i_event, vlc_epg_t::i_id, vlc_epg_t::i_source_id, vlc_epg_t::p_current, vlc_epg_t::pp_event, vlc_epg_t::psz_name, strdup(), TAB_APPEND, vlc_epg_event_Duplicate(), and vlc_epg_New().
Referenced by CmdInitControl(), and input_item_SetEpg().
vlc_epg_event_Delete()
void vlc_epg_event_Delete (vlc_epg_event_t * p_event)
Releases a vlc_epg_event_t*.
References vlc_epg_event_Clean().
Referenced by CmdCleanControl(), input_item_SetEpgEvent(), vlc_epg_AddEvent(), vlc_epg_Clean(), and vout_OSDEpg().
vlc_epg_event_Duplicate()
vlc_epg_event_t * vlc_epg_event_Duplicate (const vlc_epg_event_t * p_src)
Returns a vlc_epg_event_t * duplicated from p_src.
References vlc_epg_event_t::description_items, vlc_epg_event_t::i_description_items, vlc_epg_event_t::i_duration, vlc_epg_event_t::i_id, vlc_epg_event_t::i_rating, vlc_epg_event_t::i_start, likely, vlc_epg_event_t::psz_description, vlc_epg_event_t::psz_key, vlc_epg_event_t::psz_name, vlc_epg_event_t::psz_short_description, vlc_epg_event_t::psz_value, strdup(), and vlc_epg_event_New().
Referenced by CmdInitControl(), input_item_SetEpgEvent(), vlc_epg_Duplicate(), and vout_OSDEpg().
vlc_epg_event_New()
vlc_epg_event_t * vlc_epg_event_New (uint16_t i_id, int64_t i_start, uint32_t i_duration)
Creates a new vlc_epg_event_t*.
You must call vlc_epg_event_Delete to release the associated resources.
i_id is the event unique id i_start start in epoch time i_duration event duration in seconds
References vlc_epg_event_Init().
Referenced by vlc_epg_event_Duplicate().
vlc_epg_New()
vlc_epg_t * vlc_epg_New (uint32_t i_id, uint16_t i_source_id)
It creates a new vlc_epg_t*.
You must call vlc_epg_Delete to release the associated resource.
i_id is computed unique id depending on standard (table id, eit number) i_source_id is the associated program number
References vlc_epg_Init().
Referenced by vlc_epg_Duplicate(), and vout_OSDEpg().
vlc_epg_SetCurrent()
void vlc_epg_SetCurrent (vlc_epg_t * p_epg, int64_t i_start)
It set the current event of a vlc_epg_t given a start time.
References vlc_epg_t::i_event, vlc_epg_event_t::i_start, vlc_epg_t::p_current, and vlc_epg_t::pp_event.
Referenced by vout_OSDEpg().