VLC: include/vlc_events.h File Reference
vlc_events.h File Reference
This file is the interface definition for events (implementation in src/misc/events.c)
Data Structures
struct vlc_event_listeners_group_t
struct vlc_event_manager_t
struct vlc_event_t
union vlc_event_t::vlc_event_type_specific
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_meta_changed
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_subitem_added
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_subitem_tree_added
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_duration_changed
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_preparsed_changed
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_name_changed
struct vlc_event_t::vlc_event_type_specific::vlc_input_item_info_changed
struct vlc_event_t::vlc_event_type_specific::input_item_error_when_reading_changed
struct vlc_event_t::vlc_event_type_specific::input_item_preparse_ended
Typedefs
typedef enum vlc_event_type_t vlc_event_type_t
typedef struct vlc_event_listeners_group_t vlc_event_listeners_group_t
typedef struct vlc_event_manager_t vlc_event_manager_t
typedef struct vlc_event_t vlc_event_t
typedef void(* vlc_event_callback_t) (const vlc_event_t *, void *)
Enumerations
enum vlc_event_type_t {
vlc_InputItemMetaChanged , vlc_InputItemSubItemTreeAdded , vlc_InputItemDurationChanged , vlc_InputItemPreparsedChanged ,
vlc_InputItemNameChanged , vlc_InputItemInfoChanged , vlc_InputItemErrorWhenReadingChanged , vlc_InputItemPreparseEnded
}
Functions
void vlc_event_manager_init (vlc_event_manager_t *p_em, void *p_obj)
Initialize event manager object p_obj is the object that contains the event manager.
void vlc_event_manager_fini (vlc_event_manager_t *p_em)
Destroy the event manager.
void vlc_event_send (vlc_event_manager_t *p_em, vlc_event_t *)
Send an event to the listener attached to this p_em.
int vlc_event_attach (vlc_event_manager_t *p_event_manager, vlc_event_type_t event_type, vlc_event_callback_t pf_callback, void *p_user_data)
Add a callback for an event.
void vlc_event_detach (vlc_event_manager_t *p_event_manager, vlc_event_type_t event_type, vlc_event_callback_t pf_callback, void *p_user_data)
Remove a callback for an event.
Detailed Description
This file is the interface definition for events (implementation in src/misc/events.c)
Typedef Documentation
vlc_event_callback_t
typedef void(* vlc_event_callback_t) (const vlc_event_t *, void *)
vlc_event_listeners_group_t
typedef struct vlc_event_listeners_group_t vlc_event_listeners_group_t
vlc_event_manager_t
typedef struct vlc_event_manager_t vlc_event_manager_t
vlc_event_t
typedef struct vlc_event_t vlc_event_t
vlc_event_type_t
typedef enum vlc_event_type_t vlc_event_type_t
Enumeration Type Documentation
vlc_event_type_t
enum vlc_event_type_t
Enumerator
vlc_InputItemMetaChanged
vlc_InputItemSubItemTreeAdded
vlc_InputItemDurationChanged
vlc_InputItemPreparsedChanged
vlc_InputItemNameChanged
vlc_InputItemInfoChanged
vlc_InputItemErrorWhenReadingChanged
vlc_InputItemPreparseEnded
Function Documentation
vlc_event_attach()
int vlc_event_attach (vlc_event_manager_t * p_event_manager, vlc_event_type_t event_type, vlc_event_callback_t pf_callback, void * p_user_data)
Add a callback for an event.
< Not enough memory
< No error
References ARRAY_APPEND, vlc_event_manager_t::events, vlc_event_listeners_group_t::listeners, vlc_event_manager_t::lock, vlc_event_listener_t::p_user_data, vlc_event_listener_t::pf_callback, VLC_ENOMEM, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by playlist_ItemNewFromInput(), and playlist_MLLoad().
vlc_event_detach()
void vlc_event_detach (vlc_event_manager_t * p_event_manager, vlc_event_type_t event_type, vlc_event_callback_t pf_callback, void * p_user_data)
Remove a callback for an event.
References ARRAY_REMOVE, vlc_event_manager_t::events, FOREACH_ARRAY, FOREACH_END, vlc_event_listeners_group_t::listeners, vlc_event_manager_t::lock, vlc_event_listener_t::p_user_data, vlc_event_listener_t::pf_callback, vlc_assert_unreachable, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by playlist_ItemRelease(), and playlist_MLLoad().
vlc_event_manager_fini()
void vlc_event_manager_fini (vlc_event_manager_t * p_em)
Destroy the event manager.
References ARRAY_RESET, ARRAY_SIZE, vlc_event_manager_t::events, FOREACH_ARRAY, FOREACH_END, vlc_event_listeners_group_t::listeners, vlc_event_manager_t::lock, and vlc_mutex_destroy().
Referenced by input_item_Release().
vlc_event_manager_init()
void vlc_event_manager_init (vlc_event_manager_t * p_em, void * p_obj)
Initialize event manager object p_obj is the object that contains the event manager.
But not necessarily a vlc_object_t (an input_item_t is not a vlc_object_t for instance).
References ARRAY_INIT, ARRAY_SIZE, vlc_event_manager_t::events, vlc_event_listeners_group_t::listeners, vlc_event_manager_t::lock, vlc_event_manager_t::p_obj, and vlc_mutex_init_recursive().
Referenced by input_item_NewExt().
vlc_event_send()
void vlc_event_send (vlc_event_manager_t * p_em, vlc_event_t * p_event)
Send an event to the listener attached to this p_em.
References vlc_event_manager_t::events, FOREACH_ARRAY, FOREACH_END, vlc_event_listeners_group_t::listeners, vlc_event_manager_t::lock, vlc_event_manager_t::p_obj, vlc_event_t::p_obj, vlc_event_listener_t::p_user_data, vlc_event_listener_t::pf_callback, vlc_event_t::type, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by input_item_AddInfo(), input_item_DelInfo(), input_item_MergeInfos(), input_item_node_PostAndDelete(), input_item_ReplaceInfos(), input_item_SetDuration(), input_item_SetEpg(), input_item_SetEpgEvent(), input_item_SetEpgOffline(), input_item_SetErrorWhenReading(), input_item_SetMeta(), input_item_SetPreparsed(), and input_item_SignalPreparseEnded().