VLC: include/vlc_dialog.h File Reference
vlc_dialog.h File Reference
Interface » VLC dialog
This file declares VLC dialog functions.
Data Structures
struct vlc_dialog_cbs
Dialog callbacks to be implemented.
Macros
#define vlc_dialog_display_error(a, b, c, ...) vlc_dialog_display_error(VLC_OBJECT(a), b, c, ##__VA_ARGS__)
#define vlc_dialog_wait_login(a, b, c, d, e, f, g, ...) vlc_dialog_wait_login(VLC_OBJECT(a), b, c, d, e, f, g, ##__VA_ARGS__)
#define vlc_dialog_wait_question(a, b, c, d, e, f, g, ...) vlc_dialog_wait_question(VLC_OBJECT(a), b, c, d, e, f, g, ##__VA_ARGS__)
#define vlc_dialog_display_progress(a, b, c, d, e, f, ...) vlc_dialog_display_progress(VLC_OBJECT(a), b, c, d, e, f, ##__VA_ARGS__)
#define vlc_dialog_update_progress(a, b, c) vlc_dialog_update_progress(VLC_OBJECT(a), b, c)
#define vlc_dialog_update_progress_text(a, b, c, d, ...) vlc_dialog_update_progress_text(VLC_OBJECT(a), b, c, d, ##__VA_ARGS__)
#define vlc_dialog_release(a, b) vlc_dialog_release(VLC_OBJECT(a), b)
#define vlc_dialog_is_cancelled(a, b) vlc_dialog_is_cancelled(VLC_OBJECT(a), b)
#define vlc_dialog_provider_set_callbacks(a, b, c) vlc_dialog_provider_set_callbacks(VLC_OBJECT(a), b, c)
#define vlc_ext_dialog_update(a, b) vlc_ext_dialog_update(VLC_OBJECT(a), b)
#define vlc_dialog_provider_set_ext_callback(a, b, c) vlc_dialog_provider_set_ext_callback(VLC_OBJECT(a), b, c)
Typedefs
typedef struct vlc_dialog_provider vlc_dialog_provider
typedef struct vlc_dialog_id vlc_dialog_id
typedef struct extension_dialog_t extension_dialog_t
typedef enum vlc_dialog_question_type vlc_dialog_question_type
Dialog question type, see vlc_dialog_wait_question()
typedef struct vlc_dialog_cbs vlc_dialog_cbs
Dialog callbacks to be implemented.
typedef void(* vlc_dialog_ext_update_cb) (extension_dialog_t *p_ext_dialog, void *p_data)
Dialog extension callback to be implemented.
Enumerations
enum vlc_dialog_question_type { VLC_DIALOG_QUESTION_NORMAL , VLC_DIALOG_QUESTION_WARNING , VLC_DIALOG_QUESTION_CRITICAL }
Dialog question type, see vlc_dialog_wait_question()
Functions
int libvlc_InternalDialogInit (libvlc_int_t *p_libvlc)
void libvlc_InternalDialogClean (libvlc_int_t *p_libvlc)
int vlc_dialog_display_error (vlc_object_t *p_obj, const char *psz_title, const char *psz_fmt,...)
Sends an error message.
int vlc_dialog_display_error_va (vlc_object_t *p_obj, const char *psz_title, const char *psz_fmt, va_list ap)
Sends an error message.
int vlc_dialog_wait_login (vlc_object_t *p_obj, char **ppsz_username, char **ppsz_password, bool *p_store, const char *psz_default_username, const char *psz_title, const char *psz_fmt,...)
Requests an user name and a password.
int vlc_dialog_wait_login_va (vlc_object_t *p_obj, char **ppsz_username, char **ppsz_password, bool *p_store, const char *psz_default_username, const char *psz_title, const char *psz_fmt, va_list ap)
Requests an user name and a password.
int vlc_dialog_wait_question (vlc_object_t *p_obj, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2, const char *psz_title, const char *psz_fmt,...)
Asks a total (Yes/No/Cancel) question.
int vlc_dialog_wait_question_va (vlc_object_t *p_obj, vlc_dialog_question_type i_type, const char *psz_cancel, const char *psz_action1, const char *psz_action2, const char *psz_title, const char *psz_fmt, va_list ap)
Asks a total (Yes/No/Cancel) question.
vlc_dialog_id * vlc_dialog_display_progress (vlc_object_t *p_obj, bool b_indeterminate, float f_position, const char *psz_cancel, const char *psz_title, const char *psz_fmt,...)
Display a progress dialog.
vlc_dialog_id * vlc_dialog_display_progress_va (vlc_object_t *p_obj, bool b_indeterminate, float f_position, const char *psz_cancel, const char *psz_title, const char *psz_fmt, va_list ap)
Display a progress dialog.
int vlc_dialog_update_progress (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_position)
Update the position of the progress dialog.
int vlc_dialog_update_progress_text (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_position, const char *psz_fmt,...)
Update the position and the message of the progress dialog.
int vlc_dialog_update_progress_text_va (vlc_object_t *p_obj, vlc_dialog_id *p_id, float f_position, const char *psz_fmt, va_list ap)
Update the position and the message of the progress dialog.
void vlc_dialog_release (vlc_object_t *p_obj, vlc_dialog_id *p_id)
Release the dialog id returned by vlc_dialog_display_progress()
bool vlc_dialog_is_cancelled (vlc_object_t *p_obj, vlc_dialog_id *p_id)
Return true if the dialog id is cancelled.
void vlc_dialog_provider_set_callbacks (vlc_object_t *p_obj, const vlc_dialog_cbs *p_cbs, void *p_data)
Register callbacks to handle VLC dialogs.
void vlc_dialog_id_set_context (vlc_dialog_id *p_id, void *p_context)
Associate an opaque pointer with the dialog id.
void * vlc_dialog_id_get_context (vlc_dialog_id *p_id)
Return the opaque pointer associated with the dialog id.
int vlc_dialog_id_post_login (vlc_dialog_id *p_id, const char *psz_username, const char *psz_password, bool b_store)
Post a login answer.
int vlc_dialog_id_post_action (vlc_dialog_id *p_id, int i_action)
Post a question answer.
int vlc_dialog_id_dismiss (vlc_dialog_id *p_id)
Dismiss a dialog.
int vlc_ext_dialog_update (vlc_object_t *p_obj, extension_dialog_t *dialog)
void vlc_dialog_provider_set_ext_callback (vlc_object_t *p_obj, vlc_dialog_ext_update_cb pf_update, void *p_data)
Register a callback for VLC extension dialog.
Detailed Description
This file declares VLC dialog functions.
Typedef Documentation
extension_dialog_t
typedef struct extension_dialog_t extension_dialog_t
vlc_dialog_id
typedef struct vlc_dialog_id vlc_dialog_id
vlc_dialog_provider
typedef struct vlc_dialog_provider vlc_dialog_provider
Function Documentation
libvlc_InternalDialogClean()
void libvlc_InternalDialogClean (libvlc_int_t * p_libvlc)
References dialog_clear_all_locked(), libvlc_priv(), vlc_dialog_provider::lock, libvlc_priv_t::p_dialog_provider, vlc_mutex_destroy(), vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by libvlc_InternalCleanup().
libvlc_InternalDialogInit()
int libvlc_InternalDialogInit (libvlc_int_t * p_libvlc)
< Unspecified error
< No error
References vlc_dialog_provider::cbs, vlc_dialog_provider::dialog_array, libvlc_priv(), vlc_dialog_provider::lock, vlc_dialog_provider::p_cbs_data, libvlc_priv_t::p_dialog_provider, vlc_dialog_provider::p_ext_data, vlc_dialog_provider::pf_ext_update, vlc_array_init(), VLC_EGENERIC, vlc_mutex_init(), and VLC_SUCCESS.
Referenced by libvlc_InternalInit().