VLC: include/vlc_block_helper.h File Reference
vlc_block_helper.h File Reference
Data Structures
struct block_bytestream_t
Typedefs
typedef struct block_bytestream_t block_bytestream_t
typedef const uint8_t *(* block_startcode_helper_t) (const uint8_t *, const uint8_t *)
typedef bool(* block_startcode_matcher_t) (uint8_t, size_t, const uint8_t *)
Functions
static void block_BytestreamInit (block_bytestream_t *p_bytestream)
static void block_BytestreamRelease (block_bytestream_t *p_bytestream)
static void block_BytestreamEmpty (block_bytestream_t *p_bytestream)
It flush all data (read and unread) from a block_bytestream_t.
static void block_BytestreamFlush (block_bytestream_t *p_bytestream)
It flushes all already read data from a block_bytestream_t.
static void block_BytestreamPush (block_bytestream_t *p_bytestream, block_t *p_block)
static size_t block_BytestreamRemaining (const block_bytestream_t *p_bytestream)
static block_t * block_BytestreamPop (block_bytestream_t *p_bytestream)
static int block_WaitBytes (block_bytestream_t *p_bytestream, size_t i_data)
static int block_PeekBytes (block_bytestream_t *p_bytestream, uint8_t *p_data, size_t i_data)
static int block_GetBytes (block_bytestream_t *p_bytestream, uint8_t *p_data, size_t i_data)
static int block_SkipBytes (block_bytestream_t *p_bytestream, size_t i_data)
static int block_SkipByte (block_bytestream_t *p_bytestream)
static int block_PeekOffsetBytes (block_bytestream_t *p_bytestream, size_t i_peek_offset, uint8_t *p_data, size_t i_data)
static int block_FindStartcodeFromOffset (block_bytestream_t *p_bytestream, size_t *pi_offset, const uint8_t *p_startcode, int i_startcode_length, block_startcode_helper_t p_startcode_helper, block_startcode_matcher_t p_startcode_matcher)
Typedef Documentation
block_bytestream_t
typedef struct block_bytestream_t block_bytestream_t
block_startcode_helper_t
typedef const uint8_t *(* block_startcode_helper_t) (const uint8_t *, const uint8_t *)
block_startcode_matcher_t
typedef bool(* block_startcode_matcher_t) (uint8_t, size_t, const uint8_t *)
Function Documentation
block_BytestreamEmpty()
static void block_BytestreamEmpty (block_bytestream_t * p_bytestream) inline static
It flush all data (read and unread) from a block_bytestream_t.
References block_BytestreamInit(), and block_BytestreamRelease().
block_BytestreamFlush()
static void block_BytestreamFlush (block_bytestream_t * p_bytestream) inline static
It flushes all already read data from a block_bytestream_t.
References block_Release(), block_bytestream_t::i_base_offset, block_bytestream_t::i_block_offset, block_t::i_buffer, block_bytestream_t::i_total, block_bytestream_t::p_block, block_bytestream_t::p_chain, block_t::p_next, and block_bytestream_t::pp_last.
Referenced by block_BytestreamPop().
block_BytestreamInit()
static void block_BytestreamInit (block_bytestream_t * p_bytestream) inline static
References block_bytestream_t::i_base_offset, block_bytestream_t::i_block_offset, block_bytestream_t::i_total, block_bytestream_t::p_block, block_bytestream_t::p_chain, and block_bytestream_t::pp_last.
Referenced by block_BytestreamEmpty().
block_BytestreamPop()
static block_t * block_BytestreamPop (block_bytestream_t * p_bytestream) inline static
References block_BytestreamFlush(), block_bytestream_t::i_block_offset, block_t::i_buffer, block_bytestream_t::i_total, block_bytestream_t::p_block, block_t::p_buffer, block_bytestream_t::p_chain, block_t::p_next, block_bytestream_t::pp_last, and unlikely.
block_BytestreamPush()
static void block_BytestreamPush (block_bytestream_t * p_bytestream, block_t * p_block) inline static
References block_ChainLastAppend(), block_t::i_buffer, block_bytestream_t::i_total, block_bytestream_t::p_block, block_t::p_next, and block_bytestream_t::pp_last.
block_BytestreamRelease()
static void block_BytestreamRelease (block_bytestream_t * p_bytestream) inline static
References block_ChainRelease(), and block_bytestream_t::p_chain.
Referenced by block_BytestreamEmpty().
block_BytestreamRemaining()
static size_t block_BytestreamRemaining (const block_bytestream_t * p_bytestream) inline static
References block_bytestream_t::i_base_offset, block_bytestream_t::i_block_offset, and block_bytestream_t::i_total.
Referenced by block_GetBytes(), block_PeekBytes(), block_PeekOffsetBytes(), and block_WaitBytes().
block_FindStartcodeFromOffset()
static int block_FindStartcodeFromOffset (block_bytestream_t * p_bytestream, size_t * pi_offset, const uint8_t * p_startcode, int i_startcode_length, block_startcode_helper_t p_startcode_helper, block_startcode_matcher_t p_startcode_matcher) inline static
< Unspecified error
< No error
< No error
< Unspecified error
References block_bytestream_t::i_block_offset, block_t::i_buffer, block_bytestream_t::p_block, block_t::p_buffer, block_t::p_next, unlikely, VLC_EGENERIC, and VLC_SUCCESS.
block_GetBytes()
static int block_GetBytes (block_bytestream_t * p_bytestream, uint8_t * p_data, size_t i_data) inline static
< Unspecified error
< No error
References block_BytestreamRemaining(), block_bytestream_t::i_base_offset, block_bytestream_t::i_block_offset, block_t::i_buffer, block_bytestream_t::p_block, block_t::p_buffer, block_t::p_next, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by block_SkipByte(), and block_SkipBytes().
block_PeekBytes()
static int block_PeekBytes (block_bytestream_t * p_bytestream, uint8_t * p_data, size_t i_data) inline static
< Unspecified error
< No error
References block_BytestreamRemaining(), block_bytestream_t::i_block_offset, block_bytestream_t::p_block, VLC_EGENERIC, and VLC_SUCCESS.
block_PeekOffsetBytes()
static int block_PeekOffsetBytes (block_bytestream_t * p_bytestream, size_t i_peek_offset, uint8_t * p_data, size_t i_data) inline static
< Unspecified error
< No error
References block_BytestreamRemaining(), block_bytestream_t::i_block_offset, block_t::i_buffer, block_bytestream_t::p_block, block_t::p_buffer, block_t::p_next, VLC_EGENERIC, and VLC_SUCCESS.
block_SkipByte()
static int block_SkipByte (block_bytestream_t * p_bytestream) inline static
References block_GetBytes().
block_SkipBytes()
static int block_SkipBytes (block_bytestream_t * p_bytestream, size_t i_data) inline static
References block_GetBytes().
block_WaitBytes()
static int block_WaitBytes (block_bytestream_t * p_bytestream, size_t i_data) inline static
< No error
< Unspecified error
References block_BytestreamRemaining(), VLC_EGENERIC, and VLC_SUCCESS.