VLC: include/vlc_keystore.h File Reference
vlc_keystore.h File Reference
Keystore and credential API
This file declares vlc keystore API.
Data Structures
struct vlc_keystore_entry
Keystore entry returned by vlc_keystore_find()
struct vlc_credential
struct vlc_keystore
Macros
#define VLC_KEYSTORE_VALUES_INIT(ppsz_values) memset(ppsz_values, 0, sizeof(const char *) * KEY_MAX)
#define vlc_keystore_create(x) vlc_keystore_create(VLC_OBJECT(x))
#define vlc_credential_get(a, b, c, d, e, f, ...) vlc_credential_get(a, VLC_OBJECT(b), c, d, e, f, ##__VA_ARGS__)
#define vlc_credential_store(a, b) vlc_credential_store(a, VLC_OBJECT(b))
#define VLC_KEYSTORE_NAME "libVLC"
Typedefs
typedef struct vlc_keystore vlc_keystore
typedef struct vlc_keystore_entry vlc_keystore_entry
typedef struct vlc_credential vlc_credential
typedef struct vlc_keystore_sys vlc_keystore_sys
Enumerations
enum vlc_keystore_key {
KEY_PROTOCOL , KEY_USER , KEY_SERVER , KEY_PATH ,
KEY_PORT , KEY_REALM , KEY_AUTHTYPE , KEY_MAX
}
List of keys that can be stored via the keystore API.
Functions
int libvlc_InternalKeystoreInit (libvlc_int_t *p_libvlc)
void libvlc_InternalKeystoreClean (libvlc_int_t *p_libvlc)
vlc_keystore * vlc_keystore_create (vlc_object_t *p_parent)
Create a keystore object.
void vlc_keystore_release (vlc_keystore *p_keystore)
Release a keystore object.
int vlc_keystore_store (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX], const uint8_t *p_secret, ssize_t i_secret_len, const char *psz_label)
Store a secret associated with a set of key/values.
unsigned int vlc_keystore_find (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX], vlc_keystore_entry **pp_entries)
Find all entries that match a set of key/values.
unsigned int vlc_keystore_remove (vlc_keystore *p_keystore, const char *const ppsz_values[KEY_MAX])
Remove all entries that match a set of key/values.
void vlc_keystore_release_entries (vlc_keystore_entry *p_entries, unsigned int i_count)
Release the list of entries returned by vlc_keystore_find()
void vlc_credential_init (vlc_credential *p_credential, const vlc_url_t *p_url)
Init a credential struct.
void vlc_credential_clean (vlc_credential *p_credential)
Clean a credential struct.
bool vlc_credential_get (vlc_credential *p_credential, vlc_object_t *p_parent, const char *psz_option_username, const char *psz_option_password, const char *psz_dialog_title, const char *psz_dialog_fmt,...)
Get a username/password couple.
bool vlc_credential_store (vlc_credential *p_credential, vlc_object_t *p_parent)
Store the last dialog credential returned by vlc_credential_get()
static int vlc_keystore_entry_set_secret (vlc_keystore_entry *p_entry, const uint8_t *p_secret, size_t i_secret_len)
static void vlc_keystore_release_entry (vlc_keystore_entry *p_entry)
Detailed Description
This file declares vlc keystore API.
Typedef Documentation
vlc_credential
typedef struct vlc_credential vlc_credential
vlc_keystore
typedef struct vlc_keystore vlc_keystore
vlc_keystore_entry
typedef struct vlc_keystore_entry vlc_keystore_entry
Function Documentation
libvlc_InternalKeystoreClean()
void libvlc_InternalKeystoreClean (libvlc_int_t * p_libvlc)
References libvlc_priv(), libvlc_priv_t::p_memory_keystore, and vlc_keystore_release().
Referenced by libvlc_InternalCleanup().
libvlc_InternalKeystoreInit()
int libvlc_InternalKeystoreInit (libvlc_int_t * p_libvlc)
< No error
< Unspecified error
References keystore_create(), libvlc_priv(), libvlc_priv_t::p_memory_keystore, VLC_EGENERIC, VLC_OBJECT, and VLC_SUCCESS.
Referenced by libvlc_InternalInit().