VLC: include/vlc_md5.h File Reference
vlc_md5.h File Reference
This file defines functions and structures to compute MD5 digests.
Data Structures
struct md5_s
Functions
void InitMD5 (struct md5_s *)
void AddMD5 (struct md5_s *, const void *, size_t)
void EndMD5 (struct md5_s *)
static char * psz_md5_hash (struct md5_s *md5_s)
Returns a char representation of the md5 hash, as shown by UNIX md5 or md5sum tools.
Detailed Description
This file defines functions and structures to compute MD5 digests.
Function Documentation
AddMD5()
void AddMD5 (struct md5_s * , const void * , size_t)
EndMD5()
void EndMD5 (struct md5_s * h)
References md5_final().
Referenced by ArtCacheGetDirPath(), AuthDigest(), GenerateCnonce(), and vlc_rand_bytes().
InitMD5()
void InitMD5 (struct md5_s * h)
References md5_init().
Referenced by ArtCacheGetDirPath(), AuthDigest(), GenerateCnonce(), and vlc_rand_bytes().
psz_md5_hash()
static char * psz_md5_hash (struct md5_s * md5_s) inline static
Returns a char representation of the md5 hash, as shown by UNIX md5 or md5sum tools.
References md5_s::buf, and likely.
Referenced by ArtCacheGetDirPath(), AuthDigest(), and GenerateCnonce().