VLC: include/vlc_es.h File Reference
vlc_es.h File Reference
This file defines the elementary streams format types.
Data Structures
struct video_palette_t
struct audio_replay_gain_t
struct audio_format_t
audio format description
struct video_format_t
video format description
struct subs_format_t
subtitles format description
struct extra_languages_t
ES language definition.
struct es_format_t
Macros
#define VIDEO_PALETTE_COLORS_MAX 256
video palette data
#define AUDIO_REPLAY_GAIN_MAX (2)
audio replay gain description
#define AUDIO_REPLAY_GAIN_TRACK (0)
#define AUDIO_REPLAY_GAIN_ALBUM (1)
#define AOUT_CHAN_CENTER 0x1
#define AOUT_CHAN_LEFT 0x2
#define AOUT_CHAN_RIGHT 0x4
#define AOUT_CHAN_REARCENTER 0x10
#define AOUT_CHAN_REARLEFT 0x20
#define AOUT_CHAN_REARRIGHT 0x40
#define AOUT_CHAN_MIDDLELEFT 0x100
#define AOUT_CHAN_MIDDLERIGHT 0x200
#define AOUT_CHAN_LFE 0x1000
#define AOUT_CHANS_FRONT (AOUT_CHAN_LEFT | AOUT_CHAN_RIGHT)
#define AOUT_CHANS_MIDDLE (AOUT_CHAN_MIDDLELEFT | AOUT_CHAN_MIDDLERIGHT)
#define AOUT_CHANS_REAR (AOUT_CHAN_REARLEFT | AOUT_CHAN_REARRIGHT)
#define AOUT_CHANS_CENTER (AOUT_CHAN_CENTER | AOUT_CHAN_REARCENTER)
#define AOUT_CHANS_STEREO AOUT_CHANS_2_0
#define AOUT_CHANS_2_0 (AOUT_CHANS_FRONT)
#define AOUT_CHANS_2_1 (AOUT_CHANS_FRONT | AOUT_CHAN_LFE)
#define AOUT_CHANS_3_0 (AOUT_CHANS_FRONT | AOUT_CHAN_CENTER)
#define AOUT_CHANS_3_1 (AOUT_CHANS_3_0 | AOUT_CHAN_LFE)
#define AOUT_CHANS_4_0 (AOUT_CHANS_FRONT | AOUT_CHANS_REAR)
#define AOUT_CHANS_4_1 (AOUT_CHANS_4_0 | AOUT_CHAN_LFE)
#define AOUT_CHANS_5_0 (AOUT_CHANS_4_0 | AOUT_CHAN_CENTER)
#define AOUT_CHANS_5_1 (AOUT_CHANS_5_0 | AOUT_CHAN_LFE)
#define AOUT_CHANS_6_0 (AOUT_CHANS_4_0 | AOUT_CHANS_MIDDLE)
#define AOUT_CHANS_7_0 (AOUT_CHANS_6_0 | AOUT_CHAN_CENTER)
#define AOUT_CHANS_7_1 (AOUT_CHANS_5_1 | AOUT_CHANS_MIDDLE)
#define AOUT_CHANS_8_1 (AOUT_CHANS_7_1 | AOUT_CHAN_REARCENTER)
#define AOUT_CHANS_4_0_MIDDLE (AOUT_CHANS_FRONT | AOUT_CHANS_MIDDLE)
#define AOUT_CHANS_4_CENTER_REAR (AOUT_CHANS_FRONT | AOUT_CHANS_CENTER)
#define AOUT_CHANS_5_0_MIDDLE (AOUT_CHANS_4_0_MIDDLE | AOUT_CHAN_CENTER)
#define AOUT_CHANS_6_1_MIDDLE (AOUT_CHANS_5_0_MIDDLE | AOUT_CHAN_REARCENTER | AOUT_CHAN_LFE)
#define AOUT_CHAN_MAX 9
#define INPUT_CHAN_MAX 64
#define AOUT_CHANMODE_DUALMONO 0x1
#define AOUT_CHANMODE_DOLBYSTEREO 0x2
#define ORIENT_FROM_EXIF(exif) ((0x57642310U >> (4 * ((exif) - 1))) & 7)
Convert EXIF orientation to enum video_orientation_t.
#define ORIENT_TO_EXIF(orient) ((0x76853421U >> (4 * (orient))) & 15)
Convert enum video_orientation_t to EXIF.
#define ORIENT_IS_MIRROR(orient) parity(orient)
If the orientation is natural or mirrored.
#define ORIENT_IS_SWAP(orient) (((orient) & 4) != 0)
If the orientation swaps dimensions.
#define ORIENT_HFLIP(orient) ((orient) ^ 1)
Applies horizontal flip to an orientation.
#define ORIENT_VFLIP(orient) ((orient) ^ 2)
Applies vertical flip to an orientation.
#define ORIENT_ROTATE_180(orient) ((orient) ^ 3)
Applies horizontal flip to an orientation.
#define COLOR_PRIMARIES_SRGB COLOR_PRIMARIES_BT709
#define COLOR_PRIMARIES_SMTPE_170 COLOR_PRIMARIES_BT601_525
#define COLOR_PRIMARIES_SMTPE_240 COLOR_PRIMARIES_BT601_525 /* Only differs from 1e10-4 in white Y */
#define COLOR_PRIMARIES_SMTPE_RP145 COLOR_PRIMARIES_BT601_525
#define COLOR_PRIMARIES_EBU_3213 COLOR_PRIMARIES_BT601_625
#define COLOR_PRIMARIES_BT470_BG COLOR_PRIMARIES_BT601_625
#define COLOR_PRIMARIES_BT470_M COLOR_PRIMARIES_FCC1953
#define COLOR_PRIMARIES_MAX COLOR_PRIMARIES_FCC1953
#define TRANSFER_FUNC_BT2020 TRANSFER_FUNC_BT709
#define TRANSFER_FUNC_SMPTE_170 TRANSFER_FUNC_BT709
#define TRANSFER_FUNC_SMPTE_274 TRANSFER_FUNC_BT709
#define TRANSFER_FUNC_SMPTE_293 TRANSFER_FUNC_BT709
#define TRANSFER_FUNC_SMPTE_296 TRANSFER_FUNC_BT709
#define TRANSFER_FUNC_ARIB_B67 TRANSFER_FUNC_HLG
#define TRANSFER_FUNC_MAX TRANSFER_FUNC_HLG
#define COLOR_SPACE_SRGB COLOR_SPACE_BT709
#define COLOR_SPACE_SMPTE_170 COLOR_SPACE_BT601
#define COLOR_SPACE_SMPTE_240 COLOR_SPACE_SMPTE_170
#define COLOR_SPACE_MAX COLOR_SPACE_BT2020
#define CHROMA_LOCATION_MAX CHROMA_LOCATION_BOTTOM_CENTER
#define SPU_PALETTE_DEFINED 0xbeefbeef
#define ES_CATEGORY_COUNT (DATA_ES + 1)
#define ES_PRIORITY_NOT_SELECTABLE -2
ES format definition.
#define ES_PRIORITY_NOT_DEFAULTABLE -1
#define ES_PRIORITY_SELECTABLE_MIN 0
#define ES_PRIORITY_MIN ES_PRIORITY_NOT_SELECTABLE
Typedefs
typedef enum audio_channel_type_t audio_channel_type_t
Audio channel type.
typedef enum video_orientation_t video_orientation_t
Picture orientation.
typedef enum video_transform_t video_transform_t
typedef enum video_multiview_mode_t video_multiview_mode_t
typedef enum video_projection_mode_t video_projection_mode_t
Video projection mode.
typedef enum video_color_primaries_t video_color_primaries_t
Video color primaries (a.k.a.
typedef enum video_transfer_func_t video_transfer_func_t
Video transfer functions.
typedef enum video_color_space_t video_color_space_t
Video color space (i.e.
typedef enum video_chroma_location_t video_chroma_location_t
Video chroma location.
typedef struct extra_languages_t extra_languages_t
ES language definition.
Enumerations
enum audio_channel_type_t { AUDIO_CHANNEL_TYPE_BITMAP , AUDIO_CHANNEL_TYPE_AMBISONICS }
Audio channel type.
enum video_orientation_t {
ORIENT_TOP_LEFT = 0 , ORIENT_TOP_RIGHT , ORIENT_BOTTOM_LEFT , ORIENT_BOTTOM_RIGHT ,
ORIENT_LEFT_TOP , ORIENT_LEFT_BOTTOM , ORIENT_RIGHT_TOP , ORIENT_RIGHT_BOTTOM ,
ORIENT_NORMAL = ORIENT_TOP_LEFT , ORIENT_TRANSPOSED = ORIENT_LEFT_TOP , ORIENT_ANTI_TRANSPOSED = ORIENT_RIGHT_BOTTOM , ORIENT_HFLIPPED = ORIENT_TOP_RIGHT ,
ORIENT_VFLIPPED = ORIENT_BOTTOM_LEFT , ORIENT_ROTATED_180 = ORIENT_BOTTOM_RIGHT , ORIENT_ROTATED_270 = ORIENT_LEFT_BOTTOM , ORIENT_ROTATED_90 = ORIENT_RIGHT_TOP
}
Picture orientation.
enum video_transform_t {
TRANSFORM_IDENTITY = ORIENT_NORMAL , TRANSFORM_HFLIP = ORIENT_HFLIPPED , TRANSFORM_VFLIP = ORIENT_VFLIPPED , TRANSFORM_R180 = ORIENT_ROTATED_180 ,
TRANSFORM_R270 = ORIENT_ROTATED_270 , TRANSFORM_R90 = ORIENT_ROTATED_90 , TRANSFORM_TRANSPOSE = ORIENT_TRANSPOSED , TRANSFORM_ANTI_TRANSPOSE = ORIENT_ANTI_TRANSPOSED
}
enum video_multiview_mode_t {
MULTIVIEW_2D = 0 , MULTIVIEW_STEREO_SBS , MULTIVIEW_STEREO_TB , MULTIVIEW_STEREO_ROW ,
MULTIVIEW_STEREO_COL , MULTIVIEW_STEREO_FRAME , MULTIVIEW_STEREO_CHECKERBOARD
}
enum video_projection_mode_t { PROJECTION_MODE_RECTANGULAR = 0 , PROJECTION_MODE_EQUIRECTANGULAR , PROJECTION_MODE_CUBEMAP_LAYOUT_STANDARD = 0x100 }
Video projection mode.
enum video_color_primaries_t {
COLOR_PRIMARIES_UNDEF , COLOR_PRIMARIES_BT601_525 , COLOR_PRIMARIES_BT601_625 , COLOR_PRIMARIES_BT709 ,
COLOR_PRIMARIES_BT2020 , COLOR_PRIMARIES_DCI_P3 , COLOR_PRIMARIES_FCC1953
}
Video color primaries (a.k.a.
enum video_transfer_func_t {
TRANSFER_FUNC_UNDEF , TRANSFER_FUNC_LINEAR , TRANSFER_FUNC_SRGB , TRANSFER_FUNC_BT470_BG ,
TRANSFER_FUNC_BT470_M , TRANSFER_FUNC_BT709 , TRANSFER_FUNC_SMPTE_ST2084 , TRANSFER_FUNC_SMPTE_240 ,
TRANSFER_FUNC_HLG
}
Video transfer functions.
enum video_color_space_t { COLOR_SPACE_UNDEF , COLOR_SPACE_BT601 , COLOR_SPACE_BT709 , COLOR_SPACE_BT2020 }
Video color space (i.e.
enum video_chroma_location_t {
CHROMA_LOCATION_UNDEF , CHROMA_LOCATION_LEFT , CHROMA_LOCATION_CENTER , CHROMA_LOCATION_TOP_LEFT ,
CHROMA_LOCATION_TOP_CENTER , CHROMA_LOCATION_BOTTOM_LEFT , CHROMA_LOCATION_BOTTOM_CENTER
}
Video chroma location.
enum es_format_category_e {
UNKNOWN_ES = 0x00 , VIDEO_ES , AUDIO_ES , SPU_ES ,
DATA_ES
}
ES Categories.
Functions
static void video_format_Init (video_format_t *p_src, vlc_fourcc_t i_chroma)
Initialize a video_format_t structure with chroma 'i_chroma'.
static int video_format_Copy (video_format_t *p_dst, const video_format_t *p_src)
Copy video_format_t including the palette.
static void video_format_AdjustColorSpace (video_format_t *p_fmt)
static void video_format_Clean (video_format_t *p_src)
Cleanup and free palette of this video_format_t.
void video_format_Setup (video_format_t *, vlc_fourcc_t i_chroma, int i_width, int i_height, int i_visible_width, int i_visible_height, int i_sar_num, int i_sar_den)
It will fill up a video_format_t using the given arguments.
void video_format_CopyCrop (video_format_t *, const video_format_t *)
It will copy the crop properties from a video_format_t to another.
void video_format_ScaleCropAr (video_format_t *, const video_format_t *)
It will compute the crop/ar properties when scaling.
void video_format_ApplyRotation (video_format_t *out, const video_format_t *in)
This function "normalizes" the formats orientation, by switching the a/r according to the orientation, producing a format whose orientation is ORIENT_NORMAL.
void video_format_TransformBy (video_format_t *fmt, video_transform_t transform)
This function applies the transform operation to fmt.
void video_format_TransformTo (video_format_t *fmt, video_orientation_t dst_orientation)
This function applies the transforms necessary to fmt so that the resulting fmt has the dst_orientation.
video_transform_t video_format_GetTransform (video_orientation_t src, video_orientation_t dst)
Returns the operation required to transform src into dst.
bool video_format_IsSimilar (const video_format_t *, const video_format_t *)
This function will check if the first video format is similar to the second one.
void video_format_Print (vlc_object_t *, const char *, const video_format_t *)
It prints details about the given video_format_t.
static video_transform_t transform_Inverse (video_transform_t transform)
void video_format_FixRgb (video_format_t *)
This function will fill all RGB shift from RGB masks.
void es_format_Init (es_format_t *, int i_cat, vlc_fourcc_t i_codec)
This function will initialize a es_format_t structure.
void es_format_InitFromVideo (es_format_t *, const video_format_t *)
This function will initialize a es_format_t structure from a video_format_t.
int es_format_Copy (es_format_t *p_dst, const es_format_t *p_src)
This functions will copy a es_format_t.
void es_format_Clean (es_format_t *fmt)
This function will clean up a es_format_t and release all associated resources.
bool es_format_IsSimilar (const es_format_t *, const es_format_t *)
This function will check if the first ES format is similar to the second one.
static void es_format_Change (es_format_t *fmt, int i_cat, vlc_fourcc_t i_codec)
Changes ES format to another category Format must have been properly initialized.
Detailed Description
This file defines the elementary streams format types.
Macro Definition Documentation
AOUT_CHAN_CENTER
#define AOUT_CHAN_CENTER 0x1
Referenced by aout_FormatPrintChannels(), aout_OutputNew(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_LEFT
#define AOUT_CHAN_LEFT 0x2
Referenced by aout_FormatPrintChannels(), aout_SetWavePhysicalChannels(), and aout_update_format().
AOUT_CHAN_LFE
#define AOUT_CHAN_LFE 0x1000
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_MAX
#define AOUT_CHAN_MAX 9
Referenced by aout_ChannelReorder(), aout_CheckChannelExtraction(), aout_CheckChannelReorder(), aout_DecNew(), aout_SetWavePhysicalChannels(), and AppendRemapFilter().
AOUT_CHAN_MIDDLELEFT
#define AOUT_CHAN_MIDDLELEFT 0x100
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_MIDDLERIGHT
#define AOUT_CHAN_MIDDLERIGHT 0x200
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_REARCENTER
#define AOUT_CHAN_REARCENTER 0x10
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_REARLEFT
#define AOUT_CHAN_REARLEFT 0x20
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_REARRIGHT
#define AOUT_CHAN_REARRIGHT 0x40
Referenced by aout_FormatPrintChannels(), and aout_SetWavePhysicalChannels().
AOUT_CHAN_RIGHT
#define AOUT_CHAN_RIGHT 0x4
Referenced by aout_FormatPrintChannels(), aout_SetWavePhysicalChannels(), and aout_update_format().
AOUT_CHANMODE_DOLBYSTEREO
#define AOUT_CHANMODE_DOLBYSTEREO 0x2
Referenced by aout_FormatPrintChannels(), aout_PrepareStereoMode(), and aout_update_format().
AOUT_CHANMODE_DUALMONO
#define AOUT_CHANMODE_DUALMONO 0x1
Referenced by aout_FormatPrintChannels(), and aout_PrepareStereoMode().
AOUT_CHANS_2_0
#define AOUT_CHANS_2_0 (AOUT_CHANS_FRONT)
AOUT_CHANS_2_1
#define AOUT_CHANS_2_1 (AOUT_CHANS_FRONT | AOUT_CHAN_LFE)
AOUT_CHANS_3_0
#define AOUT_CHANS_3_0 (AOUT_CHANS_FRONT | AOUT_CHAN_CENTER)
AOUT_CHANS_3_1
#define AOUT_CHANS_3_1 (AOUT_CHANS_3_0 | AOUT_CHAN_LFE)
AOUT_CHANS_4_0
#define AOUT_CHANS_4_0 (AOUT_CHANS_FRONT | AOUT_CHANS_REAR)
AOUT_CHANS_4_0_MIDDLE
#define AOUT_CHANS_4_0_MIDDLE (AOUT_CHANS_FRONT | AOUT_CHANS_MIDDLE)
AOUT_CHANS_4_1
#define AOUT_CHANS_4_1 (AOUT_CHANS_4_0 | AOUT_CHAN_LFE)
AOUT_CHANS_4_CENTER_REAR
#define AOUT_CHANS_4_CENTER_REAR (AOUT_CHANS_FRONT | AOUT_CHANS_CENTER)
AOUT_CHANS_5_0
#define AOUT_CHANS_5_0 (AOUT_CHANS_4_0 | AOUT_CHAN_CENTER)
AOUT_CHANS_5_0_MIDDLE
#define AOUT_CHANS_5_0_MIDDLE (AOUT_CHANS_4_0_MIDDLE | AOUT_CHAN_CENTER)
AOUT_CHANS_5_1
#define AOUT_CHANS_5_1 (AOUT_CHANS_5_0 | AOUT_CHAN_LFE)
AOUT_CHANS_6_0
#define AOUT_CHANS_6_0 (AOUT_CHANS_4_0 | AOUT_CHANS_MIDDLE)
AOUT_CHANS_6_1_MIDDLE
#define AOUT_CHANS_6_1_MIDDLE (AOUT_CHANS_5_0_MIDDLE | AOUT_CHAN_REARCENTER | AOUT_CHAN_LFE)
AOUT_CHANS_7_0
#define AOUT_CHANS_7_0 (AOUT_CHANS_6_0 | AOUT_CHAN_CENTER)
AOUT_CHANS_7_1
#define AOUT_CHANS_7_1 (AOUT_CHANS_5_1 | AOUT_CHANS_MIDDLE)
Referenced by aout_OutputNew().
AOUT_CHANS_8_1
#define AOUT_CHANS_8_1 (AOUT_CHANS_7_1 | AOUT_CHAN_REARCENTER)
AOUT_CHANS_CENTER
#define AOUT_CHANS_CENTER (AOUT_CHAN_CENTER | AOUT_CHAN_REARCENTER)
AOUT_CHANS_FRONT
#define AOUT_CHANS_FRONT (AOUT_CHAN_LEFT | AOUT_CHAN_RIGHT)
AOUT_CHANS_MIDDLE
#define AOUT_CHANS_MIDDLE (AOUT_CHAN_MIDDLELEFT | AOUT_CHAN_MIDDLERIGHT)
AOUT_CHANS_REAR
#define AOUT_CHANS_REAR (AOUT_CHAN_REARLEFT | AOUT_CHAN_REARRIGHT)
AOUT_CHANS_STEREO
#define AOUT_CHANS_STEREO AOUT_CHANS_2_0
Referenced by aout_OutputNew().
AUDIO_REPLAY_GAIN_ALBUM
#define AUDIO_REPLAY_GAIN_ALBUM (1)
Referenced by aout_ReplayGainSelect(), and vlc_audio_replay_gain_MergeFromMeta().
AUDIO_REPLAY_GAIN_MAX
#define AUDIO_REPLAY_GAIN_MAX (2)
audio replay gain description
Referenced by aout_replaygain_changed(), aout_ReplayGainSelect(), CreateDecoder(), EsOutAddSlave(), and EsOutUpdateInfo().
AUDIO_REPLAY_GAIN_TRACK
#define AUDIO_REPLAY_GAIN_TRACK (0)
Referenced by aout_ReplayGainSelect(), EsOutUpdateInfo(), and vlc_audio_replay_gain_MergeFromMeta().
CHROMA_LOCATION_MAX
#define CHROMA_LOCATION_MAX CHROMA_LOCATION_BOTTOM_CENTER
Referenced by EsOutUpdateInfo().
COLOR_PRIMARIES_BT470_BG
#define COLOR_PRIMARIES_BT470_BG COLOR_PRIMARIES_BT601_625
COLOR_PRIMARIES_BT470_M
#define COLOR_PRIMARIES_BT470_M COLOR_PRIMARIES_FCC1953
Referenced by EsOutUpdateInfo().
COLOR_PRIMARIES_EBU_3213
#define COLOR_PRIMARIES_EBU_3213 COLOR_PRIMARIES_BT601_625
COLOR_PRIMARIES_MAX
#define COLOR_PRIMARIES_MAX COLOR_PRIMARIES_FCC1953
Referenced by EsOutUpdateInfo().
COLOR_PRIMARIES_SMTPE_170
#define COLOR_PRIMARIES_SMTPE_170 COLOR_PRIMARIES_BT601_525
COLOR_PRIMARIES_SMTPE_240
#define COLOR_PRIMARIES_SMTPE_240 COLOR_PRIMARIES_BT601_525 /* Only differs from 1e10-4 in white Y */
COLOR_PRIMARIES_SMTPE_RP145
#define COLOR_PRIMARIES_SMTPE_RP145 COLOR_PRIMARIES_BT601_525
COLOR_PRIMARIES_SRGB
#define COLOR_PRIMARIES_SRGB COLOR_PRIMARIES_BT709
COLOR_SPACE_MAX
#define COLOR_SPACE_MAX COLOR_SPACE_BT2020
Referenced by EsOutUpdateInfo().
COLOR_SPACE_SMPTE_170
#define COLOR_SPACE_SMPTE_170 COLOR_SPACE_BT601
COLOR_SPACE_SMPTE_240
#define COLOR_SPACE_SMPTE_240 COLOR_SPACE_SMPTE_170
COLOR_SPACE_SRGB
#define COLOR_SPACE_SRGB COLOR_SPACE_BT709
ES_CATEGORY_COUNT
#define ES_CATEGORY_COUNT (DATA_ES + 1)
Referenced by LoadDecoder().
ES_PRIORITY_MIN
#define ES_PRIORITY_MIN ES_PRIORITY_NOT_SELECTABLE
ES_PRIORITY_NOT_DEFAULTABLE
#define ES_PRIORITY_NOT_DEFAULTABLE -1
ES_PRIORITY_NOT_SELECTABLE
#define ES_PRIORITY_NOT_SELECTABLE -2
ES format definition.
ES_PRIORITY_SELECTABLE_MIN
#define ES_PRIORITY_SELECTABLE_MIN 0
Referenced by es_format_Init(), and EsOutSelect().
INPUT_CHAN_MAX
#define INPUT_CHAN_MAX 64
Referenced by aout_DecNew().
ORIENT_FROM_EXIF
#define ORIENT_FROM_EXIF (exif) ((0x57642310U >> (4 * ((exif) - 1))) & 7)
Convert EXIF orientation to enum video_orientation_t.
ORIENT_HFLIP
#define ORIENT_HFLIP (orient) ((orient) ^ 1)
Applies horizontal flip to an orientation.
ORIENT_IS_MIRROR
#define ORIENT_IS_MIRROR (orient) parity(orient)
If the orientation is natural or mirrored.
Referenced by transform_GetBasicOps().
ORIENT_IS_SWAP
#define ORIENT_IS_SWAP (orient) (((orient) & 4) != 0)
If the orientation swaps dimensions.
Referenced by video_format_TransformBy(), and vout_display_GetDefaultDisplaySize().
ORIENT_ROTATE_180
#define ORIENT_ROTATE_180 (orient) ((orient) ^ 3)
Applies horizontal flip to an orientation.
ORIENT_TO_EXIF
#define ORIENT_TO_EXIF (orient) ((0x76853421U >> (4 * (orient))) & 15)
Convert enum video_orientation_t to EXIF.
ORIENT_VFLIP
#define ORIENT_VFLIP (orient) ((orient) ^ 2)
Applies vertical flip to an orientation.
SPU_PALETTE_DEFINED
#define SPU_PALETTE_DEFINED 0xbeefbeef
TRANSFER_FUNC_ARIB_B67
#define TRANSFER_FUNC_ARIB_B67 TRANSFER_FUNC_HLG
TRANSFER_FUNC_BT2020
#define TRANSFER_FUNC_BT2020 TRANSFER_FUNC_BT709
TRANSFER_FUNC_MAX
#define TRANSFER_FUNC_MAX TRANSFER_FUNC_HLG
Referenced by EsOutUpdateInfo().
TRANSFER_FUNC_SMPTE_170
#define TRANSFER_FUNC_SMPTE_170 TRANSFER_FUNC_BT709
TRANSFER_FUNC_SMPTE_274
#define TRANSFER_FUNC_SMPTE_274 TRANSFER_FUNC_BT709
TRANSFER_FUNC_SMPTE_293
#define TRANSFER_FUNC_SMPTE_293 TRANSFER_FUNC_BT709
TRANSFER_FUNC_SMPTE_296
#define TRANSFER_FUNC_SMPTE_296 TRANSFER_FUNC_BT709
VIDEO_PALETTE_COLORS_MAX
#define VIDEO_PALETTE_COLORS_MAX 256
video palette data
See also
video_format_t
subs_format_t
Typedef Documentation
audio_channel_type_t
typedef enum audio_channel_type_t audio_channel_type_t
Audio channel type.
extra_languages_t
typedef struct extra_languages_t extra_languages_t
ES language definition.
video_chroma_location_t
typedef enum video_chroma_location_t video_chroma_location_t
Video chroma location.
video_color_primaries_t
typedef enum video_color_primaries_t video_color_primaries_t
Video color primaries (a.k.a.
chromacities)
video_color_space_t
typedef enum video_color_space_t video_color_space_t
Video color space (i.e.
YCbCr matrices)
video_multiview_mode_t
typedef enum video_multiview_mode_t video_multiview_mode_t
video_orientation_t
typedef enum video_orientation_t video_orientation_t
Picture orientation.
video_projection_mode_t
typedef enum video_projection_mode_t video_projection_mode_t
Video projection mode.
video_transfer_func_t
typedef enum video_transfer_func_t video_transfer_func_t
Video transfer functions.
video_transform_t
typedef enum video_transform_t video_transform_t
Enumeration Type Documentation
audio_channel_type_t
enum audio_channel_type_t
Audio channel type.
Enumerator
AUDIO_CHANNEL_TYPE_BITMAP
AUDIO_CHANNEL_TYPE_AMBISONICS
es_format_category_e
enum es_format_category_e
ES Categories.
Enumerator
UNKNOWN_ES
VIDEO_ES
AUDIO_ES
SPU_ES
DATA_ES
video_chroma_location_t
enum video_chroma_location_t
Video chroma location.
Enumerator
CHROMA_LOCATION_UNDEF
CHROMA_LOCATION_LEFT
CHROMA_LOCATION_CENTER
CHROMA_LOCATION_TOP_LEFT
CHROMA_LOCATION_TOP_CENTER
CHROMA_LOCATION_BOTTOM_LEFT
CHROMA_LOCATION_BOTTOM_CENTER
video_color_primaries_t
enum video_color_primaries_t
Video color primaries (a.k.a.
chromacities)
Enumerator
COLOR_PRIMARIES_UNDEF
COLOR_PRIMARIES_BT601_525
COLOR_PRIMARIES_BT601_625
COLOR_PRIMARIES_BT709
COLOR_PRIMARIES_BT2020
COLOR_PRIMARIES_DCI_P3
COLOR_PRIMARIES_FCC1953
video_color_space_t
enum video_color_space_t
Video color space (i.e.
YCbCr matrices)
Enumerator
COLOR_SPACE_UNDEF
COLOR_SPACE_BT601
COLOR_SPACE_BT709
COLOR_SPACE_BT2020
video_multiview_mode_t
enum video_multiview_mode_t
Enumerator
MULTIVIEW_2D
MULTIVIEW_STEREO_SBS
MULTIVIEW_STEREO_TB
MULTIVIEW_STEREO_ROW
MULTIVIEW_STEREO_COL
MULTIVIEW_STEREO_FRAME
MULTIVIEW_STEREO_CHECKERBOARD
video_orientation_t
enum video_orientation_t
Picture orientation.
Enumerator
ORIENT_TOP_LEFT
Top line represents top, left column left.
ORIENT_TOP_RIGHT
Flipped horizontally.
ORIENT_BOTTOM_LEFT
Flipped vertically.
ORIENT_BOTTOM_RIGHT
Rotated 180 degrees.
ORIENT_LEFT_TOP
Transposed.
ORIENT_LEFT_BOTTOM
Rotated 90 degrees clockwise.
ORIENT_RIGHT_TOP
Rotated 90 degrees anti-clockwise.
ORIENT_RIGHT_BOTTOM
Anti-transposed.
ORIENT_NORMAL
ORIENT_TRANSPOSED
ORIENT_ANTI_TRANSPOSED
ORIENT_HFLIPPED
ORIENT_VFLIPPED
ORIENT_ROTATED_180
ORIENT_ROTATED_270
ORIENT_ROTATED_90
video_projection_mode_t
enum video_projection_mode_t
Video projection mode.
Enumerator
PROJECTION_MODE_RECTANGULAR
PROJECTION_MODE_EQUIRECTANGULAR
PROJECTION_MODE_CUBEMAP_LAYOUT_STANDARD
video_transfer_func_t
enum video_transfer_func_t
Video transfer functions.
Enumerator
TRANSFER_FUNC_UNDEF
TRANSFER_FUNC_LINEAR
TRANSFER_FUNC_SRGB
TRANSFER_FUNC_BT470_BG
TRANSFER_FUNC_BT470_M
TRANSFER_FUNC_BT709
TRANSFER_FUNC_SMPTE_ST2084
TRANSFER_FUNC_SMPTE_240
TRANSFER_FUNC_HLG
video_transform_t
enum video_transform_t
Enumerator
TRANSFORM_IDENTITY
TRANSFORM_HFLIP
TRANSFORM_VFLIP
TRANSFORM_R180
TRANSFORM_R270
TRANSFORM_R90
TRANSFORM_TRANSPOSE
TRANSFORM_ANTI_TRANSPOSE
Function Documentation
es_format_Change()
static void es_format_Change (es_format_t * fmt, int i_cat, vlc_fourcc_t i_codec) inline static
Changes ES format to another category Format must have been properly initialized.
References es_format_Clean(), es_format_Init(), and i_codec.
es_format_Clean()
void es_format_Clean (es_format_t * fmt)
This function will clean up a es_format_t and release all associated resources.
You can call it multiple times on the same structure.
References es_format_Init(), es_format_t::i_cat, es_format_t::i_extra, es_format_t::i_extra_languages, es_format_t::p_extra, es_format_t::p_extra_languages, subs_format_t::p_style, es_format_t::psz_description, extra_languages_t::psz_description, subs_format_t::psz_encoding, es_format_t::psz_language, extra_languages_t::psz_language, SPU_ES, es_format_t::subs, text_style_Delete(), UNKNOWN_ES, es_format_t::video, VIDEO_ES, and video_format_Clean().
Referenced by CmdCleanAdd(), CmdCleanControl(), DecoderUpdateFormatLocked(), DeleteDecoder(), DeleteDecoder(), DeleteEncoder(), DeleteFilter(), demux_PacketizerDestroy(), demux_PacketizerNew(), es_format_Change(), EsOutControlLocked(), EsOutCreateCCChannels(), EsOutDel(), EsOutSend(), EsOutTerminate(), filter_chain_AppendInner(), filter_chain_Delete(), filter_chain_DeleteFilter(), filter_chain_Reset(), input_item_Release(), input_item_UpdateTracksInfo(), LoadDecoder(), ReloadDecoder(), sout_MuxAddStream(), sout_MuxDeleteStream(), ThreadChangeFilters(), UnloadDecoder(), and VoutDisplayCreateRender().
es_format_Copy()
int es_format_Copy (es_format_t * p_dst, const es_format_t * p_src)
This functions will copy a es_format_t.
es_format_Init()
void es_format_Init (es_format_t * fmt, int i_cat, vlc_fourcc_t i_codec)
This function will initialize a es_format_t structure.
References es_format_t::b_packetized, ES_PRIORITY_SELECTABLE_MIN, es_format_t::i_cat, es_format_t::i_codec, i_codec, es_format_t::i_id, es_format_t::i_level, es_format_t::i_priority, es_format_t::i_profile, es_format_t::p_extra, es_format_t::p_extra_languages, es_format_t::psz_description, es_format_t::psz_language, es_format_t::video, VIDEO_ES, and video_format_Init().
Referenced by CreateDecoder(), CreateDecoder(), demux_PacketizerNew(), es_format_Change(), es_format_Clean(), es_format_InitFromVideo(), EsOutCreateCCChannels(), filter_chain_NewInner(), filter_NewBlend(), ImageConvert(), ImageWrite(), input_DecoderSetCcState(), LoadDecoder(), SpuRenderCreateAndLoadScale(), SpuRenderCreateAndLoadText(), and vlm_OnMediaUpdate().
es_format_InitFromVideo()
void es_format_InitFromVideo (es_format_t * p_es, const video_format_t * p_fmt)
This function will initialize a es_format_t structure from a video_format_t.
References es_format_Init(), video_format_t::i_chroma, es_format_t::video, VIDEO_ES, and video_format_Copy().
Referenced by CreateDecoder(), CreateEncoder(), ThreadChangeFilters(), and VoutDisplayCreateRender().
es_format_IsSimilar()
bool es_format_IsSimilar (const es_format_t * p_fmt1, const es_format_t * p_fmt2)
This function will check if the first ES format is similar to the second one.
All descriptive fields are ignored.
References es_format_t::audio, AUDIO_ES, audio_format_t::channel_type, es_format_t::i_cat, audio_format_t::i_chan_mode, audio_format_t::i_channels, video_format_t::i_chroma, es_format_t::i_codec, audio_format_t::i_format, audio_format_t::i_physical_channels, es_format_t::i_profile, audio_format_t::i_rate, SPU_ES, es_format_t::video, VIDEO_ES, video_format_IsSimilar(), and vlc_fourcc_GetCodec().
Referenced by DecoderProcess(), and ThreadChangeFilters().
transform_Inverse()
static video_transform_t transform_Inverse (video_transform_t transform) inline static
References transform(), TRANSFORM_R270, and TRANSFORM_R90.
Referenced by video_format_GetTransform().
video_format_AdjustColorSpace()
static void video_format_AdjustColorSpace (video_format_t * p_fmt) inline static
References COLOR_PRIMARIES_BT601_525, COLOR_PRIMARIES_BT601_625, COLOR_PRIMARIES_BT709, COLOR_PRIMARIES_UNDEF, COLOR_SPACE_BT601, COLOR_SPACE_BT709, COLOR_SPACE_UNDEF, video_format_t::i_visible_height, video_format_t::primaries, video_format_t::space, video_format_t::transfer, TRANSFER_FUNC_BT709, TRANSFER_FUNC_SRGB, and TRANSFER_FUNC_UNDEF.
Referenced by SpuRenderRegion(), and vout_update_format().
video_format_ApplyRotation()
void video_format_ApplyRotation (video_format_t * out, const video_format_t * in)
This function "normalizes" the formats orientation, by switching the a/r according to the orientation, producing a format whose orientation is ORIENT_NORMAL.
It makes a shallow copy (pallette is not alloc'ed).
video_format_Clean()
static void video_format_Clean (video_format_t * p_src) inline static
Cleanup and free palette of this video_format_t.
Parameters
p_src video_format_t structure to clean
References video_format_t::p_palette.
Referenced by es_format_Clean(), ImageRead(), subpicture_Delete(), subpicture_region_Delete(), subpicture_region_New(), subpicture_region_private_Delete(), subpicture_Update(), ThreadChangeFilters(), ThreadReinit(), ThreadStart(), ThreadStop(), video_splitter_Delete(), vout_display_Delete(), VoutCreate(), and VoutDestructor().
video_format_Copy()
static int video_format_Copy (video_format_t * p_dst, const video_format_t * p_src) inline static
Copy video_format_t including the palette.
Parameters
p_dst video_format_t to copy to
p_src video_format_t to copy from
< Not enough memory
< No error
References video_format_t::p_palette, VLC_ENOMEM, and VLC_SUCCESS.
Referenced by CreateFilter(), es_format_Copy(), es_format_InitFromVideo(), ImageRead(), subpicture_region_New(), subpicture_region_private_New(), subpicture_Update(), ThreadChangeFilters(), ThreadStart(), video_splitter_New(), vout_display_New(), and VoutValidateFormat().
video_format_CopyCrop()
void video_format_CopyCrop (video_format_t * p_dst, const video_format_t * p_src)
It will copy the crop properties from a video_format_t to another.
References video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_x_offset, and video_format_t::i_y_offset.
Referenced by picture_NewFromResource(), VideoFormatCopyCropAr(), vout_snapshot_Set(), and vout_UpdateDisplaySourceProperties().
video_format_FixRgb()
void video_format_FixRgb (video_format_t * p_fmt)
This function will fill all RGB shift from RGB masks.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_lbshift, video_format_t::i_lgshift, video_format_t::i_lrshift, video_format_t::i_rbshift, video_format_t::i_rgshift, video_format_t::i_rmask, video_format_t::i_rrshift, MaskToShift(), VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, and VLC_CODEC_RGB32.
Referenced by BitMapFormatIsSimilar(), ConvertRGB32AndBlend(), video_format_IsSimilar(), and VoutValidateFormat().
video_format_GetTransform()
video_transform_t video_format_GetTransform (video_orientation_t src, video_orientation_t dst)
Returns the operation required to transform src into dst.
References transform_FromBasicOps(), transform_GetBasicOps(), and transform_Inverse().
Referenced by video_format_TransformTo(), and vout_display_SendMouseMovedDisplayCoordinates().
video_format_Init()
static void video_format_Init (video_format_t * p_src, vlc_fourcc_t i_chroma) inline static
Initialize a video_format_t structure with chroma 'i_chroma'.
Parameters
p_src pointer to video_format_t structure
i_chroma chroma value to use
References video_format_t::i_chroma, video_format_t::pose, and vlc_viewpoint_init().
Referenced by es_format_Init(), OSDRegion(), OSDTextUpdate(), picture_New(), spuregion_CreateFromPicture(), subpicture_New(), vout_OSDBackground(), vout_OSDEpgSlider(), vout_OSDImage(), and vout_OSDTextRegion().
video_format_IsSimilar()
bool video_format_IsSimilar (const video_format_t * f1, const video_format_t * f2)
This function will check if the first video format is similar to the second one.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_height, video_format_t::i_rmask, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, video_format_t::multiview_mode, video_format_t::orientation, video_format_FixRgb(), VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, and VLC_CODEC_RGB32.
Referenced by es_format_IsSimilar(), subpicture_Update(), and ThreadReinit().
video_format_Print()
void video_format_Print (vlc_object_t * p_this, const char * psz_text, const video_format_t * fmt)
It prints details about the given video_format_t.
References video_format_t::i_bmask, video_format_t::i_chroma, video_format_t::i_gmask, video_format_t::i_height, video_format_t::i_rmask, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, and msg_Dbg.
Referenced by ThreadStart(), and vout_ManageDisplay().
video_format_ScaleCropAr()
void video_format_ScaleCropAr (video_format_t * p_dst, const video_format_t * p_src)
It will compute the crop/ar properties when scaling.
References video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, and vlc_ureduce().
video_format_Setup()
void video_format_Setup (video_format_t * p_fmt, vlc_fourcc_t i_chroma, int i_width, int i_height, int i_visible_width, int i_visible_height, int i_sar_num, int i_sar_den)
It will fill up a video_format_t using the given arguments.
Note that the video_format_t must already be initialized.
References video_format_t::i_bits_per_pixel, video_format_t::i_chroma, video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, VIDEO_ES, VLC_CODEC_ARGB, VLC_CODEC_BGRA, VLC_CODEC_GREY, VLC_CODEC_I410, VLC_CODEC_I411, VLC_CODEC_I420, VLC_CODEC_I422, VLC_CODEC_I440, VLC_CODEC_I444, VLC_CODEC_J420, VLC_CODEC_J422, VLC_CODEC_J440, VLC_CODEC_J444, VLC_CODEC_NV12, VLC_CODEC_P010, VLC_CODEC_RGB15, VLC_CODEC_RGB16, VLC_CODEC_RGB24, VLC_CODEC_RGB32, VLC_CODEC_RGB8, VLC_CODEC_RGBA, VLC_CODEC_RGBP, VLC_CODEC_UYVY, VLC_CODEC_VYUY, VLC_CODEC_XYZ12, VLC_CODEC_Y211, VLC_CODEC_YUV420A, VLC_CODEC_YUV422A, VLC_CODEC_YUVA, VLC_CODEC_YUVP, VLC_CODEC_YUYV, VLC_CODEC_YV12, VLC_CODEC_YV9, VLC_CODEC_YVYU, vlc_fourcc_GetCodec(), and vlc_ureduce().
Referenced by picture_New(), picture_NewFromResource(), and picture_Setup().
video_format_TransformBy()
void video_format_TransformBy (video_format_t * fmt, video_transform_t transform)
This function applies the transform operation to fmt.
References video_format_t::i_height, video_format_t::i_sar_den, video_format_t::i_sar_num, video_format_t::i_visible_height, video_format_t::i_visible_width, video_format_t::i_width, video_format_t::i_x_offset, video_format_t::i_y_offset, ORIENT_ANTI_TRANSPOSED, ORIENT_HFLIPPED, ORIENT_IS_SWAP, ORIENT_NORMAL, ORIENT_ROTATED_180, ORIENT_ROTATED_270, ORIENT_ROTATED_90, ORIENT_TRANSPOSED, ORIENT_VFLIPPED, video_format_t::orientation, transform(), and transform_GetBasicOps().
Referenced by video_format_TransformTo().
video_format_TransformTo()
void video_format_TransformTo (video_format_t * fmt, video_orientation_t dst_orientation)
This function applies the transforms necessary to fmt so that the resulting fmt has the dst_orientation.