VLC: src/input/vlm_event.c File Reference
vlm_event.c File Reference
Functions
static void Trigger (vlm_t *, int i_type, int64_t id, const char *psz_name)
static void TriggerInstanceState (vlm_t *, int i_type, int64_t id, const char *psz_name, const char *psz_instance_name, input_state_e input_state)
void vlm_SendEventMediaAdded (vlm_t *p_vlm, int64_t id, const char *psz_name)
void vlm_SendEventMediaRemoved (vlm_t *p_vlm, int64_t id, const char *psz_name)
void vlm_SendEventMediaChanged (vlm_t *p_vlm, int64_t id, const char *psz_name)
void vlm_SendEventMediaInstanceStarted (vlm_t *p_vlm, int64_t id, const char *psz_name)
void vlm_SendEventMediaInstanceStopped (vlm_t *p_vlm, int64_t id, const char *psz_name)
void vlm_SendEventMediaInstanceState (vlm_t *p_vlm, int64_t id, const char *psz_name, const char *psz_instance_name, input_state_e state)
Function Documentation
Trigger()
static void Trigger (vlm_t * p_vlm, int i_type, int64_t id, const char * psz_name) static
References i_type, vlm_event_t::i_type, psz_name, and var_SetAddress.
Referenced by vlm_SendEventMediaAdded(), vlm_SendEventMediaChanged(), vlm_SendEventMediaInstanceStarted(), vlm_SendEventMediaInstanceStopped(), and vlm_SendEventMediaRemoved().
TriggerInstanceState()
static void TriggerInstanceState (vlm_t * p_vlm, int i_type, int64_t id, const char * psz_name, const char * psz_instance_name, input_state_e input_state) static
References i_type, vlm_event_t::i_type, psz_name, and var_SetAddress.
Referenced by vlm_SendEventMediaInstanceState().
vlm_SendEventMediaAdded()
void vlm_SendEventMediaAdded (vlm_t * p_vlm, int64_t id, const char * psz_name)
References psz_name, Trigger(), and VLM_EVENT_MEDIA_ADDED.
Referenced by vlm_ControlMediaAdd().
vlm_SendEventMediaChanged()
void vlm_SendEventMediaChanged (vlm_t * p_vlm, int64_t id, const char * psz_name)
References psz_name, Trigger(), and VLM_EVENT_MEDIA_CHANGED.
Referenced by vlm_OnMediaUpdate().
vlm_SendEventMediaInstanceStarted()
void vlm_SendEventMediaInstanceStarted (vlm_t * p_vlm, int64_t id, const char * psz_name)
References psz_name, Trigger(), and VLM_EVENT_MEDIA_INSTANCE_STARTED.
Referenced by vlm_ControlMediaInstanceStart().
vlm_SendEventMediaInstanceState()
void vlm_SendEventMediaInstanceState (vlm_t * p_vlm, int64_t id, const char * psz_name, const char * psz_instance_name, input_state_e state)
References psz_name, TriggerInstanceState(), and VLM_EVENT_MEDIA_INSTANCE_STATE.
Referenced by InputEvent().
vlm_SendEventMediaInstanceStopped()
void vlm_SendEventMediaInstanceStopped (vlm_t * p_vlm, int64_t id, const char * psz_name)
References psz_name, Trigger(), and VLM_EVENT_MEDIA_INSTANCE_STOPPED.
Referenced by vlm_ControlMediaInstanceStart(), and vlm_MediaInstanceDelete().
vlm_SendEventMediaRemoved()
void vlm_SendEventMediaRemoved (vlm_t * p_vlm, int64_t id, const char * psz_name)
References psz_name, Trigger(), and VLM_EVENT_MEDIA_REMOVED.
Referenced by vlm_ControlMediaDel().