VLC: src/input/vlm.c File Reference
vlm.c File Reference
Data Structures
struct preparse_data_t
Typedefs
typedef struct preparse_data_t preparse_data_t
Functions
static void * Manage (void *)
static int vlm_MediaVodControl (void *, vod_media_t *, const char *, int, va_list)
static int InputEventPreparse (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
static int InputEvent (vlc_object_t *p_this, char const *psz_cmd, vlc_value_t oldval, vlc_value_t newval, void *p_data)
vlm_t * vlm_New (vlc_object_t *p_this)
void vlm_Delete (vlm_t *p_vlm)
int vlm_ExecuteCommand (vlm_t *p_vlm, const char *psz_command, vlm_message_t **pp_message)
static vlm_media_sys_t * vlm_ControlMediaGetById (vlm_t *p_vlm, int64_t id)
static vlm_media_sys_t * vlm_ControlMediaGetByName (vlm_t *p_vlm, const char *psz_name)
static int vlm_MediaDescriptionCheck (vlm_t *p_vlm, vlm_media_t *p_cfg)
static int vlm_OnMediaUpdate (vlm_t *p_vlm, vlm_media_sys_t *p_media)
static int vlm_ControlMediaChange (vlm_t *p_vlm, vlm_media_t *p_cfg)
static int vlm_ControlMediaAdd (vlm_t *p_vlm, vlm_media_t *p_cfg, int64_t *p_id)
static int vlm_ControlMediaDel (vlm_t *p_vlm, int64_t id)
static int vlm_ControlMediaGets (vlm_t *p_vlm, vlm_media_t ***ppp_dsc, int *pi_dsc)
static int vlm_ControlMediaClear (vlm_t *p_vlm)
static int vlm_ControlMediaGet (vlm_t *p_vlm, int64_t id, vlm_media_t **pp_dsc)
static int vlm_ControlMediaGetId (vlm_t *p_vlm, const char *psz_name, int64_t *p_id)
static vlm_media_instance_sys_t * vlm_ControlMediaInstanceGetByName (vlm_media_sys_t *p_media, const char *psz_id)
static vlm_media_instance_sys_t * vlm_MediaInstanceNew (vlm_t *p_vlm, const char *psz_name)
static void vlm_MediaInstanceDelete (vlm_t *p_vlm, int64_t id, vlm_media_instance_sys_t *p_instance, vlm_media_sys_t *p_media)
static int vlm_ControlMediaInstanceStart (vlm_t *p_vlm, int64_t id, const char *psz_id, int i_input_index, const char *psz_vod_output)
static int vlm_ControlMediaInstanceStop (vlm_t *p_vlm, int64_t id, const char *psz_id)
static int vlm_ControlMediaInstancePause (vlm_t *p_vlm, int64_t id, const char *psz_id)
static int vlm_ControlMediaInstanceGetTimePosition (vlm_t *p_vlm, int64_t id, const char *psz_id, int64_t *pi_time, double *pd_position)
static int vlm_ControlMediaInstanceSetTimePosition (vlm_t *p_vlm, int64_t id, const char *psz_id, int64_t i_time, double d_position)
static int vlm_ControlMediaInstanceGets (vlm_t *p_vlm, int64_t id, vlm_media_instance_t ***ppp_idsc, int *pi_instance)
static int vlm_ControlMediaInstanceClear (vlm_t *p_vlm, int64_t id)
static int vlm_ControlScheduleClear (vlm_t *p_vlm)
static int vlm_vaControlInternal (vlm_t *p_vlm, int i_query, va_list args)
int vlm_ControlInternal (vlm_t *p_vlm, int i_query,...)
int vlm_Control (vlm_t *p_vlm, int i_query,...)
Variables
static vlc_mutex_t vlm_mutex = PTHREAD_MUTEX_INITIALIZER
Typedef Documentation
preparse_data_t
typedef struct preparse_data_t preparse_data_t
Function Documentation
InputEvent()
static int InputEvent (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlm_media_sys_t::cfg, vlm_media_sys_t::i_instance, vlc_value_t::i_int, vlm_media_t::id, INPUT_EVENT_STATE, vlm_t::input_state_changed, vlm_media_sys_t::instance, vlc_common_members::libvlc, libvlc_priv(), vlm_t::lock_manage, input_thread_t::obj, vlm_media_instance_sys_t::p_input, libvlc_priv_t::p_vlm, vlm_media_instance_sys_t::psz_name, vlm_media_t::psz_name, var_GetInteger, vlc_cond_signal(), vlc_mutex_lock(), vlc_mutex_unlock(), VLC_SUCCESS, VLC_UNUSED, vlm_SendEventMediaInstanceState(), and vlm_t::wait_manage.
Referenced by vlm_ControlMediaInstanceStart().
InputEventPreparse()
static int InputEventPreparse (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References preparse_data_t::b_mux, vlc_value_t::i_int, INPUT_EVENT_DEAD, INPUT_EVENT_ITEM_META, preparse_data_t::p_sem, vlc_sem_post(), VLC_SUCCESS, and VLC_UNUSED.
Referenced by vlm_OnMediaUpdate().
Manage()
static void * Manage (void * p_object) static
References vlm_schedule_sys_t::b_enabled, vlm_media_t::b_loop, vlm_media_t::b_vod, vlm_media_t::broadcast, vlm_media_sys_t::cfg, vlm_schedule_sys_t::command, vlm_schedule_sys_t::date, END_S, ERROR_S, ExecuteCommand(), vlm_schedule_sys_t::i_command, vlm_media_instance_sys_t::i_index, vlm_media_t::i_input, vlm_media_sys_t::i_instance, vlm_t::i_media, vlm_schedule_sys_t::i_repeat, vlm_t::i_schedule, vlm_media_t::id, INIT_S, vlm_t::input_state_changed, vlm_media_sys_t::instance, vlm_t::lock, vlm_t::lock_manage, vlm_t::media, mutex_cleanup_push, vlm_media_instance_sys_t::p_input, vlm_schedule_sys_t::period, vlm_media_instance_sys_t::psz_name, vlm_t::schedule, strdup(), TAB_APPEND, TAB_REMOVE, var_GetInteger, vlc_cleanup_pop, vlc_cond_timedwait_daytime(), vlc_cond_wait(), vlc_mutex_lock(), vlc_mutex_unlock(), vlc_restorecancel(), vlc_savecancel(), vlm_ControlInternal(), vlm_MessageDelete(), VLM_START_MEDIA_BROADCAST_INSTANCE, VLM_STOP_MEDIA_INSTANCE, and vlm_t::wait_manage.
Referenced by vlm_New().
vlm_ControlInternal()
int vlm_ControlInternal (vlm_t * p_vlm, int i_query, ...)
References vlm_vaControlInternal().
Referenced by Manage(), vlm_ControlMediaDel(), vlm_Delete(), and vlm_MediaVodControl().
vlm_ControlMediaAdd()
static int vlm_ControlMediaAdd (vlm_t * p_vlm, vlm_media_t * p_cfg, int64_t * p_id) static
< Unspecified error
< Unspecified error
< Not enough memory
References vlm_media_t::b_vod, vlm_media_sys_t::cfg, vlm_t::i_id, vlm_media_sys_t::i_instance, vlm_t::i_media, vlm_media_t::id, input_item_New, vlm_media_sys_t::instance, vlm_t::media, module_need, msg_Err, vod_t::p_data, vlm_media_sys_t::p_item, vlm_media_sys_t::p_media, vod_t::p_module, vlm_t::p_vod, vod_t::pf_media_control, vlm_media_t::psz_name, TAB_APPEND, TAB_INIT, vlc_custom_create, VLC_EGENERIC, VLC_ENOMEM, VLC_OBJECT, vlc_object_release, vlm_ControlMediaGetByName(), vlm_media_Copy(), vlm_MediaDescriptionCheck(), vlm_MediaVodControl(), vlm_OnMediaUpdate(), vlm_SendEventMediaAdded(), and vlm_media_sys_t::vod.
Referenced by vlm_vaControlInternal().
vlm_ControlMediaChange()
static int vlm_ControlMediaChange (vlm_t * p_vlm, vlm_media_t * p_cfg) static
< Unspecified error
< Unspecified error
References vlm_media_t::b_vod, vlm_media_sys_t::cfg, vlm_media_t::id, VLC_EGENERIC, vlm_ControlMediaGetById(), vlm_media_Clean(), vlm_media_Copy(), vlm_MediaDescriptionCheck(), and vlm_OnMediaUpdate().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaClear()
static int vlm_ControlMediaClear (vlm_t * p_vlm) static
< No error
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_media_t::id, vlm_t::media, VLC_SUCCESS, and vlm_ControlMediaDel().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaDel()
static int vlm_ControlMediaDel (vlm_t * p_vlm, int64_t id) static
< Unspecified error
< No error
References vlm_media_t::b_enabled, vlm_media_t::b_vod, vlm_media_sys_t::cfg, vlm_media_sys_t::i_instance, vlm_t::i_media, input_item_Release(), vlm_media_sys_t::instance, vlm_t::media, vlm_media_sys_t::p_item, vlm_media_sys_t::p_media, vlm_t::p_vod, vod_t::pf_media_del, vlm_media_instance_sys_t::psz_name, vlm_media_t::psz_name, TAB_REMOVE, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlInternal(), vlm_ControlMediaGetById(), vlm_media_Clean(), vlm_OnMediaUpdate(), vlm_SendEventMediaRemoved(), VLM_STOP_MEDIA_INSTANCE, and vlm_media_sys_t::vod.
Referenced by vlm_ControlMediaClear(), and vlm_vaControlInternal().
vlm_ControlMediaGet()
static int vlm_ControlMediaGet (vlm_t * p_vlm, int64_t id, vlm_media_t ** pp_dsc) static
< Unspecified error
< No error
References vlm_media_sys_t::cfg, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), and vlm_media_Duplicate().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaGetById()
static vlm_media_sys_t * vlm_ControlMediaGetById (vlm_t * p_vlm, int64_t id) static
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_media_t::id, and vlm_t::media.
Referenced by vlm_ControlMediaChange(), vlm_ControlMediaDel(), vlm_ControlMediaGet(), vlm_ControlMediaInstanceClear(), vlm_ControlMediaInstanceGets(), vlm_ControlMediaInstanceGetTimePosition(), vlm_ControlMediaInstancePause(), vlm_ControlMediaInstanceSetTimePosition(), vlm_ControlMediaInstanceStart(), and vlm_ControlMediaInstanceStop().
vlm_ControlMediaGetByName()
static vlm_media_sys_t * vlm_ControlMediaGetByName (vlm_t * p_vlm, const char * psz_name) static
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_t::media, psz_name, and vlm_media_t::psz_name.
Referenced by vlm_ControlMediaAdd(), and vlm_ControlMediaGetId().
vlm_ControlMediaGetId()
static int vlm_ControlMediaGetId (vlm_t * p_vlm, const char * psz_name, int64_t * p_id) static
< Unspecified error
< No error
References vlm_media_sys_t::cfg, vlm_media_t::id, psz_name, VLC_EGENERIC, VLC_SUCCESS, and vlm_ControlMediaGetByName().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaGets()
static int vlm_ControlMediaGets (vlm_t * p_vlm, vlm_media_t *** ppp_dsc, int * pi_dsc) static
< No error
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_t::media, TAB_APPEND, TAB_INIT, VLC_SUCCESS, and vlm_media_Duplicate().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceClear()
static int vlm_ControlMediaInstanceClear (vlm_t * p_vlm, int64_t id) static
< Unspecified error
< No error
References vlm_media_sys_t::i_instance, vlm_media_sys_t::instance, vlm_media_instance_sys_t::psz_name, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), and vlm_ControlMediaInstanceStop().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceGetByName()
static vlm_media_instance_sys_t * vlm_ControlMediaInstanceGetByName (vlm_media_sys_t * p_media, const char * psz_id) static
References vlm_media_sys_t::i_instance, vlm_media_sys_t::instance, and vlm_media_instance_sys_t::psz_name.
Referenced by vlm_ControlMediaInstanceGetTimePosition(), vlm_ControlMediaInstancePause(), vlm_ControlMediaInstanceSetTimePosition(), vlm_ControlMediaInstanceStart(), and vlm_ControlMediaInstanceStop().
vlm_ControlMediaInstanceGets()
static int vlm_ControlMediaInstanceGets (vlm_t * p_vlm, int64_t id, vlm_media_instance_t *** ppp_idsc, int * pi_instance) static
< Unspecified error
< No error
References vlm_media_instance_t::b_paused, vlm_media_instance_t::d_position, vlm_media_sys_t::i_instance, vlm_media_instance_t::i_length, vlm_media_instance_t::i_rate, vlm_media_instance_t::i_time, INPUT_RATE_DEFAULT, vlm_media_sys_t::instance, vlm_media_instance_sys_t::p_input, PAUSE_S, vlm_media_instance_sys_t::psz_name, vlm_media_instance_t::psz_name, strdup(), TAB_APPEND, TAB_INIT, var_GetFloat, var_GetInteger, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), and vlm_media_instance_New().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceGetTimePosition()
static int vlm_ControlMediaInstanceGetTimePosition (vlm_t * p_vlm, int64_t id, const char * psz_id, int64_t * pi_time, double * pd_position) static
< Unspecified error
< Unspecified error
< No error
References vlm_media_instance_sys_t::p_input, var_GetFloat, var_GetInteger, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), and vlm_ControlMediaInstanceGetByName().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstancePause()
static int vlm_ControlMediaInstancePause (vlm_t * p_vlm, int64_t id, const char * psz_id) static
< Unspecified error
< Unspecified error
< No error
References vlm_media_t::b_vod, vlm_media_sys_t::cfg, vlm_media_instance_sys_t::p_input, PAUSE_S, PLAYING_S, var_GetInteger, var_SetInteger, VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), and vlm_ControlMediaInstanceGetByName().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceSetTimePosition()
static int vlm_ControlMediaInstanceSetTimePosition (vlm_t * p_vlm, int64_t id, const char * psz_id, int64_t i_time, double d_position) static
< Unspecified error
< Unspecified error
< Unspecified error
References vlm_media_instance_sys_t::p_input, var_SetFloat, var_SetInteger, VLC_EGENERIC, vlm_ControlMediaGetById(), and vlm_ControlMediaInstanceGetByName().
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceStart()
static int vlm_ControlMediaInstanceStart (vlm_t * p_vlm, int64_t id, const char * psz_id, int i_input_index, const char * psz_vod_output) static
< Unspecified error
< Unspecified error
< Unspecified error
< Not enough memory
< No error
< No error
< No error
References _, asprintf(), vlm_media_t::b_enabled, vlm_media_instance_sys_t::b_sout_keep, vlm_media_t::b_vod, vlm_media_sys_t::cfg, vlm_media_instance_sys_t::i_index, vlm_media_t::i_input, vlm_media_sys_t::i_instance, vlm_media_t::i_option, input_Close(), input_Create, input_item_AddOption(), input_item_SetURI(), input_resource_TerminateSout(), input_resource_TerminateVout(), input_Start(), input_Stop(), InputEvent(), vlm_media_sys_t::instance, vlm_media_instance_sys_t::p_input, vlm_media_instance_sys_t::p_input_resource, vlm_media_instance_sys_t::p_item, vlm_media_sys_t::p_media, vlm_media_instance_sys_t::p_parent, PAUSE_S, PLAYING_S, vlm_media_t::ppsz_input, vlm_media_t::ppsz_option, vlm_media_t::psz_name, vlm_media_t::psz_output, TAB_APPEND, var_AddCallback, var_Create, var_DelCallback, var_GetInteger, var_SetAddress, var_SetInteger, var_SetString, VLC_EGENERIC, VLC_ENOMEM, VLC_INPUT_OPTION_TRUSTED, vlc_path2uri(), VLC_SUCCESS, VLC_VAR_ADDRESS, VLC_VAR_STRING, vlm_ControlMediaGetById(), vlm_ControlMediaInstanceGetByName(), vlm_MediaInstanceDelete(), vlm_MediaInstanceNew(), vlm_SendEventMediaInstanceStarted(), vlm_SendEventMediaInstanceStopped(), and vlm_media_sys_t::vod.
Referenced by vlm_vaControlInternal().
vlm_ControlMediaInstanceStop()
static int vlm_ControlMediaInstanceStop (vlm_t * p_vlm, int64_t id, const char * psz_id) static
< Unspecified error
< Unspecified error
< No error
References VLC_EGENERIC, VLC_SUCCESS, vlm_ControlMediaGetById(), vlm_ControlMediaInstanceGetByName(), and vlm_MediaInstanceDelete().
Referenced by vlm_ControlMediaInstanceClear(), and vlm_vaControlInternal().
vlm_ControlScheduleClear()
static int vlm_ControlScheduleClear (vlm_t * p_vlm) static
< No error
References vlm_t::i_schedule, vlm_t::schedule, VLC_SUCCESS, and vlm_ScheduleDelete().
Referenced by vlm_vaControlInternal().
vlm_MediaDescriptionCheck()
static int vlm_MediaDescriptionCheck (vlm_t * p_vlm, vlm_media_t * p_cfg) static
< Unspecified error
< Unspecified error
< No error
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_media_t::id, vlm_t::media, vlm_media_t::psz_name, VLC_EGENERIC, and VLC_SUCCESS.
Referenced by vlm_ControlMediaAdd(), and vlm_ControlMediaChange().
vlm_MediaInstanceDelete()
static void vlm_MediaInstanceDelete (vlm_t * p_vlm, int64_t id, vlm_media_instance_sys_t * p_instance, vlm_media_sys_t * p_media) static
References vlm_media_sys_t::cfg, vlm_media_sys_t::i_instance, input_Close(), input_item_Release(), input_resource_Release(), input_resource_Terminate(), input_Stop(), vlm_media_sys_t::instance, vlm_media_instance_sys_t::p_input, vlm_media_instance_sys_t::p_input_resource, vlm_media_instance_sys_t::p_item, vlm_media_instance_sys_t::p_parent, vlm_media_instance_sys_t::psz_name, vlm_media_t::psz_name, TAB_REMOVE, vlc_object_release, and vlm_SendEventMediaInstanceStopped().
Referenced by vlm_ControlMediaInstanceStart(), and vlm_ControlMediaInstanceStop().
vlm_MediaInstanceNew()
static vlm_media_instance_sys_t * vlm_MediaInstanceNew (vlm_t * p_vlm, const char * psz_name) static
References vlm_media_instance_sys_t::b_sout_keep, vlm_media_instance_sys_t::i_index, input_item_New, input_resource_New(), vlm_media_instance_sys_t::p_input, vlm_media_instance_sys_t::p_input_resource, vlm_media_instance_sys_t::p_item, vlm_media_instance_sys_t::p_parent, psz_name, vlm_media_instance_sys_t::psz_name, strdup(), and vlc_object_create.
Referenced by vlm_ControlMediaInstanceStart().
vlm_MediaVodControl()
static int vlm_MediaVodControl (void * p_private, vod_media_t * p_vod_media, const char * psz_id, int i_query, va_list args) static
< Unspecified error
< Unspecified error
< Unspecified error
References vlm_media_sys_t::cfg, vlm_t::i_media, vlm_media_t::id, vlm_t::lock, vlm_t::media, vlm_media_sys_t::p_media, VLC_EGENERIC, vlc_mutex_lock(), vlc_mutex_unlock(), vlm_ControlInternal(), VLM_GET_MEDIA_INSTANCE_POSITION, VLM_GET_MEDIA_INSTANCE_TIME, VLM_PAUSE_MEDIA_INSTANCE, VLM_SET_MEDIA_INSTANCE_POSITION, VLM_SET_MEDIA_INSTANCE_TIME, VLM_START_MEDIA_VOD_INSTANCE, VLM_STOP_MEDIA_INSTANCE, vlm_media_sys_t::vod, VOD_MEDIA_FORWARD, VOD_MEDIA_PAUSE, VOD_MEDIA_PLAY, VOD_MEDIA_REWIND, VOD_MEDIA_SEEK, and VOD_MEDIA_STOP.
Referenced by vlm_ControlMediaAdd().
vlm_OnMediaUpdate()
static int vlm_OnMediaUpdate (vlm_t * p_vlm, vlm_media_sys_t * p_media) static
< No error
References _, asprintf(), vlm_media_t::b_enabled, vlm_media_t::b_vod, vlm_media_sys_t::cfg, input_item_t::es, sout_description_data_t::es, es_format_Init(), input_item_t::i_es, sout_description_data_t::i_es, vlm_media_t::i_input, vlm_media_t::i_option, vlm_media_t::id, input_Close(), input_Create, input_item_AddOption(), input_item_New, input_item_Release(), input_Start(), input_Stop(), InputEventPreparse(), msg_Err, vlm_media_sys_t::p_item, vlm_media_sys_t::p_media, preparse_data_t::p_sem, vlm_t::p_vod, vod_t::pf_media_del, vod_t::pf_media_new, vlm_media_t::ppsz_input, vlm_media_t::ppsz_option, vlm_media_t::psz_mux, vlm_media_t::psz_name, vlm_media_t::psz_output, sout_description_data_t::sem, strdup(), TAB_CLEAN, TAB_INIT, var_AddCallback, var_Create, var_DelCallback, var_SetAddress, VIDEO_ES, VLC_INPUT_OPTION_TRUSTED, vlc_path2uri(), vlc_sem_destroy(), vlc_sem_init(), vlc_sem_wait(), VLC_SUCCESS, VLC_VAR_ADDRESS, vlm_SendEventMediaChanged(), vlm_media_sys_t::vod, and vlm_media_t::vod.
Referenced by vlm_ControlMediaAdd(), vlm_ControlMediaChange(), and vlm_ControlMediaDel().
vlm_vaControlInternal()
static int vlm_vaControlInternal (vlm_t * p_vlm, int i_query, va_list args) static
< Unspecified error
< Unspecified error
References msg_Err, VLC_EGENERIC, VLM_ADD_MEDIA, VLM_CHANGE_MEDIA, VLM_CLEAR_MEDIA_INSTANCES, VLM_CLEAR_MEDIAS, VLM_CLEAR_SCHEDULES, vlm_ControlMediaAdd(), vlm_ControlMediaChange(), vlm_ControlMediaClear(), vlm_ControlMediaDel(), vlm_ControlMediaGet(), vlm_ControlMediaGetId(), vlm_ControlMediaGets(), vlm_ControlMediaInstanceClear(), vlm_ControlMediaInstanceGets(), vlm_ControlMediaInstanceGetTimePosition(), vlm_ControlMediaInstancePause(), vlm_ControlMediaInstanceSetTimePosition(), vlm_ControlMediaInstanceStart(), vlm_ControlMediaInstanceStop(), vlm_ControlScheduleClear(), VLM_DEL_MEDIA, VLM_GET_MEDIA, VLM_GET_MEDIA_ID, VLM_GET_MEDIA_INSTANCE_POSITION, VLM_GET_MEDIA_INSTANCE_TIME, VLM_GET_MEDIA_INSTANCES, VLM_GET_MEDIAS, VLM_PAUSE_MEDIA_INSTANCE, VLM_SET_MEDIA_INSTANCE_POSITION, VLM_SET_MEDIA_INSTANCE_TIME, VLM_START_MEDIA_BROADCAST_INSTANCE, VLM_START_MEDIA_VOD_INSTANCE, and VLM_STOP_MEDIA_INSTANCE.
Referenced by vlm_Control(), and vlm_ControlInternal().
Variable Documentation
vlm_mutex
vlc_mutex_t vlm_mutex = PTHREAD_MUTEX_INITIALIZER static
Referenced by vlm_Delete(), and vlm_New().