VLC: src/input/vlm_internal.h File Reference
vlm_internal.h File Reference
Data Structures
struct vlm_media_instance_sys_t
struct vlm_media_sys_t
struct vlm_schedule_sys_t
struct vlm_t
Functions
int vlm_ControlInternal (vlm_t *p_vlm, int i_query,...)
int ExecuteCommand (vlm_t *, const char *, vlm_message_t **)
void vlm_ScheduleDelete (vlm_t *vlm, vlm_schedule_sys_t *sched)
Function Documentation
ExecuteCommand()
int ExecuteCommand (vlm_t * , const char * , vlm_message_t **)
Referenced by Manage(), and vlm_ExecuteCommand().
vlm_ControlInternal()
int vlm_ControlInternal (vlm_t * p_vlm, int i_query, ...)
References vlm_vaControlInternal().
Referenced by Manage(), vlm_ControlMediaDel(), vlm_Delete(), and vlm_MediaVodControl().
vlm_ScheduleDelete()
void vlm_ScheduleDelete (vlm_t * vlm, vlm_schedule_sys_t * sched)
Referenced by vlm_ControlScheduleClear().