VLC: src/audio_output/volume.c File Reference
volume.c File Reference
Data Structures
struct aout_volume
Functions
static int ReplayGainCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
aout_volume_t * aout_volume_New (vlc_object_t *parent, const audio_replay_gain_t *gain)
Creates a software amplifier.
int aout_volume_SetFormat (aout_volume_t *vol, vlc_fourcc_t format)
Selects the current sample format for software amplification.
void aout_volume_Delete (aout_volume_t *vol)
Destroys a software amplifier.
void aout_volume_SetVolume (aout_volume_t *vol, float factor)
int aout_volume_Amplify (aout_volume_t *vol, block_t *block)
Applies replay gain and software volume to an audio buffer.
static float aout_ReplayGainSelect (vlc_object_t *obj, const char *str, const audio_replay_gain_t *replay_gain)
Function Documentation
aout_ReplayGainSelect()
static float aout_ReplayGainSelect (vlc_object_t * obj, const char * str, const audio_replay_gain_t * replay_gain) static
References AUDIO_REPLAY_GAIN_ALBUM, AUDIO_REPLAY_GAIN_MAX, AUDIO_REPLAY_GAIN_TRACK, likely, audio_replay_gain_t::pb_gain, audio_replay_gain_t::pb_peak, audio_replay_gain_t::pf_gain, audio_replay_gain_t::pf_peak, var_InheritBool, and var_InheritFloat.
Referenced by ReplayGainCallback().
aout_volume_Amplify()
int aout_volume_Amplify (aout_volume_t * vol, block_t * block)
Applies replay gain and software volume to an audio buffer.
References audio_volume::amplify, aout_volume::gain_factor, aout_volume::module, aout_volume::object, aout_volume::output_factor, unlikely, and vlc_atomic_load_float().
Referenced by aout_DecPlay().
aout_volume_Delete()
void aout_volume_Delete (aout_volume_t * vol)
Destroys a software amplifier.
References aout_volume::module, module_unneed, audio_volume::obj, aout_volume::object, vlc_common_members::parent, ReplayGainCallback(), var_DelCallback, and vlc_object_release.
Referenced by aout_DecDelete(), and aout_DecNew().
aout_volume_New()
aout_volume_t * aout_volume_New (vlc_object_t * parent, const audio_replay_gain_t * gain)
Creates a software amplifier.
References aout_volume::module, aout_volume::output_factor, aout_volume::replay_gain, ReplayGainCallback(), unlikely, var_AddCallback, var_TriggerCallback, and vlc_custom_create.
aout_volume_SetFormat()
int aout_volume_SetFormat (aout_volume_t * vol, vlc_fourcc_t format)
Selects the current sample format for software amplification.
References audio_volume::format, aout_volume::module, module_need, module_unneed, msg_Dbg, aout_volume::object, and unlikely.
Referenced by aout_CheckReady(), and aout_DecNew().
aout_volume_SetVolume()
void aout_volume_SetVolume (aout_volume_t * vol, float factor)
References aout_volume::output_factor, and unlikely.
Referenced by aout_GainNotify().
ReplayGainCallback()
static int ReplayGainCallback (vlc_object_t * obj, char const * var, vlc_value_t oldval, vlc_value_t val, void * data) static
< No error
References aout_ReplayGainSelect(), aout_volume::gain_factor, vlc_value_t::psz_string, aout_volume::replay_gain, vlc_atomic_store_float(), VLC_SUCCESS, and VLC_UNUSED.
Referenced by aout_volume_Delete(), and aout_volume_New().