VLC: src/video_output/vout_control.h File Reference
vout_control.h File Reference
Typedefs
typedef struct vout_window_mouse_event_t vout_window_mouse_event_t
Functions
void vout_ChangePause (vout_thread_t *, bool b_paused, mtime_t i_date)
This function will (un)pause the display of pictures.
void spu_OffsetSubtitleDate (spu_t *p_spu, mtime_t i_duration)
This function will apply an offset on subtitle subpicture.
void vout_GetResetStatistic (vout_thread_t *p_vout, unsigned *pi_displayed, unsigned *pi_lost)
This function will return and reset internal statistics.
void vout_Flush (vout_thread_t *p_vout, mtime_t i_date)
This function will ensure that all ready/displayed pictures have at most the provided date.
void vout_Cancel (vout_thread_t *p_vout, bool b_canceled)
void vout_NextPicture (vout_thread_t *p_vout, mtime_t *pi_duration)
This function will force to display the next picture while paused.
void vout_DisplayTitle (vout_thread_t *p_vout, const char *psz_title)
This function will ask the display of the input title.
void vout_WindowMouseEvent (vout_thread_t *p_vout, const vout_window_mouse_event_t *mouse)
bool vout_IsEmpty (vout_thread_t *p_vout)
This function will return true if no more pictures are to be displayed.
Typedef Documentation
vout_window_mouse_event_t
typedef struct vout_window_mouse_event_t vout_window_mouse_event_t
Function Documentation
spu_OffsetSubtitleDate()
void spu_OffsetSubtitleDate (spu_t * p_spu, mtime_t i_duration)
This function will apply an offset on subtitle subpicture.
References subpicture_t::b_subtitle, spu_heap_t::entry, spu_private_t::heap, subpicture_t::i_start, subpicture_t::i_stop, spu_private_t::lock, spu_t::p, vlc_mutex_lock(), vlc_mutex_unlock(), and VOUT_MAX_SUBPICTURES.
Referenced by ThreadChangePause().
vout_Cancel()
void vout_Cancel (vout_thread_t * p_vout, bool b_canceled)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CANCEL, vout_control_PushBool(), and vout_control_WaitEmpty().
Referenced by decoder_AbortPictures(), DeleteDecoder(), and input_DecoderDelete().
vout_ChangePause()
void vout_ChangePause (vout_thread_t * vout, bool b_paused, mtime_t i_date)
This function will (un)pause the display of pictures.
It is thread safe
References vout_thread_sys_t::control, vout_control_cmd_t::date, vout_control_cmd_t::is_on, vout_thread_t::p, vout_control_cmd_t::pause, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_PAUSE, vout_control_Push(), and vout_control_WaitEmpty().
Referenced by DecoderThread().
vout_DisplayTitle()
void vout_DisplayTitle (vout_thread_t * p_vout, const char * psz_title)
This function will ask the display of the input title.
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_OSD_TITLE, and vout_control_PushString().
Referenced by DisplayVoutTitle().
vout_Flush()
void vout_Flush (vout_thread_t * p_vout, mtime_t i_date)
This function will ensure that all ready/displayed pictures have at most the provided date.
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_FLUSH, vout_control_PushTime(), and vout_control_WaitEmpty().
Referenced by DecoderPlayVideo(), DecoderProcessFlush(), and RequestVout().
vout_GetResetStatistic()
void vout_GetResetStatistic (vout_thread_t * p_vout, unsigned * pi_displayed, unsigned * pi_lost)
This function will return and reset internal statistics.
vout_IsEmpty()
bool vout_IsEmpty (vout_thread_t * p_vout)
This function will return true if no more pictures are to be displayed.
References vout_thread_sys_t::decoder_fifo, vout_thread_t::p, picture_fifo_Peek(), and picture_Release().
Referenced by input_DecoderIsEmpty().
vout_NextPicture()
void vout_NextPicture (vout_thread_t * p_vout, mtime_t * pi_duration)
This function will force to display the next picture while paused.
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::time_ptr, vout_control_cmd_t::u, vout_control_cmd_Init(), vout_control_Push(), VOUT_CONTROL_STEP, and vout_control_WaitEmpty().
Referenced by input_DecoderFrameNext().
vout_WindowMouseEvent()
void vout_WindowMouseEvent (vout_thread_t * p_vout, const vout_window_mouse_event_t * mouse)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_Init(), vout_control_Push(), VOUT_CONTROL_WINDOW_MOUSE, and vout_control_cmd_t::window_mouse.
Referenced by vout_display_window_MouseEvent().