VLC: src/video_output/vout_spuregion_helper.h File Reference
vout_spuregion_helper.h File Reference
Macros
#define RGB2YUV(R, G, B)
#define HEX2YUV(rgb) RGB2YUV((rgb >> 16), ((rgb & 0xFF00) >> 8), (rgb & 0xFF))
Functions
static void spuregion_CreateVGradientPalette (video_palette_t *p_palette, uint8_t i_splits, uint32_t argb1, uint32_t argb2)
static void spuregion_CreateVGradientFill (plane_t *p, uint8_t i_splits)
static subpicture_region_t * spuregion_CreateFromPicture (vlc_object_t *p_this, video_format_t *p_fmt, const char *psz_uri)
Macro Definition Documentation
HEX2YUV
#define HEX2YUV (rgb) RGB2YUV((rgb >> 16), ((rgb & 0xFF00) >> 8), (rgb & 0xFF))
Referenced by vout_OSDEpgSlider().
RGB2YUV
#define RGB2YUV (R, G, B)
Value:
    ((0.257 * R) + (0.504 * G) + (0.098 * B) + 16), \
    (-(0.148 * R) - (0.291 * G) + (0.439 * B) + 128),\
    ((0.439 * R) - (0.368 * G) - (0.071 * B) + 128)
Referenced by spuregion_CreateVGradientPalette().
Function Documentation
spuregion_CreateFromPicture()
static subpicture_region_t * spuregion_CreateFromPicture (vlc_object_t * p_this, video_format_t * p_fmt, const char * psz_uri) inline static
References vlc_common_members::flags, image_HandlerCreate, image_HandlerDelete(), image_ReadUrl, vlc_object_t::obj, OBJECT_FLAGS_NOINTERACT, OBJECT_FLAGS_QUIET, subpicture_region_t::p_picture, picture_Release(), subpicture_region_New(), and video_format_Init().
Referenced by vout_OSDImage().
spuregion_CreateVGradientFill()
static void spuregion_CreateVGradientFill (plane_t * p, uint8_t i_splits) inline static
References p.
Referenced by vout_OSDBackground().
spuregion_CreateVGradientPalette()
static void spuregion_CreateVGradientPalette (video_palette_t * p_palette, uint8_t i_splits, uint32_t argb1, uint32_t argb2) inline static
References video_palette_t::i_entries, video_palette_t::palette, and RGB2YUV.
Referenced by vout_OSDBackground().