VLC: src/video_output/vout_wrapper.c File Reference
vout_wrapper.c File Reference
Macros
#define DISPLAY_PICTURE_COUNT (1)
Functions
int vout_OpenWrapper (vout_thread_t *vout, const char *splitter_name, const vout_display_state_t *state)
void vout_CloseWrapper (vout_thread_t *vout, vout_display_state_t *state)
static void NoDrInit (vout_thread_t *vout)
int vout_InitWrapper (vout_thread_t *vout)
void vout_EndWrapper (vout_thread_t *vout)
void vout_ManageWrapper (vout_thread_t *vout)
Macro Definition Documentation
DISPLAY_PICTURE_COUNT
#define DISPLAY_PICTURE_COUNT (1)
Referenced by vout_InitWrapper().
Function Documentation
NoDrInit()
static void NoDrInit (vout_thread_t * vout) static
References vout_thread_sys_t::display, vout_thread_sys_t::display_pool, vout_thread_t::p, vout_thread_sys_t::use_dr, vout_thread_sys_t::vd, and vout_display_Pool().
Referenced by vout_InitWrapper(), and vout_ManageWrapper().
vout_CloseWrapper()
void vout_CloseWrapper (vout_thread_t * vout, vout_display_state_t * state)
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::title, var_DelCallback, vout_thread_sys_t::vd, and vout_DeleteDisplay().
Referenced by ThreadStart(), and ThreadStop().
vout_EndWrapper()
void vout_EndWrapper (vout_thread_t * vout)
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display_pool, vout_thread_t::p, picture_pool_Release(), and vout_thread_sys_t::private_pool.
Referenced by ThreadStop().
vout_InitWrapper()
int vout_InitWrapper (vout_thread_t * vout)
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, DISPLAY_PICTURE_COUNT, vout_thread_sys_t::display_pool, vout_thread_sys_t::dpb_size, vout_display_info_t::has_pictures_invalid, vout_display_t::info, vout_display_info_t::is_slow, msg_Warn, NoDrInit(), vout_thread_t::p, picture_pool_GetSize(), picture_pool_NewFromFormat(), picture_pool_Release(), picture_pool_Reserve(), vout_thread_sys_t::private_pool, vout_display_t::source, vout_thread_sys_t::use_dr, vout_thread_sys_t::vd, VLC_EGENERIC, VLC_SUCCESS, vout_display_Pool(), vout_IsDisplayFiltered(), and VOUT_MAX_PICTURES.
Referenced by ThreadStart().
vout_ManageWrapper()
void vout_ManageWrapper (vout_thread_t * vout)
References vout_thread_sys_t::display, NoDrInit(), vout_thread_t::p, vout_thread_sys_t::use_dr, vout_thread_sys_t::vd, vout_AreDisplayPicturesInvalid(), vout_IsDisplayFiltered(), and vout_ManageDisplay().
Referenced by Thread().
vout_OpenWrapper()
int vout_OpenWrapper (vout_thread_t * vout, const char * splitter_name, const vout_display_state_t * state)
< Unspecified error
< No error
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, msg_Dbg, vout_thread_sys_t::original, vout_thread_t::p, vout_thread_sys_t::title, var_AddCallback, var_Create, var_CreateGetInteger, var_InheritString, vout_thread_sys_t::vd, VLC_EGENERIC, VLC_SUCCESS, VLC_VAR_BOOL, VLC_VAR_DOINHERIT, vout_NewDisplay(), and vout_NewSplitter().
Referenced by ThreadStart().