VLC: src/video_output/vout_internal.h File Reference
vout_internal.h File Reference
Data Structures
struct vout_thread_sys_t
Macros
#define VOUT_MAX_PICTURES (20)
Functions
void vout_ControlChangeFullscreen (vout_thread_t *, bool fullscreen)
void vout_ControlChangeWindowState (vout_thread_t *, unsigned state)
void vout_ControlChangeDisplayFilled (vout_thread_t *, bool is_filled)
void vout_ControlChangeZoom (vout_thread_t *, int num, int den)
void vout_ControlChangeSampleAspectRatio (vout_thread_t *, unsigned num, unsigned den)
void vout_ControlChangeCropRatio (vout_thread_t *, unsigned num, unsigned den)
void vout_ControlChangeCropWindow (vout_thread_t *, int x, int y, int width, int height)
void vout_ControlChangeCropBorder (vout_thread_t *, int left, int top, int right, int bottom)
void vout_ControlChangeFilters (vout_thread_t *, const char *)
void vout_ControlChangeSubSources (vout_thread_t *, const char *)
void vout_ControlChangeSubFilters (vout_thread_t *, const char *)
void vout_ControlChangeSubMargin (vout_thread_t *, int)
void vout_ControlChangeViewpoint (vout_thread_t *, const vlc_viewpoint_t *)
void vout_IntfInit (vout_thread_t *)
void vout_IntfReinit (vout_thread_t *)
int vout_OpenWrapper (vout_thread_t *, const char *, const vout_display_state_t *)
void vout_CloseWrapper (vout_thread_t *, vout_display_state_t *)
int vout_InitWrapper (vout_thread_t *)
void vout_EndWrapper (vout_thread_t *)
void vout_ManageWrapper (vout_thread_t *)
int spu_ProcessMouse (spu_t *, const vlc_mouse_t *, const video_format_t *)
Inform the SPU filters of mouse event.
void spu_Attach (spu_t *, vlc_object_t *input, bool)
Attach/Detach the SPU from any input.
void spu_ChangeMargin (spu_t *, int)
Macro Definition Documentation
VOUT_MAX_PICTURES
#define VOUT_MAX_PICTURES (20)
Referenced by vout_InitWrapper().
Function Documentation
spu_Attach()
void spu_Attach (spu_t * spu, vlc_object_t * input, bool attach)
Attach/Detach the SPU from any input.
Parameters
p_this the object in which to destroy the subpicture unit
b_attach to select attach or detach
References CropCallback(), FilterRelease(), spu_private_t::input, spu_private_t::lock, spu_t::p, SpuRenderCreateAndLoadText(), spu_private_t::text, UpdateSPU(), var_AddCallback, var_Create, var_DelCallback, var_Destroy, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_VAR_BOOL.
Referenced by vout_Close(), vout_Request(), and VoutCreate().
spu_ChangeMargin()
void spu_ChangeMargin (spu_t * spu, int margin)
References spu_private_t::lock, spu_private_t::margin, spu_t::p, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by ThreadChangeSubMargin().
spu_ProcessMouse()
int spu_ProcessMouse (spu_t * spu, const vlc_mouse_t * mouse, const video_format_t * fmt)
Inform the SPU filters of mouse event.
< No error
References filter_chain_MouseEvent(), spu_t::p, spu_private_t::source_chain, spu_private_t::source_chain_lock, vlc_mutex_lock(), vlc_mutex_unlock(), and VLC_SUCCESS.
Referenced by vout_SendDisplayEventMouse().
vout_CloseWrapper()
void vout_CloseWrapper (vout_thread_t * vout, vout_display_state_t * state)
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, vout_thread_t::p, vout_thread_sys_t::title, var_DelCallback, vout_thread_sys_t::vd, and vout_DeleteDisplay().
Referenced by ThreadStart(), and ThreadStop().
vout_ControlChangeCropBorder()
void vout_ControlChangeCropBorder (vout_thread_t * vout, int left, int top, int right, int bottom)
References vout_control_cmd_t::border, vout_control_cmd_t::bottom, vout_thread_sys_t::control, vout_control_cmd_t::left, vout_thread_t::p, vout_control_cmd_t::right, vout_control_cmd_t::top, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_CROP_BORDER, and vout_control_Push().
Referenced by CropCallback().
vout_ControlChangeCropRatio()
void vout_ControlChangeCropRatio (vout_thread_t * vout, unsigned num, unsigned den)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CROP_RATIO, and vout_control_PushPair().
Referenced by CropCallback().
vout_ControlChangeCropWindow()
void vout_ControlChangeCropWindow (vout_thread_t * vout, int x, int y, int width, int height)
References vout_thread_sys_t::control, vout_control_cmd_t::height, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_Init(), VOUT_CONTROL_CROP_WINDOW, vout_control_Push(), vout_control_cmd_t::width, vout_control_cmd_t::window, vout_control_cmd_t::x, and vout_control_cmd_t::y.
Referenced by CropCallback().
vout_ControlChangeDisplayFilled()
void vout_ControlChangeDisplayFilled (vout_thread_t * vout, bool is_filled)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_DISPLAY_FILLED, and vout_control_PushBool().
Referenced by AutoScaleCallback().
vout_ControlChangeFilters()
void vout_ControlChangeFilters (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_FILTERS, and vout_control_PushString().
Referenced by FilterRestartCallback(), and VideoFilterCallback().
vout_ControlChangeFullscreen()
void vout_ControlChangeFullscreen (vout_thread_t * vout, bool fullscreen)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_FULLSCREEN, and vout_control_PushBool().
Referenced by FullscreenCallback(), and WallPaperCallback().
vout_ControlChangeSampleAspectRatio()
void vout_ControlChangeSampleAspectRatio (vout_thread_t * vout, unsigned num, unsigned den)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_ASPECT_RATIO, and vout_control_PushPair().
Referenced by AspectCallback(), and vout_ChangeAspectRatio().
vout_ControlChangeSubFilters()
void vout_ControlChangeSubFilters (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_FILTERS, and vout_control_PushString().
Referenced by RestartSubFilterCallback(), and SubFilterCallback().
vout_ControlChangeSubMargin()
void vout_ControlChangeSubMargin (vout_thread_t * vout, int margin)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_MARGIN, and vout_control_PushInteger().
Referenced by SubMarginCallback().
vout_ControlChangeSubSources()
void vout_ControlChangeSubSources (vout_thread_t * vout, const char * filters)
References vout_thread_sys_t::control, vout_thread_t::p, VOUT_CONTROL_CHANGE_SUB_SOURCES, and vout_control_PushString().
Referenced by RestartSubSourceCallback(), and SubSourceCallback().
vout_ControlChangeViewpoint()
void vout_ControlChangeViewpoint (vout_thread_t * vout, const vlc_viewpoint_t * p_viewpoint)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_cmd_t::u, vout_control_cmd_t::viewpoint, vout_control_cmd_Init(), vout_control_Push(), and VOUT_CONTROL_VIEWPOINT.
Referenced by ViewpointCallback().
vout_ControlChangeWindowState()
void vout_ControlChangeWindowState (vout_thread_t * vout, unsigned state)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_PushInteger(), and VOUT_CONTROL_WINDOW_STATE.
Referenced by AboveCallback(), and WallPaperCallback().
vout_ControlChangeZoom()
void vout_ControlChangeZoom (vout_thread_t * vout, int num, int den)
References vout_thread_sys_t::control, vout_thread_t::p, vout_control_PushPair(), and VOUT_CONTROL_ZOOM.
Referenced by ZoomCallback().
vout_EndWrapper()
void vout_EndWrapper (vout_thread_t * vout)
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display_pool, vout_thread_t::p, picture_pool_Release(), and vout_thread_sys_t::private_pool.
Referenced by ThreadStop().
vout_InitWrapper()
int vout_InitWrapper (vout_thread_t * vout)
< Unspecified error
< Unspecified error
< Unspecified error
< No error
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, DISPLAY_PICTURE_COUNT, vout_thread_sys_t::display_pool, vout_thread_sys_t::dpb_size, vout_display_info_t::has_pictures_invalid, vout_display_t::info, vout_display_info_t::is_slow, msg_Warn, NoDrInit(), vout_thread_t::p, picture_pool_GetSize(), picture_pool_NewFromFormat(), picture_pool_Release(), picture_pool_Reserve(), vout_thread_sys_t::private_pool, vout_display_t::source, vout_thread_sys_t::use_dr, vout_thread_sys_t::vd, VLC_EGENERIC, VLC_SUCCESS, vout_display_Pool(), vout_IsDisplayFiltered(), and VOUT_MAX_PICTURES.
Referenced by ThreadStart().
vout_IntfInit()
void vout_IntfInit (vout_thread_t * p_vout)
References _, AboveCallback(), AddCustomRatios(), ARRAY_SIZE, AspectCallback(), AutoScaleCallback(), CropBorderCallback(), CropCallback(), vlc_value_t::f_float, FullscreenCallback(), p_aspect_ratio_values, p_crop_values, p_zoom_values, psz_label, vlc_value_t::psz_string, psz_value, SnapshotCallback(), SubFilterCallback(), SubMarginCallback(), SubSourceCallback(), var_AddCallback, var_Change, var_Create, var_CreateGetNonEmptyString, var_SetInteger, VideoFilterCallback(), ViewpointCallback(), vlc_gettext(), VLC_VAR_ADDCHOICE, VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_COORDS, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, VLC_VAR_STRING, VLC_VAR_VOID, vout_IntfReinit(), VOUT_WINDOW_STATE_BELOW, WallPaperCallback(), and ZoomCallback().
Referenced by VoutCreate().
vout_IntfReinit()
void vout_IntfReinit (vout_thread_t * p_vout)
References var_TriggerCallback.
Referenced by vout_IntfInit(), and vout_Request().
vout_ManageWrapper()
void vout_ManageWrapper (vout_thread_t * vout)
References vout_thread_sys_t::display, NoDrInit(), vout_thread_t::p, vout_thread_sys_t::use_dr, vout_thread_sys_t::vd, vout_AreDisplayPicturesInvalid(), vout_IsDisplayFiltered(), and vout_ManageDisplay().
Referenced by Thread().
vout_OpenWrapper()
int vout_OpenWrapper (vout_thread_t * vout, const char * splitter_name, const vout_display_state_t * state)
< Unspecified error
< No error
References vout_thread_sys_t::decoder_pool, vout_thread_sys_t::display, msg_Dbg, vout_thread_sys_t::original, vout_thread_t::p, vout_thread_sys_t::title, var_AddCallback, var_Create, var_CreateGetInteger, var_InheritString, vout_thread_sys_t::vd, VLC_EGENERIC, VLC_SUCCESS, VLC_VAR_BOOL, VLC_VAR_DOINHERIT, vout_NewDisplay(), and vout_NewSplitter().
Referenced by ThreadStart().