VLC: src/video_output/vout_intf.c File Reference
vout_intf.c File Reference
Functions
static int CropCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int CropBorderCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int AspectCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int AutoScaleCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int ZoomCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int AboveCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int WallPaperCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int FullscreenCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int SnapshotCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int VideoFilterCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int SubSourceCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int SubFilterCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int SubMarginCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static int ViewpointCallback (vlc_object_t *, char const *, vlc_value_t, vlc_value_t, void *)
static void AddCustomRatios (vout_thread_t *p_vout, const char *psz_var, char *psz_list)
void vout_IntfInit (vout_thread_t *p_vout)
void vout_IntfReinit (vout_thread_t *p_vout)
static int VoutSnapshotPip (vout_thread_t *p_vout, picture_t *p_pic)
This function will inject a subpicture into the vout with the provided picture.
static void VoutOsdSnapshot (vout_thread_t *p_vout, picture_t *p_pic, const char *psz_filename)
This function will display the name and a PIP of the provided snapshot.
static void VoutSaveSnapshot (vout_thread_t *p_vout)
This function will handle a snapshot request.
Variables
struct {
double f_value
char psz_label [13]
} p_zoom_values []
struct {
char psz_value [8]
char psz_label [8]
} p_crop_values []
struct {
char psz_value [8]
char psz_label [8]
} p_aspect_ratio_values []
Function Documentation
AboveCallback()
static int AboveCallback (vlc_object_t * obj, char const * name, vlc_value_t prev, vlc_value_t cur, void * data) static
< No error
References vlc_value_t::b_bool, name, VLC_SUCCESS, vout_ControlChangeWindowState(), VOUT_WINDOW_STATE_ABOVE, and VOUT_WINDOW_STATE_NORMAL.
Referenced by vout_IntfInit().
AddCustomRatios()
static void AddCustomRatios (vout_thread_t * p_vout, const char * psz_var, char * psz_list) static
References vlc_value_t::psz_string, var_Change, and VLC_VAR_ADDCHOICE.
Referenced by vout_IntfInit().
AspectCallback()
static int AspectCallback (vlc_object_t * object, char const * cmd, vlc_value_t oldval, vlc_value_t newval, void * data) static
< No error
References vlc_value_t::psz_string, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeSampleAspectRatio().
Referenced by vout_IntfInit().
AutoScaleCallback()
static int AutoScaleCallback (vlc_object_t * obj, char const * name, vlc_value_t prev, vlc_value_t cur, void * data) static
< No error
References vlc_value_t::b_bool, name, VLC_SUCCESS, and vout_ControlChangeDisplayFilled().
Referenced by vout_IntfInit().
CropBorderCallback()
static int CropBorderCallback (vlc_object_t * object, char const * cmd, vlc_value_t oldval, vlc_value_t newval, void * data) static
< No error
References var_GetInteger, var_SetString, VLC_SUCCESS, and VLC_UNUSED.
Referenced by vout_IntfInit().
CropCallback()
static int CropCallback (vlc_object_t * object, char const * cmd, vlc_value_t oldval, vlc_value_t newval, void * data) static
< No error
References msg_Err, vlc_value_t::psz_string, VLC_SUCCESS, VLC_UNUSED, vout_ControlChangeCropBorder(), vout_ControlChangeCropRatio(), and vout_ControlChangeCropWindow().
Referenced by vout_IntfInit().
FullscreenCallback()
static int FullscreenCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::b_bool, VLC_SUCCESS, and vout_ControlChangeFullscreen().
Referenced by vout_IntfInit().
SnapshotCallback()
static int SnapshotCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References VLC_SUCCESS, VLC_UNUSED, and VoutSaveSnapshot().
Referenced by vout_IntfInit().
SubFilterCallback()
static int SubFilterCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::psz_string, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeSubFilters().
Referenced by vout_IntfInit().
SubMarginCallback()
static int SubMarginCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::i_int, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeSubMargin().
Referenced by vout_IntfInit().
SubSourceCallback()
static int SubSourceCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::psz_string, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeSubSources().
Referenced by vout_IntfInit().
VideoFilterCallback()
static int VideoFilterCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::psz_string, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeFilters().
Referenced by vout_IntfInit().
ViewpointCallback()
static int ViewpointCallback (vlc_object_t * p_this, char const * psz_cmd, vlc_value_t oldval, vlc_value_t newval, void * p_data) static
< No error
References vlc_value_t::p_address, VLC_SUCCESS, VLC_UNUSED, and vout_ControlChangeViewpoint().
Referenced by vout_IntfInit().
vout_IntfInit()
void vout_IntfInit (vout_thread_t * p_vout)
References _, AboveCallback(), AddCustomRatios(), ARRAY_SIZE, AspectCallback(), AutoScaleCallback(), CropBorderCallback(), CropCallback(), vlc_value_t::f_float, FullscreenCallback(), p_aspect_ratio_values, p_crop_values, p_zoom_values, psz_label, vlc_value_t::psz_string, psz_value, SnapshotCallback(), SubFilterCallback(), SubMarginCallback(), SubSourceCallback(), var_AddCallback, var_Change, var_Create, var_CreateGetNonEmptyString, var_SetInteger, VideoFilterCallback(), ViewpointCallback(), vlc_gettext(), VLC_VAR_ADDCHOICE, VLC_VAR_ADDRESS, VLC_VAR_BOOL, VLC_VAR_COORDS, VLC_VAR_DOINHERIT, VLC_VAR_FLOAT, VLC_VAR_INTEGER, VLC_VAR_ISCOMMAND, VLC_VAR_SETTEXT, VLC_VAR_STRING, VLC_VAR_VOID, vout_IntfReinit(), VOUT_WINDOW_STATE_BELOW, WallPaperCallback(), and ZoomCallback().
Referenced by VoutCreate().
vout_IntfReinit()
void vout_IntfReinit (vout_thread_t * p_vout)
References var_TriggerCallback.
Referenced by vout_IntfInit(), and vout_Request().
VoutOsdSnapshot()
static void VoutOsdSnapshot (vout_thread_t * p_vout, picture_t * p_pic, const char * psz_filename) static
This function will display the name and a PIP of the provided snapshot.
References msg_Dbg, msg_Warn, var_InheritBool, vout_OSDMessage(), VOUT_SPU_CHANNEL_OSD, and VoutSnapshotPip().
Referenced by VoutSaveSnapshot().
VoutSaveSnapshot()
static void VoutSaveSnapshot (vout_thread_t * p_vout) static
This function will handle a snapshot request.
References block_Release(), vout_snapshot_save_cfg_t::format, vout_snapshot_save_cfg_t::is_sequential, vlc_common_members::libvlc, msg_Err, vout_thread_t::obj, vout_snapshot_save_cfg_t::path, picture_Release(), vout_snapshot_save_cfg_t::prefix_fmt, vout_snapshot_save_cfg_t::sequence, var_GetInteger, var_InheritBool, var_InheritString, var_SetInteger, var_SetString, vout_GetSnapshot(), vout_snapshot_GetDirectory(), vout_snapshot_SaveImage(), and VoutOsdSnapshot().
Referenced by SnapshotCallback().
VoutSnapshotPip()
static int VoutSnapshotPip (vout_thread_t * p_vout, picture_t * p_pic) static
This function will inject a subpicture into the vout with the provided picture.
< Unspecified error
< No error
References subpicture_t::b_ephemer, subpicture_t::b_fade, subpicture_t::i_channel, subpicture_t::i_original_picture_height, subpicture_t::i_original_picture_width, subpicture_t::i_start, subpicture_t::i_stop, mdate(), subpicture_NewFromPicture(), VLC_CODEC_YUVA, VLC_EGENERIC, VLC_OBJECT, VLC_SUCCESS, and vout_PutSubpicture().
Referenced by VoutOsdSnapshot().
WallPaperCallback()
static int WallPaperCallback (vlc_object_t * obj, char const * name, vlc_value_t prev, vlc_value_t cur, void * data) static
< No error
References vlc_value_t::b_bool, name, var_TriggerCallback, VLC_SUCCESS, vout_ControlChangeFullscreen(), vout_ControlChangeWindowState(), and VOUT_WINDOW_STATE_BELOW.
Referenced by vout_IntfInit().
ZoomCallback()
static int ZoomCallback (vlc_object_t * obj, char const * name, vlc_value_t prev, vlc_value_t cur, void * data) static
< No error
References vlc_value_t::f_float, name, VLC_SUCCESS, and vout_ControlChangeZoom().
Referenced by vout_IntfInit().
Variable Documentation
f_value
double f_value
Referenced by config_PutFloat(), dialog_update_progress(), vlc_dialog_update_progress(), vlc_dialog_update_progress_text(), and vlc_dialog_update_progress_text_va().
[struct]
const struct { ... } p_aspect_ratio_values[]
Initial value:
= {
    { "", N_("Default") },
    { "16:9", "16:9" },
    { "4:3", "4:3" },
    { "1:1", "1:1" },
    { "16:10", "16:10" },
    { "221:100", "2.21:1" },
    { "235:100", "2.35:1" },
    { "239:100", "2.39:1" },
    { "5:4", "5:4" },
}
Referenced by vout_IntfInit().
[struct]
const struct { ... } p_crop_values[]
Initial value:
= {
    { "", N_("Default") },
    { "16:10", "16:10" },
    { "16:9", "16:9" },
    { "4:3", "4:3" },
    { "185:100", "1.85:1" },
    { "221:100", "2.21:1" },
    { "235:100", "2.35:1" },
    { "239:100", "2.39:1" },
    { "5:3", "5:3" },
    { "5:4", "5:4" },
    { "1:1", "1:1" },
}
Referenced by vout_IntfInit().
[struct]
const struct { ... } p_zoom_values[]
Initial value:
= {
    { 0.25, N_("1:4 Quarter") },
    { 0.5, N_("1:2 Half") },
    { 1, N_("1:1 Original") },
    { 2, N_("2:1 Double") },
}
Referenced by vout_IntfInit().
psz_label
char psz_label[8]
Referenced by vlc_credential_store(), vlc_keystore_store(), and vout_IntfInit().
psz_value
char psz_value[8]
Referenced by ChainGetValue(), config_GetPsz(), config_PutPsz(), config_SaveConfigFile(), EsOutUpdateInfo(), httpd_MsgAdd(), input_vaControl(), var_OptionParse(), vlc_audio_replay_gain_MergeFromMeta(), vlc_html_color(), vlc_meta_AddExtra(), vlc_xml_decode(), and vout_IntfInit().