VLC: src/win32/filesystem.c File Reference
filesystem.c File Reference
Macros
#define CONVERT_PATH(path, wpath, err)
Functions
static wchar_t * widen_path (const char *path)
int vlc_open (const char *filename, int flags,...)
Opens a system file handle.
int vlc_openat (int dir, const char *filename, int flags,...)
Opens a system file handle relative to an existing directory handle.
int vlc_memfd (void)
Creates an anonymous regular file descriptor, i.e.
int vlc_close (int fd)
Closes a file descriptor.
int vlc_mkdir (const char *dirname, mode_t mode)
Creates a directory.
char * vlc_getcwd (void)
Determines the current working directory.
DIR * vlc_opendir (const char *dirname)
Opens a DIR pointer.
const char * vlc_readdir (DIR *dir)
Reads the next file name from an open directory.
int vlc_stat (const char *filename, struct stat *buf)
Finds file/inode information - like stat().
int vlc_lstat (const char *filename, struct stat *buf)
Finds file/inode information, as lstat().
int vlc_unlink (const char *filename)
Removes a file.
int vlc_rename (const char *oldpath, const char *newpath)
Moves a file atomically.
int vlc_dup (int oldfd)
Duplicates a file descriptor.
int vlc_pipe (int fds[2])
Creates a pipe (see "man pipe" for further reference).
ssize_t vlc_write (int fd, const void *buf, size_t len)
Writes data to a file descriptor.
ssize_t vlc_writev (int fd, const struct iovec *iov, int count)
Writes data from an iovec structure to a file descriptor.
int vlc_socket (int pf, int type, int proto, bool nonblock)
Creates a socket file descriptor.
int vlc_socketpair (int pf, int type, int proto, int fds[2], bool nonblock)
Creates a pair of socket file descriptors.
int vlc_accept (int lfd, struct sockaddr *addr, socklen_t *alen, bool nonblock)
Accepts an inbound connection request on a listening socket.
FILE * vlc_win32_tmpfile (void)
Macro Definition Documentation
CONVERT_PATH
#define CONVERT_PATH (path, wpath, err)
Value:
    wchar_t *wpath = wide_path(path); \
    if (wpath == NULL) return (err)
Function Documentation
vlc_win32_tmpfile()
FILE * vlc_win32_tmpfile (void)
widen_path()
static wchar_t * widen_path (const char * path) static
Referenced by vlc_mkdir(), vlc_open(), vlc_opendir(), vlc_rename(), vlc_stat(), and vlc_unlink().