VLC: src/win32/specific.c File Reference
specific.c File Reference
Data Structures
struct vlc_ipc_data_t
Macros
#define UNICODE
Functions
static int system_InitWSA (int hi, int lo)
void system_Init (void)
Initializes MME timer, Winsock.
void system_Configure (libvlc_int_t *p_this, int i_argc, const char *const ppsz_argv[])
void system_End (void)
Cleans up after system_Init() and system_Configure().
Variables
DWORD LoadLibraryFlags = 0
Macro Definition Documentation
UNICODE
#define UNICODE
Function Documentation
system_Configure()
void system_Configure (libvlc_int_t * p_this, int i_argc, const char *const ppsz_argv[])
References vlc_ipc_data_t::argc, vlc_ipc_data_t::data, vlc_ipc_data_t::enqueue, libvlc_InternalAddIntf(), msg_Err, msg_Info, system_End(), and var_InheritBool.
system_End()
void system_End (void)
Cleans up after system_Init() and system_Configure().
system_Init()
void system_Init (void)
Initializes MME timer, Winsock.
References LoadLibraryFlags, and system_InitWSA().
system_InitWSA()
static int system_InitWSA (int hi, int lo) static
Referenced by system_Init().
Variable Documentation
LoadLibraryFlags
DWORD LoadLibraryFlags = 0
Referenced by module_Load(), and system_Init().