VLC: src/win32/dirs.c File Reference
dirs.c File Reference
Macros
#define COBJMACROS
#define INITGUID
#define UNICODE
Functions
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
char * config_GetDataDir (void)
Determines the shared data directory.
static char * config_GetShellDir (int csidl)
static char * config_GetAppDir (void)
char * config_GetUserDir (vlc_userdir_t type)
Macro Definition Documentation
COBJMACROS
#define COBJMACROS
INITGUID
#define INITGUID
UNICODE
#define UNICODE
Function Documentation
config_GetAppDir()
static char * config_GetAppDir (void) static
References asprintf(), and config_GetShellDir().
Referenced by config_GetUserDir().
config_GetDataDir()
char * config_GetDataDir (void)
Determines the shared data directory.
Returns
a nul-terminated string or NULL. Use free() to release it.
References config_GetLibDir(), getenv(), and strdup().
config_GetLibDir()
char * config_GetLibDir (void)
Determines the architecture-dependent data directory.
Returns
a string (always succeeds).
References config_GetLibDir().
config_GetShellDir()
static char * config_GetShellDir (int csidl) static
Referenced by config_GetAppDir(), and config_GetUserDir().
config_GetUserDir()
char * config_GetUserDir (vlc_userdir_t type)
References config_GetAppDir(), config_GetShellDir(), config_GetUserDir(), vlc_assert_unreachable, VLC_CACHE_DIR, VLC_CONFIG_DIR, VLC_DATA_DIR, VLC_DESKTOP_DIR, VLC_DOCUMENTS_DIR, VLC_DOWNLOAD_DIR, VLC_HOME_DIR, VLC_MUSIC_DIR, VLC_PICTURES_DIR, VLC_PUBLICSHARE_DIR, VLC_TEMPLATES_DIR, and VLC_VIDEOS_DIR.