VLC: src/video_output/window.c File Reference
window.c File Reference
Data Structures
struct window_t
struct vout_display_window
Typedefs
typedef struct vout_display_window vout_display_window_t
Functions
static int vout_window_start (void *func, va_list ap)
vout_window_t * vout_window_New (vlc_object_t *obj, const char *module, const vout_window_cfg_t *cfg, const vout_window_owner_t *owner)
Creates a new window.
static void vout_window_stop (void *func, va_list ap)
void vout_window_Delete (vout_window_t *window)
Deletes a window created by vout_window_New().
void vout_window_SetInhibition (vout_window_t *window, bool enabled)
static void vout_display_window_ResizeNotify (vout_window_t *window, unsigned width, unsigned height)
static void vout_display_window_CloseNotify (vout_window_t *window)
static void vout_display_window_MouseEvent (vout_window_t *window, const vout_window_mouse_event_t *mouse)
vout_window_t * vout_display_window_New (vout_thread_t *vout, const vout_window_cfg_t *cfg)
Creates a video window, initially without any attached display.
void vout_display_window_Attach (vout_window_t *window, vout_display_t *vd)
Attaches a window to a display.
void vout_display_window_Detach (vout_window_t *window)
Detaches a window from a display.
void vout_display_window_Delete (vout_window_t *window)
Destroys a video window.
Typedef Documentation
vout_display_window_t
typedef struct vout_display_window vout_display_window_t
Function Documentation
vout_display_window_Attach()
void vout_display_window_Attach (vout_window_t * window, vout_display_t * vd)
Attaches a window to a display.
Window events will be dispatched to the display until they are detached.
References vout_display_t::cfg, vout_display_cfg_t::display, vout_display_cfg_t::height, vout_display_window::height, vout_display_window::lock, vout_window_t::owner, vout_window_owner::sys, vout_display_window::vd, vlc_mutex_lock(), vlc_mutex_unlock(), vout_display_SendEventDisplaySize(), vout_window_SetSize(), vout_display_cfg_t::width, and vout_display_window::width.
Referenced by SplitterNewWindow(), and VoutDisplayNewWindow().
vout_display_window_CloseNotify()
static void vout_display_window_CloseNotify (vout_window_t * window) static
References vout_window_t::obj, vlc_common_members::parent, and vout_SendEventClose().
Referenced by vout_display_window_New().
vout_display_window_Delete()
void vout_display_window_Delete (vout_window_t * window)
Destroys a video window.
Note
The window must be detached.
References vout_display_window::lock, vout_window_t::owner, vout_window_owner::sys, vout_display_window::vd, vlc_mutex_destroy(), and vout_window_Delete().
Referenced by SplitterDelWindow(), vout_Close(), vout_DeleteDisplayWindow(), and VoutCreate().
vout_display_window_Detach()
void vout_display_window_Detach (vout_window_t * window)
Detaches a window from a display.
Window events will no longer be dispatched (except those that do not need a display).
References vout_display_window::lock, vout_window_t::owner, vout_window_owner::sys, vout_display_window::vd, vlc_mutex_lock(), and vlc_mutex_unlock().
Referenced by SplitterDelWindow(), and VoutDisplayDelWindow().
vout_display_window_MouseEvent()
static void vout_display_window_MouseEvent (vout_window_t * window, const vout_window_mouse_event_t * mouse) static
References vout_window_t::obj, vlc_common_members::parent, and vout_WindowMouseEvent().
Referenced by vout_display_window_New().
vout_display_window_New()
vout_window_t * vout_display_window_New (vout_thread_t * vout, const vout_window_cfg_t * cfg)
Creates a video window, initially without any attached display.
References vout_display_window::height, vout_window_cfg_t::height, vout_display_window::lock, vout_window_owner::sys, vout_display_window::vd, vlc_mutex_destroy(), vlc_mutex_init(), vout_display_window_CloseNotify(), vout_display_window_MouseEvent(), vout_display_window_ResizeNotify(), vout_window_New(), vout_display_window::width, and vout_window_cfg_t::width.
Referenced by SplitterNewWindow(), and VoutCreate().
vout_display_window_ResizeNotify()
static void vout_display_window_ResizeNotify (vout_window_t * window, unsigned width, unsigned height) static
References vout_display_window::height, vout_display_window::lock, msg_Dbg, vout_window_t::owner, vout_window_owner::sys, vout_display_window::vd, vlc_mutex_lock(), vlc_mutex_unlock(), vout_display_SendEventDisplaySize(), and vout_display_window::width.
Referenced by vout_display_window_New().
vout_window_start()
static int vout_window_start (void * func, va_list ap) static
Referenced by vout_window_New().
vout_window_stop()
static void vout_window_stop (void * func, va_list ap) static
Referenced by vout_window_Delete().